ltm profile client-ssl /EVTFLOW_EFB/__tcl_lsp_evtflow_EFB_http2_clientssl {
    defaults-from /Common/clientssl
    renegotiation disabled
}
ltm pool /EVTFLOW_EFB/__tcl_lsp_evtflow_EFB_http2_pool {
    members {
        /EVTFLOW_EFB/__tcl_lsp_evtflow_EFB_node:18603 { address 192.168.9.80 }
    }
}
ltm virtual /EVTFLOW_EFB/__tcl_lsp_evtflow_EFB_http2_vs {
    destination 192.168.9.24:18503
    ip-protocol tcp
    mask 255.255.255.255
    pool /EVTFLOW_EFB/__tcl_lsp_evtflow_EFB_http2_pool
    profiles {
        /EVTFLOW_EFB/__tcl_lsp_evtflow_EFB_http2_clientssl { context clientside }
        /Common/http { }
        /Common/http2 { context clientside }
        /Common/tcp { }
    }
    rules { /Common/__tcl_lsp_evtflow_EFB_http_trace /Common/__tcl_lsp_evtflow_EFB_clientssl_trace /Common/__tcl_lsp_evtflow_EFB_priority_100 /Common/__tcl_lsp_evtflow_EFB_priority_300 /Common/__tcl_lsp_evtflow_EFB_priority_500 /Common/__tcl_lsp_evtflow_EFB_priority_700 /Common/__tcl_lsp_evtflow_EFB_priority_900 }
    source 0.0.0.0/0
    source-address-translation { type automap }
}
