/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 123
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 68
#define ALIAS_COUNT 0
#define TOKEN_COUNT 37
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 13
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 13
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  aux_sym_include_token1 = 2,
  sym_comment = 3,
  anon_sym_define = 4,
  anon_sym_section = 5,
  anon_sym_text = 6,
  anon_sym_LBRACE = 7,
  anon_sym_RBRACE = 8,
  anon_sym_table = 9,
  anon_sym_message = 10,
  anon_sym_optional = 11,
  anon_sym_LPAREN = 12,
  anon_sym_RPAREN = 13,
  anon_sym_EQ_EQ = 14,
  anon_sym_BANG_EQ = 15,
  anon_sym_AMP_AMP = 16,
  anon_sym_PIPE_PIPE = 17,
  anon_sym_LT_EQ = 18,
  anon_sym_GT_EQ = 19,
  anon_sym_LT = 20,
  anon_sym_GT = 21,
  anon_sym_default = 22,
  anon_sym_display = 23,
  anon_sym_validator = 24,
  anon_sym_required = 25,
  anon_sym_COMMA = 26,
  anon_sym_EQ_GT = 27,
  anon_sym_LBRACK = 28,
  anon_sym_RBRACK = 29,
  aux_sym__tcl_token_token1 = 30,
  anon_sym_DOT = 31,
  sym_variable_substitution = 32,
  anon_sym_DQUOTE = 33,
  aux_sym_string_token1 = 34,
  sym_escape_sequence = 35,
  sym_number = 36,
  sym_source_file = 37,
  sym__declaration = 38,
  sym_include = 39,
  sym_define = 40,
  sym_section = 41,
  sym_text_block = 42,
  sym_text_body = 43,
  sym_text_entry = 44,
  sym_table = 45,
  sym_block = 46,
  sym__block_item = 47,
  sym_message_field = 48,
  sym_optional_block = 49,
  sym__expression = 50,
  sym_binary_expression = 51,
  sym_field = 52,
  sym_attribute = 53,
  sym_choice_list = 54,
  sym_choice_mapping = 55,
  sym_tcl_expression = 56,
  sym__tcl_token = 57,
  sym_dotted_name = 58,
  sym_string = 59,
  aux_sym_source_file_repeat1 = 60,
  aux_sym_text_body_repeat1 = 61,
  aux_sym_block_repeat1 = 62,
  aux_sym_field_repeat1 = 63,
  aux_sym_choice_list_repeat1 = 64,
  aux_sym_tcl_expression_repeat1 = 65,
  aux_sym_dotted_name_repeat1 = 66,
  aux_sym_string_repeat1 = 67,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [aux_sym_include_token1] = "directive",
  [sym_comment] = "comment",
  [anon_sym_define] = "define",
  [anon_sym_section] = "section",
  [anon_sym_text] = "text",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_table] = "table",
  [anon_sym_message] = "message",
  [anon_sym_optional] = "optional",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_AMP_AMP] = "&&",
  [anon_sym_PIPE_PIPE] = "||",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_default] = "default",
  [anon_sym_display] = "display",
  [anon_sym_validator] = "validator",
  [anon_sym_required] = "required",
  [anon_sym_COMMA] = ",",
  [anon_sym_EQ_GT] = "=>",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [aux_sym__tcl_token_token1] = "_tcl_token_token1",
  [anon_sym_DOT] = ".",
  [sym_variable_substitution] = "variable_substitution",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [sym_escape_sequence] = "escape_sequence",
  [sym_number] = "number",
  [sym_source_file] = "source_file",
  [sym__declaration] = "_declaration",
  [sym_include] = "include",
  [sym_define] = "define",
  [sym_section] = "section",
  [sym_text_block] = "text_block",
  [sym_text_body] = "text_body",
  [sym_text_entry] = "text_entry",
  [sym_table] = "table",
  [sym_block] = "block",
  [sym__block_item] = "_block_item",
  [sym_message_field] = "message_field",
  [sym_optional_block] = "optional_block",
  [sym__expression] = "_expression",
  [sym_binary_expression] = "binary_expression",
  [sym_field] = "field",
  [sym_attribute] = "attribute",
  [sym_choice_list] = "choice_list",
  [sym_choice_mapping] = "choice_mapping",
  [sym_tcl_expression] = "tcl_expression",
  [sym__tcl_token] = "_tcl_token",
  [sym_dotted_name] = "dotted_name",
  [sym_string] = "string",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_text_body_repeat1] = "text_body_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
  [aux_sym_field_repeat1] = "field_repeat1",
  [aux_sym_choice_list_repeat1] = "choice_list_repeat1",
  [aux_sym_tcl_expression_repeat1] = "tcl_expression_repeat1",
  [aux_sym_dotted_name_repeat1] = "dotted_name_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [aux_sym_include_token1] = aux_sym_include_token1,
  [sym_comment] = sym_comment,
  [anon_sym_define] = anon_sym_define,
  [anon_sym_section] = anon_sym_section,
  [anon_sym_text] = anon_sym_text,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_table] = anon_sym_table,
  [anon_sym_message] = anon_sym_message,
  [anon_sym_optional] = anon_sym_optional,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_AMP_AMP] = anon_sym_AMP_AMP,
  [anon_sym_PIPE_PIPE] = anon_sym_PIPE_PIPE,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_default] = anon_sym_default,
  [anon_sym_display] = anon_sym_display,
  [anon_sym_validator] = anon_sym_validator,
  [anon_sym_required] = anon_sym_required,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_EQ_GT] = anon_sym_EQ_GT,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [aux_sym__tcl_token_token1] = aux_sym__tcl_token_token1,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_variable_substitution] = sym_variable_substitution,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym_number] = sym_number,
  [sym_source_file] = sym_source_file,
  [sym__declaration] = sym__declaration,
  [sym_include] = sym_include,
  [sym_define] = sym_define,
  [sym_section] = sym_section,
  [sym_text_block] = sym_text_block,
  [sym_text_body] = sym_text_body,
  [sym_text_entry] = sym_text_entry,
  [sym_table] = sym_table,
  [sym_block] = sym_block,
  [sym__block_item] = sym__block_item,
  [sym_message_field] = sym_message_field,
  [sym_optional_block] = sym_optional_block,
  [sym__expression] = sym__expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym_field] = sym_field,
  [sym_attribute] = sym_attribute,
  [sym_choice_list] = sym_choice_list,
  [sym_choice_mapping] = sym_choice_mapping,
  [sym_tcl_expression] = sym_tcl_expression,
  [sym__tcl_token] = sym__tcl_token,
  [sym_dotted_name] = sym_dotted_name,
  [sym_string] = sym_string,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_text_body_repeat1] = aux_sym_text_body_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
  [aux_sym_field_repeat1] = aux_sym_field_repeat1,
  [aux_sym_choice_list_repeat1] = aux_sym_choice_list_repeat1,
  [aux_sym_tcl_expression_repeat1] = aux_sym_tcl_expression_repeat1,
  [aux_sym_dotted_name_repeat1] = aux_sym_dotted_name_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_include_token1] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_define] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_section] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_text] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_table] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_message] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_optional] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_default] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_display] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_validator] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_required] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__tcl_token_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_variable_substitution] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__declaration] = {
    .visible = false,
    .named = true,
  },
  [sym_include] = {
    .visible = true,
    .named = true,
  },
  [sym_define] = {
    .visible = true,
    .named = true,
  },
  [sym_section] = {
    .visible = true,
    .named = true,
  },
  [sym_text_block] = {
    .visible = true,
    .named = true,
  },
  [sym_text_body] = {
    .visible = true,
    .named = true,
  },
  [sym_text_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_table] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym__block_item] = {
    .visible = false,
    .named = true,
  },
  [sym_message_field] = {
    .visible = true,
    .named = true,
  },
  [sym_optional_block] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_field] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_choice_list] = {
    .visible = true,
    .named = true,
  },
  [sym_choice_mapping] = {
    .visible = true,
    .named = true,
  },
  [sym_tcl_expression] = {
    .visible = true,
    .named = true,
  },
  [sym__tcl_token] = {
    .visible = false,
    .named = true,
  },
  [sym_dotted_name] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_text_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_field_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_choice_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tcl_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_dotted_name_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_body = 1,
  field_condition = 2,
  field_directive = 3,
  field_label = 4,
  field_left = 5,
  field_locale = 6,
  field_name = 7,
  field_operator = 8,
  field_right = 9,
  field_target = 10,
  field_text = 11,
  field_type = 12,
  field_value = 13,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_body] = "body",
  [field_condition] = "condition",
  [field_directive] = "directive",
  [field_label] = "label",
  [field_left] = "left",
  [field_locale] = "locale",
  [field_name] = "name",
  [field_operator] = "operator",
  [field_right] = "right",
  [field_target] = "target",
  [field_text] = "text",
  [field_type] = "type",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 2},
  [5] = {.index = 5, .length = 2},
  [6] = {.index = 7, .length = 2},
  [7] = {.index = 9, .length = 2},
  [8] = {.index = 11, .length = 2},
  [9] = {.index = 13, .length = 1},
  [10] = {.index = 14, .length = 2},
  [11] = {.index = 16, .length = 2},
  [12] = {.index = 18, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_directive, 0},
  [1] =
    {field_body, 1},
  [2] =
    {field_text, 1},
  [3] =
    {field_name, 1},
    {field_type, 0},
  [5] =
    {field_name, 2},
    {field_type, 1},
  [7] =
    {field_body, 2},
    {field_name, 1},
  [9] =
    {field_body, 2},
    {field_locale, 1},
  [11] =
    {field_label, 1},
    {field_target, 0},
  [13] =
    {field_value, 1},
  [14] =
    {field_label, 0},
    {field_value, 2},
  [16] =
    {field_body, 4},
    {field_condition, 2},
  [18] =
    {field_left, 0},
    {field_operator, 1},
    {field_right, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 6,
  [10] = 7,
  [11] = 11,
  [12] = 2,
  [13] = 3,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 8,
  [18] = 18,
  [19] = 11,
  [20] = 15,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 16,
  [25] = 25,
  [26] = 14,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 36,
  [52] = 52,
  [53] = 37,
  [54] = 45,
  [55] = 50,
  [56] = 56,
  [57] = 34,
  [58] = 58,
  [59] = 35,
  [60] = 46,
  [61] = 38,
  [62] = 41,
  [63] = 40,
  [64] = 64,
  [65] = 42,
  [66] = 56,
  [67] = 52,
  [68] = 68,
  [69] = 69,
  [70] = 68,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 71,
  [77] = 75,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 80,
  [82] = 78,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 31,
  [88] = 88,
  [89] = 33,
  [90] = 86,
  [91] = 84,
  [92] = 88,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 96,
  [101] = 95,
  [102] = 99,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 105,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 109,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 115,
  [120] = 120,
  [121] = 118,
  [122] = 114,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(17);
      ADVANCE_MAP(
        '!', 9,
        '"', 54,
        '#', 24,
        '$', 7,
        '&', 4,
        '(', 33,
        ')', 34,
        ',', 43,
        '.', 50,
        '0', 69,
        '<', 41,
        '=', 10,
        '>', 42,
        '[', 45,
        '\\', 11,
        ']', 46,
        '{', 31,
        '|', 12,
        '}', 32,
        '+', 6,
        '-', 6,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(70);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '"', 54,
        '#', 30,
        '$', 7,
        '.', 14,
        '0', 69,
        '[', 45,
        '+', 6,
        '-', 6,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(70);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(54);
      if (lookahead == '#') ADVANCE(20);
      if (lookahead == '$') ADVANCE(7);
      if (lookahead == '\\') ADVANCE(11);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(55);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(56);
      END_STATE();
    case 3:
      if (lookahead == '#') ADVANCE(19);
      if (lookahead == '[') ADVANCE(45);
      if (lookahead == ']') ADVANCE(46);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(47);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(48);
      END_STATE();
    case 4:
      if (lookahead == '&') ADVANCE(37);
      END_STATE();
    case 5:
      if (lookahead == ')') ADVANCE(51);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '.') ADVANCE(14);
      if (lookahead == '0') ADVANCE(69);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(70);
      END_STATE();
    case 7:
      if (lookahead == ':') ADVANCE(8);
      if (lookahead == '{') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 8:
      if (lookahead == ':') ADVANCE(52);
      END_STATE();
    case 9:
      if (lookahead == '=') ADVANCE(36);
      END_STATE();
    case 10:
      if (lookahead == '=') ADVANCE(35);
      if (lookahead == '>') ADVANCE(44);
      END_STATE();
    case 11:
      if (lookahead == 'U') ADVANCE(67);
      if (lookahead == 'u') ADVANCE(63);
      if (lookahead == 'x') ADVANCE(61);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(59);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(57);
      END_STATE();
    case 12:
      if (lookahead == '|') ADVANCE(38);
      END_STATE();
    case 13:
      if (lookahead == '}') ADVANCE(51);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(13);
      END_STATE();
    case 14:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(71);
      END_STATE();
    case 15:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(72);
      END_STATE();
    case 16:
      if (eof) ADVANCE(17);
      ADVANCE_MAP(
        '!', 9,
        '"', 54,
        '#', 30,
        '&', 4,
        '(', 33,
        ')', 34,
        ',', 43,
        '.', 49,
        '<', 41,
        '=', 10,
        '>', 42,
        '{', 31,
        '|', 12,
        '}', 32,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(16);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_include_token1);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\n') ADVANCE(48);
      if (lookahead == '[' ||
          lookahead == ']') ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\n') ADVANCE(56);
      if (lookahead == '"' ||
          lookahead == '$' ||
          lookahead == '\\') ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 'c') ADVANCE(26);
      if (lookahead == 'l') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(30);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 'd') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(30);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 'e') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(30);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 'i') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(30);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 'i') ADVANCE(28);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(30);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 'l') ADVANCE(29);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(30);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 'n') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(30);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 'n') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(30);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 'u') ADVANCE(22);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(30);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_AMP_AMP);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_PIPE_PIPE);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(39);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(40);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_EQ_GT);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym__tcl_token_token1);
      if (lookahead == '#') ADVANCE(19);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(47);
      if (lookahead != 0 &&
          lookahead != '[' &&
          lookahead != ']' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(48);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym__tcl_token_token1);
      if (lookahead != 0 &&
          lookahead != '[' &&
          lookahead != ']' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(48);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_DOT);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(71);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_variable_substitution);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_variable_substitution);
      if (lookahead == '(') ADVANCE(5);
      if (lookahead == ':') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '#') ADVANCE(20);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(55);
      if (lookahead != 0 &&
          (lookahead < '"' || '$' < lookahead) &&
          lookahead != '\\' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(56);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '$' &&
          lookahead != '\\' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(56);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_escape_sequence);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(57);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_escape_sequence);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(58);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_escape_sequence);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(57);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_escape_sequence);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(60);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_escape_sequence);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(61);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_escape_sequence);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(62);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_escape_sequence);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(63);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_escape_sequence);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(64);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_escape_sequence);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(65);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_escape_sequence);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(66);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_number);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(14);
      if (lookahead == 'f') ADVANCE(68);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(70);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(14);
      if (lookahead == 'f') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(70);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'f') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(71);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(72);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'd') ADVANCE(1);
      if (lookahead == 'm') ADVANCE(2);
      if (lookahead == 'o') ADVANCE(3);
      if (lookahead == 'r') ADVANCE(4);
      if (lookahead == 's') ADVANCE(5);
      if (lookahead == 't') ADVANCE(6);
      if (lookahead == 'v') ADVANCE(7);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'e') ADVANCE(8);
      if (lookahead == 'i') ADVANCE(9);
      END_STATE();
    case 2:
      if (lookahead == 'e') ADVANCE(10);
      END_STATE();
    case 3:
      if (lookahead == 'p') ADVANCE(11);
      END_STATE();
    case 4:
      if (lookahead == 'e') ADVANCE(12);
      END_STATE();
    case 5:
      if (lookahead == 'e') ADVANCE(13);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(14);
      if (lookahead == 'e') ADVANCE(15);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(16);
      END_STATE();
    case 8:
      if (lookahead == 'f') ADVANCE(17);
      END_STATE();
    case 9:
      if (lookahead == 's') ADVANCE(18);
      END_STATE();
    case 10:
      if (lookahead == 's') ADVANCE(19);
      END_STATE();
    case 11:
      if (lookahead == 't') ADVANCE(20);
      END_STATE();
    case 12:
      if (lookahead == 'q') ADVANCE(21);
      END_STATE();
    case 13:
      if (lookahead == 'c') ADVANCE(22);
      END_STATE();
    case 14:
      if (lookahead == 'b') ADVANCE(23);
      END_STATE();
    case 15:
      if (lookahead == 'x') ADVANCE(24);
      END_STATE();
    case 16:
      if (lookahead == 'l') ADVANCE(25);
      END_STATE();
    case 17:
      if (lookahead == 'a') ADVANCE(26);
      if (lookahead == 'i') ADVANCE(27);
      END_STATE();
    case 18:
      if (lookahead == 'p') ADVANCE(28);
      END_STATE();
    case 19:
      if (lookahead == 's') ADVANCE(29);
      END_STATE();
    case 20:
      if (lookahead == 'i') ADVANCE(30);
      END_STATE();
    case 21:
      if (lookahead == 'u') ADVANCE(31);
      END_STATE();
    case 22:
      if (lookahead == 't') ADVANCE(32);
      END_STATE();
    case 23:
      if (lookahead == 'l') ADVANCE(33);
      END_STATE();
    case 24:
      if (lookahead == 't') ADVANCE(34);
      END_STATE();
    case 25:
      if (lookahead == 'i') ADVANCE(35);
      END_STATE();
    case 26:
      if (lookahead == 'u') ADVANCE(36);
      END_STATE();
    case 27:
      if (lookahead == 'n') ADVANCE(37);
      END_STATE();
    case 28:
      if (lookahead == 'l') ADVANCE(38);
      END_STATE();
    case 29:
      if (lookahead == 'a') ADVANCE(39);
      END_STATE();
    case 30:
      if (lookahead == 'o') ADVANCE(40);
      END_STATE();
    case 31:
      if (lookahead == 'i') ADVANCE(41);
      END_STATE();
    case 32:
      if (lookahead == 'i') ADVANCE(42);
      END_STATE();
    case 33:
      if (lookahead == 'e') ADVANCE(43);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_text);
      END_STATE();
    case 35:
      if (lookahead == 'd') ADVANCE(44);
      END_STATE();
    case 36:
      if (lookahead == 'l') ADVANCE(45);
      END_STATE();
    case 37:
      if (lookahead == 'e') ADVANCE(46);
      END_STATE();
    case 38:
      if (lookahead == 'a') ADVANCE(47);
      END_STATE();
    case 39:
      if (lookahead == 'g') ADVANCE(48);
      END_STATE();
    case 40:
      if (lookahead == 'n') ADVANCE(49);
      END_STATE();
    case 41:
      if (lookahead == 'r') ADVANCE(50);
      END_STATE();
    case 42:
      if (lookahead == 'o') ADVANCE(51);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_table);
      END_STATE();
    case 44:
      if (lookahead == 'a') ADVANCE(52);
      END_STATE();
    case 45:
      if (lookahead == 't') ADVANCE(53);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_define);
      END_STATE();
    case 47:
      if (lookahead == 'y') ADVANCE(54);
      END_STATE();
    case 48:
      if (lookahead == 'e') ADVANCE(55);
      END_STATE();
    case 49:
      if (lookahead == 'a') ADVANCE(56);
      END_STATE();
    case 50:
      if (lookahead == 'e') ADVANCE(57);
      END_STATE();
    case 51:
      if (lookahead == 'n') ADVANCE(58);
      END_STATE();
    case 52:
      if (lookahead == 't') ADVANCE(59);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_default);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_display);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_message);
      END_STATE();
    case 56:
      if (lookahead == 'l') ADVANCE(60);
      END_STATE();
    case 57:
      if (lookahead == 'd') ADVANCE(61);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_section);
      END_STATE();
    case 59:
      if (lookahead == 'o') ADVANCE(62);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_optional);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_required);
      END_STATE();
    case 62:
      if (lookahead == 'r') ADVANCE(63);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_validator);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 16},
  [3] = {.lex_state = 16},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 16},
  [10] = {.lex_state = 16},
  [11] = {.lex_state = 16},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 16},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 16},
  [18] = {.lex_state = 16},
  [19] = {.lex_state = 16},
  [20] = {.lex_state = 16},
  [21] = {.lex_state = 16},
  [22] = {.lex_state = 16},
  [23] = {.lex_state = 16},
  [24] = {.lex_state = 16},
  [25] = {.lex_state = 16},
  [26] = {.lex_state = 16},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 16},
  [31] = {.lex_state = 16},
  [32] = {.lex_state = 16},
  [33] = {.lex_state = 16},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 16},
  [52] = {.lex_state = 3},
  [53] = {.lex_state = 16},
  [54] = {.lex_state = 16},
  [55] = {.lex_state = 16},
  [56] = {.lex_state = 3},
  [57] = {.lex_state = 16},
  [58] = {.lex_state = 3},
  [59] = {.lex_state = 16},
  [60] = {.lex_state = 16},
  [61] = {.lex_state = 16},
  [62] = {.lex_state = 16},
  [63] = {.lex_state = 16},
  [64] = {.lex_state = 16},
  [65] = {.lex_state = 16},
  [66] = {.lex_state = 3},
  [67] = {.lex_state = 3},
  [68] = {.lex_state = 2},
  [69] = {.lex_state = 2},
  [70] = {.lex_state = 2},
  [71] = {.lex_state = 2},
  [72] = {.lex_state = 16},
  [73] = {.lex_state = 16},
  [74] = {.lex_state = 16},
  [75] = {.lex_state = 16},
  [76] = {.lex_state = 2},
  [77] = {.lex_state = 16},
  [78] = {.lex_state = 16},
  [79] = {.lex_state = 16},
  [80] = {.lex_state = 16},
  [81] = {.lex_state = 16},
  [82] = {.lex_state = 16},
  [83] = {.lex_state = 16},
  [84] = {.lex_state = 16},
  [85] = {.lex_state = 16},
  [86] = {.lex_state = 1},
  [87] = {.lex_state = 3},
  [88] = {.lex_state = 16},
  [89] = {.lex_state = 3},
  [90] = {.lex_state = 1},
  [91] = {.lex_state = 16},
  [92] = {.lex_state = 16},
  [93] = {.lex_state = 16},
  [94] = {.lex_state = 16},
  [95] = {.lex_state = 16},
  [96] = {.lex_state = 16},
  [97] = {.lex_state = 16},
  [98] = {.lex_state = 16},
  [99] = {.lex_state = 16},
  [100] = {.lex_state = 16},
  [101] = {.lex_state = 16},
  [102] = {.lex_state = 16},
  [103] = {.lex_state = 16},
  [104] = {.lex_state = 16},
  [105] = {.lex_state = 16},
  [106] = {.lex_state = 16},
  [107] = {.lex_state = 16},
  [108] = {.lex_state = 16},
  [109] = {.lex_state = 16},
  [110] = {.lex_state = 16},
  [111] = {.lex_state = 16},
  [112] = {.lex_state = 16},
  [113] = {.lex_state = 16},
  [114] = {.lex_state = 16},
  [115] = {.lex_state = 16},
  [116] = {.lex_state = 16},
  [117] = {.lex_state = 16},
  [118] = {.lex_state = 16},
  [119] = {.lex_state = 16},
  [120] = {.lex_state = 16},
  [121] = {.lex_state = 16},
  [122] = {.lex_state = 16},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [aux_sym_include_token1] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_define] = ACTIONS(1),
    [anon_sym_section] = ACTIONS(1),
    [anon_sym_text] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_table] = ACTIONS(1),
    [anon_sym_message] = ACTIONS(1),
    [anon_sym_optional] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_AMP_AMP] = ACTIONS(1),
    [anon_sym_PIPE_PIPE] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_default] = ACTIONS(1),
    [anon_sym_display] = ACTIONS(1),
    [anon_sym_validator] = ACTIONS(1),
    [anon_sym_required] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_EQ_GT] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym_variable_substitution] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(112),
    [sym__declaration] = STATE(4),
    [sym_include] = STATE(4),
    [sym_define] = STATE(4),
    [sym_section] = STATE(4),
    [sym_text_block] = STATE(4),
    [sym_table] = STATE(4),
    [sym_message_field] = STATE(4),
    [sym_field] = STATE(4),
    [aux_sym_source_file_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [aux_sym_include_token1] = ACTIONS(9),
    [sym_comment] = ACTIONS(3),
    [anon_sym_define] = ACTIONS(11),
    [anon_sym_section] = ACTIONS(13),
    [anon_sym_text] = ACTIONS(15),
    [anon_sym_table] = ACTIONS(17),
    [anon_sym_message] = ACTIONS(19),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(21), 11,
      anon_sym_section,
      anon_sym_table,
      anon_sym_message,
      anon_sym_optional,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_default,
      anon_sym_display,
      anon_sym_validator,
      anon_sym_required,
      sym_identifier,
    ACTIONS(25), 11,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_COMMA,
      anon_sym_EQ_GT,
  [30] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(27), 11,
      anon_sym_section,
      anon_sym_table,
      anon_sym_message,
      anon_sym_optional,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_default,
      anon_sym_display,
      anon_sym_validator,
      anon_sym_required,
      sym_identifier,
    ACTIONS(29), 11,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_COMMA,
      anon_sym_EQ_GT,
  [60] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      aux_sym_include_token1,
    ACTIONS(11), 1,
      anon_sym_define,
    ACTIONS(13), 1,
      anon_sym_section,
    ACTIONS(15), 1,
      anon_sym_text,
    ACTIONS(17), 1,
      anon_sym_table,
    ACTIONS(19), 1,
      anon_sym_message,
    ACTIONS(31), 1,
      ts_builtin_sym_end,
    STATE(5), 9,
      sym__declaration,
      sym_include,
      sym_define,
      sym_section,
      sym_text_block,
      sym_table,
      sym_message_field,
      sym_field,
      aux_sym_source_file_repeat1,
  [99] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 1,
      ts_builtin_sym_end,
    ACTIONS(35), 1,
      sym_identifier,
    ACTIONS(38), 1,
      aux_sym_include_token1,
    ACTIONS(41), 1,
      anon_sym_define,
    ACTIONS(44), 1,
      anon_sym_section,
    ACTIONS(47), 1,
      anon_sym_text,
    ACTIONS(50), 1,
      anon_sym_table,
    ACTIONS(53), 1,
      anon_sym_message,
    STATE(5), 9,
      sym__declaration,
      sym_include,
      sym_define,
      sym_section,
      sym_text_block,
      sym_table,
      sym_message_field,
      sym_field,
      aux_sym_source_file_repeat1,
  [138] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(60), 1,
      anon_sym_LBRACE,
    ACTIONS(62), 1,
      anon_sym_default,
    ACTIONS(66), 1,
      anon_sym_required,
    STATE(42), 1,
      sym_choice_list,
    ACTIONS(56), 2,
      ts_builtin_sym_end,
      aux_sym_include_token1,
    ACTIONS(64), 2,
      anon_sym_display,
      anon_sym_validator,
    STATE(7), 2,
      sym_attribute,
      aux_sym_field_repeat1,
    ACTIONS(58), 6,
      anon_sym_define,
      anon_sym_section,
      anon_sym_text,
      anon_sym_table,
      anon_sym_message,
      sym_identifier,
  [174] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(60), 1,
      anon_sym_LBRACE,
    ACTIONS(62), 1,
      anon_sym_default,
    ACTIONS(66), 1,
      anon_sym_required,
    STATE(34), 1,
      sym_choice_list,
    ACTIONS(64), 2,
      anon_sym_display,
      anon_sym_validator,
    ACTIONS(68), 2,
      ts_builtin_sym_end,
      aux_sym_include_token1,
    STATE(8), 2,
      sym_attribute,
      aux_sym_field_repeat1,
    ACTIONS(70), 6,
      anon_sym_define,
      anon_sym_section,
      anon_sym_text,
      anon_sym_table,
      anon_sym_message,
      sym_identifier,
  [210] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(76), 1,
      anon_sym_default,
    ACTIONS(82), 1,
      anon_sym_required,
    ACTIONS(79), 2,
      anon_sym_display,
      anon_sym_validator,
    STATE(8), 2,
      sym_attribute,
      aux_sym_field_repeat1,
    ACTIONS(72), 3,
      ts_builtin_sym_end,
      aux_sym_include_token1,
      anon_sym_LBRACE,
    ACTIONS(74), 6,
      anon_sym_define,
      anon_sym_section,
      anon_sym_text,
      anon_sym_table,
      anon_sym_message,
      sym_identifier,
  [241] = 9,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(56), 1,
      anon_sym_RBRACE,
    ACTIONS(85), 1,
      anon_sym_LBRACE,
    ACTIONS(87), 1,
      anon_sym_default,
    ACTIONS(91), 1,
      anon_sym_required,
    STATE(65), 1,
      sym_choice_list,
    ACTIONS(89), 2,
      anon_sym_display,
      anon_sym_validator,
    STATE(10), 2,
      sym_attribute,
      aux_sym_field_repeat1,
    ACTIONS(58), 5,
      anon_sym_section,
      anon_sym_table,
      anon_sym_message,
      anon_sym_optional,
      sym_identifier,
  [275] = 9,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(68), 1,
      anon_sym_RBRACE,
    ACTIONS(85), 1,
      anon_sym_LBRACE,
    ACTIONS(87), 1,
      anon_sym_default,
    ACTIONS(91), 1,
      anon_sym_required,
    STATE(57), 1,
      sym_choice_list,
    ACTIONS(89), 2,
      anon_sym_display,
      anon_sym_validator,
    STATE(17), 2,
      sym_attribute,
      aux_sym_field_repeat1,
    ACTIONS(70), 5,
      anon_sym_section,
      anon_sym_table,
      anon_sym_message,
      anon_sym_optional,
      sym_identifier,
  [309] = 8,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(93), 1,
      sym_identifier,
    ACTIONS(95), 1,
      anon_sym_section,
    ACTIONS(97), 1,
      anon_sym_RBRACE,
    ACTIONS(99), 1,
      anon_sym_table,
    ACTIONS(101), 1,
      anon_sym_message,
    ACTIONS(103), 1,
      anon_sym_optional,
    STATE(15), 7,
      sym_section,
      sym_table,
      sym__block_item,
      sym_message_field,
      sym_optional_block,
      sym_field,
      aux_sym_block_repeat1,
  [340] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 3,
      ts_builtin_sym_end,
      aux_sym_include_token1,
      anon_sym_LBRACE,
    ACTIONS(21), 10,
      anon_sym_define,
      anon_sym_section,
      anon_sym_text,
      anon_sym_table,
      anon_sym_message,
      anon_sym_default,
      anon_sym_display,
      anon_sym_validator,
      anon_sym_required,
      sym_identifier,
  [361] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(29), 3,
      ts_builtin_sym_end,
      aux_sym_include_token1,
      anon_sym_LBRACE,
    ACTIONS(27), 10,
      anon_sym_define,
      anon_sym_section,
      anon_sym_text,
      anon_sym_table,
      anon_sym_message,
      anon_sym_default,
      anon_sym_display,
      anon_sym_validator,
      anon_sym_required,
      sym_identifier,
  [382] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 3,
      ts_builtin_sym_end,
      aux_sym_include_token1,
      anon_sym_LBRACE,
    ACTIONS(107), 10,
      anon_sym_define,
      anon_sym_section,
      anon_sym_text,
      anon_sym_table,
      anon_sym_message,
      anon_sym_default,
      anon_sym_display,
      anon_sym_validator,
      anon_sym_required,
      sym_identifier,
  [403] = 8,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(93), 1,
      sym_identifier,
    ACTIONS(95), 1,
      anon_sym_section,
    ACTIONS(99), 1,
      anon_sym_table,
    ACTIONS(101), 1,
      anon_sym_message,
    ACTIONS(103), 1,
      anon_sym_optional,
    ACTIONS(109), 1,
      anon_sym_RBRACE,
    STATE(18), 7,
      sym_section,
      sym_table,
      sym__block_item,
      sym_message_field,
      sym_optional_block,
      sym_field,
      aux_sym_block_repeat1,
  [434] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 3,
      ts_builtin_sym_end,
      aux_sym_include_token1,
      anon_sym_LBRACE,
    ACTIONS(113), 10,
      anon_sym_define,
      anon_sym_section,
      anon_sym_text,
      anon_sym_table,
      anon_sym_message,
      anon_sym_default,
      anon_sym_display,
      anon_sym_validator,
      anon_sym_required,
      sym_identifier,
  [455] = 7,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(115), 1,
      anon_sym_default,
    ACTIONS(121), 1,
      anon_sym_required,
    ACTIONS(72), 2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(118), 2,
      anon_sym_display,
      anon_sym_validator,
    STATE(17), 2,
      sym_attribute,
      aux_sym_field_repeat1,
    ACTIONS(74), 5,
      anon_sym_section,
      anon_sym_table,
      anon_sym_message,
      anon_sym_optional,
      sym_identifier,
  [484] = 8,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(124), 1,
      sym_identifier,
    ACTIONS(127), 1,
      anon_sym_section,
    ACTIONS(130), 1,
      anon_sym_RBRACE,
    ACTIONS(132), 1,
      anon_sym_table,
    ACTIONS(135), 1,
      anon_sym_message,
    ACTIONS(138), 1,
      anon_sym_optional,
    STATE(18), 7,
      sym_section,
      sym_table,
      sym__block_item,
      sym_message_field,
      sym_optional_block,
      sym_field,
      aux_sym_block_repeat1,
  [515] = 8,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(93), 1,
      sym_identifier,
    ACTIONS(95), 1,
      anon_sym_section,
    ACTIONS(99), 1,
      anon_sym_table,
    ACTIONS(101), 1,
      anon_sym_message,
    ACTIONS(103), 1,
      anon_sym_optional,
    ACTIONS(141), 1,
      anon_sym_RBRACE,
    STATE(20), 7,
      sym_section,
      sym_table,
      sym__block_item,
      sym_message_field,
      sym_optional_block,
      sym_field,
      aux_sym_block_repeat1,
  [546] = 8,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(93), 1,
      sym_identifier,
    ACTIONS(95), 1,
      anon_sym_section,
    ACTIONS(99), 1,
      anon_sym_table,
    ACTIONS(101), 1,
      anon_sym_message,
    ACTIONS(103), 1,
      anon_sym_optional,
    ACTIONS(143), 1,
      anon_sym_RBRACE,
    STATE(18), 7,
      sym_section,
      sym_table,
      sym__block_item,
      sym_message_field,
      sym_optional_block,
      sym_field,
      aux_sym_block_repeat1,
  [577] = 5,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(149), 1,
      anon_sym_DOT,
    STATE(22), 1,
      aux_sym_dotted_name_repeat1,
    ACTIONS(147), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(145), 8,
      anon_sym_RPAREN,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_DQUOTE,
  [601] = 5,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(149), 1,
      anon_sym_DOT,
    STATE(23), 1,
      aux_sym_dotted_name_repeat1,
    ACTIONS(153), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(151), 8,
      anon_sym_RPAREN,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_DQUOTE,
  [625] = 5,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(159), 1,
      anon_sym_DOT,
    STATE(23), 1,
      aux_sym_dotted_name_repeat1,
    ACTIONS(157), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(155), 8,
      anon_sym_RPAREN,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_DQUOTE,
  [649] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(111), 2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(113), 9,
      anon_sym_section,
      anon_sym_table,
      anon_sym_message,
      anon_sym_optional,
      anon_sym_default,
      anon_sym_display,
      anon_sym_validator,
      anon_sym_required,
      sym_identifier,
  [668] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(157), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(155), 9,
      anon_sym_RPAREN,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_DOT,
      anon_sym_DQUOTE,
  [687] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(105), 2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(107), 9,
      anon_sym_section,
      anon_sym_table,
      anon_sym_message,
      anon_sym_optional,
      anon_sym_default,
      anon_sym_display,
      anon_sym_validator,
      anon_sym_required,
      sym_identifier,
  [706] = 6,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(162), 1,
      sym_identifier,
    ACTIONS(164), 1,
      anon_sym_LBRACK,
    ACTIONS(168), 1,
      anon_sym_DQUOTE,
    ACTIONS(166), 2,
      sym_variable_substitution,
      sym_number,
    STATE(30), 5,
      sym__expression,
      sym_binary_expression,
      sym_tcl_expression,
      sym_dotted_name,
      sym_string,
  [730] = 6,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(162), 1,
      sym_identifier,
    ACTIONS(164), 1,
      anon_sym_LBRACK,
    ACTIONS(168), 1,
      anon_sym_DQUOTE,
    ACTIONS(170), 2,
      sym_variable_substitution,
      sym_number,
    STATE(32), 5,
      sym__expression,
      sym_binary_expression,
      sym_tcl_expression,
      sym_dotted_name,
      sym_string,
  [754] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(60), 1,
      anon_sym_LBRACE,
    STATE(44), 1,
      sym_choice_list,
    ACTIONS(172), 2,
      ts_builtin_sym_end,
      aux_sym_include_token1,
    ACTIONS(174), 6,
      anon_sym_define,
      anon_sym_section,
      anon_sym_text,
      anon_sym_table,
      anon_sym_message,
      sym_identifier,
  [776] = 4,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(176), 1,
      anon_sym_RPAREN,
    ACTIONS(180), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(178), 6,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [795] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(184), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(182), 7,
      anon_sym_RPAREN,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [812] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(188), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(186), 7,
      anon_sym_RPAREN,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [829] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(192), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(190), 7,
      anon_sym_RPAREN,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [846] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(194), 2,
      ts_builtin_sym_end,
      aux_sym_include_token1,
    ACTIONS(196), 6,
      anon_sym_define,
      anon_sym_section,
      anon_sym_text,
      anon_sym_table,
      anon_sym_message,
      sym_identifier,
  [862] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(198), 2,
      ts_builtin_sym_end,
      aux_sym_include_token1,
    ACTIONS(200), 6,
      anon_sym_define,
      anon_sym_section,
      anon_sym_text,
      anon_sym_table,
      anon_sym_message,
      sym_identifier,
  [878] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(202), 2,
      ts_builtin_sym_end,
      aux_sym_include_token1,
    ACTIONS(204), 6,
      anon_sym_define,
      anon_sym_section,
      anon_sym_text,
      anon_sym_table,
      anon_sym_message,
      sym_identifier,
  [894] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(206), 2,
      ts_builtin_sym_end,
      aux_sym_include_token1,
    ACTIONS(208), 6,
      anon_sym_define,
      anon_sym_section,
      anon_sym_text,
      anon_sym_table,
      anon_sym_message,
      sym_identifier,
  [910] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(210), 2,
      ts_builtin_sym_end,
      aux_sym_include_token1,
    ACTIONS(212), 6,
      anon_sym_define,
      anon_sym_section,
      anon_sym_text,
      anon_sym_table,
      anon_sym_message,
      sym_identifier,
  [926] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(214), 2,
      ts_builtin_sym_end,
      aux_sym_include_token1,
    ACTIONS(216), 6,
      anon_sym_define,
      anon_sym_section,
      anon_sym_text,
      anon_sym_table,
      anon_sym_message,
      sym_identifier,
  [942] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(218), 2,
      ts_builtin_sym_end,
      aux_sym_include_token1,
    ACTIONS(220), 6,
      anon_sym_define,
      anon_sym_section,
      anon_sym_text,
      anon_sym_table,
      anon_sym_message,
      sym_identifier,
  [958] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(222), 2,
      ts_builtin_sym_end,
      aux_sym_include_token1,
    ACTIONS(224), 6,
      anon_sym_define,
      anon_sym_section,
      anon_sym_text,
      anon_sym_table,
      anon_sym_message,
      sym_identifier,
  [974] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 2,
      ts_builtin_sym_end,
      aux_sym_include_token1,
    ACTIONS(70), 6,
      anon_sym_define,
      anon_sym_section,
      anon_sym_text,
      anon_sym_table,
      anon_sym_message,
      sym_identifier,
  [990] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(226), 2,
      ts_builtin_sym_end,
      aux_sym_include_token1,
    ACTIONS(228), 6,
      anon_sym_define,
      anon_sym_section,
      anon_sym_text,
      anon_sym_table,
      anon_sym_message,
      sym_identifier,
  [1006] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(230), 2,
      ts_builtin_sym_end,
      aux_sym_include_token1,
    ACTIONS(232), 6,
      anon_sym_define,
      anon_sym_section,
      anon_sym_text,
      anon_sym_table,
      anon_sym_message,
      sym_identifier,
  [1022] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 2,
      ts_builtin_sym_end,
      aux_sym_include_token1,
    ACTIONS(236), 6,
      anon_sym_define,
      anon_sym_section,
      anon_sym_text,
      anon_sym_table,
      anon_sym_message,
      sym_identifier,
  [1038] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(238), 2,
      ts_builtin_sym_end,
      aux_sym_include_token1,
    ACTIONS(240), 6,
      anon_sym_define,
      anon_sym_section,
      anon_sym_text,
      anon_sym_table,
      anon_sym_message,
      sym_identifier,
  [1054] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(242), 2,
      ts_builtin_sym_end,
      aux_sym_include_token1,
    ACTIONS(244), 6,
      anon_sym_define,
      anon_sym_section,
      anon_sym_text,
      anon_sym_table,
      anon_sym_message,
      sym_identifier,
  [1070] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(246), 2,
      ts_builtin_sym_end,
      aux_sym_include_token1,
    ACTIONS(248), 6,
      anon_sym_define,
      anon_sym_section,
      anon_sym_text,
      anon_sym_table,
      anon_sym_message,
      sym_identifier,
  [1086] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(250), 2,
      ts_builtin_sym_end,
      aux_sym_include_token1,
    ACTIONS(252), 6,
      anon_sym_define,
      anon_sym_section,
      anon_sym_text,
      anon_sym_table,
      anon_sym_message,
      sym_identifier,
  [1102] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(254), 2,
      ts_builtin_sym_end,
      aux_sym_include_token1,
    ACTIONS(256), 6,
      anon_sym_define,
      anon_sym_section,
      anon_sym_text,
      anon_sym_table,
      anon_sym_message,
      sym_identifier,
  [1118] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(202), 1,
      anon_sym_RBRACE,
    ACTIONS(204), 5,
      anon_sym_section,
      anon_sym_table,
      anon_sym_message,
      anon_sym_optional,
      sym_identifier,
  [1132] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(258), 1,
      anon_sym_LBRACK,
    ACTIONS(260), 1,
      anon_sym_RBRACK,
    ACTIONS(262), 1,
      aux_sym__tcl_token_token1,
    STATE(58), 3,
      sym_tcl_expression,
      sym__tcl_token,
      aux_sym_tcl_expression_repeat1,
  [1150] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(206), 1,
      anon_sym_RBRACE,
    ACTIONS(208), 5,
      anon_sym_section,
      anon_sym_table,
      anon_sym_message,
      anon_sym_optional,
      sym_identifier,
  [1164] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(234), 1,
      anon_sym_RBRACE,
    ACTIONS(236), 5,
      anon_sym_section,
      anon_sym_table,
      anon_sym_message,
      anon_sym_optional,
      sym_identifier,
  [1178] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(254), 1,
      anon_sym_RBRACE,
    ACTIONS(256), 5,
      anon_sym_section,
      anon_sym_table,
      anon_sym_message,
      anon_sym_optional,
      sym_identifier,
  [1192] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(258), 1,
      anon_sym_LBRACK,
    ACTIONS(264), 1,
      anon_sym_RBRACK,
    ACTIONS(266), 1,
      aux_sym__tcl_token_token1,
    STATE(52), 3,
      sym_tcl_expression,
      sym__tcl_token,
      aux_sym_tcl_expression_repeat1,
  [1210] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(194), 1,
      anon_sym_RBRACE,
    ACTIONS(196), 5,
      anon_sym_section,
      anon_sym_table,
      anon_sym_message,
      anon_sym_optional,
      sym_identifier,
  [1224] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(268), 1,
      anon_sym_LBRACK,
    ACTIONS(271), 1,
      anon_sym_RBRACK,
    ACTIONS(273), 1,
      aux_sym__tcl_token_token1,
    STATE(58), 3,
      sym_tcl_expression,
      sym__tcl_token,
      aux_sym_tcl_expression_repeat1,
  [1242] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(198), 1,
      anon_sym_RBRACE,
    ACTIONS(200), 5,
      anon_sym_section,
      anon_sym_table,
      anon_sym_message,
      anon_sym_optional,
      sym_identifier,
  [1256] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(238), 1,
      anon_sym_RBRACE,
    ACTIONS(240), 5,
      anon_sym_section,
      anon_sym_table,
      anon_sym_message,
      anon_sym_optional,
      sym_identifier,
  [1270] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(210), 1,
      anon_sym_RBRACE,
    ACTIONS(212), 5,
      anon_sym_section,
      anon_sym_table,
      anon_sym_message,
      anon_sym_optional,
      sym_identifier,
  [1284] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(222), 1,
      anon_sym_RBRACE,
    ACTIONS(224), 5,
      anon_sym_section,
      anon_sym_table,
      anon_sym_message,
      anon_sym_optional,
      sym_identifier,
  [1298] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(218), 1,
      anon_sym_RBRACE,
    ACTIONS(220), 5,
      anon_sym_section,
      anon_sym_table,
      anon_sym_message,
      anon_sym_optional,
      sym_identifier,
  [1312] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(278), 1,
      anon_sym_RBRACE,
    ACTIONS(276), 5,
      anon_sym_section,
      anon_sym_table,
      anon_sym_message,
      anon_sym_optional,
      sym_identifier,
  [1326] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(68), 1,
      anon_sym_RBRACE,
    ACTIONS(70), 5,
      anon_sym_section,
      anon_sym_table,
      anon_sym_message,
      anon_sym_optional,
      sym_identifier,
  [1340] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(258), 1,
      anon_sym_LBRACK,
    ACTIONS(280), 1,
      anon_sym_RBRACK,
    ACTIONS(282), 1,
      aux_sym__tcl_token_token1,
    STATE(67), 3,
      sym_tcl_expression,
      sym__tcl_token,
      aux_sym_tcl_expression_repeat1,
  [1358] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(258), 1,
      anon_sym_LBRACK,
    ACTIONS(262), 1,
      aux_sym__tcl_token_token1,
    ACTIONS(284), 1,
      anon_sym_RBRACK,
    STATE(58), 3,
      sym_tcl_expression,
      sym__tcl_token,
      aux_sym_tcl_expression_repeat1,
  [1376] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(288), 1,
      anon_sym_DQUOTE,
    STATE(76), 1,
      aux_sym_string_repeat1,
    ACTIONS(286), 3,
      sym_variable_substitution,
      aux_sym_string_token1,
      sym_escape_sequence,
  [1391] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(293), 1,
      anon_sym_DQUOTE,
    STATE(69), 1,
      aux_sym_string_repeat1,
    ACTIONS(290), 3,
      sym_variable_substitution,
      aux_sym_string_token1,
      sym_escape_sequence,
  [1406] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(297), 1,
      anon_sym_DQUOTE,
    STATE(71), 1,
      aux_sym_string_repeat1,
    ACTIONS(295), 3,
      sym_variable_substitution,
      aux_sym_string_token1,
      sym_escape_sequence,
  [1421] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(301), 1,
      anon_sym_DQUOTE,
    STATE(69), 1,
      aux_sym_string_repeat1,
    ACTIONS(299), 3,
      sym_variable_substitution,
      aux_sym_string_token1,
      sym_escape_sequence,
  [1436] = 5,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(303), 1,
      sym_identifier,
    ACTIONS(306), 1,
      anon_sym_RBRACE,
    STATE(94), 1,
      sym_dotted_name,
    STATE(72), 2,
      sym_text_entry,
      aux_sym_text_body_repeat1,
  [1453] = 5,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(162), 1,
      sym_identifier,
    ACTIONS(308), 1,
      anon_sym_RBRACE,
    STATE(94), 1,
      sym_dotted_name,
    STATE(72), 2,
      sym_text_entry,
      aux_sym_text_body_repeat1,
  [1470] = 5,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(162), 1,
      sym_identifier,
    ACTIONS(310), 1,
      anon_sym_RBRACE,
    STATE(94), 1,
      sym_dotted_name,
    STATE(73), 2,
      sym_text_entry,
      aux_sym_text_body_repeat1,
  [1487] = 6,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(168), 1,
      anon_sym_DQUOTE,
    ACTIONS(312), 1,
      anon_sym_RBRACE,
    ACTIONS(314), 1,
      anon_sym_COMMA,
    STATE(84), 1,
      sym_choice_mapping,
    STATE(116), 1,
      sym_string,
  [1506] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(316), 1,
      anon_sym_DQUOTE,
    STATE(69), 1,
      aux_sym_string_repeat1,
    ACTIONS(299), 3,
      sym_variable_substitution,
      aux_sym_string_token1,
      sym_escape_sequence,
  [1521] = 6,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(168), 1,
      anon_sym_DQUOTE,
    ACTIONS(318), 1,
      anon_sym_RBRACE,
    ACTIONS(320), 1,
      anon_sym_COMMA,
    STATE(91), 1,
      sym_choice_mapping,
    STATE(116), 1,
      sym_string,
  [1540] = 5,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(168), 1,
      anon_sym_DQUOTE,
    ACTIONS(322), 1,
      anon_sym_RBRACE,
    STATE(93), 1,
      sym_choice_mapping,
    STATE(116), 1,
      sym_string,
  [1556] = 5,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(168), 1,
      anon_sym_DQUOTE,
    ACTIONS(324), 1,
      anon_sym_LBRACE,
    STATE(47), 1,
      sym_text_body,
    STATE(108), 1,
      sym_string,
  [1572] = 5,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(168), 1,
      anon_sym_DQUOTE,
    ACTIONS(326), 1,
      anon_sym_RBRACE,
    STATE(93), 1,
      sym_choice_mapping,
    STATE(116), 1,
      sym_string,
  [1588] = 5,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(168), 1,
      anon_sym_DQUOTE,
    ACTIONS(328), 1,
      anon_sym_RBRACE,
    STATE(93), 1,
      sym_choice_mapping,
    STATE(116), 1,
      sym_string,
  [1604] = 5,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(168), 1,
      anon_sym_DQUOTE,
    ACTIONS(330), 1,
      anon_sym_RBRACE,
    STATE(93), 1,
      sym_choice_mapping,
    STATE(116), 1,
      sym_string,
  [1620] = 4,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(332), 1,
      anon_sym_RBRACE,
    ACTIONS(334), 1,
      anon_sym_COMMA,
    STATE(83), 1,
      aux_sym_choice_list_repeat1,
  [1633] = 4,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(337), 1,
      anon_sym_RBRACE,
    ACTIONS(339), 1,
      anon_sym_COMMA,
    STATE(88), 1,
      aux_sym_choice_list_repeat1,
  [1646] = 4,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(168), 1,
      anon_sym_DQUOTE,
    STATE(93), 1,
      sym_choice_mapping,
    STATE(116), 1,
      sym_string,
  [1659] = 4,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(341), 1,
      anon_sym_DQUOTE,
    ACTIONS(343), 1,
      sym_number,
    STATE(16), 1,
      sym_string,
  [1672] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(184), 3,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      aux_sym__tcl_token_token1,
  [1681] = 4,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(326), 1,
      anon_sym_RBRACE,
    ACTIONS(345), 1,
      anon_sym_COMMA,
    STATE(83), 1,
      aux_sym_choice_list_repeat1,
  [1694] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(192), 3,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      aux_sym__tcl_token_token1,
  [1703] = 4,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(168), 1,
      anon_sym_DQUOTE,
    ACTIONS(347), 1,
      sym_number,
    STATE(24), 1,
      sym_string,
  [1716] = 4,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(349), 1,
      anon_sym_RBRACE,
    ACTIONS(351), 1,
      anon_sym_COMMA,
    STATE(92), 1,
      aux_sym_choice_list_repeat1,
  [1729] = 4,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(328), 1,
      anon_sym_RBRACE,
    ACTIONS(353), 1,
      anon_sym_COMMA,
    STATE(83), 1,
      aux_sym_choice_list_repeat1,
  [1742] = 2,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(332), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1750] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(168), 1,
      anon_sym_DQUOTE,
    STATE(97), 1,
      sym_string,
  [1760] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(341), 1,
      anon_sym_DQUOTE,
    STATE(37), 1,
      sym_string,
  [1770] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(355), 1,
      anon_sym_LBRACE,
    STATE(46), 1,
      sym_block,
  [1780] = 2,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(357), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [1788] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(359), 1,
      anon_sym_LBRACE,
    STATE(64), 1,
      sym_block,
  [1798] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(355), 1,
      anon_sym_LBRACE,
    STATE(40), 1,
      sym_block,
  [1808] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(359), 1,
      anon_sym_LBRACE,
    STATE(60), 1,
      sym_block,
  [1818] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(168), 1,
      anon_sym_DQUOTE,
    STATE(53), 1,
      sym_string,
  [1828] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(359), 1,
      anon_sym_LBRACE,
    STATE(63), 1,
      sym_block,
  [1838] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(341), 1,
      anon_sym_DQUOTE,
    STATE(43), 1,
      sym_string,
  [1848] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(168), 1,
      anon_sym_DQUOTE,
    STATE(106), 1,
      sym_string,
  [1858] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(341), 1,
      anon_sym_DQUOTE,
    STATE(16), 1,
      sym_string,
  [1868] = 2,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(361), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1876] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(168), 1,
      anon_sym_DQUOTE,
    STATE(24), 1,
      sym_string,
  [1886] = 3,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(324), 1,
      anon_sym_LBRACE,
    STATE(39), 1,
      sym_text_body,
  [1896] = 2,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(363), 1,
      sym_identifier,
  [1903] = 2,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(365), 1,
      anon_sym_LPAREN,
  [1910] = 2,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(367), 1,
      sym_identifier,
  [1917] = 2,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(369), 1,
      ts_builtin_sym_end,
  [1924] = 2,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(371), 1,
      sym_identifier,
  [1931] = 2,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(373), 1,
      sym_identifier,
  [1938] = 2,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(337), 1,
      anon_sym_RBRACE,
  [1945] = 2,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(375), 1,
      anon_sym_EQ_GT,
  [1952] = 2,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(377), 1,
      sym_identifier,
  [1959] = 2,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(379), 1,
      sym_identifier,
  [1966] = 2,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(349), 1,
      anon_sym_RBRACE,
  [1973] = 2,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(381), 1,
      sym_identifier,
  [1980] = 2,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(383), 1,
      sym_identifier,
  [1987] = 2,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(385), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 30,
  [SMALL_STATE(4)] = 60,
  [SMALL_STATE(5)] = 99,
  [SMALL_STATE(6)] = 138,
  [SMALL_STATE(7)] = 174,
  [SMALL_STATE(8)] = 210,
  [SMALL_STATE(9)] = 241,
  [SMALL_STATE(10)] = 275,
  [SMALL_STATE(11)] = 309,
  [SMALL_STATE(12)] = 340,
  [SMALL_STATE(13)] = 361,
  [SMALL_STATE(14)] = 382,
  [SMALL_STATE(15)] = 403,
  [SMALL_STATE(16)] = 434,
  [SMALL_STATE(17)] = 455,
  [SMALL_STATE(18)] = 484,
  [SMALL_STATE(19)] = 515,
  [SMALL_STATE(20)] = 546,
  [SMALL_STATE(21)] = 577,
  [SMALL_STATE(22)] = 601,
  [SMALL_STATE(23)] = 625,
  [SMALL_STATE(24)] = 649,
  [SMALL_STATE(25)] = 668,
  [SMALL_STATE(26)] = 687,
  [SMALL_STATE(27)] = 706,
  [SMALL_STATE(28)] = 730,
  [SMALL_STATE(29)] = 754,
  [SMALL_STATE(30)] = 776,
  [SMALL_STATE(31)] = 795,
  [SMALL_STATE(32)] = 812,
  [SMALL_STATE(33)] = 829,
  [SMALL_STATE(34)] = 846,
  [SMALL_STATE(35)] = 862,
  [SMALL_STATE(36)] = 878,
  [SMALL_STATE(37)] = 894,
  [SMALL_STATE(38)] = 910,
  [SMALL_STATE(39)] = 926,
  [SMALL_STATE(40)] = 942,
  [SMALL_STATE(41)] = 958,
  [SMALL_STATE(42)] = 974,
  [SMALL_STATE(43)] = 990,
  [SMALL_STATE(44)] = 1006,
  [SMALL_STATE(45)] = 1022,
  [SMALL_STATE(46)] = 1038,
  [SMALL_STATE(47)] = 1054,
  [SMALL_STATE(48)] = 1070,
  [SMALL_STATE(49)] = 1086,
  [SMALL_STATE(50)] = 1102,
  [SMALL_STATE(51)] = 1118,
  [SMALL_STATE(52)] = 1132,
  [SMALL_STATE(53)] = 1150,
  [SMALL_STATE(54)] = 1164,
  [SMALL_STATE(55)] = 1178,
  [SMALL_STATE(56)] = 1192,
  [SMALL_STATE(57)] = 1210,
  [SMALL_STATE(58)] = 1224,
  [SMALL_STATE(59)] = 1242,
  [SMALL_STATE(60)] = 1256,
  [SMALL_STATE(61)] = 1270,
  [SMALL_STATE(62)] = 1284,
  [SMALL_STATE(63)] = 1298,
  [SMALL_STATE(64)] = 1312,
  [SMALL_STATE(65)] = 1326,
  [SMALL_STATE(66)] = 1340,
  [SMALL_STATE(67)] = 1358,
  [SMALL_STATE(68)] = 1376,
  [SMALL_STATE(69)] = 1391,
  [SMALL_STATE(70)] = 1406,
  [SMALL_STATE(71)] = 1421,
  [SMALL_STATE(72)] = 1436,
  [SMALL_STATE(73)] = 1453,
  [SMALL_STATE(74)] = 1470,
  [SMALL_STATE(75)] = 1487,
  [SMALL_STATE(76)] = 1506,
  [SMALL_STATE(77)] = 1521,
  [SMALL_STATE(78)] = 1540,
  [SMALL_STATE(79)] = 1556,
  [SMALL_STATE(80)] = 1572,
  [SMALL_STATE(81)] = 1588,
  [SMALL_STATE(82)] = 1604,
  [SMALL_STATE(83)] = 1620,
  [SMALL_STATE(84)] = 1633,
  [SMALL_STATE(85)] = 1646,
  [SMALL_STATE(86)] = 1659,
  [SMALL_STATE(87)] = 1672,
  [SMALL_STATE(88)] = 1681,
  [SMALL_STATE(89)] = 1694,
  [SMALL_STATE(90)] = 1703,
  [SMALL_STATE(91)] = 1716,
  [SMALL_STATE(92)] = 1729,
  [SMALL_STATE(93)] = 1742,
  [SMALL_STATE(94)] = 1750,
  [SMALL_STATE(95)] = 1760,
  [SMALL_STATE(96)] = 1770,
  [SMALL_STATE(97)] = 1780,
  [SMALL_STATE(98)] = 1788,
  [SMALL_STATE(99)] = 1798,
  [SMALL_STATE(100)] = 1808,
  [SMALL_STATE(101)] = 1818,
  [SMALL_STATE(102)] = 1828,
  [SMALL_STATE(103)] = 1838,
  [SMALL_STATE(104)] = 1848,
  [SMALL_STATE(105)] = 1858,
  [SMALL_STATE(106)] = 1868,
  [SMALL_STATE(107)] = 1876,
  [SMALL_STATE(108)] = 1886,
  [SMALL_STATE(109)] = 1896,
  [SMALL_STATE(110)] = 1903,
  [SMALL_STATE(111)] = 1910,
  [SMALL_STATE(112)] = 1917,
  [SMALL_STATE(113)] = 1924,
  [SMALL_STATE(114)] = 1931,
  [SMALL_STATE(115)] = 1938,
  [SMALL_STATE(116)] = 1945,
  [SMALL_STATE(117)] = 1952,
  [SMALL_STATE(118)] = 1959,
  [SMALL_STATE(119)] = 1966,
  [SMALL_STATE(120)] = 1973,
  [SMALL_STATE(121)] = 1980,
  [SMALL_STATE(122)] = 1987,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(109),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(117),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(118),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(114),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(95),
  [21] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(109),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(103),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(117),
  [44] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(118),
  [47] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(79),
  [50] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(114),
  [53] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(95),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 2, 0, 4),
  [58] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_field, 2, 0, 4),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [62] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [64] = {.entry = {.count = 1, .reusable = false}}, SHIFT(105),
  [66] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 3, 0, 4),
  [70] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_field, 3, 0, 4),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_field_repeat1, 2, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_field_repeat1, 2, 0, 0),
  [76] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_field_repeat1, 2, 0, 0), SHIFT_REPEAT(86),
  [79] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_field_repeat1, 2, 0, 0), SHIFT_REPEAT(105),
  [82] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_field_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [87] = {.entry = {.count = 1, .reusable = false}}, SHIFT(90),
  [89] = {.entry = {.count = 1, .reusable = false}}, SHIFT(107),
  [91] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [93] = {.entry = {.count = 1, .reusable = false}}, SHIFT(111),
  [95] = {.entry = {.count = 1, .reusable = false}}, SHIFT(121),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [99] = {.entry = {.count = 1, .reusable = false}}, SHIFT(122),
  [101] = {.entry = {.count = 1, .reusable = false}}, SHIFT(101),
  [103] = {.entry = {.count = 1, .reusable = false}}, SHIFT(110),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 1, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute, 1, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 2, 0, 9),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute, 2, 0, 9),
  [115] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_field_repeat1, 2, 0, 0), SHIFT_REPEAT(90),
  [118] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_field_repeat1, 2, 0, 0), SHIFT_REPEAT(107),
  [121] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_field_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [124] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(111),
  [127] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(121),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0),
  [132] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(122),
  [135] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(101),
  [138] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(110),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dotted_name, 1, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dotted_name, 1, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dotted_name, 2, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dotted_name, 2, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_dotted_name_repeat1, 2, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_dotted_name_repeat1, 2, 0, 0),
  [159] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_dotted_name_repeat1, 2, 0, 0), SHIFT_REPEAT(113),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_define, 3, 0, 5),
  [174] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_define, 3, 0, 5),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [180] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tcl_expression, 2, 0, 0),
  [184] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tcl_expression, 2, 0, 0),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, 0, 12),
  [188] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3, 0, 12),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tcl_expression, 3, 0, 0),
  [192] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tcl_expression, 3, 0, 0),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 4, 0, 4),
  [196] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_field, 4, 0, 4),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [200] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 0),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_choice_list, 3, 0, 0),
  [204] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_choice_list, 3, 0, 0),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message_field, 2, 0, 3),
  [208] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_message_field, 2, 0, 3),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_choice_list, 4, 0, 0),
  [212] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_choice_list, 4, 0, 0),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text_block, 3, 0, 7),
  [216] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_text_block, 3, 0, 7),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_table, 3, 0, 6),
  [220] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_table, 3, 0, 6),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_choice_list, 5, 0, 0),
  [224] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_choice_list, 5, 0, 0),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_include, 2, 0, 1),
  [228] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_include, 2, 0, 1),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_define, 4, 0, 5),
  [232] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_define, 4, 0, 5),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [236] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2, 0, 0),
  [238] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 3, 0, 6),
  [240] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section, 3, 0, 6),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text_block, 2, 0, 2),
  [244] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_text_block, 2, 0, 2),
  [246] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text_body, 2, 0, 0),
  [248] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_text_body, 2, 0, 0),
  [250] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text_body, 3, 0, 0),
  [252] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_text_body, 3, 0, 0),
  [254] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_choice_list, 2, 0, 0),
  [256] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_choice_list, 2, 0, 0),
  [258] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [260] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [262] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [264] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [266] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [268] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_tcl_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(66),
  [271] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_tcl_expression_repeat1, 2, 0, 0),
  [273] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_tcl_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(58),
  [276] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_optional_block, 5, 0, 11),
  [278] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_optional_block, 5, 0, 11),
  [280] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [282] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [284] = {.entry = {.count = 1, .reusable = false}}, SHIFT(89),
  [286] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [288] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [290] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(69),
  [293] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [295] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [297] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [299] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [301] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [303] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_text_body_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [306] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_text_body_repeat1, 2, 0, 0),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [316] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [320] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [324] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [328] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [330] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [332] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_choice_list_repeat1, 2, 0, 0),
  [334] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_choice_list_repeat1, 2, 0, 0), SHIFT_REPEAT(85),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [347] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [349] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [351] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [353] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [355] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [357] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text_entry, 2, 0, 8),
  [359] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [361] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_choice_mapping, 3, 0, 10),
  [363] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [365] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [367] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [369] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [371] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [373] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [375] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [377] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [379] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [381] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [383] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [385] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_apl(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
