ltm rule /Common/__tcl_lsp_evtflow_EFC_respond_disable_all_safe {
    when HTTP_REQUEST priority 400 {
        set evtflow_suppression_id [HTTP::header value X-Evtflow-Request]
        log local0. "EVTFLOW|run=EFC|probe=suppression-safe|case=respond-disable-all-safe|point=before|request=$evtflow_suppression_id|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
        HTTP::respond 204 -version 1.1 -content "" Connection close -noserver
                event disable all
        log local0. "EVTFLOW|run=EFC|probe=suppression-safe|case=respond-disable-all-safe|point=after|request=$evtflow_suppression_id|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
