[package]
name = "xtask"
publish.workspace = true
description = "Build/check task runner for the workspace"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[[bin]]
name = "xtask"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive", "wrap_help"] }
anyhow = "1"
regex = "1"
tcl-core-types = { path = "../tcl-core-types" }

[lints]
workspace = true
