//! `spinbox` command.
use crate::prelude::*;
const SIDE_EFFECTS: &[SideEffect] = &[SideEffect {
    target: SideEffectTarget::InterpState,
    reads: false,
    writes: true,
    connection_side: ConnectionSide::None,
}];

const OPTIONS: &[OptionSpec] = &[
    OptionSpec {
        name: "-from",
        takes_value: true,
        value_hint: "",
        detail: "Starting value for the numeric range.",
        dialects: None,
    },
    OptionSpec {
        name: "-to",
        takes_value: true,
        value_hint: "",
        detail: "Ending value for the numeric range.",
        dialects: None,
    },
    OptionSpec {
        name: "-increment",
        takes_value: true,
        value_hint: "",
        detail: "Amount to increment or decrement the value on each arrow press.",
        dialects: None,
    },
    OptionSpec {
        name: "-values",
        takes_value: true,
        value_hint: "",
        detail: "List of values to cycle through instead of a numeric range.",
        dialects: None,
    },
    OptionSpec {
        name: "-textvariable",
        takes_value: true,
        value_hint: "",
        detail: "Name of a variable linked to the spinbox's contents.",
        dialects: None,
    },
    OptionSpec {
        name: "-width",
        takes_value: true,
        value_hint: "",
        detail: "Desired width of the spinbox in average-size characters.",
        dialects: None,
    },
    OptionSpec {
        name: "-state",
        takes_value: true,
        value_hint: "",
        detail: "State of the spinbox: normal, disabled, or readonly.",
        dialects: None,
    },
    OptionSpec {
        name: "-format",
        takes_value: true,
        value_hint: "",
        detail: "Format string for displaying the value (e.g. %5.2f).",
        dialects: None,
    },
    OptionSpec {
        name: "-wrap",
        takes_value: true,
        value_hint: "",
        detail: "Whether the value wraps around when the range limit is reached.",
        dialects: None,
    },
    OptionSpec {
        name: "-command",
        takes_value: true,
        value_hint: "",
        detail: "Tcl command to invoke when the value is changed via the arrows.",
        dialects: None,
    },
    OptionSpec {
        name: "-validate",
        takes_value: true,
        value_hint: "",
        detail: "Validation mode: none, focus, focusin, focusout, key, or all.",
        dialects: None,
    },
    OptionSpec {
        name: "-validatecommand",
        takes_value: true,
        value_hint: "",
        detail: "Script to evaluate when validation is triggered.",
        dialects: None,
    },
    OptionSpec {
        name: "-invalidcommand",
        takes_value: true,
        value_hint: "",
        detail: "Script to evaluate when validation fails.",
        dialects: None,
    },
    OptionSpec {
        name: "-font",
        takes_value: true,
        value_hint: "",
        detail: "Font to use for text in the spinbox.",
        dialects: None,
    },
    OptionSpec {
        name: "-bg",
        takes_value: true,
        value_hint: "",
        detail: "Shorthand for -background.",
        dialects: None,
    },
    OptionSpec {
        name: "-fg",
        takes_value: true,
        value_hint: "",
        detail: "Shorthand for -foreground.",
        dialects: None,
    },
    OptionSpec {
        name: "-readonlybackground",
        takes_value: true,
        value_hint: "",
        detail: "Background colour when the spinbox is in readonly state.",
        dialects: None,
    },
    OptionSpec {
        name: "-buttonbackground",
        takes_value: true,
        value_hint: "",
        detail: "Background colour of the increment/decrement buttons.",
        dialects: None,
    },
    OptionSpec {
        name: "-buttoncursor",
        takes_value: true,
        value_hint: "",
        detail: "Cursor to display when the mouse is over the buttons.",
        dialects: None,
    },
    OptionSpec {
        name: "-buttondownrelief",
        takes_value: true,
        value_hint: "",
        detail: "Relief of the down (decrement) button.",
        dialects: None,
    },
    OptionSpec {
        name: "-buttonuprelief",
        takes_value: true,
        value_hint: "",
        detail: "Relief of the up (increment) button.",
        dialects: None,
    },
    OptionSpec {
        name: "-relief",
        takes_value: true,
        value_hint: "",
        detail: "3-D effect: flat, groove, raised, ridge, solid, or sunken.",
        dialects: None,
    },
    OptionSpec {
        name: "-selectbackground",
        takes_value: true,
        value_hint: "",
        detail: "Background colour for selected text.",
        dialects: None,
    },
    OptionSpec {
        name: "-selectborderwidth",
        takes_value: true,
        value_hint: "",
        detail: "Width of the border around selected text.",
        dialects: None,
    },
    OptionSpec {
        name: "-selectforeground",
        takes_value: true,
        value_hint: "",
        detail: "Foreground colour for selected text.",
        dialects: None,
    },
    OptionSpec {
        name: "-insertbackground",
        takes_value: true,
        value_hint: "",
        detail: "Colour of the insertion cursor.",
        dialects: None,
    },
    OptionSpec {
        name: "-insertborderwidth",
        takes_value: true,
        value_hint: "",
        detail: "Width of the border around the insertion cursor.",
        dialects: None,
    },
    OptionSpec {
        name: "-insertofftime",
        takes_value: true,
        value_hint: "",
        detail: "Milliseconds the insertion cursor is off during blinking.",
        dialects: None,
    },
    OptionSpec {
        name: "-insertontime",
        takes_value: true,
        value_hint: "",
        detail: "Milliseconds the insertion cursor is on during blinking.",
        dialects: None,
    },
    OptionSpec {
        name: "-insertwidth",
        takes_value: true,
        value_hint: "",
        detail: "Width of the insertion cursor in screen units.",
        dialects: None,
    },
    OptionSpec {
        name: "-xscrollcommand",
        takes_value: true,
        value_hint: "",
        detail: "Command prefix for communicating with horizontal scrollbars.",
        dialects: None,
    },
    OptionSpec {
        name: "-exportselection",
        takes_value: true,
        value_hint: "",
        detail: "Whether the selection is exported to the X selection.",
        dialects: None,
    },
    OptionSpec {
        name: "-cursor",
        takes_value: true,
        value_hint: "",
        detail: "Cursor to display when the mouse is over the spinbox.",
        dialects: None,
    },
    OptionSpec {
        name: "-takefocus",
        takes_value: true,
        value_hint: "",
        detail: "Whether the spinbox accepts focus during keyboard traversal.",
        dialects: None,
    },
    OptionSpec {
        name: "-highlightbackground",
        takes_value: true,
        value_hint: "",
        detail: "Colour of the highlight region when the spinbox does not have focus.",
        dialects: None,
    },
    OptionSpec {
        name: "-highlightcolor",
        takes_value: true,
        value_hint: "",
        detail: "Colour of the highlight region when the spinbox has focus.",
        dialects: None,
    },
    OptionSpec {
        name: "-highlightthickness",
        takes_value: true,
        value_hint: "",
        detail: "Width of the highlight rectangle drawn around the spinbox.",
        dialects: None,
    },
];

const FORMS: &[FormSpec] = &[FormSpec {
    kind: FormKind::Default,
    synopsis: "spinbox pathName ?option value ...?",
}];

pub fn spec() -> CommandSpec {
    CommandSpec {
        name: "spinbox",
        dialects: None,
        arity: Arity::at_least(1),
        hover: Some(HoverSnippet {
            summary: "Create and manipulate a spinbox widget.",
            synopsis: &["spinbox pathName ?option value ...?"],
            snippet: "Displays a single-line text field with increment and decrement arrows for cycling through a range of values.",
            source: "Tk man page spinbox.n",
            examples: "",
            return_value: "",
        }),
        required_package: Some("Tk"),
        warn_missing_import: false,
        forms: FORMS,
        options: OPTIONS,
        side_effects: SIDE_EFFECTS,
        ..CommandSpec::DEFAULT
    }
}
