ltm rule /Common/__tcl_lsp_evtflow_efe_apm_trace {
    when RULE_INIT {
        log local0. "EVTFLOW2|run=EFE|event=RULE_INIT|tmm=[TMM::cmp_group]:[TMM::cmp_unit]|probe=apm"
    }
    when ACCESS_SESSION_STARTED {
        log local0. "EVTFLOW2|run=EFE|event=ACCESS_SESSION_STARTED|tmm=[TMM::cmp_group]:[TMM::cmp_unit]|probe=apm|sid=[ACCESS::session sid]"
    }
    when ACCESS_POLICY_AGENT_EVENT {
        set agent [ACCESS::policy agent_id]
        ACCESS::session data set session.custom.evtflow2_agent $agent
        log local0. "EVTFLOW2|run=EFE|event=ACCESS_POLICY_AGENT_EVENT|tmm=[TMM::cmp_group]:[TMM::cmp_unit]|probe=apm|agent=$agent|sid=[ACCESS::session sid]"
    }
    when ACCESS_POLICY_COMPLETED {
        log local0. "EVTFLOW2|run=EFE|event=ACCESS_POLICY_COMPLETED|tmm=[TMM::cmp_group]:[TMM::cmp_unit]|probe=apm|result=[ACCESS::policy result]|sid=[ACCESS::session sid]"
    }
    when ACCESS_ACL_ALLOWED {
        log local0. "EVTFLOW2|run=EFE|event=ACCESS_ACL_ALLOWED|tmm=[TMM::cmp_group]:[TMM::cmp_unit]|probe=apm|sid=[ACCESS::session sid]"
    }
    when ACCESS_ACL_DENIED {
        log local0. "EVTFLOW2|run=EFE|event=ACCESS_ACL_DENIED|tmm=[TMM::cmp_group]:[TMM::cmp_unit]|probe=apm|sid=[ACCESS::session sid]"
    }
    when ACCESS_SESSION_CLOSED {
        log local0. "EVTFLOW2|run=EFE|event=ACCESS_SESSION_CLOSED|tmm=[TMM::cmp_group]:[TMM::cmp_unit]|probe=apm"
    }
    when HTTP_REQUEST priority 100 {
        log local0. "EVTFLOW2|run=EFE|event=HTTP_REQUEST|tmm=[TMM::cmp_group]:[TMM::cmp_unit]|probe=apm|uri=[HTTP::uri]|internal=[ACCESS::policy uri]"
    }
}
