//! `tcl::mathop` operator ensemble — name-parity reconcile (GAP-d).
//!
//! The Rust port collapsed the operator ensemble into a single
//! `tcl::mathop` entry; the Python source of truth registers each
//! operator as a command in three spellings (bare `+`,
//! `tcl::mathop::+`, `::tcl::mathop::+`) plus the word operators
//! (`eq`/`ne`/`in`/`ni`/`max`/`min`). This file restores name parity.
//!
//! Generated by `scripts/registry-audit/gen_missing_tcl.py`.
use crate::prelude::*;

/// All `tcl::mathop` operator-command specs (every spelling).
#[allow(clippy::too_many_lines)]
pub fn specs() -> Vec<CommandSpec> {
    vec![
        CommandSpec {
            name: "!",
            arity: Arity::exact(1),
            hover: Some(HoverSnippet::brief(
                "logical NOT (unary)",
                &["! ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "!=",
            arity: Arity::exact(2),
            hover: Some(HoverSnippet::brief(
                "numeric inequality",
                &["!= ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "%",
            arity: Arity::exact(2),
            hover: Some(HoverSnippet::brief(
                "modulo",
                &["% ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "&",
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet::brief(
                "bitwise AND",
                &["& ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "&&",
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet::brief(
                "logical AND",
                &["&& ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "*",
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet::brief(
                "multiplication",
                &["* ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "**",
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet::brief(
                "exponentiation",
                &["** ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "+",
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet::brief(
                "addition",
                &["+ ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "-",
            arity: Arity::at_least(1),
            hover: Some(HoverSnippet::brief(
                "subtraction or negation",
                &["- ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "/",
            arity: Arity::at_least(1),
            hover: Some(HoverSnippet::brief(
                "division",
                &["/ ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "::tcl::build-info",
            arity: Arity::new(0, 1),
            return_type: Some(TclType::String),
            hover: Some(HoverSnippet::brief(
                "Return compile-time build metadata for the Tcl runtime.",
                &["tcl::build-info ?key?"],
                "Tcl tcl::build-info (internal)",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "::tcl::mathop::!",
            arity: Arity::exact(1),
            hover: Some(HoverSnippet::brief(
                "logical NOT (unary)",
                &["::tcl::mathop::! ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "::tcl::mathop::!=",
            arity: Arity::exact(2),
            hover: Some(HoverSnippet::brief(
                "numeric inequality",
                &["::tcl::mathop::!= ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "::tcl::mathop::%",
            arity: Arity::exact(2),
            hover: Some(HoverSnippet::brief(
                "modulo",
                &["::tcl::mathop::% ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "::tcl::mathop::&",
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet::brief(
                "bitwise AND",
                &["::tcl::mathop::& ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "::tcl::mathop::&&",
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet::brief(
                "logical AND",
                &["::tcl::mathop::&& ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "::tcl::mathop::*",
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet::brief(
                "multiplication",
                &["::tcl::mathop::* ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "::tcl::mathop::**",
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet::brief(
                "exponentiation",
                &["::tcl::mathop::** ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "::tcl::mathop::+",
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet::brief(
                "addition",
                &["::tcl::mathop::+ ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "::tcl::mathop::-",
            arity: Arity::at_least(1),
            hover: Some(HoverSnippet::brief(
                "subtraction or negation",
                &["::tcl::mathop::- ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "::tcl::mathop::/",
            arity: Arity::at_least(1),
            hover: Some(HoverSnippet::brief(
                "division",
                &["::tcl::mathop::/ ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "::tcl::mathop::<",
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet::brief(
                "numeric less-than",
                &["::tcl::mathop::< ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "::tcl::mathop::<<",
            arity: Arity::exact(2),
            hover: Some(HoverSnippet::brief(
                "left shift",
                &["::tcl::mathop::<< ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "::tcl::mathop::<=",
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet::brief(
                "numeric less-or-equal",
                &["::tcl::mathop::<= ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "::tcl::mathop::==",
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet::brief(
                "numeric equality",
                &["::tcl::mathop::== ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "::tcl::mathop::>",
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet::brief(
                "numeric greater-than",
                &["::tcl::mathop::> ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "::tcl::mathop::>=",
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet::brief(
                "numeric greater-or-equal",
                &["::tcl::mathop::>= ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "::tcl::mathop::>>",
            arity: Arity::exact(2),
            hover: Some(HoverSnippet::brief(
                "right shift",
                &["::tcl::mathop::>> ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "::tcl::mathop::@",
            arity: Arity::exact(2),
            hover: Some(HoverSnippet::brief(
                "list index operator",
                &["::tcl::mathop::@ ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "::tcl::mathop::^",
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet::brief(
                "bitwise XOR",
                &["::tcl::mathop::^ ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "::tcl::mathop::eq",
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet::brief(
                "string equality",
                &["::tcl::mathop::eq ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "::tcl::mathop::in",
            arity: Arity::exact(2),
            hover: Some(HoverSnippet::brief(
                "list membership",
                &["::tcl::mathop::in ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "::tcl::mathop::max",
            arity: Arity::at_least(1),
            hover: Some(HoverSnippet::brief(
                "maximum of arguments",
                &["::tcl::mathop::max ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "::tcl::mathop::min",
            arity: Arity::at_least(1),
            hover: Some(HoverSnippet::brief(
                "minimum of arguments",
                &["::tcl::mathop::min ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "::tcl::mathop::ne",
            arity: Arity::exact(2),
            hover: Some(HoverSnippet::brief(
                "string inequality",
                &["::tcl::mathop::ne ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "::tcl::mathop::ni",
            arity: Arity::exact(2),
            hover: Some(HoverSnippet::brief(
                "list non-membership",
                &["::tcl::mathop::ni ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "::tcl::mathop::|",
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet::brief(
                "bitwise OR",
                &["::tcl::mathop::| ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "::tcl::mathop::||",
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet::brief(
                "logical OR",
                &["::tcl::mathop::|| ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "::tcl::mathop::~",
            arity: Arity::exact(1),
            hover: Some(HoverSnippet::brief(
                "bitwise NOT (unary)",
                &["::tcl::mathop::~ ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "<",
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet::brief(
                "numeric less-than",
                &["< ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "<<",
            arity: Arity::exact(2),
            hover: Some(HoverSnippet::brief(
                "left shift",
                &["<< ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "<=",
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet::brief(
                "numeric less-or-equal",
                &["<= ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "==",
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet::brief(
                "numeric equality",
                &["== ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: ">",
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet::brief(
                "numeric greater-than",
                &["> ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: ">=",
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet::brief(
                "numeric greater-or-equal",
                &[">= ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: ">>",
            arity: Arity::exact(2),
            hover: Some(HoverSnippet::brief(
                "right shift",
                &[">> ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "@",
            arity: Arity::exact(2),
            hover: Some(HoverSnippet::brief(
                "list index operator",
                &["@ ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "^",
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet::brief(
                "bitwise XOR",
                &["^ ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "eq",
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet::brief(
                "string equality",
                &["eq ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "in",
            arity: Arity::exact(2),
            hover: Some(HoverSnippet::brief(
                "list membership",
                &["in ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "max",
            arity: Arity::at_least(1),
            hover: Some(HoverSnippet::brief(
                "maximum of arguments",
                &["max ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "min",
            arity: Arity::at_least(1),
            hover: Some(HoverSnippet::brief(
                "minimum of arguments",
                &["min ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "ne",
            arity: Arity::exact(2),
            hover: Some(HoverSnippet::brief(
                "string inequality",
                &["ne ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "ni",
            arity: Arity::exact(2),
            hover: Some(HoverSnippet::brief(
                "list non-membership",
                &["ni ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "tcl::mathop::!",
            arity: Arity::exact(1),
            hover: Some(HoverSnippet::brief(
                "logical NOT (unary)",
                &["tcl::mathop::! ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "tcl::mathop::!=",
            arity: Arity::exact(2),
            hover: Some(HoverSnippet::brief(
                "numeric inequality",
                &["tcl::mathop::!= ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "tcl::mathop::%",
            arity: Arity::exact(2),
            hover: Some(HoverSnippet::brief(
                "modulo",
                &["tcl::mathop::% ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "tcl::mathop::&",
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet::brief(
                "bitwise AND",
                &["tcl::mathop::& ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "tcl::mathop::&&",
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet::brief(
                "logical AND",
                &["tcl::mathop::&& ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "tcl::mathop::*",
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet::brief(
                "multiplication",
                &["tcl::mathop::* ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "tcl::mathop::**",
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet::brief(
                "exponentiation",
                &["tcl::mathop::** ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "tcl::mathop::+",
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet::brief(
                "addition",
                &["tcl::mathop::+ ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "tcl::mathop::-",
            arity: Arity::at_least(1),
            hover: Some(HoverSnippet::brief(
                "subtraction or negation",
                &["tcl::mathop::- ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "tcl::mathop::/",
            arity: Arity::at_least(1),
            hover: Some(HoverSnippet::brief(
                "division",
                &["tcl::mathop::/ ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "tcl::mathop::<",
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet::brief(
                "numeric less-than",
                &["tcl::mathop::< ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "tcl::mathop::<<",
            arity: Arity::exact(2),
            hover: Some(HoverSnippet::brief(
                "left shift",
                &["tcl::mathop::<< ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "tcl::mathop::<=",
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet::brief(
                "numeric less-or-equal",
                &["tcl::mathop::<= ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "tcl::mathop::==",
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet::brief(
                "numeric equality",
                &["tcl::mathop::== ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "tcl::mathop::>",
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet::brief(
                "numeric greater-than",
                &["tcl::mathop::> ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "tcl::mathop::>=",
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet::brief(
                "numeric greater-or-equal",
                &["tcl::mathop::>= ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "tcl::mathop::>>",
            arity: Arity::exact(2),
            hover: Some(HoverSnippet::brief(
                "right shift",
                &["tcl::mathop::>> ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "tcl::mathop::@",
            arity: Arity::exact(2),
            hover: Some(HoverSnippet::brief(
                "list index operator",
                &["tcl::mathop::@ ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "tcl::mathop::^",
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet::brief(
                "bitwise XOR",
                &["tcl::mathop::^ ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "tcl::mathop::eq",
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet::brief(
                "string equality",
                &["tcl::mathop::eq ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "tcl::mathop::in",
            arity: Arity::exact(2),
            hover: Some(HoverSnippet::brief(
                "list membership",
                &["tcl::mathop::in ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "tcl::mathop::max",
            arity: Arity::at_least(1),
            hover: Some(HoverSnippet::brief(
                "maximum of arguments",
                &["tcl::mathop::max ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "tcl::mathop::min",
            arity: Arity::at_least(1),
            hover: Some(HoverSnippet::brief(
                "minimum of arguments",
                &["tcl::mathop::min ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "tcl::mathop::ne",
            arity: Arity::exact(2),
            hover: Some(HoverSnippet::brief(
                "string inequality",
                &["tcl::mathop::ne ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "tcl::mathop::ni",
            arity: Arity::exact(2),
            hover: Some(HoverSnippet::brief(
                "list non-membership",
                &["tcl::mathop::ni ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "tcl::mathop::|",
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet::brief(
                "bitwise OR",
                &["tcl::mathop::| ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "tcl::mathop::||",
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet::brief(
                "logical OR",
                &["tcl::mathop::|| ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "tcl::mathop::~",
            arity: Arity::exact(1),
            hover: Some(HoverSnippet::brief(
                "bitwise NOT (unary)",
                &["tcl::mathop::~ ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "|",
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet::brief(
                "bitwise OR",
                &["| ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "||",
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet::brief(
                "logical OR",
                &["|| ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "~",
            arity: Arity::exact(1),
            hover: Some(HoverSnippet::brief(
                "bitwise NOT (unary)",
                &["~ ?arg ...?"],
                "Tcl man page mathop.n",
            )),
            ..CommandSpec::DEFAULT
        },
    ]
}
