// tcl-lsp — a language server and toolchain for Tcl
// Copyright (C) 2026 James Deucker (bitwisecook) <https://github.com/bitwisecook>
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
// SPDX-License-Identifier: AGPL-3.0-or-later

//! `tcl::mathop` operator ensemble.
//!
//! Each operator is registered as a command in three spellings (bare `+`,
//! `tcl::mathop::+`, `::tcl::mathop::+`) plus the word operators
//! (`eq`/`ne`/`in`/`ni`).
//!
//! `max`/`min` are deliberately **not** here: despite reading like operator
//! words, they were never real `::tcl::mathop` members (verified against
//! tclsh 8.6/9.0 — `info commands ::tcl::mathop::*` never lists them; only
//! `expr {max(...)}} / {min(...)}}` math functions exist under those names,
//! an unrelated Tcl feature). An earlier generator run incorrectly added all
//! three `max`/`min` spellings here; a bare `max`/`min` registry entry that
//! looked like a real builtin made a user `proc max {...}` — ordinary,
//! working Tcl since bare `max` never resolves without an explicit
//! `namespace import ::tcl::mathop::*` the ensemble doesn't even define —
//! read as "renaming a builtin" by the optimiser's command-rebinding scan,
//! silently suppressing an otherwise-valid O103 fold.
//!
//! Generated by `scripts/registry-audit/gen_missing_tcl.py`.
use crate::prelude::*;

/// All `tcl::mathop` operator-command specs (every spelling).
pub fn specs() -> Vec<CommandSpec> {
    let mut out = specs_0();
    out.extend(specs_1());
    out.extend(specs_2());
    out.extend(specs_3());
    out.extend(specs_4());
    out.extend(specs_5());
    out.extend(specs_6());
    out.extend(specs_7());
    out.extend(specs_8());
    out.extend(specs_9());
    out.extend(specs_10());
    out.extend(specs_11());
    out.extend(specs_12());
    out.extend(specs_13());
    out.extend(specs_14());
    out.extend(specs_15());
    out.extend(specs_16());
    out
}

fn specs_0() -> Vec<CommandSpec> {
    vec![
        CommandSpec {
            name: "!",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::exact(1),
            hover: Some(HoverSnippet {
                summary: "logical NOT (unary)",
                synopsis: &["! ?arg ...?"],
                snippet: "The ! operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "! ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "!=",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::exact(2),
            hover: Some(HoverSnippet {
                summary: "numeric inequality",
                synopsis: &["!= ?arg ...?"],
                snippet: "The != operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "!= ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "%",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::exact(2),
            hover: Some(HoverSnippet {
                summary: "modulo",
                synopsis: &["% ?arg ...?"],
                snippet: "The % operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "% ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "&",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet {
                summary: "bitwise AND",
                synopsis: &["& ?arg ...?"],
                snippet: "The & operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "& ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "&&",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet {
                summary: "logical AND",
                synopsis: &["&& ?arg ...?"],
                snippet: "The && operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "&& ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
    ]
}

fn specs_1() -> Vec<CommandSpec> {
    vec![
        CommandSpec {
            name: "*",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet {
                summary: "multiplication",
                synopsis: &["* ?arg ...?"],
                snippet: "The * operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "* ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "**",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet {
                summary: "exponentiation",
                synopsis: &["** ?arg ...?"],
                snippet: "The ** operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "** ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "+",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet {
                summary: "addition",
                synopsis: &["+ ?arg ...?"],
                snippet: "The + operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "+ ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "-",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::at_least(1),
            hover: Some(HoverSnippet {
                summary: "subtraction or negation",
                synopsis: &["- ?arg ...?"],
                snippet: "The - operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "- ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "/",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::at_least(1),
            hover: Some(HoverSnippet {
                summary: "division",
                synopsis: &["/ ?arg ...?"],
                snippet: "The / operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "/ ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
    ]
}

fn specs_2() -> Vec<CommandSpec> {
    vec![
        CommandSpec {
            name: "::tcl::build-info",
            dialects: None,
            arity: Arity::new(0, 1),
            return_type: Some(TclType::String),
            hover: Some(HoverSnippet {
                summary: "Return compile-time build metadata for the Tcl runtime.",
                synopsis: &["tcl::build-info ?key?"],
                snippet: "Returns the compile-time build metadata for the running Tcl runtime.  With no arguments, returns the patchlevel.  With a key argument, returns the value associated with that key (e.g. ``version``, ``commit``, ``branch``, ``compiler``).",
                source: "Tcl tcl::build-info (internal)",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "tcl::build-info ?key?",
            }],
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "::tcl::mathop::!",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::exact(1),
            hover: Some(HoverSnippet {
                summary: "logical NOT (unary)",
                synopsis: &["::tcl::mathop::! ?arg ...?"],
                snippet: "The ::tcl::mathop::! operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "::tcl::mathop::! ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "::tcl::mathop::!=",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::exact(2),
            hover: Some(HoverSnippet {
                summary: "numeric inequality",
                synopsis: &["::tcl::mathop::!= ?arg ...?"],
                snippet: "The ::tcl::mathop::!= operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "::tcl::mathop::!= ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "::tcl::mathop::%",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::exact(2),
            hover: Some(HoverSnippet {
                summary: "modulo",
                synopsis: &["::tcl::mathop::% ?arg ...?"],
                snippet: "The ::tcl::mathop::% operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "::tcl::mathop::% ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "::tcl::mathop::&",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet {
                summary: "bitwise AND",
                synopsis: &["::tcl::mathop::& ?arg ...?"],
                snippet: "The ::tcl::mathop::& operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "::tcl::mathop::& ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
    ]
}

fn specs_3() -> Vec<CommandSpec> {
    vec![
        CommandSpec {
            name: "::tcl::mathop::&&",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet {
                summary: "logical AND",
                synopsis: &["::tcl::mathop::&& ?arg ...?"],
                snippet: "The ::tcl::mathop::&& operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "::tcl::mathop::&& ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "::tcl::mathop::*",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet {
                summary: "multiplication",
                synopsis: &["::tcl::mathop::* ?arg ...?"],
                snippet: "The ::tcl::mathop::* operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "::tcl::mathop::* ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "::tcl::mathop::**",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet {
                summary: "exponentiation",
                synopsis: &["::tcl::mathop::** ?arg ...?"],
                snippet: "The ::tcl::mathop::** operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "::tcl::mathop::** ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "::tcl::mathop::+",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet {
                summary: "addition",
                synopsis: &["::tcl::mathop::+ ?arg ...?"],
                snippet: "The ::tcl::mathop::+ operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "::tcl::mathop::+ ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "::tcl::mathop::-",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::at_least(1),
            hover: Some(HoverSnippet {
                summary: "subtraction or negation",
                synopsis: &["::tcl::mathop::- ?arg ...?"],
                snippet: "The ::tcl::mathop::- operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "::tcl::mathop::- ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
    ]
}

fn specs_4() -> Vec<CommandSpec> {
    vec![
        CommandSpec {
            name: "::tcl::mathop::/",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::at_least(1),
            hover: Some(HoverSnippet {
                summary: "division",
                synopsis: &["::tcl::mathop::/ ?arg ...?"],
                snippet: "The ::tcl::mathop::/ operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "::tcl::mathop::/ ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "::tcl::mathop::<",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet {
                summary: "numeric less-than",
                synopsis: &["::tcl::mathop::< ?arg ...?"],
                snippet: "The ::tcl::mathop::< operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "::tcl::mathop::< ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "::tcl::mathop::<<",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::exact(2),
            hover: Some(HoverSnippet {
                summary: "left shift",
                synopsis: &["::tcl::mathop::<< ?arg ...?"],
                snippet: "The ::tcl::mathop::<< operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "::tcl::mathop::<< ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "::tcl::mathop::<=",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet {
                summary: "numeric less-or-equal",
                synopsis: &["::tcl::mathop::<= ?arg ...?"],
                snippet: "The ::tcl::mathop::<= operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "::tcl::mathop::<= ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "::tcl::mathop::==",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet {
                summary: "numeric equality",
                synopsis: &["::tcl::mathop::== ?arg ...?"],
                snippet: "The ::tcl::mathop::== operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "::tcl::mathop::== ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
    ]
}

fn specs_5() -> Vec<CommandSpec> {
    vec![
        CommandSpec {
            name: "::tcl::mathop::>",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet {
                summary: "numeric greater-than",
                synopsis: &["::tcl::mathop::> ?arg ...?"],
                snippet: "The ::tcl::mathop::> operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "::tcl::mathop::> ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "::tcl::mathop::>=",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet {
                summary: "numeric greater-or-equal",
                synopsis: &["::tcl::mathop::>= ?arg ...?"],
                snippet: "The ::tcl::mathop::>= operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "::tcl::mathop::>= ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "::tcl::mathop::>>",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::exact(2),
            hover: Some(HoverSnippet {
                summary: "right shift",
                synopsis: &["::tcl::mathop::>> ?arg ...?"],
                snippet: "The ::tcl::mathop::>> operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "::tcl::mathop::>> ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "::tcl::mathop::@",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::exact(2),
            hover: Some(HoverSnippet {
                summary: "list index operator",
                synopsis: &["::tcl::mathop::@ ?arg ...?"],
                snippet: "The ::tcl::mathop::@ operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "::tcl::mathop::@ ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "::tcl::mathop::^",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet {
                summary: "bitwise XOR",
                synopsis: &["::tcl::mathop::^ ?arg ...?"],
                snippet: "The ::tcl::mathop::^ operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "::tcl::mathop::^ ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
    ]
}

fn specs_6() -> Vec<CommandSpec> {
    vec![
        CommandSpec {
            name: "::tcl::mathop::eq",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet {
                summary: "string equality",
                synopsis: &["::tcl::mathop::eq ?arg ...?"],
                snippet: "The ::tcl::mathop::eq operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "::tcl::mathop::eq ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "::tcl::mathop::in",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::exact(2),
            hover: Some(HoverSnippet {
                summary: "list membership",
                synopsis: &["::tcl::mathop::in ?arg ...?"],
                snippet: "The ::tcl::mathop::in operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "::tcl::mathop::in ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "::tcl::mathop::ne",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::exact(2),
            hover: Some(HoverSnippet {
                summary: "string inequality",
                synopsis: &["::tcl::mathop::ne ?arg ...?"],
                snippet: "The ::tcl::mathop::ne operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "::tcl::mathop::ne ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
    ]
}

fn specs_7() -> Vec<CommandSpec> {
    vec![
        CommandSpec {
            name: "::tcl::mathop::ni",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::exact(2),
            hover: Some(HoverSnippet {
                summary: "list non-membership",
                synopsis: &["::tcl::mathop::ni ?arg ...?"],
                snippet: "The ::tcl::mathop::ni operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "::tcl::mathop::ni ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "::tcl::mathop::|",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet {
                summary: "bitwise OR",
                synopsis: &["::tcl::mathop::| ?arg ...?"],
                snippet: "The ::tcl::mathop::| operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "::tcl::mathop::| ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "::tcl::mathop::||",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet {
                summary: "logical OR",
                synopsis: &["::tcl::mathop::|| ?arg ...?"],
                snippet: "The ::tcl::mathop::|| operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "::tcl::mathop::|| ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "::tcl::mathop::~",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::exact(1),
            hover: Some(HoverSnippet {
                summary: "bitwise NOT (unary)",
                synopsis: &["::tcl::mathop::~ ?arg ...?"],
                snippet: "The ::tcl::mathop::~ operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "::tcl::mathop::~ ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "<",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet {
                summary: "numeric less-than",
                synopsis: &["< ?arg ...?"],
                snippet: "The < operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "< ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
    ]
}

fn specs_8() -> Vec<CommandSpec> {
    vec![
        CommandSpec {
            name: "<<",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::exact(2),
            hover: Some(HoverSnippet {
                summary: "left shift",
                synopsis: &["<< ?arg ...?"],
                snippet: "The << operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "<< ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "<=",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet {
                summary: "numeric less-or-equal",
                synopsis: &["<= ?arg ...?"],
                snippet: "The <= operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "<= ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "==",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet {
                summary: "numeric equality",
                synopsis: &["== ?arg ...?"],
                snippet: "The == operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "== ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: ">",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet {
                summary: "numeric greater-than",
                synopsis: &["> ?arg ...?"],
                snippet: "The > operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "> ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: ">=",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet {
                summary: "numeric greater-or-equal",
                synopsis: &[">= ?arg ...?"],
                snippet: "The >= operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: ">= ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
    ]
}

fn specs_9() -> Vec<CommandSpec> {
    vec![
        CommandSpec {
            name: ">>",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::exact(2),
            hover: Some(HoverSnippet {
                summary: "right shift",
                synopsis: &[">> ?arg ...?"],
                snippet: "The >> operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: ">> ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "@",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::exact(2),
            hover: Some(HoverSnippet {
                summary: "list index operator",
                synopsis: &["@ ?arg ...?"],
                snippet: "The @ operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "@ ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "^",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet {
                summary: "bitwise XOR",
                synopsis: &["^ ?arg ...?"],
                snippet: "The ^ operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "^ ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "eq",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet {
                summary: "string equality",
                synopsis: &["eq ?arg ...?"],
                snippet: "The eq operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "eq ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "in",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::exact(2),
            hover: Some(HoverSnippet {
                summary: "list membership",
                synopsis: &["in ?arg ...?"],
                snippet: "The in operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "in ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
    ]
}

fn specs_10() -> Vec<CommandSpec> {
    vec![
        CommandSpec {
            name: "ne",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::exact(2),
            hover: Some(HoverSnippet {
                summary: "string inequality",
                synopsis: &["ne ?arg ...?"],
                snippet: "The ne operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "ne ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "ni",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::exact(2),
            hover: Some(HoverSnippet {
                summary: "list non-membership",
                synopsis: &["ni ?arg ...?"],
                snippet: "The ni operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "ni ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "tcl::mathop::!",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::exact(1),
            hover: Some(HoverSnippet {
                summary: "logical NOT (unary)",
                synopsis: &["tcl::mathop::! ?arg ...?"],
                snippet: "The tcl::mathop::! operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "tcl::mathop::! ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
    ]
}

fn specs_11() -> Vec<CommandSpec> {
    vec![
        CommandSpec {
            name: "tcl::mathop::!=",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::exact(2),
            hover: Some(HoverSnippet {
                summary: "numeric inequality",
                synopsis: &["tcl::mathop::!= ?arg ...?"],
                snippet: "The tcl::mathop::!= operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "tcl::mathop::!= ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "tcl::mathop::%",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::exact(2),
            hover: Some(HoverSnippet {
                summary: "modulo",
                synopsis: &["tcl::mathop::% ?arg ...?"],
                snippet: "The tcl::mathop::% operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "tcl::mathop::% ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "tcl::mathop::&",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet {
                summary: "bitwise AND",
                synopsis: &["tcl::mathop::& ?arg ...?"],
                snippet: "The tcl::mathop::& operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "tcl::mathop::& ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "tcl::mathop::&&",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet {
                summary: "logical AND",
                synopsis: &["tcl::mathop::&& ?arg ...?"],
                snippet: "The tcl::mathop::&& operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "tcl::mathop::&& ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "tcl::mathop::*",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet {
                summary: "multiplication",
                synopsis: &["tcl::mathop::* ?arg ...?"],
                snippet: "The tcl::mathop::* operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "tcl::mathop::* ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
    ]
}

fn specs_12() -> Vec<CommandSpec> {
    vec![
        CommandSpec {
            name: "tcl::mathop::**",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet {
                summary: "exponentiation",
                synopsis: &["tcl::mathop::** ?arg ...?"],
                snippet: "The tcl::mathop::** operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "tcl::mathop::** ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "tcl::mathop::+",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet {
                summary: "addition",
                synopsis: &["tcl::mathop::+ ?arg ...?"],
                snippet: "The tcl::mathop::+ operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "tcl::mathop::+ ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "tcl::mathop::-",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::at_least(1),
            hover: Some(HoverSnippet {
                summary: "subtraction or negation",
                synopsis: &["tcl::mathop::- ?arg ...?"],
                snippet: "The tcl::mathop::- operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "tcl::mathop::- ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "tcl::mathop::/",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::at_least(1),
            hover: Some(HoverSnippet {
                summary: "division",
                synopsis: &["tcl::mathop::/ ?arg ...?"],
                snippet: "The tcl::mathop::/ operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "tcl::mathop::/ ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "tcl::mathop::<",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet {
                summary: "numeric less-than",
                synopsis: &["tcl::mathop::< ?arg ...?"],
                snippet: "The tcl::mathop::< operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "tcl::mathop::< ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
    ]
}

fn specs_13() -> Vec<CommandSpec> {
    vec![
        CommandSpec {
            name: "tcl::mathop::<<",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::exact(2),
            hover: Some(HoverSnippet {
                summary: "left shift",
                synopsis: &["tcl::mathop::<< ?arg ...?"],
                snippet: "The tcl::mathop::<< operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "tcl::mathop::<< ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "tcl::mathop::<=",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet {
                summary: "numeric less-or-equal",
                synopsis: &["tcl::mathop::<= ?arg ...?"],
                snippet: "The tcl::mathop::<= operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "tcl::mathop::<= ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "tcl::mathop::==",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet {
                summary: "numeric equality",
                synopsis: &["tcl::mathop::== ?arg ...?"],
                snippet: "The tcl::mathop::== operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "tcl::mathop::== ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "tcl::mathop::>",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet {
                summary: "numeric greater-than",
                synopsis: &["tcl::mathop::> ?arg ...?"],
                snippet: "The tcl::mathop::> operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "tcl::mathop::> ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "tcl::mathop::>=",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet {
                summary: "numeric greater-or-equal",
                synopsis: &["tcl::mathop::>= ?arg ...?"],
                snippet: "The tcl::mathop::>= operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "tcl::mathop::>= ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
    ]
}

fn specs_14() -> Vec<CommandSpec> {
    vec![
        CommandSpec {
            name: "tcl::mathop::>>",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::exact(2),
            hover: Some(HoverSnippet {
                summary: "right shift",
                synopsis: &["tcl::mathop::>> ?arg ...?"],
                snippet: "The tcl::mathop::>> operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "tcl::mathop::>> ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "tcl::mathop::@",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::exact(2),
            hover: Some(HoverSnippet {
                summary: "list index operator",
                synopsis: &["tcl::mathop::@ ?arg ...?"],
                snippet: "The tcl::mathop::@ operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "tcl::mathop::@ ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "tcl::mathop::^",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet {
                summary: "bitwise XOR",
                synopsis: &["tcl::mathop::^ ?arg ...?"],
                snippet: "The tcl::mathop::^ operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "tcl::mathop::^ ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "tcl::mathop::eq",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet {
                summary: "string equality",
                synopsis: &["tcl::mathop::eq ?arg ...?"],
                snippet: "The tcl::mathop::eq operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "tcl::mathop::eq ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "tcl::mathop::in",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::exact(2),
            hover: Some(HoverSnippet {
                summary: "list membership",
                synopsis: &["tcl::mathop::in ?arg ...?"],
                snippet: "The tcl::mathop::in operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "tcl::mathop::in ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
    ]
}

fn specs_15() -> Vec<CommandSpec> {
    vec![
        CommandSpec {
            name: "tcl::mathop::ne",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::exact(2),
            hover: Some(HoverSnippet {
                summary: "string inequality",
                synopsis: &["tcl::mathop::ne ?arg ...?"],
                snippet: "The tcl::mathop::ne operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "tcl::mathop::ne ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "tcl::mathop::ni",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::exact(2),
            hover: Some(HoverSnippet {
                summary: "list non-membership",
                synopsis: &["tcl::mathop::ni ?arg ...?"],
                snippet: "The tcl::mathop::ni operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "tcl::mathop::ni ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "tcl::mathop::|",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet {
                summary: "bitwise OR",
                synopsis: &["tcl::mathop::| ?arg ...?"],
                snippet: "The tcl::mathop::| operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "tcl::mathop::| ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
    ]
}

fn specs_16() -> Vec<CommandSpec> {
    vec![
        CommandSpec {
            name: "tcl::mathop::||",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet {
                summary: "logical OR",
                synopsis: &["tcl::mathop::|| ?arg ...?"],
                snippet: "The tcl::mathop::|| operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "tcl::mathop::|| ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "tcl::mathop::~",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::exact(1),
            hover: Some(HoverSnippet {
                summary: "bitwise NOT (unary)",
                synopsis: &["tcl::mathop::~ ?arg ...?"],
                snippet: "The tcl::mathop::~ operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "tcl::mathop::~ ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "|",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet {
                summary: "bitwise OR",
                synopsis: &["| ?arg ...?"],
                snippet: "The | operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "| ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "||",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::at_least(0),
            hover: Some(HoverSnippet {
                summary: "logical OR",
                synopsis: &["|| ?arg ...?"],
                snippet: "The || operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "|| ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
        CommandSpec {
            name: "~",
            dialects: None,
            traits: Traits::OPERATOR_COMMAND,
            arity: Arity::exact(1),
            hover: Some(HoverSnippet {
                summary: "bitwise NOT (unary)",
                synopsis: &["~ ?arg ...?"],
                snippet: "The ~ operator command. Available via namespace import ::tcl::mathop::*.",
                source: "Tcl man page mathop.n",
                examples: "",
                return_value: "",
            }),
            forms: &[FormSpec {
                kind: FormKind::Default,
                synopsis: "~ ?arg ...?",
            }],
            ..CommandSpec::DEFAULT
        },
    ]
}
