ltm rule /Common/__tcl_lsp_evtflow_EFB_cache_trace {
    when CLIENT_ACCEPTED {
        set evtflow_cache_id none
        set evtflow_cache_seq 0
    }
    when HTTP_REQUEST priority 50 {
        set evtflow_cache_id [HTTP::header value X-Evtflow-Request]
    }
    when CACHE_REQUEST {
        incr evtflow_cache_seq
        log local0. "EVTFLOW|run=EFB|probe=cache|event=CACHE_REQUEST|request=$evtflow_cache_id|seq=$evtflow_cache_seq|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
    when CACHE_RESPONSE {
        incr evtflow_cache_seq
        log local0. "EVTFLOW|run=EFB|probe=cache|event=CACHE_RESPONSE|request=$evtflow_cache_id|seq=$evtflow_cache_seq|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
    when CACHE_UPDATE {
        incr evtflow_cache_seq
        log local0. "EVTFLOW|run=EFB|probe=cache|event=CACHE_UPDATE|request=$evtflow_cache_id|seq=$evtflow_cache_seq|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
