ltm rule /Common/__tcl_lsp_evtflow_EFB_fastl4_trace {
    when CLIENT_ACCEPTED {
        log local0. "EVTFLOW|run=EFB|probe=fastl4|event=CLIENT_ACCEPTED|tmm=[TMM::cmp_group]:[TMM::cmp_unit]|client=[IP::client_addr]:[TCP::client_port]"
    }
    when LB_SELECTED {
        log local0. "EVTFLOW|run=EFB|probe=fastl4|event=LB_SELECTED|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
    when SERVER_CONNECTED {
        log local0. "EVTFLOW|run=EFB|probe=fastl4|event=SERVER_CONNECTED|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
    when CLIENT_CLOSED {
        log local0. "EVTFLOW|run=EFB|probe=fastl4|event=CLIENT_CLOSED|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
    when SERVER_CLOSED {
        log local0. "EVTFLOW|run=EFB|probe=fastl4|event=SERVER_CLOSED|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
