ltm rule /Common/__tcl_lsp_evtflow_EFB_mqtt_trace {
    when MQTT_CLIENT_INGRESS {
        log local0. "EVTFLOW|run=EFB|probe=mqtt|event=MQTT_CLIENT_INGRESS|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
    when MQTT_CLIENT_DATA {
        log local0. "EVTFLOW|run=EFB|probe=mqtt|event=MQTT_CLIENT_DATA|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
    when MQTT_CLIENT_EGRESS {
        log local0. "EVTFLOW|run=EFB|probe=mqtt|event=MQTT_CLIENT_EGRESS|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
    when MQTT_SERVER_INGRESS {
        log local0. "EVTFLOW|run=EFB|probe=mqtt|event=MQTT_SERVER_INGRESS|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
    when MQTT_SERVER_DATA {
        log local0. "EVTFLOW|run=EFB|probe=mqtt|event=MQTT_SERVER_DATA|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
    when MQTT_SERVER_EGRESS {
        log local0. "EVTFLOW|run=EFB|probe=mqtt|event=MQTT_SERVER_EGRESS|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
    when MQTT_CLIENT_SHUTDOWN {
        log local0. "EVTFLOW|run=EFB|probe=mqtt|event=MQTT_CLIENT_SHUTDOWN|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
