ltm rule /Common/__tcl_lsp_probe_2286_r2286i_rootlib {
proc identify {expected} {
    set command [binary format H* 6e616d6573706163652063757272656e74]
    set current [eval $command]
    return [list $expected $current [info level 0]]
}
}
