"""Dialect-specific command specs for F5 iRules.

Import all command modules here so their ``@register`` decorators fire.

Generated from F5 iRules reference documentation (community.f5.com,
clouddocs.f5.com).

Generated at: 2026-02-21T21:34:17Z
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ..models import CommandSpec
    from ..taint_hints import TaintHint

# Import curated command modules to trigger @register decorators
# Import generated command modules to trigger @register decorators
from . import (
    aaa__acct_result,  # noqa: F401
    aaa__acct_send,  # noqa: F401
    aaa__auth_result,  # noqa: F401
    aaa__auth_send,  # noqa: F401
    access2__access2_proc,  # noqa: F401
    access__acl,  # noqa: F401
    access__disable,  # noqa: F401
    access__enable,  # noqa: F401
    access__ephemeral_auth,  # noqa: F401
    access__flowid,  # noqa: F401
    access__log,  # noqa: F401
    access__oauth,  # noqa: F401
    access__perflow,  # noqa: F401
    access__policy,  # noqa: F401
    access__respond,  # noqa: F401
    access__restrict_irule_events,  # noqa: F401
    access__saml,  # noqa: F401
    access__session,  # noqa: F401
    access__user,  # noqa: F401
    access__uuid,  # noqa: F401
    acl__action,  # noqa: F401
    acl__eval,  # noqa: F401
    active_members,  # noqa: F401
    active_nodes,  # noqa: F401
    adapt__allow,  # noqa: F401
    adapt__context_create,  # noqa: F401
    adapt__context_current,  # noqa: F401
    adapt__context_delete_all,  # noqa: F401
    adapt__context_name,  # noqa: F401
    adapt__context_static,  # noqa: F401
    adapt__enable,  # noqa: F401
    adapt__preview_size,  # noqa: F401
    adapt__result,  # noqa: F401
    adapt__select,  # noqa: F401
    adapt__service_down_action,  # noqa: F401
    adapt__timeout,  # noqa: F401
    aes__decrypt,  # noqa: F401
    aes__encrypt,  # noqa: F401
    aes__key,  # noqa: F401
    after,  # noqa: F401
    am__age,  # noqa: F401
    am__application,  # noqa: F401
    am__cache,  # noqa: F401
    am__disable,  # noqa: F401
    am__expires,  # noqa: F401
    am__media_playlist,  # noqa: F401
    am__policy_node,  # noqa: F401
    antifraud__alert_additional_info,  # noqa: F401
    antifraud__alert_bait_signatures,  # noqa: F401
    antifraud__alert_component,  # noqa: F401
    antifraud__alert_defined_value,  # noqa: F401
    antifraud__alert_details,  # noqa: F401
    antifraud__alert_device_id,  # noqa: F401
    antifraud__alert_expected_value,  # noqa: F401
    antifraud__alert_fingerprint,  # noqa: F401
    antifraud__alert_forbidden_added_element,  # noqa: F401
    antifraud__alert_guid,  # noqa: F401
    antifraud__alert_html,  # noqa: F401
    antifraud__alert_http_referrer,  # noqa: F401
    antifraud__alert_id,  # noqa: F401
    antifraud__alert_license_id,  # noqa: F401
    antifraud__alert_min,  # noqa: F401
    antifraud__alert_origin,  # noqa: F401
    antifraud__alert_resolved_value,  # noqa: F401
    antifraud__alert_score,  # noqa: F401
    antifraud__alert_transaction_data,  # noqa: F401
    antifraud__alert_transaction_id,  # noqa: F401
    antifraud__alert_type,  # noqa: F401
    antifraud__alert_username,  # noqa: F401
    antifraud__alert_view_id,  # noqa: F401
    antifraud__client_id,  # noqa: F401
    antifraud__device_id,  # noqa: F401
    antifraud__disable,  # noqa: F401
    antifraud__disable_alert,  # noqa: F401
    antifraud__disable_app_layer_encryption,  # noqa: F401
    antifraud__disable_auto_transactions,  # noqa: F401
    antifraud__disable_injection,  # noqa: F401
    antifraud__disable_malware,  # noqa: F401
    antifraud__disable_phishing,  # noqa: F401
    antifraud__enable,  # noqa: F401
    antifraud__enable_log,  # noqa: F401
    antifraud__fingerprint,  # noqa: F401
    antifraud__geo,  # noqa: F401
    antifraud__guid,  # noqa: F401
    antifraud__result,  # noqa: F401
    antifraud__username,  # noqa: F401
    asm__captcha,  # noqa: F401
    asm__captcha_age,  # noqa: F401
    asm__captcha_status,  # noqa: F401
    asm__client_ip,  # noqa: F401
    asm__conviction,  # noqa: F401
    asm__deception,  # noqa: F401
    asm__disable,  # noqa: F401
    asm__enable,  # noqa: F401
    asm__fingerprint,  # noqa: F401
    asm__is_authenticated,  # noqa: F401
    asm__login_status,  # noqa: F401
    asm__microservice,  # noqa: F401
    asm__payload,  # noqa: F401
    asm__policy,  # noqa: F401
    asm__raise,  # noqa: F401
    asm__severity,  # noqa: F401
    asm__signature,  # noqa: F401
    asm__status,  # noqa: F401
    asm__support_id,  # noqa: F401
    asm__threat_campaign,  # noqa: F401
    asm__unblock,  # noqa: F401
    asm__uncaptcha,  # noqa: F401
    asm__username,  # noqa: F401
    asm__violation,  # noqa: F401
    asm__violation_data,  # noqa: F401
    asn1__decode,  # noqa: F401
    asn1__element,  # noqa: F401
    asn1__encode,  # noqa: F401
    auth__abort,  # noqa: F401
    auth__authenticate,  # noqa: F401
    auth__authenticate_continue,  # noqa: F401
    auth__cert_credential,  # noqa: F401
    auth__cert_issuer_credential,  # noqa: F401
    auth__last_event_session_id,  # noqa: F401
    auth__password_credential,  # noqa: F401
    auth__response_data,  # noqa: F401
    auth__ssl_cc_ldap_status,  # noqa: F401
    auth__ssl_cc_ldap_username,  # noqa: F401
    auth__start,  # noqa: F401
    auth__status,  # noqa: F401
    auth__subscribe,  # noqa: F401
    auth__unsubscribe,  # noqa: F401
    auth__username_credential,  # noqa: F401
    auth__wantcredential_prompt,  # noqa: F401
    auth__wantcredential_prompt_style,  # noqa: F401
    auth__wantcredential_type,  # noqa: F401
    avr__disable,  # noqa: F401
    avr__disable_cspm_injection,  # noqa: F401
    avr__enable,  # noqa: F401
    avr__log,  # noqa: F401
    b64decode,  # noqa: F401
    b64encode,  # noqa: F401
    bigproto__enable_fix_reset,  # noqa: F401
    bigtcp__release_flow,  # noqa: F401
    botdefense__action,  # noqa: F401
    botdefense__bot_anomalies,  # noqa: F401
    botdefense__bot_categories,  # noqa: F401
    botdefense__bot_name,  # noqa: F401
    botdefense__bot_signature,  # noqa: F401
    botdefense__bot_signature_category,  # noqa: F401
    botdefense__captcha_age,  # noqa: F401
    botdefense__captcha_status,  # noqa: F401
    botdefense__client_class,  # noqa: F401
    botdefense__client_type,  # noqa: F401
    botdefense__cookie_age,  # noqa: F401
    botdefense__cookie_status,  # noqa: F401
    botdefense__cs_allowed,  # noqa: F401
    botdefense__cs_attribute,  # noqa: F401
    botdefense__cs_possible,  # noqa: F401
    botdefense__device_id,  # noqa: F401
    botdefense__disable,  # noqa: F401
    botdefense__enable,  # noqa: F401
    botdefense__intent,  # noqa: F401
    botdefense__micro_service,  # noqa: F401
    botdefense__previous_action,  # noqa: F401
    botdefense__previous_request_age,  # noqa: F401
    botdefense__previous_support_id,  # noqa: F401
    botdefense__reason,  # noqa: F401
    botdefense__support_id,  # noqa: F401
    bwc__color,  # noqa: F401
    bwc__debug,  # noqa: F401
    bwc__mark,  # noqa: F401
    bwc__measure,  # noqa: F401
    bwc__policy,  # noqa: F401
    bwc__pps,  # noqa: F401
    bwc__priority,  # noqa: F401
    bwc__rate,  # noqa: F401
    cache__accept_encoding,  # noqa: F401
    cache__age,  # noqa: F401
    cache__disable,  # noqa: F401
    cache__disabled,  # noqa: F401
    cache__enable,  # noqa: F401
    cache__expire,  # noqa: F401
    cache__fresh,  # noqa: F401
    cache__header,  # noqa: F401
    cache__headers,  # noqa: F401
    cache__hits,  # noqa: F401
    cache__payload,  # noqa: F401
    cache__priority,  # noqa: F401
    cache__statskey,  # noqa: F401
    cache__trace,  # noqa: F401
    cache__uri,  # noqa: F401
    cache__useragent,  # noqa: F401
    cache__userkey,  # noqa: F401
    call,  # noqa: F401
    category__analytics,  # noqa: F401
    category__filetype,  # noqa: F401
    category__lookup,  # noqa: F401
    category__matchtype,  # noqa: F401
    category__result,  # noqa: F401
    category__safesearch,  # noqa: F401
    check,  # noqa: F401
    class_,  # noqa: F401
    classification__app,  # noqa: F401
    classification__category,  # noqa: F401
    classification__disable,  # noqa: F401
    classification__enable,  # noqa: F401
    classification__protocol,  # noqa: F401
    classification__result,  # noqa: F401
    classification__urlcat,  # noqa: F401
    classification__username,  # noqa: F401
    classify__application,  # noqa: F401
    classify__category,  # noqa: F401
    classify__defer,  # noqa: F401
    classify__disable,  # noqa: F401
    classify__urlcat,  # noqa: F401
    classify__username,  # noqa: F401
    client_addr,  # noqa: F401
    client_port,  # noqa: F401
    clientside,  # noqa: F401
    clone,  # noqa: F401
    close,  # noqa: F401
    compress__buffer_size,  # noqa: F401
    compress__disable,  # noqa: F401
    compress__enable,  # noqa: F401
    compress__gzip,  # noqa: F401
    compress__method,  # noqa: F401
    compress__nodelay,  # noqa: F401
    connect,  # noqa: F401
    connector__disable,  # noqa: F401
    connector__enable,  # noqa: F401
    connector__profile,  # noqa: F401
    connector__remap,  # noqa: F401
    cpu,  # noqa: F401
    crc32,  # noqa: F401
    crypto__decrypt,  # noqa: F401
    crypto__encrypt,  # noqa: F401
    crypto__hash,  # noqa: F401
    crypto__keygen,  # noqa: F401
    crypto__sign,  # noqa: F401
    crypto__verify,  # noqa: F401
    datagram__dns,  # noqa: F401
    datagram__ip,  # noqa: F401
    datagram__ip6,  # noqa: F401
    datagram__l2,  # noqa: F401
    datagram__tcp,  # noqa: F401
    datagram__udp,  # noqa: F401
    decode_uri,  # noqa: F401
    decompress__disable,  # noqa: F401
    decompress__enable,  # noqa: F401
    demangle__disable,  # noqa: F401
    demangle__enable,  # noqa: F401
    deprecated_stubs,  # noqa: F401
    dhcp__version,  # noqa: F401
    dhcpv4__chaddr,  # noqa: F401
    dhcpv4__ciaddr,  # noqa: F401
    dhcpv4__drop,  # noqa: F401
    dhcpv4__giaddr,  # noqa: F401
    dhcpv4__hlen,  # noqa: F401
    dhcpv4__hops,  # noqa: F401
    dhcpv4__htype,  # noqa: F401
    dhcpv4__len,  # noqa: F401
    dhcpv4__opcode,  # noqa: F401
    dhcpv4__option,  # noqa: F401
    dhcpv4__reject,  # noqa: F401
    dhcpv4__secs,  # noqa: F401
    dhcpv4__siaddr,  # noqa: F401
    dhcpv4__type,  # noqa: F401
    dhcpv4__xid,  # noqa: F401
    dhcpv4__yiaddr,  # noqa: F401
    dhcpv6__drop,  # noqa: F401
    dhcpv6__hop_count,  # noqa: F401
    dhcpv6__len,  # noqa: F401
    dhcpv6__link_address,  # noqa: F401
    dhcpv6__msg_type,  # noqa: F401
    dhcpv6__option,  # noqa: F401
    dhcpv6__peer_address,  # noqa: F401
    dhcpv6__reject,  # noqa: F401
    dhcpv6__transaction_id,  # noqa: F401
    diag__test,  # noqa: F401
    diameter__avp,  # noqa: F401
    diameter__command,  # noqa: F401
    diameter__disconnect,  # noqa: F401
    diameter__drop,  # noqa: F401
    diameter__dynamic_route_insertion,  # noqa: F401
    diameter__dynamic_route_lookup,  # noqa: F401
    diameter__header,  # noqa: F401
    diameter__host,  # noqa: F401
    diameter__is_request,  # noqa: F401
    diameter__is_response,  # noqa: F401
    diameter__is_retransmission,  # noqa: F401
    diameter__length,  # noqa: F401
    diameter__message,  # noqa: F401
    diameter__payload,  # noqa: F401
    diameter__persist,  # noqa: F401
    diameter__realm,  # noqa: F401
    diameter__respond,  # noqa: F401
    diameter__result,  # noqa: F401
    diameter__retransmission,  # noqa: F401
    diameter__retransmission_default,  # noqa: F401
    diameter__retransmission_reason,  # noqa: F401
    diameter__retransmit,  # noqa: F401
    diameter__retry,  # noqa: F401
    diameter__route_status,  # noqa: F401
    diameter__session,  # noqa: F401
    diameter__skip_capabilities_exchange,  # noqa: F401
    diameter__state,  # noqa: F401
    discard,  # noqa: F401
    dns__additional,  # noqa: F401
    dns__answer,  # noqa: F401
    dns__authority,  # noqa: F401
    dns__class,  # noqa: F401
    dns__disable,  # noqa: F401
    dns__drop,  # noqa: F401
    dns__edns0,  # noqa: F401
    dns__enable,  # noqa: F401
    dns__header,  # noqa: F401
    dns__is_wideip,  # noqa: F401
    dns__last_act,  # noqa: F401
    dns__len,  # noqa: F401
    dns__log,  # noqa: F401
    dns__name,  # noqa: F401
    dns__origin,  # noqa: F401
    dns__ptype,  # noqa: F401
    dns__query,  # noqa: F401
    dns__question,  # noqa: F401
    dns__rdata,  # noqa: F401
    dns__return,  # noqa: F401
    dns__rpz_policy,  # noqa: F401
    dns__rr,  # noqa: F401
    dns__scrape,  # noqa: F401
    dns__tsig,  # noqa: F401
    dns__ttl,  # noqa: F401
    dns__type,  # noqa: F401
    dnsmsg__header,  # noqa: F401
    dnsmsg__record,  # noqa: F401
    dnsmsg__section,  # noqa: F401
    domain,  # noqa: F401
    dosl7__disable,  # noqa: F401
    dosl7__enable,  # noqa: F401
    dosl7__health,  # noqa: F401
    dosl7__is_ip_slowdown,  # noqa: F401
    dosl7__is_mitigated,  # noqa: F401
    dosl7__profile,  # noqa: F401
    dosl7__slowdown,  # noqa: F401
    drop,  # noqa: F401
    dslite__remote_addr,  # noqa: F401
    eca__client_machine_name,  # noqa: F401
    eca__disable,  # noqa: F401
    eca__domainname,  # noqa: F401
    eca__enable,  # noqa: F401
    eca__select,  # noqa: F401
    eca__status,  # noqa: F401
    eca__username,  # noqa: F401
    event,  # noqa: F401
    fasthash,  # noqa: F401
    findclass,  # noqa: F401
    findstr,  # noqa: F401
    fix__tag,  # noqa: F401
    flow__create_related,  # noqa: F401
    flow__idle_duration,  # noqa: F401
    flow__idle_timeout,  # noqa: F401
    flow__peer,  # noqa: F401
    flow__priority,  # noqa: F401
    flow__refresh,  # noqa: F401
    flow__this,  # noqa: F401
    flowtable__count,  # noqa: F401
    flowtable__limit,  # noqa: F401
    forward,  # noqa: F401
    ftp__allow_active_mode,  # noqa: F401
    ftp__disable,  # noqa: F401
    ftp__enable,  # noqa: F401
    ftp__enforce_tls_session_reuse,  # noqa: F401
    ftp__ftps_mode,  # noqa: F401
    ftp__port,  # noqa: F401
    genericmessage__message,  # noqa: F401
    genericmessage__peer,  # noqa: F401
    genericmessage__route,  # noqa: F401
    getfield,  # noqa: F401
    gtp__clone,  # noqa: F401
    gtp__discard,  # noqa: F401
    gtp__forward,  # noqa: F401
    gtp__header,  # noqa: F401
    gtp__ie,  # noqa: F401
    gtp__length,  # noqa: F401
    gtp__message,  # noqa: F401
    gtp__new,  # noqa: F401
    gtp__parse,  # noqa: F401
    gtp__payload,  # noqa: F401
    gtp__respond,  # noqa: F401
    gtp__tunnel,  # noqa: F401
    ha__status,  # noqa: F401
    hsl__open,  # noqa: F401
    hsl__send,  # noqa: F401
    html__comment,  # noqa: F401
    html__disable,  # noqa: F401
    html__enable,  # noqa: F401
    html__tag,  # noqa: F401
    htonl,  # noqa: F401
    htons,  # noqa: F401
    http2__active,  # noqa: F401
    http2__concurrency,  # noqa: F401
    http2__disable,  # noqa: F401
    http2__disconnect,  # noqa: F401
    http2__enable,  # noqa: F401
    http2__header,  # noqa: F401
    http2__push,  # noqa: F401
    http2__requests,  # noqa: F401
    http2__stream,  # noqa: F401
    http2__version,  # noqa: F401
    http__close,  # noqa: F401
    http__collect,  # noqa: F401
    http__cookie,  # noqa: F401
    http__disable,  # noqa: F401
    http__enable,  # noqa: F401
    http__fallback,  # noqa: F401
    http__has_responded,  # noqa: F401
    http__header,  # noqa: F401
    http__host,  # noqa: F401
    http__hsts,  # noqa: F401
    http__is_keepalive,  # noqa: F401
    http__is_redirect,  # noqa: F401
    http__method,  # noqa: F401
    http__passthrough_reason,  # noqa: F401
    http__password,  # noqa: F401
    http__path,  # noqa: F401
    http__payload,  # noqa: F401
    http__proxy,  # noqa: F401
    http__query,  # noqa: F401
    http__redirect,  # noqa: F401
    http__reject_reason,  # noqa: F401
    http__release,  # noqa: F401
    http__request,  # noqa: F401
    http__request_num,  # noqa: F401
    http__respond,  # noqa: F401
    http__response,  # noqa: F401
    http__retry,  # noqa: F401
    http__status,  # noqa: F401
    http__uri,  # noqa: F401
    http__username,  # noqa: F401
    http__version,  # noqa: F401
    http_client_ip,  # noqa: F401
    http_content_len_max,  # noqa: F401
    http_cookie,  # noqa: F401
    http_header,  # noqa: F401
    http_host,  # noqa: F401
    http_method,  # noqa: F401
    http_uri,  # noqa: F401
    http_version,  # noqa: F401
    httplog__disable,  # noqa: F401
    httplog__enable,  # noqa: F401
    icap__header,  # noqa: F401
    icap__method,  # noqa: F401
    icap__status,  # noqa: F401
    icap__uri,  # noqa: F401
    ifile,  # noqa: F401
    ike__auth_success,  # noqa: F401
    ike__cert,  # noqa: F401
    ike__san_dirname,  # noqa: F401
    ike__san_dns,  # noqa: F401
    ike__san_ediparty,  # noqa: F401
    ike__san_email,  # noqa: F401
    ike__san_ipadd,  # noqa: F401
    ike__san_othername,  # noqa: F401
    ike__san_rid,  # noqa: F401
    ike__san_uri,  # noqa: F401
    ike__san_x400,  # noqa: F401
    ike__subjectaltname,  # noqa: F401
    ilx__call,  # noqa: F401
    ilx__init,  # noqa: F401
    ilx__notify,  # noqa: F401
    imap__activation_mode,  # noqa: F401
    imap__disable,  # noqa: F401
    imap__enable,  # noqa: F401
    imid,  # noqa: F401
    ip__addr,  # noqa: F401
    ip__client_addr,  # noqa: F401
    ip__hops,  # noqa: F401
    ip__idle_timeout,  # noqa: F401
    ip__ingress_drop_rate,  # noqa: F401
    ip__ingress_rate_limit,  # noqa: F401
    ip__intelligence,  # noqa: F401
    ip__local_addr,  # noqa: F401
    ip__protocol,  # noqa: F401
    ip__remote_addr,  # noqa: F401
    ip__reputation,  # noqa: F401
    ip__server_addr,  # noqa: F401
    ip__stats,  # noqa: F401
    ip__tos,  # noqa: F401
    ip__ttl,  # noqa: F401
    ip__version,  # noqa: F401
    ip_protocol,  # noqa: F401
    ip_tos,  # noqa: F401
    ip_ttl,  # noqa: F401
    ipfix__destination,  # noqa: F401
    ipfix__msg,  # noqa: F401
    ipfix__template,  # noqa: F401
    isession__deduplication,  # noqa: F401
    istats__get,  # noqa: F401
    istats__incr,  # noqa: F401
    istats__remove,  # noqa: F401
    istats__set,  # noqa: F401
    ivs_entry__result,  # noqa: F401
    json__array,  # noqa: F401
    json__create,  # noqa: F401
    json__get,  # noqa: F401
    json__object,  # noqa: F401
    json__parse,  # noqa: F401
    json__render,  # noqa: F401
    json__root,  # noqa: F401
    json__set,  # noqa: F401
    json__type,  # noqa: F401
    l7check__protocol,  # noqa: F401
    lasthop,  # noqa: F401
    lb__bias,  # noqa: F401
    lb__class,  # noqa: F401
    lb__command,  # noqa: F401
    lb__connect,  # noqa: F401
    lb__connlimit,  # noqa: F401
    lb__context_id,  # noqa: F401
    lb__detach,  # noqa: F401
    lb__down,  # noqa: F401
    lb__dst_tag,  # noqa: F401
    lb__enable_decisionlog,  # noqa: F401
    lb__mode,  # noqa: F401
    lb__persist,  # noqa: F401
    lb__prime,  # noqa: F401
    lb__queue,  # noqa: F401
    lb__reselect,  # noqa: F401
    lb__select,  # noqa: F401
    lb__server,  # noqa: F401
    lb__snat,  # noqa: F401
    lb__src_tag,  # noqa: F401
    lb__status,  # noqa: F401
    lb__up,  # noqa: F401
    ldap__activation_mode,  # noqa: F401
    ldap__disable,  # noqa: F401
    ldap__enable,  # noqa: F401
    line__get,  # noqa: F401
    line__set,  # noqa: F401
    link__lasthop,  # noqa: F401
    link__nexthop,  # noqa: F401
    link__qos,  # noqa: F401
    link__vlan_id,  # noqa: F401
    link_qos,  # noqa: F401
    listen,  # noqa: F401
    llookup,  # noqa: F401
    local_addr,  # noqa: F401
    log,  # noqa: F401
    lsn__address,  # noqa: F401
    lsn__disable,  # noqa: F401
    lsn__inbound,  # noqa: F401
    lsn__inbound_entry,  # noqa: F401
    lsn__persistence,  # noqa: F401
    lsn__persistence_entry,  # noqa: F401
    lsn__pool,  # noqa: F401
    lsn__port,  # noqa: F401
    matchclass,  # noqa: F401
    md4,  # noqa: F401
    md5,  # noqa: F401
    members,  # noqa: F401
    message__field,  # noqa: F401
    message__proto,  # noqa: F401
    message__type,  # noqa: F401
    mqtt__clean_session,  # noqa: F401
    mqtt__client_id,  # noqa: F401
    mqtt__collect,  # noqa: F401
    mqtt__disable,  # noqa: F401
    mqtt__disconnect,  # noqa: F401
    mqtt__drop,  # noqa: F401
    mqtt__dup,  # noqa: F401
    mqtt__enable,  # noqa: F401
    mqtt__insert,  # noqa: F401
    mqtt__keep_alive,  # noqa: F401
    mqtt__length,  # noqa: F401
    mqtt__message,  # noqa: F401
    mqtt__packet_id,  # noqa: F401
    mqtt__password,  # noqa: F401
    mqtt__payload,  # noqa: F401
    mqtt__protocol_name,  # noqa: F401
    mqtt__protocol_version,  # noqa: F401
    mqtt__qos,  # noqa: F401
    mqtt__release,  # noqa: F401
    mqtt__replace,  # noqa: F401
    mqtt__respond,  # noqa: F401
    mqtt__retain,  # noqa: F401
    mqtt__return_code,  # noqa: F401
    mqtt__return_code_list,  # noqa: F401
    mqtt__session_present,  # noqa: F401
    mqtt__topic,  # noqa: F401
    mqtt__type,  # noqa: F401
    mqtt__username,  # noqa: F401
    mqtt__will,  # noqa: F401
    mr__always_match_port,  # noqa: F401
    mr__available_for_routing,  # noqa: F401
    mr__collect,  # noqa: F401
    mr__connect_back_port,  # noqa: F401
    mr__connection_instance,  # noqa: F401
    mr__connection_mode,  # noqa: F401
    mr__equivalent_transport,  # noqa: F401
    mr__flow_id,  # noqa: F401
    mr__ignore_peer_port,  # noqa: F401
    mr__instance,  # noqa: F401
    mr__max_retries,  # noqa: F401
    mr__message,  # noqa: F401
    mr__payload,  # noqa: F401
    mr__peer,  # noqa: F401
    mr__prime,  # noqa: F401
    mr__protocol,  # noqa: F401
    mr__release,  # noqa: F401
    mr__restore,  # noqa: F401
    mr__retry,  # noqa: F401
    mr__return,  # noqa: F401
    mr__store,  # noqa: F401
    mr__stream,  # noqa: F401
    mr__transport,  # noqa: F401
    name__lookup,  # noqa: F401
    name__response,  # noqa: F401
    nexthop,  # noqa: F401
    node,  # noqa: F401
    nodes,  # noqa: F401
    nsh__chain,  # noqa: F401
    nsh__context,  # noqa: F401
    nsh__md1,  # noqa: F401
    nsh__mocksf,  # noqa: F401
    nsh__path_id,  # noqa: F401
    nsh__service_index,  # noqa: F401
    ntlm__disable,  # noqa: F401
    ntlm__enable,  # noqa: F401
    ntohl,  # noqa: F401
    ntohs,  # noqa: F401
    offbox__request,  # noqa: F401
    oneconnect__detach,  # noqa: F401
    oneconnect__label,  # noqa: F401
    oneconnect__reuse,  # noqa: F401
    oneconnect__select,  # noqa: F401
    pcp__reject,  # noqa: F401
    pcp__request,  # noqa: F401
    pcp__response,  # noqa: F401
    peer,  # noqa: F401
    pem__disable,  # noqa: F401
    pem__enable,  # noqa: F401
    pem__flow,  # noqa: F401
    pem__session,  # noqa: F401
    pem__subscriber,  # noqa: F401
    pem_dtos,  # noqa: F401
    persist,  # noqa: F401
    policy__controls,  # noqa: F401
    policy__names,  # noqa: F401
    policy__rules,  # noqa: F401
    policy__targets,  # noqa: F401
    pool,  # noqa: F401
    pop3__activation_mode,  # noqa: F401
    pop3__disable,  # noqa: F401
    pop3__enable,  # noqa: F401
    priority,  # noqa: F401
    proc,  # noqa: F401
    profile__access,  # noqa: F401
    profile__antifraud,  # noqa: F401
    profile__auth,  # noqa: F401
    profile__avr,  # noqa: F401
    profile__clientssl,  # noqa: F401
    profile__diameter,  # noqa: F401
    profile__exchange,  # noqa: F401
    profile__exists,  # noqa: F401
    profile__fasthttp,  # noqa: F401
    profile__fastl4,  # noqa: F401
    profile__ftp,  # noqa: F401
    profile__http,  # noqa: F401
    profile__httpcompression,  # noqa: F401
    profile__list,  # noqa: F401
    profile__oneconnect,  # noqa: F401
    profile__persist,  # noqa: F401
    profile__serverssl,  # noqa: F401
    profile__stream,  # noqa: F401
    profile__tcp,  # noqa: F401
    profile__tftp,  # noqa: F401
    profile__udp,  # noqa: F401
    profile__vdi,  # noqa: F401
    profile__webacceleration,  # noqa: F401
    profile__xml,  # noqa: F401
    protocol_inspection__disable,  # noqa: F401
    protocol_inspection__id,  # noqa: F401
    psc__aaa_reporting_interval,  # noqa: F401
    psc__attr,  # noqa: F401
    psc__calling_id,  # noqa: F401
    psc__imeisv,  # noqa: F401
    psc__imsi,  # noqa: F401
    psc__ip_address,  # noqa: F401
    psc__lease_time,  # noqa: F401
    psc__policy,  # noqa: F401
    psc__subscriber_id,  # noqa: F401
    psc__tower_id,  # noqa: F401
    psc__user_name,  # noqa: F401
    psm__ftp__disable,  # noqa: F401
    psm__ftp__enable,  # noqa: F401
    psm__http__disable,  # noqa: F401
    psm__http__enable,  # noqa: F401
    psm__smtp__disable,  # noqa: F401
    psm__smtp__enable,  # noqa: F401
    qoe__disable,  # noqa: F401
    qoe__enable,  # noqa: F401
    qoe__video,  # noqa: F401
    radius__avp,  # noqa: F401
    radius__code,  # noqa: F401
    radius__id,  # noqa: F401
    radius__rtdom,  # noqa: F401
    radius__subscriber,  # noqa: F401
    radius_authenticate,  # noqa: F401
    rateclass,  # noqa: F401
    recv,  # noqa: F401
    redirect,  # noqa: F401
    reject,  # noqa: F401
    relate_client,  # noqa: F401
    relate_server,  # noqa: F401
    remote_addr,  # noqa: F401
    resolv__lookup,  # noqa: F401
    resolver__name_lookup,  # noqa: F401
    resolver__summarize,  # noqa: F401
    rest__send,  # noqa: F401
    rewrite__disable,  # noqa: F401
    rewrite__enable,  # noqa: F401
    rewrite__payload,  # noqa: F401
    rewrite__post_process,  # noqa: F401
    rmd160,  # noqa: F401
    route__age,  # noqa: F401
    route__bandwidth,  # noqa: F401
    route__clear,  # noqa: F401
    route__cwnd,  # noqa: F401
    route__domain,  # noqa: F401
    route__expiration,  # noqa: F401
    route__mtu,  # noqa: F401
    route__rtt,  # noqa: F401
    route__rttvar,  # noqa: F401
    rtsp__collect,  # noqa: F401
    rtsp__header,  # noqa: F401
    rtsp__method,  # noqa: F401
    rtsp__msg_source,  # noqa: F401
    rtsp__payload,  # noqa: F401
    rtsp__release,  # noqa: F401
    rtsp__respond,  # noqa: F401
    rtsp__status,  # noqa: F401
    rtsp__uri,  # noqa: F401
    rtsp__version,  # noqa: F401
    sctp__client_port,  # noqa: F401
    sctp__collect,  # noqa: F401
    sctp__local_port,  # noqa: F401
    sctp__mss,  # noqa: F401
    sctp__payload,  # noqa: F401
    sctp__ppi,  # noqa: F401
    sctp__release,  # noqa: F401
    sctp__remote_port,  # noqa: F401
    sctp__respond,  # noqa: F401
    sctp__rto_initial,  # noqa: F401
    sctp__rto_max,  # noqa: F401
    sctp__rto_min,  # noqa: F401
    sctp__sack_timeout,  # noqa: F401
    sctp__server_port,  # noqa: F401
    sdp__field,  # noqa: F401
    sdp__media,  # noqa: F401
    sdp__session_id,  # noqa: F401
    send,  # noqa: F401
    server_addr,  # noqa: F401
    server_port,  # noqa: F401
    serverside,  # noqa: F401
    session,  # noqa: F401
    sha1,  # noqa: F401
    sha256,  # noqa: F401
    sha384,  # noqa: F401
    sha512,  # noqa: F401
    sharedvar,  # noqa: F401
    sip__call_id,  # noqa: F401
    sip__discard,  # noqa: F401
    sip__from,  # noqa: F401
    sip__header,  # noqa: F401
    sip__message,  # noqa: F401
    sip__method,  # noqa: F401
    sip__payload,  # noqa: F401
    sip__persist,  # noqa: F401
    sip__record_route,  # noqa: F401
    sip__respond,  # noqa: F401
    sip__response,  # noqa: F401
    sip__route,  # noqa: F401
    sip__route_status,  # noqa: F401
    sip__to,  # noqa: F401
    sip__uri,  # noqa: F401
    sip__via,  # noqa: F401
    sipalg__hairpin,  # noqa: F401
    sipalg__hairpin_default,  # noqa: F401
    sipalg__nonregister_subscriber_listener,  # noqa: F401
    smtps__activation_mode,  # noqa: F401
    smtps__disable,  # noqa: F401
    smtps__enable,  # noqa: F401
    snat,  # noqa: F401
    snatpool,  # noqa: F401
    socks__allowed,  # noqa: F401
    socks__destination,  # noqa: F401
    socks__version,  # noqa: F401
    sse__field,  # noqa: F401
    ssl__allow_dynamic_record_sizing,  # noqa: F401
    ssl__allow_nonssl,  # noqa: F401
    ssl__alpn,  # noqa: F401
    ssl__authenticate,  # noqa: F401
    ssl__c3d,  # noqa: F401
    ssl__cert,  # noqa: F401
    ssl__cert_constraint,  # noqa: F401
    ssl__cipher,  # noqa: F401
    ssl__clientrandom,  # noqa: F401
    ssl__collect,  # noqa: F401
    ssl__disable,  # noqa: F401
    ssl__enable,  # noqa: F401
    ssl__extensions,  # noqa: F401
    ssl__forward_proxy,  # noqa: F401
    ssl__handshake,  # noqa: F401
    ssl__is_renegotiation_secure,  # noqa: F401
    ssl__maximum_record_size,  # noqa: F401
    ssl__mode,  # noqa: F401
    ssl__modssl_sessionid_headers,  # noqa: F401
    ssl__nextproto,  # noqa: F401
    ssl__payload,  # noqa: F401
    ssl__profile,  # noqa: F401
    ssl__release,  # noqa: F401
    ssl__renegotiate,  # noqa: F401
    ssl__respond,  # noqa: F401
    ssl__secure_renegotiation,  # noqa: F401
    ssl__session,  # noqa: F401
    ssl__sessionid,  # noqa: F401
    ssl__sessionsecret,  # noqa: F401
    ssl__sessionticket,  # noqa: F401
    ssl__sni,  # noqa: F401
    ssl__tls13_secret,  # noqa: F401
    ssl__unclean_shutdown,  # noqa: F401
    ssl__verify_result,  # noqa: F401
    stats__get,  # noqa: F401
    stats__incr,  # noqa: F401
    stats__set,  # noqa: F401
    stats__setmax,  # noqa: F401
    stats__setmin,  # noqa: F401
    stream__disable,  # noqa: F401
    stream__enable,  # noqa: F401
    stream__encoding,  # noqa: F401
    stream__expression,  # noqa: F401
    stream__match,  # noqa: F401
    stream__max_matchsize,  # noqa: F401
    stream__replace,  # noqa: F401
    substr,  # noqa: F401
    table,  # noqa: F401
    tap__action,  # noqa: F401
    tap__config,  # noqa: F401
    tap__insight,  # noqa: F401
    tap__insight_requested,  # noqa: F401
    tap__score,  # noqa: F401
    tcp__abc,  # noqa: F401
    tcp__analytics,  # noqa: F401
    tcp__autowin,  # noqa: F401
    tcp__bandwidth,  # noqa: F401
    tcp__client_port,  # noqa: F401
    tcp__close,  # noqa: F401
    tcp__collect,  # noqa: F401
    tcp__congestion,  # noqa: F401
    tcp__delayed_ack,  # noqa: F401
    tcp__dsack,  # noqa: F401
    tcp__earlyrxmit,  # noqa: F401
    tcp__ecn,  # noqa: F401
    tcp__enhanced_loss_recovery,  # noqa: F401
    tcp__idletime,  # noqa: F401
    tcp__keepalive,  # noqa: F401
    tcp__limxmit,  # noqa: F401
    tcp__local_port,  # noqa: F401
    tcp__lossfilter,  # noqa: F401
    tcp__lossfilterburst,  # noqa: F401
    tcp__lossfilterrate,  # noqa: F401
    tcp__mss,  # noqa: F401
    tcp__nagle,  # noqa: F401
    tcp__naglemode,  # noqa: F401
    tcp__naglestate,  # noqa: F401
    tcp__notify,  # noqa: F401
    tcp__offset,  # noqa: F401
    tcp__option,  # noqa: F401
    tcp__pacing,  # noqa: F401
    tcp__payload,  # noqa: F401
    tcp__proxybuffer,  # noqa: F401
    tcp__proxybufferhigh,  # noqa: F401
    tcp__proxybufferlow,  # noqa: F401
    tcp__push_flag,  # noqa: F401
    tcp__rcv_scale,  # noqa: F401
    tcp__rcv_size,  # noqa: F401
    tcp__recvwnd,  # noqa: F401
    tcp__release,  # noqa: F401
    tcp__remote_port,  # noqa: F401
    tcp__respond,  # noqa: F401
    tcp__rexmt_thresh,  # noqa: F401
    tcp__rt_metrics_timeout,  # noqa: F401
    tcp__rto,  # noqa: F401
    tcp__rtt,  # noqa: F401
    tcp__rttvar,  # noqa: F401
    tcp__sendbuf,  # noqa: F401
    tcp__server_port,  # noqa: F401
    tcp__setmss,  # noqa: F401
    tcp__snd_cwnd,  # noqa: F401
    tcp__snd_scale,  # noqa: F401
    tcp__snd_ssthresh,  # noqa: F401
    tcp__snd_wnd,  # noqa: F401
    tcp__unused_port,  # noqa: F401
    tcpdump,  # noqa: F401
    tds__msg,  # noqa: F401
    tds__session,  # noqa: F401
    timing,  # noqa: F401
    tmm__cmp_count,  # noqa: F401
    tmm__cmp_group,  # noqa: F401
    tmm__cmp_groups,  # noqa: F401
    tmm__cmp_primary_group,  # noqa: F401
    tmm__cmp_unit,  # noqa: F401
    traffic_group,  # noqa: F401
    translate,  # noqa: F401
    udp__client_port,  # noqa: F401
    udp__debug_queue,  # noqa: F401
    udp__drop,  # noqa: F401
    udp__hold,  # noqa: F401
    udp__local_port,  # noqa: F401
    udp__max_buf_pkts,  # noqa: F401
    udp__max_rate,  # noqa: F401
    udp__mss,  # noqa: F401
    udp__payload,  # noqa: F401
    udp__release,  # noqa: F401
    udp__remote_port,  # noqa: F401
    udp__respond,  # noqa: F401
    udp__sendbuffer,  # noqa: F401
    udp__server_port,  # noqa: F401
    udp__unused_port,  # noqa: F401
    uniq_ordered_ip_list,  # noqa: F401
    uniq_sorted_ip_list,  # noqa: F401
    uri__basename,  # noqa: F401
    uri__compare,  # noqa: F401
    uri__decode,  # noqa: F401
    uri__encode,  # noqa: F401
    uri__host,  # noqa: F401
    uri__path,  # noqa: F401
    uri__port,  # noqa: F401
    uri__protocol,  # noqa: F401
    uri__query,  # noqa: F401
    urlcatblindquery,  # noqa: F401
    urlcatquery,  # noqa: F401
    use,  # noqa: F401
    validate__protocol,  # noqa: F401
    vdi__disable,  # noqa: F401
    vdi__enable,  # noqa: F401
    virtual,  # noqa: F401
    vlan_id,  # noqa: F401
    wam__disable,  # noqa: F401
    wam__enable,  # noqa: F401
    websso__disable,  # noqa: F401
    websso__enable,  # noqa: F401
    websso__select,  # noqa: F401
    when,  # noqa: F401
    whereis,  # noqa: F401
    ws__collect,  # noqa: F401
    ws__disconnect,  # noqa: F401
    ws__enabled,  # noqa: F401
    ws__frame,  # noqa: F401
    ws__masking,  # noqa: F401
    ws__message,  # noqa: F401
    ws__payload,  # noqa: F401
    ws__payload_ivs,  # noqa: F401
    ws__payload_processing,  # noqa: F401
    ws__release,  # noqa: F401
    ws__request,  # noqa: F401
    ws__response,  # noqa: F401
    x509__cert_fields,  # noqa: F401
    x509__extensions,  # noqa: F401
    x509__hash,  # noqa: F401
    x509__issuer,  # noqa: F401
    x509__not_valid_after,  # noqa: F401
    x509__not_valid_before,  # noqa: F401
    x509__pem2der,  # noqa: F401
    x509__serial_number,  # noqa: F401
    x509__signature_algorithm,  # noqa: F401
    x509__subject,  # noqa: F401
    x509__subject_public_key,  # noqa: F401
    x509__subject_public_key_rsa_bits,  # noqa: F401
    x509__subject_public_key_type,  # noqa: F401
    x509__verify_cert_error_string,  # noqa: F401
    x509__version,  # noqa: F401
    x509__whole,  # noqa: F401
    xff_list,  # noqa: F401
    xff_uniq_ordered_ip_list,  # noqa: F401
    xff_uniq_sorted_ip_list,  # noqa: F401
    xlat__listen,  # noqa: F401
    xlat__listen_lifetime,  # noqa: F401
    xlat__src_addr,  # noqa: F401
    xlat__src_config,  # noqa: F401
    xlat__src_endpoint_reservation,  # noqa: F401
    xlat__src_nat_valid_range,  # noqa: F401
    xlat__src_port,  # noqa: F401
    xml__disable,  # noqa: F401
    xml__enable,  # noqa: F401
    xml__payload,  # noqa: F401
)
from ._base import _REGISTRY


def irules_command_specs() -> tuple[CommandSpec, ...]:
    """Return iRules-specific command specs from all registered classes."""
    return tuple(cls.spec() for cls in _REGISTRY)


def irules_taint_hints() -> dict[str, TaintHint]:
    """Return taint hints from all registered iRules classes."""
    return {cls.name: h for cls in _REGISTRY if (h := cls.taint_hints()) is not None}
