# Enriched from F5 iRules reference documentation.
"""ACCESS::saml -- Access or manipulate SAML related messages."""

from __future__ import annotations

from ....compiler.side_effects import ConnectionSide, SideEffect, SideEffectTarget
from .._base import CommandDef, make_av
from ..models import CommandSpec, FormKind, FormSpec, HoverSnippet, SubCommand, ValidationSpec
from ..namespace_models import EventRequires
from ..signatures import Arity
from ._base import _IRULES_ONLY, register

_SOURCE = "https://clouddocs.f5.com/api/irules/ACCESS__saml.html"


_av = make_av(_SOURCE)


@register
class AccessSamlCommand(CommandDef):
    name = "ACCESS::saml"

    @classmethod
    def spec(cls) -> CommandSpec:
        return CommandSpec(
            name="ACCESS::saml",
            dialects=_IRULES_ONLY,
            hover=HoverSnippet(
                summary="Access or manipulate SAML related messages.",
                synopsis=(
                    "ACCESS::saml authn (CONTENT)?",
                    "ACCESS::saml assertion (CONTENT)?",
                    "ACCESS::saml slo_req (CONTENT)?",
                    "ACCESS::saml slo_resp (CONTENT)?",
                ),
                snippet=(
                    "The different ACCESS::saml sub-commands allow you to\n"
                    "access or manipulate outgoing SAML request/response messages including\n"
                    "authentication request, assertion, single logout request and response.\n"
                    "\n"
                    "ACCESS::saml authn\n"
                    "\n"
                    "     * Returns the SAML authentication request payload generated by BIG-IP\n"
                    "       as service provider. Sets the SAML authentication request if given.\n"
                    "\n"
                    "ACCESS::saml assertion\n"
                    "\n"
                    "     * Returns the SAML assertion payload generated by BIG-IP as\n"
                    "       identity provider. Sets the SAML assertion if given."
                ),
                source=_SOURCE,
                examples=(
                    "when ACCESS_SAML_AUTHN {\n"
                    "        # Variable authn_request is set to SAML authentication request payload generated.\n"
                    "        set authn_request [ ACCESS::saml authn ]\n"
                    "        # The value set in variable authn_request is logged.\n"
                    '        log -noname accesscontrol.local1.notice "AuthN Req before modification: $authn_request"\n'
                    "        # The NameIDPolicy format in authn_request is modified from 'unspecified' to 'emailAddress' and set in variable new_authn_request."
                ),
            ),
            forms=(
                FormSpec(
                    kind=FormKind.DEFAULT,
                    synopsis="ACCESS::saml <subcommand> ?content?",
                    arg_values={
                        0: (
                            _av(
                                "authn",
                                "Get/set SAML authentication request.",
                                "ACCESS::saml authn ?content?",
                            ),
                            _av(
                                "assertion",
                                "Get/set SAML assertion.",
                                "ACCESS::saml assertion ?content?",
                            ),
                            _av(
                                "slo_req",
                                "Get/set SAML single logout request.",
                                "ACCESS::saml slo_req ?content?",
                            ),
                            _av(
                                "slo_resp",
                                "Get/set SAML single logout response.",
                                "ACCESS::saml slo_resp ?content?",
                            ),
                        )
                    },
                ),
            ),
            validation=ValidationSpec(
                arity=Arity(),
            ),
            event_requires=EventRequires(profiles=frozenset({"ACCESS"})),
            side_effect_hints=(
                SideEffect(
                    target=SideEffectTarget.APM_STATE,
                    reads=True,
                    connection_side=ConnectionSide.BOTH,
                ),
            ),
            subcommands={
                sub: SubCommand(
                    name=sub,
                    arity=Arity(0, 1),
                    detail=detail,
                    synopsis=f"ACCESS::saml {sub} ?content?",
                    pure=True,
                    mutator=True,
                    side_effect_hints=(
                        SideEffect(
                            target=SideEffectTarget.APM_STATE,
                            reads=True,
                            writes=True,
                            connection_side=ConnectionSide.BOTH,
                        ),
                    ),
                )
                for sub, detail in (
                    ("authn", "Get/set SAML authentication request."),
                    ("assertion", "Get/set SAML assertion."),
                    ("slo_req", "Get/set SAML single logout request."),
                    ("slo_resp", "Get/set SAML single logout response."),
                )
            },
        )
