# Enriched from F5 iRules reference documentation.
"""ANTIFRAUD::device_id -- Returns device id generated by bigip."""

from __future__ import annotations

from ....compiler.side_effects import ConnectionSide, SideEffect, SideEffectTarget
from .._base import CommandDef
from ..models import CommandSpec, FormKind, FormSpec, HoverSnippet, ValidationSpec
from ..namespace_models import EventRequires
from ..signatures import Arity
from ._base import _IRULES_ONLY, register

_SOURCE = "https://clouddocs.f5.com/api/irules/ANTIFRAUD__device_id.html"


@register
class AntifraudDeviceIdCommand(CommandDef):
    name = "ANTIFRAUD::device_id"

    @classmethod
    def spec(cls) -> CommandSpec:
        return CommandSpec(
            name="ANTIFRAUD::device_id",
            dialects=_IRULES_ONLY,
            hover=HoverSnippet(
                summary="Returns device id generated by bigip.",
                synopsis=("ANTIFRAUD::device_id",),
                snippet="Returns device id generated by bigip.",
                source=_SOURCE,
                examples=(
                    "when ANTIFRAUD_ALERT {\n"
                    '                log local0. "device id: [ANTIFRAUD::device_id]."\n'
                    "            }"
                ),
                return_value="Returns device id generated by bigip.",
            ),
            forms=(
                FormSpec(
                    kind=FormKind.DEFAULT,
                    synopsis="ANTIFRAUD::device_id",
                ),
            ),
            validation=ValidationSpec(
                arity=Arity(),
            ),
            event_requires=EventRequires(),
            side_effect_hints=(
                SideEffect(
                    target=SideEffectTarget.ASM_STATE,
                    reads=True,
                    connection_side=ConnectionSide.CLIENT,
                ),
            ),
        )
