ltm rule /Common/__tcl_lsp_evtflow_efd_clientssl_alert_unknown_event {
    when CLIENTSSL_ALERT {
        log local0. "EVTFLOW2|run=EFD|event=CLIENTSSL_ALERT|tmm=[TMM::cmp_group]:[TMM::cmp_unit]|probe=literal-control"
    }
}
