[package]
name = "bpf-tcl-codegen"
description = "eBPF (and later WASM) code generation for the BPF-Tcl DSL"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
bpf-tcl-ir = { path = "../bpf-tcl-ir" }
tcl-lexer = { path = "../tcl-lexer" }

[lints]
workspace = true
