from __future__ import annotations

from ..models import (
    BigipObjectKindSpec,
    BigipObjectSpec,
    BigipPropertySpec,
)
from ._base import register


@register
def register_spec() -> BigipObjectSpec:
    return BigipObjectSpec(
        kind_spec=BigipObjectKindSpec(
            "apm_profile_connectivity",
            module="apm",
            object_types=("profile connectivity",),
        ),
        header_types=(("apm", "profile connectivity"),),
        properties=(
            BigipPropertySpec(
                name="adaptive-compression",
                value_type="enum",
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
                default="enabled",
            ),
            BigipPropertySpec(
                name="app-service",
                value_type="string",
                allow_none=True,
                default="none",
            ),
            BigipPropertySpec(
                name="citrix-client-bundle",
                value_type="reference",
                references=("apm_resource_remote_desktop_citrix_client_bundle",),
                default="default-citrix-client-bundle",
            ),
            BigipPropertySpec(
                name="client-policy",
                value_type="list",
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
                block=(
                    BigipPropertySpec(
                        name="android-ec",
                        value_type="unknown",
                        in_sections=("client-policy",),
                        shape_kind="object",
                    ),
                    BigipPropertySpec(
                        name="android-ep",
                        value_type="unknown",
                        in_sections=("client-policy",),
                        shape_kind="object",
                    ),
                    BigipPropertySpec(
                        name="chromeos-ec",
                        value_type="unknown",
                        in_sections=("client-policy",),
                        shape_kind="object",
                    ),
                    BigipPropertySpec(
                        name="ec",
                        value_type="unknown",
                        in_sections=("client-policy",),
                        shape_kind="object",
                    ),
                    BigipPropertySpec(
                        name="ios-ec",
                        value_type="unknown",
                        in_sections=("client-policy",),
                        shape_kind="object",
                    ),
                    BigipPropertySpec(
                        name="ios-ep",
                        value_type="unknown",
                        in_sections=("client-policy",),
                        shape_kind="object",
                    ),
                    BigipPropertySpec(
                        name="macos-ec",
                        value_type="unknown",
                        in_sections=("client-policy",),
                        shape_kind="object",
                    ),
                    BigipPropertySpec(
                        name="oauth",
                        value_type="unknown",
                        in_sections=("client-policy",),
                        shape_kind="object",
                    ),
                    BigipPropertySpec(
                        name="servers",
                        value_type="list",
                        in_sections=("client-policy",),
                    ),
                ),
            ),
            BigipPropertySpec(
                name="android-ec",
                value_type="unknown",
                in_sections=("client-policy",),
                shape_kind="object",
                block=(
                    BigipPropertySpec(
                        name="device-lock-complexity",
                        value_type="enum",
                        in_sections=("client-policy", "android-ec"),
                        allow_none=True,
                        enum_values=("high", "low", "medium", "none"),
                    ),
                    BigipPropertySpec(
                        name="device-lock-method",
                        value_type="enum",
                        in_sections=("client-policy", "android-ec"),
                        enum_values=("alphabetic", "alphanumeric", "any", "numeric"),
                    ),
                    BigipPropertySpec(
                        name="enable-mobilesafe",
                        value_type="enum",
                        in_sections=("client-policy", "android-ec"),
                        enum_values=("false", "true"),
                        shape_kind="boolean",
                        default="false",
                    ),
                    BigipPropertySpec(
                        name="enforce-device-lock",
                        value_type="enum",
                        in_sections=("client-policy", "android-ec"),
                        enum_values=("false", "true"),
                        shape_kind="boolean",
                        default="true",
                    ),
                    BigipPropertySpec(
                        name="enforce-logon-mode",
                        value_type="enum",
                        in_sections=("client-policy", "android-ec"),
                        enum_values=("false", "true"),
                        shape_kind="boolean",
                        default="false",
                    ),
                    BigipPropertySpec(
                        name="logon-mode",
                        value_type="enum",
                        in_sections=("client-policy", "android-ec"),
                        enum_values=("native", "web"),
                        default="native",
                    ),
                    BigipPropertySpec(
                        name="max-inactivity-time",
                        value_type="integer",
                        in_sections=("client-policy", "android-ec"),
                        default="5",
                    ),
                    BigipPropertySpec(
                        name="min-passcode-length",
                        value_type="integer",
                        in_sections=("client-policy", "android-ec"),
                        required=True,
                        default="4",
                    ),
                    BigipPropertySpec(
                        name="require-device-auth",
                        value_type="enum",
                        in_sections=("client-policy", "android-ec"),
                        enum_values=("false", "true"),
                        shape_kind="boolean",
                        default="false",
                    ),
                    BigipPropertySpec(
                        name="save-password",
                        value_type="enum",
                        in_sections=("client-policy", "android-ec"),
                        enum_values=("false", "true"),
                        shape_kind="boolean",
                        default="false",
                    ),
                    BigipPropertySpec(
                        name="save-password-method",
                        value_type="enum",
                        in_sections=("client-policy", "android-ec"),
                        enum_values=("disk", "memory"),
                        default="disk",
                    ),
                    BigipPropertySpec(
                        name="save-password-timeout",
                        value_type="integer",
                        in_sections=("client-policy", "android-ec"),
                        default="240",
                    ),
                ),
            ),
            BigipPropertySpec(
                name="device-lock-complexity",
                value_type="enum",
                in_sections=("client-policy", "android-ec"),
                allow_none=True,
                enum_values=("high", "low", "medium", "none"),
            ),
            BigipPropertySpec(
                name="device-lock-method",
                value_type="enum",
                in_sections=("client-policy", "android-ec"),
                enum_values=("alphabetic", "alphanumeric", "any", "numeric"),
            ),
            BigipPropertySpec(
                name="enable-mobilesafe",
                value_type="enum",
                in_sections=("client-policy", "android-ec"),
                enum_values=("false", "true"),
                shape_kind="boolean",
                default="false",
            ),
            BigipPropertySpec(
                name="enforce-device-lock",
                value_type="enum",
                in_sections=("client-policy", "android-ec"),
                enum_values=("false", "true"),
                shape_kind="boolean",
                default="true",
            ),
            BigipPropertySpec(
                name="enforce-logon-mode",
                value_type="enum",
                in_sections=("client-policy", "android-ec"),
                enum_values=("false", "true"),
                shape_kind="boolean",
                default="false",
            ),
            BigipPropertySpec(
                name="logon-mode",
                value_type="enum",
                in_sections=("client-policy", "android-ec"),
                enum_values=("native", "web"),
                default="native",
            ),
            BigipPropertySpec(
                name="max-inactivity-time",
                value_type="integer",
                in_sections=("client-policy", "android-ec"),
                default="5",
            ),
            BigipPropertySpec(
                name="min-passcode-length",
                value_type="integer",
                in_sections=("client-policy", "android-ec"),
                required=True,
                default="4",
            ),
            BigipPropertySpec(
                name="require-device-auth",
                value_type="enum",
                in_sections=("client-policy", "android-ec"),
                enum_values=("false", "true"),
                shape_kind="boolean",
                default="false",
            ),
            BigipPropertySpec(
                name="save-password",
                value_type="enum",
                in_sections=("client-policy", "android-ec"),
                enum_values=("false", "true"),
                shape_kind="boolean",
                default="false",
            ),
            BigipPropertySpec(
                name="save-password-method",
                value_type="enum",
                in_sections=("client-policy", "android-ec"),
                enum_values=("disk", "memory"),
                default="disk",
            ),
            BigipPropertySpec(
                name="save-password-timeout",
                value_type="integer",
                in_sections=("client-policy", "android-ec"),
                default="240",
            ),
            BigipPropertySpec(
                name="android-ep",
                value_type="unknown",
                in_sections=("client-policy",),
                shape_kind="object",
                block=(
                    BigipPropertySpec(
                        name="device-lock-method",
                        value_type="enum",
                        in_sections=("client-policy", "android-ep"),
                        enum_values=("alphabetic", "alphanumeric", "any", "numeric"),
                    ),
                    BigipPropertySpec(
                        name="enable-mobilesafe",
                        value_type="enum",
                        in_sections=("client-policy", "android-ep"),
                        enum_values=("false", "true"),
                        shape_kind="boolean",
                        default="false",
                    ),
                    BigipPropertySpec(
                        name="enforce-device-lock",
                        value_type="enum",
                        in_sections=("client-policy", "android-ep"),
                        enum_values=("false", "true"),
                        shape_kind="boolean",
                        default="true",
                    ),
                    BigipPropertySpec(
                        name="enforce-logon-mode",
                        value_type="enum",
                        in_sections=("client-policy", "android-ep"),
                        enum_values=("false", "true"),
                        shape_kind="boolean",
                        default="false",
                    ),
                    BigipPropertySpec(
                        name="logon-mode",
                        value_type="enum",
                        in_sections=("client-policy", "android-ep"),
                        enum_values=("native", "web"),
                        default="native",
                    ),
                    BigipPropertySpec(
                        name="max-inactivity-time",
                        value_type="integer",
                        in_sections=("client-policy", "android-ep"),
                        default="5",
                    ),
                    BigipPropertySpec(
                        name="min-passcode-length",
                        value_type="integer",
                        in_sections=("client-policy", "android-ep"),
                        required=True,
                        default="4",
                    ),
                    BigipPropertySpec(
                        name="save-password",
                        value_type="enum",
                        in_sections=("client-policy", "android-ep"),
                        enum_values=("false", "true"),
                        shape_kind="boolean",
                        default="false",
                    ),
                    BigipPropertySpec(
                        name="save-password-method",
                        value_type="enum",
                        in_sections=("client-policy", "android-ep"),
                        enum_values=("disk", "memory"),
                        default="disk",
                    ),
                    BigipPropertySpec(
                        name="save-password-timeout",
                        value_type="integer",
                        in_sections=("client-policy", "android-ep"),
                        default="240",
                    ),
                ),
            ),
            BigipPropertySpec(
                name="device-lock-method",
                value_type="enum",
                in_sections=("client-policy", "android-ep"),
                enum_values=("alphabetic", "alphanumeric", "any", "numeric"),
            ),
            BigipPropertySpec(
                name="enable-mobilesafe",
                value_type="enum",
                in_sections=("client-policy", "android-ep"),
                enum_values=("false", "true"),
                shape_kind="boolean",
                default="false",
            ),
            BigipPropertySpec(
                name="enforce-device-lock",
                value_type="enum",
                in_sections=("client-policy", "android-ep"),
                enum_values=("false", "true"),
                shape_kind="boolean",
                default="true",
            ),
            BigipPropertySpec(
                name="enforce-logon-mode",
                value_type="enum",
                in_sections=("client-policy", "android-ep"),
                enum_values=("false", "true"),
                shape_kind="boolean",
                default="false",
            ),
            BigipPropertySpec(
                name="logon-mode",
                value_type="enum",
                in_sections=("client-policy", "android-ep"),
                enum_values=("native", "web"),
                default="native",
            ),
            BigipPropertySpec(
                name="max-inactivity-time",
                value_type="integer",
                in_sections=("client-policy", "android-ep"),
                default="5",
            ),
            BigipPropertySpec(
                name="min-passcode-length",
                value_type="integer",
                in_sections=("client-policy", "android-ep"),
                required=True,
                default="4",
            ),
            BigipPropertySpec(
                name="save-password",
                value_type="enum",
                in_sections=("client-policy", "android-ep"),
                enum_values=("false", "true"),
                shape_kind="boolean",
                default="false",
            ),
            BigipPropertySpec(
                name="save-password-method",
                value_type="enum",
                in_sections=("client-policy", "android-ep"),
                enum_values=("disk", "memory"),
                default="disk",
            ),
            BigipPropertySpec(
                name="save-password-timeout",
                value_type="integer",
                in_sections=("client-policy", "android-ep"),
                default="240",
            ),
            BigipPropertySpec(
                name="chromeos-ec",
                value_type="unknown",
                in_sections=("client-policy",),
                shape_kind="object",
                block=(
                    BigipPropertySpec(
                        name="enforce-logon-mode",
                        value_type="enum",
                        in_sections=("client-policy", "chromeos-ec"),
                        enum_values=("false", "true"),
                        shape_kind="boolean",
                        default="false",
                    ),
                    BigipPropertySpec(
                        name="logon-mode",
                        value_type="enum",
                        in_sections=("client-policy", "chromeos-ec"),
                        enum_values=("native", "web"),
                        default="native",
                    ),
                    BigipPropertySpec(
                        name="save-password",
                        value_type="enum",
                        in_sections=("client-policy", "chromeos-ec"),
                        enum_values=("false", "true"),
                        shape_kind="boolean",
                        default="false",
                    ),
                    BigipPropertySpec(
                        name="save-password-method",
                        value_type="enum",
                        in_sections=("client-policy", "chromeos-ec"),
                        enum_values=("disk", "memory"),
                        default="disk",
                    ),
                    BigipPropertySpec(
                        name="save-password-timeout",
                        value_type="integer",
                        in_sections=("client-policy", "chromeos-ec"),
                        default="240",
                    ),
                ),
            ),
            BigipPropertySpec(
                name="enforce-logon-mode",
                value_type="enum",
                in_sections=("client-policy", "chromeos-ec"),
                enum_values=("false", "true"),
                shape_kind="boolean",
                default="false",
            ),
            BigipPropertySpec(
                name="logon-mode",
                value_type="enum",
                in_sections=("client-policy", "chromeos-ec"),
                enum_values=("native", "web"),
                default="native",
            ),
            BigipPropertySpec(
                name="save-password",
                value_type="enum",
                in_sections=("client-policy", "chromeos-ec"),
                enum_values=("false", "true"),
                shape_kind="boolean",
                default="false",
            ),
            BigipPropertySpec(
                name="save-password-method",
                value_type="enum",
                in_sections=("client-policy", "chromeos-ec"),
                enum_values=("disk", "memory"),
                default="disk",
            ),
            BigipPropertySpec(
                name="save-password-timeout",
                value_type="integer",
                in_sections=("client-policy", "chromeos-ec"),
                default="240",
            ),
            BigipPropertySpec(
                name="ec",
                value_type="unknown",
                in_sections=("client-policy",),
                shape_kind="object",
                block=(
                    BigipPropertySpec(
                        name="component-update",
                        value_type="enum",
                        in_sections=("client-policy", "ec"),
                        enum_values=("no", "prompt", "yes"),
                    ),
                    BigipPropertySpec(
                        name="location-dns",
                        value_type="list",
                        in_sections=("client-policy", "ec"),
                        list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
                        default="none",
                    ),
                    BigipPropertySpec(
                        name="reuse-winlogon-creds",
                        value_type="enum",
                        in_sections=("client-policy", "ec"),
                        enum_values=("false", "true"),
                        shape_kind="boolean",
                        default="false",
                    ),
                    BigipPropertySpec(
                        name="reuse-winlogon-session",
                        value_type="enum",
                        in_sections=("client-policy", "ec"),
                        enum_values=("false", "true"),
                        shape_kind="boolean",
                        default="false",
                    ),
                    BigipPropertySpec(
                        name="save-password",
                        value_type="enum",
                        in_sections=("client-policy", "ec"),
                        enum_values=("false", "true"),
                        shape_kind="boolean",
                        default="false",
                    ),
                    BigipPropertySpec(
                        name="save-password-method",
                        value_type="enum",
                        in_sections=("client-policy", "ec"),
                        enum_values=("disk", "memory"),
                        default="disk",
                    ),
                    BigipPropertySpec(
                        name="save-password-timeout",
                        value_type="integer",
                        in_sections=("client-policy", "ec"),
                        default="240",
                    ),
                    BigipPropertySpec(
                        name="save-servers-on-exit",
                        value_type="enum",
                        in_sections=("client-policy", "ec"),
                        enum_values=("false", "true"),
                        shape_kind="boolean",
                        default="true",
                    ),
                ),
            ),
            BigipPropertySpec(
                name="component-update",
                value_type="enum",
                in_sections=("client-policy", "ec"),
                enum_values=("no", "prompt", "yes"),
            ),
            BigipPropertySpec(
                name="location-dns",
                value_type="list",
                in_sections=("client-policy", "ec"),
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
                default="none",
            ),
            BigipPropertySpec(
                name="reuse-winlogon-creds",
                value_type="enum",
                in_sections=("client-policy", "ec"),
                enum_values=("false", "true"),
                shape_kind="boolean",
                default="false",
            ),
            BigipPropertySpec(
                name="reuse-winlogon-session",
                value_type="enum",
                in_sections=("client-policy", "ec"),
                enum_values=("false", "true"),
                shape_kind="boolean",
                default="false",
            ),
            BigipPropertySpec(
                name="save-password",
                value_type="enum",
                in_sections=("client-policy", "ec"),
                enum_values=("false", "true"),
                shape_kind="boolean",
                default="false",
            ),
            BigipPropertySpec(
                name="save-password-method",
                value_type="enum",
                in_sections=("client-policy", "ec"),
                enum_values=("disk", "memory"),
                default="disk",
            ),
            BigipPropertySpec(
                name="save-password-timeout",
                value_type="integer",
                in_sections=("client-policy", "ec"),
                default="240",
            ),
            BigipPropertySpec(
                name="save-servers-on-exit",
                value_type="enum",
                in_sections=("client-policy", "ec"),
                enum_values=("false", "true"),
                shape_kind="boolean",
                default="true",
            ),
            BigipPropertySpec(
                name="ios-ec",
                value_type="unknown",
                in_sections=("client-policy",),
                shape_kind="object",
                block=(
                    BigipPropertySpec(
                        name="enable-mobilesafe",
                        value_type="enum",
                        in_sections=("client-policy", "ios-ec"),
                        enum_values=("false", "true"),
                        shape_kind="boolean",
                        default="false",
                    ),
                    BigipPropertySpec(
                        name="enforce-logon-mode",
                        value_type="enum",
                        in_sections=("client-policy", "ios-ec"),
                        enum_values=("false", "true"),
                        shape_kind="boolean",
                        default="false",
                    ),
                    BigipPropertySpec(
                        name="logon-mode",
                        value_type="enum",
                        in_sections=("client-policy", "ios-ec"),
                        enum_values=("native", "web"),
                        default="native",
                    ),
                    BigipPropertySpec(
                        name="require-device-auth",
                        value_type="enum",
                        in_sections=("client-policy", "ios-ec"),
                        enum_values=("false", "true"),
                        shape_kind="boolean",
                        default="false",
                    ),
                    BigipPropertySpec(
                        name="save-password",
                        value_type="enum",
                        in_sections=("client-policy", "ios-ec"),
                        enum_values=("false", "true"),
                        shape_kind="boolean",
                        default="false",
                    ),
                    BigipPropertySpec(
                        name="save-password-method",
                        value_type="enum",
                        in_sections=("client-policy", "ios-ec"),
                        enum_values=("disk", "memory"),
                        default="disk",
                    ),
                    BigipPropertySpec(
                        name="save-password-timeout",
                        value_type="integer",
                        in_sections=("client-policy", "ios-ec"),
                        default="240",
                    ),
                    BigipPropertySpec(
                        name="vod-disconnect-timeout",
                        value_type="integer",
                        in_sections=("client-policy", "ios-ec"),
                    ),
                ),
            ),
            BigipPropertySpec(
                name="enable-mobilesafe",
                value_type="enum",
                in_sections=("client-policy", "ios-ec"),
                enum_values=("false", "true"),
                shape_kind="boolean",
                default="false",
            ),
            BigipPropertySpec(
                name="enforce-logon-mode",
                value_type="enum",
                in_sections=("client-policy", "ios-ec"),
                enum_values=("false", "true"),
                shape_kind="boolean",
                default="false",
            ),
            BigipPropertySpec(
                name="logon-mode",
                value_type="enum",
                in_sections=("client-policy", "ios-ec"),
                enum_values=("native", "web"),
                default="native",
            ),
            BigipPropertySpec(
                name="require-device-auth",
                value_type="enum",
                in_sections=("client-policy", "ios-ec"),
                enum_values=("false", "true"),
                shape_kind="boolean",
                default="false",
            ),
            BigipPropertySpec(
                name="save-password",
                value_type="enum",
                in_sections=("client-policy", "ios-ec"),
                enum_values=("false", "true"),
                shape_kind="boolean",
                default="false",
            ),
            BigipPropertySpec(
                name="save-password-method",
                value_type="enum",
                in_sections=("client-policy", "ios-ec"),
                enum_values=("disk", "memory"),
                default="disk",
            ),
            BigipPropertySpec(
                name="save-password-timeout",
                value_type="integer",
                in_sections=("client-policy", "ios-ec"),
                default="240",
            ),
            BigipPropertySpec(
                name="vod-disconnect-timeout",
                value_type="integer",
                in_sections=("client-policy", "ios-ec"),
            ),
            BigipPropertySpec(
                name="ios-ep",
                value_type="unknown",
                in_sections=("client-policy",),
                shape_kind="object",
                block=(
                    BigipPropertySpec(
                        name="enable-mobilesafe",
                        value_type="enum",
                        in_sections=("client-policy", "ios-ep"),
                        enum_values=("false", "true"),
                        shape_kind="boolean",
                        default="false",
                    ),
                    BigipPropertySpec(
                        name="enforce-logon-mode",
                        value_type="enum",
                        in_sections=("client-policy", "ios-ep"),
                        enum_values=("false", "true"),
                        shape_kind="boolean",
                        default="false",
                    ),
                    BigipPropertySpec(
                        name="enforce-pin-lock",
                        value_type="enum",
                        in_sections=("client-policy", "ios-ep"),
                        enum_values=("false", "true"),
                        shape_kind="boolean",
                        default="true",
                    ),
                    BigipPropertySpec(
                        name="logon-mode",
                        value_type="enum",
                        in_sections=("client-policy", "ios-ep"),
                        enum_values=("native", "web"),
                        default="native",
                    ),
                    BigipPropertySpec(
                        name="max-grace-period",
                        value_type="integer",
                        in_sections=("client-policy", "ios-ep"),
                        default="2",
                    ),
                    BigipPropertySpec(
                        name="save-password",
                        value_type="enum",
                        in_sections=("client-policy", "ios-ep"),
                        enum_values=("false", "true"),
                        shape_kind="boolean",
                        default="false",
                    ),
                    BigipPropertySpec(
                        name="save-password-method",
                        value_type="enum",
                        in_sections=("client-policy", "ios-ep"),
                        enum_values=("disk", "memory"),
                        default="disk",
                    ),
                    BigipPropertySpec(
                        name="save-password-timeout",
                        value_type="integer",
                        in_sections=("client-policy", "ios-ep"),
                        default="240",
                    ),
                ),
            ),
            BigipPropertySpec(
                name="enable-mobilesafe",
                value_type="enum",
                in_sections=("client-policy", "ios-ep"),
                enum_values=("false", "true"),
                shape_kind="boolean",
                default="false",
            ),
            BigipPropertySpec(
                name="enforce-logon-mode",
                value_type="enum",
                in_sections=("client-policy", "ios-ep"),
                enum_values=("false", "true"),
                shape_kind="boolean",
                default="false",
            ),
            BigipPropertySpec(
                name="enforce-pin-lock",
                value_type="enum",
                in_sections=("client-policy", "ios-ep"),
                enum_values=("false", "true"),
                shape_kind="boolean",
                default="true",
            ),
            BigipPropertySpec(
                name="logon-mode",
                value_type="enum",
                in_sections=("client-policy", "ios-ep"),
                enum_values=("native", "web"),
                default="native",
            ),
            BigipPropertySpec(
                name="max-grace-period",
                value_type="integer",
                in_sections=("client-policy", "ios-ep"),
                default="2",
            ),
            BigipPropertySpec(
                name="save-password",
                value_type="enum",
                in_sections=("client-policy", "ios-ep"),
                enum_values=("false", "true"),
                shape_kind="boolean",
                default="false",
            ),
            BigipPropertySpec(
                name="save-password-method",
                value_type="enum",
                in_sections=("client-policy", "ios-ep"),
                enum_values=("disk", "memory"),
                default="disk",
            ),
            BigipPropertySpec(
                name="save-password-timeout",
                value_type="integer",
                in_sections=("client-policy", "ios-ep"),
                default="240",
            ),
            BigipPropertySpec(
                name="macos-ec",
                value_type="unknown",
                in_sections=("client-policy",),
                shape_kind="object",
                block=(
                    BigipPropertySpec(
                        name="component-update",
                        value_type="enum",
                        in_sections=("client-policy", "macos-ec"),
                        enum_values=("no", "prompt", "yes"),
                    ),
                    BigipPropertySpec(
                        name="enforce-logon-mode",
                        value_type="enum",
                        in_sections=("client-policy", "macos-ec"),
                        enum_values=("false", "true"),
                        shape_kind="boolean",
                        default="false",
                    ),
                    BigipPropertySpec(
                        name="location-dns",
                        value_type="list",
                        in_sections=("client-policy", "macos-ec"),
                        list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
                        default="none",
                    ),
                    BigipPropertySpec(
                        name="logon-mode",
                        value_type="enum",
                        in_sections=("client-policy", "macos-ec"),
                        enum_values=("native", "web"),
                        default="native",
                    ),
                    BigipPropertySpec(
                        name="save-password",
                        value_type="enum",
                        in_sections=("client-policy", "macos-ec"),
                        enum_values=("false", "true"),
                        shape_kind="boolean",
                        default="false",
                    ),
                    BigipPropertySpec(
                        name="save-password-method",
                        value_type="enum",
                        in_sections=("client-policy", "macos-ec"),
                        enum_values=("disk", "memory"),
                        default="disk",
                    ),
                    BigipPropertySpec(
                        name="save-password-timeout",
                        value_type="integer",
                        in_sections=("client-policy", "macos-ec"),
                        default="240",
                    ),
                ),
            ),
            BigipPropertySpec(
                name="component-update",
                value_type="enum",
                in_sections=("client-policy", "macos-ec"),
                enum_values=("no", "prompt", "yes"),
            ),
            BigipPropertySpec(
                name="enforce-logon-mode",
                value_type="enum",
                in_sections=("client-policy", "macos-ec"),
                enum_values=("false", "true"),
                shape_kind="boolean",
                default="false",
            ),
            BigipPropertySpec(
                name="location-dns",
                value_type="list",
                in_sections=("client-policy", "macos-ec"),
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
                default="none",
            ),
            BigipPropertySpec(
                name="logon-mode",
                value_type="enum",
                in_sections=("client-policy", "macos-ec"),
                enum_values=("native", "web"),
                default="native",
            ),
            BigipPropertySpec(
                name="save-password",
                value_type="enum",
                in_sections=("client-policy", "macos-ec"),
                enum_values=("false", "true"),
                shape_kind="boolean",
                default="false",
            ),
            BigipPropertySpec(
                name="save-password-method",
                value_type="enum",
                in_sections=("client-policy", "macos-ec"),
                enum_values=("disk", "memory"),
                default="disk",
            ),
            BigipPropertySpec(
                name="save-password-timeout",
                value_type="integer",
                in_sections=("client-policy", "macos-ec"),
                default="240",
            ),
            BigipPropertySpec(
                name="oauth",
                value_type="unknown",
                in_sections=("client-policy",),
                shape_kind="object",
                block=(
                    BigipPropertySpec(
                        name="client-id",
                        value_type="string",
                        in_sections=("client-policy", "oauth"),
                        default="none",
                    ),
                    BigipPropertySpec(
                        name="client-secret",
                        value_type="string",
                        in_sections=("client-policy", "oauth"),
                        default="none",
                    ),
                    BigipPropertySpec(
                        name="done-uri",
                        value_type="string",
                        in_sections=("client-policy", "oauth"),
                        default="none",
                    ),
                    BigipPropertySpec(
                        name="provider-name",
                        value_type="reference",
                        in_sections=("client-policy", "oauth"),
                        default="none",
                    ),
                    BigipPropertySpec(
                        name="scopes",
                        value_type="string",
                        in_sections=("client-policy", "oauth"),
                        default="none",
                    ),
                ),
            ),
            BigipPropertySpec(
                name="client-id",
                value_type="string",
                in_sections=("client-policy", "oauth"),
                default="none",
            ),
            BigipPropertySpec(
                name="client-secret",
                value_type="string",
                in_sections=("client-policy", "oauth"),
                default="none",
            ),
            BigipPropertySpec(
                name="done-uri",
                value_type="string",
                in_sections=("client-policy", "oauth"),
                default="none",
            ),
            BigipPropertySpec(
                name="provider-name",
                value_type="reference",
                in_sections=("client-policy", "oauth"),
                default="none",
            ),
            BigipPropertySpec(
                name="scopes",
                value_type="string",
                in_sections=("client-policy", "oauth"),
                default="none",
            ),
            BigipPropertySpec(
                name="servers",
                value_type="list",
                in_sections=("client-policy",),
                block=(
                    BigipPropertySpec(
                        name="alias",
                        value_type="string",
                        in_sections=("client-policy", "servers"),
                        allow_none=True,
                    ),
                    BigipPropertySpec(
                        name="host",
                        value_type="string",
                        in_sections=("client-policy", "servers"),
                    ),
                ),
            ),
            BigipPropertySpec(
                name="alias",
                value_type="string",
                in_sections=("client-policy", "servers"),
                allow_none=True,
            ),
            BigipPropertySpec(
                name="host",
                value_type="string",
                in_sections=("client-policy", "servers"),
            ),
            BigipPropertySpec(name="compress-buffer-size", value_type="integer", default="4096"),
            BigipPropertySpec(
                name="compress-cpu-saver",
                value_type="enum",
                enum_values=("false", "true"),
                shape_kind="boolean",
                default="true",
            ),
            BigipPropertySpec(
                name="compress-cpu-saver-high",
                value_type="integer",
                default="90 percent",
            ),
            BigipPropertySpec(
                name="compress-cpu-saver-low",
                value_type="integer",
                default="75 percent",
            ),
            BigipPropertySpec(
                name="compress-gzip-level",
                value_type="integer",
                default="6, which provides a higher amount of compression at the expense of more CPU processing time",
            ),
            BigipPropertySpec(name="compress-gzip-memlevel", value_type="integer", default="8192"),
            BigipPropertySpec(
                name="compress-gzip-window-size",
                value_type="integer",
                default="16384",
            ),
            BigipPropertySpec(
                name="compress-ingress",
                value_type="enum",
                enum_values=("false", "true"),
                shape_kind="boolean",
                default="false",
            ),
            BigipPropertySpec(
                name="compress-preferred-method",
                value_type="string",
                allow_none=True,
                default="zlib",
            ),
            BigipPropertySpec(
                name="compression",
                value_type="enum",
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
                default="enabled",
            ),
            BigipPropertySpec(name="compression-codecs", value_type="string", allow_none=True),
            BigipPropertySpec(
                name="customization-group",
                value_type="string",
                required=True,
                allow_none=True,
            ),
            BigipPropertySpec(
                name="defaults",
                value_type="reference",
                allow_none=True,
                references=(
                    "ltm_default_node_monitor",
                    "security_firewall_uuid_default_autogenerate",
                    "security_packet_filter_default_rules",
                    "sys_default_config",
                ),
            ),
            BigipPropertySpec(name="deflate-compression-level", value_type="integer", default="1"),
            BigipPropertySpec(name="description", value_type="string", allow_none=True),
            BigipPropertySpec(
                name="location-specific",
                value_type="enum",
                enum_values=("false", "true"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="tunnel-name",
                value_type="string",
                allow_none=True,
                default="none",
            ),
        ),
    )
