from __future__ import annotations

from ..models import (
    BigipObjectKindSpec,
    BigipObjectSpec,
    BigipPropertySpec,
)
from ._base import register


@register
def register_spec() -> BigipObjectSpec:
    return BigipObjectSpec(
        kind_spec=BigipObjectKindSpec(
            "cm_traffic_group",
            module="cm",
            object_types=("traffic-group",),
        ),
        header_types=(("cm", "traffic-group"),),
        properties=(
            BigipPropertySpec(
                name="app-service",
                value_type="string",
                allow_none=True,
                default="none",
            ),
            BigipPropertySpec(
                name="auto-failback-enabled",
                value_type="enum",
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(name="auto-failback-time", value_type="integer", required=True),
            BigipPropertySpec(name="description", value_type="unknown"),
            BigipPropertySpec(
                name="failover-method",
                value_type="enum",
                enum_values=("ha-order", "ha-score"),
            ),
            BigipPropertySpec(
                name="ha-group",
                value_type="string",
                references=("cm_ha_group",),
                usage_flags=frozenset(("deprecated", "not_synced")),
            ),
            BigipPropertySpec(name="ha-load-factor", value_type="integer"),
            BigipPropertySpec(
                name="ha-order",
                value_type="unknown",
                repeated=True,
                references=("cm_device",),
            ),
            BigipPropertySpec(name="mac", value_type="unknown"),
            BigipPropertySpec(
                name="monitor",
                value_type="unknown",
                references=(
                    "analytics_system_monitor_report",
                    "gtm_monitor_bigip",
                    "gtm_monitor_bigip_link",
                    "gtm_monitor_external",
                    "gtm_monitor_firepass",
                    "gtm_monitor_ftp",
                    "gtm_monitor_gateway_icmp",
                    "gtm_monitor_gtp",
                    "gtm_monitor_http",
                    "gtm_monitor_https",
                    "gtm_monitor_imap",
                    "gtm_monitor_ldap",
                    "gtm_monitor_mssql",
                    "gtm_monitor_mysql",
                    "gtm_monitor_nntp",
                    "gtm_monitor_none",
                    "gtm_monitor_oracle",
                    "gtm_monitor_pop3",
                    "gtm_monitor_postgresql",
                    "gtm_monitor_radius",
                    "gtm_monitor_radius_accounting",
                    "gtm_monitor_real_server",
                    "gtm_monitor_scripted",
                    "gtm_monitor_sip",
                    "gtm_monitor_smtp",
                    "gtm_monitor_snmp",
                    "gtm_monitor_snmp_link",
                    "gtm_monitor_soap",
                    "gtm_monitor_tcp",
                    "gtm_monitor_tcp_half_open",
                    "gtm_monitor_udp",
                    "gtm_monitor_wap",
                    "gtm_monitor_wmi",
                    "ltm_default_node_monitor",
                    "ltm_monitor_diameter",
                    "ltm_monitor_dns",
                    "ltm_monitor_external",
                    "ltm_monitor_firepass",
                    "ltm_monitor_ftp",
                    "ltm_monitor_gateway_icmp",
                    "ltm_monitor_http",
                    "ltm_monitor_http2",
                    "ltm_monitor_https",
                    "ltm_monitor_icmp",
                    "ltm_monitor_imap",
                    "ltm_monitor_inband",
                    "ltm_monitor_ldap",
                    "ltm_monitor_module_score",
                    "ltm_monitor_mqtt",
                    "ltm_monitor_mssql",
                    "ltm_monitor_mysql",
                    "ltm_monitor_nntp",
                    "ltm_monitor_none",
                    "ltm_monitor_oracle",
                    "ltm_monitor_pop3",
                    "ltm_monitor_postgresql",
                    "ltm_monitor_radius",
                    "ltm_monitor_radius_accounting",
                    "ltm_monitor_real_server",
                    "ltm_monitor_rpc",
                    "ltm_monitor_sasp",
                    "ltm_monitor_scripted",
                    "ltm_monitor_sip",
                    "ltm_monitor_smb",
                    "ltm_monitor_smtp",
                    "ltm_monitor_snmp_dca",
                    "ltm_monitor_snmp_dca_base",
                    "ltm_monitor_soap",
                    "ltm_monitor_tcp",
                    "ltm_monitor_tcp_echo",
                    "ltm_monitor_tcp_half_open",
                    "ltm_monitor_udp",
                    "ltm_monitor_virtual_location",
                    "ltm_monitor_wap",
                    "ltm_monitor_wmi",
                    "sys_file_external_monitor",
                    "util_test_monitor",
                ),
                shape_kind="object",
            ),
        ),
    )
