from __future__ import annotations

from ..models import (
    BigipObjectKindSpec,
    BigipObjectSpec,
    BigipPropertySpec,
)
from ._base import register


@register
def register_spec() -> BigipObjectSpec:
    return BigipObjectSpec(
        kind_spec=BigipObjectKindSpec(
            "gtm_pool_svcb",
            module="gtm",
            object_types=("pool svcb",),
        ),
        header_types=(("gtm", "pool svcb"),),
        properties=(
            BigipPropertySpec(name="alpn", value_type="string"),
            BigipPropertySpec(
                name="alternate-mode",
                value_type="enum",
                allow_none=True,
                enum_values=(
                    "drop-packet",
                    "fallback-ip",
                    "none",
                    "packet-rate",
                    "ratio",
                    "return-to-dns",
                    "round-robin",
                    "static-persistence",
                    "topology",
                    "virtual-server-capacity",
                    "virtual-server-score",
                ),
                default="round-robin",
            ),
            BigipPropertySpec(
                name="app-service",
                value_type="string",
                allow_none=True,
                default="none",
            ),
            BigipPropertySpec(name="description", value_type="string"),
            BigipPropertySpec(
                name="dynamic",
                value_type="enum",
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="fallback-mode",
                value_type="enum",
                allow_none=True,
                enum_values=(
                    "completion-rate",
                    "cpu",
                    "drop-packet",
                    "fallback-ip",
                    "fewest-hops",
                    "kilobytes-per-second",
                    "least-connections",
                    "lowest-round-trip-time",
                    "none",
                    "packet-rate",
                    "quality-of-service",
                    "ratio",
                    "return-to-dns",
                    "round-robin",
                    "static-persistence",
                    "topology",
                    "virtual-server-capacity",
                    "virtual-server-score",
                ),
                default="return-to-dns",
            ),
            BigipPropertySpec(name="hpke-key", value_type="string"),
            BigipPropertySpec(
                name="load-balancing-mode",
                value_type="enum",
                enum_values=(
                    "completion-rate",
                    "cpu",
                    "drop-packet",
                    "fallback-ip",
                    "fewest-hops",
                    "kilobytes-per-second",
                    "least-connections",
                    "lowest-round-trip-time",
                    "packet-rate",
                    "quality-of-service",
                    "ratio",
                    "return-to-dns",
                    "round-robin",
                    "static-persistence",
                    "topology",
                    "virtual-server-capacity",
                    "virtual-server-score",
                ),
                default="round-robin",
            ),
            BigipPropertySpec(
                name="manual-resume",
                value_type="enum",
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(name="max-answers-returned", value_type="integer", default="1"),
            BigipPropertySpec(name="member-order", value_type="integer"),
            BigipPropertySpec(
                name="members",
                value_type="unknown",
                allow_none=True,
                default="none",
            ),
            BigipPropertySpec(name="metadata", value_type="unknown", allow_none=True),
            BigipPropertySpec(
                name="min-members-up-mode",
                value_type="enum",
                enum_values=("number", "off", "percent"),
            ),
            BigipPropertySpec(name="min-members-up-value", value_type="integer", required=True),
            BigipPropertySpec(name="path", value_type="string"),
            BigipPropertySpec(
                name="persist",
                value_type="enum",
                enum_values=("false", "true"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(name="qos-hit-ratio", value_type="integer", default="5"),
            BigipPropertySpec(name="qos-hops", value_type="integer", default="0 (zero)"),
            BigipPropertySpec(name="qos-kilobytes-second", value_type="integer", default="3"),
            BigipPropertySpec(name="qos-lcs", value_type="integer", default="30"),
            BigipPropertySpec(name="qos-packet-rate", value_type="integer", default="1"),
            BigipPropertySpec(name="qos-rtt", value_type="integer", default="50"),
            BigipPropertySpec(name="qos-topology", value_type="integer", default="0 (zero)"),
            BigipPropertySpec(name="qos-vs-capacity", value_type="integer", default="0 (zero)"),
            BigipPropertySpec(name="qos-vs-score", value_type="integer", default="0 (zero)"),
            BigipPropertySpec(
                name="ttl",
                value_type="integer",
                min_value=0,
                max_value=4294967295,
                default="30",
            ),
            BigipPropertySpec(name="value", value_type="string"),
            BigipPropertySpec(
                name="verify-member-availability",
                value_type="enum",
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
                default="enabled",
            ),
        ),
    )
