from __future__ import annotations

from ..models import (
    BigipObjectKindSpec,
    BigipObjectSpec,
    BigipPropertySpec,
)
from ._base import register


@register
def register_spec() -> BigipObjectSpec:
    return BigipObjectSpec(
        kind_spec=BigipObjectKindSpec(
            "ltm_profile_dhcpv4",
            module="ltm",
            object_types=("profile dhcpv4",),
        ),
        header_types=(("ltm", "profile dhcpv4"),),
        properties=(
            BigipPropertySpec(
                name="app-service",
                value_type="string",
                allow_none=True,
                default="none",
            ),
            BigipPropertySpec(
                name="authentication",
                value_type="unknown",
                shape_kind="object",
                block=(
                    BigipPropertySpec(
                        name="enabled",
                        value_type="enum",
                        in_sections=("authentication",),
                        enum_values=("false", "true"),
                        shape_kind="boolean",
                        default="false",
                    ),
                    BigipPropertySpec(
                        name="user-name",
                        value_type="unknown",
                        in_sections=("authentication",),
                        shape_kind="object",
                    ),
                    BigipPropertySpec(
                        name="virtual",
                        value_type="string",
                        in_sections=("authentication",),
                        allow_none=True,
                    ),
                ),
            ),
            BigipPropertySpec(
                name="enabled",
                value_type="enum",
                in_sections=("authentication",),
                enum_values=("false", "true"),
                shape_kind="boolean",
                default="false",
            ),
            BigipPropertySpec(
                name="user-name",
                value_type="unknown",
                in_sections=("authentication",),
                shape_kind="object",
                block=(
                    BigipPropertySpec(
                        name="format",
                        value_type="enum",
                        in_sections=("authentication", "user-name"),
                        enum_values=(
                            "address",
                            "as",
                            "concatenation",
                            "defined",
                            "is",
                            "mac-and-relay-option",
                            "option",
                            "relay-agent",
                            "relay-option",
                            "separator1",
                            "symbol",
                            "tcl-snippet",
                        ),
                    ),
                    BigipPropertySpec(
                        name="separator1",
                        value_type="string",
                        in_sections=("authentication", "user-name"),
                        allow_none=True,
                        default="@",
                    ),
                    BigipPropertySpec(
                        name="separator2",
                        value_type="string",
                        in_sections=("authentication", "user-name"),
                        allow_none=True,
                        default="@",
                    ),
                    BigipPropertySpec(
                        name="suboption-id1",
                        value_type="integer",
                        in_sections=("authentication", "user-name"),
                        default="1",
                    ),
                    BigipPropertySpec(
                        name="suboption-id2",
                        value_type="integer",
                        in_sections=("authentication", "user-name"),
                        default="2",
                    ),
                    BigipPropertySpec(
                        name="tcl",
                        value_type="string",
                        in_sections=("authentication", "user-name"),
                        allow_none=True,
                    ),
                ),
            ),
            BigipPropertySpec(
                name="format",
                value_type="enum",
                in_sections=("authentication", "user-name"),
                enum_values=(
                    "address",
                    "as",
                    "concatenation",
                    "defined",
                    "is",
                    "mac-and-relay-option",
                    "option",
                    "relay-agent",
                    "relay-option",
                    "separator1",
                    "symbol",
                    "tcl-snippet",
                ),
            ),
            BigipPropertySpec(
                name="separator1",
                value_type="string",
                in_sections=("authentication", "user-name"),
                allow_none=True,
                default="@",
            ),
            BigipPropertySpec(
                name="separator2",
                value_type="string",
                in_sections=("authentication", "user-name"),
                allow_none=True,
                default="@",
            ),
            BigipPropertySpec(
                name="suboption-id1",
                value_type="integer",
                in_sections=("authentication", "user-name"),
                default="1",
            ),
            BigipPropertySpec(
                name="suboption-id2",
                value_type="integer",
                in_sections=("authentication", "user-name"),
                default="2",
            ),
            BigipPropertySpec(
                name="tcl",
                value_type="string",
                in_sections=("authentication", "user-name"),
                allow_none=True,
            ),
            BigipPropertySpec(
                name="virtual",
                value_type="string",
                in_sections=("authentication",),
                allow_none=True,
            ),
            BigipPropertySpec(name="default-lease-time", value_type="integer", default="86400"),
            BigipPropertySpec(
                name="defaults-from",
                value_type="reference",
                allow_none=True,
                references=("ltm_profile_dhcpv4",),
                default="dhcpv4",
            ),
            BigipPropertySpec(name="description", value_type="string"),
            BigipPropertySpec(name="idle-timeout", value_type="integer", default="60 seconds"),
            BigipPropertySpec(name="lease-query-max-retry", value_type="integer"),
            BigipPropertySpec(
                name="lease-query-only",
                value_type="enum",
                enum_values=("false", "true"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(name="max-hops", value_type="integer", default="4"),
            BigipPropertySpec(
                name="mode",
                value_type="enum",
                enum_values=("forwarding", "relay"),
                default="relay",
            ),
            BigipPropertySpec(
                name="relay-agent-id",
                value_type="unknown",
                shape_kind="object",
                block=(
                    BigipPropertySpec(
                        name="add",
                        value_type="enum",
                        in_sections=("relay-agent-id",),
                        enum_values=("false", "true"),
                        shape_kind="boolean",
                        default="false",
                    ),
                    BigipPropertySpec(
                        name="remove",
                        value_type="enum",
                        in_sections=("relay-agent-id",),
                        enum_values=("false", "true"),
                        shape_kind="boolean",
                        default="false",
                    ),
                    BigipPropertySpec(
                        name="suboption",
                        value_type="unknown",
                        in_sections=("relay-agent-id",),
                        shape_kind="object",
                    ),
                ),
            ),
            BigipPropertySpec(
                name="add",
                value_type="enum",
                in_sections=("relay-agent-id",),
                enum_values=("false", "true"),
                shape_kind="boolean",
                default="false",
            ),
            BigipPropertySpec(
                name="remove",
                value_type="enum",
                in_sections=("relay-agent-id",),
                enum_values=("false", "true"),
                shape_kind="boolean",
                default="false",
            ),
            BigipPropertySpec(
                name="suboption",
                value_type="unknown",
                in_sections=("relay-agent-id",),
                shape_kind="object",
                block=(
                    BigipPropertySpec(
                        name="id1",
                        value_type="integer",
                        in_sections=("relay-agent-id", "suboption"),
                        default="1",
                    ),
                    BigipPropertySpec(
                        name="id2",
                        value_type="integer",
                        in_sections=("relay-agent-id", "suboption"),
                        default="2",
                    ),
                    BigipPropertySpec(
                        name="value1",
                        value_type="enum",
                        in_sections=("relay-agent-id", "suboption"),
                        allow_none=True,
                        enum_values=("none",),
                    ),
                    BigipPropertySpec(
                        name="value2",
                        value_type="enum",
                        in_sections=("relay-agent-id", "suboption"),
                        allow_none=True,
                        enum_values=("none",),
                    ),
                ),
            ),
            BigipPropertySpec(
                name="id1",
                value_type="integer",
                in_sections=("relay-agent-id", "suboption"),
                default="1",
            ),
            BigipPropertySpec(
                name="id2",
                value_type="integer",
                in_sections=("relay-agent-id", "suboption"),
                default="2",
            ),
            BigipPropertySpec(
                name="value1",
                value_type="enum",
                in_sections=("relay-agent-id", "suboption"),
                allow_none=True,
                enum_values=("none",),
            ),
            BigipPropertySpec(
                name="value2",
                value_type="enum",
                in_sections=("relay-agent-id", "suboption"),
                allow_none=True,
                enum_values=("none",),
            ),
            BigipPropertySpec(
                name="subscriber-discovery",
                value_type="unknown",
                shape_kind="object",
                block=(
                    BigipPropertySpec(
                        name="enabled",
                        value_type="enum",
                        in_sections=("subscriber-discovery",),
                        enum_values=("false", "true"),
                        shape_kind="boolean",
                        default="false",
                    ),
                    BigipPropertySpec(
                        name="subscriber-id",
                        value_type="unknown",
                        in_sections=("subscriber-discovery",),
                        shape_kind="object",
                    ),
                ),
            ),
            BigipPropertySpec(
                name="enabled",
                value_type="enum",
                in_sections=("subscriber-discovery",),
                enum_values=("false", "true"),
                shape_kind="boolean",
                default="false",
            ),
            BigipPropertySpec(
                name="subscriber-id",
                value_type="unknown",
                in_sections=("subscriber-discovery",),
                shape_kind="object",
                block=(
                    BigipPropertySpec(
                        name="format",
                        value_type="enum",
                        in_sections=("subscriber-discovery", "subscriber-id"),
                        enum_values=(
                            "address",
                            "as",
                            "concatenation",
                            "defined",
                            "is",
                            "mac-and-relay-id",
                            "option",
                            "relay-agent",
                            "separator1",
                            "symbol",
                            "tcl-snippet",
                        ),
                    ),
                    BigipPropertySpec(
                        name="separator1",
                        value_type="string",
                        in_sections=("subscriber-discovery", "subscriber-id"),
                        allow_none=True,
                        default="@",
                    ),
                    BigipPropertySpec(
                        name="separator2",
                        value_type="string",
                        in_sections=("subscriber-discovery", "subscriber-id"),
                        allow_none=True,
                        default="@",
                    ),
                    BigipPropertySpec(
                        name="suboption-id1",
                        value_type="integer",
                        in_sections=("subscriber-discovery", "subscriber-id"),
                        default="1",
                    ),
                    BigipPropertySpec(
                        name="suboption-id2",
                        value_type="integer",
                        in_sections=("subscriber-discovery", "subscriber-id"),
                        default="2",
                    ),
                    BigipPropertySpec(
                        name="tcl",
                        value_type="string",
                        in_sections=("subscriber-discovery", "subscriber-id"),
                        allow_none=True,
                    ),
                ),
            ),
            BigipPropertySpec(
                name="format",
                value_type="enum",
                in_sections=("subscriber-discovery", "subscriber-id"),
                enum_values=(
                    "address",
                    "as",
                    "concatenation",
                    "defined",
                    "is",
                    "mac-and-relay-id",
                    "option",
                    "relay-agent",
                    "separator1",
                    "symbol",
                    "tcl-snippet",
                ),
            ),
            BigipPropertySpec(
                name="separator1",
                value_type="string",
                in_sections=("subscriber-discovery", "subscriber-id"),
                allow_none=True,
                default="@",
            ),
            BigipPropertySpec(
                name="separator2",
                value_type="string",
                in_sections=("subscriber-discovery", "subscriber-id"),
                allow_none=True,
                default="@",
            ),
            BigipPropertySpec(
                name="suboption-id1",
                value_type="integer",
                in_sections=("subscriber-discovery", "subscriber-id"),
                default="1",
            ),
            BigipPropertySpec(
                name="suboption-id2",
                value_type="integer",
                in_sections=("subscriber-discovery", "subscriber-id"),
                default="2",
            ),
            BigipPropertySpec(
                name="tcl",
                value_type="string",
                in_sections=("subscriber-discovery", "subscriber-id"),
                allow_none=True,
            ),
            BigipPropertySpec(
                name="transaction-timeout",
                value_type="integer",
                default="45 seconds",
            ),
            BigipPropertySpec(
                name="ttl-dec-value",
                value_type="enum",
                enum_values=("by-0", "by-1", "by-2", "by-4"),
                default="by-1",
            ),
            BigipPropertySpec(name="ttl-value", value_type="integer", default="0"),
        ),
    )
