from __future__ import annotations

from ..models import (
    BigipObjectKindSpec,
    BigipObjectSpec,
    BigipPropertySpec,
)
from ._base import register


@register
def register_spec() -> BigipObjectSpec:
    return BigipObjectSpec(
        kind_spec=BigipObjectKindSpec(
            "net_ipsec_ike_peer",
            module="net",
            object_types=("ipsec ike-peer",),
        ),
        header_types=(("net", "ipsec ike-peer"),),
        properties=(
            BigipPropertySpec(name="address-list", value_type="string"),
            BigipPropertySpec(
                name="app-service",
                value_type="string",
                allow_none=True,
                default="none",
            ),
            BigipPropertySpec(name="ca-cert-file", value_type="unknown"),
            BigipPropertySpec(name="crl-file", value_type="unknown"),
            BigipPropertySpec(name="debug-payloads", value_type="string"),
            BigipPropertySpec(name="description", value_type="string"),
            BigipPropertySpec(name="dpd-delay", value_type="integer", default="30"),
            BigipPropertySpec(
                name="generate-policy",
                value_type="enum",
                enum_values=("off", "on", "unique"),
            ),
            BigipPropertySpec(name="ip-macro", value_type="string"),
            BigipPropertySpec(name="ip4-dhcp", value_type="string", shape_kind="ip-address"),
            BigipPropertySpec(name="ip4-dns", value_type="string", shape_kind="ip-address"),
            BigipPropertySpec(name="ip6-dhcp", value_type="string", shape_kind="ip-address"),
            BigipPropertySpec(name="ip6-dns", value_type="string", shape_kind="ip-address"),
            BigipPropertySpec(name="lifetime", value_type="unknown"),
            BigipPropertySpec(name="local-port", value_type="unknown"),
            BigipPropertySpec(name="mode", value_type="enum", enum_values=("aggressive", "main")),
            BigipPropertySpec(name="my-cert-file", value_type="unknown"),
            BigipPropertySpec(name="my-cert-key-file", value_type="unknown"),
            BigipPropertySpec(name="my-cert-key-passphrase", value_type="string"),
            BigipPropertySpec(
                name="my-id-type",
                value_type="enum",
                enum_values=("asn1dn", "fqdn", "keyid-tag", "user-fqdn"),
            ),
            BigipPropertySpec(name="my-id-value", value_type="string"),
            BigipPropertySpec(
                name="nat-traversal",
                value_type="enum",
                enum_values=("force", "off", "on"),
            ),
            BigipPropertySpec(name="ocsp-cert-validator", value_type="unknown"),
            BigipPropertySpec(name="ocsp-ha-reauth", value_type="unknown"),
            BigipPropertySpec(name="ocsp-jitter-percent", value_type="unknown"),
            BigipPropertySpec(name="ocsp-lifetime", value_type="unknown"),
            BigipPropertySpec(
                name="ocsp-reauth-fail-open",
                value_type="enum",
                enum_values=("false", "true"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="passive",
                value_type="enum",
                enum_values=("false", "true"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(name="peer-dynamic-ip", value_type="string", shape_kind="ip-address"),
            BigipPropertySpec(
                name="peers-cert-file",
                value_type="unknown",
                usage_flags=frozenset(("deprecated",)),
            ),
            BigipPropertySpec(
                name="peers-cert-type",
                value_type="enum",
                allow_none=True,
                enum_values=("certfile", "none"),
                usage_flags=frozenset(("deprecated",)),
            ),
            BigipPropertySpec(
                name="peers-id-type",
                value_type="enum",
                enum_values=("asn1dn", "fqdn", "keyid-tag", "user-fqdn"),
            ),
            BigipPropertySpec(name="peers-id-value", value_type="string"),
            BigipPropertySpec(
                name="phase1-auth-method",
                value_type="enum",
                enum_values=(
                    "dss",
                    "ecdsa-256",
                    "ecdsa-384",
                    "ecdsa-521",
                    "pre-shared-key",
                    "rsa-signature",
                ),
            ),
            BigipPropertySpec(
                name="phase1-encrypt-algorithm",
                value_type="enum",
                enum_values=(
                    "3des",
                    "aes",
                    "aes-gcm128",
                    "aes-gcm192",
                    "aes-gcm256",
                    "blowfish",
                    "camellia",
                    "cast128",
                    "des",
                ),
            ),
            BigipPropertySpec(
                name="phase1-hash-algorithm",
                value_type="enum",
                enum_values=(
                    "aes-gcm128",
                    "aes-gcm192",
                    "aes-gcm256",
                    "md5",
                    "sha1",
                    "sha256",
                    "sha384",
                    "sha512",
                ),
            ),
            BigipPropertySpec(
                name="phase1-perfect-forward-secrecy",
                value_type="enum",
                enum_values=(
                    "ecp256",
                    "ecp384",
                    "ecp521",
                    "modp1024",
                    "modp1536",
                    "modp2048",
                    "modp3072",
                    "modp4096",
                    "modp6144",
                    "modp768",
                    "modp8192",
                ),
            ),
            BigipPropertySpec(name="preshared-key", value_type="string"),
            BigipPropertySpec(name="preshared-key-encrypted", value_type="string"),
            BigipPropertySpec(
                name="prf",
                value_type="enum",
                enum_values=("sha1", "sha256", "sha384", "sha512"),
            ),
            BigipPropertySpec(
                name="proxy-support",
                value_type="enum",
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="remote-address",
                value_type="string",
                required=True,
                shape_kind="ip-address",
            ),
            BigipPropertySpec(name="remote-port", value_type="unknown"),
            BigipPropertySpec(name="replay-window-size", value_type="integer", default="64"),
            BigipPropertySpec(
                name="state",
                value_type="enum",
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="traffic-selector",
                value_type="reference",
                references=("net_ipsec_traffic_selector",),
            ),
            BigipPropertySpec(
                name="verify-cert",
                value_type="enum",
                enum_values=("false", "true"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="version",
                value_type="list",
                allow_none=True,
                list_operators=frozenset(("add", "delete", "replace-all-with")),
                default="v1",
            ),
        ),
    )
