# tcl-lsp — a language server and toolchain for Tcl
# Copyright (C) 2026 James Deucker (bitwisecook) <https://github.com/bitwisecook>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# SPDX-License-Identifier: AGPL-3.0-or-later

from __future__ import annotations

from ..models import (
    BigipObjectKindSpec,
    BigipObjectSpec,
    BigipPropertySpec,
)
from ._base import register


@register
def register_spec() -> BigipObjectSpec:
    return BigipObjectSpec(
        kind_spec=BigipObjectKindSpec(
            "security_ssh_ciphers",
            module="security",
            object_types=("ssh ciphers",),
        ),
        header_types=(("security", "ssh ciphers"),),
        properties=(
            BigipPropertySpec(
                name="client",
                value_type="unknown",
                shape_kind="object",
                block=(
                    BigipPropertySpec(
                        name="aes128-cbc",
                        value_type="enum",
                        in_sections=("client",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                    ),
                    BigipPropertySpec(
                        name="aes128-ctr",
                        value_type="enum",
                        in_sections=("client",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                    ),
                    BigipPropertySpec(
                        name="aes128-gcm-openssh-com",
                        value_type="enum",
                        in_sections=("client",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                    ),
                    BigipPropertySpec(
                        name="aes192-cbc",
                        value_type="enum",
                        in_sections=("client",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                    ),
                    BigipPropertySpec(
                        name="aes192-ctr",
                        value_type="enum",
                        in_sections=("client",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                    ),
                    BigipPropertySpec(
                        name="aes256-cbc",
                        value_type="enum",
                        in_sections=("client",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                    ),
                    BigipPropertySpec(
                        name="aes256-ctr",
                        value_type="enum",
                        in_sections=("client",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                    ),
                    BigipPropertySpec(
                        name="aes256-gcm-openssh-com",
                        value_type="enum",
                        in_sections=("client",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                    ),
                    BigipPropertySpec(
                        name="curve25519-sha256",
                        value_type="enum",
                        in_sections=("client",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                    ),
                    BigipPropertySpec(
                        name="curve25519-sha256-libssh-org",
                        value_type="enum",
                        in_sections=("client",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                    ),
                    BigipPropertySpec(
                        name="diffie-hellman-group-exchange-sha256",
                        value_type="enum",
                        in_sections=("client",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                    ),
                    BigipPropertySpec(
                        name="diffie-hellman-group1-sha1",
                        value_type="enum",
                        in_sections=("client",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                    ),
                    BigipPropertySpec(
                        name="diffie-hellman-group14-sha1",
                        value_type="enum",
                        in_sections=("client",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                    ),
                    BigipPropertySpec(
                        name="diffie-hellman-group14-sha256",
                        value_type="enum",
                        in_sections=("client",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                    ),
                    BigipPropertySpec(
                        name="diffie-hellman-group16-sha512",
                        value_type="enum",
                        in_sections=("client",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                    ),
                    BigipPropertySpec(
                        name="diffie-hellman-group18-sha512",
                        value_type="enum",
                        in_sections=("client",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                    ),
                    BigipPropertySpec(
                        name="ecdh-sha2-nistp256",
                        value_type="enum",
                        in_sections=("client",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                    ),
                    BigipPropertySpec(
                        name="ecdh-sha2-nistp384",
                        value_type="enum",
                        in_sections=("client",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                    ),
                    BigipPropertySpec(
                        name="ecdh-sha2-nistp521",
                        value_type="enum",
                        in_sections=("client",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                    ),
                    BigipPropertySpec(
                        name="ext-info-c",
                        value_type="enum",
                        in_sections=("client",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                    ),
                    BigipPropertySpec(
                        name="hmac-sha1",
                        value_type="enum",
                        in_sections=("client",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                    ),
                    BigipPropertySpec(
                        name="hmac-sha1-etm-openssh-com",
                        value_type="enum",
                        in_sections=("client",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                    ),
                    BigipPropertySpec(
                        name="hmac-sha2-256",
                        value_type="enum",
                        in_sections=("client",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                    ),
                    BigipPropertySpec(
                        name="hmac-sha2-256-etm-openssh-com",
                        value_type="enum",
                        in_sections=("client",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                    ),
                    BigipPropertySpec(
                        name="hmac-sha2-512",
                        value_type="enum",
                        in_sections=("client",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                    ),
                    BigipPropertySpec(
                        name="hmac-sha2-512-etm-openssh-com",
                        value_type="enum",
                        in_sections=("client",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                    ),
                    BigipPropertySpec(
                        name="three-des-cbc",
                        value_type="enum",
                        in_sections=("client",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                    ),
                ),
            ),
            BigipPropertySpec(
                name="aes128-cbc",
                value_type="enum",
                in_sections=("client",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="aes128-ctr",
                value_type="enum",
                in_sections=("client",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="aes128-gcm-openssh-com",
                value_type="enum",
                in_sections=("client",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="aes192-cbc",
                value_type="enum",
                in_sections=("client",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="aes192-ctr",
                value_type="enum",
                in_sections=("client",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="aes256-cbc",
                value_type="enum",
                in_sections=("client",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="aes256-ctr",
                value_type="enum",
                in_sections=("client",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="aes256-gcm-openssh-com",
                value_type="enum",
                in_sections=("client",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="curve25519-sha256",
                value_type="enum",
                in_sections=("client",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="curve25519-sha256-libssh-org",
                value_type="enum",
                in_sections=("client",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="diffie-hellman-group-exchange-sha256",
                value_type="enum",
                in_sections=("client",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="diffie-hellman-group1-sha1",
                value_type="enum",
                in_sections=("client",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="diffie-hellman-group14-sha1",
                value_type="enum",
                in_sections=("client",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="diffie-hellman-group14-sha256",
                value_type="enum",
                in_sections=("client",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="diffie-hellman-group16-sha512",
                value_type="enum",
                in_sections=("client",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="diffie-hellman-group18-sha512",
                value_type="enum",
                in_sections=("client",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="ecdh-sha2-nistp256",
                value_type="enum",
                in_sections=("client",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="ecdh-sha2-nistp384",
                value_type="enum",
                in_sections=("client",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="ecdh-sha2-nistp521",
                value_type="enum",
                in_sections=("client",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="ext-info-c",
                value_type="enum",
                in_sections=("client",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="hmac-sha1",
                value_type="enum",
                in_sections=("client",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="hmac-sha1-etm-openssh-com",
                value_type="enum",
                in_sections=("client",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="hmac-sha2-256",
                value_type="enum",
                in_sections=("client",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="hmac-sha2-256-etm-openssh-com",
                value_type="enum",
                in_sections=("client",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="hmac-sha2-512",
                value_type="enum",
                in_sections=("client",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="hmac-sha2-512-etm-openssh-com",
                value_type="enum",
                in_sections=("client",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="three-des-cbc",
                value_type="enum",
                in_sections=("client",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="server",
                value_type="unknown",
                shape_kind="object",
                block=(
                    BigipPropertySpec(
                        name="aes128-cbc",
                        value_type="enum",
                        in_sections=("server",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                    ),
                    BigipPropertySpec(
                        name="aes128-ctr",
                        value_type="enum",
                        in_sections=("server",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                    ),
                    BigipPropertySpec(
                        name="aes128-gcm-openssh-com",
                        value_type="enum",
                        in_sections=("server",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                    ),
                    BigipPropertySpec(
                        name="aes192-cbc",
                        value_type="enum",
                        in_sections=("server",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                    ),
                    BigipPropertySpec(
                        name="aes192-ctr",
                        value_type="enum",
                        in_sections=("server",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                    ),
                    BigipPropertySpec(
                        name="aes256-cbc",
                        value_type="enum",
                        in_sections=("server",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                    ),
                    BigipPropertySpec(
                        name="aes256-ctr",
                        value_type="enum",
                        in_sections=("server",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                    ),
                    BigipPropertySpec(
                        name="aes256-gcm-openssh-com",
                        value_type="enum",
                        in_sections=("server",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                    ),
                    BigipPropertySpec(
                        name="curve25519-sha256",
                        value_type="enum",
                        in_sections=("server",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                    ),
                    BigipPropertySpec(
                        name="curve25519-sha256-libssh-org",
                        value_type="enum",
                        in_sections=("server",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                    ),
                    BigipPropertySpec(
                        name="diffie-hellman-group-exchange-sha256",
                        value_type="enum",
                        in_sections=("server",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                    ),
                    BigipPropertySpec(
                        name="diffie-hellman-group1-sha1",
                        value_type="enum",
                        in_sections=("server",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                    ),
                    BigipPropertySpec(
                        name="diffie-hellman-group14-sha1",
                        value_type="enum",
                        in_sections=("server",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                    ),
                    BigipPropertySpec(
                        name="diffie-hellman-group14-sha256",
                        value_type="enum",
                        in_sections=("server",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                    ),
                    BigipPropertySpec(
                        name="diffie-hellman-group16-sha512",
                        value_type="enum",
                        in_sections=("server",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                    ),
                    BigipPropertySpec(
                        name="diffie-hellman-group18-sha512",
                        value_type="enum",
                        in_sections=("server",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                    ),
                    BigipPropertySpec(
                        name="ecdh-sha2-nistp256",
                        value_type="enum",
                        in_sections=("server",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                    ),
                    BigipPropertySpec(
                        name="ecdh-sha2-nistp384",
                        value_type="enum",
                        in_sections=("server",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                    ),
                    BigipPropertySpec(
                        name="ecdh-sha2-nistp521",
                        value_type="enum",
                        in_sections=("server",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                    ),
                    BigipPropertySpec(
                        name="ext-info-c",
                        value_type="enum",
                        in_sections=("server",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                    ),
                    BigipPropertySpec(
                        name="hmac-sha1",
                        value_type="enum",
                        in_sections=("server",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                    ),
                    BigipPropertySpec(
                        name="hmac-sha1-etm-openssh-com",
                        value_type="enum",
                        in_sections=("server",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                    ),
                    BigipPropertySpec(
                        name="hmac-sha2-256",
                        value_type="enum",
                        in_sections=("server",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                    ),
                    BigipPropertySpec(
                        name="hmac-sha2-256-etm-openssh-com",
                        value_type="enum",
                        in_sections=("server",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                    ),
                    BigipPropertySpec(
                        name="hmac-sha2-512",
                        value_type="enum",
                        in_sections=("server",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                    ),
                    BigipPropertySpec(
                        name="hmac-sha2-512-etm-openssh-com",
                        value_type="enum",
                        in_sections=("server",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                    ),
                    BigipPropertySpec(
                        name="three-des-cbc",
                        value_type="enum",
                        in_sections=("server",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                    ),
                ),
            ),
            BigipPropertySpec(
                name="aes128-cbc",
                value_type="enum",
                in_sections=("server",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="aes128-ctr",
                value_type="enum",
                in_sections=("server",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="aes128-gcm-openssh-com",
                value_type="enum",
                in_sections=("server",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="aes192-cbc",
                value_type="enum",
                in_sections=("server",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="aes192-ctr",
                value_type="enum",
                in_sections=("server",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="aes256-cbc",
                value_type="enum",
                in_sections=("server",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="aes256-ctr",
                value_type="enum",
                in_sections=("server",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="aes256-gcm-openssh-com",
                value_type="enum",
                in_sections=("server",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="curve25519-sha256",
                value_type="enum",
                in_sections=("server",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="curve25519-sha256-libssh-org",
                value_type="enum",
                in_sections=("server",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="diffie-hellman-group-exchange-sha256",
                value_type="enum",
                in_sections=("server",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="diffie-hellman-group1-sha1",
                value_type="enum",
                in_sections=("server",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="diffie-hellman-group14-sha1",
                value_type="enum",
                in_sections=("server",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="diffie-hellman-group14-sha256",
                value_type="enum",
                in_sections=("server",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="diffie-hellman-group16-sha512",
                value_type="enum",
                in_sections=("server",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="diffie-hellman-group18-sha512",
                value_type="enum",
                in_sections=("server",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="ecdh-sha2-nistp256",
                value_type="enum",
                in_sections=("server",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="ecdh-sha2-nistp384",
                value_type="enum",
                in_sections=("server",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="ecdh-sha2-nistp521",
                value_type="enum",
                in_sections=("server",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="ext-info-c",
                value_type="enum",
                in_sections=("server",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="hmac-sha1",
                value_type="enum",
                in_sections=("server",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="hmac-sha1-etm-openssh-com",
                value_type="enum",
                in_sections=("server",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="hmac-sha2-256",
                value_type="enum",
                in_sections=("server",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="hmac-sha2-256-etm-openssh-com",
                value_type="enum",
                in_sections=("server",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="hmac-sha2-512",
                value_type="enum",
                in_sections=("server",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="hmac-sha2-512-etm-openssh-com",
                value_type="enum",
                in_sections=("server",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="three-des-cbc",
                value_type="enum",
                in_sections=("server",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
        ),
    )
