#!/usr/bin/env python3
"""Generate Rust specs for tcl commands missing from the Rust port.

Name-parity reconcile (GAP-d): emits the `tcl::mathop` operator ensemble
(bare ops, `tcl::mathop::op`, `::tcl::mathop::op`, and the word
operators) that the Rust port collapsed into a single `tcl::mathop`
entry, plus the other simple missing commands — all from the Python
source of truth. Operator symbols can't be Rust filenames/modules, so
the whole set lands in one generated `mathop_generated.rs` with a
`specs()` factory wired into the group via `.extend()`.

Usage: python3 scripts/registry-audit/gen_missing_tcl.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[2]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _groups import load_specs  # noqa: E402

ANY = sys.maxsize
OUT = _REPO_ROOT / "rust/tcl-registry/src/commands/tcl/mathop_generated.rs"
AUDIT = _REPO_ROOT / "tmp/registry-audit/tcl"


def rust_str(s: str) -> str:
    return (
        '"'
        + (s or "").replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n").replace("\t", "\\t")
        + '"'
    )


def arity_expr(ar) -> str:
    if ar is None:
        return "Arity::any()"
    lo, hi = ar.min, ar.max
    if hi >= ANY:
        return f"Arity::at_least({lo})"
    if lo == hi:
        return f"Arity::exact({lo})"
    return f"Arity::new({lo}, {hi})"


_TYPE = {
    "INT": "Int", "STRING": "String", "LIST": "List", "DICT": "Dict",
    "BOOLEAN": "Boolean", "NUMERIC": "Numeric", "DOUBLE": "Double",
    "CHANNEL": "Channel",
}


def spec_literal(spec) -> str:
    val = getattr(spec, "validation", None)
    arity = getattr(val, "arity", None) if val else None
    h = spec.hover
    lines = ["    CommandSpec {", f"        name: {rust_str(spec.name)},"]
    if getattr(spec, "pure", False):
        lines.append("        traits: Traits::PURE,")
    lines.append(f"        arity: {arity_expr(arity)},")
    rt = spec.return_type
    if rt is not None and rt.name in _TYPE:
        lines.append(f"        return_type: Some(TclType::{_TYPE[rt.name]}),")
    if h is not None:
        syn = ", ".join(rust_str(s) for s in (h.synopsis or ()))
        lines.append(
            "        hover: Some(HoverSnippet::brief(\n"
            f"            {rust_str(h.summary or '')},\n"
            f"            &[{syn}],\n"
            f"            {rust_str(h.source or 'Tcl')},\n"
            "        )),"
        )
    lines.append("        ..CommandSpec::DEFAULT")
    lines.append("    },")
    return "\n".join(lines)


def main() -> None:
    py = {s.name: s for s in load_specs("tcl")}
    ru = {json.loads(l)["name"] for l in open(f"{AUDIT}.rust.jsonl")}
    missing = sorted(set(py) - ru)
    # Only the mathop ensemble + bare/word operators belong in this file;
    # genuinely-named commands get their own files.
    def is_op(n: str) -> bool:
        return (
            "mathop" in n
            or not n[:1].isalpha()
            or n in {"eq", "ne", "in", "ni", "max", "min"}
        )

    ops = [py[n] for n in missing if is_op(n)]
    body = "\n".join(spec_literal(s) for s in ops)
    text = (
        "//! `tcl::mathop` operator ensemble — name-parity reconcile (GAP-d).\n"
        "//!\n"
        "//! The Rust port collapsed the operator ensemble into a single\n"
        "//! `tcl::mathop` entry; the Python source of truth registers each\n"
        "//! operator as a command in three spellings (bare `+`,\n"
        "//! `tcl::mathop::+`, `::tcl::mathop::+`) plus the word operators\n"
        "//! (`eq`/`ne`/`in`/`ni`/`max`/`min`). This file restores name parity.\n"
        "//!\n"
        "//! Generated by `scripts/registry-audit/gen_missing_tcl.py`.\n"
        "use crate::prelude::*;\n\n"
        "/// All `tcl::mathop` operator-command specs (every spelling).\n"
        "pub fn specs() -> Vec<CommandSpec> {\n"
        "    vec![\n"
        f"{body}\n"
        "    ]\n"
        "}\n"
    )
    OUT.write_text(text)
    print(f"wrote {OUT.name}: {len(ops)} operator specs")
    named = [n for n in missing if not is_op(n)]
    print(f"named (not generated here): {named}")


if __name__ == "__main__":
    main()
