#!/usr/bin/env python3
"""Generate Rust specs for tcl commands missing from the Rust port.

Name-parity reconcile (GAP-d): emits the `tcl::mathop` operator ensemble
(bare ops, `tcl::mathop::op`, `::tcl::mathop::op`, and the word
operators) that the Rust port collapsed into a single `tcl::mathop`
entry, plus the other simple missing commands — all from the Python
source of truth. Operator symbols can't be Rust filenames/modules, so
the whole set lands in one generated `mathop_generated.rs` with a
`specs()` factory wired into the group via `.extend()`.

Usage: python3 scripts/registry-audit/gen_missing_tcl.py
"""

from __future__ import annotations

import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[2]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _groups import load_specs  # noqa: E402

ANY = sys.maxsize
OUT = _REPO_ROOT / "rust/tcl-registry/src/commands/tcl/mathop_generated.rs"
AUDIT = _REPO_ROOT / "tmp/registry-audit/tcl"


def rust_str(s: str) -> str:
    return (
        '"'
        + (s or "")
        .replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\t", "\\t")
        + '"'
    )


def arity_expr(ar) -> str:
    if ar is None:
        return "Arity::any()"
    lo, hi = ar.min, ar.max
    if hi >= ANY:
        return f"Arity::at_least({lo})"
    if lo == hi:
        return f"Arity::exact({lo})"
    return f"Arity::new({lo}, {hi})"


_TYPE = {
    "INT": "Int",
    "STRING": "String",
    "LIST": "List",
    "DICT": "Dict",
    "BOOLEAN": "Boolean",
    "NUMERIC": "Numeric",
    "DOUBLE": "Double",
    "CHANNEL": "Channel",
}
_FORMKIND = {"DEFAULT": "Default", "GETTER": "Getter", "SETTER": "Setter"}


def hover_lines(h, indent: str) -> list[str]:
    """Full `HoverSnippet { .. }` (keeps snippet/examples/return_value)."""
    inner = indent + "    "
    syn = ", ".join(rust_str(s) for s in (h.synopsis or ()))
    return [
        f"{indent}hover: Some(HoverSnippet {{",
        f"{inner}summary: {rust_str(h.summary or '')},",
        f"{inner}synopsis: &[{syn}],",
        f"{inner}snippet: {rust_str(h.snippet or '')},",
        f"{inner}source: {rust_str(h.source or 'Tcl')},",
        f"{inner}examples: {rust_str(h.examples or '')},",
        f"{inner}return_value: {rust_str(h.return_value or '')},",
        f"{indent}}}),",
    ]


def forms_line(spec, indent: str) -> str | None:
    forms = spec.forms or ()
    if not forms:
        return None
    items = ", ".join(
        f"FormSpec {{ kind: FormKind::{_FORMKIND.get(f.kind.name, 'Default')}, "
        f"synopsis: {rust_str(f.synopsis or '')} }}"
        for f in forms
    )
    return f"{indent}forms: &[{items}],"


def spec_literal(spec) -> str:
    val = getattr(spec, "validation", None)
    arity = getattr(val, "arity", None) if val else None
    h = spec.hover
    lines = ["    CommandSpec {", f"        name: {rust_str(spec.name)},"]
    if getattr(spec, "pure", False):
        lines.append("        traits: Traits::PURE,")
    lines.append(f"        arity: {arity_expr(arity)},")
    rt = spec.return_type
    if rt is not None and rt.name in _TYPE:
        lines.append(f"        return_type: Some(TclType::{_TYPE[rt.name]}),")
    if h is not None:
        lines.extend(hover_lines(h, "        "))
    fl = forms_line(spec, "        ")
    if fl:
        lines.append(fl)
    lines.append("        ..CommandSpec::DEFAULT")
    lines.append("    },")
    return "\n".join(lines)


def main() -> None:
    py = {s.name: s for s in load_specs("tcl")}

    # Regenerate from the canonical Python set directly (idempotent — does
    # not depend on the current Rust state). Only the mathop ensemble +
    # bare/word operators belong in this file; named commands get their
    # own files via gen_named_tcl.py.
    def is_op(n: str) -> bool:
        return "mathop" in n or not n[:1].isalpha() or n in {"eq", "ne", "in", "ni", "max", "min"}

    ops = [s for n, s in sorted(py.items()) if is_op(n)]
    body = "\n".join(spec_literal(s) for s in ops)
    text = (
        "//! `tcl::mathop` operator ensemble — name-parity reconcile (GAP-d).\n"
        "//!\n"
        "//! The Rust port collapsed the operator ensemble into a single\n"
        "//! `tcl::mathop` entry; the Python source of truth registers each\n"
        "//! operator as a command in three spellings (bare `+`,\n"
        "//! `tcl::mathop::+`, `::tcl::mathop::+`) plus the word operators\n"
        "//! (`eq`/`ne`/`in`/`ni`/`max`/`min`). This file restores name parity.\n"
        "//!\n"
        "//! Generated by `scripts/registry-audit/gen_missing_tcl.py`.\n"
        "use crate::prelude::*;\n\n"
        "/// All `tcl::mathop` operator-command specs (every spelling).\n"
        "#[allow(clippy::too_many_lines)]\n"
        "pub fn specs() -> Vec<CommandSpec> {\n"
        "    vec![\n"
        f"{body}\n"
        "    ]\n"
        "}\n"
    )
    OUT.write_text(text)
    print(f"wrote {OUT.name}: {len(ops)} operator specs (forms + full hover)")


if __name__ == "__main__":
    main()
