//! `ACCESS::saml` iRules command.
use crate::prelude::*;
pub fn spec() -> CommandSpec {
    CommandSpec {
        name: "ACCESS::saml",
        dialects: Some(DialectSet::IRULES),
        arity: Arity::at_least(0),
hover: Some(HoverSnippet {
            summary: "Access or manipulate SAML related messages.",
            synopsis: &["ACCESS::saml authn (CONTENT)?", "ACCESS::saml assertion (CONTENT)?", "ACCESS::saml slo_req (CONTENT)?", "ACCESS::saml slo_resp (CONTENT)?"],
            snippet: "The different ACCESS::saml sub-commands allow you to\naccess or manipulate outgoing SAML request/response messages including\nauthentication request, assertion, single logout request and response.\n\nACCESS::saml authn\n\n     * Returns the SAML authentication request payload generated by BIG-IP\n       as service provider. Sets the SAML authentication request if given.\n\nACCESS::saml assertion\n\n     * Returns the SAML assertion payload generated by BIG-IP as\n       identity provider. Sets the SAML assertion if given.",
            source: "https://clouddocs.f5.com/api/irules/ACCESS__saml.html",
            examples: "when ACCESS_SAML_AUTHN {\n        # Variable authn_request is set to SAML authentication request payload generated.\n        set authn_request [ ACCESS::saml authn ]\n        # The value set in variable authn_request is logged.\n        log -noname accesscontrol.local1.notice \"AuthN Req before modification: $authn_request\"\n        # The NameIDPolicy format in authn_request is modified from 'unspecified' to 'emailAddress' and set in variable new_authn_request.",
            return_value: "",
        }),
        event_requires: Some(EventRequires {
            client_side: false,
            server_side: false,
            transport: None,
            profiles: &["ACCESS"],
            also_in: &[],
            init_only: false,
            flow: false,
            capability: None,
        }),
        forms: &[
            FormSpec { kind: FormKind::Default, synopsis: "ACCESS::saml <subcommand> ?content?" },
        ],
        ..CommandSpec::DEFAULT
    }
}
