//! `ANTIFRAUD::device_id` iRules command.
use crate::prelude::*;
pub fn spec() -> CommandSpec {
    CommandSpec {
        name: "ANTIFRAUD::device_id",
        dialects: Some(DialectSet::IRULES),
        arity: Arity::at_least(0),
hover: Some(HoverSnippet {
            summary: "Returns device id generated by bigip.",
            synopsis: &["ANTIFRAUD::device_id"],
            snippet: "Returns device id generated by bigip.",
            source: "https://clouddocs.f5.com/api/irules/ANTIFRAUD__device_id.html",
            examples: "when ANTIFRAUD_ALERT {\n                log local0. \"device id: [ANTIFRAUD::device_id].\"\n            }",
            return_value: "Returns device id generated by bigip.",
        }),
        ..CommandSpec::DEFAULT
    }
}
