//! `ANTIFRAUD::device_id` iRules command.
use crate::prelude::*;
pub fn spec() -> CommandSpec {
    CommandSpec {
        name: "ANTIFRAUD::device_id",
        dialects: Some(DialectSet::IRULES),
        arity: Arity::at_least(0),
        hover: Some(HoverSnippet::brief(
            "Returns device id generated by bigip.",
            &["ANTIFRAUD::device_id"],
            "F5 iRules",
        )),
        ..CommandSpec::DEFAULT
    }
}
