// tcl-lsp — a language server and toolchain for Tcl
// Copyright (C) 2026 James Deucker (bitwisecook) <https://github.com/bitwisecook>
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
// SPDX-License-Identifier: AGPL-3.0-or-later

//! `HTTP::retry` iRules command.
use crate::prelude::*;
pub const fn spec() -> CommandSpec {
    CommandSpec {
        name: "HTTP::retry",
        traits: Traits::DIAGRAM_ACTION,
        dialects: Some(DialectSet::IRULES),
        arity: Arity::at_least(0),
        hover: Some(HoverSnippet {
            summary: "Resends a request to a server.",
            synopsis: &["HTTP::retry ('-reset')? HTTP_REQUEST"],
            snippet: "Re-sends a request to a server. Can be either the same or a different\nrequest, to the same or a different server.\n  * To replay the same request, save the request to a variable in the\n    HTTP_REQUEST event, then use it with this command.\n  * A different request may alternatively be specified. The request\n    string must be well-formed and complete, including all required\n    headers.\n\nThe request generated by this command triggers HTTP_REQUEST and\nall subsequent client-side events.",
            source: "https://clouddocs.f5.com/api/irules/HTTP__retry.html",
            examples: "when LB_SELECTED {\n   # Select a new pool member from the VS default pool if we are retrying this request\n   if { $retries > 0 } {\n      LB::reselect pool $default_pool\n   }\n}",
            return_value: "",
        }),
        event_requires: Some(EventRequires {
            client_side: false,
            server_side: false,
            transport: Some("tcp"),
            profiles: &["FASTHTTP", "HTTP"],
            also_in: &[],
            init_only: false,
            flow: false,
            capability: None,
        }),
        forms: &[FormSpec {
            kind: FormKind::Default,
            synopsis: "HTTP::retry ('-reset')? HTTP_REQUEST",
        }],
        options: const {
            &[OptionSpec {
                name: "-reset",
                value: OptionValue::flag(),
                detail: "Reset the server-side connection.",
                dialects: None,
                aliases: &[],
                min_version: None,
            }]
        },
        side_effects: &[SideEffect {
            target: SideEffectTarget::HttpHeader,
            reads: false,
            writes: true,
            connection_side: ConnectionSide::Server,
            dialects: None,
        }],
        ..CommandSpec::DEFAULT
    }
}
