//! `HTTP2::active` iRules command.
use crate::prelude::*;
pub fn spec() -> CommandSpec {
    CommandSpec {
        name: "HTTP2::active",
        dialects: Some(DialectSet::IRULES),
        arity: Arity::at_least(0),
        hover: Some(HoverSnippet::brief(
            "This command can be used to determine if a request or response is generated by H",
            &["HTTP2::active"],
            "F5 iRules",
        )),
        ..CommandSpec::DEFAULT
    }
}
