gtm datacenter /Common/dc-east {
    location east
}
gtm server /Common/border-fw {
    datacenter /Common/dc-east
    product bigip
    virtual-servers {
        public_a {
            destination 203.0.113.10:443
        }
        public_b {
            destination 203.0.113.11:443
        }
    }
}
gtm pool a /Common/www_pool {
    members {
        /Common/border-fw:public_a { }
        /Common/border-fw:public_b { }
    }
    monitor /Common/gateway_icmp
}
gtm wideip a /Common/www.example.com {
    pools {
        /Common/www_pool { }
    }
    pool-lb-mode round-robin
}
