ltm snat-translation /Common/snat_xlat_1 {
    address 198.51.100.101
}
ltm snat-translation /Common/snat_xlat_2 {
    address 198.51.100.102
}
ltm snat-translation /Common/snat_xlat_3 {
    address 198.51.100.103
}
ltm snatpool /Common/internet_snat {
    members {
        /Common/snat_xlat_1
        /Common/snat_xlat_2
        /Common/snat_xlat_3
    }
}
ltm node /Common/upstream_gw {
    address 198.51.100.1
}
ltm pool /Common/internet_uplink_pool {
    members {
        /Common/upstream_gw:0 {
            address 198.51.100.1
        }
    }
    monitor /Common/gateway_icmp
}
ltm virtual /Common/internet_egress_vs {
    destination /Common/0.0.0.0:0
    pool /Common/internet_uplink_pool
    profiles {
        /Common/fastL4 { }
    }
    source-address-translation {
        type snat
        pool /Common/internet_snat
    }
    ip-forward
    ip-protocol any
}
