cm device /Common/t1-a {
    hostname t1-a.example.test
    management-ip 192.0.2.11
}
cm device /Common/t1-b {
    hostname t1-b.example.test
    management-ip 192.0.2.12
}
cm device-group /Common/t1-failover {
    type sync-failover
    devices {
        /Common/t1-a { }
        /Common/t1-b { }
    }
    auto-sync enabled
}
net route-domain /Common/to_t2_c01 {
    id 101
}
net route-domain /Common/to_t2_c02 {
    id 102
}
net route-domain /Common/to_t2_c03 {
    id 103
}
net route-domain /Common/to_t2_c04 {
    id 104
}
net route-domain /Common/to_t2_c05 {
    id 105
}
net route-domain /Common/to_t2_c06 {
    id 106
}
net route-domain /Common/to_t2_c07 {
    id 107
}
net route-domain /Common/to_t2_c08 {
    id 108
}
net route-domain /Common/to_t2_c09 {
    id 109
}
net route-domain /Common/to_t2_c10 {
    id 110
}
net route-domain /Common/to_t2_c11 {
    id 111
}
net route-domain /Common/to_t2_c12 {
    id 112
}
ltm node /Common/t2_c01_vip {
    address 10.2.0.10%101
}
ltm node /Common/t2_c02_vip {
    address 10.2.0.10%102
}
ltm node /Common/t2_c03_vip {
    address 10.2.0.10%103
}
ltm node /Common/t2_c04_vip {
    address 10.2.0.10%104
}
ltm node /Common/t2_c05_vip {
    address 10.2.0.10%105
}
ltm node /Common/t2_c06_vip {
    address 10.2.0.10%106
}
ltm node /Common/t2_c07_vip {
    address 10.2.0.10%107
}
ltm node /Common/t2_c08_vip {
    address 10.2.0.10%108
}
ltm node /Common/t2_c09_vip {
    address 10.2.0.10%109
}
ltm node /Common/t2_c10_vip {
    address 10.2.0.10%110
}
ltm node /Common/t2_c11_vip {
    address 10.2.0.10%111
}
ltm node /Common/t2_c12_vip {
    address 10.2.0.10%112
}
ltm pool /Common/t2_fanout_pool {
    members {
        /Common/t2_c01_vip:443 {
            address 10.2.0.10%101
        }
        /Common/t2_c02_vip:443 {
            address 10.2.0.10%102
        }
        /Common/t2_c03_vip:443 {
            address 10.2.0.10%103
        }
        /Common/t2_c04_vip:443 {
            address 10.2.0.10%104
        }
        /Common/t2_c05_vip:443 {
            address 10.2.0.10%105
        }
        /Common/t2_c06_vip:443 {
            address 10.2.0.10%106
        }
        /Common/t2_c07_vip:443 {
            address 10.2.0.10%107
        }
        /Common/t2_c08_vip:443 {
            address 10.2.0.10%108
        }
        /Common/t2_c09_vip:443 {
            address 10.2.0.10%109
        }
        /Common/t2_c10_vip:443 {
            address 10.2.0.10%110
        }
        /Common/t2_c11_vip:443 {
            address 10.2.0.10%111
        }
        /Common/t2_c12_vip:443 {
            address 10.2.0.10%112
        }
    }
    monitor /Common/tcp
    load-balancing-mode least-connections-member
}
ltm virtual /Common/t1_ingress_vs {
    destination /Common/10.1.0.10:443
    pool /Common/t2_fanout_pool
    profiles {
        /Common/tcp { }
        /Common/http { }
        /Common/clientssl { context clientside }
        /Common/serverssl { context serverside }
    }
    ip-protocol tcp
}
