cm device /Common/t2-c04-a {
    hostname t2-c04-a.example.test
    management-ip 192.0.2.24
}
cm device /Common/t2-c04-b {
    hostname t2-c04-b.example.test
    management-ip 192.0.2.124
}
cm device-group /Common/t2-c04-failover {
    type sync-failover
    devices {
        /Common/t2-c04-a { }
        /Common/t2-c04-b { }
    }
}
net vlan /Common/client_vlan {
    interfaces {
        1.4 { }
    }
    tag 204
}
net route-domain /Common/client_rd {
    id 104
    vlans {
        /Common/client_vlan
    }
}
security firewall rule-list /Common/allow_web {
    rules {
        allow_tls {
            action accept
            ip-protocol tcp
        }
    }
}
security firewall policy /Common/edge_fw {
    rules {
        allow_web_binding { rule-list /Common/allow_web }
    }
}
ltm pool /Common/backend_pool {
    members {
        /Common/backend_1:8443 {
            address 10.3.24.10
        }
        /Common/backend_2:8443 {
            address 10.3.24.11
        }
    }
    monitor /Common/tcp
}
ltm policy /Common/http_router {
    controls { forwarding }
    requires { http }
    rules {
        api {
            actions {
                0 {
                    forward
                    select
                    pool /Common/backend_pool
                }
            }
            conditions {
                0 {
                    http-uri
                    path
                    starts-with
                    values { /api }
                }
            }
            ordinal 10
        }
        default {
            actions {
                0 {
                    forward
                    select
                    pool /Common/backend_pool
                }
            }
            ordinal 20
        }
    }
}
ltm virtual /Common/app_vs {
    destination /Common/10.2.0.10:443
    pool /Common/backend_pool
    profiles {
        /Common/tcp { }
        /Common/http { }
        /Common/clientssl { context clientside }
        /Common/serverssl { context serverside }
    }
    policies {
        /Common/http_router { }
    }
    fw-enforced-policy /Common/edge_fw
    vlans {
        /Common/client_vlan
    }
    vlans-enabled
    translate-address disabled
    translate-port disabled
    ip-protocol tcp
}
net route /Common/default_to_t3 {
    gw 10.3.24.254
    network default
}
