# tcl-lsp — a language server and toolchain for Tcl
# Copyright (C) 2026 James Deucker (bitwisecook) <https://github.com/bitwisecook>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# SPDX-License-Identifier: AGPL-3.0-or-later

FROM docker.io/library/debian:12-slim

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install --yes --no-install-recommends \
        attr \
        dnsutils \
        krb5-user \
        ldap-utils \
        samba-ad-dc \
        samba-ad-provision \
        samba-dsdb-modules \
        winbind \
    && rm -rf /var/lib/apt/lists/*

COPY entrypoint.sh /usr/local/sbin/evtflow-samba-entrypoint
COPY provision-ad.sh /usr/local/sbin/evtflow-samba-provision

ENTRYPOINT ["/usr/local/sbin/evtflow-samba-entrypoint"]
