# tcl-lsp — a language server and toolchain for Tcl
# Copyright (C) 2026 James Deucker (bitwisecook) <https://github.com/bitwisecook>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

"""Type stubs for the `sublime` module, provided by the Sublime Text host.

The module only exists inside the editor process, so type checkers cannot
resolve it from a normal environment. This stub declares just the surface
`editors/sublime-text/plugin.py` touches; extend it as the plugin grows.
"""

from typing import Any, Callable, Sequence

class Settings:
    def get(self, key: str, default: Any = ...) -> Any: ...
    def set(self, key: str, value: Any) -> None: ...
    def has(self, key: str) -> bool: ...
    def erase(self, key: str) -> None: ...
    def add_on_change(self, tag: str, callback: Callable[[], None]) -> None: ...
    def clear_on_change(self, tag: str) -> None: ...

class Edit: ...

class Region:
    a: int
    b: int

class Selection(Sequence[Region]): ...

class Syntax:
    name: str
    path: str
    scope: str

class View:
    def id(self) -> int: ...
    def run_command(self, cmd: str, args: dict[str, Any] | None = ...) -> None: ...
    def settings(self) -> Settings: ...
    def syntax(self) -> Syntax | None: ...
    def sel(self) -> Selection: ...
    def match_selector(self, point: int, selector: str) -> bool: ...

class Window:
    def active_view(self) -> View | None: ...
    def run_command(self, cmd: str, args: dict[str, Any] | None = ...) -> None: ...
    def show_input_panel(
        self,
        caption: str,
        initial_text: str,
        on_done: Callable[[str], None] | None,
        on_change: Callable[[str], None] | None,
        on_cancel: Callable[[], None] | None,
    ) -> View: ...
    def show_quick_panel(
        self,
        items: Sequence[Any],
        on_select: Callable[[int], None],
        flags: int = ...,
        selected_index: int = ...,
        on_highlight: Callable[[int], None] | None = ...,
    ) -> None: ...

def platform() -> str: ...
def arch() -> str: ...
def packages_path() -> str: ...
def cache_path() -> str: ...
def installed_packages_path() -> str: ...
def load_settings(base_name: str) -> Settings: ...
def save_settings(base_name: str) -> None: ...
def status_message(string: str) -> None: ...
def error_message(string: str) -> None: ...
def message_dialog(string: str) -> None: ...
def ok_cancel_dialog(string: str, ok_title: str = ..., title: str = ...) -> bool: ...
def find_resources(pattern: str) -> list[str]: ...
def load_resource(name: str) -> str: ...
def load_binary_resource(name: str) -> bytes: ...
def set_timeout(callback: Callable[[], Any], delay: int = ...) -> None: ...
