ltm rule lab_p_default {
when HTTP_REQUEST {
  log local0. "PRIO default(500)"
}
}
ltm rule lab_p_low {
when HTTP_REQUEST priority 900 {
  log local0. "PRIO low(900)"
}
}
ltm rule lab_p_high {
when HTTP_REQUEST priority 100 {
  log local0. "PRIO high(100)"
  HTTP::respond 200 content "done\n"
}
}
ltm rule lab_err {
when HTTP_REQUEST {
  log local0. "ERRTEST before"
  set x [expr {1/0}]
  log local0. "ERRTEST after"
}
}
