ltm rule /Common/__tcl_lsp_evtflow_eff_asm_transparent_trace {
    when RULE_INIT {
        log local0. "EVTFLOW2|run=EFF|event=RULE_INIT|tmm=[TMM::cmp_group]:[TMM::cmp_unit]|probe=asm|mode=transparent"
    }
    when HTTP_REQUEST priority 100 {
        set evtflow2_asm_id [HTTP::header value X-Evtflow-Request]
        ASM::enable /Common/__tcl_lsp_evtflow_eff_asm_transparent
        log local0. "EVTFLOW2|run=EFF|event=HTTP_REQUEST|tmm=[TMM::cmp_group]:[TMM::cmp_unit]|probe=asm|mode=transparent|id=$evtflow2_asm_id|uri=[HTTP::uri]"
    }
    when ASM_REQUEST_DONE {
        log local0. "EVTFLOW2|run=EFF|event=ASM_REQUEST_DONE|tmm=[TMM::cmp_group]:[TMM::cmp_unit]|probe=asm|mode=transparent|id=$evtflow2_asm_id|status=[ASM::status]|count=[ASM::violation count]|names=[ASM::violation names]"
    }
    when ASM_REQUEST_VIOLATION {
        log local0. "EVTFLOW2|run=EFF|event=ASM_REQUEST_VIOLATION|tmm=[TMM::cmp_group]:[TMM::cmp_unit]|probe=asm|mode=transparent|id=$evtflow2_asm_id"
    }
    when ASM_REQUEST_BLOCKING {
        log local0. "EVTFLOW2|run=EFF|event=ASM_REQUEST_BLOCKING|tmm=[TMM::cmp_group]:[TMM::cmp_unit]|probe=asm|mode=transparent|id=$evtflow2_asm_id|policy=[ASM::policy]"
    }
    when ASM_RESPONSE_VIOLATION {
        log local0. "EVTFLOW2|run=EFF|event=ASM_RESPONSE_VIOLATION|tmm=[TMM::cmp_group]:[TMM::cmp_unit]|probe=asm|mode=transparent|id=$evtflow2_asm_id"
    }
}
