# tcl-lsp — a language server and toolchain for Tcl
# Copyright (C) 2026 James Deucker (bitwisecook) <https://github.com/bitwisecook>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Enriched from F5 iRules reference documentation.
"""HTTP2::active -- This command can be used to determine if a request or response is generated by HTTP/2."""

from __future__ import annotations

from compiler.registry._base import CommandDef
from compiler.registry.models import CommandSpec, FormKind, FormSpec, HoverSnippet, ValidationSpec
from compiler.registry.namespace_models import EventRequires
from compiler.registry.signatures import Arity
from compiler.side_effects import ConnectionSide, SideEffect, SideEffectTarget

from ._base import _IRULES_ONLY, register

_SOURCE = "https://clouddocs.f5.com/api/irules/HTTP2__active.html"


@register
class Http2ActiveCommand(CommandDef):
    name = "HTTP2::active"

    @classmethod
    def spec(cls) -> CommandSpec:
        return CommandSpec(
            name="HTTP2::active",
            dialects=_IRULES_ONLY,
            hover=HoverSnippet(
                summary="This command can be used to determine if a request or response is generated by HTTP/2.",
                synopsis=("HTTP2::active",),
                snippet="Returns 1 if the HTTP transaction is using HTTP/2. Returns 0 otherwise.",
                source=_SOURCE,
                examples=(
                    "when HTTP_REQUEST {\n"
                    "    if {[HTTP2::active]} {\n"
                    '        log local0. "request from HTTP/2 client"\n'
                    "    }\n"
                    "}"
                ),
                return_value="The return is 1 if the HTTP transaction is using HTTP/2, 0 otherwise.",
            ),
            forms=(
                FormSpec(
                    kind=FormKind.DEFAULT,
                    synopsis="HTTP2::active",
                ),
            ),
            validation=ValidationSpec(
                arity=Arity(),
            ),
            event_requires=EventRequires(
                transport="tcp",
                profiles=frozenset({"HTTP"}),
                also_in=frozenset({"MR_INGRESS", "MR_EGRESS"}),
            ),
            side_effect_hints=(
                SideEffect(
                    target=SideEffectTarget.HTTP2_STATE,
                    reads=True,
                    connection_side=ConnectionSide.BOTH,
                ),
            ),
        )
