# tcl-lsp — a language server and toolchain for Tcl
# Copyright (C) 2026 James Deucker (bitwisecook) <https://github.com/bitwisecook>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Enriched from F5 iRules reference documentation.
"""HTTP::retry -- Resends a request to a server."""

from __future__ import annotations

from compiler.registry._base import CommandDef
from compiler.registry.models import (
    CommandSpec,
    FormKind,
    FormSpec,
    HoverSnippet,
    OptionSpec,
    ValidationSpec,
)
from compiler.registry.namespace_models import EventRequires
from compiler.registry.signatures import Arity
from compiler.side_effects import ConnectionSide, SideEffect, SideEffectTarget

from ._base import _IRULES_ONLY, register

_SOURCE = "https://clouddocs.f5.com/api/irules/HTTP__retry.html"


@register
class HttpRetryCommand(CommandDef):
    name = "HTTP::retry"

    @classmethod
    def spec(cls) -> CommandSpec:
        return CommandSpec(
            name="HTTP::retry",
            dialects=_IRULES_ONLY,
            hover=HoverSnippet(
                summary="Resends a request to a server.",
                synopsis=("HTTP::retry ('-reset')? HTTP_REQUEST",),
                snippet=(
                    "Re-sends a request to a server. Can be either the same or a different\n"
                    "request, to the same or a different server.\n"
                    "  * To replay the same request, save the request to a variable in the\n"
                    "    HTTP_REQUEST event, then use it with this command.\n"
                    "  * A different request may alternatively be specified. The request\n"
                    "    string must be well-formed and complete, including all required\n"
                    "    headers.\n"
                    "\n"
                    "The request generated by this command triggers HTTP_REQUEST and\n"
                    "all subsequent client-side events."
                ),
                source=_SOURCE,
                examples=(
                    "when LB_SELECTED {\n"
                    "   # Select a new pool member from the VS default pool if we are retrying this request\n"
                    "   if { $retries > 0 } {\n"
                    "      LB::reselect pool $default_pool\n"
                    "   }\n"
                    "}"
                ),
            ),
            forms=(
                FormSpec(
                    kind=FormKind.DEFAULT,
                    synopsis="HTTP::retry ('-reset')? HTTP_REQUEST",
                    options=(
                        OptionSpec(
                            name="-reset",
                            detail="Reset the server-side connection.",
                            takes_value=False,
                        ),
                    ),
                ),
            ),
            validation=ValidationSpec(
                arity=Arity(),
            ),
            event_requires=EventRequires(transport="tcp", profiles=frozenset({"HTTP", "FASTHTTP"})),
            diagram_action=True,
            side_effect_hints=(
                SideEffect(
                    target=SideEffectTarget.HTTP_HEADER,
                    writes=True,
                    connection_side=ConnectionSide.SERVER,
                ),
            ),
        )
