ltm rule probe_switch_regex_mixed {
when HTTP_REQUEST {
set myvar x12y-az09.example.com
switch -regexp -- $myvar {
    "x[0-9][0-9]y\-[a-z0-9]+\.example\.com" {
        set r 1
    }
    {z[0-9]\-[a-z0-9]+\.example\.net} {
        set r 2
    }
}
}
}
