// tcl-lsp — a language server and toolchain for Tcl
// Copyright (C) 2026 James Deucker (bitwisecook) <https://github.com/bitwisecook>
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
// SPDX-License-Identifier: AGPL-3.0-or-later

//! Project the bundled packs' `environment` blocks into
//! `rust/tcl-dialect/src/model/bundled_environments.rs` (redesign D17).
//!
//! The packs under `specs/` are the source of truth for the environments
//! they declare; the generated table is what seeds the compiled
//! environment registry at generation 0, so those environments resolve
//! before — and without — a pack publish. `--check` makes the committed
//! file a drift gate against the packs.
//!
//! The output is passed through `rustfmt`, so the committed file is exactly
//! what `cargo fmt` would leave it as.

use std::fmt::Write as _;
use std::fs;
use std::io::Write as _;
use std::process::{Command, ExitCode, Stdio};

use anyhow::{Context, Result, bail};
use tcl_dialect::model::Placement;
use tcl_spectcl::PackEnvironment;

use crate::util::{repo_root, write_if_changed};

const OUTPUT: &str = "rust/tcl-dialect/src/model/bundled_environments.rs";

const HEADER: &str = "//! The `environment` blocks of the bundled packs under `specs/`, projected
//! to Rust.
//!
//! @generated by `cargo xtask gen-bundled-environments` — do not edit by
//! hand. The packs are the source of truth (redesign D17): edit the block
//! in its `.tclspec` and regenerate; `--check` holds this file to the packs.

use super::environment::{BundledCore, BundledEnvironmentRow, BundledPlacement, BundledVersion};
use super::{BuildProfileId, Family, KeyedAxis, WorldPolicy};

pub(crate) const BUNDLED_ENVIRONMENTS: &[BundledEnvironmentRow] = &[
";

/// A `&'static [&'static str]` literal.
fn strs(items: impl IntoIterator<Item = impl AsRef<str>>) -> String {
    let items: Vec<String> = items
        .into_iter()
        .map(|item| format!("{:?}", item.as_ref()))
        .collect();
    format!("&[{}]", items.join(", "))
}

fn render_row(pack: &str, environment: &PackEnvironment) -> Result<String> {
    let mut out = String::new();
    let id = &environment.id;
    if environment.pack_core.is_some() {
        bail!(
            "pack {pack}: `environment {id}` selects a pack-declared dialect as its core; a \
             bundled environment must select a compiled family, because the generated seed \
             has no dynamic core to name"
        );
    }
    let core = environment.core.map_or_else(
        || "None".to_owned(),
        |core| {
            format!(
                "Some(BundledCore {{ family: Family::{:?}, release: {:?}, build: \
                 BuildProfileId::{:?} }})",
                core.family,
                core.default_release.as_str(),
                core.build
            )
        },
    );
    let mut placements = String::new();
    for placement in &environment.placements {
        let version = match &placement.version {
            Placement::Pinned(_) => format!("BundledVersion::Pinned({:?})", placement.version_word),
            Placement::TracksBase => "BundledVersion::TracksBase".to_owned(),
            Placement::Keyed(axis) => format!("BundledVersion::Keyed(KeyedAxis::{axis:?})"),
            Placement::Requirement(_) => {
                format!("BundledVersion::Requirement({:?})", placement.version_word)
            }
        };
        let _ = writeln!(
            placements,
            "BundledPlacement {{ package: {:?}, version: {version}, ambient: {} }},",
            placement.package, placement.ambient
        );
    }
    let extensions: Vec<String> = environment
        .file_extensions
        .iter()
        .map(|claim| {
            format!(
                "({:?}, {:?})",
                claim.extension.as_ref(),
                claim.display_name.as_ref()
            )
        })
        .collect();
    let _ = writeln!(out, "BundledEnvironmentRow {{");
    let _ = writeln!(out, "id: {id:?},");
    let _ = writeln!(
        out,
        "display_name: {:?},",
        environment.display_name.as_deref().unwrap_or(id)
    );
    let _ = writeln!(out, "aliases: {},", strs(&environment.aliases));
    let _ = writeln!(
        out,
        "editor_identity: {},",
        environment.editor_identity.map_or_else(
            || "None".to_owned(),
            |identity| format!("Some({:?})", identity.as_str())
        )
    );
    let _ = writeln!(out, "core: {core},");
    let _ = writeln!(out, "placements: &[{placements}],");
    let _ = writeln!(
        out,
        "world_policy: WorldPolicy::{:?},",
        environment.world_policy
    );
    let _ = writeln!(
        out,
        "version_ceiling: {},",
        environment.version_ceiling.map_or_else(
            || "None".to_owned(),
            |release| format!("Some({:?})", release.as_str())
        )
    );
    let _ = writeln!(out, "file_extensions: &[{}],", extensions.join(", "));
    let _ = writeln!(out, "filenames: {},", strs(&environment.filenames));
    let _ = writeln!(out, "signatures: {},", strs(&environment.signatures));
    let _ = writeln!(out, "help_terms: {},", strs(&environment.help_terms));
    let _ = writeln!(out, "}},");
    Ok(out)
}

/// The generated module text, formatted.
fn render() -> Result<String> {
    let root = repo_root();
    let set = tcl_spectcl::bundled::load_from(&root.join("specs"));
    let mut text = HEADER.to_owned();
    let mut rows = 0_usize;
    for pack in &set.packs {
        for environment in pack.environments.iter().filter(|e| !e.extends) {
            text.push_str(&render_row(&pack.name, environment)?);
            rows += 1;
        }
    }
    text.push_str("];\n");
    eprintln!(
        "  {rows} bundled environment block(s) across {} pack(s)",
        set.packs.len()
    );
    rustfmt(&text)
}

fn rustfmt(text: &str) -> Result<String> {
    let mut child = Command::new("rustfmt")
        .args(["--edition", "2024", "--emit", "stdout"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::inherit())
        .spawn()
        .context("spawning rustfmt (part of the pinned Rust toolchain)")?;
    child
        .stdin
        .take()
        .context("rustfmt stdin")?
        .write_all(text.as_bytes())
        .context("writing to rustfmt")?;
    let output = child.wait_with_output().context("waiting for rustfmt")?;
    if !output.status.success() {
        bail!("rustfmt rejected the generated module: {}", output.status);
    }
    String::from_utf8(output.stdout).context("rustfmt output is not UTF-8")
}

pub fn run(check: bool) -> Result<ExitCode> {
    let path = repo_root().join(OUTPUT);
    let rendered = render()?;
    let original = fs::read_to_string(&path).unwrap_or_default();
    if original == rendered {
        if check {
            eprintln!("OK: {OUTPUT} matches the bundled packs' environment blocks.");
        }
        return Ok(ExitCode::SUCCESS);
    }
    if check {
        eprintln!(
            "{OUTPUT} is stale against the bundled packs' environment blocks — run `cargo xtask \
             gen-bundled-environments`"
        );
        return Ok(ExitCode::from(1));
    }
    if write_if_changed(&path, rendered)? {
        eprintln!("wrote {OUTPUT}");
    }
    Ok(ExitCode::SUCCESS)
}
