//! Generate the VS Code iRules-event catalog JSON from the Rust event registry
//! — the native successor to `scripts/codegen/catalogs.py`.
//!
//! One checked-in artifact is a pure projection of `tcl-registry`:
//! `editors/vscode/src/generated/iruleEvents.json`, with event descriptions
//! and `common`/`hot`/lifecycle flags.
//!
//! Run `cargo xtask gen-editor-catalogs` to (re)write them; `--check` verifies
//! the committed files match what the registry would produce, exiting non-zero
//! on drift — the same invariant the `committed_catalogs_match_generated` test
//! pins into the `cargo test` gate.
//!
//! Serialised with stock `serde_json` 2-space pretty-printing (raw UTF-8).

use anyhow::{Context, Result};
use serde::Serialize;
use std::fs;
use std::process::ExitCode;
use tcl_registry::events::EventRegistry;

use crate::util::repo_root;

/// The header string stamped into every catalog.
const GENERATED_HEADER: &str = "DO NOT EDIT — generated by `cargo xtask gen-editor-catalogs`";

/// `false`-testing helper for `#[serde(skip_serializing_if)]` (a boolean is
/// only emitted when set).
#[allow(clippy::trivially_copy_pass_by_ref)]
fn is_false(b: &bool) -> bool {
    !*b
}

#[derive(Serialize)]
struct EventEntry {
    name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    description: Option<String>,
    #[serde(skip_serializing_if = "is_false")]
    common: bool,
    #[serde(skip_serializing_if = "is_false")]
    hot: bool,
    // Lifecycle metadata is carried through rather than flattened to a
    // boolean: `retiredVersion` is the exclusive first release without the
    // event, so a consumer can distinguish "deprecated" from "gone".
    #[serde(rename = "introducedVersion", skip_serializing_if = "Option::is_none")]
    introduced_version: Option<&'static str>,
    #[serde(rename = "deprecatedVersion", skip_serializing_if = "Option::is_none")]
    deprecated_version: Option<&'static str>,
    #[serde(rename = "retiredVersion", skip_serializing_if = "Option::is_none")]
    retired_version: Option<&'static str>,
}

#[derive(Serialize)]
struct EventDetailsCatalog {
    #[serde(rename = "__generated")]
    generated: &'static str,
    events: Vec<EventEntry>,
}

/// The sorted iRules event names shared by both editor catalogs.
fn sorted_event_names(events: &EventRegistry) -> Vec<&str> {
    let mut names = events.all_event_names();
    names.sort_unstable();
    names
}

/// `iruleEvents.json` (VS Code) — events with description + flags so the
/// extension carries no hardcoded lists.
fn vscode_irule_events_catalog(events: &EventRegistry) -> EventDetailsCatalog {
    let list = sorted_event_names(events)
        .into_iter()
        .map(|name| {
            let props = events.get_props(name);
            EventEntry {
                name: name.to_owned(),
                description: events.description(name).map(str::to_owned),
                common: props.is_some_and(|p| p.common),
                hot: props.is_some_and(|p| p.hot),
                introduced_version: props.and_then(|p| p.lifecycle.introduced),
                deprecated_version: props.and_then(|p| p.lifecycle.deprecated),
                retired_version: props.and_then(|p| p.lifecycle.retired),
            }
        })
        .collect();
    EventDetailsCatalog {
        generated: GENERATED_HEADER,
        events: list,
    }
}

/// Serialise a catalog as 2-space pretty JSON with a trailing newline.
fn to_json(value: &impl Serialize) -> String {
    serde_json::to_string_pretty(value).expect("serialise catalog") + "\n"
}

/// The `(relative-path, content)` catalogs the verb owns.
fn catalogs() -> Vec<(&'static str, String)> {
    let events = EventRegistry::build();
    vec![(
        "editors/vscode/src/generated/iruleEvents.json",
        to_json(&vscode_irule_events_catalog(&events)),
    )]
}

/// Write (or, with `check`, verify) the editor catalog file.
pub fn run(check: bool) -> Result<ExitCode> {
    let root = repo_root();
    let mut drift = Vec::new();
    for (rel, content) in catalogs() {
        let path = root.join(rel);
        if check {
            let current =
                fs::read_to_string(&path).with_context(|| format!("reading {}", path.display()))?;
            if current != content {
                drift.push(rel);
            }
        } else {
            fs::write(&path, &content).with_context(|| format!("writing {}", path.display()))?;
            eprintln!("wrote {rel}");
        }
    }

    if check && !drift.is_empty() {
        eprintln!(
            "{} generated editor catalog(s) are stale — run `cargo xtask gen-editor-catalogs`:",
            drift.len()
        );
        for rel in &drift {
            eprintln!("  - {rel}");
        }
        return Ok(ExitCode::from(1));
    }
    if check {
        eprintln!("OK: all generated editor catalogs are in sync with the registry.");
    }
    Ok(ExitCode::SUCCESS)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The drift guard: the committed catalogs must equal what the registry
    /// renders. A command/event/summary change without regenerating fails here.
    #[test]
    fn committed_catalogs_match_generated() {
        let root = repo_root();
        for (rel, content) in catalogs() {
            let path = root.join(rel);
            let current = fs::read_to_string(&path)
                .unwrap_or_else(|e| panic!("reading {}: {e}", path.display()));
            assert_eq!(
                current, content,
                "{rel} is stale — run `cargo xtask gen-editor-catalogs`"
            );
        }
    }
}
