// tcl-lsp — a language server and toolchain for Tcl
// Copyright (C) 2026 James Deucker (bitwisecook) <https://github.com/bitwisecook>
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
// SPDX-License-Identifier: AGPL-3.0-or-later

//! Small shared helpers for the xtask subcommands.

use std::ffi::OsString;
use std::fmt::Write as _;
use std::fs::{self, OpenOptions};
use std::io::{ErrorKind, Write as _};
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicU64, Ordering};

use anyhow::{Context, Result};

static NEXT_STAGED_FILE: AtomicU64 = AtomicU64::new(0);

/// The AGPL-3.0 copyright banner, every line prefixed with `line_comment`
/// (e.g. `"//"` for Rust/TS/Kotlin/JS, `"#"` for Python/shell).
///
/// Generated source files must carry the same licence header as hand-written
/// ones; the generator inserts it at the top of the file it emits. The banner
/// ends with a trailing newline but no blank line, so callers append their own
/// `\n` separator before the generated-marker / body.
#[must_use]
pub fn license_banner(line_comment: &str) -> String {
    const LINES: &[&str] = &[
        "tcl-lsp — a language server and toolchain for Tcl",
        "Copyright (C) 2026 James Deucker (bitwisecook) <https://github.com/bitwisecook>",
        "",
        "This program is free software: you can redistribute it and/or modify",
        "it under the terms of the GNU Affero General Public License as published by",
        "the Free Software Foundation, either version 3 of the License, or",
        "(at your option) any later version.",
        "",
        "This program is distributed in the hope that it will be useful,",
        "but WITHOUT ANY WARRANTY; without even the implied warranty of",
        "MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the",
        "GNU Affero General Public License for more details.",
        "",
        "You should have received a copy of the GNU Affero General Public License",
        "along with this program.  If not, see <https://www.gnu.org/licenses/>.",
        "",
        "SPDX-License-Identifier: AGPL-3.0-or-later",
    ];
    let mut out = String::new();
    for line in LINES {
        if line.is_empty() {
            let _ = writeln!(out, "{line_comment}");
        } else {
            let _ = writeln!(out, "{line_comment} {line}");
        }
    }
    out
}

/// The repository root, derived from this crate's location
/// (`<root>/rust/xtask`) so tasks work regardless of the working
/// directory `cargo xtask` is invoked from.
pub fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(2)
        .expect("xtask crate lives at <root>/rust/xtask")
        .to_path_buf()
}

/// Atomically replace generated bytes only when their content differs from the
/// file on disk. Preserving the mtime for an identical output keeps Cargo
/// build-script dependencies fresh across consecutive generators; staging a
/// changed output beside its destination prevents an interrupted write from
/// leaving a partial tracked file.
///
/// Returns `true` when the file was created or replaced.
pub fn write_if_changed(path: &Path, contents: impl AsRef<[u8]>) -> Result<bool> {
    let contents = contents.as_ref();
    match fs::read(path) {
        Ok(current) if current == contents => return Ok(false),
        Ok(_) => {}
        Err(error) if error.kind() == ErrorKind::NotFound => {}
        Err(error) => {
            return Err(error).with_context(|| format!("reading {}", path.display()));
        }
    }

    let parent = path
        .parent()
        .with_context(|| format!("generated path has no parent: {}", path.display()))?;
    let (staged_path, mut staged) = loop {
        let serial = NEXT_STAGED_FILE.fetch_add(1, Ordering::Relaxed);
        let mut name = OsString::from(".");
        name.push(path.file_name().unwrap_or_default());
        name.push(format!(".{}.{serial}.tmp", std::process::id()));
        let staged_path = parent.join(name);
        match OpenOptions::new()
            .write(true)
            .create_new(true)
            .open(&staged_path)
        {
            Ok(file) => break (staged_path, file),
            Err(error) if error.kind() == ErrorKind::AlreadyExists => {}
            Err(error) => {
                return Err(error).with_context(|| format!("staging {}", path.display()));
            }
        }
    };

    // Replacing an existing path via rename would otherwise adopt the staged
    // file's creation mode. Generated scripts and data must keep the
    // permissions they had before this helper was introduced.
    let permissions = match fs::metadata(path) {
        Ok(metadata) => Some(metadata.permissions()),
        Err(error) if error.kind() == ErrorKind::NotFound => None,
        Err(error) => {
            drop(staged);
            let _ = fs::remove_file(&staged_path);
            return Err(error).with_context(|| format!("reading metadata for {}", path.display()));
        }
    };

    let stage_result = (|| -> Result<()> {
        staged
            .write_all(contents)
            .with_context(|| format!("staging contents for {}", path.display()))?;
        if let Some(permissions) = permissions {
            staged
                .set_permissions(permissions)
                .with_context(|| format!("preserving permissions for {}", path.display()))?;
        }
        staged
            .sync_all()
            .with_context(|| format!("syncing staged contents for {}", path.display()))?;
        Ok(())
    })();
    drop(staged);
    if let Err(error) = stage_result {
        let _ = fs::remove_file(&staged_path);
        return Err(error);
    }
    if let Err(error) = fs::rename(&staged_path, path) {
        let _ = fs::remove_file(&staged_path);
        return Err(error).with_context(|| format!("replacing {}", path.display()));
    }
    Ok(true)
}

/// Placeholder registry entry (`irules_disabled.rs`) marking a command as
/// unavailable in iRules — never a real command name to project into a
/// generated editor grammar/query. Shared by every generator that walks
/// [`tcl_registry::CommandRegistry::command_names`] (`gen_zed_queries`,
/// `gen_tmlanguage_keywords`).
pub const DISABLED_SENTINEL: &str = "disabled_in_irules";

/// `true` when `name` is safe to embed literally in a generated regex
/// alternation / tree-sitter `#any-of?` list: ASCII alphanumerics, `_`, or
/// `:` only. Shared by every generator that projects
/// [`tcl_registry::CommandRegistry::command_names`] into a static editor
/// grammar/query (`gen_zed_queries`, `gen_tmlanguage_keywords`).
#[must_use]
pub fn is_safe_command_name(name: &str) -> bool {
    name.chars()
        .all(|c| c.is_ascii_alphanumeric() || c == '_' || c == ':')
}

/// `true` when `name` is registry noise that is real (has a `CommandSpec`)
/// but not a "common built-in" or "common command" by any reasonable
/// definition, so generated editor grammars/queries should exclude it even
/// though it passes the ambient-dialect / no-`required_package` filter:
///
/// * `testXxx` — Tcl core's own, stable naming convention for commands that
///   exist only in the special `tcltest`-instrumented debug build
///   (`tclUnixTest.c` et al), never present in a normal user interpreter.
/// * `::tcl::…` / `tcl::…` — Tcl's own reserved internal-implementation
///   namespace (documented as such), technically callable but not something
///   a user would recognise as a built-in command. Checked as a *prefix*
///   (`name.starts_with("tcl::")`, after stripping a leading `::`), not a
///   substring match — a substring check would also match unrelated
///   namespaces that merely end in `tcl` before their own `::`, e.g.
///   `itcl::class` (the `itcl` package's own namespace, not `::tcl::`).
///
/// Shared by every generator that projects
/// [`tcl_registry::CommandRegistry::command_names`] into a static editor
/// grammar/query (`gen_zed_queries`, `gen_tmlanguage_keywords`).
#[must_use]
pub fn is_internal_or_test_harness_noise(name: &str) -> bool {
    let is_test_harness = name.starts_with("test") && name.len() > "test".len();
    let is_tcl_internal_namespace = name.strip_prefix("::").unwrap_or(name).starts_with("tcl::");
    is_test_harness || is_tcl_internal_namespace
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::atomic::{AtomicU64, Ordering};

    static NEXT_TEMP: AtomicU64 = AtomicU64::new(0);

    #[test]
    fn internal_namespace_check_is_a_prefix_not_a_substring() {
        // The actual reserved namespace — must be excluded, bare and `::`-qualified.
        assert!(is_internal_or_test_harness_noise("tcl::mathop::eq"));
        assert!(is_internal_or_test_harness_noise("::tcl::mathop::eq"));
        assert!(is_internal_or_test_harness_noise("::tcl::process"));
        // A DIFFERENT package's namespace that merely ends in "tcl" before its
        // own "::" must NOT be excluded (issue caught in PR #866 review: a
        // `.contains("tcl::")` substring check wrongly matched this).
        assert!(!is_internal_or_test_harness_noise("itcl::class"));
        assert!(!is_internal_or_test_harness_noise("itcl::configure"));
    }

    #[test]
    fn test_prefix_check_requires_more_than_the_bare_word() {
        assert!(is_internal_or_test_harness_noise("testalarm"));
        assert!(is_internal_or_test_harness_noise("testchannel"));
        // Real commands that merely start with "test" as a substring of a
        // longer unrelated word, or are exactly "test", must survive.
        assert!(!is_internal_or_test_harness_noise("test"));
    }

    #[test]
    fn safe_command_name_rejects_regex_metacharacters() {
        assert!(is_safe_command_name("lappend"));
        assert!(is_safe_command_name("tcl::mathop::eq"));
        assert!(!is_safe_command_name("+"));
        assert!(!is_safe_command_name("a.b"));
    }

    #[test]
    fn generated_output_is_created_changed_or_preserved_by_content() {
        let serial = NEXT_TEMP.fetch_add(1, Ordering::Relaxed);
        let nanos = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .expect("system clock is after the Unix epoch")
            .as_nanos();
        let path = std::env::temp_dir().join(format!(
            "tcl-xtask-write-if-changed-{}-{nanos}-{serial}",
            std::process::id()
        ));
        assert!(write_if_changed(&path, b"same\n").expect("create generated file"));
        let before = fs::metadata(&path)
            .expect("stat generated file")
            .modified()
            .expect("read generated file mtime");

        assert!(!write_if_changed(&path, b"same\n").expect("compare identical output"));
        assert_eq!(
            before,
            fs::metadata(&path)
                .expect("restat generated file")
                .modified()
                .expect("reread generated file mtime")
        );
        assert!(write_if_changed(&path, b"changed\n").expect("replace changed output"));
        assert_eq!(fs::read(&path).expect("read changed output"), b"changed\n");

        fs::remove_file(path).expect("remove temporary generated file");
    }

    #[cfg(unix)]
    #[test]
    fn changed_generated_output_preserves_existing_permissions() {
        use std::os::unix::fs::PermissionsExt;

        let serial = NEXT_TEMP.fetch_add(1, Ordering::Relaxed);
        let path = std::env::temp_dir().join(format!(
            "tcl-xtask-write-permissions-{}-{serial}",
            std::process::id()
        ));
        fs::write(&path, b"before\n").expect("create generated file");
        fs::set_permissions(&path, fs::Permissions::from_mode(0o754))
            .expect("set generated file permissions");

        assert!(write_if_changed(&path, b"after\n").expect("replace generated file"));
        assert_eq!(
            fs::metadata(&path)
                .expect("stat generated file")
                .permissions()
                .mode()
                & 0o777,
            0o754
        );

        fs::remove_file(path).expect("remove temporary generated file");
    }
}
