// tcl-lsp — a language server and toolchain for Tcl
// Copyright (C) 2026 James Deucker (bitwisecook) <https://github.com/bitwisecook>
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
// SPDX-License-Identifier: AGPL-3.0-or-later

/**
 * Every dialect the server accepts, projected from
 * `tcl_dialect::DialectProfile::all()`.
 *
 * Generated by `cargo xtask gen-ai-diagnostics` — edit the profile catalogue,
 * not this file. Kept free of `vscode` imports (the `../languageIds` pattern)
 * so chat modules and their unit tests can name dialects without the language
 * client.
 */

export interface DialectEntry {
  /** Canonical dialect name — the string the server and `set_dialect` take. */
  readonly name: string;
  /** Human-facing display name. */
  readonly label: string;
  /** File extensions this dialect owns, without the leading dot. */
  readonly extensions: readonly string[];
}

export const DIALECT_CATALOG: readonly DialectEntry[] = [
  { name: "bpf", label: "BPF", extensions: [] },
  { name: "cadence-eda-tcl", label: "Cadence EDA Tcl", extensions: ["globals"] },
  { name: "expect", label: "Expect", extensions: ["exp", "expect"] },
  { name: "f5-bigip", label: "F5 BIG-IP", extensions: ["scf"] },
  { name: "f5-iapps", label: "F5 iApps", extensions: ["iapp", "iappimpl", "impl"] },
  { name: "f5-irules", label: "F5 iRules", extensions: ["irul", "irule", "irules"] },
  { name: "f5-tmsh", label: "F5 tmsh Scripts", extensions: ["tmsh"] },
  {
    name: "intel-quartus-eda-tcl",
    label: "Intel Quartus EDA Tcl",
    extensions: ["qsf", "qpf", "qip"],
  },
  { name: "mentor-eda-tcl", label: "Mentor EDA Tcl", extensions: ["do"] },
  { name: "microchip-libero-eda-tcl", label: "Microchip Libero EDA Tcl", extensions: [] },
  { name: "spectcl", label: "SpecTcl", extensions: ["tclspec"] },
  { name: "synopsys-eda-tcl", label: "Synopsys EDA Tcl", extensions: ["sdc", "upf"] },
  { name: "tcl8.4", label: "Tcl 8.4", extensions: [] },
  { name: "tcl8.5", label: "Tcl 8.5", extensions: [] },
  { name: "tcl8.6", label: "Tcl 8.6", extensions: [] },
  { name: "tcl9.0", label: "Tcl 9.0", extensions: [] },
  { name: "tcl9.1", label: "Tcl 9.1", extensions: [] },
  { name: "xilinx-eda-tcl", label: "Xilinx EDA Tcl", extensions: ["xdc"] },
];

/** Canonical dialect name to display label. */
export const DIALECT_LABELS: Readonly<Record<string, string>> = Object.fromEntries(
  DIALECT_CATALOG.map((dialect) => [dialect.name, dialect.label]),
);
