// tcl-lsp — a language server and toolchain for Tcl
// Copyright (C) 2026 James Deucker (bitwisecook) <https://github.com/bitwisecook>
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
// SPDX-License-Identifier: AGPL-3.0-or-later

/**
 * Every dialect the server accepts, projected from the selectable
 * environments of `tcl_dialect::model::EnvironmentRegistry`.
 *
 * Generated by `cargo xtask gen-ai-diagnostics` — edit the environment
 * registry, not this file. It is the offline copy of what the server's
 * `tcl-lsp.listDialects` command answers, for a host with no running server
 * (the browser entry before its worker has started, the chat help text), and
 * the fallback the status bar reads until the server has said which dialect a
 * document is analysed under. Kept free of `vscode` imports (the
 * `../languageIds` pattern) so chat modules and their unit tests can name
 * dialects without the language client.
 */

/** `language`: the thing written is this language. `packages`: a Tcl release with library packages loaded. */
export type DialectKind = "language" | "packages";

export interface DialectEntry {
  /** Canonical dialect name — the string the server and `set_dialect` take. */
  readonly name: string;
  /** Human-facing display name. */
  readonly label: string;
  /** Compact name for the status bar. */
  readonly shortLabel: string;
  /** The group a picker files the dialect under. */
  readonly kind: DialectKind;
  /** One line saying what the dialect is: its name, or a Tcl release plus packages. */
  readonly description: string;
  /** File extensions this dialect owns, without the leading dot. */
  readonly extensions: readonly string[];
}

export const DIALECT_CATALOG: readonly DialectEntry[] = [
  {
    name: "bpf",
    label: "BPF",
    shortLabel: "BPF",
    kind: "language",
    description: "BPF",
    extensions: [],
  },
  {
    name: "expect",
    label: "Expect",
    shortLabel: "Expect",
    kind: "language",
    description: "Expect",
    extensions: ["exp", "expect"],
  },
  {
    name: "f5-bigip",
    label: "F5 BIG-IP",
    shortLabel: "BIG-IP",
    kind: "language",
    description: "F5 BIG-IP",
    extensions: ["scf"],
  },
  {
    name: "f5-iapps",
    label: "F5 iApps",
    shortLabel: "iApps",
    kind: "language",
    description: "F5 iApps",
    extensions: ["iapp", "iappimpl", "impl"],
  },
  {
    name: "f5-irules",
    label: "F5 iRules",
    shortLabel: "iRules",
    kind: "language",
    description: "F5 iRules",
    extensions: ["irul", "irule", "irules"],
  },
  {
    name: "f5-tmsh",
    label: "F5 tmsh Scripts",
    shortLabel: "tmsh",
    kind: "language",
    description: "F5 tmsh Scripts",
    extensions: ["tmsh"],
  },
  {
    name: "jim",
    label: "Jim Tcl",
    shortLabel: "Jim",
    kind: "language",
    description: "Jim Tcl",
    extensions: [],
  },
  {
    name: "spectcl",
    label: "SpecTcl",
    shortLabel: "SpecTcl",
    kind: "language",
    description: "SpecTcl",
    extensions: ["tclspec"],
  },
  {
    name: "sslictcl",
    label: "SslicTcl",
    shortLabel: "SslicTcl",
    kind: "language",
    description: "SslicTcl",
    extensions: ["sslictcl"],
  },
  {
    name: "tcl8.4",
    label: "Tcl 8.4",
    shortLabel: "Tcl 8.4",
    kind: "language",
    description: "Tcl 8.4",
    extensions: [],
  },
  {
    name: "tcl8.5",
    label: "Tcl 8.5",
    shortLabel: "Tcl 8.5",
    kind: "language",
    description: "Tcl 8.5",
    extensions: [],
  },
  {
    name: "tcl8.6",
    label: "Tcl 8.6",
    shortLabel: "Tcl 8.6",
    kind: "language",
    description: "Tcl 8.6",
    extensions: [],
  },
  {
    name: "tcl9.0",
    label: "Tcl 9.0",
    shortLabel: "Tcl 9.0",
    kind: "language",
    description: "Tcl 9.0",
    extensions: [],
  },
  {
    name: "tcl9.1",
    label: "Tcl 9.1",
    shortLabel: "Tcl 9.1",
    kind: "language",
    description: "Tcl 9.1",
    extensions: [],
  },
  {
    name: "cadence-eda-tcl",
    label: "Cadence Genus / Innovus / Xcelium",
    shortLabel: "Cadence",
    kind: "packages",
    description:
      "Cadence Genus / Innovus / Xcelium — Tcl 8.4 + cadence-genus, cadence-common, cadence-innovus, cadence-xcelium, sdc, upf",
    extensions: ["globals"],
  },
  {
    name: "intel-quartus-eda-tcl",
    label: "Intel Quartus Prime",
    shortLabel: "Quartus",
    kind: "packages",
    description:
      "Intel Quartus Prime — Tcl 8.5 + quartus-project, quartus-flow, quartus-sta, quartus-sdc-ext, quartus-report, quartus-device, quartus-misc, sdc, upf",
    extensions: ["qsf", "qpf", "qip"],
  },
  {
    name: "mentor-eda-tcl",
    label: "Siemens Questa / ModelSim",
    shortLabel: "Questa",
    kind: "packages",
    description: "Siemens Questa / ModelSim — Tcl 8.6 + questa, questa-formal, calibre, sdc, upf",
    extensions: ["do"],
  },
  {
    name: "microchip-libero-eda-tcl",
    label: "Microchip Libero SoC",
    shortLabel: "Libero",
    kind: "packages",
    description: "Microchip Libero SoC — Tcl 8.5 + libero, sdc, upf",
    extensions: [],
  },
  {
    name: "synopsys-eda-tcl",
    label: "Synopsys DC / PrimeTime / ICC2 / Formality",
    shortLabel: "Synopsys",
    kind: "packages",
    description:
      "Synopsys DC / PrimeTime / ICC2 / Formality — Tcl 8.6 + synopsys-dc, synopsys-pt, synopsys-icc2, synopsys-fm, synopsys, sdc, upf",
    extensions: ["sdc", "upf"],
  },
  {
    name: "tk",
    label: "Tk",
    shortLabel: "Tk",
    kind: "packages",
    description: "Tk — Tcl 8.6 + Tk",
    extensions: [],
  },
  {
    name: "xilinx-eda-tcl",
    label: "Xilinx Vivado",
    shortLabel: "Vivado",
    kind: "packages",
    description: "Xilinx Vivado — Tcl 8.5 + vivado, sdc, upf",
    extensions: ["xdc"],
  },
];

/** Canonical dialect name to display label. */
export const DIALECT_LABELS: Readonly<Record<string, string>> = Object.fromEntries(
  DIALECT_CATALOG.map((dialect) => [dialect.name, dialect.label]),
);

/** The dialect a document is analysed under when nothing selects another. */
export const DEFAULT_DIALECT = "tcl8.6";
