// tcl-lsp — a language server and toolchain for Tcl
// Copyright (C) 2026 James Deucker (bitwisecook) <https://github.com/bitwisecook>
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
// SPDX-License-Identifier: AGPL-3.0-or-later

//! Stamp the short git commit hash into `GIT_HASH` so the report generated by
//! the Python `f5report` package can show which build produced it (alongside
//! the engine version). Falls back to `"unknown"` when git metadata is
//! unavailable (e.g. a source tarball / sdist build).

use std::path::{Path, PathBuf};
use std::process::Command;

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    // rust/bigip-report/py -> rust/bigip-report -> rust -> repo root.
    let repo_root = manifest
        .parent()
        .and_then(Path::parent)
        .and_then(Path::parent)
        .map(Path::to_path_buf)
        .unwrap_or_else(|| manifest.clone());

    // A CI / packaging pipeline that builds the wheel outside a git checkout
    // (an sdist build) sets `GIT_HASH` to inject the commit it built from.
    println!("cargo:rerun-if-env-changed=GIT_HASH");

    // Re-run whenever the checked-out commit changes so the stamp stays current.
    // We track the commit *pointer* — HEAD, the branch ref it resolves to (which
    // a commit rewrites), and packed-refs — not working-tree state: an unstaged
    // edit touches none of these files, so a build script keying a "-dirty" flag
    // off them could not be re-run reliably. The stamp is the committed short
    // hash, which is what a shipped report needs.
    watch_commit_refs(&repo_root.join(".git"));

    println!("cargo:rustc-env=GIT_HASH={}", resolve_git_hash(&repo_root));

    // A single `git describe --tags` version (nearest `v*` tag + commits-since +
    // short hash) shown in the report footer instead of a separate engine
    // version and build hash. Explicit `GIT_DESCRIBE` override wins for sdist /
    // out-of-checkout wheel builds.
    println!("cargo:rerun-if-env-changed=GIT_DESCRIBE");
    println!(
        "cargo:rustc-env=GIT_DESCRIBE={}",
        resolve_git_describe(&repo_root)
    );
}

/// The `git describe --tags` version: an explicit `GIT_DESCRIBE` override wins
/// (CI / out-of-checkout builds); otherwise ask git.
fn resolve_git_describe(repo_root: &Path) -> String {
    if let Ok(desc) = std::env::var("GIT_DESCRIBE") {
        let desc = desc.trim();
        if !desc.is_empty() {
            return desc.to_owned();
        }
    }
    git_describe(repo_root)
}

/// `git describe --tags --always` — nearest `v*` tag plus commits-since and the
/// short hash (e.g. `v1.2.3-4-gabcdef0`), or the bare short hash when no tag
/// exists yet. `"unknown"` when git is unavailable.
fn git_describe(repo_root: &Path) -> String {
    Command::new("git")
        .arg("-C")
        .arg(repo_root)
        .args(["describe", "--tags", "--always"])
        .output()
        .ok()
        .filter(|o| o.status.success())
        .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_owned())
        .filter(|s| !s.is_empty())
        .unwrap_or_else(|| "unknown".to_owned())
}

/// The git hash to stamp: an explicit `GIT_HASH` override (set by CI when
/// building outside a checkout) wins; otherwise ask git; otherwise `"unknown"`.
fn resolve_git_hash(repo_root: &Path) -> String {
    if let Ok(hash) = std::env::var("GIT_HASH") {
        let hash = hash.trim();
        if !hash.is_empty() {
            return hash.to_owned();
        }
    }
    git_hash(repo_root)
}

/// Emit `rerun-if-changed` for the files git rewrites when a new commit lands:
/// `HEAD`, the loose ref HEAD points at, and `packed-refs`.
fn watch_commit_refs(git_dir: &Path) {
    let head = git_dir.join("HEAD");
    if !head.exists() {
        return; // not a git checkout (e.g. an unpacked source tarball)
    }
    println!("cargo:rerun-if-changed={}", head.display());
    if let Ok(contents) = std::fs::read_to_string(&head)
        && let Some(reference) = contents.strip_prefix("ref:").map(str::trim)
    {
        let ref_path = git_dir.join(reference);
        if ref_path.exists() {
            println!("cargo:rerun-if-changed={}", ref_path.display());
        }
    }
    let packed = git_dir.join("packed-refs");
    if packed.exists() {
        println!("cargo:rerun-if-changed={}", packed.display());
    }
}

/// `git rev-parse --short HEAD`. `"unknown"` when git is unavailable or errors.
fn git_hash(repo_root: &Path) -> String {
    Command::new("git")
        .arg("-C")
        .arg(repo_root)
        .args(["rev-parse", "--short", "HEAD"])
        .output()
        .ok()
        .filter(|o| o.status.success())
        .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_owned())
        .filter(|s| !s.is_empty())
        .unwrap_or_else(|| "unknown".to_owned())
}
