// tcl-lsp — a language server and toolchain for Tcl
// Copyright (C) 2026 James Deucker (bitwisecook) <https://github.com/bitwisecook>
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
// SPDX-License-Identifier: AGPL-3.0-or-later

//! Stamp the short git commit hash into `GIT_HASH` so the report generated by
//! the Python `f5report` package can show which build produced it (alongside
//! the engine version). Falls back to `"unknown"` when git metadata is
//! unavailable (e.g. a source tarball / sdist build).

use std::path::{Path, PathBuf};
use std::process::Command;

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    // rust/bigip-report/py -> rust/bigip-report -> rust -> repo root.
    let repo_root = manifest
        .parent()
        .and_then(Path::parent)
        .and_then(Path::parent)
        .map(Path::to_path_buf)
        .unwrap_or_else(|| manifest.clone());

    let git_dir = repo_root.join(".git");
    for rel in ["HEAD", "index"] {
        let p = git_dir.join(rel);
        if p.exists() {
            println!("cargo:rerun-if-changed={}", p.display());
        }
    }

    println!("cargo:rustc-env=GIT_HASH={}", git_hash(&repo_root));
}

/// `git rev-parse --short HEAD`, with a `-dirty` suffix when the working tree
/// has uncommitted changes. `"unknown"` when git is unavailable or errors.
fn git_hash(repo_root: &Path) -> String {
    let short = Command::new("git")
        .arg("-C")
        .arg(repo_root)
        .args(["rev-parse", "--short", "HEAD"])
        .output()
        .ok()
        .filter(|o| o.status.success())
        .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_owned())
        .filter(|s| !s.is_empty());

    let Some(short) = short else {
        return "unknown".to_owned();
    };

    let dirty = Command::new("git")
        .arg("-C")
        .arg(repo_root)
        .args(["status", "--porcelain"])
        .output()
        .ok()
        .filter(|o| o.status.success())
        .is_some_and(|o| !o.stdout.is_empty());

    if dirty {
        format!("{short}-dirty")
    } else {
        short
    }
}
