// tcl-lsp — a language server and toolchain for Tcl
// Copyright (C) 2026 James Deucker (bitwisecook) <https://github.com/bitwisecook>
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
// SPDX-License-Identifier: AGPL-3.0-or-later

//! Unicode confusables -> ASCII table (W108), and the bidirectional
//! formatting-control table (W305).
//!
//! Derived from the Unicode confusables data
//! (Public/security/8.0.0/confusables.txt).
//! Sorted by codepoint for binary search via `confusable_to_ascii`.
//! Only single-codepoint confusables are included (W108 scans
//! char-by-char); multi-codepoint sequences are not table-keyed.
//!
//! # Bidi controls (Trojan Source)
//!
//! A homoglyph makes one *character* look like another; a bidi control makes a
//! whole *run* of characters render in an order other than the one it is
//! stored — and therefore parsed and executed — in.  Both defeat review by the
//! same mechanism (what the reviewer sees is not what runs), which is why they
//! share this module, but they warrant different codes: a homoglyph is a
//! plausible copy-paste accident (W108, warning, with an ASCII quick-fix),
//! whereas a bidi override in source has essentially no legitimate use and is
//! the published "Trojan Source" attack (W305, error, no quick-fix — the
//! character has to go, and only the author knows what the code was meant to
//! say).
//!
//! See [`BIDI_CONTROLS`] for the exact set and its deliberate limits.

/// The bidirectional **formatting controls** — embeddings, overrides, and
/// isolates — paired with their Unicode names, sorted by codepoint.
///
/// This is exactly the set the Trojan Source paper (CVE-2021-42574) and
/// `rustc`'s `text_direction_codepoint_in_literal` lint cover.  Each of these
/// characters opens or closes a region whose *visual* order differs from its
/// *logical* order, so a reviewer reading rendered source can be shown
/// statements in a different order — or shown a comment where an executable
/// statement sits.
///
/// **Deliberately excluded**, because including them would fire on ordinary
/// right-to-left prose and drown the real signal:
///
/// * `U+200E` LEFT-TO-RIGHT MARK / `U+200F` RIGHT-TO-LEFT MARK and `U+061C`
///   ARABIC LETTER MARK — *marks*, not overrides.  They nudge the resolved
///   direction of a single neutral character and are routinely written by hand
///   in legitimate bidirectional text; they cannot reorder a run.
/// * Arabic, Hebrew, Thaana, and N'Ko letters themselves.  Right-to-left
///   *content* is not an attack; only a control that lies about order is.
/// * Zero-width and other invisible characters (`U+200B`-`U+200D`, `U+2060`,
///   a mid-file `U+FEFF`).  They can hide or split an identifier, which is a
///   real hazard — but it is the *homoglyph / confusable* hazard, so they stay
///   with W108 rather than being folded into a bidi code.
pub static BIDI_CONTROLS: &[(char, &str)] = &[
    ('\u{202a}', "LEFT-TO-RIGHT EMBEDDING"),
    ('\u{202b}', "RIGHT-TO-LEFT EMBEDDING"),
    ('\u{202c}', "POP DIRECTIONAL FORMATTING"),
    ('\u{202d}', "LEFT-TO-RIGHT OVERRIDE"),
    ('\u{202e}', "RIGHT-TO-LEFT OVERRIDE"),
    ('\u{2066}', "LEFT-TO-RIGHT ISOLATE"),
    ('\u{2067}', "RIGHT-TO-LEFT ISOLATE"),
    ('\u{2068}', "FIRST STRONG ISOLATE"),
    ('\u{2069}', "POP DIRECTIONAL ISOLATE"),
];

/// The Unicode name of `ch` when it is a bidi formatting control
/// ([`BIDI_CONTROLS`]), else `None`.
///
/// ```
/// use tcl_compiler::analyser::confusables_table::bidi_control_name;
///
/// assert_eq!(bidi_control_name('\u{202e}'), Some("RIGHT-TO-LEFT OVERRIDE"));
/// // Arabic *content* is not a control.
/// assert_eq!(bidi_control_name('م'), None);
/// ```
#[must_use]
pub fn bidi_control_name(ch: char) -> Option<&'static str> {
    BIDI_CONTROLS
        .binary_search_by(|&(c, _)| c.cmp(&ch))
        .ok()
        .map(|i| BIDI_CONTROLS[i].1)
}

/// Whether `ch` is a bidi formatting control — the W305 membership test, and
/// the exclusion W108 applies so one character never produces both codes.
#[must_use]
pub fn is_bidi_control(ch: char) -> bool {
    bidi_control_name(ch).is_some()
}

/// Confusable codepoint -> its ASCII skeleton, sorted by `char`.
pub(crate) static CONFUSABLE_TO_ASCII: &[(char, &str)] = &[
    ('\u{a0}', " "),
    ('\u{b4}', "'"),
    ('\u{b8}', ","),
    ('\u{c6}', "AE"),
    ('\u{d7}', "x"),
    ('\u{e6}', "ae"),
    ('\u{131}', "i"),
    ('\u{132}', "lJ"),
    ('\u{133}', "ij"),
    ('\u{138}', "k"),
    ('\u{149}', "'n"),
    ('\u{152}', "OE"),
    ('\u{153}', "oe"),
    ('\u{17f}', "f"),
    ('\u{181}', "'B"),
    ('\u{184}', "b"),
    ('\u{187}', "C'"),
    ('\u{18a}', "'D"),
    ('\u{18d}', "g"),
    ('\u{193}', "G'"),
    ('\u{196}', "l"),
    ('\u{198}', "K'"),
    ('\u{1a0}', "O'"),
    ('\u{1a1}', "o'"),
    ('\u{1a4}', "'P"),
    ('\u{1a6}', "R"),
    ('\u{1a7}', "2"),
    ('\u{1ac}', "'T"),
    ('\u{1b3}', "'Y"),
    ('\u{1b7}', "3"),
    ('\u{1bc}', "5"),
    ('\u{1bd}', "s"),
    ('\u{1c0}', "l"),
    ('\u{1c1}', "ll"),
    ('\u{1c3}', "!"),
    ('\u{1c7}', "LJ"),
    ('\u{1c8}', "Lj"),
    ('\u{1c9}', "lj"),
    ('\u{1ca}', "NJ"),
    ('\u{1cb}', "Nj"),
    ('\u{1cc}', "nj"),
    ('\u{1f1}', "DZ"),
    ('\u{1f2}', "Dz"),
    ('\u{1f3}', "dz"),
    ('\u{21c}', "3"),
    ('\u{222}', "8"),
    ('\u{223}', "8"),
    ('\u{241}', "?"),
    ('\u{251}', "a"),
    ('\u{261}', "g"),
    ('\u{263}', "y"),
    ('\u{269}', "i"),
    ('\u{26a}', "i"),
    ('\u{26f}', "vv"),
    ('\u{28b}', "u"),
    ('\u{28d}', "rn"),
    ('\u{28f}', "y"),
    ('\u{294}', "?"),
    ('\u{2a3}', "dz"),
    ('\u{2a6}', "ts"),
    ('\u{2aa}', "ls"),
    ('\u{2ab}', "lz"),
    ('\u{2b9}', "'"),
    ('\u{2ba}', "''"),
    ('\u{2bb}', "'"),
    ('\u{2bc}', "'"),
    ('\u{2bd}', "'"),
    ('\u{2be}', "'"),
    ('\u{2c2}', "<"),
    ('\u{2c3}', ">"),
    ('\u{2c4}', "^"),
    ('\u{2c6}', "^"),
    ('\u{2c8}', "'"),
    ('\u{2ca}', "'"),
    ('\u{2cb}', "'"),
    ('\u{2d0}', ":"),
    ('\u{2d7}', "-"),
    ('\u{2db}', "i"),
    ('\u{2dc}', "~"),
    ('\u{2dd}', "''"),
    ('\u{2ee}', "''"),
    ('\u{2f4}', "'"),
    ('\u{2f6}', "''"),
    ('\u{2f8}', ":"),
    ('\u{374}', "'"),
    ('\u{37a}', "i"),
    ('\u{37e}', ";"),
    ('\u{37f}', "J"),
    ('\u{384}', "'"),
    ('\u{391}', "A"),
    ('\u{392}', "B"),
    ('\u{395}', "E"),
    ('\u{396}', "Z"),
    ('\u{397}', "H"),
    ('\u{399}', "l"),
    ('\u{39a}', "K"),
    ('\u{39c}', "M"),
    ('\u{39d}', "N"),
    ('\u{39f}', "O"),
    ('\u{3a1}', "P"),
    ('\u{3a4}', "T"),
    ('\u{3a5}', "Y"),
    ('\u{3a7}', "X"),
    ('\u{3b1}', "a"),
    ('\u{3b3}', "y"),
    ('\u{3b9}', "i"),
    ('\u{3ba}', "k"),
    ('\u{3bd}', "v"),
    ('\u{3bf}', "o"),
    ('\u{3c0}', "n"),
    ('\u{3c1}', "p"),
    ('\u{3c3}', "o"),
    ('\u{3c4}', "t"),
    ('\u{3c5}', "u"),
    ('\u{3d2}', "Y"),
    ('\u{3d6}', "n"),
    ('\u{3dc}', "F"),
    ('\u{3e8}', "2"),
    ('\u{3f0}', "k"),
    ('\u{3f1}', "p"),
    ('\u{3f2}', "c"),
    ('\u{3f3}', "j"),
    ('\u{3f9}', "C"),
    ('\u{3fa}', "M"),
    ('\u{405}', "S"),
    ('\u{406}', "l"),
    ('\u{408}', "J"),
    ('\u{410}', "A"),
    ('\u{412}', "B"),
    ('\u{415}', "E"),
    ('\u{417}', "3"),
    ('\u{41a}', "K"),
    ('\u{41c}', "M"),
    ('\u{41d}', "H"),
    ('\u{41e}', "O"),
    ('\u{420}', "P"),
    ('\u{421}', "C"),
    ('\u{422}', "T"),
    ('\u{425}', "X"),
    ('\u{42b}', "bl"),
    ('\u{42c}', "b"),
    ('\u{42e}', "lO"),
    ('\u{430}', "a"),
    ('\u{431}', "6"),
    ('\u{433}', "r"),
    ('\u{435}', "e"),
    ('\u{43a}', "k"),
    ('\u{43c}', "rn"),
    ('\u{43e}', "o"),
    ('\u{43f}', "n"),
    ('\u{440}', "p"),
    ('\u{441}', "c"),
    ('\u{442}', "t"),
    ('\u{443}', "y"),
    ('\u{445}', "x"),
    ('\u{446}', "u"),
    ('\u{455}', "s"),
    ('\u{456}', "i"),
    ('\u{458}', "j"),
    ('\u{461}', "vv"),
    ('\u{474}', "V"),
    ('\u{475}', "v"),
    ('\u{491}', "r'"),
    ('\u{4ae}', "Y"),
    ('\u{4af}', "y"),
    ('\u{4bb}', "h"),
    ('\u{4bd}', "e"),
    ('\u{4c0}', "l"),
    ('\u{4cf}', "i"),
    ('\u{4d4}', "AE"),
    ('\u{4d5}', "ae"),
    ('\u{4e0}', "3"),
    ('\u{501}', "d"),
    ('\u{50c}', "G"),
    ('\u{51b}', "q"),
    ('\u{51c}', "W"),
    ('\u{51d}', "vv"),
    ('\u{54d}', "U"),
    ('\u{54f}', "S"),
    ('\u{555}', "O"),
    ('\u{55a}', "'"),
    ('\u{55d}', "'"),
    ('\u{561}', "vv"),
    ('\u{563}', "q"),
    ('\u{566}', "q"),
    ('\u{570}', "h"),
    ('\u{578}', "n"),
    ('\u{57c}', "n"),
    ('\u{57d}', "u"),
    ('\u{581}', "g"),
    ('\u{584}', "f"),
    ('\u{585}', "o"),
    ('\u{589}', ":"),
    ('\u{5c0}', "l"),
    ('\u{5c3}', ":"),
    ('\u{5d5}', "l"),
    ('\u{5d8}', "v"),
    ('\u{5d9}', "'"),
    ('\u{5df}', "l"),
    ('\u{5e1}', "o"),
    ('\u{5f0}', "ll"),
    ('\u{5f1}', "l'"),
    ('\u{5f2}', "''"),
    ('\u{5f3}', "'"),
    ('\u{5f4}', "''"),
    ('\u{60d}', ","),
    ('\u{627}', "l"),
    ('\u{647}', "o"),
    ('\u{660}', "."),
    ('\u{661}', "l"),
    ('\u{665}', "o"),
    ('\u{667}', "V"),
    ('\u{66b}', ","),
    ('\u{66d}', "*"),
    ('\u{6be}', "o"),
    ('\u{6c1}', "o"),
    ('\u{6d4}', "-"),
    ('\u{6d5}', "o"),
    ('\u{6f0}', "."),
    ('\u{6f1}', "l"),
    ('\u{6f5}', "o"),
    ('\u{6f7}', "V"),
    ('\u{701}', "."),
    ('\u{702}', "."),
    ('\u{703}', ":"),
    ('\u{704}', ":"),
    ('\u{7c0}', "O"),
    ('\u{7ca}', "l"),
    ('\u{7f4}', "'"),
    ('\u{7f5}', "'"),
    ('\u{7fa}', "_"),
    ('\u{903}', ":"),
    ('\u{966}', "o"),
    ('\u{97d}', "?"),
    ('\u{9e6}', "O"),
    ('\u{9ea}', "8"),
    ('\u{9ed}', "9"),
    ('\u{a66}', "o"),
    ('\u{a67}', "9"),
    ('\u{a6a}', "8"),
    ('\u{a83}', ":"),
    ('\u{ae6}', "o"),
    ('\u{b03}', "8"),
    ('\u{b20}', "O"),
    ('\u{b66}', "O"),
    ('\u{b68}', "9"),
    ('\u{be6}', "o"),
    ('\u{c02}', "o"),
    ('\u{c66}', "o"),
    ('\u{c82}', "o"),
    ('\u{ce6}', "o"),
    ('\u{d02}', "o"),
    ('\u{d20}', "O"),
    ('\u{d66}', "o"),
    ('\u{d82}', "o"),
    ('\u{e50}', "o"),
    ('\u{ed0}', "o"),
    ('\u{101d}', "o"),
    ('\u{1040}', "o"),
    ('\u{10e7}', "y"),
    ('\u{10ff}', "o"),
    ('\u{13a0}', "D"),
    ('\u{13a1}', "R"),
    ('\u{13a2}', "T"),
    ('\u{13a4}', "O'"),
    ('\u{13a5}', "i"),
    ('\u{13a9}', "Y"),
    ('\u{13aa}', "A"),
    ('\u{13ab}', "J"),
    ('\u{13ac}', "E"),
    ('\u{13ae}', "?"),
    ('\u{13b3}', "W"),
    ('\u{13b7}', "M"),
    ('\u{13bb}', "H"),
    ('\u{13bd}', "Y"),
    ('\u{13c0}', "G"),
    ('\u{13c2}', "h"),
    ('\u{13c3}', "Z"),
    ('\u{13ce}', "4"),
    ('\u{13cf}', "b"),
    ('\u{13d2}', "R"),
    ('\u{13d4}', "W"),
    ('\u{13d5}', "S"),
    ('\u{13d9}', "V"),
    ('\u{13da}', "S"),
    ('\u{13de}', "L"),
    ('\u{13df}', "C"),
    ('\u{13e2}', "P"),
    ('\u{13e6}', "K"),
    ('\u{13e7}', "d"),
    ('\u{13ee}', "6"),
    ('\u{13f3}', "G"),
    ('\u{13f4}', "B"),
    ('\u{1400}', "="),
    ('\u{142f}', "V"),
    ('\u{1433}', ">"),
    ('\u{1438}', "<"),
    ('\u{144a}', "'"),
    ('\u{144c}', "U"),
    ('\u{1467}', "U'"),
    ('\u{146d}', "P"),
    ('\u{146f}', "d"),
    ('\u{1486}', "P'"),
    ('\u{1487}', "d'"),
    ('\u{148d}', "J"),
    ('\u{14aa}', "L"),
    ('\u{14bf}', "2"),
    ('\u{1541}', "x"),
    ('\u{157c}', "H"),
    ('\u{157d}', "x"),
    ('\u{1587}', "R"),
    ('\u{15af}', "b"),
    ('\u{15b4}', "F"),
    ('\u{15c5}', "A"),
    ('\u{15de}', "D"),
    ('\u{15ea}', "D"),
    ('\u{15f0}', "M"),
    ('\u{15f7}', "B"),
    ('\u{166d}', "X"),
    ('\u{166e}', "x"),
    ('\u{1680}', " "),
    ('\u{16b2}', "<"),
    ('\u{16b7}', "X"),
    ('\u{16c1}', "l"),
    ('\u{16cc}', "'"),
    ('\u{16d5}', "K"),
    ('\u{16d6}', "M"),
    ('\u{16ec}', ":"),
    ('\u{16ed}', "+"),
    ('\u{1735}', "/"),
    ('\u{1803}', ":"),
    ('\u{1809}', ":"),
    ('\u{1cd3}', "''"),
    ('\u{1d00}', "A"),
    ('\u{1d04}', "c"),
    ('\u{1d0b}', "k"),
    ('\u{1d0d}', "rn"),
    ('\u{1d0f}', "o"),
    ('\u{1d11}', "o"),
    ('\u{1d1b}', "t"),
    ('\u{1d1c}', "u"),
    ('\u{1d20}', "v"),
    ('\u{1d21}', "vv"),
    ('\u{1d22}', "z"),
    ('\u{1d26}', "r"),
    ('\u{1d28}', "n"),
    ('\u{1d6b}', "ue"),
    ('\u{1d83}', "g"),
    ('\u{1d8c}', "y"),
    ('\u{1e9d}', "f"),
    ('\u{1eff}', "y"),
    ('\u{1fbd}', "'"),
    ('\u{1fbe}', "i"),
    ('\u{1fbf}', "'"),
    ('\u{1fc0}', "~"),
    ('\u{1fef}', "'"),
    ('\u{1ffd}', "'"),
    ('\u{1ffe}', "'"),
    ('\u{2000}', " "),
    ('\u{2001}', " "),
    ('\u{2002}', " "),
    ('\u{2003}', " "),
    ('\u{2004}', " "),
    ('\u{2005}', " "),
    ('\u{2006}', " "),
    ('\u{2007}', " "),
    ('\u{2008}', " "),
    ('\u{2009}', " "),
    ('\u{200a}', " "),
    ('\u{2010}', "-"),
    ('\u{2011}', "-"),
    ('\u{2012}', "-"),
    ('\u{2013}', "-"),
    ('\u{2016}', "ll"),
    ('\u{2018}', "'"),
    ('\u{2019}', "'"),
    ('\u{201a}', ","),
    ('\u{201b}', "'"),
    ('\u{201c}', "''"),
    ('\u{201d}', "''"),
    ('\u{201f}', "''"),
    ('\u{2024}', "."),
    ('\u{2025}', ".."),
    ('\u{2026}', "..."),
    ('\u{2028}', " "),
    ('\u{2029}', " "),
    ('\u{202f}', " "),
    ('\u{2032}', "'"),
    ('\u{2033}', "''"),
    ('\u{2034}', "'''"),
    ('\u{2035}', "'"),
    ('\u{2036}', "''"),
    ('\u{2037}', "'''"),
    ('\u{2039}', "<"),
    ('\u{203a}', ">"),
    ('\u{203c}', "!!"),
    ('\u{2041}', "/"),
    ('\u{2043}', "-"),
    ('\u{2044}', "/"),
    ('\u{2047}', "??"),
    ('\u{2048}', "?!"),
    ('\u{2049}', "!?"),
    ('\u{204e}', "*"),
    ('\u{2053}', "~"),
    ('\u{2057}', "''''"),
    ('\u{205a}', ":"),
    ('\u{205f}', " "),
    ('\u{20a8}', "Rs"),
    ('\u{20b6}', "lt"),
    ('\u{2100}', "a/c"),
    ('\u{2101}', "a/s"),
    ('\u{2102}', "C"),
    ('\u{2105}', "c/o"),
    ('\u{2106}', "c/u"),
    ('\u{210a}', "g"),
    ('\u{210b}', "H"),
    ('\u{210c}', "H"),
    ('\u{210d}', "H"),
    ('\u{210e}', "h"),
    ('\u{2110}', "l"),
    ('\u{2111}', "l"),
    ('\u{2112}', "L"),
    ('\u{2113}', "l"),
    ('\u{2115}', "N"),
    ('\u{2116}', "No"),
    ('\u{2119}', "P"),
    ('\u{211a}', "Q"),
    ('\u{211b}', "R"),
    ('\u{211c}', "R"),
    ('\u{211d}', "R"),
    ('\u{2121}', "TEL"),
    ('\u{2124}', "Z"),
    ('\u{2128}', "Z"),
    ('\u{212a}', "K"),
    ('\u{212c}', "B"),
    ('\u{212d}', "C"),
    ('\u{212e}', "e"),
    ('\u{212f}', "e"),
    ('\u{2130}', "E"),
    ('\u{2131}', "F"),
    ('\u{2133}', "M"),
    ('\u{2134}', "o"),
    ('\u{2139}', "i"),
    ('\u{213b}', "FAX"),
    ('\u{213c}', "n"),
    ('\u{213d}', "y"),
    ('\u{2145}', "D"),
    ('\u{2146}', "d"),
    ('\u{2147}', "e"),
    ('\u{2148}', "i"),
    ('\u{2149}', "j"),
    ('\u{2160}', "l"),
    ('\u{2161}', "ll"),
    ('\u{2162}', "lll"),
    ('\u{2163}', "lV"),
    ('\u{2164}', "V"),
    ('\u{2165}', "Vl"),
    ('\u{2166}', "Vll"),
    ('\u{2167}', "Vlll"),
    ('\u{2168}', "lX"),
    ('\u{2169}', "X"),
    ('\u{216a}', "Xl"),
    ('\u{216b}', "Xll"),
    ('\u{216c}', "L"),
    ('\u{216d}', "C"),
    ('\u{216e}', "D"),
    ('\u{216f}', "M"),
    ('\u{2170}', "i"),
    ('\u{2171}', "ii"),
    ('\u{2172}', "iii"),
    ('\u{2173}', "iv"),
    ('\u{2174}', "v"),
    ('\u{2175}', "vi"),
    ('\u{2176}', "vii"),
    ('\u{2177}', "viii"),
    ('\u{2178}', "ix"),
    ('\u{2179}', "x"),
    ('\u{217a}', "xi"),
    ('\u{217b}', "xii"),
    ('\u{217c}', "l"),
    ('\u{217d}', "c"),
    ('\u{217e}', "d"),
    ('\u{217f}', "rn"),
    ('\u{2212}', "-"),
    ('\u{2215}', "/"),
    ('\u{2216}', "\\"),
    ('\u{2217}', "*"),
    ('\u{221e}', "oo"),
    ('\u{2223}', "l"),
    ('\u{2225}', "ll"),
    ('\u{2228}', "v"),
    ('\u{222a}', "U"),
    ('\u{2236}', ":"),
    ('\u{223c}', "~"),
    ('\u{226a}', "<<"),
    ('\u{226b}', ">>"),
    ('\u{22a4}', "T"),
    ('\u{22c1}', "v"),
    ('\u{22c3}', "U"),
    ('\u{22d8}', "<<<"),
    ('\u{22d9}', ">>>"),
    ('\u{22ff}', "E"),
    ('\u{2373}', "i"),
    ('\u{2374}', "p"),
    ('\u{237a}', "a"),
    ('\u{244a}', "\\\\"),
    ('\u{2474}', "(l)"),
    ('\u{2475}', "(2)"),
    ('\u{2476}', "(3)"),
    ('\u{2477}', "(4)"),
    ('\u{2478}', "(5)"),
    ('\u{2479}', "(6)"),
    ('\u{247a}', "(7)"),
    ('\u{247b}', "(8)"),
    ('\u{247c}', "(9)"),
    ('\u{247d}', "(lO)"),
    ('\u{247e}', "(ll)"),
    ('\u{247f}', "(l2)"),
    ('\u{2480}', "(l3)"),
    ('\u{2481}', "(l4)"),
    ('\u{2482}', "(l5)"),
    ('\u{2483}', "(l6)"),
    ('\u{2484}', "(l7)"),
    ('\u{2485}', "(l8)"),
    ('\u{2486}', "(l9)"),
    ('\u{2487}', "(2O)"),
    ('\u{2488}', "l."),
    ('\u{2489}', "2."),
    ('\u{248a}', "3."),
    ('\u{248b}', "4."),
    ('\u{248c}', "5."),
    ('\u{248d}', "6."),
    ('\u{248e}', "7."),
    ('\u{248f}', "8."),
    ('\u{2490}', "9."),
    ('\u{2491}', "lO."),
    ('\u{2492}', "ll."),
    ('\u{2493}', "l2."),
    ('\u{2494}', "l3."),
    ('\u{2495}', "l4."),
    ('\u{2496}', "l5."),
    ('\u{2497}', "l6."),
    ('\u{2498}', "l7."),
    ('\u{2499}', "l8."),
    ('\u{249a}', "l9."),
    ('\u{249b}', "2O."),
    ('\u{249c}', "(a)"),
    ('\u{249d}', "(b)"),
    ('\u{249e}', "(c)"),
    ('\u{249f}', "(d)"),
    ('\u{24a0}', "(e)"),
    ('\u{24a1}', "(f)"),
    ('\u{24a2}', "(g)"),
    ('\u{24a3}', "(h)"),
    ('\u{24a4}', "(i)"),
    ('\u{24a5}', "(j)"),
    ('\u{24a6}', "(k)"),
    ('\u{24a7}', "(l)"),
    ('\u{24a8}', "(rn)"),
    ('\u{24a9}', "(n)"),
    ('\u{24aa}', "(o)"),
    ('\u{24ab}', "(p)"),
    ('\u{24ac}', "(q)"),
    ('\u{24ad}', "(r)"),
    ('\u{24ae}', "(s)"),
    ('\u{24af}', "(t)"),
    ('\u{24b0}', "(u)"),
    ('\u{24b1}', "(v)"),
    ('\u{24b2}', "(vv)"),
    ('\u{24b3}', "(x)"),
    ('\u{24b4}', "(y)"),
    ('\u{24b5}', "(z)"),
    ('\u{2571}', "/"),
    ('\u{2573}', "X"),
    ('\u{2768}', "("),
    ('\u{2769}', ")"),
    ('\u{276e}', "<"),
    ('\u{276f}', ">"),
    ('\u{2772}', "("),
    ('\u{2773}', ")"),
    ('\u{2774}', "{"),
    ('\u{2775}', "}"),
    ('\u{2795}', "+"),
    ('\u{2796}', "-"),
    ('\u{27cb}', "/"),
    ('\u{27cd}', "\\"),
    ('\u{27d9}', "T"),
    ('\u{292b}', "x"),
    ('\u{292c}', "x"),
    ('\u{29f5}', "\\"),
    ('\u{29f8}', "/"),
    ('\u{29f9}', "\\"),
    ('\u{2a20}', ">>"),
    ('\u{2a2f}', "x"),
    ('\u{2a74}', "::="),
    ('\u{2a75}', "=="),
    ('\u{2a76}', "==="),
    ('\u{2aa5}', "><"),
    ('\u{2afb}', "///"),
    ('\u{2afd}', "//"),
    ('\u{2c85}', "r"),
    ('\u{2c8e}', "H"),
    ('\u{2c92}', "l"),
    ('\u{2c94}', "K"),
    ('\u{2c95}', "k"),
    ('\u{2c98}', "M"),
    ('\u{2c9a}', "N"),
    ('\u{2c9e}', "O"),
    ('\u{2c9f}', "o"),
    ('\u{2ca2}', "P"),
    ('\u{2ca3}', "p"),
    ('\u{2ca4}', "C"),
    ('\u{2ca5}', "c"),
    ('\u{2ca6}', "T"),
    ('\u{2ca8}', "Y"),
    ('\u{2cac}', "X"),
    ('\u{2cba}', "-"),
    ('\u{2cc6}', "/"),
    ('\u{2cca}', "9"),
    ('\u{2ccc}', "3"),
    ('\u{2cd0}', "L"),
    ('\u{2cd2}', "6"),
    ('\u{2cf9}', "\\\\"),
    ('\u{2d38}', "V"),
    ('\u{2d39}', "E"),
    ('\u{2d4f}', "l"),
    ('\u{2d51}', "!"),
    ('\u{2d54}', "O"),
    ('\u{2d55}', "Q"),
    ('\u{2d5d}', "X"),
    ('\u{2e28}', "(("),
    ('\u{2e29}', "))"),
    ('\u{2e40}', "="),
    ('\u{2f02}', "\\"),
    ('\u{2f03}', "/"),
    ('\u{3003}', "''"),
    ('\u{3007}', "O"),
    ('\u{3014}', "("),
    ('\u{3015}', ")"),
    ('\u{3033}', "/"),
    ('\u{30a0}', "="),
    ('\u{31d3}', "/"),
    ('\u{31d4}', "\\"),
    ('\u{4e36}', "\\"),
    ('\u{4e3f}', "/"),
    ('\u{a4d0}', "B"),
    ('\u{a4d1}', "P"),
    ('\u{a4d2}', "d"),
    ('\u{a4d3}', "D"),
    ('\u{a4d4}', "T"),
    ('\u{a4d6}', "G"),
    ('\u{a4d7}', "K"),
    ('\u{a4d9}', "J"),
    ('\u{a4da}', "C"),
    ('\u{a4dc}', "Z"),
    ('\u{a4dd}', "F"),
    ('\u{a4df}', "M"),
    ('\u{a4e0}', "N"),
    ('\u{a4e1}', "L"),
    ('\u{a4e2}', "S"),
    ('\u{a4e3}', "R"),
    ('\u{a4e6}', "V"),
    ('\u{a4e7}', "H"),
    ('\u{a4ea}', "W"),
    ('\u{a4eb}', "X"),
    ('\u{a4ec}', "Y"),
    ('\u{a4ee}', "A"),
    ('\u{a4f0}', "E"),
    ('\u{a4f2}', "l"),
    ('\u{a4f3}', "O"),
    ('\u{a4f4}', "U"),
    ('\u{a4f8}', "."),
    ('\u{a4f9}', ","),
    ('\u{a4fa}', ".."),
    ('\u{a4fb}', ".,"),
    ('\u{a4fd}', ":"),
    ('\u{a4fe}', "-."),
    ('\u{a4ff}', "="),
    ('\u{a60e}', "."),
    ('\u{a644}', "2"),
    ('\u{a647}', "i"),
    ('\u{a698}', "OO"),
    ('\u{a699}', "oo"),
    ('\u{a728}', "T3"),
    ('\u{a731}', "s"),
    ('\u{a732}', "AA"),
    ('\u{a733}', "aa"),
    ('\u{a734}', "AO"),
    ('\u{a735}', "ao"),
    ('\u{a736}', "AU"),
    ('\u{a737}', "au"),
    ('\u{a738}', "AV"),
    ('\u{a739}', "av"),
    ('\u{a73a}', "AV"),
    ('\u{a73b}', "av"),
    ('\u{a73c}', "AY"),
    ('\u{a73d}', "ay"),
    ('\u{a74e}', "OO"),
    ('\u{a74f}', "oo"),
    ('\u{a75a}', "2"),
    ('\u{a761}', "vy"),
    ('\u{a76a}', "3"),
    ('\u{a76e}', "9"),
    ('\u{a777}', "tf"),
    ('\u{a778}', "&"),
    ('\u{a789}', ":"),
    ('\u{a78c}', "'"),
    ('\u{a798}', "F"),
    ('\u{a799}', "f"),
    ('\u{a79f}', "u"),
    ('\u{a7ab}', "3"),
    ('\u{a7b2}', "J"),
    ('\u{a7b3}', "X"),
    ('\u{a7b4}', "B"),
    ('\u{ab32}', "e"),
    ('\u{ab35}', "f"),
    ('\u{ab3d}', "o"),
    ('\u{ab47}', "r"),
    ('\u{ab48}', "r"),
    ('\u{ab4e}', "u"),
    ('\u{ab51}', "rn"),
    ('\u{ab52}', "u"),
    ('\u{ab5a}', "y"),
    ('\u{fb00}', "ff"),
    ('\u{fb01}', "fi"),
    ('\u{fb02}', "fl"),
    ('\u{fb03}', "ffi"),
    ('\u{fb04}', "ffl"),
    ('\u{fb06}', "st"),
    ('\u{fba6}', "o"),
    ('\u{fba7}', "o"),
    ('\u{fba8}', "o"),
    ('\u{fba9}', "o"),
    ('\u{fbaa}', "o"),
    ('\u{fbab}', "o"),
    ('\u{fbac}', "o"),
    ('\u{fbad}', "o"),
    ('\u{fd3e}', "("),
    ('\u{fd3f}', ")"),
    ('\u{fe30}', ":"),
    ('\u{fe4d}', "_"),
    ('\u{fe4e}', "_"),
    ('\u{fe4f}', "_"),
    ('\u{fe58}', "-"),
    ('\u{fe68}', "\\"),
    ('\u{fe8d}', "l"),
    ('\u{fe8e}', "l"),
    ('\u{fee9}', "o"),
    ('\u{feea}', "o"),
    ('\u{feeb}', "o"),
    ('\u{feec}', "o"),
    ('\u{ff01}', "!"),
    ('\u{ff02}', "''"),
    ('\u{ff07}', "'"),
    ('\u{ff1a}', ":"),
    ('\u{ff21}', "A"),
    ('\u{ff22}', "B"),
    ('\u{ff23}', "C"),
    ('\u{ff25}', "E"),
    ('\u{ff28}', "H"),
    ('\u{ff29}', "l"),
    ('\u{ff2a}', "J"),
    ('\u{ff2b}', "K"),
    ('\u{ff2d}', "M"),
    ('\u{ff2e}', "N"),
    ('\u{ff2f}', "O"),
    ('\u{ff30}', "P"),
    ('\u{ff33}', "S"),
    ('\u{ff34}', "T"),
    ('\u{ff38}', "X"),
    ('\u{ff39}', "Y"),
    ('\u{ff3a}', "Z"),
    ('\u{ff3b}', "("),
    ('\u{ff3c}', "\\"),
    ('\u{ff3d}', ")"),
    ('\u{ff40}', "'"),
    ('\u{ff41}', "a"),
    ('\u{ff43}', "c"),
    ('\u{ff45}', "e"),
    ('\u{ff47}', "g"),
    ('\u{ff48}', "h"),
    ('\u{ff49}', "i"),
    ('\u{ff4a}', "j"),
    ('\u{ff4c}', "l"),
    ('\u{ff4f}', "o"),
    ('\u{ff50}', "p"),
    ('\u{ff53}', "s"),
    ('\u{ff56}', "v"),
    ('\u{ff58}', "x"),
    ('\u{ff59}', "y"),
    ('\u{ffe8}', "l"),
];

/// Look up the ASCII skeleton for a confusable `ch`, if any.
#[must_use]
pub(crate) fn confusable_to_ascii(ch: char) -> Option<&'static str> {
    CONFUSABLE_TO_ASCII
        .binary_search_by(|&(c, _)| c.cmp(&ch))
        .ok()
        .map(|i| CONFUSABLE_TO_ASCII[i].1)
}

/// Known copy-paste artifacts (smart quotes, NBSP, dashes, …) ->
/// their ASCII replacement, sorted by `char`.
pub(crate) static AUTO_FIX_MAP: &[(char, &str)] = &[
    ('\u{60}', "'"),
    ('\u{a0}', " "),
    ('\u{ab}', "\""),
    ('\u{b4}', "'"),
    ('\u{b7}', "."),
    ('\u{bb}', "\""),
    ('\u{d7}', "*"),
    ('\u{f7}', "/"),
    ('\u{2bc}', "'"),
    ('\u{2002}', " "),
    ('\u{2003}', " "),
    ('\u{2009}', " "),
    ('\u{200a}', " "),
    ('\u{200b}', ""),
    ('\u{200c}', ""),
    ('\u{200d}', ""),
    ('\u{2010}', "-"),
    ('\u{2011}', "-"),
    ('\u{2012}', "-"),
    ('\u{2013}', "-"),
    ('\u{2014}', "--"),
    ('\u{2015}', "--"),
    ('\u{2016}', "||"),
    ('\u{2018}', "'"),
    ('\u{2019}', "'"),
    ('\u{201a}', "'"),
    ('\u{201c}', "\""),
    ('\u{201d}', "\""),
    ('\u{201e}', "\""),
    ('\u{2022}', "*"),
    ('\u{2026}', "..."),
    ('\u{2027}', "-"),
    ('\u{202f}', " "),
    ('\u{2032}', "'"),
    ('\u{2033}', "\""),
    ('\u{2039}', "'"),
    ('\u{203a}', "'"),
    ('\u{2044}', "/"),
    ('\u{205f}', " "),
    ('\u{2190}', "<-"),
    ('\u{2192}', "->"),
    ('\u{21d0}', "<="),
    ('\u{21d2}', "=>"),
    ('\u{2212}', "-"),
    ('\u{2260}', "!="),
    ('\u{2264}', "<="),
    ('\u{2265}', ">="),
    ('\u{2705}', "[x]"),
    ('\u{2714}', "[x]"),
    ('\u{2716}', "[x]"),
    ('\u{274c}', "[x]"),
    ('\u{2764}', "<3"),
    ('\u{fe63}', "-"),
    ('\u{feff}', ""),
    ('\u{ff01}', "!"),
    ('\u{ff03}', "#"),
    ('\u{ff04}', "$"),
    ('\u{ff05}', "%"),
    ('\u{ff06}', "&"),
    ('\u{ff08}', "("),
    ('\u{ff09}', ")"),
    ('\u{ff0a}', "*"),
    ('\u{ff0b}', "+"),
    ('\u{ff0c}', ","),
    ('\u{ff0d}', "-"),
    ('\u{ff0e}', "."),
    ('\u{ff0f}', "/"),
    ('\u{ff1a}', ":"),
    ('\u{ff1b}', ";"),
    ('\u{ff1c}', "<"),
    ('\u{ff1d}', "="),
    ('\u{ff1e}', ">"),
    ('\u{ff1f}', "?"),
    ('\u{ff20}', "@"),
    ('\u{ff3b}', "["),
    ('\u{ff3c}', "\\"),
    ('\u{ff3d}', "]"),
    ('\u{ff5b}', "{"),
    ('\u{ff5c}', "|"),
    ('\u{ff5d}', "}"),
    ('\u{ff5e}', "~"),
    ('\u{1f389}', "!"),
    ('\u{1f44d}', "+1"),
    ('\u{1f44e}', "-1"),
    ('\u{1f4af}', "100"),
    ('\u{1f525}', "*"),
    ('\u{1f600}', ":D"),
    ('\u{1f601}', ":D"),
    ('\u{1f603}', ":D"),
    ('\u{1f604}', ":D"),
    ('\u{1f609}', ";)"),
    ('\u{1f60a}', ":)"),
    ('\u{1f60d}', "<3"),
    ('\u{1f60e}', "B)"),
    ('\u{1f610}', ":|"),
    ('\u{1f618}', ":*"),
    ('\u{1f61b}', ":P"),
    ('\u{1f61c}', ";P"),
    ('\u{1f61e}', ":("),
    ('\u{1f622}', ":'("),
    ('\u{1f62e}', ":O"),
    ('\u{1f631}', ":O"),
    ('\u{1f641}', ":("),
    ('\u{1f642}', ":)"),
    ('\u{1f680}', "=>"),
    ('\u{1f911}', ":$"),
    ('\u{1f913}', "8)"),
    ('\u{1f914}', ":?"),
];

/// The ASCII replacement for a known copy-paste artifact `ch`.
#[must_use]
pub(crate) fn auto_fix_for(ch: char) -> Option<&'static str> {
    AUTO_FIX_MAP
        .binary_search_by(|&(c, _)| c.cmp(&ch))
        .ok()
        .map(|i| AUTO_FIX_MAP[i].1)
}
