from __future__ import annotations

from . import (
    analytics_afm_sweeper_scheduled_report,  # noqa: F401
    analytics_application_security_anomalies_scheduled_report,  # noqa: F401
    analytics_application_security_network_scheduled_report,  # noqa: F401
    analytics_application_security_scheduled_report,  # noqa: F401
    analytics_asm_bypass_scheduled_report,  # noqa: F401
    analytics_asm_cpu_scheduled_report,  # noqa: F401
    analytics_asm_memory_scheduled_report,  # noqa: F401
    analytics_asm_violation_scheduled_report,  # noqa: F401
    analytics_cpu_scheduled_report,  # noqa: F401
    analytics_device_traffic_scheduled_report,  # noqa: F401
    analytics_disk_info_scheduled_report,  # noqa: F401
    analytics_dns_protocol_scheduled_report,  # noqa: F401
    analytics_dns_scheduled_report,  # noqa: F401
    analytics_dos_l3_scheduled_report,  # noqa: F401
    analytics_fw_nat_scheduled_report,  # noqa: F401
    analytics_global_settings,  # noqa: F401
    analytics_http_scheduled_report,  # noqa: F401
    analytics_ip_intelligence_scheduled_report,  # noqa: F401
    analytics_ip_layer_scheduled_report,  # noqa: F401
    analytics_lsn_pool_scheduled_report,  # noqa: F401
    analytics_memory_scheduled_report,  # noqa: F401
    analytics_network_scheduled_report,  # noqa: F401
    analytics_pem_scheduled_report,  # noqa: F401
    analytics_pool_traffic_scheduled_report,  # noqa: F401
    analytics_proc_cpu_scheduled_report,  # noqa: F401
    analytics_protocol_security_http_scheduled_report,  # noqa: F401
    analytics_protocol_security_scheduled_report,  # noqa: F401
    analytics_sip_dos_scheduled_report,  # noqa: F401
    analytics_sip_scheduled_report,  # noqa: F401
    analytics_ssl_orchestrator_scheduled_report,  # noqa: F401
    analytics_ssl_orchestrator_service_virtual_scheduled_report,  # noqa: F401
    analytics_swg_blocked_scheduled_report,  # noqa: F401
    analytics_swg_scheduled_report,  # noqa: F401
    analytics_tcp_analytics_scheduled_report,  # noqa: F401
    analytics_tcp_scheduled_report,  # noqa: F401
    analytics_traffic_classification_scheduled_report,  # noqa: F401
    analytics_udp_scheduled_report,  # noqa: F401
    analytics_uri_type,  # noqa: F401
    analytics_vcmp_scheduled_report,  # noqa: F401
    analytics_virtual_scheduled_report,  # noqa: F401
    api_protection_profile_apiprotection,  # noqa: F401
    api_protection_response,  # noqa: F401
    api_protection_server,  # noqa: F401
    apm_aaa_active_directory,  # noqa: F401
    apm_aaa_active_directory_trusted_domains,  # noqa: F401
    apm_aaa_crldp,  # noqa: F401
    apm_aaa_endpoint_management_system,  # noqa: F401
    apm_aaa_f5_mfa_configuration,  # noqa: F401
    apm_aaa_f5_service_connector,  # noqa: F401
    apm_aaa_http,  # noqa: F401
    apm_aaa_http_connector_request,  # noqa: F401
    apm_aaa_kerberos,  # noqa: F401
    apm_aaa_kerberos_keytab_file,  # noqa: F401
    apm_aaa_ldap,  # noqa: F401
    apm_aaa_oam,  # noqa: F401
    apm_aaa_oauth_provider,  # noqa: F401
    apm_aaa_oauth_request,  # noqa: F401
    apm_aaa_oauth_server,  # noqa: F401
    apm_aaa_ocsp,  # noqa: F401
    apm_aaa_okta_connector,  # noqa: F401
    apm_aaa_radius,  # noqa: F401
    apm_aaa_saml,  # noqa: F401
    apm_aaa_saml_idp_automation,  # noqa: F401
    apm_aaa_saml_idp_connector,  # noqa: F401
    apm_aaa_securid,  # noqa: F401
    apm_aaa_tacacsplus,  # noqa: F401
    apm_acl,  # noqa: F401
    apm_apm_avr_config,  # noqa: F401
    apm_client_image,  # noqa: F401
    apm_configuration_captcha,  # noqa: F401
    apm_epsec_epsec_package,  # noqa: F401
    apm_log_setting,  # noqa: F401
    apm_ntlm_machine_account,  # noqa: F401
    apm_ntlm_ntlm_auth,  # noqa: F401
    apm_oauth_db_instance,  # noqa: F401
    apm_oauth_jwk_config,  # noqa: F401
    apm_oauth_jwt_config,  # noqa: F401
    apm_oauth_jwt_provider_list,  # noqa: F401
    apm_oauth_oauth_claim,  # noqa: F401
    apm_oauth_oauth_client_app,  # noqa: F401
    apm_oauth_oauth_resource_server,  # noqa: F401
    apm_oauth_oauth_scope,  # noqa: F401
    apm_policy_agent_aaa_active_directory,  # noqa: F401
    apm_policy_agent_aaa_client_cert,  # noqa: F401
    apm_policy_agent_aaa_crldp,  # noqa: F401
    apm_policy_agent_aaa_http,  # noqa: F401
    apm_policy_agent_aaa_ldap,  # noqa: F401
    apm_policy_agent_aaa_oauth,  # noqa: F401
    apm_policy_agent_aaa_radius,  # noqa: F401
    apm_policy_agent_aaa_saml,  # noqa: F401
    apm_policy_agent_aaa_securid,  # noqa: F401
    apm_policy_agent_acct_radius,  # noqa: F401
    apm_policy_agent_acct_tacacsplus,  # noqa: F401
    apm_policy_agent_api_authentication,  # noqa: F401
    apm_policy_agent_api_server_selection,  # noqa: F401
    apm_policy_agent_decision_box,  # noqa: F401
    apm_policy_agent_dynamic_acl,  # noqa: F401
    apm_policy_agent_ending_allow,  # noqa: F401
    apm_policy_agent_ending_deny,  # noqa: F401
    apm_policy_agent_ending_redirect,  # noqa: F401
    apm_policy_agent_endpoint_check_machine_cert,  # noqa: F401
    apm_policy_agent_endpoint_check_software,  # noqa: F401
    apm_policy_agent_endpoint_linux_check_file,  # noqa: F401
    apm_policy_agent_endpoint_linux_check_process,  # noqa: F401
    apm_policy_agent_endpoint_mac_check_file,  # noqa: F401
    apm_policy_agent_endpoint_mac_check_process,  # noqa: F401
    apm_policy_agent_endpoint_machine_info,  # noqa: F401
    apm_policy_agent_endpoint_windows_browser_cache_cleaner,  # noqa: F401
    apm_policy_agent_endpoint_windows_check_file,  # noqa: F401
    apm_policy_agent_endpoint_windows_check_process,  # noqa: F401
    apm_policy_agent_endpoint_windows_check_registry,  # noqa: F401
    apm_policy_agent_endpoint_windows_group_policy,  # noqa: F401
    apm_policy_agent_endpoint_windows_info_os,  # noqa: F401
    apm_policy_agent_endpoint_windows_protected_workspace,  # noqa: F401
    apm_policy_agent_external_logon_page,  # noqa: F401
    apm_policy_agent_http_header_modify,  # noqa: F401
    apm_policy_agent_ip_geolocation_lookup,  # noqa: F401
    apm_policy_agent_ip_reputation_lookup,  # noqa: F401
    apm_policy_agent_irule_event,  # noqa: F401
    apm_policy_agent_kerberos,  # noqa: F401
    apm_policy_agent_l7_protocol_lookup,  # noqa: F401
    apm_policy_agent_logging,  # noqa: F401
    apm_policy_agent_logon_page,  # noqa: F401
    apm_policy_agent_message_box,  # noqa: F401
    apm_policy_agent_oam,  # noqa: F401
    apm_policy_agent_oauth_authz,  # noqa: F401
    apm_policy_agent_request_classification,  # noqa: F401
    apm_policy_agent_resource_assign,  # noqa: F401
    apm_policy_agent_response_selection,  # noqa: F401
    apm_policy_agent_route_domain_selection,  # noqa: F401
    apm_policy_agent_server_cert_response_control,  # noqa: F401
    apm_policy_agent_server_cert_status,  # noqa: F401
    apm_policy_agent_session_check,  # noqa: F401
    apm_policy_agent_ssl_check,  # noqa: F401
    apm_policy_agent_tacacsplus,  # noqa: F401
    apm_policy_agent_variable_assign,  # noqa: F401
    apm_profile_access,  # noqa: F401
    apm_profile_connectivity,  # noqa: F401
    apm_profile_exchange,  # noqa: F401
    apm_profile_oauth,  # noqa: F401
    apm_profile_vdi,  # noqa: F401
    apm_report_custom_report_field,  # noqa: F401
    apm_resource_address_space,  # noqa: F401
    apm_resource_app_tunnel,  # noqa: F401
    apm_resource_client_rate_class,  # noqa: F401
    apm_resource_client_traffic_classifier,  # noqa: F401
    apm_resource_ipv6_leasepool,  # noqa: F401
    apm_resource_leasepool,  # noqa: F401
    apm_resource_network_access,  # noqa: F401
    apm_resource_portal_access,  # noqa: F401
    apm_resource_remote_desktop_citrix,  # noqa: F401
    apm_resource_remote_desktop_citrix_client_bundle,  # noqa: F401
    apm_resource_remote_desktop_citrix_client_package_file,  # noqa: F401
    apm_resource_remote_desktop_quest,  # noqa: F401
    apm_resource_remote_desktop_rdp,  # noqa: F401
    apm_resource_remote_desktop_vmware_view,  # noqa: F401
    apm_resource_sandbox,  # noqa: F401
    apm_resource_webtop,  # noqa: F401
    apm_resource_webtop_link,  # noqa: F401
    apm_saml_artifact_resolution_service,  # noqa: F401
    apm_saml_attribute_consuming_service,  # noqa: F401
    apm_saml_auth_context_class_list,  # noqa: F401
    apm_session,  # noqa: F401
    apm_sso_basic,  # noqa: F401
    apm_sso_form_based,  # noqa: F401
    apm_sso_form_basedv2,  # noqa: F401
    apm_sso_kerberos,  # noqa: F401
    apm_sso_ntlmv1,  # noqa: F401
    apm_sso_ntlmv2,  # noqa: F401
    apm_sso_oauth_bearer,  # noqa: F401
    apm_sso_saml,  # noqa: F401
    apm_sso_saml_resource,  # noqa: F401
    apm_sso_saml_sp_automation,  # noqa: F401
    apm_sso_saml_sp_connector,  # noqa: F401
    apm_swg_scheme,  # noqa: F401
    apm_url_filter,  # noqa: F401
    asm_httpclass_asm,  # noqa: F401
    asm_policy,  # noqa: F401
    auth_apm_auth,  # noqa: F401
    auth_cert_ldap,  # noqa: F401
    auth_ldap,  # noqa: F401
    auth_partition,  # noqa: F401
    auth_password,  # noqa: F401
    auth_password_policy,  # noqa: F401
    auth_radius,  # noqa: F401
    auth_radius_server,  # noqa: F401
    auth_remote_role,  # noqa: F401
    auth_remote_user,  # noqa: F401
    auth_source,  # noqa: F401
    auth_tacacs,  # noqa: F401
    auth_user,  # noqa: F401
    cli_admin_partitions,  # noqa: F401
    cli_alias_private,  # noqa: F401
    cli_alias_shared,  # noqa: F401
    cli_global_settings,  # noqa: F401
    cli_preference,  # noqa: F401
    cli_script,  # noqa: F401
    cli_transaction,  # noqa: F401
    cli_version,  # noqa: F401
    cm_device,  # noqa: F401
    cm_device_group,  # noqa: F401
    cm_ha_group,  # noqa: F401
    cm_key,  # noqa: F401
    cm_traffic_group,  # noqa: F401
    cm_trust_domain,  # noqa: F401
    gtm_add,  # noqa: F401
    gtm_datacenter,  # noqa: F401
    gtm_distributed_app,  # noqa: F401
    gtm_global_settings_general,  # noqa: F401
    gtm_global_settings_load_balancing,  # noqa: F401
    gtm_global_settings_metrics,  # noqa: F401
    gtm_global_settings_metrics_exclusions,  # noqa: F401
    gtm_link,  # noqa: F401
    gtm_listener,  # noqa: F401
    gtm_listener_doh_proxy,  # noqa: F401
    gtm_listener_doh_server,  # noqa: F401
    gtm_monitor_bigip,  # noqa: F401
    gtm_monitor_bigip_link,  # noqa: F401
    gtm_monitor_external,  # noqa: F401
    gtm_monitor_firepass,  # noqa: F401
    gtm_monitor_ftp,  # noqa: F401
    gtm_monitor_gateway_icmp,  # noqa: F401
    gtm_monitor_gtp,  # noqa: F401
    gtm_monitor_http,  # noqa: F401
    gtm_monitor_https,  # noqa: F401
    gtm_monitor_imap,  # noqa: F401
    gtm_monitor_ldap,  # noqa: F401
    gtm_monitor_mssql,  # noqa: F401
    gtm_monitor_mysql,  # noqa: F401
    gtm_monitor_nntp,  # noqa: F401
    gtm_monitor_oracle,  # noqa: F401
    gtm_monitor_pop3,  # noqa: F401
    gtm_monitor_postgresql,  # noqa: F401
    gtm_monitor_radius,  # noqa: F401
    gtm_monitor_radius_accounting,  # noqa: F401
    gtm_monitor_real_server,  # noqa: F401
    gtm_monitor_scripted,  # noqa: F401
    gtm_monitor_sip,  # noqa: F401
    gtm_monitor_smtp,  # noqa: F401
    gtm_monitor_snmp,  # noqa: F401
    gtm_monitor_snmp_link,  # noqa: F401
    gtm_monitor_soap,  # noqa: F401
    gtm_monitor_tcp,  # noqa: F401
    gtm_monitor_tcp_half_open,  # noqa: F401
    gtm_monitor_udp,  # noqa: F401
    gtm_monitor_wap,  # noqa: F401
    gtm_monitor_wmi,  # noqa: F401
    gtm_pool_a,  # noqa: F401
    gtm_pool_aaaa,  # noqa: F401
    gtm_pool_cname,  # noqa: F401
    gtm_pool_https,  # noqa: F401
    gtm_pool_mx,  # noqa: F401
    gtm_pool_naptr,  # noqa: F401
    gtm_pool_srv,  # noqa: F401
    gtm_pool_svcb,  # noqa: F401
    gtm_prober_pool,  # noqa: F401
    gtm_region,  # noqa: F401
    gtm_rule,  # noqa: F401
    gtm_server,  # noqa: F401
    gtm_topology,  # noqa: F401
    gtm_wideip_a,  # noqa: F401
    gtm_wideip_aaaa,  # noqa: F401
    gtm_wideip_cname,  # noqa: F401
    gtm_wideip_https,  # noqa: F401
    gtm_wideip_mx,  # noqa: F401
    gtm_wideip_naptr,  # noqa: F401
    gtm_wideip_srv,  # noqa: F401
    gtm_wideip_svcb,  # noqa: F401
    ilx_global_settings,  # noqa: F401
    ilx_plugin,  # noqa: F401
    ilx_workspace,  # noqa: F401
    ltm_alg_log_profile,  # noqa: F401
    ltm_auth_crldp_server,  # noqa: F401
    ltm_auth_kerberos_delegation,  # noqa: F401
    ltm_auth_ldap,  # noqa: F401
    ltm_auth_ocsp_responder,  # noqa: F401
    ltm_auth_profile,  # noqa: F401
    ltm_auth_radius,  # noqa: F401
    ltm_auth_radius_server,  # noqa: F401
    ltm_auth_ssl_cc_ldap,  # noqa: F401
    ltm_auth_ssl_crldp,  # noqa: F401
    ltm_auth_ssl_ocsp,  # noqa: F401
    ltm_auth_tacacs,  # noqa: F401
    ltm_cipher_group,  # noqa: F401
    ltm_cipher_rule,  # noqa: F401
    ltm_classification_application,  # noqa: F401
    ltm_classification_auto_update_settings,  # noqa: F401
    ltm_classification_category,  # noqa: F401
    ltm_classification_ce,  # noqa: F401
    ltm_classification_signature_update_schedule,  # noqa: F401
    ltm_classification_url_cat_policy,  # noqa: F401
    ltm_classification_url_category,  # noqa: F401
    ltm_classification_urldb_feed_list,  # noqa: F401
    ltm_classification_urldb_file,  # noqa: F401
    ltm_clientssl_ocsp_stapling_responses,  # noqa: F401
    ltm_clientssl_proxy_cached_certs,  # noqa: F401
    ltm_data_group_external,  # noqa: F401
    ltm_data_group_internal,  # noqa: F401
    ltm_default_node_monitor,  # noqa: F401
    ltm_dns_analytics_global_settings,  # noqa: F401
    ltm_dns_cache_global_settings,  # noqa: F401
    ltm_dns_cache_records_all,  # noqa: F401
    ltm_dns_cache_records_key,  # noqa: F401
    ltm_dns_cache_records_msg,  # noqa: F401
    ltm_dns_cache_records_nameserver,  # noqa: F401
    ltm_dns_cache_records_rrset,  # noqa: F401
    ltm_dns_cache_resolver,  # noqa: F401
    ltm_dns_cache_transparent,  # noqa: F401
    ltm_dns_cache_validating_resolver,  # noqa: F401
    ltm_dns_dnssec_key,  # noqa: F401
    ltm_dns_dnssec_zone,  # noqa: F401
    ltm_dns_hpke_key,  # noqa: F401
    ltm_dns_hpke_profile,  # noqa: F401
    ltm_dns_nameserver,  # noqa: F401
    ltm_dns_tsig_key,  # noqa: F401
    ltm_dns_zone,  # noqa: F401
    ltm_eviction_policy,  # noqa: F401
    ltm_global_settings_connection,  # noqa: F401
    ltm_global_settings_general,  # noqa: F401
    ltm_global_settings_rule,  # noqa: F401
    ltm_global_settings_traffic_control,  # noqa: F401
    ltm_ifile,  # noqa: F401
    ltm_lsn_log_profile,  # noqa: F401
    ltm_lsn_pool,  # noqa: F401
    ltm_message_routing_diameter_peer,  # noqa: F401
    ltm_message_routing_diameter_profile_router,  # noqa: F401
    ltm_message_routing_diameter_profile_session,  # noqa: F401
    ltm_message_routing_diameter_route,  # noqa: F401
    ltm_message_routing_diameter_transport_config,  # noqa: F401
    ltm_message_routing_generic_peer,  # noqa: F401
    ltm_message_routing_generic_protocol,  # noqa: F401
    ltm_message_routing_generic_route,  # noqa: F401
    ltm_message_routing_generic_router,  # noqa: F401
    ltm_message_routing_generic_transport_config,  # noqa: F401
    ltm_message_routing_mqtt_peer,  # noqa: F401
    ltm_message_routing_mqtt_profile_router,  # noqa: F401
    ltm_message_routing_mqtt_profile_session,  # noqa: F401
    ltm_message_routing_mqtt_route,  # noqa: F401
    ltm_message_routing_mqtt_transport_config,  # noqa: F401
    ltm_message_routing_sip_peer,  # noqa: F401
    ltm_message_routing_sip_profile_router,  # noqa: F401
    ltm_message_routing_sip_profile_session,  # noqa: F401
    ltm_message_routing_sip_route,  # noqa: F401
    ltm_message_routing_sip_transport_config,  # noqa: F401
    ltm_monitor_diameter,  # noqa: F401
    ltm_monitor_dns,  # noqa: F401
    ltm_monitor_external,  # noqa: F401
    ltm_monitor_firepass,  # noqa: F401
    ltm_monitor_ftp,  # noqa: F401
    ltm_monitor_gateway_icmp,  # noqa: F401
    ltm_monitor_http,  # noqa: F401
    ltm_monitor_http2,  # noqa: F401
    ltm_monitor_https,  # noqa: F401
    ltm_monitor_icmp,  # noqa: F401
    ltm_monitor_imap,  # noqa: F401
    ltm_monitor_inband,  # noqa: F401
    ltm_monitor_ldap,  # noqa: F401
    ltm_monitor_module_score,  # noqa: F401
    ltm_monitor_mqtt,  # noqa: F401
    ltm_monitor_mssql,  # noqa: F401
    ltm_monitor_mysql,  # noqa: F401
    ltm_monitor_nntp,  # noqa: F401
    ltm_monitor_oracle,  # noqa: F401
    ltm_monitor_pop3,  # noqa: F401
    ltm_monitor_postgresql,  # noqa: F401
    ltm_monitor_radius,  # noqa: F401
    ltm_monitor_radius_accounting,  # noqa: F401
    ltm_monitor_real_server,  # noqa: F401
    ltm_monitor_rpc,  # noqa: F401
    ltm_monitor_sasp,  # noqa: F401
    ltm_monitor_scripted,  # noqa: F401
    ltm_monitor_sip,  # noqa: F401
    ltm_monitor_smb,  # noqa: F401
    ltm_monitor_smtp,  # noqa: F401
    ltm_monitor_snmp_dca,  # noqa: F401
    ltm_monitor_snmp_dca_base,  # noqa: F401
    ltm_monitor_soap,  # noqa: F401
    ltm_monitor_tcp,  # noqa: F401
    ltm_monitor_tcp_echo,  # noqa: F401
    ltm_monitor_tcp_half_open,  # noqa: F401
    ltm_monitor_udp,  # noqa: F401
    ltm_monitor_virtual_location,  # noqa: F401
    ltm_monitor_wap,  # noqa: F401
    ltm_monitor_wmi,  # noqa: F401
    ltm_nat,  # noqa: F401
    ltm_node,  # noqa: F401
    ltm_persistence_cookie,  # noqa: F401
    ltm_persistence_dest_addr,  # noqa: F401
    ltm_persistence_global_settings,  # noqa: F401
    ltm_persistence_hash,  # noqa: F401
    ltm_persistence_host,  # noqa: F401
    ltm_persistence_msrdp,  # noqa: F401
    ltm_persistence_persist_records,  # noqa: F401
    ltm_persistence_sip,  # noqa: F401
    ltm_persistence_source_addr,  # noqa: F401
    ltm_persistence_ssl,  # noqa: F401
    ltm_persistence_universal,  # noqa: F401
    ltm_policy,  # noqa: F401
    ltm_pool,  # noqa: F401
    ltm_profile_analytics,  # noqa: F401
    ltm_profile_certificate_authority,  # noqa: F401
    ltm_profile_classification,  # noqa: F401
    ltm_profile_client_ldap,  # noqa: F401
    ltm_profile_client_ssl,  # noqa: F401
    ltm_profile_connector,  # noqa: F401
    ltm_profile_dhcpv4,  # noqa: F401
    ltm_profile_dhcpv6,  # noqa: F401
    ltm_profile_diameter,  # noqa: F401
    ltm_profile_dns,  # noqa: F401
    ltm_profile_dns_logging,  # noqa: F401
    ltm_profile_doh_proxy,  # noqa: F401
    ltm_profile_doh_server,  # noqa: F401
    ltm_profile_fasthttp,  # noqa: F401
    ltm_profile_fastl4,  # noqa: F401
    ltm_profile_fix,  # noqa: F401
    ltm_profile_ftp,  # noqa: F401
    ltm_profile_georedundancy,  # noqa: F401
    ltm_profile_gtp,  # noqa: F401
    ltm_profile_html,  # noqa: F401
    ltm_profile_http,  # noqa: F401
    ltm_profile_http2,  # noqa: F401
    ltm_profile_http3,  # noqa: F401
    ltm_profile_http_compression,  # noqa: F401
    ltm_profile_httprouter,  # noqa: F401
    ltm_profile_icap,  # noqa: F401
    ltm_profile_iiop,  # noqa: F401
    ltm_profile_ilx,  # noqa: F401
    ltm_profile_imap,  # noqa: F401
    ltm_profile_ipother,  # noqa: F401
    ltm_profile_ipsecalg,  # noqa: F401
    ltm_profile_json,  # noqa: F401
    ltm_profile_mapt,  # noqa: F401
    ltm_profile_mblb,  # noqa: F401
    ltm_profile_mqtt,  # noqa: F401
    ltm_profile_mr_ratelimit,  # noqa: F401
    ltm_profile_mr_ratelimit_action,  # noqa: F401
    ltm_profile_mssql,  # noqa: F401
    ltm_profile_netflow,  # noqa: F401
    ltm_profile_ntlm,  # noqa: F401
    ltm_profile_ocsp,  # noqa: F401
    ltm_profile_one_connect,  # noqa: F401
    ltm_profile_pcp,  # noqa: F401
    ltm_profile_pop3,  # noqa: F401
    ltm_profile_pptp,  # noqa: F401
    ltm_profile_qoe,  # noqa: F401
    ltm_profile_quic,  # noqa: F401
    ltm_profile_radius,  # noqa: F401
    ltm_profile_ramcache,  # noqa: F401
    ltm_profile_request_adapt,  # noqa: F401
    ltm_profile_request_log,  # noqa: F401
    ltm_profile_response_adapt,  # noqa: F401
    ltm_profile_rewrite,  # noqa: F401
    ltm_profile_rtsp,  # noqa: F401
    ltm_profile_sctp,  # noqa: F401
    ltm_profile_server_ldap,  # noqa: F401
    ltm_profile_server_ssl,  # noqa: F401
    ltm_profile_sip,  # noqa: F401
    ltm_profile_smtp,  # noqa: F401
    ltm_profile_smtps,  # noqa: F401
    ltm_profile_socks,  # noqa: F401
    ltm_profile_splitsessionclient,  # noqa: F401
    ltm_profile_splitsessionserver,  # noqa: F401
    ltm_profile_sse,  # noqa: F401
    ltm_profile_statistics,  # noqa: F401
    ltm_profile_stream,  # noqa: F401
    ltm_profile_tcp,  # noqa: F401
    ltm_profile_tcp_analytics,  # noqa: F401
    ltm_profile_tdr,  # noqa: F401
    ltm_profile_tftp,  # noqa: F401
    ltm_profile_traffic_acceleration,  # noqa: F401
    ltm_profile_udp,  # noqa: F401
    ltm_profile_wa_cache,  # noqa: F401
    ltm_profile_web_acceleration,  # noqa: F401
    ltm_profile_web_security,  # noqa: F401
    ltm_profile_websocket,  # noqa: F401
    ltm_profile_xml,  # noqa: F401
    ltm_rule,  # noqa: F401
    ltm_rule_profiler,  # noqa: F401
    ltm_snat,  # noqa: F401
    ltm_snat_translation,  # noqa: F401
    ltm_snatpool,  # noqa: F401
    ltm_tacdb_customdb,  # noqa: F401
    ltm_tacdb_customdb_file,  # noqa: F401
    ltm_tacdb_licenseddb,  # noqa: F401
    ltm_traffic_class,  # noqa: F401
    ltm_traffic_matching_criteria,  # noqa: F401
    ltm_urlcat_cloud_cache,  # noqa: F401
    ltm_virtual,  # noqa: F401
    ltm_virtual_address,  # noqa: F401
    mgmt_shared_settings_api_status_availability,  # noqa: F401
    mgmt_shared_settings_api_status_log_resource,  # noqa: F401
    mgmt_shared_settings_api_status_log_resource_property,  # noqa: F401
    net_address_list,  # noqa: F401
    net_arp,  # noqa: F401
    net_bwc_policy,  # noqa: F401
    net_bwc_priority_group,  # noqa: F401
    net_bwc_traffic_group,  # noqa: F401
    net_cmetrics,  # noqa: F401
    net_cos_global_settings,  # noqa: F401
    net_cos_map_8021p,  # noqa: F401
    net_cos_map_dscp,  # noqa: F401
    net_cos_traffic_priority,  # noqa: F401
    net_dag_globals,  # noqa: F401
    net_dns_resolver,  # noqa: F401
    net_fdb_tunnel,  # noqa: F401
    net_fdb_vlan,  # noqa: F401
    net_interface,  # noqa: F401
    net_ipsec_ike_daemon,  # noqa: F401
    net_ipsec_ike_peer,  # noqa: F401
    net_ipsec_ipsec_policy,  # noqa: F401
    net_ipsec_manual_security_association,  # noqa: F401
    net_ipsec_traffic_selector,  # noqa: F401
    net_ipv6_subscriber_prefix_length,  # noqa: F401
    net_lacp_globals,  # noqa: F401
    net_lldp_globals,  # noqa: F401
    net_multicast_globals,  # noqa: F401
    net_ndp,  # noqa: F401
    net_packet_filter,  # noqa: F401
    net_packet_filter_trusted,  # noqa: F401
    net_port_list,  # noqa: F401
    net_port_mirror,  # noqa: F401
    net_rate_shaping_class,  # noqa: F401
    net_rate_shaping_color_policer,  # noqa: F401
    net_rate_shaping_drop_policy,  # noqa: F401
    net_rate_shaping_queue,  # noqa: F401
    net_rate_shaping_shaping_policy,  # noqa: F401
    net_route,  # noqa: F401
    net_route_domain,  # noqa: F401
    net_router_advertisement,  # noqa: F401
    net_routing_access_list,  # noqa: F401
    net_routing_bfd,  # noqa: F401
    net_routing_bgp,  # noqa: F401
    net_routing_community_list,  # noqa: F401
    net_routing_debug,  # noqa: F401
    net_routing_extcommunity_list,  # noqa: F401
    net_routing_prefix_list,  # noqa: F401
    net_routing_profile_bgp,  # noqa: F401
    net_routing_route_map,  # noqa: F401
    net_self,  # noqa: F401
    net_self_allow,  # noqa: F401
    net_service_policy,  # noqa: F401
    net_sfc_chain,  # noqa: F401
    net_sfc_sf,  # noqa: F401
    net_stp,  # noqa: F401
    net_stp_globals,  # noqa: F401
    net_timer_policy,  # noqa: F401
    net_trunk,  # noqa: F401
    net_tunnels_etherip,  # noqa: F401
    net_tunnels_fec,  # noqa: F401
    net_tunnels_geneve,  # noqa: F401
    net_tunnels_gre,  # noqa: F401
    net_tunnels_ipip,  # noqa: F401
    net_tunnels_ipsec,  # noqa: F401
    net_tunnels_lw4o6,  # noqa: F401
    net_tunnels_map,  # noqa: F401
    net_tunnels_ppp,  # noqa: F401
    net_tunnels_tcp_forward,  # noqa: F401
    net_tunnels_tunnel,  # noqa: F401
    net_tunnels_v6rd,  # noqa: F401
    net_tunnels_vxlan,  # noqa: F401
    net_tunnels_wccp,  # noqa: F401
    net_vlan,  # noqa: F401
    net_vlan_group,  # noqa: F401
    net_wccp,  # noqa: F401
    pem_forwarding_endpoint,  # noqa: F401
    pem_global_settings_analytics,  # noqa: F401
    pem_global_settings_gx,  # noqa: F401
    pem_global_settings_hsl_flow,  # noqa: F401
    pem_global_settings_hsl_report,  # noqa: F401
    pem_global_settings_insert_content,  # noqa: F401
    pem_global_settings_policy,  # noqa: F401
    pem_global_settings_quota_mgmt,  # noqa: F401
    pem_global_settings_session_mgmt_attributes,  # noqa: F401
    pem_global_settings_subscriber_activity_log,  # noqa: F401
    pem_interception_endpoint,  # noqa: F401
    pem_irule,  # noqa: F401
    pem_listener,  # noqa: F401
    pem_policy,  # noqa: F401
    pem_profile_diameter_endpoint,  # noqa: F401
    pem_profile_radius_aaa,  # noqa: F401
    pem_profile_spm,  # noqa: F401
    pem_profile_subscriber_mgmt,  # noqa: F401
    pem_protocol_diameter_avp,  # noqa: F401
    pem_protocol_profile_gx,  # noqa: F401
    pem_protocol_profile_radius,  # noqa: F401
    pem_protocol_radius_avp,  # noqa: F401
    pem_quota_mgmt_rating_group,  # noqa: F401
    pem_reporting_format_script,  # noqa: F401
    pem_service_chain_endpoint,  # noqa: F401
    pem_subscriber,  # noqa: F401
    pem_subscriber_attribute,  # noqa: F401
    saas_ap_ai_profile,  # noqa: F401
    saas_ati_profile,  # noqa: F401
    saas_bd_profile,  # noqa: F401
    saas_csd_profile,  # noqa: F401
    security_analytics_settings,  # noqa: F401
    security_anti_fraud_profile,  # noqa: F401
    security_anti_fraud_signatures_update,  # noqa: F401
    security_blacklist_publisher_category,  # noqa: F401
    security_blacklist_publisher_profile,  # noqa: F401
    security_bot_defense_profile,  # noqa: F401
    security_bot_defense_signature,  # noqa: F401
    security_bot_defense_signature_category,  # noqa: F401
    security_cloud_services_connector,  # noqa: F401
    security_datasync_background_tasks,  # noqa: F401
    security_datasync_global_profile,  # noqa: F401
    security_datasync_local_profile,  # noqa: F401
    security_debug_matcher,  # noqa: F401
    security_debug_register,  # noqa: F401
    security_device_device_context,  # noqa: F401
    security_device_id_attribute,  # noqa: F401
    security_dos_autodos_file_object,  # noqa: F401
    security_dos_behavioral_signature,  # noqa: F401
    security_dos_bot_signature,  # noqa: F401
    security_dos_bot_signature_category,  # noqa: F401
    security_dos_device_config,  # noqa: F401
    security_dos_dos_signature,  # noqa: F401
    security_dos_dynamic_signatures,  # noqa: F401
    security_dos_ip_uncommon_protolist,  # noqa: F401
    security_dos_l4bdos_file_object,  # noqa: F401
    security_dos_network_whitelist,  # noqa: F401
    security_dos_profile,  # noqa: F401
    security_dos_udp_portlist,  # noqa: F401
    security_firewall_address_list,  # noqa: F401
    security_firewall_config_change_log,  # noqa: F401
    security_firewall_global_fqdn_policy,  # noqa: F401
    security_firewall_global_rules,  # noqa: F401
    security_firewall_management_ip_rules,  # noqa: F401
    security_firewall_on_demand_compilation,  # noqa: F401
    security_firewall_on_demand_rule_deploy,  # noqa: F401
    security_firewall_policy,  # noqa: F401
    security_firewall_port_list,  # noqa: F401
    security_firewall_port_misuse_policy,  # noqa: F401
    security_firewall_rule_list,  # noqa: F401
    security_firewall_schedule,  # noqa: F401
    security_firewall_user_domain,  # noqa: F401
    security_firewall_user_list,  # noqa: F401
    security_firewall_uuid_default_autogenerate,  # noqa: F401
    security_flowspec_route_injector_profile,  # noqa: F401
    security_http_profile,  # noqa: F401
    security_ip_intelligence_blacklist_category,  # noqa: F401
    security_ip_intelligence_feed_list,  # noqa: F401
    security_ip_intelligence_global_policy,  # noqa: F401
    security_ip_intelligence_policy,  # noqa: F401
    security_log_profile,  # noqa: F401
    security_nat_destination_translation,  # noqa: F401
    security_nat_policy,  # noqa: F401
    security_nat_source_translation,  # noqa: F401
    security_packet_filter_default_rules,  # noqa: F401
    security_packet_filter_policy,  # noqa: F401
    security_protected_zone,  # noqa: F401
    security_protocol_inspection_common_config,  # noqa: F401
    security_protocol_inspection_learning_stats,  # noqa: F401
    security_protocol_inspection_profile,  # noqa: F401
    security_protocol_inspection_signature,  # noqa: F401
    security_scrubber_profile,  # noqa: F401
    security_ssh_ciphers,  # noqa: F401
    security_ssh_profile,  # noqa: F401
    security_zone,  # noqa: F401
    sys_appiq_config,  # noqa: F401
    sys_application_apl_script,  # noqa: F401
    sys_application_custom_stat,  # noqa: F401
    sys_application_service,  # noqa: F401
    sys_application_template,  # noqa: F401
    sys_autoscale_group,  # noqa: F401
    sys_clock,  # noqa: F401
    sys_cluster,  # noqa: F401
    sys_config,  # noqa: F401
    sys_connection,  # noqa: F401
    sys_console,  # noqa: F401
    sys_core,  # noqa: F401
    sys_crypto_allow_key_export,  # noqa: F401
    sys_crypto_ca_bundle_manager,  # noqa: F401
    sys_crypto_cert,  # noqa: F401
    sys_crypto_cert_order_manager,  # noqa: F401
    sys_crypto_cert_validation_response_ocsp,  # noqa: F401
    sys_crypto_cert_validator_crl,  # noqa: F401
    sys_crypto_cert_validator_ocsp,  # noqa: F401
    sys_crypto_client,  # noqa: F401
    sys_crypto_csr,  # noqa: F401
    sys_crypto_fips_external_hsm,  # noqa: F401
    sys_crypto_fips_key,  # noqa: F401
    sys_crypto_key,  # noqa: F401
    sys_crypto_master_key,  # noqa: F401
    sys_crypto_server,  # noqa: F401
    sys_daemon_ha,  # noqa: F401
    sys_daemon_log_settings_clusterd,  # noqa: F401
    sys_daemon_log_settings_csyncd,  # noqa: F401
    sys_daemon_log_settings_icr_eventd,  # noqa: F401
    sys_daemon_log_settings_icrd,  # noqa: F401
    sys_daemon_log_settings_lind,  # noqa: F401
    sys_daemon_log_settings_mcpd,  # noqa: F401
    sys_daemon_log_settings_tmm,  # noqa: F401
    sys_datastor,  # noqa: F401
    sys_db,  # noqa: F401
    sys_diags_ihealth,  # noqa: F401
    sys_disk_application_volume,  # noqa: F401
    sys_disk_directory,  # noqa: F401
    sys_disk_logical_disk,  # noqa: F401
    sys_dns,  # noqa: F401
    sys_dynad_instrumentation,  # noqa: F401
    sys_dynad_key,  # noqa: F401
    sys_dynad_rpm,  # noqa: F401
    sys_dynad_settings,  # noqa: F401
    sys_ecm_config,  # noqa: F401
    sys_feature_module,  # noqa: F401
    sys_file_apache_ssl_cert,  # noqa: F401
    sys_file_browser_capabilities_db,  # noqa: F401
    sys_file_data_group,  # noqa: F401
    sys_file_device_capabilities_db,  # noqa: F401
    sys_file_external_monitor,  # noqa: F401
    sys_file_ifile,  # noqa: F401
    sys_file_lwtunneltbl,  # noqa: F401
    sys_file_rewrite_rule,  # noqa: F401
    sys_file_ssl_cert,  # noqa: F401
    sys_file_ssl_crl,  # noqa: F401
    sys_file_ssl_key,  # noqa: F401
    sys_folder,  # noqa: F401
    sys_fpga_firmware_config,  # noqa: F401
    sys_global_settings,  # noqa: F401
    sys_ha_group,  # noqa: F401
    sys_httpd,  # noqa: F401
    sys_iapp_restricted_key,  # noqa: F401
    sys_iapprestricted_key,  # noqa: F401
    sys_icall_handler_periodic,  # noqa: F401
    sys_icall_handler_perpetual,  # noqa: F401
    sys_icall_handler_triggered,  # noqa: F401
    sys_icall_istats_trigger,  # noqa: F401
    sys_icall_script,  # noqa: F401
    sys_icontrol_soap,  # noqa: F401
    sys_internal_proxy,  # noqa: F401
    sys_ipfix_element,  # noqa: F401
    sys_log_config_destination_alertd,  # noqa: F401
    sys_log_config_destination_arcsight,  # noqa: F401
    sys_log_config_destination_ipfix,  # noqa: F401
    sys_log_config_destination_local_database,  # noqa: F401
    sys_log_config_destination_local_syslog,  # noqa: F401
    sys_log_config_destination_management_port,  # noqa: F401
    sys_log_config_destination_remote_high_speed_log,  # noqa: F401
    sys_log_config_destination_remote_syslog,  # noqa: F401
    sys_log_config_destination_splunk,  # noqa: F401
    sys_log_config_filter,  # noqa: F401
    sys_log_config_publisher,  # noqa: F401
    sys_log_rotate,  # noqa: F401
    sys_management_dhcp,  # noqa: F401
    sys_management_ip,  # noqa: F401
    sys_management_ovsdb,  # noqa: F401
    sys_management_proxy_config,  # noqa: F401
    sys_management_route,  # noqa: F401
    sys_ntp,  # noqa: F401
    sys_outbound_smtp,  # noqa: F401
    sys_pfman_consumer,  # noqa: F401
    sys_pfman_device,  # noqa: F401
    sys_provision,  # noqa: F401
    sys_raid_array,  # noqa: F401
    sys_raid_bay,  # noqa: F401
    sys_scriptd,  # noqa: F401
    sys_service,  # noqa: F401
    sys_sflow_global_settings_http,  # noqa: F401
    sys_sflow_global_settings_interface,  # noqa: F401
    sys_sflow_global_settings_system,  # noqa: F401
    sys_sflow_global_settings_vlan,  # noqa: F401
    sys_sflow_receiver,  # noqa: F401
    sys_smtp_server,  # noqa: F401
    sys_snmp,  # noqa: F401
    sys_software_hotfix,  # noqa: F401
    sys_software_image,  # noqa: F401
    sys_software_signature,  # noqa: F401
    sys_software_update,  # noqa: F401
    sys_software_volume,  # noqa: F401
    sys_sshd,  # noqa: F401
    sys_state_mirroring,  # noqa: F401
    sys_syslog,  # noqa: F401
    sys_turboflex_profile_config,  # noqa: F401
    sys_ucs,  # noqa: F401
    sys_url_db_download_schedule,  # noqa: F401
    sys_url_db_url_category,  # noqa: F401
    util_ipsecalgdb,  # noqa: F401
    vcmp_guest,  # noqa: F401
    vcmp_traffic_profile,  # noqa: F401
    vcmp_virtual_disk,  # noqa: F401
    vcmp_virtual_disk_template,  # noqa: F401
    wam_ad_policy,  # noqa: F401
    wam_application,  # noqa: F401
    wam_domain_list,  # noqa: F401
    wam_object_type,  # noqa: F401
    wam_policy,  # noqa: F401
    wam_resource_concat_set,  # noqa: F401
    wam_resource_domain_list,  # noqa: F401
    wam_resource_url,  # noqa: F401
    wom_advertised_route,  # noqa: F401
    wom_deduplication,  # noqa: F401
    wom_endpoint_discovery,  # noqa: F401
    wom_local_endpoint,  # noqa: F401
    wom_profile_cifs,  # noqa: F401
    wom_profile_isession,  # noqa: F401
    wom_profile_mapi,  # noqa: F401
    wom_remote_endpoint,  # noqa: F401
    wom_server_discovery,  # noqa: F401
)
from ._base import _REGISTRY


def bigip_object_specs() -> tuple:
    return tuple(_REGISTRY)


OBJECT_SPECS = bigip_object_specs()

__all__ = ["OBJECT_SPECS", "bigip_object_specs"]
