from __future__ import annotations

from . import (
    auth_apm_auth,  # noqa: F401
    auth_cert_ldap,  # noqa: F401
    auth_ldap,  # noqa: F401
    auth_login_failures,  # noqa: F401
    auth_partition,  # noqa: F401
    auth_password,  # noqa: F401
    auth_password_policy,  # noqa: F401
    auth_radius,  # noqa: F401
    auth_radius_server,  # noqa: F401
    auth_remote_role,  # noqa: F401
    auth_remote_user,  # noqa: F401
    auth_source,  # noqa: F401
    auth_tacacs,  # noqa: F401
    auth_user,  # noqa: F401
    cm_add_to_trust,  # noqa: F401
    cm_cert,  # noqa: F401
    cm_config_sync,  # noqa: F401
    cm_device,  # noqa: F401
    cm_device_group,  # noqa: F401
    cm_failover_status,  # noqa: F401
    cm_ha_group,  # noqa: F401
    cm_key,  # noqa: F401
    cm_remove_from_trust,  # noqa: F401
    cm_sha1_fingerprint,  # noqa: F401
    cm_sniff_updates,  # noqa: F401
    cm_sync_status,  # noqa: F401
    cm_traffic_group,  # noqa: F401
    cm_trust_domain,  # noqa: F401
    cm_watch_devicegroup_device,  # noqa: F401
    cm_watch_sys_device,  # noqa: F401
    cm_watch_trafficgroup_device,  # noqa: F401
    gtm_add,  # noqa: F401
    gtm_datacenter,  # noqa: F401
    gtm_distributed_app,  # noqa: F401
    gtm_global_settings_general,  # noqa: F401
    gtm_global_settings_load_balancing,  # noqa: F401
    gtm_global_settings_metrics,  # noqa: F401
    gtm_global_settings_metrics_exclusions,  # noqa: F401
    gtm_iquery,  # noqa: F401
    gtm_ldns,  # noqa: F401
    gtm_link,  # noqa: F401
    gtm_listener,  # noqa: F401
    gtm_listener_doh_proxy,  # noqa: F401
    gtm_listener_doh_server,  # noqa: F401
    gtm_monitor_bigip,  # noqa: F401
    gtm_monitor_bigip_link,  # noqa: F401
    gtm_monitor_external,  # noqa: F401
    gtm_monitor_firepass,  # noqa: F401
    gtm_monitor_ftp,  # noqa: F401
    gtm_monitor_gateway_icmp,  # noqa: F401
    gtm_monitor_gtp,  # noqa: F401
    gtm_monitor_http,  # noqa: F401
    gtm_monitor_https,  # noqa: F401
    gtm_monitor_imap,  # noqa: F401
    gtm_monitor_ldap,  # noqa: F401
    gtm_monitor_mssql,  # noqa: F401
    gtm_monitor_mysql,  # noqa: F401
    gtm_monitor_nntp,  # noqa: F401
    gtm_monitor_none,  # noqa: F401
    gtm_monitor_oracle,  # noqa: F401
    gtm_monitor_pop3,  # noqa: F401
    gtm_monitor_postgresql,  # noqa: F401
    gtm_monitor_radius,  # noqa: F401
    gtm_monitor_radius_accounting,  # noqa: F401
    gtm_monitor_real_server,  # noqa: F401
    gtm_monitor_scripted,  # noqa: F401
    gtm_monitor_sip,  # noqa: F401
    gtm_monitor_smtp,  # noqa: F401
    gtm_monitor_snmp,  # noqa: F401
    gtm_monitor_snmp_link,  # noqa: F401
    gtm_monitor_soap,  # noqa: F401
    gtm_monitor_tcp,  # noqa: F401
    gtm_monitor_tcp_half_open,  # noqa: F401
    gtm_monitor_udp,  # noqa: F401
    gtm_monitor_wap,  # noqa: F401
    gtm_monitor_wmi,  # noqa: F401
    gtm_path,  # noqa: F401
    gtm_persist,  # noqa: F401
    gtm_pool_a,  # noqa: F401
    gtm_pool_aaaa,  # noqa: F401
    gtm_pool_cname,  # noqa: F401
    gtm_pool_https,  # noqa: F401
    gtm_pool_mx,  # noqa: F401
    gtm_pool_naptr,  # noqa: F401
    gtm_pool_srv,  # noqa: F401
    gtm_pool_svcb,  # noqa: F401
    gtm_prober_pool,  # noqa: F401
    gtm_region,  # noqa: F401
    gtm_rule,  # noqa: F401
    gtm_server,  # noqa: F401
    gtm_topology,  # noqa: F401
    gtm_traffic,  # noqa: F401
    gtm_wideip_a,  # noqa: F401
    gtm_wideip_aaaa,  # noqa: F401
    gtm_wideip_cname,  # noqa: F401
    gtm_wideip_https,  # noqa: F401
    gtm_wideip_mx,  # noqa: F401
    gtm_wideip_naptr,  # noqa: F401
    gtm_wideip_srv,  # noqa: F401
    gtm_wideip_svcb,  # noqa: F401
    ltm_alg_log_profile,  # noqa: F401
    ltm_auth_crldp_server,  # noqa: F401
    ltm_auth_kerberos_delegation,  # noqa: F401
    ltm_auth_ldap,  # noqa: F401
    ltm_auth_ocsp_responder,  # noqa: F401
    ltm_auth_profile,  # noqa: F401
    ltm_auth_radius,  # noqa: F401
    ltm_auth_radius_server,  # noqa: F401
    ltm_auth_ssl_cc_ldap,  # noqa: F401
    ltm_auth_ssl_crldp,  # noqa: F401
    ltm_auth_ssl_ocsp,  # noqa: F401
    ltm_auth_tacacs,  # noqa: F401
    ltm_cipher_group,  # noqa: F401
    ltm_cipher_rule,  # noqa: F401
    ltm_classification_application,  # noqa: F401
    ltm_classification_auto_update_settings,  # noqa: F401
    ltm_classification_auto_update_status,  # noqa: F401
    ltm_classification_category,  # noqa: F401
    ltm_classification_ce,  # noqa: F401
    ltm_classification_signature_definition,  # noqa: F401
    ltm_classification_signature_update_schedule,  # noqa: F401
    ltm_classification_signature_version,  # noqa: F401
    ltm_classification_signatures,  # noqa: F401
    ltm_classification_stats_application,  # noqa: F401
    ltm_classification_stats_url_category,  # noqa: F401
    ltm_classification_stats_urlcat_cloud,  # noqa: F401
    ltm_classification_update_signatures,  # noqa: F401
    ltm_classification_updates,  # noqa: F401
    ltm_classification_url_cat_policy,  # noqa: F401
    ltm_classification_url_category,  # noqa: F401
    ltm_classification_urldb_feed_list,  # noqa: F401
    ltm_classification_urldb_file,  # noqa: F401
    ltm_clientssl_ocsp_stapling_responses,  # noqa: F401
    ltm_clientssl_proxy_cached_certs,  # noqa: F401
    ltm_data_group_external,  # noqa: F401
    ltm_data_group_internal,  # noqa: F401
    ltm_default_node_monitor,  # noqa: F401
    ltm_dns_analytics_global_settings,  # noqa: F401
    ltm_dns_cache_global_settings,  # noqa: F401
    ltm_dns_cache_records_all,  # noqa: F401
    ltm_dns_cache_records_key,  # noqa: F401
    ltm_dns_cache_records_msg,  # noqa: F401
    ltm_dns_cache_records_nameserver,  # noqa: F401
    ltm_dns_cache_records_rrset,  # noqa: F401
    ltm_dns_cache_resolver,  # noqa: F401
    ltm_dns_cache_transparent,  # noqa: F401
    ltm_dns_cache_validating_resolver,  # noqa: F401
    ltm_dns_dns_express_db,  # noqa: F401
    ltm_dns_dnssec_key,  # noqa: F401
    ltm_dns_dnssec_zone,  # noqa: F401
    ltm_dns_hpke_key,  # noqa: F401
    ltm_dns_hpke_profile,  # noqa: F401
    ltm_dns_nameserver,  # noqa: F401
    ltm_dns_tsig_key,  # noqa: F401
    ltm_dns_zone,  # noqa: F401
    ltm_eviction_policy,  # noqa: F401
    ltm_global_settings_connection,  # noqa: F401
    ltm_global_settings_general,  # noqa: F401
    ltm_global_settings_rule,  # noqa: F401
    ltm_global_settings_traffic_control,  # noqa: F401
    ltm_ifile,  # noqa: F401
    ltm_lsn_log_profile,  # noqa: F401
    ltm_lsn_pool,  # noqa: F401
    ltm_message_routing_diameter_peer,  # noqa: F401
    ltm_message_routing_diameter_profile_router,  # noqa: F401
    ltm_message_routing_diameter_profile_session,  # noqa: F401
    ltm_message_routing_diameter_route,  # noqa: F401
    ltm_message_routing_diameter_transport_config,  # noqa: F401
    ltm_message_routing_generic_peer,  # noqa: F401
    ltm_message_routing_generic_protocol,  # noqa: F401
    ltm_message_routing_generic_route,  # noqa: F401
    ltm_message_routing_generic_router,  # noqa: F401
    ltm_message_routing_generic_transport_config,  # noqa: F401
    ltm_message_routing_mqtt_peer,  # noqa: F401
    ltm_message_routing_mqtt_profile_router,  # noqa: F401
    ltm_message_routing_mqtt_profile_session,  # noqa: F401
    ltm_message_routing_mqtt_route,  # noqa: F401
    ltm_message_routing_mqtt_transport_config,  # noqa: F401
    ltm_message_routing_sip_peer,  # noqa: F401
    ltm_message_routing_sip_profile_router,  # noqa: F401
    ltm_message_routing_sip_profile_session,  # noqa: F401
    ltm_message_routing_sip_route,  # noqa: F401
    ltm_message_routing_sip_transport_config,  # noqa: F401
    ltm_monitor_diameter,  # noqa: F401
    ltm_monitor_dns,  # noqa: F401
    ltm_monitor_external,  # noqa: F401
    ltm_monitor_firepass,  # noqa: F401
    ltm_monitor_ftp,  # noqa: F401
    ltm_monitor_gateway_icmp,  # noqa: F401
    ltm_monitor_http,  # noqa: F401
    ltm_monitor_http2,  # noqa: F401
    ltm_monitor_https,  # noqa: F401
    ltm_monitor_icmp,  # noqa: F401
    ltm_monitor_imap,  # noqa: F401
    ltm_monitor_inband,  # noqa: F401
    ltm_monitor_ldap,  # noqa: F401
    ltm_monitor_module_score,  # noqa: F401
    ltm_monitor_mqtt,  # noqa: F401
    ltm_monitor_mssql,  # noqa: F401
    ltm_monitor_mysql,  # noqa: F401
    ltm_monitor_nntp,  # noqa: F401
    ltm_monitor_none,  # noqa: F401
    ltm_monitor_oracle,  # noqa: F401
    ltm_monitor_pop3,  # noqa: F401
    ltm_monitor_postgresql,  # noqa: F401
    ltm_monitor_radius,  # noqa: F401
    ltm_monitor_radius_accounting,  # noqa: F401
    ltm_monitor_real_server,  # noqa: F401
    ltm_monitor_rpc,  # noqa: F401
    ltm_monitor_sasp,  # noqa: F401
    ltm_monitor_scripted,  # noqa: F401
    ltm_monitor_sip,  # noqa: F401
    ltm_monitor_smb,  # noqa: F401
    ltm_monitor_smtp,  # noqa: F401
    ltm_monitor_snmp_dca,  # noqa: F401
    ltm_monitor_snmp_dca_base,  # noqa: F401
    ltm_monitor_soap,  # noqa: F401
    ltm_monitor_tcp,  # noqa: F401
    ltm_monitor_tcp_echo,  # noqa: F401
    ltm_monitor_tcp_half_open,  # noqa: F401
    ltm_monitor_udp,  # noqa: F401
    ltm_monitor_virtual_location,  # noqa: F401
    ltm_monitor_wap,  # noqa: F401
    ltm_monitor_wmi,  # noqa: F401
    ltm_nat,  # noqa: F401
    ltm_nat_stats,  # noqa: F401
    ltm_node,  # noqa: F401
    ltm_persistence_cookie,  # noqa: F401
    ltm_persistence_dest_addr,  # noqa: F401
    ltm_persistence_global_settings,  # noqa: F401
    ltm_persistence_hash,  # noqa: F401
    ltm_persistence_host,  # noqa: F401
    ltm_persistence_msrdp,  # noqa: F401
    ltm_persistence_persist_records,  # noqa: F401
    ltm_persistence_sip,  # noqa: F401
    ltm_persistence_source_addr,  # noqa: F401
    ltm_persistence_ssl,  # noqa: F401
    ltm_persistence_universal,  # noqa: F401
    ltm_policy,  # noqa: F401
    ltm_policy_strategy,  # noqa: F401
    ltm_pool,  # noqa: F401
    ltm_profile_analytics,  # noqa: F401
    ltm_profile_certificate_authority,  # noqa: F401
    ltm_profile_classification,  # noqa: F401
    ltm_profile_client_ldap,  # noqa: F401
    ltm_profile_client_ssl,  # noqa: F401
    ltm_profile_connector,  # noqa: F401
    ltm_profile_dhcpv4,  # noqa: F401
    ltm_profile_dhcpv6,  # noqa: F401
    ltm_profile_diameter,  # noqa: F401
    ltm_profile_dns,  # noqa: F401
    ltm_profile_dns_logging,  # noqa: F401
    ltm_profile_doh_proxy,  # noqa: F401
    ltm_profile_doh_server,  # noqa: F401
    ltm_profile_fasthttp,  # noqa: F401
    ltm_profile_fastl4,  # noqa: F401
    ltm_profile_fix,  # noqa: F401
    ltm_profile_ftp,  # noqa: F401
    ltm_profile_georedundancy,  # noqa: F401
    ltm_profile_gtp,  # noqa: F401
    ltm_profile_html,  # noqa: F401
    ltm_profile_http,  # noqa: F401
    ltm_profile_http2,  # noqa: F401
    ltm_profile_http3,  # noqa: F401
    ltm_profile_http_compression,  # noqa: F401
    ltm_profile_httprouter,  # noqa: F401
    ltm_profile_icap,  # noqa: F401
    ltm_profile_iiop,  # noqa: F401
    ltm_profile_ilx,  # noqa: F401
    ltm_profile_imap,  # noqa: F401
    ltm_profile_ipother,  # noqa: F401
    ltm_profile_ipsecalg,  # noqa: F401
    ltm_profile_json,  # noqa: F401
    ltm_profile_mapt,  # noqa: F401
    ltm_profile_mblb,  # noqa: F401
    ltm_profile_mqtt,  # noqa: F401
    ltm_profile_mr_ratelimit,  # noqa: F401
    ltm_profile_mr_ratelimit_action,  # noqa: F401
    ltm_profile_mssql,  # noqa: F401
    ltm_profile_netflow,  # noqa: F401
    ltm_profile_ntlm,  # noqa: F401
    ltm_profile_ocsp,  # noqa: F401
    ltm_profile_ocsp_stapling_params,  # noqa: F401
    ltm_profile_one_connect,  # noqa: F401
    ltm_profile_pcp,  # noqa: F401
    ltm_profile_pop3,  # noqa: F401
    ltm_profile_pptp,  # noqa: F401
    ltm_profile_qoe,  # noqa: F401
    ltm_profile_quic,  # noqa: F401
    ltm_profile_radius,  # noqa: F401
    ltm_profile_ramcache,  # noqa: F401
    ltm_profile_request_adapt,  # noqa: F401
    ltm_profile_request_log,  # noqa: F401
    ltm_profile_response_adapt,  # noqa: F401
    ltm_profile_rewrite,  # noqa: F401
    ltm_profile_rtsp,  # noqa: F401
    ltm_profile_sctp,  # noqa: F401
    ltm_profile_server_ldap,  # noqa: F401
    ltm_profile_server_ssl,  # noqa: F401
    ltm_profile_sip,  # noqa: F401
    ltm_profile_smtp,  # noqa: F401
    ltm_profile_smtps,  # noqa: F401
    ltm_profile_socks,  # noqa: F401
    ltm_profile_splitsessionclient,  # noqa: F401
    ltm_profile_splitsessionserver,  # noqa: F401
    ltm_profile_sse,  # noqa: F401
    ltm_profile_statistics,  # noqa: F401
    ltm_profile_stream,  # noqa: F401
    ltm_profile_tcp,  # noqa: F401
    ltm_profile_tcp_analytics,  # noqa: F401
    ltm_profile_tdr,  # noqa: F401
    ltm_profile_tftp,  # noqa: F401
    ltm_profile_traffic_acceleration,  # noqa: F401
    ltm_profile_udp,  # noqa: F401
    ltm_profile_wa_cache,  # noqa: F401
    ltm_profile_web_acceleration,  # noqa: F401
    ltm_profile_web_security,  # noqa: F401
    ltm_profile_websocket,  # noqa: F401
    ltm_profile_xml,  # noqa: F401
    ltm_rule,  # noqa: F401
    ltm_rule_profiler,  # noqa: F401
    ltm_snat,  # noqa: F401
    ltm_snat_translation,  # noqa: F401
    ltm_snatpool,  # noqa: F401
    ltm_tacdb_customdb,  # noqa: F401
    ltm_tacdb_customdb_file,  # noqa: F401
    ltm_tacdb_licenseddb,  # noqa: F401
    ltm_tacdb_query,  # noqa: F401
    ltm_traffic_class,  # noqa: F401
    ltm_traffic_matching_criteria,  # noqa: F401
    ltm_urlcat_cloud_cache,  # noqa: F401
    ltm_urlcat_query,  # noqa: F401
    ltm_virtual,  # noqa: F401
    ltm_virtual_address,  # noqa: F401
    net_address_list,  # noqa: F401
    net_arp,  # noqa: F401
    net_bwc_policy,  # noqa: F401
    net_bwc_priority_group,  # noqa: F401
    net_bwc_traffic_group,  # noqa: F401
    net_clone_stats,  # noqa: F401
    net_cmetrics,  # noqa: F401
    net_cos_global_settings,  # noqa: F401
    net_cos_map_8021p,  # noqa: F401
    net_cos_map_dscp,  # noqa: F401
    net_cos_traffic_priority,  # noqa: F401
    net_dag_globals,  # noqa: F401
    net_dns_resolver,  # noqa: F401
    net_f5optics,  # noqa: F401
    net_fdb_tunnel,  # noqa: F401
    net_fdb_vlan,  # noqa: F401
    net_ike_evt_stat,  # noqa: F401
    net_ike_msg_stat,  # noqa: F401
    net_interface,  # noqa: F401
    net_interface_cos,  # noqa: F401
    net_interface_ddm,  # noqa: F401
    net_ipsec_ike_daemon,  # noqa: F401
    net_ipsec_ike_peer,  # noqa: F401
    net_ipsec_ike_sa,  # noqa: F401
    net_ipsec_ipsec_policy,  # noqa: F401
    net_ipsec_ipsec_sa,  # noqa: F401
    net_ipsec_manual_security_association,  # noqa: F401
    net_ipsec_stat,  # noqa: F401
    net_ipsec_traffic_selector,  # noqa: F401
    net_ipv6_subscriber_prefix_length,  # noqa: F401
    net_lacp_globals,  # noqa: F401
    net_lldp_globals,  # noqa: F401
    net_lldp_neighbors,  # noqa: F401
    net_mroute,  # noqa: F401
    net_multicast_globals,  # noqa: F401
    net_ndp,  # noqa: F401
    net_packet_filter,  # noqa: F401
    net_packet_filter_trusted,  # noqa: F401
    net_packet_tester_security,  # noqa: F401
    net_port_list,  # noqa: F401
    net_port_mirror,  # noqa: F401
    net_rate_shaping_class,  # noqa: F401
    net_rate_shaping_color_policer,  # noqa: F401
    net_rate_shaping_drop_policy,  # noqa: F401
    net_rate_shaping_queue,  # noqa: F401
    net_rate_shaping_shaping_policy,  # noqa: F401
    net_route,  # noqa: F401
    net_route_domain,  # noqa: F401
    net_router_advertisement,  # noqa: F401
    net_routing_access_list,  # noqa: F401
    net_routing_bfd,  # noqa: F401
    net_routing_bgp,  # noqa: F401
    net_routing_community_list,  # noqa: F401
    net_routing_debug,  # noqa: F401
    net_routing_extcommunity_list,  # noqa: F401
    net_routing_prefix_list,  # noqa: F401
    net_routing_profile_bgp,  # noqa: F401
    net_routing_route_map,  # noqa: F401
    net_rst_cause,  # noqa: F401
    net_self,  # noqa: F401
    net_self_allow,  # noqa: F401
    net_service_policy,  # noqa: F401
    net_sfc_chain,  # noqa: F401
    net_sfc_hop,  # noqa: F401
    net_sfc_sf,  # noqa: F401
    net_sfc_stats,  # noqa: F401
    net_stp,  # noqa: F401
    net_stp_globals,  # noqa: F401
    net_timer_policy,  # noqa: F401
    net_trunk,  # noqa: F401
    net_tunnels_endpoint,  # noqa: F401
    net_tunnels_etherip,  # noqa: F401
    net_tunnels_fec,  # noqa: F401
    net_tunnels_fec_stat,  # noqa: F401
    net_tunnels_geneve,  # noqa: F401
    net_tunnels_gre,  # noqa: F401
    net_tunnels_ipip,  # noqa: F401
    net_tunnels_ipsec,  # noqa: F401
    net_tunnels_lw4o6,  # noqa: F401
    net_tunnels_map,  # noqa: F401
    net_tunnels_ppp,  # noqa: F401
    net_tunnels_tcp_forward,  # noqa: F401
    net_tunnels_tunnel,  # noqa: F401
    net_tunnels_v6rd,  # noqa: F401
    net_tunnels_vxlan,  # noqa: F401
    net_tunnels_wccp,  # noqa: F401
    net_vlan,  # noqa: F401
    net_vlan_allowed,  # noqa: F401
    net_vlan_group,  # noqa: F401
    net_wccp,  # noqa: F401
    security_analytics_settings,  # noqa: F401
    security_anti_fraud_engine_update,  # noqa: F401
    security_anti_fraud_profile,  # noqa: F401
    security_anti_fraud_signatures_update,  # noqa: F401
    security_blacklist_publisher_all_blacklist_publisher,  # noqa: F401
    security_blacklist_publisher_blacklist_publisher_stats,  # noqa: F401
    security_blacklist_publisher_by_addr,  # noqa: F401
    security_blacklist_publisher_by_category,  # noqa: F401
    security_blacklist_publisher_category,  # noqa: F401
    security_blacklist_publisher_profile,  # noqa: F401
    security_bot_defense_anomaly,  # noqa: F401
    security_bot_defense_anomaly_category,  # noqa: F401
    security_bot_defense_class,  # noqa: F401
    security_bot_defense_micro_service,  # noqa: F401
    security_bot_defense_profile,  # noqa: F401
    security_bot_defense_signature,  # noqa: F401
    security_bot_defense_signature_category,  # noqa: F401
    security_bot_defense_template,  # noqa: F401
    security_cloud_services_cmd,  # noqa: F401
    security_cloud_services_connector,  # noqa: F401
    security_datasync_background_tasks,  # noqa: F401
    security_datasync_device_stats,  # noqa: F401
    security_datasync_global_profile,  # noqa: F401
    security_datasync_local_profile,  # noqa: F401
    security_debug_drop_redirect_stats,  # noqa: F401
    security_debug_matcher,  # noqa: F401
    security_debug_register,  # noqa: F401
    security_device_device_context,  # noqa: F401
    security_device_id_attribute,  # noqa: F401
    security_dos_auto_thresholds_heavy_urls,  # noqa: F401
    security_dos_auto_thresholds_stress_based,  # noqa: F401
    security_dos_auto_thresholds_top_device_ids,  # noqa: F401
    security_dos_auto_thresholds_top_geolocations,  # noqa: F401
    security_dos_auto_thresholds_top_source_ips,  # noqa: F401
    security_dos_auto_thresholds_top_urls,  # noqa: F401
    security_dos_auto_thresholds_tps_based,  # noqa: F401
    security_dos_autodos_file_object,  # noqa: F401
    security_dos_behavioral_signature,  # noqa: F401
    security_dos_bot_signature,  # noqa: F401
    security_dos_bot_signature_category,  # noqa: F401
    security_dos_device_config,  # noqa: F401
    security_dos_dns_nxdomain_stat,  # noqa: F401
    security_dos_dos_signature,  # noqa: F401
    security_dos_dynamic_signatures,  # noqa: F401
    security_dos_ip_uncommon_protolist,  # noqa: F401
    security_dos_l4bdos_file_object,  # noqa: F401
    security_dos_network_whitelist,  # noqa: F401
    security_dos_profile,  # noqa: F401
    security_dos_spva_stats,  # noqa: F401
    security_dos_stress_stats,  # noqa: F401
    security_dos_udp_portlist,  # noqa: F401
    security_dos_virtual,  # noqa: F401
    security_firewall_address_list,  # noqa: F401
    security_firewall_config_change_log,  # noqa: F401
    security_firewall_container_stat,  # noqa: F401
    security_firewall_context_stat,  # noqa: F401
    security_firewall_current_state,  # noqa: F401
    security_firewall_fqdn_entity,  # noqa: F401
    security_firewall_fqdn_info,  # noqa: F401
    security_firewall_global_fqdn_policy,  # noqa: F401
    security_firewall_global_rules,  # noqa: F401
    security_firewall_ipi_category_info,  # noqa: F401
    security_firewall_management_ip_rules,  # noqa: F401
    security_firewall_matching_rule,  # noqa: F401
    security_firewall_on_demand_compilation,  # noqa: F401
    security_firewall_on_demand_rule_deploy,  # noqa: F401
    security_firewall_policy,  # noqa: F401
    security_firewall_port_list,  # noqa: F401
    security_firewall_port_misuse_policy,  # noqa: F401
    security_firewall_rule_list,  # noqa: F401
    security_firewall_rule_stat,  # noqa: F401
    security_firewall_schedule,  # noqa: F401
    security_firewall_user_domain,  # noqa: F401
    security_firewall_user_list,  # noqa: F401
    security_firewall_uuid_default_autogenerate,  # noqa: F401
    security_flowspec_route_injector_flowspec_advertised_route_info,  # noqa: F401
    security_flowspec_route_injector_profile,  # noqa: F401
    security_http_file_type,  # noqa: F401
    security_http_mandatory_header,  # noqa: F401
    security_http_profile,  # noqa: F401
    security_ip_intelligence_blacklist_category,  # noqa: F401
    security_ip_intelligence_feed_list,  # noqa: F401
    security_ip_intelligence_global_policy,  # noqa: F401
    security_ip_intelligence_info,  # noqa: F401
    security_ip_intelligence_policy,  # noqa: F401
    security_log_antifraud_storage_field,  # noqa: F401
    security_log_network_storage_field,  # noqa: F401
    security_log_profile,  # noqa: F401
    security_log_protocol_dns_storage_field,  # noqa: F401
    security_log_protocol_sip_storage_field,  # noqa: F401
    security_log_remote_format,  # noqa: F401
    security_log_storage_field,  # noqa: F401
    security_malicious_sources_device_ids,  # noqa: F401
    security_malicious_sources_ip_addresses,  # noqa: F401
    security_nat_destination_translation,  # noqa: F401
    security_nat_policy,  # noqa: F401
    security_nat_source_translation,  # noqa: F401
    security_packet_filter_default_rules,  # noqa: F401
    security_packet_filter_policy,  # noqa: F401
    security_packet_filter_rule_stat,  # noqa: F401
    security_presentation_tmui_netflow_details,  # noqa: F401
    security_presentation_tmui_netflow_list,  # noqa: F401
    security_presentation_tmui_signature_details,  # noqa: F401
    security_presentation_tmui_signature_list,  # noqa: F401
    security_protected_servers_netflow_tmc_stat,  # noqa: F401
    security_protected_zone,  # noqa: F401
    security_protocol_inspection_auto_update_settings,  # noqa: F401
    security_protocol_inspection_auto_update_status,  # noqa: F401
    security_protocol_inspection_common_config,  # noqa: F401
    security_protocol_inspection_compliance,  # noqa: F401
    security_protocol_inspection_compliance_enums,  # noqa: F401
    security_protocol_inspection_learning_stats,  # noqa: F401
    security_protocol_inspection_learning_suggestions,  # noqa: F401
    security_protocol_inspection_profile,  # noqa: F401
    security_protocol_inspection_profile_status,  # noqa: F401
    security_protocol_inspection_service,  # noqa: F401
    security_protocol_inspection_signature,  # noqa: F401
    security_protocol_inspection_staging,  # noqa: F401
    security_protocol_inspection_system,  # noqa: F401
    security_protocol_inspection_updates,  # noqa: F401
    security_protocol_inspection_virtual_servers,  # noqa: F401
    security_scrubber_dwbl_scrubber_category_stats,  # noqa: F401
    security_scrubber_dwbl_scrubber_stat,  # noqa: F401
    security_scrubber_profile,  # noqa: F401
    security_scrubber_unredirect,  # noqa: F401
    security_ssh_ciphers,  # noqa: F401
    security_ssh_profile,  # noqa: F401
    security_zone,  # noqa: F401
    sys_air_filter_reset,  # noqa: F401
    sys_alert_lcd,  # noqa: F401
    sys_aom,  # noqa: F401
    sys_appiq_config,  # noqa: F401
    sys_application_apl_script,  # noqa: F401
    sys_application_custom_stat,  # noqa: F401
    sys_application_service,  # noqa: F401
    sys_application_template,  # noqa: F401
    sys_autoscale_group,  # noqa: F401
    sys_availability,  # noqa: F401
    sys_clock,  # noqa: F401
    sys_cluster,  # noqa: F401
    sys_config,  # noqa: F401
    sys_config_diff,  # noqa: F401
    sys_connection,  # noqa: F401
    sys_console,  # noqa: F401
    sys_core,  # noqa: F401
    sys_cpu,  # noqa: F401
    sys_crypto_acceleration_strategy,  # noqa: F401
    sys_crypto_allow_key_export,  # noqa: F401
    sys_crypto_ca_bundle_manager,  # noqa: F401
    sys_crypto_cert,  # noqa: F401
    sys_crypto_cert_order_manager,  # noqa: F401
    sys_crypto_cert_validation_response_ocsp,  # noqa: F401
    sys_crypto_cert_validator_crl,  # noqa: F401
    sys_crypto_cert_validator_ocsp,  # noqa: F401
    sys_crypto_check_cert,  # noqa: F401
    sys_crypto_client,  # noqa: F401
    sys_crypto_crl,  # noqa: F401
    sys_crypto_csr,  # noqa: F401
    sys_crypto_encrypted_attributes,  # noqa: F401
    sys_crypto_fips_by_handle,  # noqa: F401
    sys_crypto_fips_external_hsm,  # noqa: F401
    sys_crypto_fips_key,  # noqa: F401
    sys_crypto_key,  # noqa: F401
    sys_crypto_master_key,  # noqa: F401
    sys_crypto_pkcs12,  # noqa: F401
    sys_crypto_server,  # noqa: F401
    sys_daemon_ha,  # noqa: F401
    sys_daemon_log_settings_clusterd,  # noqa: F401
    sys_daemon_log_settings_csyncd,  # noqa: F401
    sys_daemon_log_settings_icr_eventd,  # noqa: F401
    sys_daemon_log_settings_icrd,  # noqa: F401
    sys_daemon_log_settings_lind,  # noqa: F401
    sys_daemon_log_settings_mcpd,  # noqa: F401
    sys_daemon_log_settings_tmm,  # noqa: F401
    sys_datastor,  # noqa: F401
    sys_db,  # noqa: F401
    sys_default_config,  # noqa: F401
    sys_diags_ihealth,  # noqa: F401
    sys_diags_ihealth_request,  # noqa: F401
    sys_diags_ihealth_result,  # noqa: F401
    sys_disk_application_volume,  # noqa: F401
    sys_disk_directory,  # noqa: F401
    sys_disk_logical_disk,  # noqa: F401
    sys_dns,  # noqa: F401
    sys_dynad_instrumentation,  # noqa: F401
    sys_dynad_key,  # noqa: F401
    sys_dynad_rpm,  # noqa: F401
    sys_dynad_settings,  # noqa: F401
    sys_dynad_status,  # noqa: F401
    sys_ecm_config,  # noqa: F401
    sys_ecm_register,  # noqa: F401
    sys_failover,  # noqa: F401
    sys_feature_module,  # noqa: F401
    sys_file_apache_ssl_cert,  # noqa: F401
    sys_file_browser_capabilities_db,  # noqa: F401
    sys_file_data_group,  # noqa: F401
    sys_file_device_capabilities_db,  # noqa: F401
    sys_file_external_monitor,  # noqa: F401
    sys_file_ifile,  # noqa: F401
    sys_file_lwtunneltbl,  # noqa: F401
    sys_file_rewrite_rule,  # noqa: F401
    sys_file_ssl_cert,  # noqa: F401
    sys_file_ssl_crl,  # noqa: F401
    sys_file_ssl_key,  # noqa: F401
    sys_fix_connection,  # noqa: F401
    sys_folder,  # noqa: F401
    sys_fpga_firmware_config,  # noqa: F401
    sys_fpga_info,  # noqa: F401
    sys_fpga_turboflex_profile,  # noqa: F401
    sys_geoip,  # noqa: F401
    sys_global_settings,  # noqa: F401
    sys_ha_group,  # noqa: F401
    sys_ha_status,  # noqa: F401
    sys_hardware,  # noqa: F401
    sys_host_info,  # noqa: F401
    sys_httpd,  # noqa: F401
    sys_hypervisor_info,  # noqa: F401
    sys_iapp_restricted_key,  # noqa: F401
    sys_iapprestricted_key,  # noqa: F401
    sys_icall_event,  # noqa: F401
    sys_icall_handler_periodic,  # noqa: F401
    sys_icall_handler_perpetual,  # noqa: F401
    sys_icall_handler_triggered,  # noqa: F401
    sys_icall_istats_trigger,  # noqa: F401
    sys_icall_publisher,  # noqa: F401
    sys_icall_script,  # noqa: F401
    sys_icmp_stat,  # noqa: F401
    sys_icontrol_soap,  # noqa: F401
    sys_integrity_status_check,  # noqa: F401
    sys_internal_proxy,  # noqa: F401
    sys_ip_address,  # noqa: F401
    sys_ip_stat,  # noqa: F401
    sys_ipfix_destination,  # noqa: F401
    sys_ipfix_element,  # noqa: F401
    sys_ipfix_irules,  # noqa: F401
    sys_iprep_status,  # noqa: F401
    sys_license,  # noqa: F401
    sys_log,  # noqa: F401
    sys_log_config_destination_alertd,  # noqa: F401
    sys_log_config_destination_arcsight,  # noqa: F401
    sys_log_config_destination_ipfix,  # noqa: F401
    sys_log_config_destination_local_database,  # noqa: F401
    sys_log_config_destination_local_syslog,  # noqa: F401
    sys_log_config_destination_management_port,  # noqa: F401
    sys_log_config_destination_remote_high_speed_log,  # noqa: F401
    sys_log_config_destination_remote_syslog,  # noqa: F401
    sys_log_config_destination_splunk,  # noqa: F401
    sys_log_config_filter,  # noqa: F401
    sys_log_config_publisher,  # noqa: F401
    sys_log_rotate,  # noqa: F401
    sys_mac_address,  # noqa: F401
    sys_management_dhcp,  # noqa: F401
    sys_management_ip,  # noqa: F401
    sys_management_ovsdb,  # noqa: F401
    sys_management_proxy_config,  # noqa: F401
    sys_management_route,  # noqa: F401
    sys_mcp_state,  # noqa: F401
    sys_memory,  # noqa: F401
    sys_nethsm_async_queue_stat,  # noqa: F401
    sys_nethsm_pkcs11d_stat,  # noqa: F401
    sys_nethsm_sync_queue_stat,  # noqa: F401
    sys_ntp,  # noqa: F401
    sys_outbound_smtp,  # noqa: F401
    sys_performance_all_stats,  # noqa: F401
    sys_performance_connections,  # noqa: F401
    sys_performance_dnsexpress,  # noqa: F401
    sys_performance_dnssec,  # noqa: F401
    sys_performance_gtm,  # noqa: F401
    sys_performance_ramcache,  # noqa: F401
    sys_performance_system,  # noqa: F401
    sys_performance_throughput,  # noqa: F401
    sys_pfman_consumer,  # noqa: F401
    sys_pfman_device,  # noqa: F401
    sys_proc_info,  # noqa: F401
    sys_provision,  # noqa: F401
    sys_pva_traffic,  # noqa: F401
    sys_raid_array,  # noqa: F401
    sys_raid_bay,  # noqa: F401
    sys_raid_disk,  # noqa: F401
    sys_ready,  # noqa: F401
    sys_scriptd,  # noqa: F401
    sys_service,  # noqa: F401
    sys_sflow_data_source_http,  # noqa: F401
    sys_sflow_data_source_interface,  # noqa: F401
    sys_sflow_data_source_system,  # noqa: F401
    sys_sflow_data_source_vlan,  # noqa: F401
    sys_sflow_global_settings_http,  # noqa: F401
    sys_sflow_global_settings_interface,  # noqa: F401
    sys_sflow_global_settings_system,  # noqa: F401
    sys_sflow_global_settings_vlan,  # noqa: F401
    sys_sflow_receiver,  # noqa: F401
    sys_smtp_server,  # noqa: F401
    sys_snmp,  # noqa: F401
    sys_software_block_device_hotfix,  # noqa: F401
    sys_software_block_device_image,  # noqa: F401
    sys_software_hotfix,  # noqa: F401
    sys_software_image,  # noqa: F401
    sys_software_signature,  # noqa: F401
    sys_software_status,  # noqa: F401
    sys_software_update,  # noqa: F401
    sys_software_update_status,  # noqa: F401
    sys_software_volume,  # noqa: F401
    sys_sshd,  # noqa: F401
    sys_state_mirroring,  # noqa: F401
    sys_sync_sys_files,  # noqa: F401
    sys_syslog,  # noqa: F401
    sys_tmm_info,  # noqa: F401
    sys_tmm_traffic,  # noqa: F401
    sys_traffic,  # noqa: F401
    sys_turboflex_features,  # noqa: F401
    sys_turboflex_profile_all,  # noqa: F401
    sys_turboflex_profile_config,  # noqa: F401
    sys_turboflex_profile_feature,  # noqa: F401
    sys_turboflex_warning,  # noqa: F401
    sys_ucs,  # noqa: F401
    sys_url_db_download_result,  # noqa: F401
    sys_url_db_download_schedule,  # noqa: F401
    sys_url_db_url_category,  # noqa: F401
    sys_version,  # noqa: F401
)
from ._base import _REGISTRY


def bigip_object_specs() -> tuple:
    return tuple(_REGISTRY)


OBJECT_SPECS = bigip_object_specs()

__all__ = ["OBJECT_SPECS", "bigip_object_specs"]
