from __future__ import annotations

from ..models import (
    BigipObjectKindSpec,
    BigipObjectSpec,
    BigipPropertySpec,
)
from ._base import register


@register
def register_spec() -> BigipObjectSpec:
    return BigipObjectSpec(
        kind_spec=BigipObjectKindSpec(
            "apm_profile_connectivity",
            module="apm",
            object_types=("profile connectivity",),
        ),
        header_types=(("apm", "profile connectivity"),),
        properties=(
            BigipPropertySpec(
                name="adaptive-compression",
                value_type="enum",
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(name="app-service", value_type="string", allow_none=True),
            BigipPropertySpec(
                name="citrix-client-bundle",
                value_type="reference",
                references=("apm_resource_remote_desktop_citrix_client_bundle",),
            ),
            BigipPropertySpec(
                name="client-policy",
                value_type="list",
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="android-ec",
                value_type="unknown",
                in_sections=("client-policy",),
            ),
            BigipPropertySpec(
                name="device-lock-complexity",
                value_type="enum",
                in_sections=("client-policy", "android-ec"),
                allow_none=True,
                enum_values=("high", "low", "medium", "none"),
            ),
            BigipPropertySpec(
                name="device-lock-method",
                value_type="enum",
                in_sections=("client-policy", "android-ec"),
                enum_values=("alphabetic", "alphanumeric", "any", "numeric"),
            ),
            BigipPropertySpec(
                name="enable-mobilesafe",
                value_type="enum",
                in_sections=("client-policy", "android-ec"),
                enum_values=("false", "true"),
            ),
            BigipPropertySpec(
                name="enforce-device-lock",
                value_type="enum",
                in_sections=("client-policy", "android-ec"),
                enum_values=("false", "true"),
            ),
            BigipPropertySpec(
                name="enforce-logon-mode",
                value_type="enum",
                in_sections=("client-policy", "android-ec"),
                enum_values=("false", "true"),
            ),
            BigipPropertySpec(
                name="logon-mode",
                value_type="enum",
                in_sections=("client-policy", "android-ec"),
                enum_values=("native", "web"),
            ),
            BigipPropertySpec(
                name="max-inactivity-time",
                value_type="integer",
                in_sections=("client-policy", "android-ec"),
            ),
            BigipPropertySpec(
                name="min-passcode-length",
                value_type="integer",
                in_sections=("client-policy", "android-ec"),
            ),
            BigipPropertySpec(
                name="require-device-auth",
                value_type="enum",
                in_sections=("client-policy", "android-ec"),
                enum_values=("false", "true"),
            ),
            BigipPropertySpec(
                name="save-password",
                value_type="enum",
                in_sections=("client-policy", "android-ec"),
                enum_values=("false", "true"),
            ),
            BigipPropertySpec(
                name="save-password-method",
                value_type="enum",
                in_sections=("client-policy", "android-ec"),
                enum_values=("disk", "memory"),
            ),
            BigipPropertySpec(
                name="save-password-timeout",
                value_type="integer",
                in_sections=("client-policy", "android-ec"),
            ),
            BigipPropertySpec(
                name="android-ep",
                value_type="unknown",
                in_sections=("client-policy",),
            ),
            BigipPropertySpec(
                name="device-lock-method",
                value_type="enum",
                in_sections=("client-policy", "android-ep"),
                enum_values=("alphabetic", "alphanumeric", "any", "numeric"),
            ),
            BigipPropertySpec(
                name="enable-mobilesafe",
                value_type="enum",
                in_sections=("client-policy", "android-ep"),
                enum_values=("false", "true"),
            ),
            BigipPropertySpec(
                name="enforce-device-lock",
                value_type="enum",
                in_sections=("client-policy", "android-ep"),
                enum_values=("false", "true"),
            ),
            BigipPropertySpec(
                name="enforce-logon-mode",
                value_type="enum",
                in_sections=("client-policy", "android-ep"),
                enum_values=("false", "true"),
            ),
            BigipPropertySpec(
                name="logon-mode",
                value_type="enum",
                in_sections=("client-policy", "android-ep"),
                enum_values=("native", "web"),
            ),
            BigipPropertySpec(
                name="max-inactivity-time",
                value_type="integer",
                in_sections=("client-policy", "android-ep"),
            ),
            BigipPropertySpec(
                name="min-passcode-length",
                value_type="integer",
                in_sections=("client-policy", "android-ep"),
            ),
            BigipPropertySpec(
                name="save-password",
                value_type="enum",
                in_sections=("client-policy", "android-ep"),
                enum_values=("false", "true"),
            ),
            BigipPropertySpec(
                name="save-password-method",
                value_type="enum",
                in_sections=("client-policy", "android-ep"),
                enum_values=("disk", "memory"),
            ),
            BigipPropertySpec(
                name="save-password-timeout",
                value_type="integer",
                in_sections=("client-policy", "android-ep"),
            ),
            BigipPropertySpec(
                name="chromeos-ec",
                value_type="unknown",
                in_sections=("client-policy",),
            ),
            BigipPropertySpec(
                name="enforce-logon-mode",
                value_type="enum",
                in_sections=("client-policy", "chromeos-ec"),
                enum_values=("false", "true"),
            ),
            BigipPropertySpec(
                name="logon-mode",
                value_type="enum",
                in_sections=("client-policy", "chromeos-ec"),
                enum_values=("native", "web"),
            ),
            BigipPropertySpec(
                name="save-password",
                value_type="enum",
                in_sections=("client-policy", "chromeos-ec"),
                enum_values=("false", "true"),
            ),
            BigipPropertySpec(
                name="save-password-method",
                value_type="enum",
                in_sections=("client-policy", "chromeos-ec"),
                enum_values=("disk", "memory"),
            ),
            BigipPropertySpec(
                name="save-password-timeout",
                value_type="integer",
                in_sections=("client-policy", "chromeos-ec"),
            ),
            BigipPropertySpec(name="ec", value_type="unknown", in_sections=("client-policy",)),
            BigipPropertySpec(
                name="component-update",
                value_type="enum",
                in_sections=("client-policy", "ec"),
                enum_values=("no", "prompt", "yes"),
            ),
            BigipPropertySpec(
                name="location-dns",
                value_type="list",
                in_sections=("client-policy", "ec"),
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="reuse-winlogon-creds",
                value_type="enum",
                in_sections=("client-policy", "ec"),
                enum_values=("false", "true"),
            ),
            BigipPropertySpec(
                name="reuse-winlogon-session",
                value_type="enum",
                in_sections=("client-policy", "ec"),
                enum_values=("false", "true"),
            ),
            BigipPropertySpec(
                name="save-password",
                value_type="enum",
                in_sections=("client-policy", "ec"),
                enum_values=("false", "true"),
            ),
            BigipPropertySpec(
                name="save-password-method",
                value_type="enum",
                in_sections=("client-policy", "ec"),
                enum_values=("disk", "memory"),
            ),
            BigipPropertySpec(
                name="save-password-timeout",
                value_type="integer",
                in_sections=("client-policy", "ec"),
            ),
            BigipPropertySpec(
                name="save-servers-on-exit",
                value_type="enum",
                in_sections=("client-policy", "ec"),
                enum_values=("false", "true"),
            ),
            BigipPropertySpec(name="ios-ec", value_type="unknown", in_sections=("client-policy",)),
            BigipPropertySpec(
                name="enable-mobilesafe",
                value_type="enum",
                in_sections=("client-policy", "ios-ec"),
                enum_values=("false", "true"),
            ),
            BigipPropertySpec(
                name="enforce-logon-mode",
                value_type="enum",
                in_sections=("client-policy", "ios-ec"),
                enum_values=("false", "true"),
            ),
            BigipPropertySpec(
                name="logon-mode",
                value_type="enum",
                in_sections=("client-policy", "ios-ec"),
                enum_values=("native", "web"),
            ),
            BigipPropertySpec(
                name="require-device-auth",
                value_type="enum",
                in_sections=("client-policy", "ios-ec"),
                enum_values=("false", "true"),
            ),
            BigipPropertySpec(
                name="save-password",
                value_type="enum",
                in_sections=("client-policy", "ios-ec"),
                enum_values=("false", "true"),
            ),
            BigipPropertySpec(
                name="save-password-method",
                value_type="enum",
                in_sections=("client-policy", "ios-ec"),
                enum_values=("disk", "memory"),
            ),
            BigipPropertySpec(
                name="save-password-timeout",
                value_type="integer",
                in_sections=("client-policy", "ios-ec"),
            ),
            BigipPropertySpec(
                name="vod-disconnect-timeout",
                value_type="integer",
                in_sections=("client-policy", "ios-ec"),
            ),
            BigipPropertySpec(name="ios-ep", value_type="unknown", in_sections=("client-policy",)),
            BigipPropertySpec(
                name="enable-mobilesafe",
                value_type="enum",
                in_sections=("client-policy", "ios-ep"),
                enum_values=("false", "true"),
            ),
            BigipPropertySpec(
                name="enforce-logon-mode",
                value_type="enum",
                in_sections=("client-policy", "ios-ep"),
                enum_values=("false", "true"),
            ),
            BigipPropertySpec(
                name="enforce-pin-lock",
                value_type="enum",
                in_sections=("client-policy", "ios-ep"),
                enum_values=("false", "true"),
            ),
            BigipPropertySpec(
                name="logon-mode",
                value_type="enum",
                in_sections=("client-policy", "ios-ep"),
                enum_values=("native", "web"),
            ),
            BigipPropertySpec(
                name="max-grace-period",
                value_type="integer",
                in_sections=("client-policy", "ios-ep"),
            ),
            BigipPropertySpec(
                name="save-password",
                value_type="enum",
                in_sections=("client-policy", "ios-ep"),
                enum_values=("false", "true"),
            ),
            BigipPropertySpec(
                name="save-password-method",
                value_type="enum",
                in_sections=("client-policy", "ios-ep"),
                enum_values=("disk", "memory"),
            ),
            BigipPropertySpec(
                name="save-password-timeout",
                value_type="integer",
                in_sections=("client-policy", "ios-ep"),
            ),
            BigipPropertySpec(
                name="macos-ec",
                value_type="unknown",
                in_sections=("client-policy",),
            ),
            BigipPropertySpec(
                name="component-update",
                value_type="enum",
                in_sections=("client-policy", "macos-ec"),
                enum_values=("no", "prompt", "yes"),
            ),
            BigipPropertySpec(
                name="enforce-logon-mode",
                value_type="enum",
                in_sections=("client-policy", "macos-ec"),
                enum_values=("false", "true"),
            ),
            BigipPropertySpec(
                name="location-dns",
                value_type="list",
                in_sections=("client-policy", "macos-ec"),
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="logon-mode",
                value_type="enum",
                in_sections=("client-policy", "macos-ec"),
                enum_values=("native", "web"),
            ),
            BigipPropertySpec(
                name="save-password",
                value_type="enum",
                in_sections=("client-policy", "macos-ec"),
                enum_values=("false", "true"),
            ),
            BigipPropertySpec(
                name="save-password-method",
                value_type="enum",
                in_sections=("client-policy", "macos-ec"),
                enum_values=("disk", "memory"),
            ),
            BigipPropertySpec(
                name="save-password-timeout",
                value_type="integer",
                in_sections=("client-policy", "macos-ec"),
            ),
            BigipPropertySpec(name="oauth", value_type="unknown", in_sections=("client-policy",)),
            BigipPropertySpec(
                name="client-id",
                value_type="string",
                in_sections=("client-policy", "oauth"),
            ),
            BigipPropertySpec(
                name="client-secret",
                value_type="string",
                in_sections=("client-policy", "oauth"),
            ),
            BigipPropertySpec(
                name="done-uri",
                value_type="string",
                in_sections=("client-policy", "oauth"),
            ),
            BigipPropertySpec(
                name="provider-name",
                value_type="reference",
                in_sections=("client-policy", "oauth"),
            ),
            BigipPropertySpec(
                name="scopes",
                value_type="string",
                in_sections=("client-policy", "oauth"),
            ),
            BigipPropertySpec(name="servers", value_type="list", in_sections=("client-policy",)),
            BigipPropertySpec(
                name="alias",
                value_type="string",
                in_sections=("client-policy", "servers"),
                allow_none=True,
            ),
            BigipPropertySpec(
                name="host",
                value_type="string",
                in_sections=("client-policy", "servers"),
            ),
            BigipPropertySpec(name="compress-buffer-size", value_type="integer"),
            BigipPropertySpec(
                name="compress-cpu-saver",
                value_type="enum",
                enum_values=("false", "true"),
            ),
            BigipPropertySpec(name="compress-cpu-saver-high", value_type="integer"),
            BigipPropertySpec(name="compress-cpu-saver-low", value_type="integer"),
            BigipPropertySpec(name="compress-gzip-level", value_type="integer"),
            BigipPropertySpec(name="compress-gzip-memlevel", value_type="integer"),
            BigipPropertySpec(name="compress-gzip-window-size", value_type="integer"),
            BigipPropertySpec(
                name="compress-ingress",
                value_type="enum",
                enum_values=("false", "true"),
            ),
            BigipPropertySpec(
                name="compress-preferred-method",
                value_type="string",
                allow_none=True,
            ),
            BigipPropertySpec(
                name="compression",
                value_type="enum",
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(name="compression-codecs", value_type="string", allow_none=True),
            BigipPropertySpec(name="customization-group", value_type="string", allow_none=True),
            BigipPropertySpec(
                name="defaults",
                value_type="reference",
                allow_none=True,
                references=(
                    "ltm_default_node_monitor",
                    "security_firewall_uuid_default_autogenerate",
                    "security_packet_filter_default_rules",
                    "sys_default_config",
                ),
            ),
            BigipPropertySpec(name="deflate-compression-level", value_type="integer"),
            BigipPropertySpec(name="description", value_type="string", allow_none=True),
            BigipPropertySpec(
                name="location-specific",
                value_type="enum",
                enum_values=("false", "true"),
            ),
            BigipPropertySpec(name="tunnel-name", value_type="string", allow_none=True),
        ),
    )
