from __future__ import annotations

from ..models import (
    BigipObjectKindSpec,
    BigipObjectSpec,
    BigipPropertySpec,
)
from ._base import register


@register
def register_spec() -> BigipObjectSpec:
    return BigipObjectSpec(
        kind_spec=BigipObjectKindSpec(
            "apm_policy_agent_http_header_modify",
            module="apm",
            object_types=("policy agent http-header-modify",),
        ),
        header_types=(("apm", "policy agent http-header-modify"),),
        properties=(
            BigipPropertySpec(
                name="app-service",
                value_type="string",
                allow_none=True,
                default="none",
            ),
            BigipPropertySpec(
                name="cookie-entries",
                value_type="list",
                allow_none=True,
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
                block=(
                    BigipPropertySpec(
                        name="app-service",
                        value_type="string",
                        in_sections=("cookie-entries",),
                        allow_none=True,
                        default="none",
                    ),
                    BigipPropertySpec(
                        name="cookie-name",
                        value_type="string",
                        in_sections=("cookie-entries",),
                        required=True,
                    ),
                    BigipPropertySpec(
                        name="cookie-operation",
                        value_type="enum",
                        in_sections=("cookie-entries",),
                        enum_values=("cookie-delete", "cookie-update"),
                    ),
                    BigipPropertySpec(
                        name="cookie-value",
                        value_type="string",
                        in_sections=("cookie-entries",),
                        required=True,
                    ),
                ),
            ),
            BigipPropertySpec(
                name="app-service",
                value_type="string",
                in_sections=("cookie-entries",),
                allow_none=True,
                default="none",
            ),
            BigipPropertySpec(
                name="cookie-name",
                value_type="string",
                in_sections=("cookie-entries",),
                required=True,
            ),
            BigipPropertySpec(
                name="cookie-operation",
                value_type="enum",
                in_sections=("cookie-entries",),
                enum_values=("cookie-delete", "cookie-update"),
            ),
            BigipPropertySpec(
                name="cookie-value",
                value_type="string",
                in_sections=("cookie-entries",),
                required=True,
            ),
            BigipPropertySpec(
                name="header-entries",
                value_type="list",
                allow_none=True,
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
                block=(
                    BigipPropertySpec(
                        name="app-service",
                        value_type="string",
                        in_sections=("header-entries",),
                        allow_none=True,
                        default="none",
                    ),
                    BigipPropertySpec(
                        name="header-delimiter",
                        value_type="string",
                        in_sections=("header-entries",),
                    ),
                    BigipPropertySpec(
                        name="header-name",
                        value_type="string",
                        in_sections=("header-entries",),
                        required=True,
                    ),
                    BigipPropertySpec(
                        name="header-operation",
                        value_type="enum",
                        in_sections=("header-entries",),
                        enum_values=(
                            "header-append",
                            "header-insert",
                            "header-remove",
                            "header-replace",
                        ),
                    ),
                    BigipPropertySpec(
                        name="header-value",
                        value_type="string",
                        in_sections=("header-entries",),
                        required=True,
                    ),
                ),
            ),
            BigipPropertySpec(
                name="app-service",
                value_type="string",
                in_sections=("header-entries",),
                allow_none=True,
                default="none",
            ),
            BigipPropertySpec(
                name="header-delimiter",
                value_type="string",
                in_sections=("header-entries",),
            ),
            BigipPropertySpec(
                name="header-name",
                value_type="string",
                in_sections=("header-entries",),
                required=True,
            ),
            BigipPropertySpec(
                name="header-operation",
                value_type="enum",
                in_sections=("header-entries",),
                enum_values=("header-append", "header-insert", "header-remove", "header-replace"),
            ),
            BigipPropertySpec(
                name="header-value",
                value_type="string",
                in_sections=("header-entries",),
                required=True,
            ),
        ),
    )
