from __future__ import annotations

from ..models import (
    BigipObjectKindSpec,
    BigipObjectSpec,
    BigipPropertySpec,
)
from ._base import register


@register
def register_spec() -> BigipObjectSpec:
    return BigipObjectSpec(
        kind_spec=BigipObjectKindSpec(
            "auth_remote_role",
            module="auth",
            object_types=("remote-role",),
        ),
        header_types=(("auth", "remote-role"),),
        properties=(
            BigipPropertySpec(name="description", value_type="string"),
            BigipPropertySpec(
                name="role-info",
                value_type="list",
                allow_none=True,
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
                block=(
                    BigipPropertySpec(
                        name="attribute",
                        value_type="string",
                        in_sections=("role-info",),
                        required=True,
                    ),
                    BigipPropertySpec(
                        name="console",
                        value_type="enum",
                        in_sections=("role-info",),
                        enum_values=("disabled", "tmsh"),
                        default="disabled",
                    ),
                    BigipPropertySpec(
                        name="deny",
                        value_type="enum",
                        in_sections=("role-info",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                        default="disabled",
                    ),
                    BigipPropertySpec(
                        name="description",
                        value_type="string",
                        in_sections=("role-info",),
                    ),
                    BigipPropertySpec(
                        name="line-order",
                        value_type="integer",
                        in_sections=("role-info",),
                        required=True,
                    ),
                    BigipPropertySpec(
                        name="role",
                        value_type="enum",
                        in_sections=("role-info",),
                        enum_values=(
                            "acceleration-policy-editor",
                            "admin",
                            "application-editor",
                            "auditor",
                            "certificate-manager",
                            "firewall-manager",
                            "fraud-protection-manager",
                            "guest",
                            "irule-manager",
                            "log-manager",
                            "manager",
                            "no-access",
                            "operator",
                            "resource-admin",
                            "user-manager",
                            "web-application-security-administrator",
                            "web-application-security-editor",
                            "web-application-security-operations-administrator",
                        ),
                        default="no-access",
                    ),
                    BigipPropertySpec(
                        name="user-partition",
                        value_type="reference",
                        in_sections=("role-info",),
                        required=True,
                        default="Common",
                    ),
                ),
            ),
            BigipPropertySpec(
                name="attribute",
                value_type="string",
                in_sections=("role-info",),
                required=True,
            ),
            BigipPropertySpec(
                name="console",
                value_type="enum",
                in_sections=("role-info",),
                enum_values=("disabled", "tmsh"),
                default="disabled",
            ),
            BigipPropertySpec(
                name="deny",
                value_type="enum",
                in_sections=("role-info",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
                default="disabled",
            ),
            BigipPropertySpec(name="description", value_type="string", in_sections=("role-info",)),
            BigipPropertySpec(
                name="line-order",
                value_type="integer",
                in_sections=("role-info",),
                required=True,
            ),
            BigipPropertySpec(
                name="role",
                value_type="enum",
                in_sections=("role-info",),
                enum_values=(
                    "acceleration-policy-editor",
                    "admin",
                    "application-editor",
                    "auditor",
                    "certificate-manager",
                    "firewall-manager",
                    "fraud-protection-manager",
                    "guest",
                    "irule-manager",
                    "log-manager",
                    "manager",
                    "no-access",
                    "operator",
                    "resource-admin",
                    "user-manager",
                    "web-application-security-administrator",
                    "web-application-security-editor",
                    "web-application-security-operations-administrator",
                ),
                default="no-access",
            ),
            BigipPropertySpec(
                name="user-partition",
                value_type="reference",
                in_sections=("role-info",),
                required=True,
                default="Common",
            ),
        ),
    )
