from __future__ import annotations

from ..models import (
    BigipObjectKindSpec,
    BigipObjectSpec,
    BigipPropertySpec,
)
from ._base import register


@register
def register_spec() -> BigipObjectSpec:
    return BigipObjectSpec(
        kind_spec=BigipObjectKindSpec(
            "gtm_pool_srv",
            module="gtm",
            object_types=("pool srv",),
        ),
        header_types=(("gtm", "pool srv"),),
        properties=(
            BigipPropertySpec(
                name="alternate-mode",
                value_type="enum",
                allow_none=True,
                enum_values=(
                    "drop-packet",
                    "none",
                    "packet-rate",
                    "ratio",
                    "return-to-dns",
                    "round-robin",
                    "static-persistence",
                    "topology",
                    "virtual-server-capacity",
                    "virtual-server-score",
                ),
            ),
            BigipPropertySpec(name="app-service", value_type="string", allow_none=True),
            BigipPropertySpec(name="description", value_type="string"),
            BigipPropertySpec(
                name="dynamic",
                value_type="enum",
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="fallback-mode",
                value_type="enum",
                allow_none=True,
                enum_values=(
                    "completion-rate",
                    "cpu",
                    "drop-packet",
                    "fewest-hops",
                    "kilobytes-per-second",
                    "least-connections",
                    "lowest-round-trip-time",
                    "none",
                    "packet-rate",
                    "quality-of-service",
                    "ratio",
                    "return-to-dns",
                    "round-robin",
                    "static-persistence",
                    "topology",
                    "virtual-server-capacity",
                    "virtual-server-score",
                ),
            ),
            BigipPropertySpec(
                name="load-balancing-mode",
                value_type="enum",
                enum_values=(
                    "completion-rate",
                    "cpu",
                    "drop-packet",
                    "fewest-hops",
                    "kilobytes-per-second",
                    "least-connections",
                    "lowest-round-trip-time",
                    "packet-rate",
                    "quality-of-service",
                    "ratio",
                    "return-to-dns",
                    "round-robin",
                    "static-persistence",
                    "topology",
                    "virtual-server-capacity",
                    "virtual-server-score",
                ),
            ),
            BigipPropertySpec(
                name="manual-resume",
                value_type="enum",
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(name="max-answers-returned", value_type="integer"),
            BigipPropertySpec(name="member-order", value_type="integer"),
            BigipPropertySpec(name="members", value_type="unknown", allow_none=True),
            BigipPropertySpec(name="metadata", value_type="unknown", allow_none=True),
            BigipPropertySpec(name="persist", value_type="enum", enum_values=("false", "true")),
            BigipPropertySpec(name="port", value_type="integer"),
            BigipPropertySpec(name="priority", value_type="integer"),
            BigipPropertySpec(name="qos-hit-ratio", value_type="integer"),
            BigipPropertySpec(name="qos-hops", value_type="integer"),
            BigipPropertySpec(name="qos-kilobytes-second", value_type="integer"),
            BigipPropertySpec(name="qos-lcs", value_type="integer"),
            BigipPropertySpec(name="qos-packet-rate", value_type="integer"),
            BigipPropertySpec(name="qos-rtt", value_type="integer"),
            BigipPropertySpec(name="qos-topology", value_type="integer"),
            BigipPropertySpec(name="qos-vs-capacity", value_type="integer"),
            BigipPropertySpec(name="qos-vs-score", value_type="integer"),
            BigipPropertySpec(name="ratio", value_type="integer"),
            BigipPropertySpec(name="ttl", value_type="integer", min_value=0, max_value=4294967295),
            BigipPropertySpec(name="value", value_type="string"),
            BigipPropertySpec(
                name="verify-member-availability",
                value_type="enum",
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(name="weight", value_type="integer"),
        ),
    )
