from __future__ import annotations

from ..models import (
    BigipObjectKindSpec,
    BigipObjectSpec,
    BigipPropertySpec,
)
from ._base import register


@register
def register_spec() -> BigipObjectSpec:
    return BigipObjectSpec(
        kind_spec=BigipObjectKindSpec(
            "gtm_pool_a",
            module="gtm",
            object_types=("pool a",),
        ),
        header_types=(("gtm", "pool a"),),
        properties=(
            BigipPropertySpec(
                name="alternate-mode",
                value_type="enum",
                allow_none=True,
                enum_values=(
                    "drop-packet",
                    "fallback-ip",
                    "none",
                    "packet-rate",
                    "ratio",
                    "return-to-dns",
                    "round-robin",
                    "static-persistence",
                    "topology",
                    "virtual-server-capacity",
                    "virtual-server-score",
                ),
            ),
            BigipPropertySpec(name="app-service", value_type="string", allow_none=True),
            BigipPropertySpec(name="depends-on", value_type="unknown", allow_none=True),
            BigipPropertySpec(name="description", value_type="string"),
            BigipPropertySpec(
                name="dynamic",
                value_type="enum",
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(name="fallback-ip", value_type="string"),
            BigipPropertySpec(
                name="fallback-mode",
                value_type="enum",
                allow_none=True,
                enum_values=(
                    "completion-rate",
                    "cpu",
                    "drop-packet",
                    "fallback-ip",
                    "fewest-hops",
                    "kilobytes-per-second",
                    "least-connections",
                    "lowest-round-trip-time",
                    "none",
                    "packet-rate",
                    "quality-of-service",
                    "ratio",
                    "return-to-dns",
                    "round-robin",
                    "static-persistence",
                    "topology",
                    "virtual-server-capacity",
                    "virtual-server-score",
                ),
            ),
            BigipPropertySpec(name="limit-max-bps", value_type="integer"),
            BigipPropertySpec(
                name="limit-max-bps-status",
                value_type="enum",
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(name="limit-max-connections", value_type="integer"),
            BigipPropertySpec(
                name="limit-max-connections-status",
                value_type="enum",
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(name="limit-max-pps", value_type="integer"),
            BigipPropertySpec(
                name="limit-max-pps-status",
                value_type="enum",
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="load-balancing-mode",
                value_type="enum",
                enum_values=(
                    "completion-rate",
                    "cpu",
                    "drop-packet",
                    "fallback-ip",
                    "fewest-hops",
                    "kilobytes-per-second",
                    "least-connections",
                    "lowest-round-trip-time",
                    "packet-rate",
                    "quality-of-service",
                    "ratio",
                    "return-to-dns",
                    "round-robin",
                    "static-persistence",
                    "topology",
                    "virtual-server-capacity",
                    "virtual-server-score",
                ),
            ),
            BigipPropertySpec(
                name="manual-resume",
                value_type="enum",
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(name="max-answers-returned", value_type="integer"),
            BigipPropertySpec(name="member-order", value_type="integer"),
            BigipPropertySpec(name="members", value_type="unknown", allow_none=True),
            BigipPropertySpec(name="metadata", value_type="unknown", allow_none=True),
            BigipPropertySpec(
                name="min-members-up-mode",
                value_type="enum",
                enum_values=("number", "off", "percent"),
            ),
            BigipPropertySpec(name="min-members-up-value", value_type="integer"),
            BigipPropertySpec(
                name="monitor",
                value_type="unknown",
                references=(
                    "analytics_system_monitor_report",
                    "gtm_monitor_bigip",
                    "gtm_monitor_bigip_link",
                    "gtm_monitor_external",
                    "gtm_monitor_firepass",
                    "gtm_monitor_ftp",
                    "gtm_monitor_gateway_icmp",
                    "gtm_monitor_gtp",
                    "gtm_monitor_http",
                    "gtm_monitor_https",
                    "gtm_monitor_imap",
                    "gtm_monitor_ldap",
                    "gtm_monitor_mssql",
                    "gtm_monitor_mysql",
                    "gtm_monitor_nntp",
                    "gtm_monitor_none",
                    "gtm_monitor_oracle",
                    "gtm_monitor_pop3",
                    "gtm_monitor_postgresql",
                    "gtm_monitor_radius",
                    "gtm_monitor_radius_accounting",
                    "gtm_monitor_real_server",
                    "gtm_monitor_scripted",
                    "gtm_monitor_sip",
                    "gtm_monitor_smtp",
                    "gtm_monitor_snmp",
                    "gtm_monitor_snmp_link",
                    "gtm_monitor_soap",
                    "gtm_monitor_tcp",
                    "gtm_monitor_tcp_half_open",
                    "gtm_monitor_udp",
                    "gtm_monitor_wap",
                    "gtm_monitor_wmi",
                    "ltm_default_node_monitor",
                    "ltm_monitor_diameter",
                    "ltm_monitor_dns",
                    "ltm_monitor_external",
                    "ltm_monitor_firepass",
                    "ltm_monitor_ftp",
                    "ltm_monitor_gateway_icmp",
                    "ltm_monitor_http",
                    "ltm_monitor_http2",
                    "ltm_monitor_https",
                    "ltm_monitor_icmp",
                    "ltm_monitor_imap",
                    "ltm_monitor_inband",
                    "ltm_monitor_ldap",
                    "ltm_monitor_module_score",
                    "ltm_monitor_mqtt",
                    "ltm_monitor_mssql",
                    "ltm_monitor_mysql",
                    "ltm_monitor_nntp",
                    "ltm_monitor_none",
                    "ltm_monitor_oracle",
                    "ltm_monitor_pop3",
                    "ltm_monitor_postgresql",
                    "ltm_monitor_radius",
                    "ltm_monitor_radius_accounting",
                    "ltm_monitor_real_server",
                    "ltm_monitor_rpc",
                    "ltm_monitor_sasp",
                    "ltm_monitor_scripted",
                    "ltm_monitor_sip",
                    "ltm_monitor_smb",
                    "ltm_monitor_smtp",
                    "ltm_monitor_snmp_dca",
                    "ltm_monitor_snmp_dca_base",
                    "ltm_monitor_soap",
                    "ltm_monitor_tcp",
                    "ltm_monitor_tcp_echo",
                    "ltm_monitor_tcp_half_open",
                    "ltm_monitor_udp",
                    "ltm_monitor_virtual_location",
                    "ltm_monitor_wap",
                    "ltm_monitor_wmi",
                    "sys_file_external_monitor",
                    "util_test_monitor",
                ),
            ),
            BigipPropertySpec(name="persist", value_type="enum", enum_values=("false", "true")),
            BigipPropertySpec(name="qos-hit-ratio", value_type="integer"),
            BigipPropertySpec(name="qos-hops", value_type="integer"),
            BigipPropertySpec(name="qos-kilobytes-second", value_type="integer"),
            BigipPropertySpec(name="qos-lcs", value_type="integer"),
            BigipPropertySpec(name="qos-packet-rate", value_type="integer"),
            BigipPropertySpec(name="qos-rtt", value_type="integer"),
            BigipPropertySpec(name="qos-topology", value_type="integer"),
            BigipPropertySpec(name="qos-vs-capacity", value_type="integer"),
            BigipPropertySpec(name="qos-vs-score", value_type="integer"),
            BigipPropertySpec(name="ratio", value_type="integer"),
            BigipPropertySpec(name="ttl", value_type="integer", min_value=0, max_value=4294967295),
            BigipPropertySpec(name="value", value_type="string"),
            BigipPropertySpec(
                name="verify-member-availability",
                value_type="enum",
                enum_values=("disabled", "enabled"),
            ),
        ),
    )
