from __future__ import annotations

from ..models import (
    BigipObjectKindSpec,
    BigipObjectSpec,
    BigipPropertySpec,
)
from ._base import register


@register
def register_spec() -> BigipObjectSpec:
    return BigipObjectSpec(
        kind_spec=BigipObjectKindSpec(
            "gtm_server",
            module="gtm",
            object_types=("server",),
        ),
        header_types=(("gtm", "server"),),
        properties=(
            BigipPropertySpec(name="addresses", value_type="unknown"),
            BigipPropertySpec(
                name="app-service",
                value_type="string",
                allow_none=True,
                default="none",
            ),
            BigipPropertySpec(
                name="datacenter",
                value_type="reference",
                required=True,
                references=("gtm_datacenter",),
            ),
            BigipPropertySpec(name="depends-on", value_type="unknown", allow_none=True),
            BigipPropertySpec(name="description", value_type="string"),
            BigipPropertySpec(name="destination", value_type="string", shape_kind="ip-address"),
            BigipPropertySpec(name="devices", value_type="unknown"),
            BigipPropertySpec(name="explicit-link-name", value_type="reference", default="none"),
            BigipPropertySpec(
                name="expose-route-domains",
                value_type="enum",
                enum_values=("no", "yes"),
                shape_kind="boolean",
                default="no",
            ),
            BigipPropertySpec(
                name="iq-allow-path",
                value_type="enum",
                enum_values=("no", "yes"),
                shape_kind="boolean",
                default="yes",
            ),
            BigipPropertySpec(
                name="iq-allow-service-check",
                value_type="enum",
                enum_values=("no", "yes"),
                shape_kind="boolean",
                default="yes",
            ),
            BigipPropertySpec(
                name="iq-allow-snmp",
                value_type="enum",
                enum_values=("no", "yes"),
                shape_kind="boolean",
                default="yes",
            ),
            BigipPropertySpec(name="iquery-cipher-list", value_type="string"),
            BigipPropertySpec(name="iquery-minimum-tls-version", value_type="string"),
            BigipPropertySpec(name="limit-cpu-usage", value_type="integer"),
            BigipPropertySpec(
                name="limit-cpu-usage-status",
                value_type="enum",
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
                default="disabled",
            ),
            BigipPropertySpec(name="limit-max-bps", value_type="integer"),
            BigipPropertySpec(
                name="limit-max-bps-status",
                value_type="enum",
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
                default="disabled",
            ),
            BigipPropertySpec(name="limit-max-connections", value_type="integer"),
            BigipPropertySpec(
                name="limit-max-connections-status",
                value_type="enum",
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
                default="disabled",
            ),
            BigipPropertySpec(name="limit-max-pps", value_type="integer"),
            BigipPropertySpec(
                name="limit-max-pps-status",
                value_type="enum",
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
                default="disabled",
            ),
            BigipPropertySpec(name="limit-mem-avail", value_type="integer", required=True),
            BigipPropertySpec(
                name="limit-mem-avail-status",
                value_type="enum",
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
                default="disabled",
            ),
            BigipPropertySpec(
                name="link-discovery",
                value_type="enum",
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
                default="disabled",
            ),
            BigipPropertySpec(name="ltm-name", value_type="reference"),
            BigipPropertySpec(name="metadata", value_type="unknown"),
            BigipPropertySpec(
                name="monitor",
                value_type="unknown",
                repeated=True,
                references=(
                    "gtm_monitor_bigip",
                    "gtm_monitor_bigip_link",
                    "gtm_monitor_external",
                    "gtm_monitor_firepass",
                    "gtm_monitor_ftp",
                    "gtm_monitor_gateway_icmp",
                    "gtm_monitor_gtp",
                    "gtm_monitor_http",
                    "gtm_monitor_https",
                    "gtm_monitor_imap",
                    "gtm_monitor_ldap",
                    "gtm_monitor_mssql",
                    "gtm_monitor_mysql",
                    "gtm_monitor_nntp",
                    "gtm_monitor_none",
                    "gtm_monitor_oracle",
                    "gtm_monitor_pop3",
                    "gtm_monitor_postgresql",
                    "gtm_monitor_radius",
                    "gtm_monitor_radius_accounting",
                    "gtm_monitor_real_server",
                    "gtm_monitor_scripted",
                    "gtm_monitor_sip",
                    "gtm_monitor_smtp",
                    "gtm_monitor_snmp",
                    "gtm_monitor_snmp_link",
                    "gtm_monitor_soap",
                    "gtm_monitor_tcp",
                    "gtm_monitor_tcp_half_open",
                    "gtm_monitor_udp",
                    "gtm_monitor_wap",
                    "gtm_monitor_wmi",
                ),
                shape_kind="object",
            ),
            BigipPropertySpec(
                name="persist",
                value_type="enum",
                enum_values=("false", "true"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="prober-fallback",
                value_type="enum",
                allow_none=True,
                enum_values=(
                    "any-available",
                    "inherit",
                    "inside-datacenter",
                    "none",
                    "outside-datacenter",
                    "pool",
                ),
                default="inherit",
            ),
            BigipPropertySpec(
                name="prober-pool",
                value_type="reference",
                allow_none=True,
                enum_values=("none",),
                references=("gtm_prober_pool",),
                default="none",
            ),
            BigipPropertySpec(
                name="prober-preference",
                value_type="enum",
                enum_values=("inherit", "inside-datacenter", "outside-datacenter", "pool"),
                default="inherit",
            ),
            BigipPropertySpec(name="product", value_type="reference"),
            BigipPropertySpec(
                name="translation",
                value_type="string",
                shape_kind="ip-address",
                default="::",
            ),
            BigipPropertySpec(
                name="translation-address",
                value_type="string",
                shape_kind="ip-address",
                default="::",
            ),
            BigipPropertySpec(name="translation-port", value_type="reference", default="0"),
            BigipPropertySpec(name="value", value_type="string"),
            BigipPropertySpec(
                name="virtual-server-discovery",
                value_type="enum",
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
                default="disabled",
            ),
            BigipPropertySpec(name="virtual-servers", value_type="unknown", allow_none=True),
        ),
    )
