from __future__ import annotations

from ..models import (
    BigipObjectKindSpec,
    BigipObjectSpec,
    BigipPropertySpec,
)
from ._base import register


@register
def register_spec() -> BigipObjectSpec:
    return BigipObjectSpec(
        kind_spec=BigipObjectKindSpec(
            "ltm_profile_analytics",
            module="ltm",
            object_types=("profile analytics",),
        ),
        header_types=(("ltm", "profile analytics"),),
        properties=(
            BigipPropertySpec(
                name="alerts",
                value_type="list",
                allow_none=True,
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
                block=(
                    BigipPropertySpec(
                        name="app-service",
                        value_type="string",
                        in_sections=("alerts",),
                        allow_none=True,
                        default="none",
                    ),
                    BigipPropertySpec(
                        name="granularity",
                        value_type="enum",
                        in_sections=("alerts",),
                        enum_values=("application", "pool-member", "virtual-server"),
                    ),
                    BigipPropertySpec(
                        name="metric",
                        value_type="enum",
                        in_sections=("alerts",),
                        enum_values=(
                            "average-page-load-time",
                            "average-request-throughput",
                            "average-response-throughput",
                            "average-server-latency",
                            "average-tps",
                            "max-page-load-time",
                            "max-request-throughput",
                            "max-response-throughput",
                            "max-server-latency",
                            "max-tps",
                        ),
                    ),
                    BigipPropertySpec(
                        name="sample-period",
                        value_type="integer",
                        in_sections=("alerts",),
                        default="300",
                    ),
                    BigipPropertySpec(
                        name="threshold", value_type="integer", in_sections=("alerts",)
                    ),
                    BigipPropertySpec(
                        name="threshold-relation",
                        value_type="enum",
                        in_sections=("alerts",),
                        enum_values=("above", "below"),
                    ),
                ),
            ),
            BigipPropertySpec(
                name="app-service",
                value_type="string",
                in_sections=("alerts",),
                allow_none=True,
                default="none",
            ),
            BigipPropertySpec(
                name="granularity",
                value_type="enum",
                in_sections=("alerts",),
                enum_values=("application", "pool-member", "virtual-server"),
            ),
            BigipPropertySpec(
                name="metric",
                value_type="enum",
                in_sections=("alerts",),
                enum_values=(
                    "average-page-load-time",
                    "average-request-throughput",
                    "average-response-throughput",
                    "average-server-latency",
                    "average-tps",
                    "max-page-load-time",
                    "max-request-throughput",
                    "max-response-throughput",
                    "max-server-latency",
                    "max-tps",
                ),
            ),
            BigipPropertySpec(
                name="sample-period",
                value_type="integer",
                in_sections=("alerts",),
                default="300",
            ),
            BigipPropertySpec(name="threshold", value_type="integer", in_sections=("alerts",)),
            BigipPropertySpec(
                name="threshold-relation",
                value_type="enum",
                in_sections=("alerts",),
                enum_values=("above", "below"),
            ),
            BigipPropertySpec(
                name="app-service",
                value_type="string",
                allow_none=True,
                default="none",
            ),
            BigipPropertySpec(
                name="captured-traffic-external-logging",
                value_type="enum",
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="captured-traffic-internal-logging",
                value_type="enum",
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="collect-geo",
                value_type="enum",
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="collect-http-throughput",
                value_type="enum",
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
                usage_flags=frozenset(("deprecated",)),
            ),
            BigipPropertySpec(
                name="collect-http-timing-metrics",
                value_type="enum",
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="collect-ip",
                value_type="enum",
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="collect-max-tps-and-throughput",
                value_type="enum",
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="collect-methods",
                value_type="enum",
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="collect-page-load-time",
                value_type="enum",
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="collect-response-codes",
                value_type="enum",
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="collect-server-latency",
                value_type="enum",
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
                usage_flags=frozenset(("deprecated",)),
            ),
            BigipPropertySpec(
                name="collect-subnets",
                value_type="enum",
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="collect-url",
                value_type="enum",
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="collect-user-agent",
                value_type="enum",
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="collect-user-sessions",
                value_type="enum",
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="collected-stats-external-logging",
                value_type="enum",
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="collected-stats-internal-logging",
                value_type="enum",
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="countries-for-stat-collection",
                value_type="list",
                list_operators=frozenset(("add", "delete")),
            ),
            BigipPropertySpec(
                name="defaults-from",
                value_type="string",
                allow_none=True,
                references=("ltm_profile_analytics",),
                default="analytics",
            ),
            BigipPropertySpec(name="description", value_type="string"),
            BigipPropertySpec(name="external-logging-publisher", value_type="reference"),
            BigipPropertySpec(
                name="ips-for-stat-collection",
                value_type="list",
                list_operators=frozenset(("add", "delete")),
            ),
            BigipPropertySpec(
                name="notification-by-email",
                value_type="enum",
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="notification-by-snmp",
                value_type="enum",
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="notification-by-syslog",
                value_type="enum",
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="notification-email-addresses",
                value_type="list",
                allow_none=True,
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="publish-irule-statistics",
                value_type="enum",
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="sampling",
                value_type="enum",
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
                default="disabled",
            ),
            BigipPropertySpec(
                name="session-cookie-security",
                value_type="enum",
                enum_values=("always-secure", "never-secure", "ssl-only"),
            ),
            BigipPropertySpec(name="session-timeout-minutes", value_type="integer"),
            BigipPropertySpec(name="smtp-config", value_type="reference"),
            BigipPropertySpec(
                name="subnet-masks",
                value_type="list",
                allow_none=True,
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
                block=(
                    BigipPropertySpec(
                        name="subnet",
                        value_type="string",
                        in_sections=("subnet-masks",),
                        shape_kind="ip-address",
                    ),
                ),
            ),
            BigipPropertySpec(
                name="subnet",
                value_type="string",
                in_sections=("subnet-masks",),
                shape_kind="ip-address",
            ),
            BigipPropertySpec(
                name="subnets-for-stat-collection",
                value_type="list",
                list_operators=frozenset(("add", "delete")),
            ),
            BigipPropertySpec(
                name="traffic-capture",
                value_type="list",
                allow_none=True,
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
                block=(
                    BigipPropertySpec(
                        name="app-service",
                        value_type="string",
                        in_sections=("traffic-capture",),
                        allow_none=True,
                        default="none",
                    ),
                    BigipPropertySpec(
                        name="captured-protocols",
                        value_type="enum",
                        in_sections=("traffic-capture",),
                        enum_values=("all", "http", "https"),
                    ),
                    BigipPropertySpec(
                        name="client-ips",
                        value_type="list",
                        in_sections=("traffic-capture",),
                        allow_none=True,
                        list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
                    ),
                    BigipPropertySpec(
                        name="dos-activity",
                        value_type="enum",
                        in_sections=("traffic-capture",),
                        enum_values=("any", "mitigated-by-dosl7"),
                    ),
                    BigipPropertySpec(
                        name="methods",
                        value_type="list",
                        in_sections=("traffic-capture",),
                        allow_none=True,
                        list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
                    ),
                    BigipPropertySpec(
                        name="node-addresses",
                        value_type="list",
                        in_sections=("traffic-capture",),
                        allow_none=True,
                        list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
                    ),
                    BigipPropertySpec(
                        name="request-captured-parts",
                        value_type="enum",
                        in_sections=("traffic-capture",),
                        allow_none=True,
                        enum_values=("all", "body", "headers", "none"),
                    ),
                    BigipPropertySpec(
                        name="request-content-filter-search-part",
                        value_type="enum",
                        in_sections=("traffic-capture",),
                        allow_none=True,
                        enum_values=("all", "body", "headers", "none", "uri"),
                    ),
                    BigipPropertySpec(
                        name="request-content-filter-search-string",
                        value_type="string",
                        in_sections=("traffic-capture",),
                    ),
                    BigipPropertySpec(
                        name="response-captured-parts",
                        value_type="enum",
                        in_sections=("traffic-capture",),
                        allow_none=True,
                        enum_values=("all", "body", "headers", "none"),
                    ),
                    BigipPropertySpec(
                        name="response-codes",
                        value_type="list",
                        in_sections=("traffic-capture",),
                        allow_none=True,
                        list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
                    ),
                    BigipPropertySpec(
                        name="response-content-filter-search-part",
                        value_type="enum",
                        in_sections=("traffic-capture",),
                        allow_none=True,
                        enum_values=("all", "body", "headers", "none"),
                    ),
                    BigipPropertySpec(
                        name="response-content-filter-search-string",
                        value_type="string",
                        in_sections=("traffic-capture",),
                    ),
                    BigipPropertySpec(
                        name="url-filter-type",
                        value_type="enum",
                        in_sections=("traffic-capture",),
                        enum_values=("all", "black-list", "white-list"),
                    ),
                    BigipPropertySpec(
                        name="url-path-prefixes",
                        value_type="list",
                        in_sections=("traffic-capture",),
                        allow_none=True,
                        list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
                    ),
                    BigipPropertySpec(
                        name="user-agent-substrings",
                        value_type="list",
                        in_sections=("traffic-capture",),
                        allow_none=True,
                        list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
                    ),
                    BigipPropertySpec(
                        name="virtual-servers",
                        value_type="list",
                        in_sections=("traffic-capture",),
                        allow_none=True,
                        list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
                    ),
                ),
            ),
            BigipPropertySpec(
                name="app-service",
                value_type="string",
                in_sections=("traffic-capture",),
                allow_none=True,
                default="none",
            ),
            BigipPropertySpec(
                name="captured-protocols",
                value_type="enum",
                in_sections=("traffic-capture",),
                enum_values=("all", "http", "https"),
            ),
            BigipPropertySpec(
                name="client-ips",
                value_type="list",
                in_sections=("traffic-capture",),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="dos-activity",
                value_type="enum",
                in_sections=("traffic-capture",),
                enum_values=("any", "mitigated-by-dosl7"),
            ),
            BigipPropertySpec(
                name="methods",
                value_type="list",
                in_sections=("traffic-capture",),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="node-addresses",
                value_type="list",
                in_sections=("traffic-capture",),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="request-captured-parts",
                value_type="enum",
                in_sections=("traffic-capture",),
                allow_none=True,
                enum_values=("all", "body", "headers", "none"),
            ),
            BigipPropertySpec(
                name="request-content-filter-search-part",
                value_type="enum",
                in_sections=("traffic-capture",),
                allow_none=True,
                enum_values=("all", "body", "headers", "none", "uri"),
            ),
            BigipPropertySpec(
                name="request-content-filter-search-string",
                value_type="string",
                in_sections=("traffic-capture",),
            ),
            BigipPropertySpec(
                name="response-captured-parts",
                value_type="enum",
                in_sections=("traffic-capture",),
                allow_none=True,
                enum_values=("all", "body", "headers", "none"),
            ),
            BigipPropertySpec(
                name="response-codes",
                value_type="list",
                in_sections=("traffic-capture",),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="response-content-filter-search-part",
                value_type="enum",
                in_sections=("traffic-capture",),
                allow_none=True,
                enum_values=("all", "body", "headers", "none"),
            ),
            BigipPropertySpec(
                name="response-content-filter-search-string",
                value_type="string",
                in_sections=("traffic-capture",),
            ),
            BigipPropertySpec(
                name="url-filter-type",
                value_type="enum",
                in_sections=("traffic-capture",),
                enum_values=("all", "black-list", "white-list"),
            ),
            BigipPropertySpec(
                name="url-path-prefixes",
                value_type="list",
                in_sections=("traffic-capture",),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="user-agent-substrings",
                value_type="list",
                in_sections=("traffic-capture",),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="virtual-servers",
                value_type="list",
                in_sections=("traffic-capture",),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="urls-for-stat-collection",
                value_type="list",
                list_operators=frozenset(("add", "delete")),
            ),
        ),
    )
