from __future__ import annotations

from ..models import (
    BigipObjectKindSpec,
    BigipObjectSpec,
    BigipPropertySpec,
)
from ._base import register


@register
def register_spec() -> BigipObjectSpec:
    return BigipObjectSpec(
        kind_spec=BigipObjectKindSpec(
            "ltm_node",
            module="ltm",
            object_types=("node",),
        ),
        header_types=(("ltm", "node"),),
        properties=(
            BigipPropertySpec(
                name="address",
                value_type="string",
                pattern="^(?:\\\\d{1,3}(?:\\\\.\\\\d{1,3}){3})(?:/\\\\d{1,2})?$",
            ),
            BigipPropertySpec(name="connection-limit", value_type="integer"),
            BigipPropertySpec(name="description", value_type="string"),
            BigipPropertySpec(name="dynamic-ratio", value_type="integer"),
            BigipPropertySpec(
                name="fqdn",
                value_type="string",
                pattern="^(?=.{1,253}$)(?:[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?\\\\.)+[A-Za-z]{2,63}$",
            ),
            BigipPropertySpec(name="name", value_type="string", in_sections=("fqdn",)),
            BigipPropertySpec(
                name="address-family",
                value_type="enum",
                in_sections=("fqdn",),
                enum_values=("ipv4", "ipv6"),
            ),
            BigipPropertySpec(
                name="autopopulate",
                value_type="enum",
                in_sections=("fqdn",),
                enum_values=("enabled", "disabled"),
            ),
            BigipPropertySpec(name="down-interval", value_type="integer", in_sections=("fqdn",)),
            BigipPropertySpec(name="interval", value_type="integer", in_sections=("fqdn",)),
            BigipPropertySpec(
                name="logging", value_type="enum", enum_values=("enabled", "disabled")
            ),
            BigipPropertySpec(
                name="monitor",
                value_type="reference",
                allow_none=True,
                references=(
                    "ltm_monitor_diameter",
                    "ltm_monitor_dns",
                    "ltm_monitor_external",
                    "ltm_monitor_firepass",
                    "ltm_monitor_ftp",
                    "ltm_monitor_gateway_icmp",
                    "ltm_monitor_http",
                    "ltm_monitor_http2",
                    "ltm_monitor_https",
                    "ltm_monitor_icmp",
                    "ltm_monitor_imap",
                    "ltm_monitor_inband",
                    "ltm_monitor_ldap",
                    "ltm_monitor_module_score",
                    "ltm_monitor_mqtt",
                    "ltm_monitor_mssql",
                    "ltm_monitor_mysql",
                    "ltm_monitor_nntp",
                    "ltm_monitor_none",
                    "ltm_monitor_oracle",
                    "ltm_monitor_pop3",
                    "ltm_monitor_postgresql",
                    "ltm_monitor_radius",
                    "ltm_monitor_radius_accounting",
                    "ltm_monitor_real_server",
                    "ltm_monitor_rpc",
                    "ltm_monitor_sasp",
                    "ltm_monitor_scripted",
                    "ltm_monitor_sip",
                    "ltm_monitor_smb",
                    "ltm_monitor_smtp",
                    "ltm_monitor_snmp_dca",
                    "ltm_monitor_snmp_dca_base",
                    "ltm_monitor_soap",
                    "ltm_monitor_tcp",
                    "ltm_monitor_tcp_echo",
                    "ltm_monitor_tcp_half_open",
                    "ltm_monitor_udp",
                    "ltm_monitor_virtual_location",
                    "ltm_monitor_wap",
                    "ltm_monitor_wmi",
                ),
            ),
            BigipPropertySpec(name="rate-limit", value_type="integer"),
            BigipPropertySpec(name="ratio", value_type="integer"),
            BigipPropertySpec(
                name="session",
                value_type="reference",
                enum_values=("user-enabled", "user-disabled"),
                references=("auth_user",),
            ),
            BigipPropertySpec(
                name="state",
                value_type="reference",
                enum_values=("user-down", "user-up"),
                references=("auth_user",),
            ),
            BigipPropertySpec(name="value", value_type="string"),
            BigipPropertySpec(
                name="persist",
                value_type="reference",
                enum_values=("true", "false"),
                references=(
                    "ltm_persistence_cookie",
                    "ltm_persistence_dest_addr",
                    "ltm_persistence_global_settings",
                    "ltm_persistence_hash",
                    "ltm_persistence_host",
                    "ltm_persistence_msrdp",
                    "ltm_persistence_persist_records",
                    "ltm_persistence_sip",
                    "ltm_persistence_source_addr",
                    "ltm_persistence_ssl",
                    "ltm_persistence_universal",
                ),
            ),
            BigipPropertySpec(name="reset-stats", value_type="boolean"),
        ),
    )
