from __future__ import annotations

from ..models import (
    BigipObjectKindSpec,
    BigipObjectSpec,
    BigipPropertySpec,
)
from ._base import register


@register
def register_spec() -> BigipObjectSpec:
    return BigipObjectSpec(
        kind_spec=BigipObjectKindSpec(
            "ltm_profile_http",
            module="ltm",
            object_types=("profile http",),
        ),
        header_types=(("ltm", "profile http"),),
        properties=(
            BigipPropertySpec(
                name="accept-xff",
                value_type="enum",
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="app-service",
                value_type="string",
                allow_none=True,
                default="none",
            ),
            BigipPropertySpec(
                name="basic-auth-realm",
                value_type="unknown",
                allow_none=True,
                default="none",
            ),
            BigipPropertySpec(
                name="defaults-from",
                value_type="reference",
                allow_none=True,
                references=("ltm_profile_http",),
                default="http",
            ),
            BigipPropertySpec(name="description", value_type="string"),
            BigipPropertySpec(name="encrypt-cookie-secret", value_type="unknown", default="none"),
            BigipPropertySpec(
                name="encrypt-cookies",
                value_type="unknown",
                allow_none=True,
                default="none",
            ),
            BigipPropertySpec(
                name="enforcement",
                value_type="unknown",
                shape_kind="object",
                block=(
                    BigipPropertySpec(
                        name="allow-ws-header-name",
                        value_type="enum",
                        in_sections=("enforcement",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                    ),
                    BigipPropertySpec(
                        name="excess-client-headers",
                        value_type="enum",
                        in_sections=("enforcement",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                        default="disabled which rejects the connection",
                    ),
                    BigipPropertySpec(
                        name="excess-server-headers",
                        value_type="enum",
                        in_sections=("enforcement",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                        default="disabled which rejects the connection",
                    ),
                    BigipPropertySpec(
                        name="known-methods",
                        value_type="unknown",
                        in_sections=("enforcement",),
                    ),
                    BigipPropertySpec(
                        name="max-header-count",
                        value_type="integer",
                        in_sections=("enforcement",),
                        default="64",
                    ),
                    BigipPropertySpec(
                        name="max-header-size",
                        value_type="integer",
                        in_sections=("enforcement",),
                        default="32768",
                    ),
                    BigipPropertySpec(
                        name="max-requests",
                        value_type="integer",
                        in_sections=("enforcement",),
                        default="0 (zero), which means the system does not limit the number of requests per connection",
                    ),
                    BigipPropertySpec(
                        name="oversize-client-headers",
                        value_type="enum",
                        in_sections=("enforcement",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                        default="disabled which rejects the connection",
                    ),
                    BigipPropertySpec(
                        name="oversize-server-headers",
                        value_type="enum",
                        in_sections=("enforcement",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                        default="disabled which rejects the connection",
                    ),
                    BigipPropertySpec(
                        name="pipeline",
                        value_type="enum",
                        in_sections=("enforcement",),
                        enum_values=("allow", "pass-through", "reject"),
                        default="allow, which means that clients can make requests even when prior requests have not received a response",
                    ),
                    BigipPropertySpec(
                        name="rfc-compliance",
                        value_type="enum",
                        in_sections=("enforcement",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                        default="disabled which ignores rfc non-compliance",
                    ),
                    BigipPropertySpec(
                        name="truncated-redirects",
                        value_type="enum",
                        in_sections=("enforcement",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                        default="disabled, which will silently drop the invalid HTTP",
                    ),
                    BigipPropertySpec(
                        name="unknown-method",
                        value_type="enum",
                        in_sections=("enforcement",),
                        enum_values=("allow", "pass-through", "reject"),
                        default="allow which allows all methods, (known or unknown)",
                    ),
                ),
            ),
            BigipPropertySpec(
                name="allow-ws-header-name",
                value_type="enum",
                in_sections=("enforcement",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="excess-client-headers",
                value_type="enum",
                in_sections=("enforcement",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
                default="disabled which rejects the connection",
            ),
            BigipPropertySpec(
                name="excess-server-headers",
                value_type="enum",
                in_sections=("enforcement",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
                default="disabled which rejects the connection",
            ),
            BigipPropertySpec(
                name="known-methods",
                value_type="unknown",
                in_sections=("enforcement",),
            ),
            BigipPropertySpec(
                name="max-header-count",
                value_type="integer",
                in_sections=("enforcement",),
                default="64",
            ),
            BigipPropertySpec(
                name="max-header-size",
                value_type="integer",
                in_sections=("enforcement",),
                default="32768",
            ),
            BigipPropertySpec(
                name="max-requests",
                value_type="integer",
                in_sections=("enforcement",),
                default="0 (zero), which means the system does not limit the number of requests per connection",
            ),
            BigipPropertySpec(
                name="oversize-client-headers",
                value_type="enum",
                in_sections=("enforcement",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
                default="disabled which rejects the connection",
            ),
            BigipPropertySpec(
                name="oversize-server-headers",
                value_type="enum",
                in_sections=("enforcement",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
                default="disabled which rejects the connection",
            ),
            BigipPropertySpec(
                name="pipeline",
                value_type="enum",
                in_sections=("enforcement",),
                enum_values=("allow", "pass-through", "reject"),
                default="allow, which means that clients can make requests even when prior requests have not received a response",
            ),
            BigipPropertySpec(
                name="rfc-compliance",
                value_type="enum",
                in_sections=("enforcement",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
                default="disabled which ignores rfc non-compliance",
            ),
            BigipPropertySpec(
                name="truncated-redirects",
                value_type="enum",
                in_sections=("enforcement",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
                default="disabled, which will silently drop the invalid HTTP",
            ),
            BigipPropertySpec(
                name="unknown-method",
                value_type="enum",
                in_sections=("enforcement",),
                enum_values=("allow", "pass-through", "reject"),
                default="allow which allows all methods, (known or unknown)",
            ),
            BigipPropertySpec(
                name="explicit-proxy",
                value_type="unknown",
                shape_kind="object",
                block=(
                    BigipPropertySpec(
                        name="bad-request-message",
                        value_type="unknown",
                        in_sections=("explicit-proxy",),
                    ),
                    BigipPropertySpec(
                        name="bad-response-message",
                        value_type="unknown",
                        in_sections=("explicit-proxy",),
                    ),
                    BigipPropertySpec(
                        name="connect-error-message",
                        value_type="unknown",
                        in_sections=("explicit-proxy",),
                    ),
                    BigipPropertySpec(
                        name="default-connect-handling",
                        value_type="enum",
                        in_sections=("explicit-proxy",),
                        enum_values=("allow", "deny"),
                        default="deny",
                    ),
                    BigipPropertySpec(
                        name="dns-error-message",
                        value_type="unknown",
                        in_sections=("explicit-proxy",),
                    ),
                    BigipPropertySpec(
                        name="dns-resolver",
                        value_type="unknown",
                        in_sections=("explicit-proxy",),
                        default="dns-resolver",
                    ),
                    BigipPropertySpec(
                        name="enabled",
                        value_type="enum",
                        in_sections=("explicit-proxy",),
                        enum_values=("no", "yes"),
                        shape_kind="boolean",
                    ),
                    BigipPropertySpec(
                        name="ipv6",
                        value_type="enum",
                        in_sections=("explicit-proxy",),
                        enum_values=("no", "yes"),
                        shape_kind="boolean",
                        default="no, which will try a IPv4 lookup before a IPv6",
                    ),
                    BigipPropertySpec(
                        name="route-domain",
                        value_type="unknown",
                        in_sections=("explicit-proxy",),
                        default="0",
                    ),
                    BigipPropertySpec(
                        name="tunnel-name",
                        value_type="unknown",
                        in_sections=("explicit-proxy",),
                        default="http-tunnel",
                    ),
                    BigipPropertySpec(
                        name="tunnel-on-any-request",
                        value_type="enum",
                        in_sections=("explicit-proxy",),
                        enum_values=("no", "yes"),
                        shape_kind="boolean",
                        default="no",
                    ),
                ),
            ),
            BigipPropertySpec(
                name="bad-request-message",
                value_type="unknown",
                in_sections=("explicit-proxy",),
            ),
            BigipPropertySpec(
                name="bad-response-message",
                value_type="unknown",
                in_sections=("explicit-proxy",),
            ),
            BigipPropertySpec(
                name="connect-error-message",
                value_type="unknown",
                in_sections=("explicit-proxy",),
            ),
            BigipPropertySpec(
                name="default-connect-handling",
                value_type="enum",
                in_sections=("explicit-proxy",),
                enum_values=("allow", "deny"),
                default="deny",
            ),
            BigipPropertySpec(
                name="dns-error-message",
                value_type="unknown",
                in_sections=("explicit-proxy",),
            ),
            BigipPropertySpec(
                name="dns-resolver",
                value_type="unknown",
                in_sections=("explicit-proxy",),
                default="dns-resolver",
            ),
            BigipPropertySpec(
                name="enabled",
                value_type="enum",
                in_sections=("explicit-proxy",),
                enum_values=("no", "yes"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="ipv6",
                value_type="enum",
                in_sections=("explicit-proxy",),
                enum_values=("no", "yes"),
                shape_kind="boolean",
                default="no, which will try a IPv4 lookup before a IPv6",
            ),
            BigipPropertySpec(
                name="route-domain",
                value_type="unknown",
                in_sections=("explicit-proxy",),
                references=("net_route_domain",),
                default="0",
            ),
            BigipPropertySpec(
                name="tunnel-name",
                value_type="unknown",
                in_sections=("explicit-proxy",),
                default="http-tunnel",
            ),
            BigipPropertySpec(
                name="tunnel-on-any-request",
                value_type="enum",
                in_sections=("explicit-proxy",),
                enum_values=("no", "yes"),
                shape_kind="boolean",
                default="no",
            ),
            BigipPropertySpec(
                name="fallback-host",
                value_type="unknown",
                allow_none=True,
                default="none",
            ),
            BigipPropertySpec(
                name="fallback-status-codes",
                value_type="unknown",
                allow_none=True,
                default="none",
            ),
            BigipPropertySpec(name="header-erase", value_type="string", default="none"),
            BigipPropertySpec(name="header-insert", value_type="string", default="none"),
            BigipPropertySpec(
                name="hsts",
                value_type="block",
                shape_kind="list",
                block=(
                    BigipPropertySpec(
                        name="include-subdomains",
                        value_type="enum",
                        in_sections=("hsts",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                        default="enabled",
                    ),
                    BigipPropertySpec(
                        name="maximum-age",
                        value_type="integer",
                        in_sections=("hsts",),
                        default="16070400",
                    ),
                    BigipPropertySpec(
                        name="mode",
                        value_type="enum",
                        in_sections=("hsts",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                        default="disabled",
                    ),
                    BigipPropertySpec(
                        name="preload",
                        value_type="enum",
                        in_sections=("hsts",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                        default="disabled",
                    ),
                ),
            ),
            BigipPropertySpec(
                name="include-subdomains",
                value_type="enum",
                in_sections=("hsts",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
                default="enabled",
            ),
            BigipPropertySpec(
                name="maximum-age",
                value_type="integer",
                in_sections=("hsts",),
                default="16070400",
            ),
            BigipPropertySpec(
                name="mode",
                value_type="enum",
                in_sections=("hsts",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
                default="disabled",
            ),
            BigipPropertySpec(
                name="preload",
                value_type="enum",
                in_sections=("hsts",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
                default="disabled",
            ),
            BigipPropertySpec(
                name="insert-xforwarded-for",
                value_type="enum",
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
                default="disabled",
            ),
            BigipPropertySpec(
                name="lws-separator",
                value_type="enum",
                allow_none=True,
                enum_values=("none",),
                default="none",
            ),
            BigipPropertySpec(name="lws-width", value_type="integer", default="80"),
            BigipPropertySpec(
                name="oneconnect-status-reuse",
                value_type="unknown",
                default='"200 206"',
            ),
            BigipPropertySpec(
                name="oneconnect-transformations",
                value_type="enum",
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
                default="enabled",
            ),
            BigipPropertySpec(
                name="proxy-type",
                value_type="enum",
                enum_values=("explicit", "reverse", "transparent"),
            ),
            BigipPropertySpec(
                name="redirect-rewrite",
                value_type="enum",
                allow_none=True,
                enum_values=("all", "matching", "nodes", "none"),
            ),
            BigipPropertySpec(
                name="request-chunking",
                value_type="enum",
                enum_values=("rechunk", "sustain"),
                default="sustain",
            ),
            BigipPropertySpec(
                name="response-chunking",
                value_type="enum",
                enum_values=("rechunk", "sustain", "unchunk"),
                default="sustain",
            ),
            BigipPropertySpec(
                name="response-headers-permitted",
                value_type="unknown",
                allow_none=True,
                default="none",
            ),
            BigipPropertySpec(name="server-agent-name", value_type="string", default="BigIP"),
            BigipPropertySpec(
                name="sflow",
                value_type="unknown",
                shape_kind="object",
                block=(
                    BigipPropertySpec(
                        name="poll-interval",
                        value_type="integer",
                        in_sections=("sflow",),
                        default="0",
                    ),
                    BigipPropertySpec(
                        name="poll-interval-global",
                        value_type="enum",
                        in_sections=("sflow",),
                        enum_values=("no", "yes"),
                        shape_kind="boolean",
                        default="yes",
                    ),
                    BigipPropertySpec(
                        name="sampling-rate",
                        value_type="integer",
                        in_sections=("sflow",),
                        default="0",
                    ),
                    BigipPropertySpec(
                        name="sampling-rate-global",
                        value_type="enum",
                        in_sections=("sflow",),
                        enum_values=("no", "yes"),
                        shape_kind="boolean",
                        default="yes",
                    ),
                ),
            ),
            BigipPropertySpec(
                name="poll-interval",
                value_type="integer",
                in_sections=("sflow",),
                default="0",
            ),
            BigipPropertySpec(
                name="poll-interval-global",
                value_type="enum",
                in_sections=("sflow",),
                enum_values=("no", "yes"),
                shape_kind="boolean",
                default="yes",
            ),
            BigipPropertySpec(
                name="sampling-rate",
                value_type="integer",
                in_sections=("sflow",),
                default="0",
            ),
            BigipPropertySpec(
                name="sampling-rate-global",
                value_type="enum",
                in_sections=("sflow",),
                enum_values=("no", "yes"),
                shape_kind="boolean",
                default="yes",
            ),
            BigipPropertySpec(name="via-host-name", value_type="string", required=True),
            BigipPropertySpec(
                name="via-request",
                value_type="enum",
                enum_values=("append", "preserve", "remove"),
            ),
            BigipPropertySpec(
                name="via-response",
                value_type="enum",
                enum_values=("append", "preserve", "remove"),
            ),
            BigipPropertySpec(name="xff-alternative-names", value_type="unknown"),
        ),
    )
