from __future__ import annotations

from ..models import (
    BigipObjectKindSpec,
    BigipObjectSpec,
    BigipPropertySpec,
)
from ._base import register


@register
def register_spec() -> BigipObjectSpec:
    return BigipObjectSpec(
        kind_spec=BigipObjectKindSpec(
            "ltm_policy",
            module="ltm",
            object_types=("policy",),
        ),
        header_types=(("ltm", "policy"),),
        properties=(
            BigipPropertySpec(name="strategy", value_type="boolean", allow_none=True),
            BigipPropertySpec(name="copy-from", value_type="string"),
            BigipPropertySpec(
                name="rules",
                value_type="enum",
                enum_values=("add", "delete", "modify", "replace-all-with"),
            ),
            BigipPropertySpec(name="ordinal", value_type="string", in_sections=("rules",)),
            BigipPropertySpec(
                name="conditions",
                value_type="enum",
                in_sections=("rules",),
                enum_values=("add", "delete", "modify", "replace-all-with"),
            ),
            BigipPropertySpec(
                name="actions",
                value_type="enum",
                enum_values=("add", "delete", "modify", "replace-all-with"),
            ),
            BigipPropertySpec(name="publish", value_type="string"),
            BigipPropertySpec(name="log", value_type="boolean"),
            BigipPropertySpec(name="values", value_type="list", repeated=True),
            BigipPropertySpec(name="not", value_type="boolean", repeated=True),
            BigipPropertySpec(name="equals", value_type="list", repeated=True),
            BigipPropertySpec(name="ends-with", value_type="list", repeated=True),
            BigipPropertySpec(name="contains", value_type="list", repeated=True),
            BigipPropertySpec(name="http-uri", value_type="string"),
            BigipPropertySpec(name="name", value_type="string"),
            BigipPropertySpec(name="index", value_type="string"),
            BigipPropertySpec(name="all", value_type="string"),
            BigipPropertySpec(name="normalized", value_type="string"),
            BigipPropertySpec(name="consistent", value_type="string"),
            BigipPropertySpec(name="scheme", value_type="string"),
            BigipPropertySpec(
                name="host",
                value_type="string",
                pattern="^(?=.{1,253}$)(?:[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?\\\\.)+[A-Za-z]{2,63}$",
            ),
            BigipPropertySpec(name="port", value_type="integer", min_value=0, max_value=65535),
            BigipPropertySpec(name="path", value_type="string"),
            BigipPropertySpec(name="extension", value_type="string"),
            BigipPropertySpec(name="query-string", value_type="string"),
            BigipPropertySpec(name="query-param", value_type="string"),
            BigipPropertySpec(name="from", value_type="string"),
            BigipPropertySpec(name="parameter", value_type="string"),
            BigipPropertySpec(name="unnamed-query-param", value_type="string"),
            BigipPropertySpec(name="whose", value_type="string"),
            BigipPropertySpec(name="path-segment", value_type="string"),
            BigipPropertySpec(name="numeric", value_type="string"),
            BigipPropertySpec(name="counting", value_type="string"),
            BigipPropertySpec(name="urlcat", value_type="string"),
            BigipPropertySpec(name="of", value_type="string"),
            BigipPropertySpec(name="tcp", value_type="string"),
            BigipPropertySpec(name="ssl-client-serverhello-send", value_type="string"),
            BigipPropertySpec(name="ssl-server-hello", value_type="string"),
            BigipPropertySpec(name="connector-open", value_type="string"),
            BigipPropertySpec(name="response", value_type="string"),
            BigipPropertySpec(name="proxy-response", value_type="string"),
            BigipPropertySpec(
                name="address",
                value_type="string",
                pattern="^(?:\\\\d{1,3}(?:\\\\.\\\\d{1,3}){3})(?:/\\\\d{1,2})?$",
            ),
            BigipPropertySpec(name="internal", value_type="string"),
            BigipPropertySpec(name="the", value_type="string"),
            BigipPropertySpec(name="local", value_type="string"),
            BigipPropertySpec(name="end", value_type="string"),
            BigipPropertySpec(name="endpoint", value_type="string"),
            BigipPropertySpec(name="mss", value_type="string"),
            BigipPropertySpec(name="external", value_type="string"),
            BigipPropertySpec(name="rtt", value_type="string"),
            BigipPropertySpec(name="network", value_type="string"),
            BigipPropertySpec(name="vlan", value_type="reference", references=("net_vlan",)),
            BigipPropertySpec(name="vlan-id", value_type="reference", references=("net_vlan",)),
            BigipPropertySpec(name="number", value_type="string"),
            BigipPropertySpec(
                name="route-domain", value_type="reference", references=("net_route_domain",)
            ),
            BigipPropertySpec(name="domain", value_type="string"),
            BigipPropertySpec(name="client-ssl", value_type="string"),
            BigipPropertySpec(name="protocol", value_type="string"),
            BigipPropertySpec(name="cipher", value_type="string"),
            BigipPropertySpec(name="cipher-bits", value_type="string"),
            BigipPropertySpec(name="http-method", value_type="string"),
            BigipPropertySpec(name="http-version", value_type="string"),
            BigipPropertySpec(name="major", value_type="string"),
            BigipPropertySpec(name="minor", value_type="boolean"),
            BigipPropertySpec(name="http-status", value_type="string"),
            BigipPropertySpec(name="including", value_type="string"),
            BigipPropertySpec(name="code", value_type="string"),
            BigipPropertySpec(name="text", value_type="string"),
            BigipPropertySpec(name="http-host", value_type="string"),
            BigipPropertySpec(name="http-header", value_type="string"),
            BigipPropertySpec(name="http-referer", value_type="string"),
            BigipPropertySpec(name="numerical", value_type="string"),
            BigipPropertySpec(name="indicate", value_type="string"),
            BigipPropertySpec(name="http-cookie", value_type="string"),
            BigipPropertySpec(name="http-set-cookie", value_type="string"),
            BigipPropertySpec(name="value", value_type="string"),
            BigipPropertySpec(name="version", value_type="string"),
            BigipPropertySpec(name="expiry", value_type="string"),
            BigipPropertySpec(name="in", value_type="string"),
            BigipPropertySpec(name="http-basic-auth", value_type="string"),
            BigipPropertySpec(name="username", value_type="reference", references=("auth_user",)),
            BigipPropertySpec(name="password", value_type="string"),
            BigipPropertySpec(name="http-proxy", value_type="string"),
            BigipPropertySpec(name="http-connect", value_type="string"),
            BigipPropertySpec(name="server-connected", value_type="string"),
            BigipPropertySpec(name="proxy-connect", value_type="string"),
            BigipPropertySpec(name="http-proxy-connect", value_type="list", repeated=True),
            BigipPropertySpec(name="ssl-extension", value_type="string"),
            BigipPropertySpec(name="server-name", value_type="string"),
            BigipPropertySpec(name="npn", value_type="string"),
            BigipPropertySpec(name="alpn", value_type="string"),
            BigipPropertySpec(name="ssl-cert", value_type="string"),
            BigipPropertySpec(name="common-name", value_type="string"),
            BigipPropertySpec(name="geoip", value_type="string"),
            BigipPropertySpec(name="continent", value_type="string"),
            BigipPropertySpec(name="country-code", value_type="string"),
            BigipPropertySpec(name="country-name", value_type="string"),
            BigipPropertySpec(name="region-code", value_type="string"),
            BigipPropertySpec(name="country-specific", value_type="string"),
            BigipPropertySpec(name="region-name", value_type="string"),
            BigipPropertySpec(name="org", value_type="string"),
            BigipPropertySpec(name="isp", value_type="string"),
            BigipPropertySpec(name="cpu-usage", value_type="string"),
            BigipPropertySpec(name="last-15secs", value_type="string"),
            BigipPropertySpec(name="last-1min", value_type="string"),
            BigipPropertySpec(name="last-5mins", value_type="string"),
            BigipPropertySpec(name="http-user-agent", value_type="string"),
            BigipPropertySpec(name="device-make", value_type="string"),
            BigipPropertySpec(name="device-model", value_type="string"),
            BigipPropertySpec(name="browser-type", value_type="string"),
            BigipPropertySpec(name="browser-version", value_type="string"),
            BigipPropertySpec(name="ua-token", value_type="string"),
            BigipPropertySpec(name="specified", value_type="string"),
            BigipPropertySpec(name="websocket", value_type="string"),
            BigipPropertySpec(name="classification", value_type="string"),
            BigipPropertySpec(name="application", value_type="string"),
            BigipPropertySpec(name="application-id", value_type="integer"),
            BigipPropertySpec(name="application-risk", value_type="string"),
            BigipPropertySpec(name="category", value_type="string"),
            BigipPropertySpec(name="category-id", value_type="integer"),
            BigipPropertySpec(name="url-category", value_type="string"),
            BigipPropertySpec(name="url-category-id", value_type="integer"),
            BigipPropertySpec(name="iprep", value_type="string"),
            BigipPropertySpec(name="ip", value_type="string"),
            BigipPropertySpec(name="ssl-server-handshake", value_type="string"),
            BigipPropertySpec(name="proxy-request", value_type="string"),
            BigipPropertySpec(name="ltm-policy", value_type="string"),
            BigipPropertySpec(name="http", value_type="string"),
            BigipPropertySpec(name="replace", value_type="string"),
            BigipPropertySpec(name="command", value_type="string"),
            BigipPropertySpec(name="insert", value_type="string"),
            BigipPropertySpec(name="remove", value_type="string"),
            BigipPropertySpec(name="treated", value_type="string"),
            BigipPropertySpec(name="before", value_type="string"),
            BigipPropertySpec(name="are", value_type="string"),
            BigipPropertySpec(name="expanded", value_type="string"),
            BigipPropertySpec(name="cookie", value_type="string"),
            BigipPropertySpec(name="substitutions", value_type="string"),
            BigipPropertySpec(name="allowed", value_type="string"),
            BigipPropertySpec(name="http-reply", value_type="string"),
            BigipPropertySpec(name="location", value_type="string"),
            BigipPropertySpec(name="redirect", value_type="string"),
            BigipPropertySpec(name="can", value_type="string"),
            BigipPropertySpec(name="request", value_type="string"),
            BigipPropertySpec(name="write", value_type="string"),
            BigipPropertySpec(name="or", value_type="string"),
            BigipPropertySpec(name="message", value_type="string"),
            BigipPropertySpec(name="facility", value_type="string"),
            BigipPropertySpec(name="with", value_type="reference", references=("auth_user",)),
            BigipPropertySpec(name="priority", value_type="string"),
            BigipPropertySpec(name="remote", value_type="string"),
            BigipPropertySpec(name="collect-data", value_type="string"),
            BigipPropertySpec(name="ssl-client-handshake", value_type="string"),
            BigipPropertySpec(name="pem", value_type="string"),
            BigipPropertySpec(name="classify", value_type="string"),
            BigipPropertySpec(name="ce", value_type="string"),
            BigipPropertySpec(name="cache", value_type="string"),
            BigipPropertySpec(name="enable", value_type="string"),
            BigipPropertySpec(name="disable", value_type="string"),
            BigipPropertySpec(name="compress", value_type="string"),
            BigipPropertySpec(name="decompress", value_type="string"),
            BigipPropertySpec(name="forward", value_type="string"),
            BigipPropertySpec(name="select", value_type="string"),
            BigipPropertySpec(name="one", value_type="string"),
            BigipPropertySpec(name="pool", value_type="reference", references=("ltm_pool",)),
            BigipPropertySpec(
                name="fallback-pool", value_type="reference", references=("ltm_pool",)
            ),
            BigipPropertySpec(name="active", value_type="string"),
            BigipPropertySpec(name="clone-pool", value_type="reference", references=("ltm_pool",)),
            BigipPropertySpec(name="node", value_type="boolean"),
            BigipPropertySpec(name="snat", value_type="string"),
            BigipPropertySpec(
                name="snatpool", value_type="reference", references=("ltm_snatpool",)
            ),
            BigipPropertySpec(name="nexthop", value_type="string"),
            BigipPropertySpec(name="connection", value_type="reference", references=("net_vlan",)),
            BigipPropertySpec(name="by", value_type="reference", references=("net_vlan",)),
            BigipPropertySpec(name="virtual", value_type="string"),
            BigipPropertySpec(name="rateclass", value_type="string"),
            BigipPropertySpec(name="reset", value_type="string"),
            BigipPropertySpec(name="shutdown", value_type="string"),
            BigipPropertySpec(
                name="persist",
                value_type="reference",
                references=(
                    "ltm_persistence_cookie",
                    "ltm_persistence_dest_addr",
                    "ltm_persistence_global_settings",
                    "ltm_persistence_hash",
                    "ltm_persistence_host",
                    "ltm_persistence_msrdp",
                    "ltm_persistence_persist_records",
                    "ltm_persistence_sip",
                    "ltm_persistence_source_addr",
                    "ltm_persistence_ssl",
                    "ltm_persistence_universal",
                ),
            ),
            BigipPropertySpec(name="key", value_type="string"),
            BigipPropertySpec(name="src-addr", value_type="string"),
            BigipPropertySpec(name="netmask", value_type="string"),
            BigipPropertySpec(name="timeout", value_type="string"),
            BigipPropertySpec(name="dest-addr", value_type="string"),
            BigipPropertySpec(name="destination", value_type="string"),
            BigipPropertySpec(name="cookie-insert", value_type="string"),
            BigipPropertySpec(name="insertion", value_type="string"),
            BigipPropertySpec(name="cookie-rewrite", value_type="string"),
            BigipPropertySpec(name="rewrite", value_type="string"),
            BigipPropertySpec(name="cookie-passive", value_type="string"),
            BigipPropertySpec(name="passive", value_type="string"),
            BigipPropertySpec(name="cookie-hash", value_type="string"),
            BigipPropertySpec(name="offset", value_type="string"),
            BigipPropertySpec(name="length", value_type="string"),
            BigipPropertySpec(name="universal", value_type="reference", references=("auth_user",)),
            BigipPropertySpec(name="hash", value_type="string"),
            BigipPropertySpec(name="carp", value_type="string"),
            BigipPropertySpec(name="wam", value_type="string"),
            BigipPropertySpec(name="asm", value_type="string"),
            BigipPropertySpec(name="policy", value_type="reference", references=("ltm_policy",)),
            BigipPropertySpec(name="l7dos", value_type="string"),
            BigipPropertySpec(name="from-profile", value_type="string"),
            BigipPropertySpec(name="bot-defense", value_type="string"),
            BigipPropertySpec(name="avr", value_type="string"),
            BigipPropertySpec(name="tcl", value_type="string"),
            BigipPropertySpec(name="expression", value_type="string"),
            BigipPropertySpec(name="set-variable", value_type="string"),
            BigipPropertySpec(name="request-adapt", value_type="string"),
            BigipPropertySpec(name="internal-virtual", value_type="string"),
            BigipPropertySpec(name="response-adapt", value_type="string"),
            BigipPropertySpec(name="tcp-nagle", value_type="string"),
            BigipPropertySpec(name="auto-mode", value_type="string"),
            BigipPropertySpec(name="server-ssl", value_type="string"),
            BigipPropertySpec(name="ssl-intercept", value_type="string"),
            BigipPropertySpec(name="websocket-payload-processing", value_type="string"),
            BigipPropertySpec(name="drop", value_type="string"),
            BigipPropertySpec(name="reject", value_type="string"),
            BigipPropertySpec(name="connector-profile", value_type="string"),
            BigipPropertySpec(name="server-ssl-profile", value_type="string"),
            BigipPropertySpec(name="http-uri-rewrite", value_type="string"),
            BigipPropertySpec(name="retry", value_type="string"),
            BigipPropertySpec(name="log-publisher", value_type="string"),
        ),
    )
