from __future__ import annotations

from ..models import (
    BigipObjectKindSpec,
    BigipObjectSpec,
    BigipPropertySpec,
)
from ._base import register


@register
def register_spec() -> BigipObjectSpec:
    return BigipObjectSpec(
        kind_spec=BigipObjectKindSpec(
            "ltm_pool",
            module="ltm",
            object_types=("pool",),
        ),
        header_types=(("ltm", "pool"),),
        properties=(
            BigipPropertySpec(name="allow-nat", value_type="enum", enum_values=("yes", "no")),
            BigipPropertySpec(name="allow-snat", value_type="enum", enum_values=("yes", "no")),
            BigipPropertySpec(name="autoscale-group-id", value_type="integer", allow_none=True),
            BigipPropertySpec(name="description", value_type="string"),
            BigipPropertySpec(name="gateway-failsafe-device", value_type="string"),
            BigipPropertySpec(
                name="ignore-persisted-weight", value_type="enum", enum_values=("yes", "no")
            ),
            BigipPropertySpec(name="ip-tos-to-client", value_type="integer"),
            BigipPropertySpec(name="ip-tos-to-server", value_type="integer"),
            BigipPropertySpec(name="link-qos-to-client", value_type="integer"),
            BigipPropertySpec(name="link-qos-to-server", value_type="integer"),
            BigipPropertySpec(name="load-balancing-mode", value_type="boolean"),
            BigipPropertySpec(name="fastest-app-response", value_type="boolean"),
            BigipPropertySpec(name="least-connections-members", value_type="string"),
            BigipPropertySpec(name="least-connections-node", value_type="string"),
            BigipPropertySpec(name="least-sessions", value_type="string"),
            BigipPropertySpec(name="observed-member", value_type="boolean"),
            BigipPropertySpec(name="predictive-member", value_type="boolean"),
            BigipPropertySpec(name="ratio-least-connections-member", value_type="string"),
            BigipPropertySpec(name="ratio-least-connections-node", value_type="string"),
            BigipPropertySpec(name="ratio-member", value_type="boolean"),
            BigipPropertySpec(name="round-robin", value_type="string"),
            BigipPropertySpec(
                name="members",
                value_type="reference",
                enum_values=("add", "delete", "modify", "replace-all-with"),
                references=("ltm_node",),
            ),
            BigipPropertySpec(
                name="address",
                value_type="string",
                in_sections=("members",),
                pattern="^(?:\\\\d{1,3}(?:\\\\.\\\\d{1,3}){3})(?:/\\\\d{1,2})?$",
            ),
            BigipPropertySpec(
                name="connection-limit", value_type="integer", in_sections=("members",)
            ),
            BigipPropertySpec(name="description", value_type="string", in_sections=("members",)),
            BigipPropertySpec(name="dynamic-ratio", value_type="integer", in_sections=("members",)),
            BigipPropertySpec(
                name="inherit-profile",
                value_type="enum",
                in_sections=("members",),
                enum_values=("enabled", "disabled"),
            ),
            BigipPropertySpec(
                name="logging",
                value_type="enum",
                in_sections=("members",),
                enum_values=("enabled", "disabled"),
            ),
            BigipPropertySpec(
                name="monitor",
                value_type="reference",
                in_sections=("members",),
                references=(
                    "ltm_monitor_diameter",
                    "ltm_monitor_dns",
                    "ltm_monitor_external",
                    "ltm_monitor_firepass",
                    "ltm_monitor_ftp",
                    "ltm_monitor_gateway_icmp",
                    "ltm_monitor_http",
                    "ltm_monitor_http2",
                    "ltm_monitor_https",
                    "ltm_monitor_icmp",
                    "ltm_monitor_imap",
                    "ltm_monitor_inband",
                    "ltm_monitor_ldap",
                    "ltm_monitor_module_score",
                    "ltm_monitor_mqtt",
                    "ltm_monitor_mssql",
                    "ltm_monitor_mysql",
                    "ltm_monitor_nntp",
                    "ltm_monitor_none",
                    "ltm_monitor_oracle",
                    "ltm_monitor_pop3",
                    "ltm_monitor_postgresql",
                    "ltm_monitor_radius",
                    "ltm_monitor_radius_accounting",
                    "ltm_monitor_real_server",
                    "ltm_monitor_rpc",
                    "ltm_monitor_sasp",
                    "ltm_monitor_scripted",
                    "ltm_monitor_sip",
                    "ltm_monitor_smb",
                    "ltm_monitor_smtp",
                    "ltm_monitor_snmp_dca",
                    "ltm_monitor_snmp_dca_base",
                    "ltm_monitor_soap",
                    "ltm_monitor_tcp",
                    "ltm_monitor_tcp_echo",
                    "ltm_monitor_tcp_half_open",
                    "ltm_monitor_udp",
                    "ltm_monitor_virtual_location",
                    "ltm_monitor_wap",
                    "ltm_monitor_wmi",
                ),
            ),
            BigipPropertySpec(
                name="priority-group", value_type="integer", in_sections=("members",)
            ),
            BigipPropertySpec(
                name="profiles",
                value_type="reference",
                in_sections=("members",),
                allow_none=True,
                references=(
                    "ltm_profile_analytics",
                    "ltm_profile_certificate_authority",
                    "ltm_profile_classification",
                    "ltm_profile_client_ldap",
                    "ltm_profile_client_ssl",
                    "ltm_profile_connector",
                    "ltm_profile_dhcpv4",
                    "ltm_profile_dhcpv6",
                    "ltm_profile_diameter",
                    "ltm_profile_dns",
                    "ltm_profile_dns_logging",
                    "ltm_profile_doh_proxy",
                    "ltm_profile_doh_server",
                    "ltm_profile_fasthttp",
                    "ltm_profile_fastl4",
                    "ltm_profile_fix",
                    "ltm_profile_ftp",
                    "ltm_profile_georedundancy",
                    "ltm_profile_gtp",
                    "ltm_profile_html",
                    "ltm_profile_http",
                    "ltm_profile_http2",
                    "ltm_profile_http3",
                    "ltm_profile_http_compression",
                    "ltm_profile_httprouter",
                    "ltm_profile_icap",
                    "ltm_profile_iiop",
                    "ltm_profile_ilx",
                    "ltm_profile_imap",
                    "ltm_profile_ipother",
                    "ltm_profile_ipsecalg",
                    "ltm_profile_json",
                    "ltm_profile_mapt",
                    "ltm_profile_mblb",
                    "ltm_profile_mqtt",
                    "ltm_profile_mr_ratelimit",
                    "ltm_profile_mr_ratelimit_action",
                    "ltm_profile_mssql",
                    "ltm_profile_netflow",
                    "ltm_profile_ntlm",
                    "ltm_profile_ocsp",
                    "ltm_profile_ocsp_stapling_params",
                    "ltm_profile_one_connect",
                    "ltm_profile_pcp",
                    "ltm_profile_pop3",
                    "ltm_profile_pptp",
                    "ltm_profile_qoe",
                    "ltm_profile_quic",
                    "ltm_profile_radius",
                    "ltm_profile_ramcache",
                    "ltm_profile_request_adapt",
                    "ltm_profile_request_log",
                    "ltm_profile_response_adapt",
                    "ltm_profile_rewrite",
                    "ltm_profile_rtsp",
                    "ltm_profile_sctp",
                    "ltm_profile_server_ldap",
                    "ltm_profile_server_ssl",
                    "ltm_profile_sip",
                    "ltm_profile_smtp",
                    "ltm_profile_smtps",
                    "ltm_profile_socks",
                    "ltm_profile_splitsessionclient",
                    "ltm_profile_splitsessionserver",
                    "ltm_profile_sse",
                    "ltm_profile_statistics",
                    "ltm_profile_stream",
                    "ltm_profile_tcp",
                    "ltm_profile_tcp_analytics",
                    "ltm_profile_tdr",
                    "ltm_profile_tftp",
                    "ltm_profile_traffic_acceleration",
                    "ltm_profile_udp",
                    "ltm_profile_wa_cache",
                    "ltm_profile_web_acceleration",
                    "ltm_profile_web_security",
                    "ltm_profile_websocket",
                    "ltm_profile_xml",
                ),
            ),
            BigipPropertySpec(name="rate-limit", value_type="integer", in_sections=("members",)),
            BigipPropertySpec(name="ratio", value_type="integer", in_sections=("members",)),
            BigipPropertySpec(
                name="session",
                value_type="reference",
                in_sections=("members",),
                enum_values=("user-enabled", "user-disabled"),
                references=("auth_user",),
            ),
            BigipPropertySpec(
                name="state",
                value_type="reference",
                in_sections=("members",),
                enum_values=("user-up", "user-down"),
                references=("auth_user",),
            ),
            BigipPropertySpec(
                name="fqdn",
                value_type="string",
                in_sections=("members",),
                pattern="^(?=.{1,253}$)(?:[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?\\\\.)+[A-Za-z]{2,63}$",
            ),
            BigipPropertySpec(name="name", value_type="string", in_sections=("fqdn",)),
            BigipPropertySpec(
                name="autopopulate",
                value_type="enum",
                in_sections=("fqdn",),
                enum_values=("enabled", "disabled"),
            ),
            BigipPropertySpec(name="value", value_type="string"),
            BigipPropertySpec(
                name="persist",
                value_type="reference",
                enum_values=("true", "false"),
                references=(
                    "ltm_persistence_cookie",
                    "ltm_persistence_dest_addr",
                    "ltm_persistence_global_settings",
                    "ltm_persistence_hash",
                    "ltm_persistence_host",
                    "ltm_persistence_msrdp",
                    "ltm_persistence_persist_records",
                    "ltm_persistence_sip",
                    "ltm_persistence_source_addr",
                    "ltm_persistence_ssl",
                    "ltm_persistence_universal",
                ),
            ),
            BigipPropertySpec(name="min-active-members", value_type="integer"),
            BigipPropertySpec(name="min-up-members", value_type="integer"),
            BigipPropertySpec(
                name="min-up-members-action",
                value_type="enum",
                enum_values=("failover", "reboot", "restart-all"),
            ),
            BigipPropertySpec(
                name="min-up-members-checking",
                value_type="enum",
                enum_values=("enabled", "disabled"),
            ),
            BigipPropertySpec(
                name="monitor",
                value_type="reference",
                references=(
                    "ltm_monitor_diameter",
                    "ltm_monitor_dns",
                    "ltm_monitor_external",
                    "ltm_monitor_firepass",
                    "ltm_monitor_ftp",
                    "ltm_monitor_gateway_icmp",
                    "ltm_monitor_http",
                    "ltm_monitor_http2",
                    "ltm_monitor_https",
                    "ltm_monitor_icmp",
                    "ltm_monitor_imap",
                    "ltm_monitor_inband",
                    "ltm_monitor_ldap",
                    "ltm_monitor_module_score",
                    "ltm_monitor_mqtt",
                    "ltm_monitor_mssql",
                    "ltm_monitor_mysql",
                    "ltm_monitor_nntp",
                    "ltm_monitor_none",
                    "ltm_monitor_oracle",
                    "ltm_monitor_pop3",
                    "ltm_monitor_postgresql",
                    "ltm_monitor_radius",
                    "ltm_monitor_radius_accounting",
                    "ltm_monitor_real_server",
                    "ltm_monitor_rpc",
                    "ltm_monitor_sasp",
                    "ltm_monitor_scripted",
                    "ltm_monitor_sip",
                    "ltm_monitor_smb",
                    "ltm_monitor_smtp",
                    "ltm_monitor_snmp_dca",
                    "ltm_monitor_snmp_dca_base",
                    "ltm_monitor_soap",
                    "ltm_monitor_tcp",
                    "ltm_monitor_tcp_echo",
                    "ltm_monitor_tcp_half_open",
                    "ltm_monitor_udp",
                    "ltm_monitor_virtual_location",
                    "ltm_monitor_wap",
                    "ltm_monitor_wmi",
                ),
            ),
            BigipPropertySpec(
                name="profiles",
                value_type="reference",
                allow_none=True,
                references=(
                    "ltm_profile_analytics",
                    "ltm_profile_certificate_authority",
                    "ltm_profile_classification",
                    "ltm_profile_client_ldap",
                    "ltm_profile_client_ssl",
                    "ltm_profile_connector",
                    "ltm_profile_dhcpv4",
                    "ltm_profile_dhcpv6",
                    "ltm_profile_diameter",
                    "ltm_profile_dns",
                    "ltm_profile_dns_logging",
                    "ltm_profile_doh_proxy",
                    "ltm_profile_doh_server",
                    "ltm_profile_fasthttp",
                    "ltm_profile_fastl4",
                    "ltm_profile_fix",
                    "ltm_profile_ftp",
                    "ltm_profile_georedundancy",
                    "ltm_profile_gtp",
                    "ltm_profile_html",
                    "ltm_profile_http",
                    "ltm_profile_http2",
                    "ltm_profile_http3",
                    "ltm_profile_http_compression",
                    "ltm_profile_httprouter",
                    "ltm_profile_icap",
                    "ltm_profile_iiop",
                    "ltm_profile_ilx",
                    "ltm_profile_imap",
                    "ltm_profile_ipother",
                    "ltm_profile_ipsecalg",
                    "ltm_profile_json",
                    "ltm_profile_mapt",
                    "ltm_profile_mblb",
                    "ltm_profile_mqtt",
                    "ltm_profile_mr_ratelimit",
                    "ltm_profile_mr_ratelimit_action",
                    "ltm_profile_mssql",
                    "ltm_profile_netflow",
                    "ltm_profile_ntlm",
                    "ltm_profile_ocsp",
                    "ltm_profile_ocsp_stapling_params",
                    "ltm_profile_one_connect",
                    "ltm_profile_pcp",
                    "ltm_profile_pop3",
                    "ltm_profile_pptp",
                    "ltm_profile_qoe",
                    "ltm_profile_quic",
                    "ltm_profile_radius",
                    "ltm_profile_ramcache",
                    "ltm_profile_request_adapt",
                    "ltm_profile_request_log",
                    "ltm_profile_response_adapt",
                    "ltm_profile_rewrite",
                    "ltm_profile_rtsp",
                    "ltm_profile_sctp",
                    "ltm_profile_server_ldap",
                    "ltm_profile_server_ssl",
                    "ltm_profile_sip",
                    "ltm_profile_smtp",
                    "ltm_profile_smtps",
                    "ltm_profile_socks",
                    "ltm_profile_splitsessionclient",
                    "ltm_profile_splitsessionserver",
                    "ltm_profile_sse",
                    "ltm_profile_statistics",
                    "ltm_profile_stream",
                    "ltm_profile_tcp",
                    "ltm_profile_tcp_analytics",
                    "ltm_profile_tdr",
                    "ltm_profile_tftp",
                    "ltm_profile_traffic_acceleration",
                    "ltm_profile_udp",
                    "ltm_profile_wa_cache",
                    "ltm_profile_web_acceleration",
                    "ltm_profile_web_security",
                    "ltm_profile_websocket",
                    "ltm_profile_xml",
                ),
            ),
            BigipPropertySpec(
                name="queue-on-connection-limit",
                value_type="enum",
                enum_values=("enabled", "disabled"),
            ),
            BigipPropertySpec(name="queue-depth-limit", value_type="integer"),
            BigipPropertySpec(name="queue-time-limit", value_type="integer"),
            BigipPropertySpec(name="reselect-tries", value_type="integer"),
            BigipPropertySpec(
                name="service-down-action",
                value_type="enum",
                allow_none=True,
                enum_values=("drop", "none", "reselect", "reset"),
            ),
            BigipPropertySpec(name="slow-ramp-time", value_type="integer"),
            BigipPropertySpec(name="reset-stats", value_type="string"),
        ),
    )
