from __future__ import annotations

from ..models import (
    BigipObjectKindSpec,
    BigipObjectSpec,
    BigipPropertySpec,
)
from ._base import register


@register
def register_spec() -> BigipObjectSpec:
    return BigipObjectSpec(
        kind_spec=BigipObjectKindSpec(
            "ltm_virtual",
            module="ltm",
            object_types=("virtual",),
        ),
        header_types=(("ltm", "virtual"),),
        properties=(
            BigipPropertySpec(name="address-status", value_type="enum", enum_values=("yes", "no")),
            BigipPropertySpec(
                name="auth", value_type="enum", enum_values=("add", "delete", "replace-all-with")
            ),
            BigipPropertySpec(
                name="auto-discovery", value_type="enum", enum_values=("enabled", "disabled")
            ),
            BigipPropertySpec(
                name="auto-lasthop",
                value_type="enum",
                enum_values=("default", "enabled", "disabled"),
            ),
            BigipPropertySpec(
                name="clone-pools",
                value_type="enum",
                enum_values=("add", "delete", "replace-all-with"),
            ),
            BigipPropertySpec(
                name="context",
                value_type="enum",
                in_sections=("clone-pools",),
                enum_values=("clientside", "serverside"),
            ),
            BigipPropertySpec(name="cmp-enabled", value_type="enum", enum_values=("yes", "no")),
            BigipPropertySpec(name="connection-limit", value_type="integer"),
            BigipPropertySpec(name="description", value_type="string"),
            BigipPropertySpec(
                name="destination", value_type="reference", references=("ltm_virtual_address",)
            ),
            BigipPropertySpec(
                name="eviction-protected", value_type="enum", enum_values=("enabled", "disabled")
            ),
            BigipPropertySpec(
                name="fallback-persistence",
                value_type="reference",
                allow_none=True,
                references=(
                    "ltm_persistence_cookie",
                    "ltm_persistence_dest_addr",
                    "ltm_persistence_global_settings",
                    "ltm_persistence_hash",
                    "ltm_persistence_host",
                    "ltm_persistence_msrdp",
                    "ltm_persistence_persist_records",
                    "ltm_persistence_sip",
                    "ltm_persistence_source_addr",
                    "ltm_persistence_ssl",
                    "ltm_persistence_universal",
                ),
            ),
            BigipPropertySpec(name="flow-eviction-policy", value_type="boolean", allow_none=True),
            BigipPropertySpec(
                name="fw-enforced-policy",
                value_type="reference",
                allow_none=True,
                references=("security_firewall_policy", "ltm_policy"),
            ),
            BigipPropertySpec(
                name="fw-staged-policy",
                value_type="reference",
                allow_none=True,
                references=("security_firewall_policy", "ltm_policy"),
            ),
            BigipPropertySpec(name="gtm-score", value_type="integer"),
            BigipPropertySpec(
                name="ip-protocol", value_type="enum", enum_values=("any", "protocol")
            ),
            BigipPropertySpec(
                name="last-hop-pool",
                value_type="reference",
                allow_none=True,
                references=("ltm_pool",),
            ),
            BigipPropertySpec(name="mask", value_type="list", repeated=True),
            BigipPropertySpec(
                name="mirror",
                value_type="enum",
                repeated=True,
                allow_none=True,
                enum_values=("disabled", "enabled", "none"),
            ),
            BigipPropertySpec(name="nat64", value_type="enum", enum_values=("enabled", "disabled")),
            BigipPropertySpec(
                name="per-flow-request-access-policy", value_type="boolean", allow_none=True
            ),
            BigipPropertySpec(
                name="persist",
                value_type="reference",
                references=(
                    "ltm_persistence_cookie",
                    "ltm_persistence_dest_addr",
                    "ltm_persistence_global_settings",
                    "ltm_persistence_hash",
                    "ltm_persistence_host",
                    "ltm_persistence_msrdp",
                    "ltm_persistence_persist_records",
                    "ltm_persistence_sip",
                    "ltm_persistence_source_addr",
                    "ltm_persistence_ssl",
                    "ltm_persistence_universal",
                ),
            ),
            BigipPropertySpec(
                name="default",
                value_type="enum",
                in_sections=("persist",),
                enum_values=("no", "yes"),
            ),
            BigipPropertySpec(
                name="policies",
                value_type="reference",
                enum_values=("add", "delete", "replace-all-with"),
                references=("ltm_policy",),
            ),
            BigipPropertySpec(
                name="pool", value_type="reference", allow_none=True, references=("ltm_pool",)
            ),
            BigipPropertySpec(
                name="profiles",
                value_type="reference",
                enum_values=("add", "delete", "replace-all-with"),
                references=(
                    "ltm_profile_analytics",
                    "ltm_profile_certificate_authority",
                    "ltm_profile_classification",
                    "ltm_profile_client_ldap",
                    "ltm_profile_client_ssl",
                    "ltm_profile_connector",
                    "ltm_profile_dhcpv4",
                    "ltm_profile_dhcpv6",
                    "ltm_profile_diameter",
                    "ltm_profile_dns",
                    "ltm_profile_dns_logging",
                    "ltm_profile_doh_proxy",
                    "ltm_profile_doh_server",
                    "ltm_profile_fasthttp",
                    "ltm_profile_fastl4",
                    "ltm_profile_fix",
                    "ltm_profile_ftp",
                    "ltm_profile_georedundancy",
                    "ltm_profile_gtp",
                    "ltm_profile_html",
                    "ltm_profile_http",
                    "ltm_profile_http2",
                    "ltm_profile_http3",
                    "ltm_profile_http_compression",
                    "ltm_profile_httprouter",
                    "ltm_profile_icap",
                    "ltm_profile_iiop",
                    "ltm_profile_ilx",
                    "ltm_profile_imap",
                    "ltm_profile_ipother",
                    "ltm_profile_ipsecalg",
                    "ltm_profile_json",
                    "ltm_profile_mapt",
                    "ltm_profile_mblb",
                    "ltm_profile_mqtt",
                    "ltm_profile_mr_ratelimit",
                    "ltm_profile_mr_ratelimit_action",
                    "ltm_profile_mssql",
                    "ltm_profile_netflow",
                    "ltm_profile_ntlm",
                    "ltm_profile_ocsp",
                    "ltm_profile_ocsp_stapling_params",
                    "ltm_profile_one_connect",
                    "ltm_profile_pcp",
                    "ltm_profile_pop3",
                    "ltm_profile_pptp",
                    "ltm_profile_qoe",
                    "ltm_profile_quic",
                    "ltm_profile_radius",
                    "ltm_profile_ramcache",
                    "ltm_profile_request_adapt",
                    "ltm_profile_request_log",
                    "ltm_profile_response_adapt",
                    "ltm_profile_rewrite",
                    "ltm_profile_rtsp",
                    "ltm_profile_sctp",
                    "ltm_profile_server_ldap",
                    "ltm_profile_server_ssl",
                    "ltm_profile_sip",
                    "ltm_profile_smtp",
                    "ltm_profile_smtps",
                    "ltm_profile_socks",
                    "ltm_profile_splitsessionclient",
                    "ltm_profile_splitsessionserver",
                    "ltm_profile_sse",
                    "ltm_profile_statistics",
                    "ltm_profile_stream",
                    "ltm_profile_tcp",
                    "ltm_profile_tcp_analytics",
                    "ltm_profile_tdr",
                    "ltm_profile_tftp",
                    "ltm_profile_traffic_acceleration",
                    "ltm_profile_udp",
                    "ltm_profile_wa_cache",
                    "ltm_profile_web_acceleration",
                    "ltm_profile_web_security",
                    "ltm_profile_websocket",
                    "ltm_profile_xml",
                ),
            ),
            BigipPropertySpec(
                name="context",
                value_type="enum",
                in_sections=("profiles",),
                enum_values=("all", "clientside", "serverside"),
            ),
            BigipPropertySpec(name="rate-class", value_type="string"),
            BigipPropertySpec(name="rate-limit", value_type="integer"),
            BigipPropertySpec(name="rate-limit-mode", value_type="string"),
            BigipPropertySpec(name="object-source", value_type="string"),
            BigipPropertySpec(name="rate-limit-dst", value_type="integer"),
            BigipPropertySpec(name="rate-limit-src", value_type="integer"),
            BigipPropertySpec(
                name="related-rules",
                value_type="reference",
                repeated=True,
                allow_none=True,
                references=("ltm_rule",),
            ),
            BigipPropertySpec(
                name="rules",
                value_type="reference",
                repeated=True,
                allow_none=True,
                references=("ltm_rule",),
            ),
            BigipPropertySpec(
                name="security-nat-policy",
                value_type="reference",
                references=("security_nat_policy",),
            ),
            BigipPropertySpec(
                name="policy",
                value_type="reference",
                in_sections=("security-nat-policy",),
                allow_none=True,
                references=("security_nat_policy", "ltm_policy"),
            ),
            BigipPropertySpec(
                name="use-device-policy",
                value_type="enum",
                in_sections=("security-nat-policy",),
                enum_values=("no", "yes"),
            ),
            BigipPropertySpec(
                name="use-route-domain-policy",
                value_type="enum",
                in_sections=("security-nat-policy",),
                enum_values=("no", "yes"),
            ),
            BigipPropertySpec(
                name="serverssl-use-sni", value_type="enum", enum_values=("enabled", "disabled")
            ),
            BigipPropertySpec(
                name="service-down-immediate-action",
                value_type="enum",
                allow_none=True,
                enum_values=("none", "drop", "reset"),
            ),
            BigipPropertySpec(
                name="service-policy",
                value_type="reference",
                allow_none=True,
                references=("security_firewall_policy", "ltm_policy"),
            ),
            BigipPropertySpec(
                name="snat", value_type="enum", allow_none=True, enum_values=("automap", "none")
            ),
            BigipPropertySpec(
                name="snatpool", value_type="reference", references=("ltm_snatpool",)
            ),
            BigipPropertySpec(name="source", value_type="list", repeated=True),
            BigipPropertySpec(name="source-address-translation", value_type="string"),
            BigipPropertySpec(
                name="pool",
                value_type="reference",
                in_sections=("source-address-translation",),
                allow_none=True,
                references=("ltm_snatpool", "ltm_pool"),
            ),
            BigipPropertySpec(
                name="type",
                value_type="enum",
                in_sections=("source-address-translation",),
                allow_none=True,
                enum_values=("automap", "lsn", "snat", "none"),
            ),
            BigipPropertySpec(
                name="source-port",
                value_type="enum",
                enum_values=("change", "preserve", "preserve-strict"),
                min_value=0,
                max_value=65535,
            ),
            BigipPropertySpec(
                name="traffic-classes",
                value_type="enum",
                enum_values=("add", "delete", "replace-all-with"),
            ),
            BigipPropertySpec(
                name="translate-address",
                value_type="enum",
                enum_values=("enabled", "disabled"),
                pattern="^(?:\\\\d{1,3}(?:\\\\.\\\\d{1,3}){3})(?:/\\\\d{1,2})?$",
            ),
            BigipPropertySpec(
                name="translate-port",
                value_type="enum",
                enum_values=("enabled", "disabled"),
                min_value=0,
                max_value=65535,
            ),
            BigipPropertySpec(
                name="transparent-nexthop", value_type="reference", references=("net_vlan",)
            ),
            BigipPropertySpec(
                name="vlans",
                value_type="reference",
                enum_values=("add", "delete", "replace-all-with"),
                references=("net_vlan",),
            ),
            BigipPropertySpec(
                name="metadata", value_type="enum", enum_values=("add", "delete", "modify")
            ),
            BigipPropertySpec(name="value", value_type="string", in_sections=("metadata",)),
            BigipPropertySpec(
                name="persist",
                value_type="reference",
                in_sections=("metadata",),
                enum_values=("true", "false"),
                references=(
                    "ltm_persistence_cookie",
                    "ltm_persistence_dest_addr",
                    "ltm_persistence_global_settings",
                    "ltm_persistence_hash",
                    "ltm_persistence_host",
                    "ltm_persistence_msrdp",
                    "ltm_persistence_persist_records",
                    "ltm_persistence_sip",
                    "ltm_persistence_source_addr",
                    "ltm_persistence_ssl",
                    "ltm_persistence_universal",
                ),
            ),
            BigipPropertySpec(name="reset-stats", value_type="list", repeated=True),
            BigipPropertySpec(
                name="fw-enforced-policy-rules",
                value_type="reference",
                repeated=True,
                references=("ltm_rule",),
            ),
            BigipPropertySpec(
                name="fw-staged-policy-rules",
                value_type="reference",
                repeated=True,
                references=("ltm_rule",),
            ),
            BigipPropertySpec(
                name="security-nat-rules",
                value_type="reference",
                repeated=True,
                references=("ltm_rule",),
            ),
            BigipPropertySpec(name="yotta", value_type="string"),
        ),
    )
