from __future__ import annotations

from ..models import (
    BigipObjectKindSpec,
    BigipObjectSpec,
    BigipPropertySpec,
)
from ._base import register


@register
def register_spec() -> BigipObjectSpec:
    return BigipObjectSpec(
        kind_spec=BigipObjectKindSpec(
            "pem_policy",
            module="pem",
            object_types=("policy",),
        ),
        header_types=(("pem", "policy"),),
        properties=(
            BigipPropertySpec(name="description", value_type="string"),
            BigipPropertySpec(
                name="rules",
                value_type="list",
                references=(
                    "gtm_rule",
                    "ltm_cipher_rule",
                    "ltm_global_settings_rule",
                    "ltm_rule",
                    "ltm_rule_profiler",
                    "security_firewall_matching_rule",
                    "security_firewall_on_demand_rule_deploy",
                    "security_firewall_rule_list",
                    "security_firewall_rule_stat",
                    "security_packet_filter_rule_stat",
                    "sys_file_rewrite_rule",
                ),
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="app-service",
                value_type="string",
                in_sections=("rules",),
                allow_none=True,
            ),
            BigipPropertySpec(
                name="classification-filters",
                value_type="list",
                in_sections=("rules",),
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="app-service",
                value_type="string",
                in_sections=("rules", "classification-filters"),
                allow_none=True,
            ),
            BigipPropertySpec(
                name="application",
                value_type="reference",
                in_sections=("rules", "classification-filters"),
                references=(
                    "analytics_application_security_anomalies_report",
                    "analytics_application_security_anomalies_scheduled_report",
                    "analytics_application_security_incidents_report",
                    "analytics_application_security_network_report",
                    "analytics_application_security_network_scheduled_report",
                    "analytics_application_security_report",
                    "analytics_application_security_scheduled_report",
                    "ltm_classification_application",
                    "ltm_classification_stats_application",
                    "sys_application_apl_script",
                    "sys_application_custom_stat",
                    "sys_application_service",
                    "sys_application_template",
                    "sys_disk_application_volume",
                    "wam_application",
                ),
            ),
            BigipPropertySpec(
                name="category",
                value_type="reference",
                in_sections=("rules", "classification-filters"),
                references=(
                    "ltm_classification_category",
                    "ltm_classification_stats_url_category",
                    "ltm_classification_url_category",
                    "security_blacklist_publisher_by_category",
                    "security_blacklist_publisher_category",
                    "security_bot_defense_anomaly_category",
                    "security_bot_defense_signature_category",
                    "security_dos_bot_signature_category",
                    "security_firewall_ipi_category_info",
                    "security_ip_intelligence_blacklist_category",
                    "security_scrubber_dwbl_scrubber_category_stats",
                    "sys_url_db_url_category",
                ),
            ),
            BigipPropertySpec(
                name="operation",
                value_type="enum",
                in_sections=("rules", "classification-filters"),
                enum_values=("match", "nomatch"),
            ),
            BigipPropertySpec(name="deprecated", value_type="unknown", in_sections=("rules",)),
            BigipPropertySpec(
                name="dscp-marking-downlink",
                value_type="integer",
                in_sections=("rules",),
            ),
            BigipPropertySpec(
                name="dscp-marking-uplink",
                value_type="integer",
                in_sections=("rules",),
            ),
            BigipPropertySpec(name="dtos-tethering", value_type="unknown", in_sections=("rules",)),
            BigipPropertySpec(
                name="dtos-detect",
                value_type="enum",
                in_sections=("rules", "dtos-tethering"),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="report",
                value_type="unknown",
                in_sections=("rules", "dtos-tethering"),
            ),
            BigipPropertySpec(
                name="dest",
                value_type="unknown",
                in_sections=("rules", "dtos-tethering", "report"),
            ),
            BigipPropertySpec(
                name="hsl",
                value_type="unknown",
                in_sections=("rules", "dtos-tethering", "report", "dest"),
            ),
            BigipPropertySpec(
                name="format-script",
                value_type="reference",
                in_sections=("rules", "dtos-tethering", "report", "dest", "hsl"),
                allow_none=True,
                references=("pem_reporting_format_script",),
            ),
            BigipPropertySpec(
                name="publisher",
                value_type="reference",
                in_sections=("rules", "dtos-tethering", "report", "dest", "hsl"),
                allow_none=True,
                references=(
                    "security_blacklist_publisher_all_blacklist_publisher",
                    "security_blacklist_publisher_blacklist_publisher_stats",
                    "security_blacklist_publisher_by_addr",
                    "security_blacklist_publisher_by_category",
                    "security_blacklist_publisher_category",
                    "security_blacklist_publisher_profile",
                    "sys_icall_publisher",
                    "sys_log_config_publisher",
                ),
            ),
            BigipPropertySpec(
                name="tethering-detect",
                value_type="enum",
                in_sections=("rules", "dtos-tethering"),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="flow-info-filters",
                value_type="list",
                in_sections=("rules",),
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="app-service",
                value_type="string",
                in_sections=("rules", "flow-info-filters"),
                allow_none=True,
            ),
            BigipPropertySpec(
                name="dscp-code",
                value_type="integer",
                in_sections=("rules", "flow-info-filters"),
            ),
            BigipPropertySpec(
                name="dst-ip-addr",
                value_type="string",
                in_sections=("rules", "flow-info-filters"),
            ),
            BigipPropertySpec(
                name="dst-port",
                value_type="unknown",
                in_sections=("rules", "flow-info-filters"),
            ),
            BigipPropertySpec(
                name="ecn-detection",
                value_type="enum",
                in_sections=("rules", "flow-info-filters"),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="from-vlan",
                value_type="reference",
                in_sections=("rules", "flow-info-filters"),
                references=(
                    "net_fdb_vlan",
                    "net_vlan",
                    "net_vlan_allowed",
                    "net_vlan_group",
                    "sys_sflow_data_source_vlan",
                    "sys_sflow_global_settings_vlan",
                ),
            ),
            BigipPropertySpec(
                name="ip-addr-type",
                value_type="enum",
                in_sections=("rules", "flow-info-filters"),
                enum_values=("IPv4", "IPv6", "any"),
            ),
            BigipPropertySpec(
                name="l2-endpoint",
                value_type="enum",
                in_sections=("rules", "flow-info-filters"),
                enum_values=("disabled", "vlan"),
            ),
            BigipPropertySpec(
                name="operation",
                value_type="enum",
                in_sections=("rules", "flow-info-filters"),
                enum_values=("match", "nomatch"),
            ),
            BigipPropertySpec(
                name="proto",
                value_type="enum",
                in_sections=("rules", "flow-info-filters"),
                enum_values=("any", "tcp", "udp"),
            ),
            BigipPropertySpec(
                name="src-ip-addr",
                value_type="string",
                in_sections=("rules", "flow-info-filters"),
            ),
            BigipPropertySpec(
                name="src-port",
                value_type="unknown",
                in_sections=("rules", "flow-info-filters"),
            ),
            BigipPropertySpec(name="forwarding", value_type="unknown", in_sections=("rules",)),
            BigipPropertySpec(
                name="endpoint",
                value_type="reference",
                in_sections=("rules", "forwarding"),
                references=("pem_forwarding_endpoint",),
            ),
            BigipPropertySpec(
                name="fallback-action",
                value_type="enum",
                in_sections=("rules", "forwarding"),
                enum_values=("continue", "default", "drop", "is"),
            ),
            BigipPropertySpec(
                name="icap-type",
                value_type="enum",
                in_sections=("rules", "forwarding"),
                allow_none=True,
                enum_values=("both", "none", "request", "response"),
            ),
            BigipPropertySpec(
                name="internal-virtual",
                value_type="reference",
                in_sections=("rules", "forwarding"),
            ),
            BigipPropertySpec(
                name="type",
                value_type="enum",
                in_sections=("rules", "forwarding"),
                allow_none=True,
                enum_values=("icap", "none", "pool", "route-to-network"),
            ),
            BigipPropertySpec(
                name="gate-status",
                value_type="enum",
                in_sections=("rules",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(name="http-redirect", value_type="unknown", in_sections=("rules",)),
            BigipPropertySpec(
                name="fallback-action",
                value_type="enum",
                in_sections=("rules", "http-redirect"),
                enum_values=("continue", "default", "drop", "is"),
            ),
            BigipPropertySpec(
                name="redirect-url",
                value_type="string",
                in_sections=("rules", "http-redirect"),
            ),
            BigipPropertySpec(name="insert-content", value_type="unknown", in_sections=("rules",)),
            BigipPropertySpec(
                name="duration",
                value_type="integer",
                in_sections=("rules", "insert-content"),
            ),
            BigipPropertySpec(
                name="frequency",
                value_type="enum",
                in_sections=("rules", "insert-content"),
                enum_values=("always", "once", "once-every"),
            ),
            BigipPropertySpec(
                name="position",
                value_type="enum",
                in_sections=("rules", "insert-content"),
                enum_values=("append", "prepend"),
            ),
            BigipPropertySpec(
                name="value-content",
                value_type="string",
                in_sections=("rules", "insert-content"),
            ),
            BigipPropertySpec(
                name="value-type",
                value_type="enum",
                in_sections=("rules", "insert-content"),
                enum_values=("tcl-snippet",),
            ),
            BigipPropertySpec(name="intercept", value_type="reference", in_sections=("rules",)),
            BigipPropertySpec(
                name="l2-marking-downlink",
                value_type="integer",
                in_sections=("rules",),
            ),
            BigipPropertySpec(
                name="l2-marking-uplink",
                value_type="integer",
                in_sections=("rules",),
            ),
            BigipPropertySpec(name="modify-http-hdr", value_type="unknown", in_sections=("rules",)),
            BigipPropertySpec(
                name="operation",
                value_type="enum",
                in_sections=("rules", "modify-http-hdr"),
                allow_none=True,
                enum_values=("insert", "none", "remove"),
            ),
            BigipPropertySpec(
                name="value-content",
                value_type="unknown",
                in_sections=("rules", "modify-http-hdr"),
            ),
            BigipPropertySpec(
                name="value-type",
                value_type="enum",
                in_sections=("rules", "modify-http-hdr"),
                enum_values=("tcl-snippet",),
            ),
            BigipPropertySpec(name="precedence", value_type="integer", in_sections=("rules",)),
            BigipPropertySpec(name="qoe-reporting", value_type="unknown", in_sections=("rules",)),
            BigipPropertySpec(
                name="dest",
                value_type="unknown",
                in_sections=("rules", "qoe-reporting"),
            ),
            BigipPropertySpec(
                name="hsl",
                value_type="unknown",
                in_sections=("rules", "qoe-reporting", "dest"),
            ),
            BigipPropertySpec(
                name="format-script",
                value_type="reference",
                in_sections=("rules", "qoe-reporting", "dest", "hsl"),
                allow_none=True,
                references=("pem_reporting_format_script",),
            ),
            BigipPropertySpec(
                name="publisher",
                value_type="reference",
                in_sections=("rules", "qoe-reporting", "dest", "hsl"),
                allow_none=True,
                references=(
                    "security_blacklist_publisher_all_blacklist_publisher",
                    "security_blacklist_publisher_blacklist_publisher_stats",
                    "security_blacklist_publisher_by_addr",
                    "security_blacklist_publisher_by_category",
                    "security_blacklist_publisher_category",
                    "security_blacklist_publisher_profile",
                    "sys_icall_publisher",
                    "sys_log_config_publisher",
                ),
            ),
            BigipPropertySpec(
                name="qos-rate-pir-downlink",
                value_type="reference",
                in_sections=("rules",),
                allow_none=True,
                enum_values=("none",),
            ),
            BigipPropertySpec(
                name="qos-rate-pir-uplink",
                value_type="reference",
                in_sections=("rules",),
                allow_none=True,
                enum_values=("none",),
            ),
            BigipPropertySpec(name="quota", value_type="unknown", in_sections=("rules",)),
            BigipPropertySpec(
                name="rating-group",
                value_type="reference",
                in_sections=("rules", "quota"),
                references=("pem_quota_mgmt_rating_group",),
            ),
            BigipPropertySpec(
                name="reporting-level",
                value_type="enum",
                in_sections=("rules", "quota"),
                enum_values=("rating-group", "service-id"),
            ),
            BigipPropertySpec(name="ran-congestion", value_type="unknown", in_sections=("rules",)),
            BigipPropertySpec(
                name="detect",
                value_type="enum",
                in_sections=("rules", "ran-congestion"),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="lowerthreshold-bw",
                value_type="integer",
                in_sections=("rules", "ran-congestion"),
            ),
            BigipPropertySpec(
                name="report",
                value_type="unknown",
                in_sections=("rules", "ran-congestion"),
            ),
            BigipPropertySpec(
                name="dest",
                value_type="unknown",
                in_sections=("rules", "ran-congestion", "report"),
            ),
            BigipPropertySpec(
                name="hsl",
                value_type="unknown",
                in_sections=("rules", "ran-congestion", "report", "dest"),
            ),
            BigipPropertySpec(
                name="format-script",
                value_type="reference",
                in_sections=("rules", "ran-congestion", "report", "dest", "hsl"),
                allow_none=True,
                references=("pem_reporting_format_script",),
            ),
            BigipPropertySpec(
                name="publisher",
                value_type="reference",
                in_sections=("rules", "ran-congestion", "report", "dest", "hsl"),
                allow_none=True,
                references=(
                    "security_blacklist_publisher_all_blacklist_publisher",
                    "security_blacklist_publisher_blacklist_publisher_stats",
                    "security_blacklist_publisher_by_addr",
                    "security_blacklist_publisher_by_category",
                    "security_blacklist_publisher_category",
                    "security_blacklist_publisher_profile",
                    "sys_icall_publisher",
                    "sys_log_config_publisher",
                ),
            ),
            BigipPropertySpec(name="reporting", value_type="unknown", in_sections=("rules",)),
            BigipPropertySpec(
                name="dest",
                value_type="unknown",
                in_sections=("rules", "reporting"),
            ),
            BigipPropertySpec(
                name="gx",
                value_type="unknown",
                in_sections=("rules", "reporting", "dest"),
            ),
            BigipPropertySpec(
                name="application-reporting",
                value_type="enum",
                in_sections=("rules", "reporting", "dest", "gx"),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="monitoring-key",
                value_type="reference",
                in_sections=("rules", "reporting", "dest", "gx"),
            ),
            BigipPropertySpec(
                name="hsl",
                value_type="unknown",
                in_sections=("rules", "reporting", "dest"),
            ),
            BigipPropertySpec(
                name="flow-reporting-fields",
                value_type="unknown",
                in_sections=("rules", "reporting", "dest", "hsl"),
            ),
            BigipPropertySpec(
                name="format-script",
                value_type="reference",
                in_sections=("rules", "reporting", "dest", "hsl"),
                references=("pem_reporting_format_script",),
            ),
            BigipPropertySpec(
                name="publisher",
                value_type="reference",
                in_sections=("rules", "reporting", "dest", "hsl"),
                references=(
                    "security_blacklist_publisher_all_blacklist_publisher",
                    "security_blacklist_publisher_blacklist_publisher_stats",
                    "security_blacklist_publisher_by_addr",
                    "security_blacklist_publisher_by_category",
                    "security_blacklist_publisher_category",
                    "security_blacklist_publisher_profile",
                    "sys_icall_publisher",
                    "sys_log_config_publisher",
                ),
            ),
            BigipPropertySpec(
                name="session-reporting-fields",
                value_type="unknown",
                in_sections=("rules", "reporting", "dest", "hsl"),
            ),
            BigipPropertySpec(
                name="transaction-reporting-fields",
                value_type="unknown",
                in_sections=("rules", "reporting", "dest", "hsl"),
            ),
            BigipPropertySpec(
                name="radius-accounting",
                value_type="unknown",
                in_sections=("rules", "reporting", "dest"),
            ),
            BigipPropertySpec(
                name="radius-aaa-virtual",
                value_type="reference",
                in_sections=("rules", "reporting", "dest", "radius-accounting"),
            ),
            BigipPropertySpec(
                name="sd",
                value_type="unknown",
                in_sections=("rules", "reporting", "dest"),
            ),
            BigipPropertySpec(
                name="application-reporting",
                value_type="enum",
                in_sections=("rules", "reporting", "dest", "sd"),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="monitoring-key",
                value_type="reference",
                in_sections=("rules", "reporting", "dest", "sd"),
            ),
            BigipPropertySpec(
                name="granularity",
                value_type="enum",
                in_sections=("rules", "reporting"),
                enum_values=("flow", "session", "transaction"),
            ),
            BigipPropertySpec(
                name="interval",
                value_type="integer",
                in_sections=("rules", "reporting"),
            ),
            BigipPropertySpec(
                name="transaction",
                value_type="unknown",
                in_sections=("rules", "reporting"),
            ),
            BigipPropertySpec(
                name="http",
                value_type="unknown",
                in_sections=("rules", "reporting", "transaction"),
            ),
            BigipPropertySpec(
                name="hostname-len",
                value_type="integer",
                in_sections=("rules", "reporting", "transaction", "http"),
            ),
            BigipPropertySpec(
                name="uri-len",
                value_type="integer",
                in_sections=("rules", "reporting", "transaction", "http"),
            ),
            BigipPropertySpec(
                name="user-agent-len",
                value_type="integer",
                in_sections=("rules", "reporting", "transaction", "http"),
            ),
            BigipPropertySpec(
                name="volume",
                value_type="unknown",
                in_sections=("rules", "reporting"),
            ),
            BigipPropertySpec(
                name="downlink",
                value_type="unknown",
                in_sections=("rules", "reporting", "volume"),
            ),
            BigipPropertySpec(
                name="total",
                value_type="unknown",
                in_sections=("rules", "reporting", "volume"),
            ),
            BigipPropertySpec(
                name="uplink",
                value_type="unknown",
                in_sections=("rules", "reporting", "volume"),
            ),
            BigipPropertySpec(name="service-chain", value_type="reference", in_sections=("rules",)),
            BigipPropertySpec(name="sfc-action", value_type="unknown", in_sections=("rules",)),
            BigipPropertySpec(
                name="metadata-template",
                value_type="string",
                in_sections=("rules", "sfc-action"),
            ),
            BigipPropertySpec(
                name="path-name",
                value_type="string",
                in_sections=("rules", "sfc-action"),
            ),
            BigipPropertySpec(name="tcl-filter", value_type="unknown", in_sections=("rules",)),
            BigipPropertySpec(
                name="tcp-analytics-enable",
                value_type="enum",
                in_sections=("rules",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="tcp-optimization-downlink",
                value_type="string",
                in_sections=("rules",),
            ),
            BigipPropertySpec(
                name="tcp-optimization-uplink",
                value_type="string",
                in_sections=("rules",),
            ),
            BigipPropertySpec(
                name="url-categorization-filters",
                value_type="list",
                in_sections=("rules",),
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="category",
                value_type="reference",
                in_sections=("rules", "url-categorization-filters"),
                references=(
                    "ltm_classification_category",
                    "ltm_classification_stats_url_category",
                    "ltm_classification_url_category",
                    "security_blacklist_publisher_by_category",
                    "security_blacklist_publisher_category",
                    "security_bot_defense_anomaly_category",
                    "security_bot_defense_signature_category",
                    "security_dos_bot_signature_category",
                    "security_firewall_ipi_category_info",
                    "security_ip_intelligence_blacklist_category",
                    "security_scrubber_dwbl_scrubber_category_stats",
                    "sys_url_db_url_category",
                ),
            ),
            BigipPropertySpec(
                name="operation",
                value_type="enum",
                in_sections=("rules", "url-categorization-filters"),
                enum_values=("match", "nomatch"),
            ),
            BigipPropertySpec(
                name="status",
                value_type="enum",
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="transactional",
                value_type="enum",
                enum_values=("disabled", "enabled"),
            ),
        ),
    )
