from __future__ import annotations

from ..models import (
    BigipObjectKindSpec,
    BigipObjectSpec,
    BigipPropertySpec,
)
from ._base import register


@register
def register_spec() -> BigipObjectSpec:
    return BigipObjectSpec(
        kind_spec=BigipObjectKindSpec(
            "saas_bd_profile",
            module="saas",
            object_types=("bd profile",),
        ),
        header_types=(("saas", "bd profile"),),
        properties=(
            BigipPropertySpec(name="allow-headers", value_type="list"),
            BigipPropertySpec(
                name="allow-ip-addresses",
                value_type="list",
                allow_none=True,
                list_operators=frozenset(("add", "delete", "replace-all-with")),
            ),
            BigipPropertySpec(name="api-auth-key", value_type="string", allow_none=True),
            BigipPropertySpec(name="api-hostname", value_type="string"),
            BigipPropertySpec(name="api-key", value_type="string"),
            BigipPropertySpec(name="app-service", value_type="string", allow_none=True),
            BigipPropertySpec(name="application-id", value_type="string", allow_none=True),
            BigipPropertySpec(
                name="bigip-handles-js-injections",
                value_type="enum",
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(name="block-response-body", value_type="string", allow_none=True),
            BigipPropertySpec(name="block-response-code", value_type="integer", allow_none=True),
            BigipPropertySpec(
                name="block-response-content-type",
                value_type="string",
                allow_none=True,
            ),
            BigipPropertySpec(
                name="block-responses",
                value_type="list",
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="app-service",
                value_type="string",
                in_sections=("block-responses",),
                allow_none=True,
            ),
            BigipPropertySpec(
                name="block-response-body",
                value_type="string",
                in_sections=("block-responses",),
                allow_none=True,
            ),
            BigipPropertySpec(
                name="block-response-code",
                value_type="integer",
                in_sections=("block-responses",),
                allow_none=True,
            ),
            BigipPropertySpec(
                name="block-response-content-type",
                value_type="string",
                in_sections=("block-responses",),
                allow_none=True,
            ),
            BigipPropertySpec(
                name="cors-support",
                value_type="enum",
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(name="dashboard-link", value_type="string", allow_none=True),
            BigipPropertySpec(
                name="defaults-from",
                value_type="reference",
                allow_none=True,
                references=("saas_bd_profile",),
            ),
            BigipPropertySpec(
                name="deployment-environment",
                value_type="enum",
                enum_values=("pre-production", "production"),
            ),
            BigipPropertySpec(name="description", value_type="string", allow_none=True),
            BigipPropertySpec(
                name="exclude-js-injection-from-specific-url",
                value_type="enum",
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="include-post-body",
                value_type="enum",
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="inject-js-in-specific-url",
                value_type="enum",
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="inject-telemetry-js-in-body-tag",
                value_type="enum",
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="irules",
                value_type="list",
                allow_none=True,
                references=("apm_policy_agent_irule_event", "pem_irule"),
                list_operators=frozenset(("add", "delete", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="js-inject-exclude-paths",
                value_type="list",
                allow_none=True,
                list_operators=frozenset(("add", "delete", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="js-inject-include-paths",
                value_type="list",
                allow_none=True,
                list_operators=frozenset(("add", "delete", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="js-mode",
                value_type="enum",
                enum_values=(
                    "async-and-caching-with-defer-XHR",
                    "async-no-caching",
                    "async-with-caching",
                    "sync",
                ),
            ),
            BigipPropertySpec(
                name="location-for-shape-js-injection",
                value_type="enum",
                enum_values=("after-head", "after-title", "before-script"),
            ),
            BigipPropertySpec(
                name="log-level",
                value_type="enum",
                enum_values=(
                    "alert",
                    "crit",
                    "debug",
                    "default-value",
                    "emerg",
                    "err",
                    "info",
                    "notice",
                    "warn",
                ),
            ),
            BigipPropertySpec(name="log-publisher", value_type="string", allow_none=True),
            BigipPropertySpec(
                name="mitigation-handler",
                value_type="enum",
                enum_values=("bigip", "shape-policy"),
            ),
            BigipPropertySpec(name="mobile-api-hostname", value_type="string", allow_none=True),
            BigipPropertySpec(
                name="mobile-applications-in-scope",
                value_type="enum",
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="mobile-block-response-body",
                value_type="string",
                allow_none=True,
            ),
            BigipPropertySpec(
                name="mobile-block-response-code",
                value_type="integer",
                allow_none=True,
            ),
            BigipPropertySpec(
                name="mobile-block-response-content-type",
                value_type="string",
                allow_none=True,
            ),
            BigipPropertySpec(
                name="mobile-identifier-body-keywords",
                value_type="list",
                allow_none=True,
                list_operators=frozenset(("add", "delete", "replace-all-with")),
            ),
            BigipPropertySpec(name="mobile-identifier-request-headers", value_type="list"),
            BigipPropertySpec(
                name="mobile-include-post-body",
                value_type="enum",
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="mobile-mitigation-handler",
                value_type="enum",
                enum_values=("bigip", "shape-policy"),
            ),
            BigipPropertySpec(
                name="mobile-protected-endpoints",
                value_type="list",
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="any-method",
                value_type="enum",
                in_sections=("mobile-protected-endpoints",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="block-response-name",
                value_type="enum",
                in_sections=("mobile-protected-endpoints",),
                allow_none=True,
                enum_values=("none",),
            ),
            BigipPropertySpec(
                name="check-mobile-request-identifier",
                value_type="enum",
                in_sections=("mobile-protected-endpoints",),
                enum_values=("body", "header", "skip"),
            ),
            BigipPropertySpec(
                name="endpoint",
                value_type="string",
                in_sections=("mobile-protected-endpoints",),
                allow_none=True,
            ),
            BigipPropertySpec(
                name="get",
                value_type="enum",
                in_sections=("mobile-protected-endpoints",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="host",
                value_type="string",
                in_sections=("mobile-protected-endpoints",),
                allow_none=True,
            ),
            BigipPropertySpec(
                name="mitigation-action",
                value_type="enum",
                in_sections=("mobile-protected-endpoints",),
                enum_values=("block", "continue"),
            ),
            BigipPropertySpec(
                name="post",
                value_type="enum",
                in_sections=("mobile-protected-endpoints",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="mobile-proxy-shape-endpoint-url",
                value_type="string",
                allow_none=True,
            ),
            BigipPropertySpec(
                name="mobile-sdk-config-fetch-url-android",
                value_type="string",
                allow_none=True,
            ),
            BigipPropertySpec(
                name="mobile-sdk-config-fetch-url-ios",
                value_type="string",
                allow_none=True,
            ),
            BigipPropertySpec(
                name="mobile-sdk-reload-header-name",
                value_type="string",
                allow_none=True,
            ),
            BigipPropertySpec(
                name="mobile-shape-protection-pool",
                value_type="string",
                allow_none=True,
            ),
            BigipPropertySpec(
                name="mobile-telemetry-header-prefix",
                value_type="string",
                allow_none=True,
            ),
            BigipPropertySpec(
                name="pool-cookie-persistence",
                value_type="enum",
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="protected-endpoints",
                value_type="list",
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="any-method",
                value_type="enum",
                in_sections=("protected-endpoints",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="block-response-name",
                value_type="enum",
                in_sections=("protected-endpoints",),
                allow_none=True,
                enum_values=("none",),
            ),
            BigipPropertySpec(
                name="endpoint",
                value_type="string",
                in_sections=("protected-endpoints",),
                allow_none=True,
            ),
            BigipPropertySpec(
                name="get-document",
                value_type="enum",
                in_sections=("protected-endpoints",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="get-xhr-or-fetch",
                value_type="enum",
                in_sections=("protected-endpoints",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="host",
                value_type="string",
                in_sections=("protected-endpoints",),
                allow_none=True,
            ),
            BigipPropertySpec(
                name="mitigation-action",
                value_type="enum",
                in_sections=("protected-endpoints",),
                enum_values=("block", "continue", "drop", "redirect"),
            ),
            BigipPropertySpec(
                name="post",
                value_type="enum",
                in_sections=("protected-endpoints",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="put",
                value_type="enum",
                in_sections=("protected-endpoints",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="redirect-response-name",
                value_type="enum",
                in_sections=("protected-endpoints",),
                allow_none=True,
                enum_values=("none",),
            ),
            BigipPropertySpec(name="proxy-password", value_type="string", allow_none=True),
            BigipPropertySpec(name="proxy-pool", value_type="string", allow_none=True),
            BigipPropertySpec(
                name="proxy-shape-endpoint-url",
                value_type="string",
                allow_none=True,
            ),
            BigipPropertySpec(name="proxy-username", value_type="string", allow_none=True),
            BigipPropertySpec(name="redirect-path", value_type="string", allow_none=True),
            BigipPropertySpec(name="redirect-response-code", value_type="integer", allow_none=True),
            BigipPropertySpec(
                name="redirect-responses",
                value_type="list",
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="app-service",
                value_type="string",
                in_sections=("redirect-responses",),
                allow_none=True,
            ),
            BigipPropertySpec(
                name="redirect-path",
                value_type="string",
                in_sections=("redirect-responses",),
                allow_none=True,
            ),
            BigipPropertySpec(
                name="redirect-response-code",
                value_type="integer",
                in_sections=("redirect-responses",),
                allow_none=True,
            ),
            BigipPropertySpec(
                name="report-transaction-result",
                value_type="enum",
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="rewrite-xff-header-with-connecting-ip",
                value_type="enum",
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="service-level",
                value_type="enum",
                enum_values=("enterprise", "standard"),
            ),
            BigipPropertySpec(
                name="shape-api-response-timeout",
                value_type="integer",
                allow_none=True,
            ),
            BigipPropertySpec(name="shape-inference-header", value_type="string", allow_none=True),
            BigipPropertySpec(name="shape-js-url-or-path", value_type="string"),
            BigipPropertySpec(name="shape-protection-pool", value_type="string"),
            BigipPropertySpec(
                name="source-of-client-ip-address",
                value_type="enum",
                enum_values=("connecting-ip", "custom", "x-forwarded-for"),
            ),
            BigipPropertySpec(name="ssl-profile", value_type="string"),
            BigipPropertySpec(name="telemetry-header-prefix", value_type="string"),
            BigipPropertySpec(
                name="telemetry-request-body-size",
                value_type="integer",
                allow_none=True,
            ),
            BigipPropertySpec(name="tenant-id", value_type="string", allow_none=True),
            BigipPropertySpec(
                name="tls-fingerprint",
                value_type="enum",
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="use-proxy",
                value_type="enum",
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="use-sni",
                value_type="enum",
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="web-applications-in-scope",
                value_type="enum",
                enum_values=("disabled", "enabled"),
            ),
        ),
    )
