from __future__ import annotations

from ..models import (
    BigipObjectKindSpec,
    BigipObjectSpec,
    BigipPropertySpec,
)
from ._base import register


@register
def register_spec() -> BigipObjectSpec:
    return BigipObjectSpec(
        kind_spec=BigipObjectKindSpec(
            "security_firewall_management_ip_rules",
            module="security",
            object_types=("firewall management-ip-rules",),
        ),
        header_types=(("security", "firewall management-ip-rules"),),
        properties=(
            BigipPropertySpec(name="description", value_type="string"),
            BigipPropertySpec(
                name="rules",
                value_type="list",
                allow_none=True,
                references=(
                    "gtm_rule",
                    "ltm_cipher_rule",
                    "ltm_global_settings_rule",
                    "ltm_rule",
                    "ltm_rule_profiler",
                    "security_firewall_matching_rule",
                    "security_firewall_on_demand_rule_deploy",
                    "security_firewall_rule_list",
                    "security_firewall_rule_stat",
                    "security_packet_filter_rule_stat",
                    "sys_file_rewrite_rule",
                ),
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
                block=(
                    BigipPropertySpec(
                        name="action",
                        value_type="enum",
                        in_sections=("rules",),
                        enum_values=("accept", "accept-decisively", "drop", "reject"),
                    ),
                    BigipPropertySpec(
                        name="description", value_type="string", in_sections=("rules",)
                    ),
                    BigipPropertySpec(
                        name="destination",
                        value_type="unknown",
                        in_sections=("rules",),
                        shape_kind="object",
                    ),
                    BigipPropertySpec(
                        name="icmp",
                        value_type="list",
                        in_sections=("rules",),
                        allow_none=True,
                        list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
                    ),
                    BigipPropertySpec(
                        name="ip-protocol",
                        value_type="reference",
                        in_sections=("rules",),
                    ),
                    BigipPropertySpec(
                        name="log",
                        value_type="enum",
                        in_sections=("rules",),
                        enum_values=("no", "yes"),
                        shape_kind="boolean",
                    ),
                    BigipPropertySpec(
                        name="place-after",
                        value_type="reference",
                        in_sections=("rules",),
                    ),
                    BigipPropertySpec(
                        name="place-before",
                        value_type="reference",
                        in_sections=("rules",),
                    ),
                    BigipPropertySpec(
                        name="rule-list",
                        value_type="reference",
                        in_sections=("rules",),
                        references=("security_firewall_rule_list",),
                    ),
                    BigipPropertySpec(
                        name="schedule",
                        value_type="reference",
                        in_sections=("rules",),
                        references=(
                            "ltm_classification_signature_update_schedule",
                            "security_firewall_schedule",
                            "sys_url_db_download_schedule",
                        ),
                    ),
                    BigipPropertySpec(
                        name="source",
                        value_type="unknown",
                        in_sections=("rules",),
                        shape_kind="object",
                    ),
                    BigipPropertySpec(
                        name="status",
                        value_type="enum",
                        in_sections=("rules",),
                        enum_values=("disabled", "enabled", "scheduled"),
                    ),
                    BigipPropertySpec(
                        name="uuid",
                        value_type="enum",
                        in_sections=("rules",),
                        allow_none=True,
                        enum_values=("auto-generate", "none"),
                    ),
                ),
            ),
            BigipPropertySpec(
                name="action",
                value_type="enum",
                in_sections=("rules",),
                enum_values=("accept", "accept-decisively", "drop", "reject"),
            ),
            BigipPropertySpec(name="description", value_type="string", in_sections=("rules",)),
            BigipPropertySpec(
                name="destination",
                value_type="unknown",
                in_sections=("rules",),
                shape_kind="object",
                block=(
                    BigipPropertySpec(
                        name="address-lists",
                        value_type="list",
                        in_sections=("rules", "destination"),
                        allow_none=True,
                        list_operators=frozenset(("add", "delete", "replace-all-with")),
                    ),
                    BigipPropertySpec(
                        name="addresses",
                        value_type="list",
                        in_sections=("rules", "destination"),
                        allow_none=True,
                        list_operators=frozenset(("add", "delete", "replace-all-with")),
                    ),
                    BigipPropertySpec(
                        name="port-lists",
                        value_type="list",
                        in_sections=("rules", "destination"),
                        allow_none=True,
                        list_operators=frozenset(("add", "delete", "replace-all-with")),
                    ),
                    BigipPropertySpec(
                        name="ports",
                        value_type="list",
                        in_sections=("rules", "destination"),
                        allow_none=True,
                        list_operators=frozenset(("add", "delete", "replace-all-with")),
                    ),
                ),
            ),
            BigipPropertySpec(
                name="address-lists",
                value_type="list",
                in_sections=("rules", "destination"),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="addresses",
                value_type="list",
                in_sections=("rules", "destination"),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="port-lists",
                value_type="list",
                in_sections=("rules", "destination"),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="ports",
                value_type="list",
                in_sections=("rules", "destination"),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="icmp",
                value_type="list",
                in_sections=("rules",),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
                block=(
                    BigipPropertySpec(
                        name="description",
                        value_type="string",
                        in_sections=("rules", "icmp"),
                    ),
                ),
            ),
            BigipPropertySpec(
                name="description",
                value_type="string",
                in_sections=("rules", "icmp"),
            ),
            BigipPropertySpec(name="ip-protocol", value_type="reference", in_sections=("rules",)),
            BigipPropertySpec(
                name="log",
                value_type="enum",
                in_sections=("rules",),
                enum_values=("no", "yes"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(name="place-after", value_type="reference", in_sections=("rules",)),
            BigipPropertySpec(name="place-before", value_type="reference", in_sections=("rules",)),
            BigipPropertySpec(
                name="rule-list",
                value_type="reference",
                in_sections=("rules",),
                references=("security_firewall_rule_list",),
            ),
            BigipPropertySpec(
                name="schedule",
                value_type="reference",
                in_sections=("rules",),
                references=(
                    "ltm_classification_signature_update_schedule",
                    "security_firewall_schedule",
                    "sys_url_db_download_schedule",
                ),
            ),
            BigipPropertySpec(
                name="source",
                value_type="unknown",
                in_sections=("rules",),
                shape_kind="object",
                block=(
                    BigipPropertySpec(
                        name="address-lists",
                        value_type="list",
                        in_sections=("rules", "source"),
                        allow_none=True,
                        list_operators=frozenset(("add", "delete", "replace-all-with")),
                    ),
                    BigipPropertySpec(
                        name="addresses",
                        value_type="list",
                        in_sections=("rules", "source"),
                        allow_none=True,
                        list_operators=frozenset(("add", "delete", "replace-all-with")),
                    ),
                    BigipPropertySpec(
                        name="port-lists",
                        value_type="list",
                        in_sections=("rules", "source"),
                        allow_none=True,
                        list_operators=frozenset(("add", "delete", "replace-all-with")),
                    ),
                    BigipPropertySpec(
                        name="ports",
                        value_type="list",
                        in_sections=("rules", "source"),
                        allow_none=True,
                        list_operators=frozenset(("add", "delete", "replace-all-with")),
                    ),
                    BigipPropertySpec(
                        name="vlans",
                        value_type="list",
                        in_sections=("rules", "source"),
                        allow_none=True,
                        list_operators=frozenset(("add", "delete", "replace-all-with")),
                    ),
                ),
            ),
            BigipPropertySpec(
                name="address-lists",
                value_type="list",
                in_sections=("rules", "source"),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="addresses",
                value_type="list",
                in_sections=("rules", "source"),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="port-lists",
                value_type="list",
                in_sections=("rules", "source"),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="ports",
                value_type="list",
                in_sections=("rules", "source"),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="vlans",
                value_type="list",
                in_sections=("rules", "source"),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="status",
                value_type="enum",
                in_sections=("rules",),
                enum_values=("disabled", "enabled", "scheduled"),
            ),
            BigipPropertySpec(
                name="uuid",
                value_type="enum",
                in_sections=("rules",),
                allow_none=True,
                enum_values=("auto-generate", "none"),
            ),
        ),
    )
