from __future__ import annotations

from ..models import (
    BigipObjectKindSpec,
    BigipObjectSpec,
    BigipPropertySpec,
)
from ._base import register


@register
def register_spec() -> BigipObjectSpec:
    return BigipObjectSpec(
        kind_spec=BigipObjectKindSpec(
            "security_bot_defense_profile",
            module="security",
            object_types=("bot-defense profile",),
        ),
        header_types=(("security", "bot-defense profile"),),
        properties=(
            BigipPropertySpec(
                name="anomaly-category-overrides",
                value_type="list",
                allow_none=True,
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="action",
                value_type="enum",
                in_sections=("anomaly-category-overrides",),
                allow_none=True,
                enum_values=(
                    "alarm",
                    "block",
                    "captcha",
                    "honeypot-page",
                    "none",
                    "redirect-to-pool",
                    "tcp-reset",
                ),
            ),
            BigipPropertySpec(
                name="app-service",
                value_type="string",
                in_sections=("anomaly-category-overrides",),
                allow_none=True,
            ),
            BigipPropertySpec(
                name="anomaly-overrides",
                value_type="list",
                allow_none=True,
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="action",
                value_type="enum",
                in_sections=("anomaly-overrides",),
                allow_none=True,
                enum_values=(
                    "alarm",
                    "block",
                    "captcha",
                    "honeypot-page",
                    "none",
                    "redirect-to-pool",
                    "tcp-reset",
                ),
            ),
            BigipPropertySpec(
                name="api-access-strict-mitigation",
                value_type="enum",
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(name="app-service", value_type="string", allow_none=True),
            BigipPropertySpec(name="blocking-page", value_type="unknown"),
            BigipPropertySpec(name="body", value_type="string", in_sections=("blocking-page",)),
            BigipPropertySpec(name="headers", value_type="string", in_sections=("blocking-page",)),
            BigipPropertySpec(
                name="status-code",
                value_type="integer",
                in_sections=("blocking-page",),
            ),
            BigipPropertySpec(
                name="type",
                value_type="enum",
                in_sections=("blocking-page",),
                enum_values=("custom", "default"),
            ),
            BigipPropertySpec(name="captcha-response", value_type="unknown"),
            BigipPropertySpec(
                name="failure",
                value_type="unknown",
                in_sections=("captcha-response",),
            ),
            BigipPropertySpec(
                name="body",
                value_type="string",
                in_sections=("captcha-response", "failure"),
            ),
            BigipPropertySpec(
                name="type",
                value_type="enum",
                in_sections=("captcha-response", "failure"),
                enum_values=("custom", "default"),
            ),
            BigipPropertySpec(
                name="first",
                value_type="unknown",
                in_sections=("captcha-response",),
            ),
            BigipPropertySpec(
                name="body",
                value_type="string",
                in_sections=("captcha-response", "first"),
            ),
            BigipPropertySpec(
                name="type",
                value_type="enum",
                in_sections=("captcha-response", "first"),
                enum_values=("custom", "default"),
            ),
            BigipPropertySpec(
                name="class-overrides",
                value_type="list",
                allow_none=True,
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="mitigation",
                value_type="unknown",
                in_sections=("class-overrides",),
            ),
            BigipPropertySpec(
                name="action",
                value_type="enum",
                in_sections=("class-overrides", "mitigation"),
                allow_none=True,
                enum_values=(
                    "alarm",
                    "block",
                    "captcha",
                    "honeypot-page",
                    "none",
                    "rate-limit",
                    "redirect-to-pool",
                    "tcp-reset",
                ),
            ),
            BigipPropertySpec(
                name="rate-limit-tps",
                value_type="integer",
                in_sections=("class-overrides", "mitigation"),
            ),
            BigipPropertySpec(
                name="verification",
                value_type="unknown",
                in_sections=("class-overrides",),
            ),
            BigipPropertySpec(
                name="action",
                value_type="enum",
                in_sections=("class-overrides", "verification"),
                allow_none=True,
                enum_values=(
                    "browser-challenge-free-verification",
                    "browser-verify-after-access-detection",
                    "browser-verify-before-access",
                    "none",
                ),
            ),
            BigipPropertySpec(
                name="cross-domain-requests",
                value_type="enum",
                enum_values=("allow-all", "validate-bulk", "validate-upon-request"),
            ),
            BigipPropertySpec(
                name="defaults-from",
                value_type="unknown",
                references=("security_bot_defense_profile",),
            ),
            BigipPropertySpec(name="description", value_type="string", allow_none=True),
            BigipPropertySpec(
                name="deviceid-mode",
                value_type="enum",
                allow_none=True,
                enum_values=("generate-after-access", "generate-before-access", "none"),
            ),
            BigipPropertySpec(
                name="dos-attack-strict-mitigation",
                value_type="enum",
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="enforcement-mode",
                value_type="enum",
                enum_values=("blocking", "transparent"),
            ),
            BigipPropertySpec(name="enforcement-readiness-period", value_type="integer"),
            BigipPropertySpec(
                name="external-domains",
                value_type="list",
                allow_none=True,
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(name="grace-period", value_type="integer"),
            BigipPropertySpec(
                name="micro-services",
                value_type="list",
                allow_none=True,
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="action",
                value_type="enum",
                in_sections=("micro-services",),
                allow_none=True,
                enum_values=(
                    "alarm",
                    "block",
                    "captcha",
                    "honeypot-page",
                    "none",
                    "redirect-to-pool",
                    "tcp-reset",
                ),
            ),
            BigipPropertySpec(
                name="class-overrides",
                value_type="list",
                in_sections=("micro-services",),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="mitigation",
                value_type="unknown",
                in_sections=("micro-services", "class-overrides"),
            ),
            BigipPropertySpec(
                name="action",
                value_type="enum",
                in_sections=("micro-services", "class-overrides", "mitigation"),
                allow_none=True,
                enum_values=(
                    "alarm",
                    "block",
                    "captcha",
                    "honeypot-page",
                    "none",
                    "redirect-to-pool",
                    "tcp-reset",
                ),
            ),
            BigipPropertySpec(
                name="verification",
                value_type="unknown",
                in_sections=("micro-services", "class-overrides"),
            ),
            BigipPropertySpec(
                name="action",
                value_type="enum",
                in_sections=("micro-services", "class-overrides", "verification"),
                allow_none=True,
                enum_values=(
                    "browser-captcha",
                    "browser-challenge-free-verification",
                    "browser-verify-after-access-detection",
                    "browser-verify-before-access",
                    "none",
                ),
            ),
            BigipPropertySpec(
                name="description",
                value_type="string",
                in_sections=("micro-services",),
                allow_none=True,
            ),
            BigipPropertySpec(
                name="detection-threshold",
                value_type="integer",
                in_sections=("micro-services",),
            ),
            BigipPropertySpec(
                name="detection-time",
                value_type="integer",
                in_sections=("micro-services",),
            ),
            BigipPropertySpec(
                name="enforcement-mode",
                value_type="enum",
                in_sections=("micro-services",),
                enum_values=("blocking", "profile-default", "transparent"),
            ),
            BigipPropertySpec(
                name="hostname",
                value_type="string",
                in_sections=("micro-services",),
            ),
            BigipPropertySpec(
                name="match-order",
                value_type="integer",
                in_sections=("micro-services",),
            ),
            BigipPropertySpec(
                name="mitigation-time",
                value_type="integer",
                in_sections=("micro-services",),
            ),
            BigipPropertySpec(name="type", value_type="unknown", in_sections=("micro-services",)),
            BigipPropertySpec(
                name="urls",
                value_type="list",
                in_sections=("micro-services",),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="match-order",
                value_type="integer",
                in_sections=("micro-services", "urls"),
            ),
            BigipPropertySpec(
                name="url",
                value_type="string",
                in_sections=("micro-services", "urls"),
            ),
            BigipPropertySpec(name="mobile-detection", value_type="unknown"),
            BigipPropertySpec(
                name="allow-android-rooted-device",
                value_type="enum",
                in_sections=("mobile-detection",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="allow-any-android-package",
                value_type="enum",
                in_sections=("mobile-detection",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="allow-any-ios-package",
                value_type="enum",
                in_sections=("mobile-detection",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="allow-emulators",
                value_type="enum",
                in_sections=("mobile-detection",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="allow-jailbroken-devices",
                value_type="enum",
                in_sections=("mobile-detection",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="android-publishers",
                value_type="list",
                in_sections=("mobile-detection",),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="block-debugger-enabled-device",
                value_type="enum",
                in_sections=("mobile-detection",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="client-side-challenge-mode",
                value_type="enum",
                in_sections=("mobile-detection",),
                enum_values=("cshui", "pass"),
            ),
            BigipPropertySpec(
                name="ios-allowed-packages",
                value_type="list",
                in_sections=("mobile-detection",),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="signatures",
                value_type="list",
                in_sections=("mobile-detection",),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="perform-challenge-in-transparent",
                value_type="enum",
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="signature-category-overrides",
                value_type="list",
                allow_none=True,
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="action",
                value_type="enum",
                in_sections=("signature-category-overrides",),
                allow_none=True,
                enum_values=(
                    "alarm",
                    "block",
                    "captcha",
                    "honeypot-page",
                    "none",
                    "redirect-to-pool",
                    "tcp-reset",
                ),
            ),
            BigipPropertySpec(
                name="signature-overrides",
                value_type="list",
                allow_none=True,
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="action",
                value_type="enum",
                in_sections=("signature-overrides",),
                allow_none=True,
                enum_values=(
                    "alarm",
                    "block",
                    "captcha",
                    "honeypot-page",
                    "none",
                    "rate-limit",
                    "redirect-to-pool",
                    "tcp-reset",
                ),
            ),
            BigipPropertySpec(
                name="rate-limit-tps",
                value_type="integer",
                in_sections=("signature-overrides",),
            ),
            BigipPropertySpec(
                name="signature-staging-upon-update",
                value_type="enum",
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="single-page-application",
                value_type="enum",
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="site-domains",
                value_type="list",
                allow_none=True,
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="staged-signatures",
                value_type="list",
                allow_none=True,
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="template",
                value_type="enum",
                enum_values=("balanced", "relaxed", "strict"),
            ),
            BigipPropertySpec(
                name="whitelist",
                value_type="list",
                allow_none=True,
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="disable-mitigation",
                value_type="enum",
                in_sections=("whitelist",),
                enum_values=("no", "yes"),
            ),
            BigipPropertySpec(
                name="disable-verification",
                value_type="enum",
                in_sections=("whitelist",),
                enum_values=("no", "yes"),
            ),
            BigipPropertySpec(name="geolocation", value_type="unknown", in_sections=("whitelist",)),
            BigipPropertySpec(name="match-order", value_type="integer", in_sections=("whitelist",)),
            BigipPropertySpec(
                name="source-address",
                value_type="unknown",
                in_sections=("whitelist",),
            ),
            BigipPropertySpec(name="url", value_type="string", in_sections=("whitelist",)),
        ),
    )
