from __future__ import annotations

from ..models import (
    BigipObjectKindSpec,
    BigipObjectSpec,
    BigipPropertySpec,
)
from ._base import register


@register
def register_spec() -> BigipObjectSpec:
    return BigipObjectSpec(
        kind_spec=BigipObjectKindSpec(
            "security_nat_policy",
            module="security",
            object_types=("nat policy",),
        ),
        header_types=(("security", "nat policy"),),
        properties=(
            BigipPropertySpec(name="app-service", value_type="string", allow_none=True),
            BigipPropertySpec(name="description", value_type="string"),
            BigipPropertySpec(
                name="rules",
                value_type="list",
                allow_none=True,
                references=(
                    "gtm_rule",
                    "ltm_cipher_rule",
                    "ltm_global_settings_rule",
                    "ltm_rule",
                    "ltm_rule_profiler",
                    "security_firewall_matching_rule",
                    "security_firewall_on_demand_rule_deploy",
                    "security_firewall_rule_list",
                    "security_firewall_rule_stat",
                    "security_packet_filter_rule_stat",
                    "sys_file_rewrite_rule",
                ),
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
                block=(
                    BigipPropertySpec(
                        name="app-service",
                        value_type="string",
                        in_sections=("rules",),
                        allow_none=True,
                    ),
                    BigipPropertySpec(
                        name="description", value_type="string", in_sections=("rules",)
                    ),
                    BigipPropertySpec(
                        name="destination",
                        value_type="unknown",
                        in_sections=("rules",),
                        shape_kind="object",
                    ),
                    BigipPropertySpec(
                        name="ip-protocol",
                        value_type="reference",
                        in_sections=("rules",),
                    ),
                    BigipPropertySpec(
                        name="log-profile",
                        value_type="reference",
                        in_sections=("rules",),
                        allow_none=True,
                        enum_values=("none",),
                    ),
                    BigipPropertySpec(
                        name="next-hop",
                        value_type="unknown",
                        in_sections=("rules",),
                        shape_kind="object",
                    ),
                    BigipPropertySpec(
                        name="place-after",
                        value_type="reference",
                        in_sections=("rules",),
                    ),
                    BigipPropertySpec(
                        name="place-before",
                        value_type="reference",
                        in_sections=("rules",),
                    ),
                    BigipPropertySpec(
                        name="source",
                        value_type="unknown",
                        in_sections=("rules",),
                        shape_kind="object",
                    ),
                    BigipPropertySpec(
                        name="status",
                        value_type="enum",
                        in_sections=("rules",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                    ),
                    BigipPropertySpec(
                        name="translation",
                        value_type="unknown",
                        in_sections=("rules",),
                        shape_kind="object",
                    ),
                ),
            ),
            BigipPropertySpec(
                name="app-service",
                value_type="string",
                in_sections=("rules",),
                allow_none=True,
            ),
            BigipPropertySpec(name="description", value_type="string", in_sections=("rules",)),
            BigipPropertySpec(
                name="destination",
                value_type="unknown",
                in_sections=("rules",),
                shape_kind="object",
                block=(
                    BigipPropertySpec(
                        name="address-lists",
                        value_type="list",
                        in_sections=("rules", "destination"),
                        allow_none=True,
                        list_operators=frozenset(("add", "delete", "replace-all-with")),
                    ),
                    BigipPropertySpec(
                        name="addresses",
                        value_type="list",
                        in_sections=("rules", "destination"),
                        allow_none=True,
                        list_operators=frozenset(("add", "delete", "replace-all-with")),
                    ),
                    BigipPropertySpec(
                        name="port-lists",
                        value_type="list",
                        in_sections=("rules", "destination"),
                        allow_none=True,
                        list_operators=frozenset(("add", "delete", "replace-all-with")),
                    ),
                    BigipPropertySpec(
                        name="ports",
                        value_type="list",
                        in_sections=("rules", "destination"),
                        allow_none=True,
                        list_operators=frozenset(("add", "delete", "replace-all-with")),
                    ),
                    BigipPropertySpec(
                        name="proxy-arp",
                        value_type="enum",
                        in_sections=("rules", "destination"),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                    ),
                    BigipPropertySpec(
                        name="route-advertisement",
                        value_type="enum",
                        in_sections=("rules", "destination"),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                    ),
                ),
            ),
            BigipPropertySpec(
                name="address-lists",
                value_type="list",
                in_sections=("rules", "destination"),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="addresses",
                value_type="list",
                in_sections=("rules", "destination"),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="port-lists",
                value_type="list",
                in_sections=("rules", "destination"),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="ports",
                value_type="list",
                in_sections=("rules", "destination"),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="proxy-arp",
                value_type="enum",
                in_sections=("rules", "destination"),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="route-advertisement",
                value_type="enum",
                in_sections=("rules", "destination"),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(name="ip-protocol", value_type="reference", in_sections=("rules",)),
            BigipPropertySpec(
                name="log-profile",
                value_type="reference",
                in_sections=("rules",),
                allow_none=True,
                enum_values=("none",),
            ),
            BigipPropertySpec(
                name="next-hop",
                value_type="unknown",
                in_sections=("rules",),
                shape_kind="object",
                block=(
                    BigipPropertySpec(
                        name="gw",
                        value_type="string",
                        in_sections=("rules", "next-hop"),
                        shape_kind="ip-address",
                    ),
                    BigipPropertySpec(
                        name="pool",
                        value_type="reference",
                        in_sections=("rules", "next-hop"),
                        allow_none=True,
                        enum_values=("none",),
                        references=(
                            "analytics_lsn_pool_report",
                            "analytics_lsn_pool_scheduled_report",
                            "analytics_pool_traffic_report",
                            "analytics_pool_traffic_scheduled_report",
                            "gtm_pool_a",
                            "gtm_pool_aaaa",
                            "gtm_pool_cname",
                            "gtm_pool_https",
                            "gtm_pool_mx",
                            "gtm_pool_naptr",
                            "gtm_pool_srv",
                            "gtm_pool_svcb",
                            "gtm_prober_pool",
                            "ltm_lsn_pool",
                            "ltm_pool",
                        ),
                    ),
                    BigipPropertySpec(
                        name="type",
                        value_type="enum",
                        in_sections=("rules", "next-hop"),
                        enum_values=("default", "gateway", "pool", "vlan"),
                    ),
                    BigipPropertySpec(
                        name="vlan",
                        value_type="reference",
                        in_sections=("rules", "next-hop"),
                        allow_none=True,
                        enum_values=("none",),
                        references=(
                            "net_fdb_vlan",
                            "net_vlan",
                            "net_vlan_allowed",
                            "net_vlan_group",
                            "sys_sflow_data_source_vlan",
                            "sys_sflow_global_settings_vlan",
                        ),
                    ),
                ),
            ),
            BigipPropertySpec(
                name="gw",
                value_type="string",
                in_sections=("rules", "next-hop"),
                shape_kind="ip-address",
            ),
            BigipPropertySpec(
                name="pool",
                value_type="reference",
                in_sections=("rules", "next-hop"),
                allow_none=True,
                enum_values=("none",),
                references=(
                    "analytics_lsn_pool_report",
                    "analytics_lsn_pool_scheduled_report",
                    "analytics_pool_traffic_report",
                    "analytics_pool_traffic_scheduled_report",
                    "gtm_pool_a",
                    "gtm_pool_aaaa",
                    "gtm_pool_cname",
                    "gtm_pool_https",
                    "gtm_pool_mx",
                    "gtm_pool_naptr",
                    "gtm_pool_srv",
                    "gtm_pool_svcb",
                    "gtm_prober_pool",
                    "ltm_lsn_pool",
                    "ltm_pool",
                ),
            ),
            BigipPropertySpec(
                name="type",
                value_type="enum",
                in_sections=("rules", "next-hop"),
                enum_values=("default", "gateway", "pool", "vlan"),
            ),
            BigipPropertySpec(
                name="vlan",
                value_type="reference",
                in_sections=("rules", "next-hop"),
                allow_none=True,
                enum_values=("none",),
                references=(
                    "net_fdb_vlan",
                    "net_vlan",
                    "net_vlan_allowed",
                    "net_vlan_group",
                    "sys_sflow_data_source_vlan",
                    "sys_sflow_global_settings_vlan",
                ),
            ),
            BigipPropertySpec(name="place-after", value_type="reference", in_sections=("rules",)),
            BigipPropertySpec(name="place-before", value_type="reference", in_sections=("rules",)),
            BigipPropertySpec(
                name="source",
                value_type="unknown",
                in_sections=("rules",),
                shape_kind="object",
                block=(
                    BigipPropertySpec(
                        name="address-lists",
                        value_type="list",
                        in_sections=("rules", "source"),
                        allow_none=True,
                        list_operators=frozenset(("add", "delete", "replace-all-with")),
                    ),
                    BigipPropertySpec(
                        name="addresses",
                        value_type="list",
                        in_sections=("rules", "source"),
                        allow_none=True,
                        list_operators=frozenset(("add", "delete", "replace-all-with")),
                    ),
                    BigipPropertySpec(
                        name="port-lists",
                        value_type="list",
                        in_sections=("rules", "source"),
                        allow_none=True,
                        list_operators=frozenset(("add", "delete", "replace-all-with")),
                    ),
                    BigipPropertySpec(
                        name="ports",
                        value_type="list",
                        in_sections=("rules", "source"),
                        allow_none=True,
                        list_operators=frozenset(("add", "delete", "replace-all-with")),
                    ),
                    BigipPropertySpec(
                        name="vlans",
                        value_type="list",
                        in_sections=("rules", "source"),
                        allow_none=True,
                        list_operators=frozenset(("add", "delete", "replace-all-with")),
                    ),
                ),
            ),
            BigipPropertySpec(
                name="address-lists",
                value_type="list",
                in_sections=("rules", "source"),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="addresses",
                value_type="list",
                in_sections=("rules", "source"),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="port-lists",
                value_type="list",
                in_sections=("rules", "source"),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="ports",
                value_type="list",
                in_sections=("rules", "source"),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="vlans",
                value_type="list",
                in_sections=("rules", "source"),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="status",
                value_type="enum",
                in_sections=("rules",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="translation",
                value_type="unknown",
                in_sections=("rules",),
                shape_kind="object",
                block=(
                    BigipPropertySpec(
                        name="destination",
                        value_type="reference",
                        in_sections=("rules", "translation"),
                        allow_none=True,
                        enum_values=("none",),
                        references=(
                            "security_nat_destination_translation",
                            "sys_ipfix_destination",
                            "sys_log_config_destination_alertd",
                            "sys_log_config_destination_arcsight",
                            "sys_log_config_destination_ipfix",
                            "sys_log_config_destination_local_database",
                            "sys_log_config_destination_local_syslog",
                            "sys_log_config_destination_management_port",
                            "sys_log_config_destination_remote_high_speed_log",
                            "sys_log_config_destination_remote_syslog",
                            "sys_log_config_destination_splunk",
                        ),
                    ),
                    BigipPropertySpec(
                        name="source",
                        value_type="enum",
                        in_sections=("rules", "translation"),
                        allow_none=True,
                        enum_values=("automap", "none"),
                        references=(
                            "auth_source",
                            "ltm_persistence_source_addr",
                            "security_dos_auto_thresholds_top_source_ips",
                            "security_nat_source_translation",
                            "sys_sflow_data_source_http",
                            "sys_sflow_data_source_interface",
                            "sys_sflow_data_source_system",
                            "sys_sflow_data_source_vlan",
                        ),
                    ),
                ),
            ),
            BigipPropertySpec(
                name="destination",
                value_type="reference",
                in_sections=("rules", "translation"),
                allow_none=True,
                enum_values=("none",),
                references=(
                    "security_nat_destination_translation",
                    "sys_ipfix_destination",
                    "sys_log_config_destination_alertd",
                    "sys_log_config_destination_arcsight",
                    "sys_log_config_destination_ipfix",
                    "sys_log_config_destination_local_database",
                    "sys_log_config_destination_local_syslog",
                    "sys_log_config_destination_management_port",
                    "sys_log_config_destination_remote_high_speed_log",
                    "sys_log_config_destination_remote_syslog",
                    "sys_log_config_destination_splunk",
                ),
            ),
            BigipPropertySpec(
                name="source",
                value_type="enum",
                in_sections=("rules", "translation"),
                allow_none=True,
                enum_values=("automap", "none"),
                references=(
                    "auth_source",
                    "ltm_persistence_source_addr",
                    "security_dos_auto_thresholds_top_source_ips",
                    "security_nat_source_translation",
                    "sys_sflow_data_source_http",
                    "sys_sflow_data_source_interface",
                    "sys_sflow_data_source_system",
                    "sys_sflow_data_source_vlan",
                ),
            ),
            BigipPropertySpec(
                name="traffic-group",
                value_type="string",
                usage_flags=frozenset(("read_only",)),
            ),
        ),
    )
