from __future__ import annotations

from ..models import (
    BigipObjectKindSpec,
    BigipObjectSpec,
    BigipPropertySpec,
)
from ._base import register


@register
def register_spec() -> BigipObjectSpec:
    return BigipObjectSpec(
        kind_spec=BigipObjectKindSpec(
            "security_anti_fraud_profile",
            module="security",
            object_types=("anti-fraud profile",),
        ),
        header_types=(("security", "anti-fraud profile"),),
        properties=(
            BigipPropertySpec(
                name="alert-client-side-caching",
                value_type="enum",
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(name="alert-identifier", value_type="string"),
            BigipPropertySpec(name="alert-path", value_type="string"),
            BigipPropertySpec(name="alert-pool", value_type="reference", allow_none=True),
            BigipPropertySpec(name="alert-publisher", value_type="reference", allow_none=True),
            BigipPropertySpec(name="alert-token-header", value_type="string"),
            BigipPropertySpec(name="app-layer-encryption", value_type="unknown"),
            BigipPropertySpec(
                name="fail-open",
                value_type="enum",
                in_sections=("app-layer-encryption",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(name="app-service", value_type="string", allow_none=True),
            BigipPropertySpec(name="auto-transactions", value_type="list"),
            BigipPropertySpec(
                name="bot-score",
                value_type="integer",
                in_sections=("auto-transactions",),
            ),
            BigipPropertySpec(
                name="click-score",
                value_type="integer",
                in_sections=("auto-transactions",),
            ),
            BigipPropertySpec(
                name="integrity-fail-score",
                value_type="integer",
                in_sections=("auto-transactions",),
            ),
            BigipPropertySpec(
                name="min-mouse-move-count",
                value_type="integer",
                in_sections=("auto-transactions",),
            ),
            BigipPropertySpec(
                name="min-mouse-over-count",
                value_type="integer",
                in_sections=("auto-transactions",),
            ),
            BigipPropertySpec(
                name="min-report-score",
                value_type="integer",
                in_sections=("auto-transactions",),
            ),
            BigipPropertySpec(
                name="min-time-to-request",
                value_type="integer",
                in_sections=("auto-transactions",),
            ),
            BigipPropertySpec(
                name="not-human-score",
                value_type="integer",
                in_sections=("auto-transactions",),
            ),
            BigipPropertySpec(
                name="strong-integrity",
                value_type="unknown",
                in_sections=("auto-transactions",),
            ),
            BigipPropertySpec(
                name="hide-encrypted-parameters",
                value_type="enum",
                in_sections=("auto-transactions", "strong-integrity"),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="parameter",
                value_type="string",
                in_sections=("auto-transactions", "strong-integrity"),
            ),
            BigipPropertySpec(
                name="tampered-cookie-score",
                value_type="integer",
                in_sections=("auto-transactions",),
            ),
            BigipPropertySpec(
                name="time-fail-score",
                value_type="integer",
                in_sections=("auto-transactions",),
            ),
            BigipPropertySpec(name="before-load-function", value_type="string", allow_none=True),
            BigipPropertySpec(name="behaviour-analysis", value_type="list"),
            BigipPropertySpec(
                name="run",
                value_type="enum",
                in_sections=("behaviour-analysis",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="score",
                value_type="integer",
                in_sections=("behaviour-analysis",),
            ),
            BigipPropertySpec(name="blocking-page", value_type="unknown"),
            BigipPropertySpec(
                name="response-body",
                value_type="string",
                in_sections=("blocking-page",),
                allow_none=True,
            ),
            BigipPropertySpec(
                name="response-headers",
                value_type="string",
                in_sections=("blocking-page",),
            ),
            BigipPropertySpec(
                name="check-custom",
                value_type="enum",
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="check-generic",
                value_type="enum",
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(name="cloud-service-pool", value_type="reference", allow_none=True),
            BigipPropertySpec(name="config-location", value_type="string"),
            BigipPropertySpec(name="cookies", value_type="list"),
            BigipPropertySpec(
                name="application",
                value_type="list",
                in_sections=("cookies",),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "replace-all-with")),
            ),
            BigipPropertySpec(name="base-domain", value_type="unknown", in_sections=("cookies",)),
            BigipPropertySpec(
                name="apply",
                value_type="enum",
                in_sections=("cookies", "base-domain"),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="exceptions",
                value_type="list",
                in_sections=("cookies", "base-domain"),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "replace-all-with")),
            ),
            BigipPropertySpec(name="client-side", value_type="string", in_sections=("cookies",)),
            BigipPropertySpec(
                name="client-side-lifetime",
                value_type="integer",
                in_sections=("cookies",),
            ),
            BigipPropertySpec(
                name="components-state",
                value_type="string",
                in_sections=("cookies",),
            ),
            BigipPropertySpec(
                name="components-state-lifetime",
                value_type="integer",
                in_sections=("cookies",),
            ),
            BigipPropertySpec(
                name="components-state-removal-protection",
                value_type="enum",
                in_sections=("cookies",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="encryption-disabled",
                value_type="string",
                in_sections=("cookies",),
            ),
            BigipPropertySpec(
                name="encryption-disabled-lifetime",
                value_type="integer",
                in_sections=("cookies",),
            ),
            BigipPropertySpec(
                name="encryption-disabled-removal-protection",
                value_type="enum",
                in_sections=("cookies",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(name="fingerprint", value_type="string", in_sections=("cookies",)),
            BigipPropertySpec(
                name="fingerprint-lifetime",
                value_type="integer",
                in_sections=("cookies",),
            ),
            BigipPropertySpec(
                name="fingerprint-removal-protection",
                value_type="enum",
                in_sections=("cookies",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="html-field-obfuscation",
                value_type="string",
                in_sections=("cookies",),
            ),
            BigipPropertySpec(
                name="html-field-obfuscation-lifetime",
                value_type="integer",
                in_sections=("cookies",),
            ),
            BigipPropertySpec(
                name="malware-forensic",
                value_type="string",
                in_sections=("cookies",),
            ),
            BigipPropertySpec(
                name="malware-forensic-lifetime",
                value_type="integer",
                in_sections=("cookies",),
            ),
            BigipPropertySpec(name="malware-guid", value_type="string", in_sections=("cookies",)),
            BigipPropertySpec(
                name="malware-guid-lifetime",
                value_type="integer",
                in_sections=("cookies",),
            ),
            BigipPropertySpec(
                name="malware-guid-removal-protection",
                value_type="enum",
                in_sections=("cookies",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="rules",
                value_type="string",
                in_sections=("cookies",),
                references=(
                    "gtm_rule",
                    "ltm_cipher_rule",
                    "ltm_global_settings_rule",
                    "ltm_rule",
                    "ltm_rule_profiler",
                    "security_firewall_matching_rule",
                    "security_firewall_on_demand_rule_deploy",
                    "security_firewall_rule_list",
                    "security_firewall_rule_stat",
                    "security_packet_filter_rule_stat",
                    "sys_file_rewrite_rule",
                ),
            ),
            BigipPropertySpec(
                name="rules-lifetime",
                value_type="integer",
                in_sections=("cookies",),
            ),
            BigipPropertySpec(
                name="rules-removal-protection",
                value_type="enum",
                in_sections=("cookies",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(name="secure-alert", value_type="string", in_sections=("cookies",)),
            BigipPropertySpec(
                name="secure-alert-lifetime",
                value_type="integer",
                in_sections=("cookies",),
            ),
            BigipPropertySpec(
                name="secure-alert-removal-protection",
                value_type="enum",
                in_sections=("cookies",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(name="secure-channel", value_type="string", in_sections=("cookies",)),
            BigipPropertySpec(
                name="secure-channel-lifetime",
                value_type="integer",
                in_sections=("cookies",),
            ),
            BigipPropertySpec(
                name="secure-channel-removal-protection",
                value_type="enum",
                in_sections=("cookies",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="secure-mode",
                value_type="enum",
                in_sections=("cookies",),
                enum_values=("auto", "disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="transaction-data",
                value_type="string",
                in_sections=("cookies",),
            ),
            BigipPropertySpec(
                name="transaction-data-lifetime",
                value_type="integer",
                in_sections=("cookies",),
            ),
            BigipPropertySpec(
                name="user-inspection",
                value_type="string",
                in_sections=("cookies",),
            ),
            BigipPropertySpec(name="user-name", value_type="string", in_sections=("cookies",)),
            BigipPropertySpec(
                name="user-name-lifetime",
                value_type="integer",
                in_sections=("cookies",),
            ),
            BigipPropertySpec(
                name="user-name-removal-protection",
                value_type="enum",
                in_sections=("cookies",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(name="custom-config", value_type="string", allow_none=True),
            BigipPropertySpec(
                name="custom-whitelist",
                value_type="list",
                allow_none=True,
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(name="path", value_type="string", in_sections=("custom-whitelist",)),
            BigipPropertySpec(name="debug", value_type="unknown"),
            BigipPropertySpec(name="console-log", value_type="unknown", in_sections=("debug",)),
            BigipPropertySpec(
                name="client-ips",
                value_type="list",
                in_sections=("debug", "console-log"),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="fingerprints",
                value_type="list",
                in_sections=("debug", "console-log"),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="user-agents",
                value_type="list",
                in_sections=("debug", "console-log"),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "replace-all-with")),
            ),
            BigipPropertySpec(name="send-alert", value_type="unknown", in_sections=("debug",)),
            BigipPropertySpec(
                name="client-ips",
                value_type="list",
                in_sections=("debug", "send-alert"),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="fingerprints",
                value_type="list",
                in_sections=("debug", "send-alert"),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="user-agents",
                value_type="list",
                in_sections=("debug", "send-alert"),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="defaults-from",
                value_type="reference",
                allow_none=True,
                references=("security_anti_fraud_profile",),
            ),
            BigipPropertySpec(name="description", value_type="string", allow_none=True),
            BigipPropertySpec(
                name="destination-urls",
                value_type="list",
                allow_none=True,
                list_operators=frozenset(("add", "delete", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="domain-availability-urls",
                value_type="string",
                allow_none=True,
            ),
            BigipPropertySpec(name="dummy-alert-html-maximum-length", value_type="integer"),
            BigipPropertySpec(
                name="encryption-staging-mode",
                value_type="enum",
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="external-sources-targets",
                value_type="list",
                allow_none=True,
                list_operators=frozenset(("add", "delete", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="fallback-to-base-url",
                value_type="enum",
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(name="fingerprint", value_type="unknown"),
            BigipPropertySpec(
                name="collect",
                value_type="enum",
                in_sections=("fingerprint",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(name="location", value_type="string", in_sections=("fingerprint",)),
            BigipPropertySpec(name="flash-cookie-content", value_type="string", allow_none=True),
            BigipPropertySpec(name="flash-cookie-location", value_type="string"),
            BigipPropertySpec(
                name="flash-cookies",
                value_type="enum",
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(name="forensic", value_type="unknown"),
            BigipPropertySpec(name="alert-path", value_type="string", in_sections=("forensic",)),
            BigipPropertySpec(
                name="client-domains",
                value_type="list",
                in_sections=("forensic",),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="cloud-config-path",
                value_type="string",
                in_sections=("forensic",),
            ),
            BigipPropertySpec(
                name="cloud-forensics-mode",
                value_type="integer",
                in_sections=("forensic",),
            ),
            BigipPropertySpec(
                name="cloud-remediation-mode",
                value_type="integer",
                in_sections=("forensic",),
            ),
            BigipPropertySpec(
                name="continue-element",
                value_type="string",
                in_sections=("forensic",),
                allow_none=True,
            ),
            BigipPropertySpec(name="exe-location", value_type="string", in_sections=("forensic",)),
            BigipPropertySpec(
                name="html",
                value_type="string",
                in_sections=("forensic",),
                allow_none=True,
            ),
            BigipPropertySpec(
                name="self-post-location",
                value_type="string",
                in_sections=("forensic",),
            ),
            BigipPropertySpec(
                name="skip-element",
                value_type="string",
                in_sections=("forensic",),
                allow_none=True,
            ),
            BigipPropertySpec(name="skip-path", value_type="string", in_sections=("forensic",)),
            BigipPropertySpec(
                name="generic-whitelist-words",
                value_type="list",
                allow_none=True,
                list_operators=frozenset(("add", "delete", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="geolocation",
                value_type="enum",
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="include-query-string",
                value_type="enum",
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="inject-javascript",
                value_type="enum",
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(name="inject-javascript-removal", value_type="unknown"),
            BigipPropertySpec(
                name="tag",
                value_type="string",
                in_sections=("inject-javascript-removal",),
            ),
            BigipPropertySpec(name="inject-main-javascript", value_type="unknown"),
            BigipPropertySpec(
                name="tag",
                value_type="string",
                in_sections=("inject-main-javascript",),
            ),
            BigipPropertySpec(
                name="inline-scripts-whitelist-signatures",
                value_type="list",
                allow_none=True,
                list_operators=frozenset(("add", "delete", "replace-all-with")),
            ),
            BigipPropertySpec(name="ios", value_type="list"),
            BigipPropertySpec(
                name="custom-malware",
                value_type="list",
                in_sections=("ios",),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="path",
                value_type="string",
                in_sections=("ios", "custom-malware"),
            ),
            BigipPropertySpec(
                name="score",
                value_type="integer",
                in_sections=("ios", "custom-malware"),
            ),
            BigipPropertySpec(name="javascript-grace-threshold", value_type="integer"),
            BigipPropertySpec(name="javascript-location", value_type="string"),
            BigipPropertySpec(name="javascript-removal-location", value_type="string"),
            BigipPropertySpec(
                name="local-syslog-publisher",
                value_type="reference",
                allow_none=True,
            ),
            BigipPropertySpec(name="login-response", value_type="unknown"),
            BigipPropertySpec(
                name="domain-cookie",
                value_type="string",
                in_sections=("login-response",),
                allow_none=True,
            ),
            BigipPropertySpec(
                name="exclude-string",
                value_type="string",
                in_sections=("login-response",),
                allow_none=True,
            ),
            BigipPropertySpec(
                name="header",
                value_type="string",
                in_sections=("login-response",),
                allow_none=True,
            ),
            BigipPropertySpec(
                name="include-string",
                value_type="string",
                in_sections=("login-response",),
                allow_none=True,
            ),
            BigipPropertySpec(
                name="status-code",
                value_type="integer",
                in_sections=("login-response",),
                allow_none=True,
            ),
            BigipPropertySpec(
                name="validation",
                value_type="enum",
                in_sections=("login-response",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(name="malware", value_type="unknown"),
            BigipPropertySpec(
                name="allowed-domains",
                value_type="list",
                in_sections=("malware",),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="attach-html-to-alerts",
                value_type="enum",
                in_sections=("malware",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="auto-learn-form-tags",
                value_type="enum",
                in_sections=("malware",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="auto-learn-input-tags",
                value_type="enum",
                in_sections=("malware",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="auto-learn-script-tags",
                value_type="enum",
                in_sections=("malware",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="bait-check-generic",
                value_type="enum",
                in_sections=("malware",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(name="bait-location", value_type="string", in_sections=("malware",)),
            BigipPropertySpec(
                name="blacklist-functions",
                value_type="list",
                in_sections=("malware",),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="blacklist-js-words",
                value_type="list",
                in_sections=("malware",),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="blacklist-urls",
                value_type="list",
                in_sections=("malware",),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="blacklist-words",
                value_type="list",
                in_sections=("malware",),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="blocked-enter-key-detection",
                value_type="enum",
                in_sections=("malware",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(name="browser-cache", value_type="unknown", in_sections=("malware",)),
            BigipPropertySpec(
                name="blacklist-urls",
                value_type="list",
                in_sections=("malware", "browser-cache"),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="whitelist-urls",
                value_type="list",
                in_sections=("malware", "browser-cache"),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="deferred-execution",
                value_type="enum",
                in_sections=("malware",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="detected-malware",
                value_type="list",
                in_sections=("malware",),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="baits",
                value_type="list",
                in_sections=("malware", "detected-malware"),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="data-before",
                value_type="string",
                in_sections=("malware", "detected-malware", "baits"),
            ),
            BigipPropertySpec(
                name="data-inject",
                value_type="string",
                in_sections=("malware", "detected-malware", "baits"),
            ),
            BigipPropertySpec(
                name="trigger-url",
                value_type="unknown",
                in_sections=("malware", "detected-malware", "baits"),
            ),
            BigipPropertySpec(
                name="position",
                value_type="enum",
                in_sections=("malware", "detected-malware", "baits", "trigger-url"),
                enum_values=("alone", "any", "last"),
            ),
            BigipPropertySpec(
                name="dom-signatures",
                value_type="list",
                in_sections=("malware",),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="attribute-name",
                value_type="string",
                in_sections=("malware", "dom-signatures"),
                allow_none=True,
            ),
            BigipPropertySpec(
                name="hash-id",
                value_type="string",
                in_sections=("malware", "dom-signatures"),
            ),
            BigipPropertySpec(
                name="html-tag",
                value_type="string",
                in_sections=("malware", "dom-signatures"),
                allow_none=True,
            ),
            BigipPropertySpec(
                name="match-type",
                value_type="enum",
                in_sections=("malware", "dom-signatures"),
                enum_values=("contains", "is"),
            ),
            BigipPropertySpec(
                name="search-for",
                value_type="string",
                in_sections=("malware", "dom-signatures"),
            ),
            BigipPropertySpec(
                name="search-in",
                value_type="enum",
                in_sections=("malware", "dom-signatures"),
                enum_values=("all", "attribute", "html", "text"),
            ),
            BigipPropertySpec(
                name="domain-availability",
                value_type="unknown",
                in_sections=("malware",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="blacklist-urls",
                value_type="list",
                in_sections=("malware", "domain-availability"),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="whitelist-urls",
                value_type="list",
                in_sections=("malware", "domain-availability"),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="enable-symbols",
                value_type="enum",
                in_sections=("malware",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="external-injection",
                value_type="enum",
                in_sections=("malware",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="generic-malware",
                value_type="enum",
                in_sections=("malware",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="manual-count-form-tags",
                value_type="integer",
                in_sections=("malware",),
            ),
            BigipPropertySpec(
                name="manual-count-input-tags",
                value_type="integer",
                in_sections=("malware",),
            ),
            BigipPropertySpec(
                name="manual-count-script-tags",
                value_type="integer",
                in_sections=("malware",),
            ),
            BigipPropertySpec(
                name="password-exfiltration-detection",
                value_type="enum",
                in_sections=("malware",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="rat-detection",
                value_type="enum",
                in_sections=("malware",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="removed-scripts-detection",
                value_type="enum",
                in_sections=("malware",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="same-domain-scripts-validation",
                value_type="enum",
                in_sections=("malware",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="self-bait",
                value_type="enum",
                in_sections=("malware",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="source-integrity",
                value_type="enum",
                in_sections=("malware",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="vbklip-detection",
                value_type="enum",
                in_sections=("malware",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="visibility-check",
                value_type="enum",
                in_sections=("malware",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="visibility-check-items",
                value_type="list",
                in_sections=("malware",),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="web-rootkit-detection",
                value_type="enum",
                in_sections=("malware",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="whitelist-dom-signatures",
                value_type="list",
                in_sections=("malware",),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="whitelist-words",
                value_type="list",
                in_sections=("malware",),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "replace-all-with")),
            ),
            BigipPropertySpec(name="mitm", value_type="unknown"),
            BigipPropertySpec(
                name="certificate-custom-config",
                value_type="string",
                in_sections=("mitm",),
                allow_none=True,
            ),
            BigipPropertySpec(
                name="dns-custom-config",
                value_type="string",
                in_sections=("mitm",),
                allow_none=True,
            ),
            BigipPropertySpec(
                name="domains",
                value_type="list",
                in_sections=("mitm",),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="certificate",
                value_type="unknown",
                in_sections=("mitm", "domains"),
            ),
            BigipPropertySpec(
                name="forging-score",
                value_type="integer",
                in_sections=("mitm", "domains", "certificate"),
            ),
            BigipPropertySpec(
                name="hash",
                value_type="string",
                in_sections=("mitm", "domains", "certificate"),
            ),
            BigipPropertySpec(name="dns", value_type="list", in_sections=("mitm", "domains")),
            BigipPropertySpec(
                name="ip-ranges",
                value_type="list",
                in_sections=("mitm", "domains", "dns"),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="spoofing-score",
                value_type="integer",
                in_sections=("mitm", "domains", "dns"),
            ),
            BigipPropertySpec(name="mobilesafe", value_type="unknown"),
            BigipPropertySpec(
                name="mobilesafe-encryption",
                value_type="enum",
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="alert-custom-config",
                value_type="string",
                in_sections=("mobilesafe",),
                allow_none=True,
            ),
            BigipPropertySpec(
                name="alert-threshold",
                value_type="integer",
                in_sections=("mobilesafe",),
            ),
            BigipPropertySpec(
                name="app-integrity",
                value_type="unknown",
                in_sections=("mobilesafe",),
            ),
            BigipPropertySpec(
                name="android",
                value_type="unknown",
                in_sections=("mobilesafe", "app-integrity"),
            ),
            BigipPropertySpec(
                name="score",
                value_type="integer",
                in_sections=("mobilesafe", "app-integrity", "android"),
            ),
            BigipPropertySpec(
                name="signature",
                value_type="string",
                in_sections=("mobilesafe", "app-integrity", "android"),
                allow_none=True,
            ),
            BigipPropertySpec(
                name="custom-config",
                value_type="string",
                in_sections=("mobilesafe", "app-integrity"),
                allow_none=True,
            ),
            BigipPropertySpec(
                name="ios",
                value_type="list",
                in_sections=("mobilesafe", "app-integrity"),
            ),
            BigipPropertySpec(
                name="hashes",
                value_type="list",
                in_sections=("mobilesafe", "app-integrity", "ios"),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="value",
                value_type="unknown",
                in_sections=("mobilesafe", "app-integrity", "ios", "hashes"),
            ),
            BigipPropertySpec(
                name="version",
                value_type="string",
                in_sections=("mobilesafe", "app-integrity", "ios", "hashes", "value"),
                allow_none=True,
            ),
            BigipPropertySpec(
                name="score",
                value_type="integer",
                in_sections=("mobilesafe", "app-integrity", "ios"),
            ),
            BigipPropertySpec(
                name="general-custom-config",
                value_type="string",
                in_sections=("mobilesafe",),
                allow_none=True,
            ),
            BigipPropertySpec(name="malware", value_type="unknown", in_sections=("mobilesafe",)),
            BigipPropertySpec(
                name="android",
                value_type="unknown",
                in_sections=("mobilesafe", "malware"),
            ),
            BigipPropertySpec(
                name="custom-malware",
                value_type="list",
                in_sections=("mobilesafe", "malware", "android"),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="package",
                value_type="string",
                in_sections=("mobilesafe", "malware", "android", "custom-malware"),
            ),
            BigipPropertySpec(
                name="score",
                value_type="integer",
                in_sections=("mobilesafe", "malware", "android", "custom-malware"),
            ),
            BigipPropertySpec(
                name="custom-whitelist",
                value_type="list",
                in_sections=("mobilesafe", "malware"),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="package",
                value_type="string",
                in_sections=("mobilesafe", "malware", "custom-whitelist"),
            ),
            BigipPropertySpec(name="os-security", value_type="unknown"),
            BigipPropertySpec(name="android", value_type="unknown", in_sections=("os-security",)),
            BigipPropertySpec(
                name="untrusted-apps-score",
                value_type="integer",
                in_sections=("os-security", "android"),
            ),
            BigipPropertySpec(
                name="versions",
                value_type="list",
                in_sections=("os-security", "android"),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="priority",
                value_type="unknown",
                in_sections=("os-security", "android", "versions"),
            ),
            BigipPropertySpec(
                name="from",
                value_type="string",
                in_sections=("os-security", "android", "versions", "priority"),
            ),
            BigipPropertySpec(
                name="score",
                value_type="integer",
                in_sections=("os-security", "android", "versions", "priority"),
            ),
            BigipPropertySpec(
                name="to",
                value_type="string",
                in_sections=("os-security", "android", "versions", "priority"),
            ),
            BigipPropertySpec(
                name="custom-config",
                value_type="string",
                in_sections=("os-security",),
                allow_none=True,
            ),
            BigipPropertySpec(name="ios", value_type="list", in_sections=("os-security",)),
            BigipPropertySpec(
                name="versions",
                value_type="list",
                in_sections=("os-security", "ios"),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="priority",
                value_type="unknown",
                in_sections=("os-security", "ios", "versions"),
            ),
            BigipPropertySpec(
                name="from",
                value_type="string",
                in_sections=("os-security", "ios", "versions", "priority"),
            ),
            BigipPropertySpec(
                name="score",
                value_type="integer",
                in_sections=("os-security", "ios", "versions", "priority"),
            ),
            BigipPropertySpec(
                name="to",
                value_type="string",
                in_sections=("os-security", "ios", "versions", "priority"),
            ),
            BigipPropertySpec(
                name="parameters",
                value_type="list",
                allow_none=True,
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="ajax-mapping",
                value_type="string",
                in_sections=("parameters",),
            ),
            BigipPropertySpec(
                name="attach-to-vtoken-report",
                value_type="enum",
                in_sections=("parameters",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="check-integrity",
                value_type="enum",
                in_sections=("parameters",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="encrypt",
                value_type="enum",
                in_sections=("parameters",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="identify-as-username",
                value_type="enum",
                in_sections=("parameters",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="method",
                value_type="enum",
                in_sections=("parameters",),
                enum_values=("GET", "POST"),
            ),
            BigipPropertySpec(
                name="mobilesafe-encrypt",
                value_type="enum",
                in_sections=("parameters",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="mobilesafe-entangle",
                value_type="enum",
                in_sections=("parameters",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="obfuscate",
                value_type="enum",
                in_sections=("parameters",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(name="priority", value_type="integer", in_sections=("parameters",)),
            BigipPropertySpec(
                name="protect-by-selector",
                value_type="enum",
                in_sections=("parameters",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="search-in",
                value_type="enum",
                in_sections=("parameters",),
                enum_values=("any", "payload"),
            ),
            BigipPropertySpec(
                name="substitute-value",
                value_type="enum",
                in_sections=("parameters",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="type",
                value_type="enum",
                in_sections=("parameters",),
                enum_values=("explicit", "wildcard"),
            ),
            BigipPropertySpec(name="phishing", value_type="unknown"),
            BigipPropertySpec(name="alert-path", value_type="string", in_sections=("phishing",)),
            BigipPropertySpec(
                name="allowed-elements",
                value_type="list",
                in_sections=("phishing",),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="allowed-referrers",
                value_type="list",
                in_sections=("phishing",),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="application-css",
                value_type="enum",
                in_sections=("phishing",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="application-css-locations",
                value_type="list",
                in_sections=("phishing",),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="capture-users",
                value_type="enum",
                in_sections=("phishing",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="copy-detection",
                value_type="enum",
                in_sections=("phishing",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="css-attribute-name",
                value_type="string",
                in_sections=("phishing",),
            ),
            BigipPropertySpec(name="css-location", value_type="string", in_sections=("phishing",)),
            BigipPropertySpec(
                name="css-protection",
                value_type="enum",
                in_sections=("phishing",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="expiration-checks",
                value_type="enum",
                in_sections=("phishing",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="field-types-to-send",
                value_type="list",
                in_sections=("phishing",),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="image-location",
                value_type="string",
                in_sections=("phishing",),
            ),
            BigipPropertySpec(
                name="inject-css-element",
                value_type="unknown",
                in_sections=("phishing",),
            ),
            BigipPropertySpec(
                name="tag",
                value_type="string",
                in_sections=("phishing", "inject-css-element"),
            ),
            BigipPropertySpec(
                name="inject-css-link",
                value_type="unknown",
                in_sections=("phishing",),
            ),
            BigipPropertySpec(
                name="tag",
                value_type="string",
                in_sections=("phishing", "inject-css-link"),
            ),
            BigipPropertySpec(
                name="inject-inline-javascript",
                value_type="unknown",
                in_sections=("phishing",),
            ),
            BigipPropertySpec(
                name="tag",
                value_type="string",
                in_sections=("phishing", "inject-inline-javascript"),
            ),
            BigipPropertySpec(
                name="protected-elements",
                value_type="list",
                in_sections=("phishing",),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="referrer-checks",
                value_type="enum",
                in_sections=("phishing",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(name="priority", value_type="integer"),
            BigipPropertySpec(name="referrer-info-header", value_type="string"),
            BigipPropertySpec(name="removed-scripts", value_type="list"),
            BigipPropertySpec(
                name="blacklist-functions",
                value_type="list",
                in_sections=("removed-scripts",),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="whitelist-functions",
                value_type="list",
                in_sections=("removed-scripts",),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "replace-all-with")),
            ),
            BigipPropertySpec(name="risk-engine-path", value_type="string"),
            BigipPropertySpec(
                name="risk-engine-publisher",
                value_type="reference",
                allow_none=True,
            ),
            BigipPropertySpec(name="rooting-jailbreak", value_type="unknown"),
            BigipPropertySpec(
                name="custom-config",
                value_type="string",
                in_sections=("rooting-jailbreak",),
                allow_none=True,
            ),
            BigipPropertySpec(
                name="jailbreak-score",
                value_type="integer",
                in_sections=("rooting-jailbreak",),
            ),
            BigipPropertySpec(
                name="rooting-score",
                value_type="integer",
                in_sections=("rooting-jailbreak",),
            ),
            BigipPropertySpec(
                name="rules",
                value_type="list",
                allow_none=True,
                references=(
                    "gtm_rule",
                    "ltm_cipher_rule",
                    "ltm_global_settings_rule",
                    "ltm_rule",
                    "ltm_rule_profiler",
                    "security_firewall_matching_rule",
                    "security_firewall_on_demand_rule_deploy",
                    "security_firewall_rule_list",
                    "security_firewall_rule_stat",
                    "security_packet_filter_rule_stat",
                    "sys_file_rewrite_rule",
                ),
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="event",
                value_type="unknown",
                in_sections=("rules",),
                enum_values=(
                    "auto-transaction",
                    "client-network-connection",
                    "client-side-missing-components",
                    "encryption-failure",
                    "generic-malware",
                    "mandatory-words",
                    "phishing",
                    "phishing-user",
                    "rat-detection",
                    "referrer-checks",
                    "server-side-missing-components",
                    "source-integrity",
                    "web-injection",
                ),
            ),
            BigipPropertySpec(
                name="action",
                value_type="enum",
                in_sections=("rules", "event"),
                enum_values=(
                    "block-user",
                    "forensic",
                    "inspection",
                    "redirect",
                    "remediation",
                    "route",
                    "web-service",
                ),
            ),
            BigipPropertySpec(
                name="duration",
                value_type="integer",
                in_sections=("rules", "event"),
            ),
            BigipPropertySpec(
                name="enforce-policy",
                value_type="enum",
                in_sections=("rules", "event"),
                enum_values=("enforce", "time-limited", "unlimited"),
            ),
            BigipPropertySpec(
                name="min-score",
                value_type="integer",
                in_sections=("rules", "event"),
            ),
            BigipPropertySpec(
                name="payload",
                value_type="string",
                in_sections=("rules", "event"),
                allow_none=True,
            ),
            BigipPropertySpec(
                name="pool",
                value_type="reference",
                in_sections=("rules", "event"),
                allow_none=True,
                references=(
                    "analytics_lsn_pool_report",
                    "analytics_lsn_pool_scheduled_report",
                    "analytics_pool_traffic_report",
                    "analytics_pool_traffic_scheduled_report",
                    "gtm_pool_a",
                    "gtm_pool_aaaa",
                    "gtm_pool_cname",
                    "gtm_pool_https",
                    "gtm_pool_mx",
                    "gtm_pool_naptr",
                    "gtm_pool_srv",
                    "gtm_pool_svcb",
                    "gtm_prober_pool",
                    "ltm_lsn_pool",
                    "ltm_pool",
                ),
            ),
            BigipPropertySpec(
                name="publisher",
                value_type="reference",
                in_sections=("rules", "event"),
                allow_none=True,
                references=(
                    "security_blacklist_publisher_all_blacklist_publisher",
                    "security_blacklist_publisher_blacklist_publisher_stats",
                    "security_blacklist_publisher_by_addr",
                    "security_blacklist_publisher_by_category",
                    "security_blacklist_publisher_category",
                    "security_blacklist_publisher_profile",
                    "sys_icall_publisher",
                    "sys_log_config_publisher",
                ),
            ),
            BigipPropertySpec(
                name="url",
                value_type="string",
                in_sections=("rules", "event"),
                allow_none=True,
            ),
            BigipPropertySpec(name="same-domain-scripts-validation-header", value_type="string"),
            BigipPropertySpec(name="self-bait-header", value_type="string"),
            BigipPropertySpec(name="source-integrity-location", value_type="string"),
            BigipPropertySpec(name="suggested-username-header", value_type="string"),
            BigipPropertySpec(
                name="trigger-irule",
                value_type="enum",
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(name="type", value_type="enum", enum_values=("explicit", "wildcard")),
            BigipPropertySpec(
                name="urls",
                value_type="list",
                allow_none=True,
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="app-layer-encryption",
                value_type="unknown",
                in_sections=("urls",),
            ),
            BigipPropertySpec(
                name="add-decoy-inputs",
                value_type="enum",
                in_sections=("urls", "app-layer-encryption"),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="auto-complete-block",
                value_type="enum",
                in_sections=("urls", "app-layer-encryption"),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="auto-complete-whitelist-functions",
                value_type="list",
                in_sections=("urls", "app-layer-encryption"),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="custom-encryption-function",
                value_type="string",
                in_sections=("urls", "app-layer-encryption"),
                allow_none=True,
            ),
            BigipPropertySpec(
                name="fake-strokes",
                value_type="enum",
                in_sections=("urls", "app-layer-encryption"),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="full-ajax-encryption",
                value_type="enum",
                in_sections=("urls", "app-layer-encryption"),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="hide-password-revealer",
                value_type="enum",
                in_sections=("urls", "app-layer-encryption"),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="html-field-obfuscation",
                value_type="enum",
                in_sections=("urls", "app-layer-encryption"),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="real-time-encryption",
                value_type="enum",
                in_sections=("urls", "app-layer-encryption"),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="remove-element-ids",
                value_type="enum",
                in_sections=("urls", "app-layer-encryption"),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="remove-event-listeners",
                value_type="enum",
                in_sections=("urls", "app-layer-encryption"),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="stolen-creds",
                value_type="enum",
                in_sections=("urls", "app-layer-encryption"),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="substitute-value-function",
                value_type="string",
                in_sections=("urls", "app-layer-encryption"),
                allow_none=True,
            ),
            BigipPropertySpec(name="auto-transactions", value_type="list", in_sections=("urls",)),
            BigipPropertySpec(
                name="attach-ajax-payload-to-alerts",
                value_type="enum",
                in_sections=("urls", "auto-transactions"),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="bot-score",
                value_type="integer",
                in_sections=("urls", "auto-transactions"),
            ),
            BigipPropertySpec(
                name="browser",
                value_type="enum",
                in_sections=("urls", "auto-transactions"),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="click-score",
                value_type="integer",
                in_sections=("urls", "auto-transactions"),
            ),
            BigipPropertySpec(
                name="full-ajax-integrity",
                value_type="enum",
                in_sections=("urls", "auto-transactions"),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="integrity-fail-max-score",
                value_type="integer",
                in_sections=("urls", "auto-transactions"),
            ),
            BigipPropertySpec(
                name="integrity-fail-score",
                value_type="integer",
                in_sections=("urls", "auto-transactions"),
            ),
            BigipPropertySpec(
                name="min-mouse-move-count",
                value_type="integer",
                in_sections=("urls", "auto-transactions"),
            ),
            BigipPropertySpec(
                name="min-mouse-over-count",
                value_type="integer",
                in_sections=("urls", "auto-transactions"),
            ),
            BigipPropertySpec(
                name="min-report-score",
                value_type="integer",
                in_sections=("urls", "auto-transactions"),
            ),
            BigipPropertySpec(
                name="min-time-to-request",
                value_type="integer",
                in_sections=("urls", "auto-transactions"),
            ),
            BigipPropertySpec(
                name="non-browser",
                value_type="enum",
                in_sections=("urls", "auto-transactions"),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="not-human-score",
                value_type="integer",
                in_sections=("urls", "auto-transactions"),
            ),
            BigipPropertySpec(
                name="strong-integrity",
                value_type="enum",
                in_sections=("urls", "auto-transactions"),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="strong-integrity-user-functions",
                value_type="list",
                in_sections=("urls", "auto-transactions"),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="submit-buttons",
                value_type="list",
                in_sections=("urls", "auto-transactions"),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="tampered-cookie-score",
                value_type="integer",
                in_sections=("urls", "auto-transactions"),
            ),
            BigipPropertySpec(
                name="time-fail-score",
                value_type="integer",
                in_sections=("urls", "auto-transactions"),
            ),
            BigipPropertySpec(
                name="before-load-function",
                value_type="string",
                in_sections=("urls",),
                allow_none=True,
            ),
            BigipPropertySpec(
                name="custom-alerts",
                value_type="list",
                in_sections=("urls",),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="attach-request-part",
                value_type="enum",
                in_sections=("urls", "custom-alerts"),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="component",
                value_type="enum",
                in_sections=("urls", "custom-alerts"),
                enum_values=("auto-transactions", "malware", "mobilesafe", "phishing"),
            ),
            BigipPropertySpec(
                name="header-name",
                value_type="string",
                in_sections=("urls", "custom-alerts"),
                allow_none=True,
            ),
            BigipPropertySpec(
                name="malware-name",
                value_type="string",
                in_sections=("urls", "custom-alerts"),
                allow_none=True,
            ),
            BigipPropertySpec(
                name="message",
                value_type="string",
                in_sections=("urls", "custom-alerts"),
                allow_none=True,
            ),
            BigipPropertySpec(
                name="search-in",
                value_type="enum",
                in_sections=("urls", "custom-alerts"),
                enum_values=("client-ip", "header", "payload"),
            ),
            BigipPropertySpec(
                name="value",
                value_type="string",
                in_sections=("urls", "custom-alerts"),
                allow_none=True,
            ),
            BigipPropertySpec(
                name="users",
                value_type="list",
                list_operators=frozenset(("add", "delete", "modify")),
            ),
            BigipPropertySpec(
                name="modes",
                value_type="list",
                in_sections=("users",),
                list_operators=frozenset(("add", "delete")),
            ),
            BigipPropertySpec(
                name="mode",
                value_type="unknown",
                in_sections=("users", "modes"),
                enum_values=("block", "forensic", "inspection", "remediation"),
            ),
            BigipPropertySpec(
                name="duration",
                value_type="integer",
                in_sections=("users", "modes", "mode"),
            ),
            BigipPropertySpec(
                name="enforce-policy",
                value_type="enum",
                in_sections=("users", "modes", "mode"),
                enum_values=("enforce", "time-limited", "unlimited"),
            ),
            BigipPropertySpec(
                name="first-login-time",
                value_type="unknown",
                in_sections=("users", "modes", "mode"),
            ),
            BigipPropertySpec(name="web-rootkit", value_type="unknown"),
            BigipPropertySpec(
                name="blacklist-functions",
                value_type="list",
                in_sections=("web-rootkit",),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="whitelist-functions",
                value_type="list",
                in_sections=("web-rootkit",),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="whitelist-custom-alerts",
                value_type="list",
                allow_none=True,
                list_operators=frozenset(("add", "delete", "replace-all-with")),
            ),
        ),
    )
