from __future__ import annotations

from ..models import (
    BigipObjectKindSpec,
    BigipObjectSpec,
    BigipPropertySpec,
)
from ._base import register


@register
def register_spec() -> BigipObjectSpec:
    return BigipObjectSpec(
        kind_spec=BigipObjectKindSpec(
            "security_ssh_ciphers",
            module="security",
            object_types=("ssh ciphers",),
        ),
        header_types=(("security", "ssh ciphers"),),
        properties=(
            BigipPropertySpec(name="client", value_type="string"),
            BigipPropertySpec(
                name="curve25519-sha256",
                value_type="enum",
                in_sections=("client",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="curve25519-sha256-libssh-org",
                value_type="enum",
                in_sections=("client",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="ecdh-sha2-nistp256",
                value_type="enum",
                in_sections=("client",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="ecdh-sha2-nistp384",
                value_type="enum",
                in_sections=("client",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="ecdh-sha2-nistp521",
                value_type="enum",
                in_sections=("client",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="diffie-hellman-group18-sha512",
                value_type="enum",
                in_sections=("client",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="diffie-hellman-group16-sha512",
                value_type="enum",
                in_sections=("client",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="diffie-hellman-group-exchange-sha256",
                value_type="enum",
                in_sections=("client",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="diffie-hellman-group14-sha256",
                value_type="enum",
                in_sections=("client",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="diffie-hellman-group14-sha1",
                value_type="enum",
                in_sections=("client",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="diffie-hellman-group1-sha1",
                value_type="enum",
                in_sections=("client",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="ext-info-c",
                value_type="enum",
                in_sections=("client",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="aes256-gcm-openssh-com",
                value_type="enum",
                in_sections=("client",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="aes128-gcm-openssh-com",
                value_type="enum",
                in_sections=("client",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="aes256-ctr",
                value_type="enum",
                in_sections=("client",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="aes192-ctr",
                value_type="enum",
                in_sections=("client",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="aes128-ctr",
                value_type="enum",
                in_sections=("client",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="aes256-cbc",
                value_type="enum",
                in_sections=("client",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="aes192-cbc",
                value_type="enum",
                in_sections=("client",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="aes128-cbc",
                value_type="enum",
                in_sections=("client",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="three-des-cbc",
                value_type="enum",
                in_sections=("client",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="hmac-sha2-256-etm-openssh-com",
                value_type="enum",
                in_sections=("client",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="hmac-sha2-512-etm-openssh-com",
                value_type="enum",
                in_sections=("client",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="hmac-sha1-etm-openssh-com",
                value_type="enum",
                in_sections=("client",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="hmac-sha2-256",
                value_type="enum",
                in_sections=("client",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="hmac-sha2-512",
                value_type="enum",
                in_sections=("client",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="hmac-sha1",
                value_type="enum",
                in_sections=("client",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="server",
                value_type="string",
                pattern="^(?:\\\\d{1,3}(?:\\\\.\\\\d{1,3}){3})(?:/\\\\d{1,2})?$",
            ),
            BigipPropertySpec(
                name="curve25519-sha256",
                value_type="enum",
                in_sections=("server",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="curve25519-sha256-libssh-org",
                value_type="enum",
                in_sections=("server",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="ecdh-sha2-nistp256",
                value_type="enum",
                in_sections=("server",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="ecdh-sha2-nistp384",
                value_type="enum",
                in_sections=("server",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="ecdh-sha2-nistp521",
                value_type="enum",
                in_sections=("server",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="diffie-hellman-group18-sha512",
                value_type="enum",
                in_sections=("server",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="diffie-hellman-group16-sha512",
                value_type="enum",
                in_sections=("server",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="diffie-hellman-group-exchange-sha256",
                value_type="enum",
                in_sections=("server",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="diffie-hellman-group14-sha256",
                value_type="enum",
                in_sections=("server",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="diffie-hellman-group14-sha1",
                value_type="enum",
                in_sections=("server",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="diffie-hellman-group1-sha1",
                value_type="enum",
                in_sections=("server",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="ext-info-c",
                value_type="enum",
                in_sections=("server",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="aes256-gcm-openssh-com",
                value_type="enum",
                in_sections=("server",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="aes128-gcm-openssh-com",
                value_type="enum",
                in_sections=("server",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="aes256-ctr",
                value_type="enum",
                in_sections=("server",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="aes192-ctr",
                value_type="enum",
                in_sections=("server",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="aes128-ctr",
                value_type="enum",
                in_sections=("server",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="aes256-cbc",
                value_type="enum",
                in_sections=("server",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="aes192-cbc",
                value_type="enum",
                in_sections=("server",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="aes128-cbc",
                value_type="enum",
                in_sections=("server",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="three-des-cbc",
                value_type="enum",
                in_sections=("server",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="hmac-sha2-256-etm-openssh-com",
                value_type="enum",
                in_sections=("server",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="hmac-sha2-512-etm-openssh-com",
                value_type="enum",
                in_sections=("server",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="hmac-sha1-etm-openssh-com",
                value_type="enum",
                in_sections=("server",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="hmac-sha2-256",
                value_type="enum",
                in_sections=("server",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="hmac-sha2-512",
                value_type="enum",
                in_sections=("server",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="hmac-sha1",
                value_type="enum",
                in_sections=("server",),
                enum_values=("disabled", "enabled"),
            ),
        ),
    )
