from __future__ import annotations

from ..models import (
    BigipObjectKindSpec,
    BigipObjectSpec,
    BigipPropertySpec,
)
from ._base import register


@register
def register_spec() -> BigipObjectSpec:
    return BigipObjectSpec(
        kind_spec=BigipObjectKindSpec(
            "security_log_profile",
            module="security",
            object_types=("log profile",),
        ),
        header_types=(("security", "log profile"),),
        properties=(
            BigipPropertySpec(
                name="antifraud",
                value_type="list",
                allow_none=True,
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="encode-fields",
                value_type="list",
                in_sections=("antifraud",),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="events",
                value_type="list",
                in_sections=("antifraud",),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="type",
                value_type="unknown",
                in_sections=("antifraud", "events"),
                enum_values=("alert", "login"),
            ),
            BigipPropertySpec(
                name="format",
                value_type="unknown",
                in_sections=("antifraud", "events", "type"),
            ),
            BigipPropertySpec(
                name="type",
                value_type="enum",
                in_sections=("antifraud", "events", "type", "format"),
                allow_none=True,
                enum_values=("default", "none", "user-defined"),
            ),
            BigipPropertySpec(
                name="user-template",
                value_type="string",
                in_sections=("antifraud", "events", "type", "format"),
            ),
            BigipPropertySpec(
                name="rate-limit",
                value_type="integer",
                in_sections=("antifraud", "events", "type"),
            ),
            BigipPropertySpec(
                name="rate-limit-template",
                value_type="string",
                in_sections=("antifraud",),
            ),
            BigipPropertySpec(
                name="remote-publisher",
                value_type="reference",
                in_sections=("antifraud",),
                allow_none=True,
            ),
            BigipPropertySpec(name="app-service", value_type="string", allow_none=True),
            BigipPropertySpec(
                name="application",
                value_type="list",
                allow_none=True,
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="facility",
                value_type="enum",
                in_sections=("application",),
                enum_values=(
                    "local0",
                    "local1",
                    "local2",
                    "local3",
                    "local4",
                    "local5",
                    "local6",
                    "local7",
                ),
            ),
            BigipPropertySpec(
                name="filter",
                value_type="list",
                in_sections=("application",),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="key",
                value_type="unknown",
                in_sections=("application", "filter"),
                enum_values=(
                    "http-method",
                    "protocol",
                    "request-type",
                    "response-code",
                    "search-all",
                    "search-in-headers",
                    "search-in-post-data",
                    "search-in-request",
                    "search-in-uri",
                ),
            ),
            BigipPropertySpec(
                name="values",
                value_type="list",
                in_sections=("application", "filter", "key"),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "replace-all-with")),
            ),
            BigipPropertySpec(name="format", value_type="unknown", in_sections=("application",)),
            BigipPropertySpec(
                name="field-delimiter",
                value_type="string",
                in_sections=("application", "format"),
            ),
            BigipPropertySpec(
                name="field-format",
                value_type="string",
                in_sections=("application", "format"),
            ),
            BigipPropertySpec(
                name="fields",
                value_type="list",
                in_sections=("application", "format"),
            ),
            BigipPropertySpec(
                name="type",
                value_type="enum",
                in_sections=("application", "format"),
                enum_values=("predefined", "user-defined"),
            ),
            BigipPropertySpec(
                name="user-string",
                value_type="string",
                in_sections=("application", "format"),
            ),
            BigipPropertySpec(
                name="guarantee-logging",
                value_type="enum",
                in_sections=("application",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="guarantee-response-logging",
                value_type="enum",
                in_sections=("application",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="local-storage",
                value_type="enum",
                in_sections=("application",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="logic-operation",
                value_type="enum",
                in_sections=("application",),
                enum_values=("and", "or"),
            ),
            BigipPropertySpec(
                name="maximum-entry-length",
                value_type="enum",
                in_sections=("application",),
                enum_values=("10k", "1k", "2k", "64k"),
            ),
            BigipPropertySpec(
                name="maximum-header-size",
                value_type="integer",
                in_sections=("application",),
            ),
            BigipPropertySpec(
                name="maximum-query-size",
                value_type="integer",
                in_sections=("application",),
            ),
            BigipPropertySpec(
                name="maximum-request-size",
                value_type="integer",
                in_sections=("application",),
            ),
            BigipPropertySpec(
                name="protocol",
                value_type="enum",
                in_sections=("application",),
                enum_values=("tcp", "tcp-rfc3195", "udp"),
            ),
            BigipPropertySpec(
                name="remote-storage",
                value_type="enum",
                in_sections=("application",),
                allow_none=True,
                enum_values=("arcsight", "none", "remote", "splunk"),
            ),
            BigipPropertySpec(
                name="report-anomalies",
                value_type="enum",
                in_sections=("application",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="response-logging",
                value_type="enum",
                in_sections=("application",),
                allow_none=True,
                enum_values=("all", "illegal", "none"),
            ),
            BigipPropertySpec(
                name="servers",
                value_type="list",
                in_sections=("application",),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="bot-defense",
                value_type="list",
                allow_none=True,
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(name="filter", value_type="unknown", in_sections=("bot-defense",)),
            BigipPropertySpec(
                name="log-bot-signature-matched-requests",
                value_type="enum",
                in_sections=("bot-defense", "filter"),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="log-captcha-challenged-requests",
                value_type="enum",
                in_sections=("bot-defense", "filter"),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="log-challenged-requests",
                value_type="enum",
                in_sections=("bot-defense", "filter"),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="log-illegal-requests",
                value_type="enum",
                in_sections=("bot-defense", "filter"),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="log-legal-requests",
                value_type="enum",
                in_sections=("bot-defense", "filter"),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="local-publisher",
                value_type="reference",
                in_sections=("bot-defense",),
            ),
            BigipPropertySpec(
                name="remote-publisher",
                value_type="reference",
                in_sections=("bot-defense",),
            ),
            BigipPropertySpec(
                name="built-in",
                value_type="enum",
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(name="description", value_type="string"),
            BigipPropertySpec(
                name="dos-application",
                value_type="list",
                allow_none=True,
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="local-publisher",
                value_type="reference",
                in_sections=("dos-application",),
            ),
            BigipPropertySpec(
                name="remote-publisher",
                value_type="reference",
                in_sections=("dos-application",),
            ),
            BigipPropertySpec(name="dos-network-publisher", value_type="reference"),
            BigipPropertySpec(name="flowspec", value_type="unknown"),
            BigipPropertySpec(
                name="log-publisher",
                value_type="reference",
                in_sections=("flowspec",),
            ),
            BigipPropertySpec(name="ip-intelligence", value_type="unknown"),
            BigipPropertySpec(
                name="aggregate-rate",
                value_type="integer",
                in_sections=("ip-intelligence",),
            ),
            BigipPropertySpec(
                name="log-geo",
                value_type="enum",
                in_sections=("ip-intelligence",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="log-publisher",
                value_type="reference",
                in_sections=("ip-intelligence",),
            ),
            BigipPropertySpec(
                name="log-rtbh",
                value_type="enum",
                in_sections=("ip-intelligence",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="log-scrubber",
                value_type="enum",
                in_sections=("ip-intelligence",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="log-shun",
                value_type="enum",
                in_sections=("ip-intelligence",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="log-translation-fields",
                value_type="enum",
                in_sections=("ip-intelligence",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(name="nat", value_type="unknown"),
            BigipPropertySpec(
                name="end-inbound-session",
                value_type="enum",
                in_sections=("nat",),
                enum_values=("backup-allocation-only", "disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="end-outbound-session",
                value_type="unknown",
                in_sections=("nat",),
            ),
            BigipPropertySpec(
                name="action",
                value_type="enum",
                in_sections=("nat", "end-outbound-session"),
                enum_values=("backup-allocation-only", "disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="elements",
                value_type="list",
                in_sections=("nat", "end-outbound-session"),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="errors",
                value_type="enum",
                in_sections=("nat",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(name="format", value_type="unknown", in_sections=("nat",)),
            BigipPropertySpec(
                name="end-inbound-session",
                value_type="unknown",
                in_sections=("nat", "format"),
            ),
            BigipPropertySpec(
                name="field-list",
                value_type="unknown",
                in_sections=("nat", "format", "end-inbound-session"),
                allow_none=True,
                enum_values=(
                    "dest_ip",
                    "duration",
                    "none",
                    "protocol",
                    "route_domain",
                    "src_ip",
                    "sub_id",
                    "timestamp",
                    "translated_dest_ip",
                    "translated_route_domain",
                    "translated_src_ip",
                ),
                references=(
                    "analytics_bot_defense_event_report",
                    "apm_policy_agent_irule_event",
                    "apm_saml_auth_context_class_list",
                    "security_device_device_context",
                    "security_firewall_context_stat",
                    "sys_icall_event",
                ),
            ),
            BigipPropertySpec(
                name="field-list-delimiter",
                value_type="string",
                in_sections=("nat", "format", "end-inbound-session"),
            ),
            BigipPropertySpec(
                name="type",
                value_type="enum",
                in_sections=("nat", "format", "end-inbound-session"),
                allow_none=True,
                enum_values=("field-list", "none", "user-defined"),
            ),
            BigipPropertySpec(
                name="user-defined",
                value_type="string",
                in_sections=("nat", "format", "end-inbound-session"),
            ),
            BigipPropertySpec(
                name="end-outbound-session",
                value_type="unknown",
                in_sections=("nat", "format"),
            ),
            BigipPropertySpec(
                name="field-list",
                value_type="unknown",
                in_sections=("nat", "format", "end-outbound-session"),
                allow_none=True,
                enum_values=(
                    "dest_ip",
                    "duration",
                    "none",
                    "protocol",
                    "route_domain",
                    "src_ip",
                    "sub_id",
                    "timestamp",
                    "translated_dest_ip",
                    "translated_route_domain",
                    "translated_src_ip",
                ),
                references=(
                    "analytics_bot_defense_event_report",
                    "apm_policy_agent_irule_event",
                    "apm_saml_auth_context_class_list",
                    "security_device_device_context",
                    "security_firewall_context_stat",
                    "sys_icall_event",
                ),
            ),
            BigipPropertySpec(
                name="field-list-delimiter",
                value_type="string",
                in_sections=("nat", "format", "end-outbound-session"),
            ),
            BigipPropertySpec(
                name="type",
                value_type="enum",
                in_sections=("nat", "format", "end-outbound-session"),
                allow_none=True,
                enum_values=("field-list", "none", "user-defined"),
            ),
            BigipPropertySpec(
                name="user-defined",
                value_type="string",
                in_sections=("nat", "format", "end-outbound-session"),
            ),
            BigipPropertySpec(name="errors", value_type="list", in_sections=("nat", "format")),
            BigipPropertySpec(
                name="field-list",
                value_type="unknown",
                in_sections=("nat", "format", "errors"),
                allow_none=True,
                enum_values=(
                    "dest_ip",
                    "duration",
                    "none",
                    "protocol",
                    "route_domain",
                    "src_ip",
                    "sub_id",
                    "timestamp",
                    "translated_dest_ip",
                    "translated_route_domain",
                    "translated_src_ip",
                ),
                references=(
                    "analytics_bot_defense_event_report",
                    "apm_policy_agent_irule_event",
                    "apm_saml_auth_context_class_list",
                    "security_device_device_context",
                    "security_firewall_context_stat",
                    "sys_icall_event",
                ),
            ),
            BigipPropertySpec(
                name="field-list-delimiter",
                value_type="string",
                in_sections=("nat", "format", "errors"),
            ),
            BigipPropertySpec(
                name="type",
                value_type="enum",
                in_sections=("nat", "format", "errors"),
                allow_none=True,
                enum_values=("field-list", "none", "user-defined"),
            ),
            BigipPropertySpec(
                name="user-defined",
                value_type="string",
                in_sections=("nat", "format", "errors"),
            ),
            BigipPropertySpec(
                name="quota-exceeded",
                value_type="unknown",
                in_sections=("nat", "format"),
            ),
            BigipPropertySpec(
                name="field-list",
                value_type="unknown",
                in_sections=("nat", "format", "quota-exceeded"),
                allow_none=True,
                enum_values=(
                    "dest_ip",
                    "duration",
                    "none",
                    "protocol",
                    "route_domain",
                    "src_ip",
                    "sub_id",
                    "timestamp",
                    "translated_dest_ip",
                    "translated_route_domain",
                    "translated_src_ip",
                ),
                references=(
                    "analytics_bot_defense_event_report",
                    "apm_policy_agent_irule_event",
                    "apm_saml_auth_context_class_list",
                    "security_device_device_context",
                    "security_firewall_context_stat",
                    "sys_icall_event",
                ),
            ),
            BigipPropertySpec(
                name="field-list-delimiter",
                value_type="string",
                in_sections=("nat", "format", "quota-exceeded"),
            ),
            BigipPropertySpec(
                name="type",
                value_type="enum",
                in_sections=("nat", "format", "quota-exceeded"),
                allow_none=True,
                enum_values=("field-list", "none", "user-defined"),
            ),
            BigipPropertySpec(
                name="user-defined",
                value_type="string",
                in_sections=("nat", "format", "quota-exceeded"),
            ),
            BigipPropertySpec(
                name="start-inbound-session",
                value_type="unknown",
                in_sections=("nat", "format"),
            ),
            BigipPropertySpec(
                name="field-list",
                value_type="unknown",
                in_sections=("nat", "format", "start-inbound-session"),
                allow_none=True,
                enum_values=(
                    "dest_ip",
                    "duration",
                    "none",
                    "protocol",
                    "route_domain",
                    "src_ip",
                    "sub_id",
                    "timestamp",
                    "translated_dest_ip",
                    "translated_route_domain",
                    "translated_src_ip",
                ),
                references=(
                    "analytics_bot_defense_event_report",
                    "apm_policy_agent_irule_event",
                    "apm_saml_auth_context_class_list",
                    "security_device_device_context",
                    "security_firewall_context_stat",
                    "sys_icall_event",
                ),
            ),
            BigipPropertySpec(
                name="field-list-delimiter",
                value_type="string",
                in_sections=("nat", "format", "start-inbound-session"),
            ),
            BigipPropertySpec(
                name="type",
                value_type="enum",
                in_sections=("nat", "format", "start-inbound-session"),
                allow_none=True,
                enum_values=("field-list", "none", "user-defined"),
            ),
            BigipPropertySpec(
                name="user-defined",
                value_type="string",
                in_sections=("nat", "format", "start-inbound-session"),
            ),
            BigipPropertySpec(
                name="start-outbound-session",
                value_type="unknown",
                in_sections=("nat", "format"),
            ),
            BigipPropertySpec(
                name="field-list",
                value_type="unknown",
                in_sections=("nat", "format", "start-outbound-session"),
                allow_none=True,
                enum_values=(
                    "dest_ip",
                    "duration",
                    "none",
                    "protocol",
                    "route_domain",
                    "src_ip",
                    "sub_id",
                    "timestamp",
                    "translated_dest_ip",
                    "translated_route_domain",
                    "translated_src_ip",
                ),
                references=(
                    "analytics_bot_defense_event_report",
                    "apm_policy_agent_irule_event",
                    "apm_saml_auth_context_class_list",
                    "security_device_device_context",
                    "security_firewall_context_stat",
                    "sys_icall_event",
                ),
            ),
            BigipPropertySpec(
                name="field-list-delimiter",
                value_type="string",
                in_sections=("nat", "format", "start-outbound-session"),
            ),
            BigipPropertySpec(
                name="type",
                value_type="enum",
                in_sections=("nat", "format", "start-outbound-session"),
                allow_none=True,
                enum_values=("field-list", "none", "user-defined"),
            ),
            BigipPropertySpec(
                name="user-defined",
                value_type="string",
                in_sections=("nat", "format", "start-outbound-session"),
            ),
            BigipPropertySpec(name="log-publisher", value_type="reference", in_sections=("nat",)),
            BigipPropertySpec(
                name="log-subscriber-id",
                value_type="enum",
                in_sections=("nat",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="lsn-legacy-mode",
                value_type="enum",
                in_sections=("nat",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="quota-exceeded",
                value_type="enum",
                in_sections=("nat",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(name="rate-limit", value_type="unknown", in_sections=("nat",)),
            BigipPropertySpec(
                name="aggregate-rate",
                value_type="integer",
                in_sections=("nat", "rate-limit"),
            ),
            BigipPropertySpec(
                name="end-inbound-session",
                value_type="integer",
                in_sections=("nat", "rate-limit"),
            ),
            BigipPropertySpec(
                name="end-outbound-session",
                value_type="integer",
                in_sections=("nat", "rate-limit"),
            ),
            BigipPropertySpec(
                name="errors",
                value_type="integer",
                in_sections=("nat", "rate-limit"),
            ),
            BigipPropertySpec(
                name="quota-exceeded",
                value_type="integer",
                in_sections=("nat", "rate-limit"),
            ),
            BigipPropertySpec(
                name="start-inbound-session",
                value_type="integer",
                in_sections=("nat", "rate-limit"),
            ),
            BigipPropertySpec(
                name="start-outbound-session",
                value_type="integer",
                in_sections=("nat", "rate-limit"),
            ),
            BigipPropertySpec(
                name="start-inbound-session",
                value_type="enum",
                in_sections=("nat",),
                enum_values=("backup-allocation-only", "disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="start-outbound-session",
                value_type="unknown",
                in_sections=("nat",),
            ),
            BigipPropertySpec(
                name="action",
                value_type="enum",
                in_sections=("nat", "start-outbound-session"),
                enum_values=("backup-allocation-only", "disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="elements",
                value_type="list",
                in_sections=("nat", "start-outbound-session"),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="network",
                value_type="list",
                allow_none=True,
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(name="filter", value_type="unknown", in_sections=("network",)),
            BigipPropertySpec(
                name="log-acl-match-accept",
                value_type="enum",
                in_sections=("network", "filter"),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="log-acl-match-drop",
                value_type="enum",
                in_sections=("network", "filter"),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="log-acl-match-reject",
                value_type="enum",
                in_sections=("network", "filter"),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="log-geo-always",
                value_type="enum",
                in_sections=("network", "filter"),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="log-ip-errors",
                value_type="enum",
                in_sections=("network", "filter"),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="log-tcp-errors",
                value_type="enum",
                in_sections=("network", "filter"),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="log-tcp-events",
                value_type="enum",
                in_sections=("network", "filter"),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="log-translation-fields",
                value_type="enum",
                in_sections=("network", "filter"),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="log-uuid-field",
                value_type="enum",
                in_sections=("network", "filter"),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(name="format", value_type="unknown", in_sections=("network",)),
            BigipPropertySpec(
                name="field-list",
                value_type="unknown",
                in_sections=("network", "format"),
                allow_none=True,
                enum_values=(
                    "acl_policy_type",
                    "acl_rule_uuid",
                    "action",
                    "context_type",
                    "date_time",
                    "dest_ip",
                    "drop_reason",
                    "none",
                    "protocol",
                    "route_domain",
                    "sa_translation_pool",
                    "sa_translation_type",
                    "src_ip",
                    "translated_dest_ip",
                    "translated_ip_protocol",
                    "translated_route_domain",
                    "translated_src_ip",
                    "translated_vlan",
                ),
                references=(
                    "apm_saml_auth_context_class_list",
                    "security_device_device_context",
                    "security_firewall_context_stat",
                ),
            ),
            BigipPropertySpec(
                name="field-list-delimiter",
                value_type="string",
                in_sections=("network", "format"),
            ),
            BigipPropertySpec(
                name="type",
                value_type="enum",
                in_sections=("network", "format"),
                allow_none=True,
                enum_values=("field-list", "none", "user-defined"),
            ),
            BigipPropertySpec(
                name="user-defined",
                value_type="string",
                in_sections=("network", "format"),
            ),
            BigipPropertySpec(
                name="publisher",
                value_type="reference",
                in_sections=("network",),
                references=(
                    "security_blacklist_publisher_all_blacklist_publisher",
                    "security_blacklist_publisher_blacklist_publisher_stats",
                    "security_blacklist_publisher_by_addr",
                    "security_blacklist_publisher_by_category",
                    "security_blacklist_publisher_category",
                    "security_blacklist_publisher_profile",
                    "sys_icall_publisher",
                    "sys_log_config_publisher",
                ),
            ),
            BigipPropertySpec(name="rate-limit", value_type="unknown", in_sections=("network",)),
            BigipPropertySpec(
                name="acl-match-accept",
                value_type="integer",
                in_sections=("network", "rate-limit"),
            ),
            BigipPropertySpec(
                name="acl-match-drop",
                value_type="integer",
                in_sections=("network", "rate-limit"),
            ),
            BigipPropertySpec(
                name="acl-match-reject",
                value_type="integer",
                in_sections=("network", "rate-limit"),
            ),
            BigipPropertySpec(
                name="aggregate-rate",
                value_type="integer",
                in_sections=("network", "rate-limit"),
            ),
            BigipPropertySpec(
                name="ip-errors",
                value_type="integer",
                in_sections=("network", "rate-limit"),
            ),
            BigipPropertySpec(
                name="tcp-errors",
                value_type="integer",
                in_sections=("network", "rate-limit"),
            ),
            BigipPropertySpec(
                name="tcp-events",
                value_type="integer",
                in_sections=("network", "rate-limit"),
            ),
            BigipPropertySpec(name="port-misuse", value_type="unknown"),
            BigipPropertySpec(
                name="aggregate-rate",
                value_type="integer",
                in_sections=("port-misuse",),
            ),
            BigipPropertySpec(
                name="log-publisher",
                value_type="reference",
                in_sections=("port-misuse",),
            ),
            BigipPropertySpec(
                name="protocol-dns",
                value_type="list",
                allow_none=True,
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(name="protocol-dns-dos-publisher", value_type="reference"),
            BigipPropertySpec(name="filter", value_type="unknown", in_sections=("protocol-dns",)),
            BigipPropertySpec(
                name="log-dns-drop",
                value_type="enum",
                in_sections=("protocol-dns", "filter"),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="log-dns-filtered-drop",
                value_type="enum",
                in_sections=("protocol-dns", "filter"),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="log-dns-malformed",
                value_type="enum",
                in_sections=("protocol-dns", "filter"),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="log-dns-malicious",
                value_type="enum",
                in_sections=("protocol-dns", "filter"),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="log-dns-reject",
                value_type="enum",
                in_sections=("protocol-dns", "filter"),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(name="format", value_type="unknown", in_sections=("protocol-dns",)),
            BigipPropertySpec(
                name="field-list",
                value_type="unknown",
                in_sections=("protocol-dns", "format"),
                allow_none=True,
                enum_values=(
                    "attack_type",
                    "date_time",
                    "dest_ip",
                    "dns_query_type",
                    "none",
                    "src_ip",
                    "vlan",
                ),
                references=(
                    "apm_saml_auth_context_class_list",
                    "security_device_device_context",
                    "security_firewall_context_stat",
                ),
            ),
            BigipPropertySpec(
                name="field-list-delimiter",
                value_type="string",
                in_sections=("protocol-dns", "format"),
            ),
            BigipPropertySpec(
                name="type",
                value_type="enum",
                in_sections=("protocol-dns", "format"),
                allow_none=True,
                enum_values=("field-list", "none", "user-defined"),
            ),
            BigipPropertySpec(
                name="user-defined",
                value_type="string",
                in_sections=("protocol-dns", "format"),
            ),
            BigipPropertySpec(
                name="publisher",
                value_type="reference",
                in_sections=("protocol-dns",),
                references=(
                    "security_blacklist_publisher_all_blacklist_publisher",
                    "security_blacklist_publisher_blacklist_publisher_stats",
                    "security_blacklist_publisher_by_addr",
                    "security_blacklist_publisher_by_category",
                    "security_blacklist_publisher_category",
                    "security_blacklist_publisher_profile",
                    "sys_icall_publisher",
                    "sys_log_config_publisher",
                ),
            ),
            BigipPropertySpec(
                name="protocol-sip",
                value_type="list",
                allow_none=True,
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(name="protocol-sip-dos-publisher", value_type="reference"),
            BigipPropertySpec(name="filter", value_type="unknown", in_sections=("protocol-sip",)),
            BigipPropertySpec(
                name="log-sip-drop",
                value_type="enum",
                in_sections=("protocol-sip", "filter"),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="log-sip-global-failures",
                value_type="enum",
                in_sections=("protocol-sip", "filter"),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="log-sip-malformed",
                value_type="enum",
                in_sections=("protocol-sip", "filter"),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="log-sip-redirection-responses",
                value_type="enum",
                in_sections=("protocol-sip", "filter"),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="log-sip-request-failures",
                value_type="enum",
                in_sections=("protocol-sip", "filter"),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="log-sip-server-errors",
                value_type="enum",
                in_sections=("protocol-sip", "filter"),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(name="format", value_type="unknown", in_sections=("protocol-sip",)),
            BigipPropertySpec(
                name="field-list",
                value_type="unknown",
                in_sections=("protocol-sip", "format"),
                allow_none=True,
                enum_values=(
                    "attack_type",
                    "date_time",
                    "dest_ip",
                    "none",
                    "sip_callee",
                    "sip_caller",
                    "sip_method_type",
                    "src_ip",
                    "vlan",
                ),
                references=(
                    "apm_saml_auth_context_class_list",
                    "security_device_device_context",
                    "security_firewall_context_stat",
                ),
            ),
            BigipPropertySpec(
                name="field-list-delimiter",
                value_type="string",
                in_sections=("protocol-sip", "format"),
            ),
            BigipPropertySpec(
                name="type",
                value_type="enum",
                in_sections=("protocol-sip", "format"),
                allow_none=True,
                enum_values=("field-list", "none", "user-defined"),
            ),
            BigipPropertySpec(
                name="user-defined",
                value_type="string",
                in_sections=("protocol-sip", "format"),
            ),
            BigipPropertySpec(
                name="publisher",
                value_type="reference",
                in_sections=("protocol-sip",),
                references=(
                    "security_blacklist_publisher_all_blacklist_publisher",
                    "security_blacklist_publisher_blacklist_publisher_stats",
                    "security_blacklist_publisher_by_addr",
                    "security_blacklist_publisher_by_category",
                    "security_blacklist_publisher_category",
                    "security_blacklist_publisher_profile",
                    "sys_icall_publisher",
                    "sys_log_config_publisher",
                ),
            ),
            BigipPropertySpec(
                name="protocol-transfer",
                value_type="list",
                allow_none=True,
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="publisher",
                value_type="reference",
                in_sections=("protocol-transfer",),
                references=(
                    "security_blacklist_publisher_all_blacklist_publisher",
                    "security_blacklist_publisher_blacklist_publisher_stats",
                    "security_blacklist_publisher_by_addr",
                    "security_blacklist_publisher_by_category",
                    "security_blacklist_publisher_category",
                    "security_blacklist_publisher_profile",
                    "sys_icall_publisher",
                    "sys_log_config_publisher",
                ),
            ),
            BigipPropertySpec(name="traffic-statistics", value_type="list"),
            BigipPropertySpec(
                name="log-missed-flows",
                value_type="enum",
                in_sections=("traffic-statistics",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="log-publisher",
                value_type="reference",
                in_sections=("traffic-statistics",),
            ),
            BigipPropertySpec(
                name="log-reaped-flows",
                value_type="enum",
                in_sections=("traffic-statistics",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="log-sctive-flows",
                value_type="enum",
                in_sections=("traffic-statistics",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="log-syncookies",
                value_type="enum",
                in_sections=("traffic-statistics",),
                enum_values=("disabled", "enabled"),
            ),
            BigipPropertySpec(
                name="log-syncookies-whitelist",
                value_type="enum",
                in_sections=("traffic-statistics",),
                enum_values=("disabled", "enabled"),
            ),
        ),
    )
