from __future__ import annotations

from ..models import (
    BigipObjectKindSpec,
    BigipObjectSpec,
    BigipPropertySpec,
)
from ._base import register


@register
def register_spec() -> BigipObjectSpec:
    return BigipObjectSpec(
        kind_spec=BigipObjectKindSpec(
            "security_dos_device_config",
            module="security",
            object_types=("dos device-config",),
        ),
        header_types=(("security", "dos device-config"),),
        properties=(
            BigipPropertySpec(
                name="auto-threshold-sensitivity",
                value_type="unknown",
                usage_flags=frozenset(("deprecated",)),
            ),
            BigipPropertySpec(
                name="custom-signatures",
                value_type="list",
                allow_none=True,
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
                block=(
                    BigipPropertySpec(
                        name="manual-detection-threshold",
                        value_type="integer",
                        in_sections=("custom-signatures",),
                        default="infinite",
                    ),
                    BigipPropertySpec(
                        name="manual-mitigation-threshold",
                        value_type="integer",
                        in_sections=("custom-signatures",),
                        default="infinite",
                    ),
                    BigipPropertySpec(
                        name="state",
                        value_type="enum",
                        in_sections=("custom-signatures",),
                        enum_values=("detect-only", "disabled", "learn-only", "mitigate"),
                        default="disabled",
                    ),
                    BigipPropertySpec(
                        name="threshold-mode",
                        value_type="enum",
                        in_sections=("custom-signatures",),
                        enum_values=(
                            "fully-automatic",
                            "manual",
                            "manual-multiplier-mitigation",
                            "stress-based-mitigation",
                        ),
                        default="manual",
                    ),
                ),
            ),
            BigipPropertySpec(
                name="manual-detection-threshold",
                value_type="integer",
                in_sections=("custom-signatures",),
                default="infinite",
            ),
            BigipPropertySpec(
                name="manual-mitigation-threshold",
                value_type="integer",
                in_sections=("custom-signatures",),
                default="infinite",
            ),
            BigipPropertySpec(
                name="state",
                value_type="enum",
                in_sections=("custom-signatures",),
                enum_values=("detect-only", "disabled", "learn-only", "mitigate"),
                default="disabled",
            ),
            BigipPropertySpec(
                name="threshold-mode",
                value_type="enum",
                in_sections=("custom-signatures",),
                enum_values=(
                    "fully-automatic",
                    "manual",
                    "manual-multiplier-mitigation",
                    "stress-based-mitigation",
                ),
                default="manual",
            ),
            BigipPropertySpec(name="dns-dos-mitigation-percentage", value_type="integer"),
            BigipPropertySpec(name="dns-nxdomain-stat", value_type="unknown"),
            BigipPropertySpec(
                name="dos-device-vector",
                value_type="unknown",
                shape_kind="object",
                block=(
                    BigipPropertySpec(
                        name="allow-advertisement",
                        value_type="enum",
                        in_sections=("dos-device-vector",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                    ),
                    BigipPropertySpec(
                        name="allow-upstream-scrubbing",
                        value_type="enum",
                        in_sections=("dos-device-vector",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                    ),
                    BigipPropertySpec(
                        name="attacked-dst",
                        value_type="enum",
                        in_sections=("dos-device-vector",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                    ),
                    BigipPropertySpec(
                        name="auto-blacklisting",
                        value_type="enum",
                        in_sections=("dos-device-vector",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                    ),
                    BigipPropertySpec(
                        name="auto-scrubbing",
                        value_type="enum",
                        in_sections=("dos-device-vector",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                    ),
                    BigipPropertySpec(
                        name="auto-threshold",
                        value_type="enum",
                        in_sections=("dos-device-vector",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                    ),
                    BigipPropertySpec(
                        name="bad-actor",
                        value_type="enum",
                        in_sections=("dos-device-vector",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                    ),
                    BigipPropertySpec(
                        name="blacklist-category",
                        value_type="reference",
                        in_sections=("dos-device-vector",),
                        references=("security_ip_intelligence_blacklist_category",),
                    ),
                    BigipPropertySpec(
                        name="blacklist-detection-seconds",
                        value_type="integer",
                        in_sections=("dos-device-vector",),
                    ),
                    BigipPropertySpec(
                        name="blacklist-duration",
                        value_type="integer",
                        in_sections=("dos-device-vector",),
                    ),
                    BigipPropertySpec(
                        name="ceiling",
                        value_type="enum",
                        in_sections=("dos-device-vector",),
                        enum_values=("infinite",),
                    ),
                    BigipPropertySpec(
                        name="default-internal-rate-limit",
                        value_type="enum",
                        in_sections=("dos-device-vector",),
                        enum_values=("infinite",),
                    ),
                    BigipPropertySpec(
                        name="detection-threshold-percent",
                        value_type="enum",
                        in_sections=("dos-device-vector",),
                        enum_values=("infinite",),
                    ),
                    BigipPropertySpec(
                        name="detection-threshold-pps",
                        value_type="enum",
                        in_sections=("dos-device-vector",),
                        enum_values=("infinite",),
                    ),
                    BigipPropertySpec(
                        name="enforce",
                        value_type="enum",
                        in_sections=("dos-device-vector",),
                        enum_values=("disabled", "enabled"),
                        shape_kind="boolean",
                    ),
                    BigipPropertySpec(
                        name="floor",
                        value_type="integer",
                        in_sections=("dos-device-vector",),
                    ),
                    BigipPropertySpec(
                        name="packet-types",
                        value_type="list",
                        in_sections=("dos-device-vector",),
                        allow_none=True,
                        list_operators=frozenset(("add", "delete", "replace-all-with")),
                    ),
                    BigipPropertySpec(
                        name="per-dst-ip-detection-pps",
                        value_type="integer",
                        in_sections=("dos-device-vector",),
                    ),
                    BigipPropertySpec(
                        name="per-dst-ip-limit-pps",
                        value_type="integer",
                        in_sections=("dos-device-vector",),
                    ),
                    BigipPropertySpec(
                        name="per-source-ip-detection-pps",
                        value_type="integer",
                        in_sections=("dos-device-vector",),
                    ),
                    BigipPropertySpec(
                        name="per-source-ip-limit-pps",
                        value_type="integer",
                        in_sections=("dos-device-vector",),
                    ),
                    BigipPropertySpec(
                        name="scrubbing-category",
                        value_type="enum",
                        in_sections=("dos-device-vector",),
                        enum_values=('"none"',),
                    ),
                    BigipPropertySpec(
                        name="scrubbing-detection-seconds",
                        value_type="integer",
                        in_sections=("dos-device-vector",),
                    ),
                    BigipPropertySpec(
                        name="scrubbing-duration",
                        value_type="integer",
                        in_sections=("dos-device-vector",),
                    ),
                    BigipPropertySpec(
                        name="simulate-auto-threshold",
                        value_type="enum",
                        in_sections=("dos-device-vector",),
                        enum_values=("disable", "enable"),
                    ),
                    BigipPropertySpec(
                        name="state",
                        value_type="enum",
                        in_sections=("dos-device-vector",),
                        enum_values=("detect-only", "disabled", "learn-only", "mitigate"),
                        default="disabled",
                    ),
                    BigipPropertySpec(
                        name="suspicious",
                        value_type="enum",
                        in_sections=("dos-device-vector",),
                        enum_values=("false", "true"),
                        shape_kind="boolean",
                    ),
                    BigipPropertySpec(
                        name="threshold-mode",
                        value_type="enum",
                        in_sections=("dos-device-vector",),
                        enum_values=(
                            "fully-automatic",
                            "manual",
                            "manual-multiplier-mitigation",
                            "stress-based-mitigation",
                        ),
                        default="manual",
                    ),
                    BigipPropertySpec(
                        name="tscookie",
                        value_type="enum",
                        in_sections=("dos-device-vector",),
                        enum_values=("disable", "enable"),
                    ),
                    BigipPropertySpec(
                        name="valid-domains",
                        value_type="list",
                        in_sections=("dos-device-vector",),
                        allow_none=True,
                        list_operators=frozenset(("add", "delete", "replace-all-with")),
                    ),
                ),
            ),
            BigipPropertySpec(
                name="allow-advertisement",
                value_type="enum",
                in_sections=("dos-device-vector",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="allow-upstream-scrubbing",
                value_type="enum",
                in_sections=("dos-device-vector",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="attacked-dst",
                value_type="enum",
                in_sections=("dos-device-vector",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="auto-blacklisting",
                value_type="enum",
                in_sections=("dos-device-vector",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="auto-scrubbing",
                value_type="enum",
                in_sections=("dos-device-vector",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="auto-threshold",
                value_type="enum",
                in_sections=("dos-device-vector",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="bad-actor",
                value_type="enum",
                in_sections=("dos-device-vector",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="blacklist-category",
                value_type="reference",
                in_sections=("dos-device-vector",),
                references=("security_ip_intelligence_blacklist_category",),
            ),
            BigipPropertySpec(
                name="blacklist-detection-seconds",
                value_type="integer",
                in_sections=("dos-device-vector",),
            ),
            BigipPropertySpec(
                name="blacklist-duration",
                value_type="integer",
                in_sections=("dos-device-vector",),
            ),
            BigipPropertySpec(
                name="ceiling",
                value_type="enum",
                in_sections=("dos-device-vector",),
                enum_values=("infinite",),
            ),
            BigipPropertySpec(
                name="default-internal-rate-limit",
                value_type="enum",
                in_sections=("dos-device-vector",),
                enum_values=("infinite",),
            ),
            BigipPropertySpec(
                name="detection-threshold-percent",
                value_type="enum",
                in_sections=("dos-device-vector",),
                enum_values=("infinite",),
            ),
            BigipPropertySpec(
                name="detection-threshold-pps",
                value_type="enum",
                in_sections=("dos-device-vector",),
                enum_values=("infinite",),
            ),
            BigipPropertySpec(
                name="enforce",
                value_type="enum",
                in_sections=("dos-device-vector",),
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="floor",
                value_type="integer",
                in_sections=("dos-device-vector",),
            ),
            BigipPropertySpec(
                name="packet-types",
                value_type="list",
                in_sections=("dos-device-vector",),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="per-dst-ip-detection-pps",
                value_type="integer",
                in_sections=("dos-device-vector",),
            ),
            BigipPropertySpec(
                name="per-dst-ip-limit-pps",
                value_type="integer",
                in_sections=("dos-device-vector",),
            ),
            BigipPropertySpec(
                name="per-source-ip-detection-pps",
                value_type="integer",
                in_sections=("dos-device-vector",),
            ),
            BigipPropertySpec(
                name="per-source-ip-limit-pps",
                value_type="integer",
                in_sections=("dos-device-vector",),
            ),
            BigipPropertySpec(
                name="scrubbing-category",
                value_type="enum",
                in_sections=("dos-device-vector",),
                enum_values=('"none"',),
            ),
            BigipPropertySpec(
                name="scrubbing-detection-seconds",
                value_type="integer",
                in_sections=("dos-device-vector",),
            ),
            BigipPropertySpec(
                name="scrubbing-duration",
                value_type="integer",
                in_sections=("dos-device-vector",),
            ),
            BigipPropertySpec(
                name="simulate-auto-threshold",
                value_type="enum",
                in_sections=("dos-device-vector",),
                enum_values=("disable", "enable"),
            ),
            BigipPropertySpec(
                name="state",
                value_type="enum",
                in_sections=("dos-device-vector",),
                enum_values=("detect-only", "disabled", "learn-only", "mitigate"),
                default="disabled",
            ),
            BigipPropertySpec(
                name="suspicious",
                value_type="enum",
                in_sections=("dos-device-vector",),
                enum_values=("false", "true"),
                shape_kind="boolean",
            ),
            BigipPropertySpec(
                name="threshold-mode",
                value_type="enum",
                in_sections=("dos-device-vector",),
                enum_values=(
                    "fully-automatic",
                    "manual",
                    "manual-multiplier-mitigation",
                    "stress-based-mitigation",
                ),
                default="manual",
            ),
            BigipPropertySpec(
                name="tscookie",
                value_type="enum",
                in_sections=("dos-device-vector",),
                enum_values=("disable", "enable"),
            ),
            BigipPropertySpec(
                name="valid-domains",
                value_type="list",
                in_sections=("dos-device-vector",),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="dynamic-signatures",
                value_type="list",
                block=(
                    BigipPropertySpec(
                        name="detection",
                        value_type="enum",
                        in_sections=("dynamic-signatures",),
                        enum_values=("disabled", "enabled", "learn-only"),
                        default="disabled",
                    ),
                    BigipPropertySpec(
                        name="dns",
                        value_type="list",
                        in_sections=("dynamic-signatures",),
                    ),
                    BigipPropertySpec(
                        name="mitigation",
                        value_type="enum",
                        in_sections=("dynamic-signatures",),
                        allow_none=True,
                        enum_values=("high", "low", "medium", "none"),
                        default="none",
                    ),
                    BigipPropertySpec(
                        name="network",
                        value_type="unknown",
                        in_sections=("dynamic-signatures",),
                        shape_kind="object",
                    ),
                    BigipPropertySpec(
                        name="scrubber-advertisement-period",
                        value_type="integer",
                        in_sections=("dynamic-signatures",),
                        default="300 seconds",
                    ),
                    BigipPropertySpec(
                        name="scrubber-category",
                        value_type="reference",
                        in_sections=("dynamic-signatures",),
                    ),
                    BigipPropertySpec(
                        name="scrubber-enable",
                        value_type="enum",
                        in_sections=("dynamic-signatures",),
                        enum_values=("no", "yes"),
                        shape_kind="boolean",
                        default="no",
                    ),
                ),
            ),
            BigipPropertySpec(
                name="detection",
                value_type="enum",
                in_sections=("dynamic-signatures",),
                enum_values=("disabled", "enabled", "learn-only"),
                default="disabled",
            ),
            BigipPropertySpec(
                name="dns",
                value_type="list",
                in_sections=("dynamic-signatures",),
                block=(
                    BigipPropertySpec(
                        name="detection",
                        value_type="enum",
                        in_sections=("dynamic-signatures", "dns"),
                        enum_values=("disabled", "enabled", "learn-only"),
                        default="disabled",
                    ),
                    BigipPropertySpec(
                        name="mitigation",
                        value_type="enum",
                        in_sections=("dynamic-signatures", "dns"),
                        allow_none=True,
                        enum_values=("high", "low", "manual-multiplier", "medium", "none"),
                        default="none",
                    ),
                ),
            ),
            BigipPropertySpec(
                name="detection",
                value_type="enum",
                in_sections=("dynamic-signatures", "dns"),
                enum_values=("disabled", "enabled", "learn-only"),
                default="disabled",
            ),
            BigipPropertySpec(
                name="mitigation",
                value_type="enum",
                in_sections=("dynamic-signatures", "dns"),
                allow_none=True,
                enum_values=("high", "low", "manual-multiplier", "medium", "none"),
                default="none",
            ),
            BigipPropertySpec(
                name="mitigation",
                value_type="enum",
                in_sections=("dynamic-signatures",),
                allow_none=True,
                enum_values=("high", "low", "medium", "none"),
                default="none",
            ),
            BigipPropertySpec(
                name="network",
                value_type="unknown",
                in_sections=("dynamic-signatures",),
                shape_kind="object",
                block=(
                    BigipPropertySpec(
                        name="detection",
                        value_type="enum",
                        in_sections=("dynamic-signatures", "network"),
                        enum_values=("disabled", "enabled", "learn-only"),
                        default="disabled",
                    ),
                    BigipPropertySpec(
                        name="mitigation",
                        value_type="enum",
                        in_sections=("dynamic-signatures", "network"),
                        allow_none=True,
                        enum_values=("high", "low", "manual-multiplier", "medium", "none"),
                        default="none",
                    ),
                    BigipPropertySpec(
                        name="scrubber-advertisement-period",
                        value_type="integer",
                        in_sections=("dynamic-signatures", "network"),
                        default="300 seconds",
                    ),
                    BigipPropertySpec(
                        name="scrubber-category",
                        value_type="reference",
                        in_sections=("dynamic-signatures", "network"),
                    ),
                    BigipPropertySpec(
                        name="scrubber-enable",
                        value_type="enum",
                        in_sections=("dynamic-signatures", "network"),
                        enum_values=("no", "yes"),
                        shape_kind="boolean",
                        default="no",
                    ),
                ),
            ),
            BigipPropertySpec(
                name="detection",
                value_type="enum",
                in_sections=("dynamic-signatures", "network"),
                enum_values=("disabled", "enabled", "learn-only"),
                default="disabled",
            ),
            BigipPropertySpec(
                name="mitigation",
                value_type="enum",
                in_sections=("dynamic-signatures", "network"),
                allow_none=True,
                enum_values=("high", "low", "manual-multiplier", "medium", "none"),
                default="none",
            ),
            BigipPropertySpec(
                name="scrubber-advertisement-period",
                value_type="integer",
                in_sections=("dynamic-signatures", "network"),
                default="300 seconds",
            ),
            BigipPropertySpec(
                name="scrubber-category",
                value_type="reference",
                in_sections=("dynamic-signatures", "network"),
            ),
            BigipPropertySpec(
                name="scrubber-enable",
                value_type="enum",
                in_sections=("dynamic-signatures", "network"),
                enum_values=("no", "yes"),
                shape_kind="boolean",
                default="no",
            ),
            BigipPropertySpec(
                name="scrubber-advertisement-period",
                value_type="integer",
                in_sections=("dynamic-signatures",),
                default="300 seconds",
            ),
            BigipPropertySpec(
                name="scrubber-category",
                value_type="reference",
                in_sections=("dynamic-signatures",),
            ),
            BigipPropertySpec(
                name="scrubber-enable",
                value_type="enum",
                in_sections=("dynamic-signatures",),
                enum_values=("no", "yes"),
                shape_kind="boolean",
                default="no",
            ),
            BigipPropertySpec(
                name="ip-uncommon-protolist",
                value_type="string",
                default="/Common/ip-uncommon-protolist",
            ),
            BigipPropertySpec(name="log-publisher", value_type="reference"),
            BigipPropertySpec(name="network-dos-mitigation-percentage", value_type="integer"),
            BigipPropertySpec(name="sip-dos-mitigation-percentage", value_type="integer"),
            BigipPropertySpec(
                name="syn-cookie-dsr-flow-reset-by",
                value_type="enum",
                allow_none=True,
                enum_values=("bigip", "client", "none"),
                default="none",
            ),
            BigipPropertySpec(
                name="syn-cookie-whitelist",
                value_type="enum",
                enum_values=("disabled", "enabled"),
                shape_kind="boolean",
                default="disabled",
            ),
            BigipPropertySpec(
                name="threshold-sensitivity",
                value_type="enum",
                enum_values=("high", "low", "medium"),
                default="set to medium",
            ),
        ),
    )
