from __future__ import annotations

from ..models import (
    BigipObjectKindSpec,
    BigipObjectSpec,
    BigipPropertySpec,
)
from ._base import register


@register
def register_spec() -> BigipObjectSpec:
    return BigipObjectSpec(
        kind_spec=BigipObjectKindSpec(
            "wam_policy",
            module="wam",
            object_types=("policy",),
        ),
        header_types=(("wam", "policy"),),
        properties=(
            BigipPropertySpec(name="app-service", value_type="string", allow_none=True),
            BigipPropertySpec(name="code", value_type="integer"),
            BigipPropertySpec(name="copy-from", value_type="reference"),
            BigipPropertySpec(name="description", value_type="string"),
            BigipPropertySpec(
                name="invalidations",
                value_type="list",
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="active",
                value_type="enum",
                in_sections=("invalidations",),
                enum_values=("no", "yes"),
            ),
            BigipPropertySpec(
                name="app-service",
                value_type="string",
                in_sections=("invalidations",),
                allow_none=True,
            ),
            BigipPropertySpec(
                name="broadcast",
                value_type="enum",
                in_sections=("invalidations",),
                enum_values=("no", "yes"),
            ),
            BigipPropertySpec(
                name="cache-content",
                value_type="list",
                in_sections=("invalidations",),
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="app-service",
                value_type="string",
                in_sections=("invalidations", "cache-content"),
                allow_none=True,
            ),
            BigipPropertySpec(
                name="arg-alias",
                value_type="string",
                in_sections=("invalidations", "cache-content"),
            ),
            BigipPropertySpec(
                name="arg-direction",
                value_type="enum",
                in_sections=("invalidations", "cache-content"),
                enum_values=("left-to-right", "right-to-left"),
            ),
            BigipPropertySpec(
                name="arg-name",
                value_type="string",
                in_sections=("invalidations", "cache-content"),
            ),
            BigipPropertySpec(
                name="arg-ordinal",
                value_type="unknown",
                in_sections=("invalidations", "cache-content"),
            ),
            BigipPropertySpec(
                name="description",
                value_type="string",
                in_sections=("invalidations", "cache-content"),
            ),
            BigipPropertySpec(
                name="request-data-alias",
                value_type="string",
                in_sections=("invalidations", "cache-content"),
            ),
            BigipPropertySpec(
                name="request-data-direction",
                value_type="enum",
                in_sections=("invalidations", "cache-content"),
                enum_values=("left-to-right", "right-to-left"),
            ),
            BigipPropertySpec(
                name="request-data-name",
                value_type="string",
                in_sections=("invalidations", "cache-content"),
            ),
            BigipPropertySpec(
                name="request-data-ordinal",
                value_type="unknown",
                in_sections=("invalidations", "cache-content"),
            ),
            BigipPropertySpec(
                name="request-data-type",
                value_type="unknown",
                in_sections=("invalidations", "cache-content"),
            ),
            BigipPropertySpec(
                name="value-case-sensitive",
                value_type="enum",
                in_sections=("invalidations", "cache-content"),
                enum_values=("no", "yes"),
            ),
            BigipPropertySpec(
                name="values",
                value_type="list",
                in_sections=("invalidations", "cache-content"),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="app-service",
                value_type="string",
                in_sections=("invalidations", "cache-content", "values"),
                allow_none=True,
            ),
            BigipPropertySpec(
                name="can-be-empty",
                value_type="enum",
                in_sections=("invalidations", "cache-content", "values"),
                enum_values=("no", "yes"),
            ),
            BigipPropertySpec(
                name="can-be-missing",
                value_type="enum",
                in_sections=("invalidations", "cache-content", "values"),
                enum_values=("no", "yes"),
            ),
            BigipPropertySpec(
                name="invert-match",
                value_type="enum",
                in_sections=("invalidations", "cache-content", "values"),
                enum_values=("no", "yes"),
            ),
            BigipPropertySpec(
                name="description",
                value_type="string",
                in_sections=("invalidations",),
            ),
            BigipPropertySpec(
                name="nodes",
                value_type="list",
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="always-proxy",
                value_type="enum",
                in_sections=("nodes",),
                enum_values=("no", "yes"),
            ),
            BigipPropertySpec(
                name="app-service",
                value_type="string",
                in_sections=("nodes",),
                allow_none=True,
            ),
            BigipPropertySpec(name="arg-alias", value_type="string", in_sections=("nodes",)),
            BigipPropertySpec(
                name="arg-direction",
                value_type="enum",
                in_sections=("nodes",),
                enum_values=("left-to-right", "right-to-left"),
            ),
            BigipPropertySpec(name="arg-name", value_type="string", in_sections=("nodes",)),
            BigipPropertySpec(name="arg-ordinal", value_type="unknown", in_sections=("nodes",)),
            BigipPropertySpec(
                name="assembly-compression",
                value_type="enum",
                in_sections=("nodes",),
                enum_values=("disable", "enable"),
            ),
            BigipPropertySpec(
                name="assembly-compression-ows",
                value_type="enum",
                in_sections=("nodes",),
                enum_values=("disable", "enable"),
            ),
            BigipPropertySpec(
                name="assembly-concatenation",
                value_type="enum",
                in_sections=("nodes",),
                enum_values=("disable", "enable"),
            ),
            BigipPropertySpec(
                name="assembly-concatenation-sets",
                value_type="unknown",
                in_sections=("nodes",),
            ),
            BigipPropertySpec(
                name="assembly-css-inlining",
                value_type="enum",
                in_sections=("nodes",),
                enum_values=("disable", "enable"),
            ),
            BigipPropertySpec(
                name="assembly-css-inlining-urls",
                value_type="unknown",
                in_sections=("nodes",),
            ),
            BigipPropertySpec(
                name="assembly-css-reorder",
                value_type="enum",
                in_sections=("nodes",),
                enum_values=("disable", "enable"),
            ),
            BigipPropertySpec(
                name="assembly-css-reorder-cache-size",
                value_type="integer",
                in_sections=("nodes",),
            ),
            BigipPropertySpec(
                name="assembly-css-reorder-urls",
                value_type="unknown",
                in_sections=("nodes",),
            ),
            BigipPropertySpec(
                name="assembly-dns-prefetch",
                value_type="enum",
                in_sections=("nodes",),
                enum_values=("disable", "enable"),
            ),
            BigipPropertySpec(
                name="assembly-dns-prefetch-domain-lists",
                value_type="list",
                in_sections=("nodes",),
                list_operators=frozenset(("add", "delete", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="assembly-dns-prefetch-https-automatic",
                value_type="enum",
                in_sections=("nodes",),
                enum_values=("disable", "enable"),
            ),
            BigipPropertySpec(
                name="assembly-dns-prefetch-https-enable",
                value_type="enum",
                in_sections=("nodes",),
                enum_values=("disable", "enable"),
            ),
            BigipPropertySpec(
                name="assembly-ibr",
                value_type="enum",
                in_sections=("nodes",),
                enum_values=("disable", "enable"),
            ),
            BigipPropertySpec(
                name="assembly-icc-css-inlining-max-size",
                value_type="integer",
                in_sections=("nodes",),
            ),
            BigipPropertySpec(
                name="assembly-icc-force",
                value_type="enum",
                in_sections=("nodes",),
                enum_values=("disable", "enable"),
            ),
            BigipPropertySpec(
                name="assembly-icc-image-max-size",
                value_type="integer",
                in_sections=("nodes",),
            ),
            BigipPropertySpec(
                name="assembly-icc-js-inlining-max-size",
                value_type="integer",
                in_sections=("nodes",),
            ),
            BigipPropertySpec(
                name="assembly-icc-max-num-urls",
                value_type="integer",
                in_sections=("nodes",),
            ),
            BigipPropertySpec(
                name="assembly-icc-min-client-expiry",
                value_type="integer",
                in_sections=("nodes",),
            ),
            BigipPropertySpec(
                name="assembly-image-inlining",
                value_type="enum",
                in_sections=("nodes",),
                enum_values=("disable", "enable"),
            ),
            BigipPropertySpec(
                name="assembly-image-inlining-max-size",
                value_type="integer",
                in_sections=("nodes",),
            ),
            BigipPropertySpec(
                name="assembly-image-inlining-urls",
                value_type="unknown",
                in_sections=("nodes",),
            ),
            BigipPropertySpec(
                name="assembly-intelligent-client-cache",
                value_type="enum",
                in_sections=("nodes",),
                enum_values=("disable", "enable"),
            ),
            BigipPropertySpec(
                name="assembly-js-inlining",
                value_type="enum",
                in_sections=("nodes",),
                enum_values=("disable", "enable"),
            ),
            BigipPropertySpec(
                name="assembly-js-inlining-urls",
                value_type="unknown",
                in_sections=("nodes",),
            ),
            BigipPropertySpec(
                name="assembly-js-reorder",
                value_type="enum",
                in_sections=("nodes",),
                enum_values=("disable", "enable"),
            ),
            BigipPropertySpec(
                name="assembly-js-reorder-cache-size",
                value_type="integer",
                in_sections=("nodes",),
            ),
            BigipPropertySpec(
                name="assembly-js-reorder-urls",
                value_type="unknown",
                in_sections=("nodes",),
            ),
            BigipPropertySpec(
                name="assembly-minification",
                value_type="enum",
                in_sections=("nodes",),
                enum_values=("disable", "enable"),
            ),
            BigipPropertySpec(
                name="assembly-multiconnect",
                value_type="enum",
                in_sections=("nodes",),
                enum_values=("disable", "enable"),
            ),
            BigipPropertySpec(
                name="assembly-on-proxies",
                value_type="enum",
                in_sections=("nodes",),
                enum_values=("disable", "enable"),
            ),
            BigipPropertySpec(
                name="assembly-pdf-linearization",
                value_type="enum",
                in_sections=("nodes",),
                enum_values=("disable", "enable"),
            ),
            BigipPropertySpec(
                name="cache-complete-only",
                value_type="enum",
                in_sections=("nodes",),
                enum_values=("disable", "enable"),
            ),
            BigipPropertySpec(
                name="cache-first-hit",
                value_type="enum",
                in_sections=("nodes",),
                enum_values=("no", "yes"),
            ),
            BigipPropertySpec(
                name="cache-mode",
                value_type="enum",
                in_sections=("nodes",),
                enum_values=("memory-and-disk", "memory-only"),
            ),
            BigipPropertySpec(
                name="cache-priority",
                value_type="enum",
                in_sections=("nodes",),
                enum_values=("high", "low", "medium"),
            ),
            BigipPropertySpec(
                name="cache-stand-in-period",
                value_type="integer",
                in_sections=("nodes",),
            ),
            BigipPropertySpec(
                name="can-be-empty",
                value_type="enum",
                in_sections=("nodes",),
                enum_values=("no", "yes"),
            ),
            BigipPropertySpec(
                name="can-be-missing",
                value_type="enum",
                in_sections=("nodes",),
                enum_values=("no", "yes"),
            ),
            BigipPropertySpec(name="code", value_type="integer", in_sections=("nodes",)),
            BigipPropertySpec(
                name="coherency",
                value_type="enum",
                in_sections=("nodes",),
                enum_values=("blade", "cluster"),
            ),
            BigipPropertySpec(
                name="defaults-from",
                value_type="reference",
                in_sections=("nodes",),
                references=("wam_policy",),
            ),
            BigipPropertySpec(name="description", value_type="string", in_sections=("nodes",)),
            BigipPropertySpec(
                name="invert-match",
                value_type="enum",
                in_sections=("nodes",),
                enum_values=("no", "yes"),
            ),
            BigipPropertySpec(
                name="jpeg-progressive-encoding",
                value_type="enum",
                in_sections=("nodes",),
                enum_values=("no", "yes"),
            ),
            BigipPropertySpec(name="jpeg-quality", value_type="integer", in_sections=("nodes",)),
            BigipPropertySpec(
                name="jpeg-quality-is-relative",
                value_type="enum",
                in_sections=("nodes",),
                enum_values=("no", "yes"),
            ),
            BigipPropertySpec(
                name="jpeg-sampling",
                value_type="enum",
                in_sections=("nodes",),
                enum_values=("1x1", "1x2", "2x1", "2x2", "preserve"),
            ),
            BigipPropertySpec(
                name="jpeg-strip-exif",
                value_type="enum",
                in_sections=("nodes",),
                enum_values=("if-safe", "make-safe", "no", "yes"),
            ),
            BigipPropertySpec(
                name="jpeg-strip-keeps-copyright",
                value_type="enum",
                in_sections=("nodes",),
                enum_values=("no", "yes"),
            ),
            BigipPropertySpec(name="jpegxr-quality", value_type="integer", in_sections=("nodes",)),
            BigipPropertySpec(
                name="lifetime-cache-control-extensions",
                value_type="unknown",
                in_sections=("nodes",),
                allow_none=True,
            ),
            BigipPropertySpec(
                name="lifetime-cache-max-age",
                value_type="integer",
                in_sections=("nodes",),
            ),
            BigipPropertySpec(
                name="lifetime-honor-ows",
                value_type="enum",
                in_sections=("nodes",),
                enum_values=("no", "yes"),
            ),
            BigipPropertySpec(
                name="lifetime-honor-ows-values",
                value_type="unknown",
                in_sections=("nodes",),
                allow_none=True,
            ),
            BigipPropertySpec(
                name="lifetime-honor-request",
                value_type="enum",
                in_sections=("nodes",),
                enum_values=("no", "yes"),
            ),
            BigipPropertySpec(
                name="lifetime-honor-request-values",
                value_type="unknown",
                in_sections=("nodes",),
                allow_none=True,
            ),
            BigipPropertySpec(
                name="lifetime-http-heuristic",
                value_type="unknown",
                in_sections=("nodes",),
            ),
            BigipPropertySpec(
                name="lifetime-insert-no-cache",
                value_type="enum",
                in_sections=("nodes",),
                enum_values=("no", "yes"),
            ),
            BigipPropertySpec(
                name="lifetime-preserve-response",
                value_type="enum",
                in_sections=("nodes",),
                enum_values=("no", "yes"),
            ),
            BigipPropertySpec(
                name="lifetime-preserve-response-values",
                value_type="unknown",
                in_sections=("nodes",),
                allow_none=True,
            ),
            BigipPropertySpec(
                name="lifetime-response-max-age",
                value_type="integer",
                in_sections=("nodes",),
            ),
            BigipPropertySpec(
                name="lifetime-response-s-maxage",
                value_type="integer",
                in_sections=("nodes",),
            ),
            BigipPropertySpec(
                name="lifetime-stand-in-codes",
                value_type="unknown",
                in_sections=("nodes",),
                allow_none=True,
            ),
            BigipPropertySpec(
                name="lifetime-use-heuristic",
                value_type="enum",
                in_sections=("nodes",),
                enum_values=("no", "yes"),
            ),
            BigipPropertySpec(
                name="matching",
                value_type="list",
                in_sections=("nodes",),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="app-service",
                value_type="string",
                in_sections=("nodes", "matching"),
                allow_none=True,
            ),
            BigipPropertySpec(
                name="arg-alias",
                value_type="string",
                in_sections=("nodes", "matching"),
            ),
            BigipPropertySpec(
                name="arg-direction",
                value_type="enum",
                in_sections=("nodes", "matching"),
                enum_values=("left-to-right", "right-to-left"),
            ),
            BigipPropertySpec(
                name="arg-name",
                value_type="string",
                in_sections=("nodes", "matching"),
            ),
            BigipPropertySpec(
                name="arg-ordinal",
                value_type="unknown",
                in_sections=("nodes", "matching"),
            ),
            BigipPropertySpec(
                name="description",
                value_type="string",
                in_sections=("nodes", "matching"),
            ),
            BigipPropertySpec(
                name="value-case-sensitive",
                value_type="enum",
                in_sections=("nodes", "matching"),
                enum_values=("no", "yes"),
            ),
            BigipPropertySpec(
                name="values",
                value_type="list",
                in_sections=("nodes", "matching"),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="app-service",
                value_type="string",
                in_sections=("nodes", "matching", "values"),
                allow_none=True,
            ),
            BigipPropertySpec(
                name="can-be-empty",
                value_type="enum",
                in_sections=("nodes", "matching", "values"),
                enum_values=("no", "yes"),
            ),
            BigipPropertySpec(
                name="can-be-missing",
                value_type="enum",
                in_sections=("nodes", "matching", "values"),
                enum_values=("no", "yes"),
            ),
            BigipPropertySpec(
                name="invert-match",
                value_type="enum",
                in_sections=("nodes", "matching", "values"),
                enum_values=("no", "yes"),
            ),
            BigipPropertySpec(
                name="object-max-size",
                value_type="enum",
                in_sections=("nodes",),
                enum_values=("from-profile",),
            ),
            BigipPropertySpec(
                name="object-min-size",
                value_type="enum",
                in_sections=("nodes",),
                enum_values=("from-profile",),
            ),
            BigipPropertySpec(
                name="optimize-for-client",
                value_type="enum",
                in_sections=("nodes",),
                enum_values=("no", "yes"),
            ),
            BigipPropertySpec(
                name="optimize-image",
                value_type="enum",
                in_sections=("nodes",),
                allow_none=True,
                enum_values=("none", "to-gif", "to-jpeg", "to-png", "to-tiff"),
            ),
            BigipPropertySpec(name="options", value_type="list", in_sections=("nodes",)),
            BigipPropertySpec(name="order", value_type="integer", in_sections=("nodes",)),
            BigipPropertySpec(
                name="png-256-colors",
                value_type="enum",
                in_sections=("nodes",),
                enum_values=("no", "yes"),
            ),
            BigipPropertySpec(
                name="request-queueing",
                value_type="enum",
                in_sections=("nodes",),
                enum_values=("disable", "enable"),
            ),
            BigipPropertySpec(
                name="response-codes-cached",
                value_type="unknown",
                in_sections=("nodes",),
            ),
            BigipPropertySpec(
                name="value-case-sensitive",
                value_type="enum",
                in_sections=("nodes",),
                enum_values=("no", "yes"),
            ),
            BigipPropertySpec(
                name="values",
                value_type="list",
                in_sections=("nodes",),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="variation",
                value_type="list",
                in_sections=("nodes",),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="app-service",
                value_type="string",
                in_sections=("nodes", "variation"),
                allow_none=True,
            ),
            BigipPropertySpec(
                name="arg-alias",
                value_type="string",
                in_sections=("nodes", "variation"),
            ),
            BigipPropertySpec(
                name="arg-all",
                value_type="enum",
                in_sections=("nodes", "variation"),
                enum_values=("no", "yes"),
            ),
            BigipPropertySpec(
                name="arg-ambiguous-as-unnamed",
                value_type="enum",
                in_sections=("nodes", "variation"),
                enum_values=("no", "yes"),
            ),
            BigipPropertySpec(
                name="arg-direction",
                value_type="enum",
                in_sections=("nodes", "variation"),
                enum_values=("left-to-right", "right-to-left"),
            ),
            BigipPropertySpec(
                name="arg-name",
                value_type="string",
                in_sections=("nodes", "variation"),
            ),
            BigipPropertySpec(
                name="arg-ordinal",
                value_type="unknown",
                in_sections=("nodes", "variation"),
            ),
            BigipPropertySpec(
                name="description",
                value_type="string",
                in_sections=("nodes", "variation"),
            ),
            BigipPropertySpec(
                name="value-case-sensitive",
                value_type="enum",
                in_sections=("nodes", "variation"),
                enum_values=("no", "yes"),
            ),
            BigipPropertySpec(
                name="values",
                value_type="list",
                in_sections=("nodes", "variation"),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="app-service",
                value_type="string",
                in_sections=("nodes", "variation", "values"),
                allow_none=True,
            ),
            BigipPropertySpec(
                name="cache-as",
                value_type="enum",
                in_sections=("nodes", "variation", "values"),
                enum_values=("different", "same"),
            ),
            BigipPropertySpec(
                name="can-be-empty",
                value_type="enum",
                in_sections=("nodes", "variation", "values"),
                enum_values=("no", "yes"),
            ),
            BigipPropertySpec(
                name="can-be-missing",
                value_type="enum",
                in_sections=("nodes", "variation", "values"),
                enum_values=("no", "yes"),
            ),
            BigipPropertySpec(
                name="invert-match",
                value_type="enum",
                in_sections=("nodes", "variation", "values"),
                enum_values=("no", "yes"),
            ),
            BigipPropertySpec(
                name="match-all",
                value_type="enum",
                in_sections=("nodes", "variation", "values"),
                enum_values=("no", "yes"),
            ),
            BigipPropertySpec(
                name="video-acceleration-ad-policy",
                value_type="string",
                in_sections=("nodes",),
            ),
            BigipPropertySpec(
                name="video-optimization-ad-frequency",
                value_type="integer",
                in_sections=("nodes",),
            ),
            BigipPropertySpec(
                name="video-optimization-fast-start",
                value_type="enum",
                in_sections=("nodes",),
                enum_values=("disable", "enable"),
            ),
            BigipPropertySpec(
                name="video-optimization-insert-ad",
                value_type="enum",
                in_sections=("nodes",),
                enum_values=("disable", "enable"),
            ),
            BigipPropertySpec(
                name="video-optimization-max-bitrate",
                value_type="integer",
                in_sections=("nodes",),
            ),
            BigipPropertySpec(
                name="video-optimization-preroll-ad",
                value_type="enum",
                in_sections=("nodes",),
                enum_values=("disable", "enable"),
            ),
            BigipPropertySpec(
                name="viewstate-cache",
                value_type="enum",
                in_sections=("nodes",),
                enum_values=("no", "yes"),
            ),
            BigipPropertySpec(
                name="viewstate-cache-size",
                value_type="integer",
                in_sections=("nodes",),
            ),
            BigipPropertySpec(name="viewstate-tag", value_type="string", in_sections=("nodes",)),
            BigipPropertySpec(name="webp-quality", value_type="integer", in_sections=("nodes",)),
            BigipPropertySpec(name="publish-build", value_type="integer"),
            BigipPropertySpec(name="publish-comment", value_type="string"),
            BigipPropertySpec(name="published-on", value_type="unknown"),
            BigipPropertySpec(
                name="substitutions",
                value_type="list",
                allow_none=True,
                list_operators=frozenset(("add", "delete", "modify", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="app-service",
                value_type="string",
                in_sections=("substitutions",),
                allow_none=True,
            ),
            BigipPropertySpec(
                name="description",
                value_type="string",
                in_sections=("substitutions",),
            ),
            BigipPropertySpec(
                name="dst-alias",
                value_type="string",
                in_sections=("substitutions",),
            ),
            BigipPropertySpec(
                name="dst-direction",
                value_type="enum",
                in_sections=("substitutions",),
                enum_values=("left-to-right", "right-to-left"),
            ),
            BigipPropertySpec(name="dst-name", value_type="string", in_sections=("substitutions",)),
            BigipPropertySpec(
                name="dst-ordinal",
                value_type="unknown",
                in_sections=("substitutions",),
            ),
            BigipPropertySpec(
                name="dst-type",
                value_type="enum",
                in_sections=("substitutions",),
                enum_values=("path-segment", "query-param"),
            ),
            BigipPropertySpec(
                name="dst-urls",
                value_type="list",
                in_sections=("substitutions",),
                allow_none=True,
                list_operators=frozenset(("add", "delete", "replace-all-with")),
            ),
            BigipPropertySpec(
                name="src-alias",
                value_type="string",
                in_sections=("substitutions",),
            ),
            BigipPropertySpec(
                name="src-direction",
                value_type="enum",
                in_sections=("substitutions",),
                enum_values=("left-to-right", "right-to-left"),
            ),
            BigipPropertySpec(name="src-name", value_type="string", in_sections=("substitutions",)),
            BigipPropertySpec(
                name="src-ordinal",
                value_type="unknown",
                in_sections=("substitutions",),
            ),
            BigipPropertySpec(
                name="src-type",
                value_type="unknown",
                in_sections=("substitutions",),
            ),
            BigipPropertySpec(
                name="src-url",
                value_type="enum",
                in_sections=("substitutions",),
                enum_values=("absolute", "relative"),
            ),
        ),
    )
