ltm rule /Common/__tcl_lsp_evtflow_EFB_load_access_policy_agent_event {
    when ACCESS_POLICY_AGENT_EVENT priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=ACCESS_POLICY_AGENT_EVENT|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
