ltm rule /Common/__tcl_lsp_evtflow_EFB_load_access_policy_completed {
    when ACCESS_POLICY_COMPLETED priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=ACCESS_POLICY_COMPLETED|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
