ltm rule /Common/__tcl_lsp_evtflow_EFB_load_access2_policy_expression_eval {
    when ACCESS2_POLICY_EXPRESSION_EVAL priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=ACCESS2_POLICY_EXPRESSION_EVAL|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
