ltm rule /Common/__tcl_lsp_evtflow_EFB_load_access_saml_slo_req {
    when ACCESS_SAML_SLO_REQ priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=ACCESS_SAML_SLO_REQ|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
