ltm rule /Common/__tcl_lsp_evtflow_EFB_load_access_saml_authn {
    when ACCESS_SAML_AUTHN priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=ACCESS_SAML_AUTHN|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
