ltm rule /Common/__tcl_lsp_evtflow_EFB_load_adapt_request_headers {
    when ADAPT_REQUEST_HEADERS priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=ADAPT_REQUEST_HEADERS|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
