ltm rule /Common/__tcl_lsp_evtflow_EFB_load_adapt_request_result {
    when ADAPT_REQUEST_RESULT priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=ADAPT_REQUEST_RESULT|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
