ltm rule /Common/__tcl_lsp_evtflow_EFB_load_adapt_response_headers {
    when ADAPT_RESPONSE_HEADERS priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=ADAPT_RESPONSE_HEADERS|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
