ltm rule /Common/__tcl_lsp_evtflow_EFB_load_antifraud_login {
    when ANTIFRAUD_LOGIN priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=ANTIFRAUD_LOGIN|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
