ltm rule /Common/__tcl_lsp_evtflow_EFB_load_antifraud_alert {
    when ANTIFRAUD_ALERT priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=ANTIFRAUD_ALERT|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
