ltm rule /Common/__tcl_lsp_evtflow_EFB_load_asm_request_done {
    when ASM_REQUEST_DONE priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=ASM_REQUEST_DONE|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
