ltm rule /Common/__tcl_lsp_evtflow_EFB_load_asm_request_blocking {
    when ASM_REQUEST_BLOCKING priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=ASM_REQUEST_BLOCKING|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
