ltm rule /Common/__tcl_lsp_evtflow_EFB_load_auth_error {
    when AUTH_ERROR priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=AUTH_ERROR|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
