ltm rule /Common/__tcl_lsp_evtflow_EFB_load_avr_cspm_injection {
    when AVR_CSPM_INJECTION priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=AVR_CSPM_INJECTION|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
