ltm rule /Common/__tcl_lsp_evtflow_EFB_load_botdefense_action {
    when BOTDEFENSE_ACTION priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=BOTDEFENSE_ACTION|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
