ltm rule /Common/__tcl_lsp_evtflow_EFB_load_botdefense_request {
    when BOTDEFENSE_REQUEST priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=BOTDEFENSE_REQUEST|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
