ltm rule /Common/__tcl_lsp_evtflow_EFB_load_category_matched {
    when CATEGORY_MATCHED priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=CATEGORY_MATCHED|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
