ltm rule /Common/__tcl_lsp_evtflow_EFB_load_classification_detected {
    when CLASSIFICATION_DETECTED priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=CLASSIFICATION_DETECTED|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
