ltm rule /Common/__tcl_lsp_evtflow_EFB_load_clientssl_clienthello {
    when CLIENTSSL_CLIENTHELLO priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=CLIENTSSL_CLIENTHELLO|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
