ltm rule /Common/__tcl_lsp_evtflow_EFB_load_clientssl_passthrough {
    when CLIENTSSL_PASSTHROUGH priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=CLIENTSSL_PASSTHROUGH|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
