ltm rule /Common/__tcl_lsp_evtflow_EFB_load_clientssl_clientcert {
    when CLIENTSSL_CLIENTCERT priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=CLIENTSSL_CLIENTCERT|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
