ltm rule /Common/__tcl_lsp_evtflow_EFB_load_clientssl_serverhello_send {
    when CLIENTSSL_SERVERHELLO_SEND priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=CLIENTSSL_SERVERHELLO_SEND|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
