ltm rule /Common/__tcl_lsp_evtflow_EFB_load_client_data {
    when CLIENT_DATA priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=CLIENT_DATA|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
