ltm rule /Common/__tcl_lsp_evtflow_EFB_load_diameter_retransmission {
    when DIAMETER_RETRANSMISSION priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=DIAMETER_RETRANSMISSION|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
