ltm rule /Common/__tcl_lsp_evtflow_EFB_load_diameter_ingress {
    when DIAMETER_INGRESS priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=DIAMETER_INGRESS|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
