ltm rule /Common/__tcl_lsp_evtflow_EFB_load_diameter_egress {
    when DIAMETER_EGRESS priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=DIAMETER_EGRESS|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
