ltm rule /Common/__tcl_lsp_evtflow_EFB_load_dns_response {
    when DNS_RESPONSE priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=DNS_RESPONSE|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
