ltm rule /Common/__tcl_lsp_evtflow_EFB_load_dns_request {
    when DNS_REQUEST priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=DNS_REQUEST|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
