ltm rule /Common/__tcl_lsp_evtflow_EFB_load_epi_na_check_http_request {
    when EPI_NA_CHECK_HTTP_REQUEST priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=EPI_NA_CHECK_HTTP_REQUEST|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
