ltm rule /Common/__tcl_lsp_evtflow_EFB_load_flow_init {
    when FLOW_INIT priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=FLOW_INIT|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
