ltm rule /Common/__tcl_lsp_evtflow_EFB_load_genericmessage_egress {
    when GENERICMESSAGE_EGRESS priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=GENERICMESSAGE_EGRESS|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
