ltm rule /Common/__tcl_lsp_evtflow_EFB_load_gtp_gpdu_egress {
    when GTP_GPDU_EGRESS priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=GTP_GPDU_EGRESS|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
