ltm rule /Common/__tcl_lsp_evtflow_EFB_load_html_comment_matched {
    when HTML_COMMENT_MATCHED priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=HTML_COMMENT_MATCHED|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
