ltm rule /Common/__tcl_lsp_evtflow_EFB_load_http_class_selected {
    when HTTP_CLASS_SELECTED priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=HTTP_CLASS_SELECTED|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
