ltm rule /Common/__tcl_lsp_evtflow_EFB_load_http_proxy_connect {
    when HTTP_PROXY_CONNECT priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=HTTP_PROXY_CONNECT|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
