ltm rule /Common/__tcl_lsp_evtflow_EFB_load_http_reject {
    when HTTP_REJECT priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=HTTP_REJECT|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
