ltm rule /Common/__tcl_lsp_evtflow_EFB_load_http_request_data {
    when HTTP_REQUEST_DATA priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=HTTP_REQUEST_DATA|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
