ltm rule /Common/__tcl_lsp_evtflow_EFB_load_icap_request {
    when ICAP_REQUEST priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=ICAP_REQUEST|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
