ltm rule /Common/__tcl_lsp_evtflow_EFB_load_icap_response {
    when ICAP_RESPONSE priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=ICAP_RESPONSE|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
