ltm rule /Common/__tcl_lsp_evtflow_EFB_load_in_dosl7_attack {
    when IN_DOSL7_ATTACK priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=IN_DOSL7_ATTACK|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
