ltm rule /Common/__tcl_lsp_evtflow_EFB_load_ivs_entry_request {
    when IVS_ENTRY_REQUEST priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=IVS_ENTRY_REQUEST|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
