ltm rule /Common/__tcl_lsp_evtflow_EFB_load_ivs_entry_response {
    when IVS_ENTRY_RESPONSE priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=IVS_ENTRY_RESPONSE|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
