ltm rule /Common/__tcl_lsp_evtflow_EFB_load_json_response_missing {
    when JSON_RESPONSE_MISSING priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=JSON_RESPONSE_MISSING|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
