ltm rule /Common/__tcl_lsp_evtflow_EFB_load_json_request_missing {
    when JSON_REQUEST_MISSING priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=JSON_REQUEST_MISSING|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
