ltm rule /Common/__tcl_lsp_evtflow_EFB_load_lb_queued {
    when LB_QUEUED priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=LB_QUEUED|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
