ltm rule /Common/__tcl_lsp_evtflow_EFB_load_mqtt_client_egress {
    when MQTT_CLIENT_EGRESS priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=MQTT_CLIENT_EGRESS|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
