ltm rule /Common/__tcl_lsp_evtflow_EFB_load_mr_data {
    when MR_DATA priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=MR_DATA|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
