ltm rule /Common/__tcl_lsp_evtflow_EFB_load_pcp_request {
    when PCP_REQUEST priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=PCP_REQUEST|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
