ltm rule /Common/__tcl_lsp_evtflow_EFB_load_pem_subs_sess_deleted {
    when PEM_SUBS_SESS_DELETED priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=PEM_SUBS_SESS_DELETED|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
