ltm rule /Common/__tcl_lsp_evtflow_EFB_load_persist_down {
    when PERSIST_DOWN priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=PERSIST_DOWN|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
