ltm rule /Common/__tcl_lsp_evtflow_EFB_load_ping_request_ready {
    when PING_REQUEST_READY priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=PING_REQUEST_READY|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
