ltm rule /Common/__tcl_lsp_evtflow_EFB_load_protocol_inspection_match {
    when PROTOCOL_INSPECTION_MATCH priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=PROTOCOL_INSPECTION_MATCH|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
