ltm rule /Common/__tcl_lsp_evtflow_EFB_load_qoe_parse_done {
    when QOE_PARSE_DONE priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=QOE_PARSE_DONE|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
