ltm rule /Common/__tcl_lsp_evtflow_EFB_load_radius_aaa_auth_response {
    when RADIUS_AAA_AUTH_RESPONSE priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=RADIUS_AAA_AUTH_RESPONSE|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
