ltm rule /Common/__tcl_lsp_evtflow_EFB_load_rewrite_request {
    when REWRITE_REQUEST priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=REWRITE_REQUEST|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
