ltm rule /Common/__tcl_lsp_evtflow_EFB_load_rewrite_request_done {
    when REWRITE_REQUEST_DONE priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=REWRITE_REQUEST_DONE|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
