ltm rule /Common/__tcl_lsp_evtflow_EFB_load_rtsp_response {
    when RTSP_RESPONSE priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=RTSP_RESPONSE|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
