ltm rule /Common/__tcl_lsp_evtflow_EFB_load_rule_init {
    when RULE_INIT priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=RULE_INIT|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
