ltm rule /Common/__tcl_lsp_evtflow_EFB_load_sa_picked {
    when SA_PICKED priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=SA_PICKED|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
