ltm rule /Common/__tcl_lsp_evtflow_EFB_load_server_connected {
    when SERVER_CONNECTED priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=SERVER_CONNECTED|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
