ltm rule /Common/__tcl_lsp_evtflow_EFB_load_server_init {
    when SERVER_INIT priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=SERVER_INIT|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
