ltm rule /Common/__tcl_lsp_evtflow_EFB_load_sip_request {
    when SIP_REQUEST priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=SIP_REQUEST|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
