ltm rule /Common/__tcl_lsp_evtflow_EFB_load_sip_response_send {
    when SIP_RESPONSE_SEND priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=SIP_RESPONSE_SEND|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
