ltm rule /Common/__tcl_lsp_evtflow_EFB_load_socks_request {
    when SOCKS_REQUEST priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=SOCKS_REQUEST|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
