ltm rule /Common/__tcl_lsp_evtflow_EFB_load_stream_matched {
    when STREAM_MATCHED priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=STREAM_MATCHED|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
