ltm rule /Common/__tcl_lsp_evtflow_EFB_load_tap_request {
    when TAP_REQUEST priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=TAP_REQUEST|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
