ltm rule /Common/__tcl_lsp_evtflow_EFB_load_tds_response {
    when TDS_RESPONSE priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=TDS_RESPONSE|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
