ltm rule /Common/__tcl_lsp_evtflow_EFB_load_ws_client_frame_done {
    when WS_CLIENT_FRAME_DONE priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=WS_CLIENT_FRAME_DONE|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
