ltm rule /Common/__tcl_lsp_evtflow_EFB_load_ws_server_data {
    when WS_SERVER_DATA priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=WS_SERVER_DATA|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
