ltm rule /Common/__tcl_lsp_evtflow_EFB_load_xml_content_based_routing {
    when XML_CONTENT_BASED_ROUTING priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=XML_CONTENT_BASED_ROUTING|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
