ltm rule /Common/__tcl_lsp_evtflow_EFB_load_xml_end_document {
    when XML_END_DOCUMENT priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=XML_END_DOCUMENT|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
