ltm rule /Common/__tcl_lsp_evtflow_EFB_load_xml_begin_document {
    when XML_BEGIN_DOCUMENT priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=XML_BEGIN_DOCUMENT|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
