ltm rule /Common/__tcl_lsp_evtflow_EFB_load_xml_begin_element {
    when XML_BEGIN_ELEMENT priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=XML_BEGIN_ELEMENT|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
