ltm rule /Common/__tcl_lsp_evtflow_EFB_load_xml_cdata {
    when XML_CDATA priority 500 {
        log local0. "EVTFLOW|run=EFB|probe=event_load|event=XML_CDATA|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
