//! Differential test: the `f5-xc` translator must match the captured
//! golden fixture on a representative iRule corpus.
//!
//! The fixture (`tests/differential_fixture.json`) is regenerated by the
//! fixture generator; this test re-runs the `f5-xc` translator over the
//! same sources and asserts the summary (per-item codes, status counts,
//! coverage, construct counts, origin-pool names, and the lifted diagnostic
//! codes + messages) matches byte-for-byte.

use std::collections::BTreeMap;

use f5_xc::model::TranslateStatus;
use f5_xc::{get_xc_diagnostics, translate_irule};
use serde_json::Value;

/// Build the same summary shape the captured golden fixture uses for one source.
fn summarise(source: &str) -> Value {
    let result = translate_irule(source);

    let mut item_codes: Vec<String> = result
        .items
        .iter()
        .filter(|i| !i.diagnostic_code.is_empty())
        .map(|i| i.diagnostic_code.clone())
        .collect();
    item_codes.sort();

    let count = |s: TranslateStatus| result.items.iter().filter(|i| i.status == s).count();

    let mut origin_pool_names: Vec<String> =
        result.origin_pools.iter().map(|p| p.name.clone()).collect();
    origin_pool_names.sort();

    let diags = get_xc_diagnostics(source);
    let mut diag_codes: Vec<String> = diags.iter().map(|d| d.code.clone()).collect();
    diag_codes.sort();
    let mut diag_messages: Vec<String> = diags.iter().map(|d| d.message.clone()).collect();
    diag_messages.sort();

    let service_policy_rules: usize = result.service_policies.iter().map(|p| p.rules.len()).sum();

    serde_json::json!({
        "item_codes": item_codes,
        "statuses": {
            "translated": count(TranslateStatus::Translated),
            "partial": count(TranslateStatus::Partial),
            "untranslatable": count(TranslateStatus::Untranslatable),
            "advisory": count(TranslateStatus::Advisory),
        },
        "coverage_pct": result.coverage_pct,
        "counts": {
            "routes": result.routes.len(),
            "origin_pools": result.origin_pools.len(),
            "service_policies": result.service_policies.len(),
            "service_policy_rules": service_policy_rules,
            "header_actions": result.header_actions.len(),
            "waf_exclusion_rules": result.waf_exclusion_rules.len(),
        },
        "origin_pool_names": origin_pool_names,
        "diag_codes": diag_codes,
        "diag_messages": diag_messages,
    })
}

#[test]
fn rust_translator_matches_golden_fixture() {
    let fixture_src = include_str!("differential_fixture.json");
    let cases: Vec<Value> = serde_json::from_str(fixture_src).expect("valid fixture JSON");

    let mut failures: Vec<String> = Vec::new();
    for case in &cases {
        let name = case["name"].as_str().unwrap();
        let source = case["source"].as_str().unwrap();
        let expected = &case["expected"];
        let actual = summarise(source);

        if &actual != expected {
            // Pinpoint the differing keys for a readable failure.
            let mut diffs: BTreeMap<String, (Value, Value)> = BTreeMap::new();
            for key in expected.as_object().unwrap().keys() {
                if expected[key] != actual[key] {
                    diffs.insert(key.clone(), (expected[key].clone(), actual[key].clone()));
                }
            }
            failures.push(format!(
                "case `{name}` diverged:\n  source: {source:?}\n  diffs (expected vs actual): {diffs:#?}"
            ));
        }
    }

    assert!(
        failures.is_empty(),
        "{} of {} parity cases diverged:\n\n{}",
        failures.len(),
        cases.len(),
        failures.join("\n\n")
    );
}
