ltm profile tcp /EVTFLOW_EFB/__tcl_lsp_evtflow_EFB_mptcp_profile {
    defaults-from /Common/tcp
    mptcp enabled
}
ltm pool /EVTFLOW_EFB/__tcl_lsp_evtflow_EFB_mptcp_pool {
    members {
        /EVTFLOW_EFB/__tcl_lsp_evtflow_EFB_node:18600 { address 192.168.9.80 }
    }
}
ltm virtual /EVTFLOW_EFB/__tcl_lsp_evtflow_EFB_mptcp_vs {
    destination 192.168.9.24:18508
    ip-protocol tcp
    mask 255.255.255.255
    pool /EVTFLOW_EFB/__tcl_lsp_evtflow_EFB_mptcp_pool
    profiles {
        /EVTFLOW_EFB/__tcl_lsp_evtflow_EFB_mptcp_profile { }
    }
    rules { /Common/__tcl_lsp_evtflow_EFB_tcp_trace }
    source 0.0.0.0/0
    source-address-translation { type automap }
}
