ltm pool /EVTFLOW_EFB/__tcl_lsp_evtflow_EFB_sip_pool {
    members {
        /EVTFLOW_EFB/__tcl_lsp_evtflow_EFB_node:18604 { address 192.168.9.80 }
    }
}
ltm virtual /EVTFLOW_EFB/__tcl_lsp_evtflow_EFB_sip_vs {
    destination 192.168.9.24:18509
    ip-protocol udp
    mask 255.255.255.255
    pool /EVTFLOW_EFB/__tcl_lsp_evtflow_EFB_sip_pool
    profiles {
        /Common/sip { }
        /Common/udp { }
    }
    rules { /Common/__tcl_lsp_evtflow_EFB_udp_trace /Common/__tcl_lsp_evtflow_EFB_sip_trace }
    source 0.0.0.0/0
    source-address-translation { type automap }
}
