ltm pool /EVTFLOW_EFB/__tcl_lsp_evtflow_EFB_mqtt_pool {
    members {
        /EVTFLOW_EFB/__tcl_lsp_evtflow_EFB_node:18600 { address 192.168.9.80 }
    }
}
ltm virtual /EVTFLOW_EFB/__tcl_lsp_evtflow_EFB_mqtt_vs {
    destination 192.168.9.24:18511
    ip-protocol tcp
    mask 255.255.255.255
    pool /EVTFLOW_EFB/__tcl_lsp_evtflow_EFB_mqtt_pool
    profiles {
        /Common/mqtt { }
        /Common/tcp { }
    }
    rules { /Common/__tcl_lsp_evtflow_EFB_tcp_trace /Common/__tcl_lsp_evtflow_EFB_mqtt_trace }
    source 0.0.0.0/0
    source-address-translation { type automap }
}
