apm policy policy-item /Common/employee_login_ent {
    caption Start
    agents { }
}
apm policy policy-item /Common/employee_login_logon_page {
    caption "Logon Page"
    agents {
        /Common/employee_login_logon_page_ag {
            type logon-page
        }
    }
}
apm policy policy-item /Common/employee_login_localdb_auth {
    caption "LocalDB Auth"
    agents {
        /Common/employee_login_localdb_auth_ag {
            type aaa-localdb
        }
    }
}
apm policy policy-item /Common/employee_login_end_allow {
    caption Allow
    agents { }
}
apm policy policy-item /Common/employee_login_end_deny {
    caption Deny
    agents { }
}
apm policy access-policy /Common/employee_login {
    default-ending /Common/employee_login_end_deny
    items {
        /Common/employee_login_ent { }
        /Common/employee_login_logon_page { }
        /Common/employee_login_localdb_auth { }
        /Common/employee_login_end_allow { }
        /Common/employee_login_end_deny { }
    }
    start-item /Common/employee_login_ent
}
apm profile access /Common/employee_login_profile {
    access-policy /Common/employee_login
}
