gtm datacenter /Common/dc-east { }
gtm datacenter /Common/dc-west { }
gtm server /Common/bigip-east {
    datacenter /Common/dc-east
    addresses {
        10.0.0.1 { }
    }
    virtual-servers {
        /Common/web_vs {
            destination 10.0.0.10:80
        }
        /Common/web_secure_vs {
            destination 10.0.0.10:443
        }
        /Common/api_vs {
            destination 10.0.0.20:443
        }
    }
}
gtm server /Common/bigip-west {
    datacenter /Common/dc-west
    addresses {
        10.1.0.1 { }
    }
    virtual-servers {
        /Common/web_vs {
            destination 10.1.0.10:80
        }
    }
}
gtm pool a /Common/example_app_pool {
    members {
        /Common/bigip-east:/Common/web_vs {
            order 0
        }
        /Common/bigip-west:/Common/web_vs {
            order 1
        }
    }
    monitor /Common/gateway_icmp
}
gtm pool a /Common/api_app_pool {
    members {
        /Common/bigip-east:/Common/api_vs {
            order 0
        }
    }
    monitor /Common/gateway_icmp
}
gtm wideip a /Common/www.example.com {
    pools {
        /Common/example_app_pool { }
    }
}
gtm wideip a /Common/api.example.com {
    pools {
        /Common/api_app_pool { }
    }
}
