include /workspace/tcl-lsp/tmp/tcl9.1.0/unix/Makefile
BUILD_DIR := /workspace/tcl-lsp/tmp/tcl9.1.0/unix
.PHONY: observed-dictionary observed-object
observed-dictionary:
	$(CC) -c $(CC_SWITCHES) /tmp/native-dictionary-with-lifetime405/9.1.0/observed-tclDictObj.c -o /tmp/native-dictionary-with-lifetime405-capture/9.1.0/tclDictObj.o
observed-object:
	$(CC) -c $(CC_SWITCHES) /tmp/native-dictionary-with-lifetime405/9.1.0/observed-tclObj.c -o /tmp/native-dictionary-with-lifetime405-capture/9.1.0/tclObj.o
