ltm rule /Common/__tcl_lsp_2286_vl1_identity {
    when HTTP_REQUEST {
        if {[HTTP::path] eq "/r2286-vl1-identity"} {
            HTTP::respond 200 content [list vl1 [TMM::cmp_group] [TMM::cmp_unit] [IP::client_addr] [TCP::client_port]] "Content-Type" "text/plain" "Connection" "close"
        }
    }
}
