ltm node /Common/__tcl_lsp_2286_r2286lex1_node {
    address 192.168.9.80
}
ltm pool /Common/__tcl_lsp_2286_r2286lex1_pool {
    members { /Common/__tcl_lsp_2286_r2286lex1_node:18760 { address 192.168.9.80 } }
}
ltm virtual /Common/__tcl_lsp_2286_r2286lex1_vs {
    destination 192.168.9.24:18860
    mask 255.255.255.255
    ip-protocol tcp
    source 0.0.0.0/0
    profiles { /Common/tcp { } /Common/http { } }
    pool /Common/__tcl_lsp_2286_r2286lex1_pool
    rules { /Common/__tcl_lsp_2286_r2286lex1_identity }
    source-address-translation { type automap }
    cmp-enabled yes
}
