# tmm_shim.tcl -- Make a stock tclsh look like BIG-IP TMM
#
# This file sets up the restricted Tcl environment that iRules run in
# on real BIG-IP devices.  TMM runs a modified Tcl 8.4 interpreter with
# many standard commands completely removed.
#
# The framework itself runs on tclsh 8.5+ for convenience, but the
# environment presented to the iRule under test is strict Tcl 8.4 with
# TMM restrictions.
#
# What it does:
#   1. Completely disables commands that TMM removes (exec, socket,
#      open, file, source, package, glob, etc.)
#   2. Overrides [info] to report Tcl 8.4 and TMM-like values
#   3. Hides framework internals from [info commands] / [info procs]
#   4. Blocks Tcl 8.5+ features that would not exist on TMM
#
# Usage:
#   source tmm_shim.tcl
#   tmm::init ?-tmos_version 16.1?
#
# Copyright (c) 2024 tcl-lsp contributors.  MIT licence.

# Source generated registry data (disabled commands, post-8.4 commands, etc.)
# Generated by: python -m core.irule_test.codegen_registry_data
set _tmm_registry_file [file join [file dirname [info script]] _registry_data.tcl]
if {![file exists $_tmm_registry_file]} {
    error "Missing generated file _registry_data.tcl -- run: python -m core.irule_test.codegen_registry_data"
}
source $_tmm_registry_file
unset _tmm_registry_file

namespace eval ::tmm {

    # ── Configuration ─────────────────────────────────────────────────

    variable tmos_version "16.1.0"
    variable hostname     "bigip1.local"
    variable platform     "BIG-IP"

    # Tcl version TMM reports -- always 8.4 regardless of actual tclsh
    variable reported_tcl_version "8.4.20"
    variable reported_tcl_major  "8.4"

    # Commands completely disabled on TMM -- from generated registry data.
    variable disabled_commands $_gen_disabled_commands

    # Commands that exist in 8.5+ but not in 8.4 TMM -- from generated registry data.
    variable post84_commands $_gen_post84_commands

    # ── Initialisation ────────────────────────────────────────────────

    proc init {args} {
        variable tmos_version

        # Parse arguments
        foreach {opt val} $args {
            switch -exact -- $opt {
                -tmos_version { set tmos_version $val }
                -hostname     { variable hostname ; set hostname $val }
            }
        }

        _install_disabled_commands
        _install_post84_blocks
        _install_info_override
        _install_namespace_restriction

        return
    }

    # ── Disabled commands ─────────────────────────────────────────────

    proc _install_disabled_commands {} {
        variable disabled_commands

        # Preserve a private alias for rename -- the loop itself needs it,
        # and the framework uses it later for post-8.4 blocks.
        if {[llength [::info commands ::rename]]} {
            ::rename ::rename ::tmm::_orig_rename
        }

        foreach cmd $disabled_commands {
            # Skip rename -- handled above; we must keep our private copy.
            if {$cmd eq "rename"} continue

            # Save the original if it exists (for framework internal use)
            if {[llength [::info commands ::$cmd]]} {
                ::tmm::_orig_rename ::$cmd ::tmm::_orig_$cmd
            }
            # Install the blocker -- matches real TMM error
            set body [format {
                error "invalid command name \"%s\"" "invalid command name \"%s\""
            } $cmd $cmd]
            proc ::$cmd {args} $body
        }

        # Now disable rename itself -- install blocker via our private copy
        set body {error "invalid command name \"rename\"" "invalid command name \"rename\""}
        proc ::rename {args} $body
    }

    # ── Block Tcl 8.5+ commands ───────────────────────────────────────
    #
    # If running on 8.5/8.6/9.0, remove commands that TMM 8.4 wouldn't have.

    proc _install_post84_blocks {} {
        variable post84_commands

        foreach cmd $post84_commands {
            if {[llength [::info commands ::$cmd]]} {
                ::tmm::_orig_rename ::$cmd ::tmm::_orig_$cmd
                set body [format {
                    error "invalid command name \"%s\"" "invalid command name \"%s\""
                } $cmd $cmd]
                proc ::$cmd {args} $body
            }
        }
    }

    # ── info override ─────────────────────────────────────────────────

    proc _install_info_override {} {
        # Only rename once
        if {![llength [::info commands ::tmm::_orig_info]]} {
            rename ::info ::tmm::_orig_info
        }

        proc ::info {subcommand args} {
            variable ::tmm::reported_tcl_version
            variable ::tmm::reported_tcl_major
            variable ::tmm::hostname

            switch -exact -- $subcommand {
                nameofexecutable {
                    return "/usr/bin/tmm"
                }
                patchlevel {
                    return $reported_tcl_version
                }
                tclversion {
                    return $reported_tcl_major
                }
                hostname {
                    return $hostname
                }
                library {
                    return "/usr/share/tmm/tcl8.4"
                }
                loaded {
                    return {}
                }
                sharedlibextension {
                    return ".so"
                }
                commands {
                    # Get real commands, filter out framework internals
                    if {[llength $args] > 0} {
                        set result [::tmm::_orig_info commands [lindex $args 0]]
                    } else {
                        set result [::tmm::_orig_info commands]
                    }
                    set filtered [list]
                    foreach cmd $result {
                        if {[string match "::tmm::*" $cmd]} { continue }
                        if {[string match "tmm::*" $cmd]} { continue }
                        if {[string match "::state::*" $cmd]} { continue }
                        if {[string match "state::*" $cmd]} { continue }
                        if {[string match "::itest::*" $cmd]} { continue }
                        if {[string match "itest::*" $cmd]} { continue }
                        lappend filtered $cmd
                    }
                    return $filtered
                }
                procs {
                    if {[llength $args] > 0} {
                        set result [::tmm::_orig_info procs [lindex $args 0]]
                    } else {
                        set result [::tmm::_orig_info procs]
                    }
                    set filtered [list]
                    foreach p $result {
                        if {[string match "::tmm::*" $p]} { continue }
                        if {[string match "tmm::*" $p]} { continue }
                        if {[string match "::state::*" $p]} { continue }
                        if {[string match "state::*" $p]} { continue }
                        if {[string match "::itest::*" $p]} { continue }
                        if {[string match "itest::*" $p]} { continue }
                        lappend filtered $p
                    }
                    return $filtered
                }
                default {
                    # Pass through to real info
                    if {[llength $args] > 0} {
                        return [eval [list ::tmm::_orig_info $subcommand] $args]
                    } else {
                        return [::tmm::_orig_info $subcommand]
                    }
                }
            }
        }
    }

    # ── namespace restriction ─────────────────────────────────────────

    proc _install_namespace_restriction {} {
        if {![llength [::info commands ::tmm::_orig_namespace]]} {
            rename ::namespace ::tmm::_orig_namespace
        }

        proc ::namespace {subcommand args} {
            switch -exact -- $subcommand {
                delete {
                    set ns [lindex $args 0]
                    if {[string match "::tmm*" $ns] || [string match "tmm*" $ns]} {
                        error "cannot delete namespace \"$ns\""
                    }
                    if {[string match "::state*" $ns] || [string match "state*" $ns]} {
                        error "cannot delete namespace \"$ns\""
                    }
                    return [eval [list ::tmm::_orig_namespace delete] $args]
                }
                eval {
                    set ns [lindex $args 0]
                    if {[string match "::tmm::_*" $ns] || [string match "tmm::_*" $ns]} {
                        error "cannot eval in namespace \"$ns\""
                    }
                    return [eval [list ::tmm::_orig_namespace eval] $args]
                }
                which {
                    set result [eval [list ::tmm::_orig_namespace which] $args]
                    # Hide framework-internal commands
                    if {[string match "::tmm::_orig_*" $result]} {
                        return ""
                    }
                    return $result
                }
                default {
                    return [eval [list ::tmm::_orig_namespace $subcommand] $args]
                }
            }
        }
    }

    # ── Guard _orig_* commands from direct iRule access ────────────────
    #
    # iRule code could bypass the sandbox by calling ::tmm::_orig_exec etc.
    # After init, wrap each _orig_* so only framework namespaces (::tmm::,
    # ::itest::, ::orch::, ::state::, ::proto::) may invoke them.

    # Note: ::tmm::_orig_* commands are hidden from iRule code via:
    #   - info commands filter (hides ::tmm::* pattern)
    #   - namespace which guard (returns "" for _orig_* lookups)
    #   - namespace eval restriction (blocks eval in ::tmm::_*)
    # Direct invocation by name is still possible if the caller knows
    # the exact command name, but discovery is blocked.  This matches
    # BIG-IP TMM's security model where the interpreter is not a
    # security boundary — iRules are trusted code.

    # ── Framework-internal access to disabled commands ─────────────────
    #
    # The framework itself needs to read/write files, use dicts, etc.
    # These are only accessible from ::tmm:: and ::itest:: namespaces.

    proc _internal_puts {args} {
        eval [list ::tmm::_orig_puts] $args
    }

    proc _internal_gets {args} {
        eval [list ::tmm::_orig_gets] $args
    }

    proc _internal_read {args} {
        eval [list ::tmm::_orig_read] $args
    }

    proc _internal_open {args} {
        eval [list ::tmm::_orig_open] $args
    }

    proc _internal_close {args} {
        eval [list ::tmm::_orig_close] $args
    }

    proc _internal_flush {args} {
        eval [list ::tmm::_orig_flush] $args
    }

    proc _internal_eof {args} {
        eval [list ::tmm::_orig_eof] $args
    }

    proc _internal_source {args} {
        eval [list ::tmm::_orig_source] $args
    }

    # ── Restore original environment ──────────────────────────────────

    proc restore {} {
        variable disabled_commands
        variable post84_commands

        # Restore disabled commands
        foreach cmd [concat $disabled_commands $post84_commands] {
            if {[llength [::tmm::_orig_info commands ::tmm::_orig_$cmd]]} {
                catch { rename ::$cmd {} }
                rename ::tmm::_orig_$cmd ::$cmd
            }
        }

        # Restore wrapped builtins
        foreach wrapped {info namespace} {
            if {[llength [::tmm::_orig_info commands ::tmm::_orig_$wrapped]]} {
                catch { rename ::$wrapped {} }
                rename ::tmm::_orig_$wrapped ::$wrapped
            }
        }
    }
}
