"""BIG-IP object registry catalogue."""

from .data import (
    HEADER_KIND_MAP,
    KIND_SPECS,
    OBJECT_KIND_SPECS,
    PROPERTY_NAMES_BY_TYPE,
    PROPERTY_REFERENCE_SPECS,
    PROPERTY_SPECS_BY_TYPE,
    list_operator_for,
    property_names_for,
    property_spec_for,
)
from .models import (
    BigipObjectKindSpec,
    BigipObjectSpec,
    BigipPropertySpec,
)
from .properties import (
    ObjectKeySpec,
    ObjectSpec,
    PropertySpec,
)
from .references import (
    iter_object_references,
    references_via_spec,
)
from .value_specs import (
    AddressSpec,
    BoolSpec,
    DestinationSpec,
    Diagnostic,
    EnumSpec,
    IntSpec,
    ListSpec,
    MonitorExpressionSpec,
    NetworkSpec,
    ObjectRefSpec,
    ParseContext,
    ParsedValue,
    PersistenceAttachmentSpec,
    PortSpec,
    ProfileAttachmentSpec,
    ProjectionContext,
    Reference,
    ReferenceContext,
    RenderContext,
    SnatModeSpec,
    SourceRange,
    StringSpec,
    ValueSpec,
)

__all__ = [
    # Phase-1 new shape
    "ObjectSpec",
    "ObjectKeySpec",
    "PropertySpec",
    "ValueSpec",
    "ParsedValue",
    "ParseContext",
    "ProjectionContext",
    "RenderContext",
    "ReferenceContext",
    "Reference",
    "SourceRange",
    "Diagnostic",
    "StringSpec",
    "IntSpec",
    "BoolSpec",
    "EnumSpec",
    "ObjectRefSpec",
    "ListSpec",
    "DestinationSpec",
    "MonitorExpressionSpec",
    "NetworkSpec",
    "AddressSpec",
    "PersistenceAttachmentSpec",
    "PortSpec",
    "ProfileAttachmentSpec",
    "SnatModeSpec",
    # Phase 5 reference dispatch
    "iter_object_references",
    "references_via_spec",
    # Legacy shape (still in use across every spec file under specs/)
    "BigipObjectSpec",
    "BigipObjectKindSpec",
    "BigipPropertySpec",
    "KIND_SPECS",
    "OBJECT_KIND_SPECS",
    "PROPERTY_REFERENCE_SPECS",
    "PROPERTY_NAMES_BY_TYPE",
    "PROPERTY_SPECS_BY_TYPE",
    "HEADER_KIND_MAP",
    "list_operator_for",
    "property_names_for",
    "property_spec_for",
]
