ltm rule probe_ver_irule {
when RULE_INIT {
  log local0. "TCLVER-IRULE patchlevel=[info patchlevel] version=[info tclversion] nameofexecutable=[info nameofexecutable] hasthreads=[info exists tcl_platform(threaded)]"
  log local0. "TCLVER-IRULE platform=[array get tcl_platform]"
}
}
