sys application template probe_ver_iapp {
  actions {
    definition {
      implementation {
        set msg "TCLVER-IAPP patchlevel=[info patchlevel] version=[info tclversion] plat=[array get tcl_platform] exe=[info nameofexecutable] cmds=[llength [info commands]]"
        tmsh::log err $msg
      }
      presentation {
      }
    }
  }
}
