import * as vscode from "vscode";
import { CommandContext } from "../types";
import { extractCodeBlock } from "../codeUtils";
import { sendContextualRequest } from "../contextPack";
import { runAgenticLoop } from "../agenticLoop";
import { renderDiagnosticSection } from "../diagnosticAccess";

// Generated by scripts/generate_catalogs.py — run `make generate` to update.
import generatedEvents from "../../generated/iruleEvents.json";

interface GeneratedEvent {
  name: string;
  description?: string;
  common?: boolean;
}

// Derive the common events list from the generated catalog.
const COMMON_EVENTS: readonly GeneratedEvent[] = (
  generatedEvents.events as GeneratedEvent[]
).filter((e) => e.common);

function parseEvents(prompt: string): string[] {
  const words = prompt.toUpperCase().split(/[\s,]+/);
  const known = new Set(COMMON_EVENTS.map((e) => e.name));
  return words.filter((w) => known.has(w));
}

export async function handleScaffold(ctx: CommandContext): Promise<vscode.ChatResult> {
  const events = parseEvents(ctx.request.prompt);

  if (events.length === 0) {
    // Show event reference
    ctx.response.markdown(
      "Specify events to include in the skeleton. For example:\n\n" +
        "> `@irule /scaffold HTTP_REQUEST HTTP_RESPONSE RULE_INIT`\n\n" +
        "### Common Events\n\n",
    );
    for (const ev of COMMON_EVENTS) {
      ctx.response.markdown(`- **${ev.name}** — ${ev.description}\n`);
    }
    return {};
  }

  ctx.response.progress(`Generating skeleton for ${events.join(", ")}...`);

  const llmResponse = await sendContextualRequest(
    ctx,
    `Generate an F5 BIG-IP iRule skeleton with these event handlers: ${events.join(", ")}.\n\n` +
      `Requirements:\n` +
      `- If any HTTP event is present, include a CLIENT_ACCEPTED block with set debug 0 for log gating\n` +
      `- In HTTP events, gate log calls with if {$debug} — never use static:: variables for this\n` +
      `- In HTTP events, extract commonly-used values (HTTP::uri, HTTP::host, HTTP::method) into local variables at the top\n` +
      `- Include commented placeholder sections (e.g. # --- Request routing ---) in each event\n` +
      `- Use K&R brace style: when EVENT {\n` +
      `- 4-space indentation\n` +
      `- Add brief comments explaining when each event fires\n\n` +
      `Return ONLY the complete iRule skeleton in a single \`\`\`tcl code block.`,
    { allowAmbientContext: false },
  );
  let responseText = "";
  for await (const chunk of llmResponse.text) {
    responseText += chunk;
  }

  const initialCode = extractCodeBlock(responseText);
  if (!initialCode) {
    ctx.response.markdown(
      "Failed to generate skeleton. Here is the raw response:\n\n" + responseText,
    );
    return {};
  }

  // Run agentic loop to validate the skeleton
  const result = await runAgenticLoop(ctx, initialCode, undefined, { targetDialect: "f5-irules" });

  ctx.response.markdown(`## iRule Skeleton\n\n\`\`\`tcl\n${result.finalCode}\n\`\`\`\n`);

  if (result.clean) {
    ctx.response.markdown(
      `\nSkeleton with ${events.length} event(s) validated clean in ${result.iterations} iteration(s).`,
    );
  } else {
    ctx.response.markdown(
      `\nAfter ${result.iterations} iteration(s), ${result.remainingDiagnostics.length} issue(s) remain:\n`,
    );
    renderDiagnosticSection(
      ctx.response,
      "Remaining Issues",
      result.remainingDiagnostics,
      result.finalCode,
    );
  }

  ctx.response.button({
    command: "tclLsp.insertIrule",
    title: "Insert into new file",
    arguments: [result.finalCode],
  });

  return { metadata: { command: "scaffold", events, clean: result.clean } };
}
