// tcl-lsp — a language server and toolchain for Tcl
// Copyright (C) 2026 James Deucker (bitwisecook) <https://github.com/bitwisecook>
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
// SPDX-License-Identifier: AGPL-3.0-or-later

//! `tcl explore --serve` — serve the compiler-explorer GUI from the binary.
//!
//! The GUI is a static web app (a shell of `index.html` / `explorer-core.js` /
//! `worker.js` plus the Rust → WASM compiler core) embedded into the binary at
//! build time (see `build.rs`). This is a minimal, dependency-free HTTP/1.1
//! server: it serves the embedded bundle from memory over `127.0.0.1`, with no
//! filesystem access and no external network requests at runtime. Everything
//! the browser needs (WASM, JS, Mermaid) is local.

use std::io::{BufRead, BufReader, Write};
use std::net::{TcpListener, TcpStream};

/// The embedded GUI bundle and completeness flags generated by `build.rs`.
mod assets {
    // tcl-lsp-no-smoke-include
    include!(concat!(env!("OUT_DIR"), "/gui_assets.rs"));
}

/// Look up an embedded asset by its bundle-relative name.
fn asset(name: &str) -> Option<&'static [u8]> {
    assets::GUI_ASSETS
        .iter()
        .find(|(n, _)| *n == name)
        .map(|(_, b)| *b)
}

/// Guess a `Content-Type` from a filename extension — the handful of types
/// the bundle actually serves.
fn content_type(path: &str) -> &'static str {
    match path.rsplit('.').next() {
        Some("html") => "text/html; charset=utf-8",
        Some("js" | "mjs") => "text/javascript; charset=utf-8",
        Some("wasm") => "application/wasm",
        Some("json") => "application/json",
        Some("svg") => "image/svg+xml",
        Some("png") => "image/png",
        Some("css") => "text/css; charset=utf-8",
        _ => "application/octet-stream",
    }
}

/// Handle `tcl explore --serve`.
///
/// # Errors
/// Fails if the address cannot be bound.
pub fn run_serve(bind: &str, port: u16, open: bool) -> anyhow::Result<u8> {
    if !assets::GUI_HAS_WASM || !assets::GUI_HAS_EDITOR {
        anyhow::bail!(
            "the complete compiler-explorer Web UI is not embedded in this build.\n\
             Assemble its compiler, Monaco, and language-server assets first, then rebuild `tcl`:\n\
             \n    make explorer-build && cargo build -p tcl-cli --release\n"
        );
    }

    let listener = TcpListener::bind((bind, port))
        .map_err(|e| anyhow::anyhow!("cannot bind {bind}:{port}: {e}"))?;
    let local = listener.local_addr()?;
    let url = format!("http://{bind}:{}", local.port());
    println!("Compiler explorer serving at {url} (Ctrl-C to stop)");

    if open {
        open_browser(&url);
    }

    for stream in listener.incoming() {
        match stream {
            Ok(stream) => {
                if let Err(e) = serve_one(stream) {
                    eprintln!("[explorer] connection error: {e}");
                }
            }
            Err(e) => eprintln!("[explorer] accept error: {e}"),
        }
    }
    Ok(0)
}

/// Serve a single HTTP/1.1 request: parse the request line, resolve the path to
/// an embedded asset (defaulting `/` → `index.html`), and write the response.
fn serve_one(mut stream: TcpStream) -> std::io::Result<()> {
    let mut reader = BufReader::new(stream.try_clone()?);
    let mut request_line = String::new();
    if reader.read_line(&mut request_line)? == 0 {
        return Ok(());
    }
    // Drain the remaining request headers (we serve GET/HEAD only, no body).
    let mut header = String::new();
    loop {
        header.clear();
        if reader.read_line(&mut header)? == 0 || header == "\r\n" || header == "\n" {
            break;
        }
    }

    let mut parts = request_line.split_whitespace();
    let method = parts.next().unwrap_or("");
    let raw_target = parts.next().unwrap_or("/");

    if method != "GET" && method != "HEAD" {
        return write_error(&mut stream, 405, "Method Not Allowed");
    }

    // Strip query/fragment, drop the leading slash, default to index.html.
    let mut path = raw_target
        .split(['?', '#'])
        .next()
        .unwrap_or("/")
        .trim_start_matches('/')
        .to_owned();
    if path.is_empty() || path.ends_with('/') {
        path.push_str("index.html");
    }

    let Some(body) = asset(&path) else {
        return write_error(&mut stream, 404, "Not Found");
    };

    let head = format!(
        "HTTP/1.1 200 OK\r\n\
         Content-Type: {}\r\n\
         Content-Length: {}\r\n\
         Cross-Origin-Opener-Policy: same-origin\r\n\
         Cross-Origin-Embedder-Policy: require-corp\r\n\
         Cache-Control: no-store\r\n\
         Connection: close\r\n\r\n",
        content_type(&path),
        body.len(),
    );
    stream.write_all(head.as_bytes())?;
    if method == "GET" {
        stream.write_all(body)?;
    }
    stream.flush()
}

/// Write a minimal error response and close.
fn write_error(stream: &mut TcpStream, code: u16, reason: &str) -> std::io::Result<()> {
    let body = format!("{code} {reason}\n");
    let head = format!(
        "HTTP/1.1 {code} {reason}\r\n\
         Content-Type: text/plain; charset=utf-8\r\n\
         Content-Length: {}\r\n\
         Connection: close\r\n\r\n",
        body.len(),
    );
    stream.write_all(head.as_bytes())?;
    stream.write_all(body.as_bytes())?;
    stream.flush()
}

/// Best-effort: open the default browser at `url`. A failure is non-fatal —
/// the URL is already printed for the user to open manually.
fn open_browser(url: &str) {
    #[cfg(target_os = "macos")]
    let cmd = ("open", [url]);
    #[cfg(target_os = "windows")]
    let cmd = ("cmd", ["/C", "start", url]);
    #[cfg(all(unix, not(target_os = "macos")))]
    let cmd = ("xdg-open", [url]);

    let _ = std::process::Command::new(cmd.0)
        .args(cmd.1)
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .spawn();
}
