// tcl-lsp — a language server and toolchain for Tcl
// Copyright (C) 2026 James Deucker (bitwisecook) <https://github.com/bitwisecook>
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
// SPDX-License-Identifier: AGPL-3.0-or-later

//! Issue #1362 — `$obj configure` on an `oo::configurable` class reported
//! `Unknown method 'configure' on class '::UnifiedTest'; did you mean
//! 'configure'?`.
//!
//! The accessors a configurable class generates for its `property` members
//! are written by no `method` body, so they land in neither the class's
//! member tables nor the hierarchy's `method_providers` — but the W308
//! *suggestion* list folded them in, which is how the diagnostic came to
//! suggest the very word it had just called unknown. Both sides now ask
//! `ClassHierarchy::configures_by_property`.
//!
//! This is the editor-visible half: what a user actually sees in the
//! Problems panel and in the token colouring.

use crate::common::helpers::*;
use crate::common::{Lsp, unique_uri};
use serde_json::{Value, json};

/// The ticket's shape: a configurable class, then both generated accessors.
const SRC: &str = "oo::configurable create UnifiedTest {\n\
                   \x20   property name\n\
                   }\n\
                   set t [UnifiedTest new]\n\
                   $t configure -name x\n\
                   $t cget -name\n";

/// A genuinely unknown method on the same configurable class.
const SRC_UNKNOWN: &str = "oo::configurable create UnifiedTest {\n\
                           \x20   property name\n\
                           }\n\
                           set t [UnifiedTest new]\n\
                           $t nosuchmethod\n";

/// A Tcl 9.0 server — `oo::configurable` and `property` are 9.0+.
fn lsp90() -> Lsp {
    Lsp::with_config(json!({
        "dialect": "tcl9.0",
        "features": { "linkedEditingRange": true },
    }))
}

fn codes(diags: &[Value]) -> Vec<&str> {
    diags
        .iter()
        .filter_map(|d| d.get("code").and_then(Value::as_str))
        .collect()
}

/// TN — the ticket's own repro: neither generated accessor draws W308.
#[test]
fn property_accessors_draw_no_w308() {
    let mut lsp = lsp90();
    let uri = unique_uri("tcl");
    let diags = lsp.open_ready(&uri, SRC);
    assert!(
        !codes(&diags).contains(&"W308"),
        "configure/cget are generated by the property: {diags:?}"
    );
}

/// TP guard — the abstention is scoped to the accessor pair, so a method
/// the class really does not have still draws W308.
#[test]
fn unknown_method_on_a_configurable_class_still_draws_w308() {
    let mut lsp = lsp90();
    let uri = unique_uri("tcl");
    let diags = lsp.open_ready(&uri, SRC_UNKNOWN);
    assert!(
        codes(&diags).contains(&"W308"),
        "a genuinely unknown method must still draw W308: {diags:?}"
    );
}

/// TP — the colouring half: `configure` on line 4 (0-based) is a `method`
/// token, the same classification a declared method word gets.
#[test]
fn configure_word_is_a_method_token() {
    let mut lsp = lsp90();
    let uri = unique_uri("tcl");
    lsp.open_ready(&uri, SRC);
    let legend =
        lsp.initialize_result()["capabilities"]["semanticTokensProvider"]["legend"]["tokenTypes"]
            .as_array()
            .expect("tokenTypes legend")
            .iter()
            .map(|v| v.as_str().unwrap_or("").to_owned())
            .collect::<Vec<_>>();
    let raw = lsp.semantic_tokens_settled(&uri);
    let tokens = decode_semantic_tokens(&raw);
    let method_line = 4; // 0-based: `$t configure -name x`
    let found = tokens.iter().any(|t| {
        t.line == method_line
            && legend
                .get(usize::try_from(t.ttype).unwrap_or(usize::MAX))
                .is_some_and(|ty| ty == "method")
    });
    assert!(
        found,
        "expected a `method` token on line {method_line}: {tokens:?} (legend={legend:?})"
    );
}
