# venv.tcl — virtual environment create/delete/info.

namespace eval ::tclpkg::venv {

    # Find tclsh on PATH, preferring newer versions.
    proc find_tclsh {{requested ""}} {
        if {$requested ne ""} {
            set path [_which "tclsh$requested"]
            if {$path ne ""} { return $path }
            set path [_which tclsh]
            if {$path ne ""} { return $path }
            error "tclsh$requested not found on PATH"
        }
        foreach name {tclsh9.0 tclsh8.6 tclsh8.5 tclsh} {
            set path [_which $name]
            if {$path ne ""} { return $path }
        }
        error "no tclsh found on PATH"
    }

    proc _which {name} {
        foreach dir [split $::env(PATH) [expr {$::tcl_platform(platform) eq "windows" ? ";" : ":"}]] {
            set path [file join $dir $name]
            if {[file executable $path]} { return $path }
        }
        return ""
    }

    proc _tclsh_version {tclsh_path} {
        catch {
            set result [exec $tclsh_path << "puts \[info patchlevel\]"]
            return [string trim $result]
        }
        return ""
    }

    # Create a new virtual environment.
    proc create {venv_path args} {
        set tcl_version ""
        set system_site 0
        set prompt ""
        foreach {k v} $args {
            switch -- $k {
                -tcl    { set tcl_version $v }
                -system { set system_site $v }
                -prompt { set prompt $v }
            }
        }

        set venv_path [file normalize $venv_path]
        if {[file exists $venv_path]} {
            error "directory already exists: $venv_path (use --force to overwrite)"
        }

        set tclsh [find_tclsh $tcl_version]
        set version_str [_tclsh_version $tclsh]
        if {$version_str eq ""} {
            set version_str [expr {$tcl_version ne "" ? $tcl_version : "unknown"}]
        }
        if {$prompt eq ""} { set prompt [file tail $venv_path] }

        set bin_dir [file join $venv_path bin]
        set lib_dir [file join $venv_path lib]
        file mkdir $bin_dir
        file mkdir $lib_dir

        # Write tclvenv.cfg.
        set ts [clock format [clock seconds] -format "%Y-%m-%dT%H:%M:%SZ" -gmt 1]
        set cfg [join [list \
            "tcl_version = $version_str" \
            "tcl_executable = $tclsh" \
            "venv_tool = tclpkg 0.1.0" \
            "created = $ts" \
            "prompt = $prompt" \
            "include-system-site-packages = [expr {$system_site ? "true" : "false"}]" \
        ] "\n"]
        _write_file [file join $venv_path tclvenv.cfg] "$cfg\n"

        # Write tclsh wrapper.
        set wrapper [join [list \
            "#!/bin/sh" \
            "# Auto-generated by tclpkg — do not edit." \
            "VENV=\"\$(cd \"\$(dirname \"\$0\")/..\" && pwd)\"" \
            ": \"\${TCLLIBPATH:=}\"" \
            "export TCLLIBPATH=\"\$VENV/lib\${TCLLIBPATH:+ \$TCLLIBPATH}\"" \
            "export TCL_VENV=\"\$VENV\"" \
            "exec \"$tclsh\" \"\$@\"" \
        ] "\n"]
        set wrapper_path [file join $bin_dir tclsh]
        _write_file $wrapper_path "$wrapper\n"
        file attributes $wrapper_path -permissions 0755

        # Write bash/zsh activation script.
        _write_activate_bash [file join $bin_dir activate] $venv_path $prompt

        # Write fish activation script.
        _write_activate_fish [file join $bin_dir activate.fish] $venv_path $prompt

        # Write lib/pkgIndex.tcl placeholder.
        _write_file [file join $lib_dir pkgIndex.tcl] \
            "# Auto-generated by tclpkg — do not edit.\n# Regenerated by 'tclpkg pkg install'.\n"

        return $venv_path
    }

    proc read_config {venv_path} {
        set cfg_file [file join $venv_path tclvenv.cfg]
        if {![file isfile $cfg_file]} {
            error "not a tclpkg venv: $venv_path (missing tclvenv.cfg)"
        }
        set fd [open $cfg_file r]
        set text [read $fd]
        close $fd
        set result {}
        foreach line [split $text "\n"] {
            if {[string match "*=*" $line]} {
                set idx [string first "=" $line]
                set key [string trim [string range $line 0 $idx-1]]
                set val [string trim [string range $line $idx+1 end]]
                dict set result $key $val
            }
        }
        return $result
    }

    proc delete {venv_path} {
        set venv_path [file normalize $venv_path]
        if {![file isdirectory $venv_path]} {
            error "venv not found: $venv_path"
        }
        if {![file isfile [file join $venv_path tclvenv.cfg]]} {
            error "directory is not a tclpkg venv: $venv_path (missing tclvenv.cfg)"
        }
        if {[info exists ::env(TCL_VENV)] && [file normalize $::env(TCL_VENV)] eq $venv_path} {
            error "cannot delete the currently active venv (run 'deactivate' first)"
        }
        file delete -force $venv_path
    }

    proc _write_activate_bash {path venv prompt} {
        set script [subst -nocommands {# Auto-generated by tclpkg — source this file.
deactivate () {
    if [ -n "\${_OLD_TCL_VENV_PATH:-}" ]; then
        PATH="\${_OLD_TCL_VENV_PATH}"
        export PATH
        unset _OLD_TCL_VENV_PATH
    fi
    if [ -n "\${_OLD_TCL_VENV_TCLLIBPATH:-}" ]; then
        TCLLIBPATH="\${_OLD_TCL_VENV_TCLLIBPATH}"
        export TCLLIBPATH
    else
        unset TCLLIBPATH
    fi
    unset _OLD_TCL_VENV_TCLLIBPATH
    if [ -n "\${_OLD_TCL_VENV_PS1:-}" ]; then
        PS1="\${_OLD_TCL_VENV_PS1}"
        export PS1
        unset _OLD_TCL_VENV_PS1
    fi
    unset TCL_VENV
}

_OLD_TCL_VENV_PATH="\$PATH"
_OLD_TCL_VENV_TCLLIBPATH="\${TCLLIBPATH:-}"
_OLD_TCL_VENV_PS1="\${PS1:-}"

export TCL_VENV="$venv"
export TCLLIBPATH="$venv/lib\${TCLLIBPATH:+ \$TCLLIBPATH}"
export PATH="$venv/bin:\$PATH"
PS1="($prompt) \${PS1:-}"
export PS1
}]
        _write_file $path $script
    }

    proc _write_activate_fish {path venv prompt} {
        set script [subst -nocommands {# Auto-generated by tclpkg — source this file in fish.
function deactivate
    if set -q _OLD_TCL_VENV_PATH
        set -gx PATH \$_OLD_TCL_VENV_PATH
        set -e _OLD_TCL_VENV_PATH
    end
    if set -q _OLD_TCL_VENV_TCLLIBPATH
        set -gx TCLLIBPATH \$_OLD_TCL_VENV_TCLLIBPATH
        set -e _OLD_TCL_VENV_TCLLIBPATH
    else
        set -e TCLLIBPATH
    end
    set -e TCL_VENV
    functions -e deactivate
end

set -gx _OLD_TCL_VENV_PATH \$PATH
if set -q TCLLIBPATH
    set -gx _OLD_TCL_VENV_TCLLIBPATH \$TCLLIBPATH
end

set -gx TCL_VENV "$venv"
set -gx TCLLIBPATH "$venv/lib \$TCLLIBPATH"
set -gx PATH "$venv/bin" \$PATH
}]
        _write_file $path $script
    }

    proc _write_file {path content} {
        set fd [open $path w]
        fconfigure $fd -encoding utf-8 -translation lf
        puts -nonewline $fd $content
        close $fd
    }
}
