ltm rule /Common/__tcl_lsp_evtflow_EFB_clientssl_trace {
    when CLIENT_ACCEPTED {
        set evtflow_tls_seq 0
        set evtflow_tls_flow [format {%s:%s-%s:%s} [IP::client_addr] [TCP::client_port] [IP::local_addr] [TCP::local_port]]
    }
    when CLIENTSSL_CLIENTHELLO {
        incr evtflow_tls_seq
        log local0. "EVTFLOW|run=EFB|probe=tls|event=CLIENTSSL_CLIENTHELLO|tmm=[TMM::cmp_group]:[TMM::cmp_unit]|flow=$evtflow_tls_flow|seq=$evtflow_tls_seq"
    }
    when CLIENTSSL_SERVERHELLO_SEND {
        incr evtflow_tls_seq
        log local0. "EVTFLOW|run=EFB|probe=tls|event=CLIENTSSL_SERVERHELLO_SEND|tmm=[TMM::cmp_group]:[TMM::cmp_unit]|flow=$evtflow_tls_flow|seq=$evtflow_tls_seq"
    }
    when CLIENTSSL_HANDSHAKE {
        incr evtflow_tls_seq
        log local0. "EVTFLOW|run=EFB|probe=tls|event=CLIENTSSL_HANDSHAKE|tmm=[TMM::cmp_group]:[TMM::cmp_unit]|flow=$evtflow_tls_flow|seq=$evtflow_tls_seq|cipher=[SSL::cipher name]|version=[SSL::cipher version]"
    }
}
