ltm rule /Common/__tcl_lsp_evtflow_EFB_dns_trace {
    when CLIENT_ACCEPTED {
        set evtflow_dns_seq 0
        set evtflow_dns_flow [format {%s:%s-%s:%s} [IP::client_addr] [UDP::client_port] [IP::local_addr] [UDP::local_port]]
    }
    when DNS_REQUEST {
        incr evtflow_dns_seq
        log local0. "EVTFLOW|run=EFB|probe=dns|event=DNS_REQUEST|tmm=[TMM::cmp_group]:[TMM::cmp_unit]|flow=$evtflow_dns_flow|seq=$evtflow_dns_seq|id=[DNS::header id]|name=[DNS::question name]|type=[DNS::question type]"
    }
    when DNS_RESPONSE {
        incr evtflow_dns_seq
        log local0. "EVTFLOW|run=EFB|probe=dns|event=DNS_RESPONSE|tmm=[TMM::cmp_group]:[TMM::cmp_unit]|flow=$evtflow_dns_flow|seq=$evtflow_dns_seq|id=[DNS::header id]|answers=[llength [DNS::answer]]"
    }
}
