ltm rule /Common/__tcl_lsp_evtflow_EFB_tcp_trace {
    when RULE_INIT {
        log local0. "EVTFLOW|run=EFB|probe=tcp|event=RULE_INIT|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
    when CLIENT_ACCEPTED {
        set evtflow_seq 0
        set evtflow_flow [format {%s:%s-%s:%s} [IP::client_addr] [TCP::client_port] [IP::local_addr] [TCP::local_port]]
        incr evtflow_seq
        log local0. "EVTFLOW|run=EFB|probe=flow|event=CLIENT_ACCEPTED|tmm=[TMM::cmp_group]:[TMM::cmp_unit]|flow=$evtflow_flow|seq=$evtflow_seq"
        TCP::collect
    }
    when CLIENT_DATA {
        incr evtflow_seq
        log local0. "EVTFLOW|run=EFB|probe=flow|event=CLIENT_DATA|tmm=[TMM::cmp_group]:[TMM::cmp_unit]|flow=$evtflow_flow|seq=$evtflow_seq|bytes=[TCP::payload length]"
        TCP::release
    }
    when LB_SELECTED {
        incr evtflow_seq
        log local0. "EVTFLOW|run=EFB|probe=flow|event=LB_SELECTED|tmm=[TMM::cmp_group]:[TMM::cmp_unit]|flow=$evtflow_flow|seq=$evtflow_seq"
    }
    when SERVER_INIT {
        incr evtflow_seq
        log local0. "EVTFLOW|run=EFB|probe=flow|event=SERVER_INIT|tmm=[TMM::cmp_group]:[TMM::cmp_unit]|flow=$evtflow_flow|seq=$evtflow_seq"
    }
    when SA_PICKED {
        incr evtflow_seq
        log local0. "EVTFLOW|run=EFB|probe=flow|event=SA_PICKED|tmm=[TMM::cmp_group]:[TMM::cmp_unit]|flow=$evtflow_flow|seq=$evtflow_seq"
    }
    when SERVER_CONNECTED {
        incr evtflow_seq
        log local0. "EVTFLOW|run=EFB|probe=flow|event=SERVER_CONNECTED|tmm=[TMM::cmp_group]:[TMM::cmp_unit]|flow=$evtflow_flow|seq=$evtflow_seq"
        TCP::collect
    }
    when LB_FAILED {
        incr evtflow_seq
        log local0. "EVTFLOW|run=EFB|probe=flow|event=LB_FAILED|tmm=[TMM::cmp_group]:[TMM::cmp_unit]|flow=$evtflow_flow|seq=$evtflow_seq"
    }
    when LB_QUEUED {
        incr evtflow_seq
        log local0. "EVTFLOW|run=EFB|probe=flow|event=LB_QUEUED|tmm=[TMM::cmp_group]:[TMM::cmp_unit]|flow=$evtflow_flow|seq=$evtflow_seq"
    }
    when SERVER_DATA {
        incr evtflow_seq
        log local0. "EVTFLOW|run=EFB|probe=flow|event=SERVER_DATA|tmm=[TMM::cmp_group]:[TMM::cmp_unit]|flow=$evtflow_flow|seq=$evtflow_seq|bytes=[TCP::payload length]"
        TCP::release
    }
    when SERVER_CLOSED {
        incr evtflow_seq
        log local0. "EVTFLOW|run=EFB|probe=flow|event=SERVER_CLOSED|tmm=[TMM::cmp_group]:[TMM::cmp_unit]|flow=$evtflow_flow|seq=$evtflow_seq"
    }
    when CLIENT_CLOSED {
        incr evtflow_seq
        log local0. "EVTFLOW|run=EFB|probe=flow|event=CLIENT_CLOSED|tmm=[TMM::cmp_group]:[TMM::cmp_unit]|flow=$evtflow_flow|seq=$evtflow_seq"
    }
}
