ltm rule probe_vf_switch_nextline {
when RULE_INIT {
set out "NOTRUN"
switch "a"
{
  a {set out "matched-a"}
  default {set out "matched-default"}
}
log local0. "VERIFY switch_nextline out=<$out>"
}
}
