ltm profile client-ssl /Common/__tcl_lsp_evtflow_egh_clientssl {
    defaults-from /Common/clientssl
    cert-key-chain {
        evtflow {
            cert /Common/__tcl_lsp_evtflow_egh_server
            key /Common/__tcl_lsp_evtflow_egh_server
        }
    }
}
ltm profile server-ssl /Common/__tcl_lsp_evtflow_egh_serverssl {
    defaults-from /Common/serverssl
    peer-cert-mode ignore
}
ltm profile client-ssl /Common/__tcl_lsp_evtflow_egh_clientssl_dynamic {
    defaults-from /Common/clientssl
    authenticate always
    authenticate-depth 9
    ca-file /Common/__tcl_lsp_evtflow_egh_ca
    cert-key-chain {
        evtflow {
            cert /Common/__tcl_lsp_evtflow_egh_server
            key /Common/__tcl_lsp_evtflow_egh_server
        }
    }
    client-cert-ca /Common/__tcl_lsp_evtflow_egh_ca
    options { no-tlsv1.3 }
    peer-cert-mode ignore
    retain-certificate true
}
ltm profile client-ssl /Common/__tcl_lsp_evtflow_egh_clientssl_request {
    defaults-from /Common/clientssl
    authenticate always
    authenticate-depth 9
    ca-file /Common/__tcl_lsp_evtflow_egh_ca
    cert-key-chain {
        evtflow {
            cert /Common/__tcl_lsp_evtflow_egh_server
            key /Common/__tcl_lsp_evtflow_egh_server
        }
    }
    client-cert-ca /Common/__tcl_lsp_evtflow_egh_ca
    options { no-tlsv1.3 }
    peer-cert-mode request
    retain-certificate true
}
ltm profile client-ssl /Common/__tcl_lsp_evtflow_egh_clientssl_require {
    defaults-from /Common/clientssl
    authenticate always
    authenticate-depth 9
    ca-file /Common/__tcl_lsp_evtflow_egh_ca
    cert-key-chain {
        evtflow {
            cert /Common/__tcl_lsp_evtflow_egh_server
            key /Common/__tcl_lsp_evtflow_egh_server
        }
    }
    client-cert-ca /Common/__tcl_lsp_evtflow_egh_ca
    options { no-tlsv1.3 }
    peer-cert-mode require
    retain-certificate true
}
