"""Generate a Wireshark *profile* directory from a BIG-IP config.

Powers ``f5 enrich-wireshark``.

A Wireshark profile is a small directory that lives under
``~/.config/wireshark/profiles/<name>/`` (Linux/macOS) or
``%APPDATA%\\Wireshark\\profiles\\<name>\\`` (Windows).  Each file in
the directory teaches Wireshark how to label some part of a packet:

================  ==========================================================
``hosts``         IPv4/IPv6 → name (alternative to a PCAPNG NRB; works on
                  plain libpcap captures too).
``subnets``       ``<network>/<prefix>  <name>`` — e.g. tag every host on
                  ``10.0.5.0/24`` with ``net-common-external-self``.
``vlans``         ``<vlan_tag> <name>`` — derived from ``net vlan { tag N }``.
``dfilters``      Saved display filters (``"label" filter-expr``).  We
                  emit one per virtual-server destination so the user
                  can click through to "all packets touching VS X".
``services``      Reserved for future port→service mappings.
``ethers``        Reserved for future MAC→name mappings.
================  ==========================================================

We emit the four most-useful files (``hosts``, ``subnets``, ``vlans``,
``dfilters``) plus a ``README.md`` explaining how to install the
profile.  The verb is purely additive — it never touches an existing
profile directory unless the user passes ``--force``.
"""

from __future__ import annotations

import ipaddress
import re
from dataclasses import dataclass, field
from pathlib import Path

from .model import BigipConfig
from .parser import _extract_blocks
from .pcap_enrich import (
    NameIndex,
    _extract_self_ips,
    _label,
    _split_destination,
    build_merged_name_index,
)


@dataclass(frozen=True, slots=True)
class WiresharkProfileWriteResult:
    hosts_lines: int = 0
    subnets_lines: int = 0
    vlans_lines: int = 0
    dfilters_lines: int = 0
    files_written: tuple[str, ...] = ()


@dataclass(slots=True)
class WiresharkProfile:
    """In-memory model of every file the profile directory will contain."""

    hosts: list[tuple[str, str]] = field(default_factory=list)
    subnets: list[tuple[str, str]] = field(default_factory=list)
    vlans: list[tuple[int, str]] = field(default_factory=list)
    dfilters: list[tuple[str, str]] = field(default_factory=list)

    def extend(self, other: WiresharkProfile) -> None:
        """Append every entry from *other* to ``self``."""
        self.hosts.extend(other.hosts)
        self.subnets.extend(other.subnets)
        self.vlans.extend(other.vlans)
        self.dfilters.extend(other.dfilters)

    def deduplicate(self) -> None:
        """Drop duplicate rows while preserving insertion order."""
        self.hosts = list(dict.fromkeys(self.hosts))
        self.subnets = list(dict.fromkeys(self.subnets))
        self.vlans = list(dict.fromkeys(self.vlans))
        self.dfilters = list(dict.fromkeys(self.dfilters))

    def write_to(self, directory: Path) -> WiresharkProfileWriteResult:
        directory.mkdir(parents=True, exist_ok=True)
        files: list[str] = []

        if self.hosts:
            (directory / "hosts").write_text(
                _format_hosts(self.hosts), encoding="utf-8"
            )
            files.append("hosts")
        if self.subnets:
            (directory / "subnets").write_text(
                _format_subnets(self.subnets), encoding="utf-8"
            )
            files.append("subnets")
        if self.vlans:
            (directory / "vlans").write_text(
                _format_vlans(self.vlans), encoding="utf-8"
            )
            files.append("vlans")
        if self.dfilters:
            (directory / "dfilters").write_text(
                _format_dfilters(self.dfilters), encoding="utf-8"
            )
            files.append("dfilters")

        (directory / "README.md").write_text(
            _format_readme(directory.name, files), encoding="utf-8"
        )
        files.append("README.md")

        return WiresharkProfileWriteResult(
            hosts_lines=len(self.hosts),
            subnets_lines=len(self.subnets),
            vlans_lines=len(self.vlans),
            dfilters_lines=len(self.dfilters),
            files_written=tuple(files),
        )


# Formatters
#
# Wireshark accepts whitespace-separated columns in hosts / subnets /
# vlans / ethers files.  Comments start with ``#``.  dfilters uses
# ``"name" filter-expr`` per line.


def _format_hosts(entries: list[tuple[str, str]]) -> str:
    lines = ["# Generated by f5 enrich-wireshark — IP -> BIG-IP object label"]
    for addr, name in entries:
        lines.append(f"{addr}\t{name}")
    return "\n".join(lines) + "\n"


def _format_subnets(entries: list[tuple[str, str]]) -> str:
    lines = [
        "# Generated by f5 enrich-wireshark — CIDR -> BIG-IP self-IP label",
        "# Hosts inside these networks pick up the corresponding name.",
    ]
    for cidr, name in entries:
        lines.append(f"{cidr}\t{name}")
    return "\n".join(lines) + "\n"


def _format_vlans(entries: list[tuple[int, str]]) -> str:
    lines = ["# Generated by f5 enrich-wireshark — VLAN tag -> BIG-IP vlan name"]
    for tag, name in entries:
        lines.append(f"{tag}\t{name}")
    return "\n".join(lines) + "\n"


def _format_dfilters(entries: list[tuple[str, str]]) -> str:
    lines = ["# Generated by f5 enrich-wireshark — saved display filters"]
    for label, expr in entries:
        # Escape any embedded double-quote in the label (rare).
        safe_label = label.replace('"', "'")
        lines.append(f'"{safe_label}" {expr}')
    return "\n".join(lines) + "\n"


def _format_readme(profile_name: str, files: list[str]) -> str:
    file_list = "\n".join(f"- `{f}`" for f in files)
    return (
        f"# `{profile_name}` Wireshark profile\n"
        f"\n"
        f"Generated by `f5 enrich-wireshark`.  Drop this directory into "
        f"your Wireshark profiles folder and select it from "
        f"**Edit → Configuration Profiles**.\n"
        f"\n"
        f"## Install\n"
        f"\n"
        f"- **Linux/macOS:** copy to "
        f"`~/.config/wireshark/profiles/{profile_name}/`\n"
        f"- **Windows:** copy to "
        f"`%APPDATA%\\Wireshark\\profiles\\{profile_name}\\`\n"
        f"\n"
        f"## Files\n"
        f"\n"
        f"{file_list}\n"
    )


# Source-text extractors


_VLAN_TAG_LINE = re.compile(r"^\s*tag\s+(\d+)\s*$", re.MULTILINE)


def _extract_vlans(source: str) -> list[tuple[str, int]]:
    """Return ``[(full_path, tag), …]`` for every ``net vlan`` block."""
    out: list[tuple[str, int]] = []
    for block in _extract_blocks(source):
        parts = block.header.split()
        if len(parts) < 3 or parts[0] != "net" or parts[1] != "vlan":
            continue
        full_path = parts[2]
        m = _VLAN_TAG_LINE.search(block.body)
        if m is None:
            continue
        try:
            tag = int(m.group(1))
        except ValueError:
            continue
        out.append((full_path, tag))
    return out


# Builder


def _hosts_from_index(index: NameIndex) -> list[tuple[str, str]]:
    """Flatten ``NameIndex`` exact entries into ``(IP, name)`` pairs.

    Each label gets its own line — Wireshark accepts repeated keys and
    treats each as an alias, which keeps the file mirror-image-readable
    and lets every label show up in the *Resolved Addresses* dialog.
    """
    pairs: list[tuple[str, str]] = []
    for addr, names in index.v4.items():
        for name in names:
            pairs.append((addr, name))
    for addr, names in index.v6.items():
        for name in names:
            pairs.append((addr, name))
    return pairs


def _subnets_from_index(index: NameIndex) -> list[tuple[str, str]]:
    pairs: list[tuple[str, str]] = []
    for net, name in index.v4_subnets:
        pairs.append((str(net), name))
    for net, name in index.v6_subnets:
        pairs.append((str(net), name))
    return pairs


def _dfilters_for_virtual_servers(config: BigipConfig) -> list[tuple[str, str]]:
    """One display-filter button per virtual server (``ip.addr == <dest>``)."""
    out: list[tuple[str, str]] = []
    for full_path, vs in config.virtual_servers.items():
        addr = _split_destination(vs.destination)
        if not addr:
            continue
        try:
            ip = ipaddress.ip_address(addr)
        except ValueError:
            continue
        field_name = "ipv6.addr" if isinstance(ip, ipaddress.IPv6Address) else "ip.addr"
        label = _label("vs", full_path)
        out.append((label, f"{field_name} == {addr}"))
    return out


def _dfilters_for_self_ips(source: str) -> list[tuple[str, str]]:
    """One display filter per ``net self`` block, scoped to its CIDR."""
    out: list[tuple[str, str]] = []
    for self_ip in _extract_self_ips(source):
        if self_ip.network is None:
            continue
        net = self_ip.network
        field_name = (
            "ipv6.addr"
            if isinstance(net, ipaddress.IPv6Network)
            else "ip.addr"
        )
        label = _label("net", self_ip.full_path)
        out.append((label, f"{field_name} == {net}"))
    return out


def build_wireshark_profile(
    configs_with_sources: list[tuple[BigipConfig, str]],
) -> WiresharkProfile:
    """Assemble a :class:`WiresharkProfile` from one or more ``(config, source)`` pairs.

    Multi-input deployments — GTM separate from LTM, multiple LTM
    tiers, partition-split SCFs — feed every file in via this list.
    Wide-IP / pool / server cross-references resolve against the
    combined source so a wide-IP in one file can reach a server
    declared in another.
    """
    if not configs_with_sources:
        return WiresharkProfile()

    combined_source = "\n".join(src for _cfg, src in configs_with_sources)
    index = build_merged_name_index(configs_with_sources)

    profile = WiresharkProfile(
        hosts=_hosts_from_index(index),
        subnets=_subnets_from_index(index),
        vlans=[
            (tag, _label("vlan", full_path))
            for full_path, tag in _extract_vlans(combined_source)
        ],
        dfilters=_dfilters_for_self_ips(combined_source),
    )
    for config, _src in configs_with_sources:
        profile.dfilters.extend(_dfilters_for_virtual_servers(config))

    profile.deduplicate()
    return profile
