// tcl-lsp — a language server and toolchain for Tcl
// Copyright (C) 2026 James Deucker (bitwisecook)
// SPDX-License-Identifier: AGPL-3.0-or-later

//! Original expression byte, numeric-unit and NUL conversion specimens.
//! Consumers compare actual completions with an independently selected oracle.
//! These sources carry no compiler, handler or representation authority.

/// Original native Jim expression value and comparison observations.
pub const JIM_RAW_EXPRESSION_VALUE_SCRIPTS: &[&str] = &[
    r"set a [binary format H* ff];set b [binary format H* c3bf];list [expr {$a eq $b}] [expr {$a == $b}] [expr {$a lt $b}] [expr {$a le $b}]",
    r"set a [binary format H* ff];set b [binary format H* c3bf];list [expr {$a in [list $b]}] [expr {$a in [list $a]}] [expr {$a ni [list $b]}]",
    r"set a [binary format H* ff];list [expr {$a eq $a}] [expr {$a ne $a}]",
    r"set a [binary format H* 410042];set b [binary format H* 410043];list [expr {$a eq $b}] [expr {$a == $b}] [expr {$a lt $b}]",
    r"set a [binary format H* eda080];set b [binary format H* eda081];list [expr {$a eq $b}] [expr {$a lt $b}] [expr {$a in [list $a $b]}]",
    r"set s [binary format H* c341c3a9];set r [string range $s 0 1];list [expr {$r eq $s}] [expr {$r == $s}] [string length $r]",
    r"set a [binary format H* ff];expr {$a + 1}",
    r"set a [binary format H* ff];expr {$a ? 1 : 2}",
    r"set a [binary format H* ff];set seen 0;expr {0 && [incr seen] && $a};set seen",
];

/// Original native Jim expression conversion error observations.
pub const JIM_RAW_EXPRESSION_ERROR_SCRIPTS: &[&str] = &[
    r"set a [binary format H* ff];expr {$a + 1}",
    r"set a [binary format H* ff];expr {1 + $a}",
    r"set a [binary format H* ff];expr {$a & 1}",
    r"set a [binary format H* ff];expr {$a % 1}",
    r"set a [binary format H* ff];expr {~$a}",
    r"set a [binary format H* ff];expr {-$a}",
    r"set a [binary format H* ff];expr {!$a}",
    r"set a [binary format H* ff];expr {$a ? 1 : 2}",
    r"set a [binary format H* ff];expr {$a && 1}",
];

/// Original native cross-release scalar numeric NUL observations.
pub const NUMERIC_NUL_EXPRESSION_SCRIPTS: &[&str] = &[
    r"set ::errorCode NONE; set x [binary format H* 310058]; set c [catch {expr {$x + 1}} r]; puts [list $c [binary scan $r H* hx; set hx] $::errorCode]",
    r"set ::errorCode NONE; set x [binary format H* 310058]; set c [catch {expr {$x & 1}} r]; puts [list $c [binary scan $r H* hx; set hx] $::errorCode]",
    r"set ::errorCode NONE; set x [binary format H* 310058]; set c [catch {expr {$x ? 1 : 0}} r]; puts [list $c [binary scan $r H* hx; set hx] $::errorCode]",
    r"set ::errorCode NONE; set x [binary format H* 3100ff]; set c [catch {expr {$x + 1}} r]; puts [list $c [binary scan $r H* hx; set hx] $::errorCode]",
    r"set ::errorCode NONE; set x [binary format H* 3100ff]; set c [catch {expr {$x & 1}} r]; puts [list $c [binary scan $r H* hx; set hx] $::errorCode]",
    r"set ::errorCode NONE; set x [binary format H* 3100ff]; set c [catch {expr {$x ? 1 : 0}} r]; puts [list $c [binary scan $r H* hx; set hx] $::errorCode]",
    r"set ::errorCode NONE; set x [binary format H* 312e350058]; set c [catch {expr {$x + 1}} r]; puts [list $c [binary scan $r H* hx; set hx] $::errorCode]",
    r"set ::errorCode NONE; set x [binary format H* 312e350058]; set c [catch {expr {$x & 1}} r]; puts [list $c [binary scan $r H* hx; set hx] $::errorCode]",
    r"set ::errorCode NONE; set x [binary format H* 312e350058]; set c [catch {expr {$x ? 1 : 0}} r]; puts [list $c [binary scan $r H* hx; set hx] $::errorCode]",
    r"set ::errorCode NONE; set x [binary format H* 300058]; set c [catch {expr {$x + 1}} r]; puts [list $c [binary scan $r H* hx; set hx] $::errorCode]",
    r"set ::errorCode NONE; set x [binary format H* 300058]; set c [catch {expr {$x & 1}} r]; puts [list $c [binary scan $r H* hx; set hx] $::errorCode]",
    r"set ::errorCode NONE; set x [binary format H* 300058]; set c [catch {expr {$x ? 1 : 0}} r]; puts [list $c [binary scan $r H* hx; set hx] $::errorCode]",
    r"set ::errorCode NONE; set x [binary format H* 00ff]; set c [catch {expr {$x + 1}} r]; puts [list $c [binary scan $r H* hx; set hx] $::errorCode]",
    r"set ::errorCode NONE; set x [binary format H* 00ff]; set c [catch {expr {$x & 1}} r]; puts [list $c [binary scan $r H* hx; set hx] $::errorCode]",
    r"set ::errorCode NONE; set x [binary format H* 00ff]; set c [catch {expr {$x ? 1 : 0}} r]; puts [list $c [binary scan $r H* hx; set hx] $::errorCode]",
    r"set ::errorCode NONE; set x [binary format H* ff0031]; set c [catch {expr {$x + 1}} r]; puts [list $c [binary scan $r H* hx; set hx] $::errorCode]",
    r"set ::errorCode NONE; set x [binary format H* ff0031]; set c [catch {expr {$x & 1}} r]; puts [list $c [binary scan $r H* hx; set hx] $::errorCode]",
    r"set ::errorCode NONE; set x [binary format H* ff0031]; set c [catch {expr {$x ? 1 : 0}} r]; puts [list $c [binary scan $r H* hx; set hx] $::errorCode]",
];
/// The same eighteen original numeric operations, with the observation list
/// returned instead of printed. This preserves catch code, raw result hex and
/// error code in result-based engine comparison harnesses.
pub const NUMERIC_NUL_EXPRESSION_OBSERVATION_SCRIPTS: &[&str] = &[
    r"set ::errorCode NONE; set x [binary format H* 310058]; set c [catch {expr {$x + 1}} r]; list $c [binary scan $r H* hx; set hx] $::errorCode",
    r"set ::errorCode NONE; set x [binary format H* 310058]; set c [catch {expr {$x & 1}} r]; list $c [binary scan $r H* hx; set hx] $::errorCode",
    r"set ::errorCode NONE; set x [binary format H* 310058]; set c [catch {expr {$x ? 1 : 0}} r]; list $c [binary scan $r H* hx; set hx] $::errorCode",
    r"set ::errorCode NONE; set x [binary format H* 3100ff]; set c [catch {expr {$x + 1}} r]; list $c [binary scan $r H* hx; set hx] $::errorCode",
    r"set ::errorCode NONE; set x [binary format H* 3100ff]; set c [catch {expr {$x & 1}} r]; list $c [binary scan $r H* hx; set hx] $::errorCode",
    r"set ::errorCode NONE; set x [binary format H* 3100ff]; set c [catch {expr {$x ? 1 : 0}} r]; list $c [binary scan $r H* hx; set hx] $::errorCode",
    r"set ::errorCode NONE; set x [binary format H* 312e350058]; set c [catch {expr {$x + 1}} r]; list $c [binary scan $r H* hx; set hx] $::errorCode",
    r"set ::errorCode NONE; set x [binary format H* 312e350058]; set c [catch {expr {$x & 1}} r]; list $c [binary scan $r H* hx; set hx] $::errorCode",
    r"set ::errorCode NONE; set x [binary format H* 312e350058]; set c [catch {expr {$x ? 1 : 0}} r]; list $c [binary scan $r H* hx; set hx] $::errorCode",
    r"set ::errorCode NONE; set x [binary format H* 300058]; set c [catch {expr {$x + 1}} r]; list $c [binary scan $r H* hx; set hx] $::errorCode",
    r"set ::errorCode NONE; set x [binary format H* 300058]; set c [catch {expr {$x & 1}} r]; list $c [binary scan $r H* hx; set hx] $::errorCode",
    r"set ::errorCode NONE; set x [binary format H* 300058]; set c [catch {expr {$x ? 1 : 0}} r]; list $c [binary scan $r H* hx; set hx] $::errorCode",
    r"set ::errorCode NONE; set x [binary format H* 00ff]; set c [catch {expr {$x + 1}} r]; list $c [binary scan $r H* hx; set hx] $::errorCode",
    r"set ::errorCode NONE; set x [binary format H* 00ff]; set c [catch {expr {$x & 1}} r]; list $c [binary scan $r H* hx; set hx] $::errorCode",
    r"set ::errorCode NONE; set x [binary format H* 00ff]; set c [catch {expr {$x ? 1 : 0}} r]; list $c [binary scan $r H* hx; set hx] $::errorCode",
    r"set ::errorCode NONE; set x [binary format H* ff0031]; set c [catch {expr {$x + 1}} r]; list $c [binary scan $r H* hx; set hx] $::errorCode",
    r"set ::errorCode NONE; set x [binary format H* ff0031]; set c [catch {expr {$x & 1}} r]; list $c [binary scan $r H* hx; set hx] $::errorCode",
    r"set ::errorCode NONE; set x [binary format H* ff0031]; set c [catch {expr {$x ? 1 : 0}} r]; list $c [binary scan $r H* hx; set hx] $::errorCode",
];

/// Actual counted-source syntax failures. Rows retain the selected engine,
/// original case name, original source bytes and exact native result bytes.
pub const NATIVE_EXPRESSION_SYNTAX_FAILURES: &[(&str, &str, &[u8], &[u8])] = &[
    (
        "tcl8.4",
        "quote_nul_eof",
        b"\x22\xff\x00tail\x22 +",
        b"syntax error in expression \x22\x22\xff\x22: premature end of expression",
    ),
    (
        "tcl8.4",
        "quote_nul_paren",
        b"\x22\xff\x00tail\x22 + )",
        b"syntax error in expression \x22\x22\xff\x22: unexpected close parenthesis",
    ),
    (
        "tcl8.4",
        "suffix_nul_eof",
        b"0 + \x22\xff\x00tail\x22 +",
        b"syntax error in expression \x220 + \x22\xff\x22: premature end of expression",
    ),
    (
        "tcl8.4",
        "external_nul_middle",
        b"1\x00+2",
        b"syntax error in expression \x221\x22: extra tokens at end of expression",
    ),
    (
        "tcl8.4",
        "external_nul_end",
        b"1+2\x00",
        b"syntax error in expression \x221+2\x22: extra tokens at end of expression",
    ),
    (
        "tcl8.4",
        "invalid_raw_operand",
        b"1+\xff",
        b"syntax error in expression \x221+\xff\x22: character not legal in expressions",
    ),
    (
        "tcl8.4",
        "bare_raw_variable",
        b"$\xff",
        b"syntax error in expression \x22$\xff\x22: extra tokens at end of expression",
    ),
    (
        "tcl8.4",
        "unclosed_quote_raw_nul",
        b"\x22\xff\x00tail",
        b"missing \x22",
    ),
    (
        "tcl8.4",
        "unclosed_brace_raw_nul",
        b"{\xff\x00tail",
        b"missing close-brace",
    ),
    (
        "tcl8.4",
        "raw_brace_extra",
        b"{\xff} \x00 1",
        b"syntax error in expression \x22{\xff} \x22: extra tokens at end of expression",
    ),
    (
        "tcl8.4",
        "raw_quote_extra",
        b"\x22\xff\x22 1",
        b"syntax error in expression \x22\x22\xff\x22 1\x22: extra tokens at end of expression",
    ),
    (
        "tcl8.4",
        "raw_command_extra",
        b"[set {\xff}] \x00 1",
        b"syntax error in expression \x22[set {\xff}] \x22: extra tokens at end of expression",
    ),
    (
        "tcl8.5",
        "quote_nul_eof",
        b"\x22\xff\x00tail\x22 +",
        b"missing operand at _@_\x0ain expression \x22\x22\xff_@_\x22",
    ),
    (
        "tcl8.5",
        "quote_nul_paren",
        b"\x22\xff\x00tail\x22 + )",
        b"missing operand at _@_\x0ain expression \x22\x22\xff_@_)\x22",
    ),
    (
        "tcl8.5",
        "suffix_nul_eof",
        b"0 + \x22\xff\x00tail\x22 +",
        b"missing operand at _@_\x0ain expression \x220 + \x22\xff_@_\x22",
    ),
    (
        "tcl8.5",
        "external_nul_middle",
        b"1\x00+2",
        b"invalid character \x22\x22\x0ain expression \x221+2\x22",
    ),
    (
        "tcl8.5",
        "external_nul_end",
        b"1+2\x00",
        b"invalid character \x22\x22\x0ain expression \x221+2\x22",
    ),
    (
        "tcl8.5",
        "invalid_raw_operand",
        b"1+\xff",
        b"invalid character \x22\xff\x22\x0ain expression \x221+\xff\x22",
    ),
    (
        "tcl8.5",
        "bare_raw_variable",
        b"$\xff",
        b"invalid character \x22$\x22\x0ain expression \x22$\xff\x22",
    ),
    (
        "tcl8.5",
        "unclosed_quote_raw_nul",
        b"\x22\xff\x00tail",
        b"missing \x22\x0ain expression \x22\x22\xff\x22",
    ),
    (
        "tcl8.5",
        "unclosed_brace_raw_nul",
        b"{\xff\x00tail",
        b"missing close-brace\x0ain expression \x22{\xff\x22",
    ),
    (
        "tcl8.5",
        "raw_brace_extra",
        b"{\xff} \x00 1",
        b"invalid character \x22\x22\x0ain expression \x22{\xff}  1\x22",
    ),
    (
        "tcl8.5",
        "raw_quote_extra",
        b"\x22\xff\x22 1",
        b"missing operator at _@_\x0ain expression \x22\x22\xff\x22 _@_1\x22",
    ),
    (
        "tcl8.5",
        "raw_command_extra",
        b"[set {\xff}] \x00 1",
        b"invalid character \x22\x22\x0ain expression \x22[set {\xff}]  1\x22",
    ),
    (
        "tcl8.6",
        "quote_nul_eof",
        b"\x22\xff\x00tail\x22 +",
        b"missing operand at _@_\x0ain expression \x22\x22\xff_@_\x22",
    ),
    (
        "tcl8.6",
        "quote_nul_paren",
        b"\x22\xff\x00tail\x22 + )",
        b"missing operand at _@_\x0ain expression \x22\x22\xff_@_)\x22",
    ),
    (
        "tcl8.6",
        "suffix_nul_eof",
        b"0 + \x22\xff\x00tail\x22 +",
        b"missing operand at _@_\x0ain expression \x220 + \x22\xff_@_\x22",
    ),
    (
        "tcl8.6",
        "external_nul_middle",
        b"1\x00+2",
        b"invalid character \x22\x22\x0ain expression \x221+2\x22",
    ),
    (
        "tcl8.6",
        "external_nul_end",
        b"1+2\x00",
        b"invalid character \x22\x22\x0ain expression \x221+2\x22",
    ),
    (
        "tcl8.6",
        "invalid_raw_operand",
        b"1+\xff",
        b"invalid character \x22\xff\x22\x0ain expression \x221+\xff\x22",
    ),
    (
        "tcl8.6",
        "bare_raw_variable",
        b"$\xff",
        b"invalid character \x22$\x22\x0ain expression \x22$\xff\x22",
    ),
    (
        "tcl8.6",
        "unclosed_quote_raw_nul",
        b"\x22\xff\x00tail",
        b"missing \x22\x0ain expression \x22\x22\xff\x22",
    ),
    (
        "tcl8.6",
        "unclosed_brace_raw_nul",
        b"{\xff\x00tail",
        b"missing close-brace\x0ain expression \x22{\xff\x22",
    ),
    (
        "tcl8.6",
        "raw_brace_extra",
        b"{\xff} \x00 1",
        b"invalid character \x22\x22\x0ain expression \x22{\xff}  1\x22",
    ),
    (
        "tcl8.6",
        "raw_quote_extra",
        b"\x22\xff\x22 1",
        b"missing operator at _@_\x0ain expression \x22\x22\xff\x22 _@_1\x22",
    ),
    (
        "tcl8.6",
        "raw_command_extra",
        b"[set {\xff}] \x00 1",
        b"invalid character \x22\x22\x0ain expression \x22[set {\xff}]  1\x22",
    ),
    (
        "tcl9.0",
        "quote_nul_eof",
        b"\x22\xff\x00tail\x22 +",
        b"missing operand at _@_\x0ain expression \x22\x22\xff_@_\x22",
    ),
    (
        "tcl9.0",
        "quote_nul_paren",
        b"\x22\xff\x00tail\x22 + )",
        b"missing operand at _@_\x0ain expression \x22\x22\xff_@_)\x22",
    ),
    (
        "tcl9.0",
        "suffix_nul_eof",
        b"0 + \x22\xff\x00tail\x22 +",
        b"missing operand at _@_\x0ain expression \x220 + \x22\xff_@_\x22",
    ),
    (
        "tcl9.0",
        "external_nul_middle",
        b"1\x00+2",
        b"invalid character \x22\x22\x0ain expression \x221+2\x22",
    ),
    (
        "tcl9.0",
        "external_nul_end",
        b"1+2\x00",
        b"invalid character \x22\x22\x0ain expression \x221+2\x22",
    ),
    (
        "tcl9.0",
        "invalid_raw_operand",
        b"1+\xff",
        b"invalid character \x22\xff\x22\x0ain expression \x221+\xff\x22",
    ),
    (
        "tcl9.0",
        "bare_raw_variable",
        b"$\xff",
        b"invalid character \x22$\x22\x0ain expression \x22$\xff\x22",
    ),
    (
        "tcl9.0",
        "unclosed_quote_raw_nul",
        b"\x22\xff\x00tail",
        b"missing \x22\x0ain expression \x22\x22\xff\x22",
    ),
    (
        "tcl9.0",
        "unclosed_brace_raw_nul",
        b"{\xff\x00tail",
        b"missing close-brace\x0ain expression \x22{\xff\x22",
    ),
    (
        "tcl9.0",
        "raw_brace_extra",
        b"{\xff} \x00 1",
        b"invalid character \x22\x22\x0ain expression \x22{\xff}  1\x22",
    ),
    (
        "tcl9.0",
        "raw_quote_extra",
        b"\x22\xff\x22 1",
        b"missing operator at _@_\x0ain expression \x22\x22\xff\x22 _@_1\x22",
    ),
    (
        "tcl9.0",
        "raw_command_extra",
        b"[set {\xff}] \x00 1",
        b"invalid character \x22\x22\x0ain expression \x22[set {\xff}]  1\x22",
    ),
    (
        "tcl9.1",
        "quote_nul_eof",
        b"\x22\xff\x00tail\x22 +",
        b"missing operand at _@_\x0ain expression \x22\x22\xff_@_\x22",
    ),
    (
        "tcl9.1",
        "quote_nul_paren",
        b"\x22\xff\x00tail\x22 + )",
        b"missing operand at _@_\x0ain expression \x22\x22\xff_@_)\x22",
    ),
    (
        "tcl9.1",
        "suffix_nul_eof",
        b"0 + \x22\xff\x00tail\x22 +",
        b"missing operand at _@_\x0ain expression \x220 + \x22\xff_@_\x22",
    ),
    (
        "tcl9.1",
        "external_nul_middle",
        b"1\x00+2",
        b"invalid character \x22\x22\x0ain expression \x221+2\x22",
    ),
    (
        "tcl9.1",
        "external_nul_end",
        b"1+2\x00",
        b"invalid character \x22\x22\x0ain expression \x221+2\x22",
    ),
    (
        "tcl9.1",
        "invalid_raw_operand",
        b"1+\xff",
        b"invalid character \x22\xff\x22\x0ain expression \x221+\xff\x22",
    ),
    (
        "tcl9.1",
        "bare_raw_variable",
        b"$\xff",
        b"invalid character \x22$\x22\x0ain expression \x22$\xff\x22",
    ),
    (
        "tcl9.1",
        "unclosed_quote_raw_nul",
        b"\x22\xff\x00tail",
        b"missing \x22\x0ain expression \x22\x22\xff\x22",
    ),
    (
        "tcl9.1",
        "unclosed_brace_raw_nul",
        b"{\xff\x00tail",
        b"missing close-brace\x0ain expression \x22{\xff\x22",
    ),
    (
        "tcl9.1",
        "raw_brace_extra",
        b"{\xff} \x00 1",
        b"invalid character \x22\x22\x0ain expression \x22{\xff}  1\x22",
    ),
    (
        "tcl9.1",
        "raw_quote_extra",
        b"\x22\xff\x22 1",
        b"missing operator at _@_\x0ain expression \x22\x22\xff\x22 _@_1\x22",
    ),
    (
        "tcl9.1",
        "raw_command_extra",
        b"[set {\xff}] \x00 1",
        b"invalid character \x22\x22\x0ain expression \x22[set {\xff}]  1\x22",
    ),
    (
        "jim",
        "quote_nul_eof",
        b"\x22\xff\x00tail\x22 +",
        b"syntax error in expression \x22\x22\xff\x22: premature end of expression",
    ),
    (
        "jim",
        "quote_nul_paren",
        b"\x22\xff\x00tail\x22 + )",
        b"unexpected closing parenthesis in expression: \x22\x22\xff\x22",
    ),
    (
        "jim",
        "suffix_nul_eof",
        b"0 + \x22\xff\x00tail\x22 +",
        b"syntax error in expression \x220 + \x22\xff\x22: premature end of expression",
    ),
    (
        "jim",
        "external_nul_middle",
        b"1\x00+2",
        b"syntax error in expression: \x221\x22",
    ),
    (
        "jim",
        "external_nul_end",
        b"1+2\x00",
        b"syntax error in expression: \x221+2\x22",
    ),
    (
        "jim",
        "invalid_raw_operand",
        b"1+\xff",
        b"syntax error in expression: \x221+\xff\x22",
    ),
    (
        "jim",
        "unclosed_quote_raw_nul",
        b"\x22\xff\x00tail",
        b"missing quote",
    ),
    (
        "jim",
        "unclosed_brace_raw_nul",
        b"{\xff\x00tail",
        b"missing close-brace",
    ),
    (
        "jim",
        "raw_brace_extra",
        b"{\xff} \x00 1",
        b"syntax error in expression: \x22{\xff} \x22",
    ),
    (
        "jim",
        "raw_quote_extra",
        b"\x22\xff\x22 1",
        b"missing operator in expression: \x22\x22\xff\x22 1\x22",
    ),
    (
        "jim",
        "raw_command_extra",
        b"[set {\xff}] \x00 1",
        b"syntax error in expression: \x22[set {\xff}] \x22",
    ),
];

/// Engine, case, counted source, result, seeded error code and observed code.
pub type NativeExpressionSyntaxState = (
    &'static str,
    &'static str,
    &'static [u8],
    &'static [u8],
    &'static [u8],
    &'static [u8],
);

/// Original counted expression syntax failures after a seeded direct native
/// error-code state. Rows retain source, exact result and observed private code.
pub const NATIVE_EXPRESSION_SYNTAX_STATES: &[NativeExpressionSyntaxState] = &[
    (
        "tcl8.4",
        "quote_nul_eof",
        b"\"\xff\x00tail\" +",
        b"syntax error in expression \"\"\xff\": premature end of expression",
        b"PROBE BEFORE",
        b"NONE",
    ),
    (
        "tcl8.4",
        "quote_nul_paren",
        b"\"\xff\x00tail\" + )",
        b"syntax error in expression \"\"\xff\": unexpected close parenthesis",
        b"PROBE BEFORE",
        b"NONE",
    ),
    (
        "tcl8.4",
        "suffix_nul_eof",
        b"0 + \"\xff\x00tail\" +",
        b"syntax error in expression \"0 + \"\xff\": premature end of expression",
        b"PROBE BEFORE",
        b"NONE",
    ),
    (
        "tcl8.4",
        "external_nul_middle",
        b"1\x00+2",
        b"syntax error in expression \"1\": extra tokens at end of expression",
        b"PROBE BEFORE",
        b"NONE",
    ),
    (
        "tcl8.4",
        "external_nul_end",
        b"1+2\x00",
        b"syntax error in expression \"1+2\": extra tokens at end of expression",
        b"PROBE BEFORE",
        b"NONE",
    ),
    (
        "tcl8.4",
        "invalid_raw_operand",
        b"1+\xff",
        b"syntax error in expression \"1+\xff\": character not legal in expressions",
        b"PROBE BEFORE",
        b"NONE",
    ),
    (
        "tcl8.4",
        "bare_raw_variable",
        b"$\xff",
        b"syntax error in expression \"$\xff\": extra tokens at end of expression",
        b"PROBE BEFORE",
        b"NONE",
    ),
    (
        "tcl8.4",
        "unclosed_quote_raw_nul",
        b"\"\xff\x00tail",
        b"missing \"",
        b"PROBE BEFORE",
        b"NONE",
    ),
    (
        "tcl8.4",
        "unclosed_brace_raw_nul",
        b"{\xff\x00tail",
        b"missing close-brace",
        b"PROBE BEFORE",
        b"NONE",
    ),
    (
        "tcl8.4",
        "raw_brace_extra",
        b"{\xff} \x00 1",
        b"syntax error in expression \"{\xff} \": extra tokens at end of expression",
        b"PROBE BEFORE",
        b"NONE",
    ),
    (
        "tcl8.4",
        "raw_quote_extra",
        b"\"\xff\" 1",
        b"syntax error in expression \"\"\xff\" 1\": extra tokens at end of expression",
        b"PROBE BEFORE",
        b"NONE",
    ),
    (
        "tcl8.4",
        "raw_command_extra",
        b"[set {\xff}] \x00 1",
        b"syntax error in expression \"[set {\xff}] \": extra tokens at end of expression",
        b"PROBE BEFORE",
        b"NONE",
    ),
    (
        "tcl8.5",
        "quote_nul_eof",
        b"\"\xff\x00tail\" +",
        b"missing operand at _@_\x0ain expression \"\"\xff_@_\"",
        b"PROBE BEFORE",
        b"NONE",
    ),
    (
        "tcl8.5",
        "quote_nul_paren",
        b"\"\xff\x00tail\" + )",
        b"missing operand at _@_\x0ain expression \"\"\xff_@_)\"",
        b"PROBE BEFORE",
        b"NONE",
    ),
    (
        "tcl8.5",
        "suffix_nul_eof",
        b"0 + \"\xff\x00tail\" +",
        b"missing operand at _@_\x0ain expression \"0 + \"\xff_@_\"",
        b"PROBE BEFORE",
        b"NONE",
    ),
    (
        "tcl8.5",
        "external_nul_middle",
        b"1\x00+2",
        b"invalid character \"\"\x0ain expression \"1+2\"",
        b"PROBE BEFORE",
        b"NONE",
    ),
    (
        "tcl8.5",
        "external_nul_end",
        b"1+2\x00",
        b"invalid character \"\"\x0ain expression \"1+2\"",
        b"PROBE BEFORE",
        b"NONE",
    ),
    (
        "tcl8.5",
        "invalid_raw_operand",
        b"1+\xff",
        b"invalid character \"\xff\"\x0ain expression \"1+\xff\"",
        b"PROBE BEFORE",
        b"NONE",
    ),
    (
        "tcl8.5",
        "bare_raw_variable",
        b"$\xff",
        b"invalid character \"$\"\x0ain expression \"$\xff\"",
        b"PROBE BEFORE",
        b"NONE",
    ),
    (
        "tcl8.5",
        "unclosed_quote_raw_nul",
        b"\"\xff\x00tail",
        b"missing \"\x0ain expression \"\"\xff\"",
        b"PROBE BEFORE",
        b"NONE",
    ),
    (
        "tcl8.5",
        "unclosed_brace_raw_nul",
        b"{\xff\x00tail",
        b"missing close-brace\x0ain expression \"{\xff\"",
        b"PROBE BEFORE",
        b"NONE",
    ),
    (
        "tcl8.5",
        "raw_brace_extra",
        b"{\xff} \x00 1",
        b"invalid character \"\"\x0ain expression \"{\xff}  1\"",
        b"PROBE BEFORE",
        b"NONE",
    ),
    (
        "tcl8.5",
        "raw_quote_extra",
        b"\"\xff\" 1",
        b"missing operator at _@_\x0ain expression \"\"\xff\" _@_1\"",
        b"PROBE BEFORE",
        b"NONE",
    ),
    (
        "tcl8.5",
        "raw_command_extra",
        b"[set {\xff}] \x00 1",
        b"invalid character \"\"\x0ain expression \"[set {\xff}]  1\"",
        b"PROBE BEFORE",
        b"NONE",
    ),
    (
        "tcl8.6",
        "quote_nul_eof",
        b"\"\xff\x00tail\" +",
        b"missing operand at _@_\x0ain expression \"\"\xff_@_\"",
        b"TCL PARSE EXPR MISSING",
        b"TCL PARSE EXPR MISSING",
    ),
    (
        "tcl8.6",
        "quote_nul_paren",
        b"\"\xff\x00tail\" + )",
        b"missing operand at _@_\x0ain expression \"\"\xff_@_)\"",
        b"TCL PARSE EXPR MISSING",
        b"TCL PARSE EXPR MISSING",
    ),
    (
        "tcl8.6",
        "suffix_nul_eof",
        b"0 + \"\xff\x00tail\" +",
        b"missing operand at _@_\x0ain expression \"0 + \"\xff_@_\"",
        b"TCL PARSE EXPR MISSING",
        b"TCL PARSE EXPR MISSING",
    ),
    (
        "tcl8.6",
        "external_nul_middle",
        b"1\x00+2",
        b"invalid character \"\"\x0ain expression \"1+2\"",
        b"TCL PARSE EXPR BADCHAR",
        b"TCL PARSE EXPR BADCHAR",
    ),
    (
        "tcl8.6",
        "external_nul_end",
        b"1+2\x00",
        b"invalid character \"\"\x0ain expression \"1+2\"",
        b"TCL PARSE EXPR BADCHAR",
        b"TCL PARSE EXPR BADCHAR",
    ),
    (
        "tcl8.6",
        "invalid_raw_operand",
        b"1+\xff",
        b"invalid character \"\xff\"\x0ain expression \"1+\xff\"",
        b"TCL PARSE EXPR BADCHAR",
        b"TCL PARSE EXPR BADCHAR",
    ),
    (
        "tcl8.6",
        "bare_raw_variable",
        b"$\xff",
        b"invalid character \"$\"\x0ain expression \"$\xff\"",
        b"TCL PARSE EXPR BADCHAR",
        b"TCL PARSE EXPR BADCHAR",
    ),
    (
        "tcl8.6",
        "unclosed_quote_raw_nul",
        b"\"\xff\x00tail",
        b"missing \"\x0ain expression \"\"\xff\"",
        b"TCL PARSE EXPR UNBALANCED",
        b"TCL PARSE EXPR UNBALANCED",
    ),
    (
        "tcl8.6",
        "unclosed_brace_raw_nul",
        b"{\xff\x00tail",
        b"missing close-brace\x0ain expression \"{\xff\"",
        b"TCL PARSE EXPR UNBALANCED",
        b"TCL PARSE EXPR UNBALANCED",
    ),
    (
        "tcl8.6",
        "raw_brace_extra",
        b"{\xff} \x00 1",
        b"invalid character \"\"\x0ain expression \"{\xff}  1\"",
        b"TCL PARSE EXPR BADCHAR",
        b"TCL PARSE EXPR BADCHAR",
    ),
    (
        "tcl8.6",
        "raw_quote_extra",
        b"\"\xff\" 1",
        b"missing operator at _@_\x0ain expression \"\"\xff\" _@_1\"",
        b"TCL PARSE EXPR MISSING",
        b"TCL PARSE EXPR MISSING",
    ),
    (
        "tcl8.6",
        "raw_command_extra",
        b"[set {\xff}] \x00 1",
        b"invalid character \"\"\x0ain expression \"[set {\xff}]  1\"",
        b"TCL PARSE EXPR BADCHAR",
        b"TCL PARSE EXPR BADCHAR",
    ),
    (
        "tcl9.0",
        "quote_nul_eof",
        b"\"\xff\x00tail\" +",
        b"missing operand at _@_\x0ain expression \"\"\xff_@_\"",
        b"TCL PARSE EXPR MISSING",
        b"TCL PARSE EXPR MISSING",
    ),
    (
        "tcl9.0",
        "quote_nul_paren",
        b"\"\xff\x00tail\" + )",
        b"missing operand at _@_\x0ain expression \"\"\xff_@_)\"",
        b"TCL PARSE EXPR MISSING",
        b"TCL PARSE EXPR MISSING",
    ),
    (
        "tcl9.0",
        "suffix_nul_eof",
        b"0 + \"\xff\x00tail\" +",
        b"missing operand at _@_\x0ain expression \"0 + \"\xff_@_\"",
        b"TCL PARSE EXPR MISSING",
        b"TCL PARSE EXPR MISSING",
    ),
    (
        "tcl9.0",
        "external_nul_middle",
        b"1\x00+2",
        b"invalid character \"\"\x0ain expression \"1+2\"",
        b"TCL PARSE EXPR BADCHAR",
        b"TCL PARSE EXPR BADCHAR",
    ),
    (
        "tcl9.0",
        "external_nul_end",
        b"1+2\x00",
        b"invalid character \"\"\x0ain expression \"1+2\"",
        b"TCL PARSE EXPR BADCHAR",
        b"TCL PARSE EXPR BADCHAR",
    ),
    (
        "tcl9.0",
        "invalid_raw_operand",
        b"1+\xff",
        b"invalid character \"\xff\"\x0ain expression \"1+\xff\"",
        b"TCL PARSE EXPR BADCHAR",
        b"TCL PARSE EXPR BADCHAR",
    ),
    (
        "tcl9.0",
        "bare_raw_variable",
        b"$\xff",
        b"invalid character \"$\"\x0ain expression \"$\xff\"",
        b"TCL PARSE EXPR BADCHAR",
        b"TCL PARSE EXPR BADCHAR",
    ),
    (
        "tcl9.0",
        "unclosed_quote_raw_nul",
        b"\"\xff\x00tail",
        b"missing \"\x0ain expression \"\"\xff\"",
        b"TCL PARSE EXPR UNBALANCED",
        b"TCL PARSE EXPR UNBALANCED",
    ),
    (
        "tcl9.0",
        "unclosed_brace_raw_nul",
        b"{\xff\x00tail",
        b"missing close-brace\x0ain expression \"{\xff\"",
        b"TCL PARSE EXPR UNBALANCED",
        b"TCL PARSE EXPR UNBALANCED",
    ),
    (
        "tcl9.0",
        "raw_brace_extra",
        b"{\xff} \x00 1",
        b"invalid character \"\"\x0ain expression \"{\xff}  1\"",
        b"TCL PARSE EXPR BADCHAR",
        b"TCL PARSE EXPR BADCHAR",
    ),
    (
        "tcl9.0",
        "raw_quote_extra",
        b"\"\xff\" 1",
        b"missing operator at _@_\x0ain expression \"\"\xff\" _@_1\"",
        b"TCL PARSE EXPR MISSING",
        b"TCL PARSE EXPR MISSING",
    ),
    (
        "tcl9.0",
        "raw_command_extra",
        b"[set {\xff}] \x00 1",
        b"invalid character \"\"\x0ain expression \"[set {\xff}]  1\"",
        b"TCL PARSE EXPR BADCHAR",
        b"TCL PARSE EXPR BADCHAR",
    ),
    (
        "tcl9.1",
        "quote_nul_eof",
        b"\"\xff\x00tail\" +",
        b"missing operand at _@_\x0ain expression \"\"\xff_@_\"",
        b"TCL PARSE EXPR MISSING",
        b"TCL PARSE EXPR MISSING",
    ),
    (
        "tcl9.1",
        "quote_nul_paren",
        b"\"\xff\x00tail\" + )",
        b"missing operand at _@_\x0ain expression \"\"\xff_@_)\"",
        b"TCL PARSE EXPR MISSING",
        b"TCL PARSE EXPR MISSING",
    ),
    (
        "tcl9.1",
        "suffix_nul_eof",
        b"0 + \"\xff\x00tail\" +",
        b"missing operand at _@_\x0ain expression \"0 + \"\xff_@_\"",
        b"TCL PARSE EXPR MISSING",
        b"TCL PARSE EXPR MISSING",
    ),
    (
        "tcl9.1",
        "external_nul_middle",
        b"1\x00+2",
        b"invalid character \"\"\x0ain expression \"1+2\"",
        b"TCL PARSE EXPR BADCHAR",
        b"TCL PARSE EXPR BADCHAR",
    ),
    (
        "tcl9.1",
        "external_nul_end",
        b"1+2\x00",
        b"invalid character \"\"\x0ain expression \"1+2\"",
        b"TCL PARSE EXPR BADCHAR",
        b"TCL PARSE EXPR BADCHAR",
    ),
    (
        "tcl9.1",
        "invalid_raw_operand",
        b"1+\xff",
        b"invalid character \"\xff\"\x0ain expression \"1+\xff\"",
        b"TCL PARSE EXPR BADCHAR",
        b"TCL PARSE EXPR BADCHAR",
    ),
    (
        "tcl9.1",
        "bare_raw_variable",
        b"$\xff",
        b"invalid character \"$\"\x0ain expression \"$\xff\"",
        b"TCL PARSE EXPR BADCHAR",
        b"TCL PARSE EXPR BADCHAR",
    ),
    (
        "tcl9.1",
        "unclosed_quote_raw_nul",
        b"\"\xff\x00tail",
        b"missing \"\x0ain expression \"\"\xff\"",
        b"TCL PARSE EXPR UNBALANCED",
        b"TCL PARSE EXPR UNBALANCED",
    ),
    (
        "tcl9.1",
        "unclosed_brace_raw_nul",
        b"{\xff\x00tail",
        b"missing close-brace\x0ain expression \"{\xff\"",
        b"TCL PARSE EXPR UNBALANCED",
        b"TCL PARSE EXPR UNBALANCED",
    ),
    (
        "tcl9.1",
        "raw_brace_extra",
        b"{\xff} \x00 1",
        b"invalid character \"\"\x0ain expression \"{\xff}  1\"",
        b"TCL PARSE EXPR BADCHAR",
        b"TCL PARSE EXPR BADCHAR",
    ),
    (
        "tcl9.1",
        "raw_quote_extra",
        b"\"\xff\" 1",
        b"missing operator at _@_\x0ain expression \"\"\xff\" _@_1\"",
        b"TCL PARSE EXPR MISSING",
        b"TCL PARSE EXPR MISSING",
    ),
    (
        "tcl9.1",
        "raw_command_extra",
        b"[set {\xff}] \x00 1",
        b"invalid character \"\"\x0ain expression \"[set {\xff}]  1\"",
        b"TCL PARSE EXPR BADCHAR",
        b"TCL PARSE EXPR BADCHAR",
    ),
    (
        "jim",
        "quote_nul_eof",
        b"\"\xff\x00tail\" +",
        b"syntax error in expression \"\"\xff\": premature end of expression",
        b"PROBE BEFORE",
        b"PROBE BEFORE",
    ),
    (
        "jim",
        "quote_nul_paren",
        b"\"\xff\x00tail\" + )",
        b"unexpected closing parenthesis in expression: \"\"\xff\"",
        b"PROBE BEFORE",
        b"PROBE BEFORE",
    ),
    (
        "jim",
        "suffix_nul_eof",
        b"0 + \"\xff\x00tail\" +",
        b"syntax error in expression \"0 + \"\xff\": premature end of expression",
        b"PROBE BEFORE",
        b"PROBE BEFORE",
    ),
    (
        "jim",
        "external_nul_middle",
        b"1\x00+2",
        b"syntax error in expression: \"1\"",
        b"PROBE BEFORE",
        b"PROBE BEFORE",
    ),
    (
        "jim",
        "external_nul_end",
        b"1+2\x00",
        b"syntax error in expression: \"1+2\"",
        b"PROBE BEFORE",
        b"PROBE BEFORE",
    ),
    (
        "jim",
        "invalid_raw_operand",
        b"1+\xff",
        b"syntax error in expression: \"1+\xff\"",
        b"PROBE BEFORE",
        b"PROBE BEFORE",
    ),
    (
        "jim",
        "unclosed_quote_raw_nul",
        b"\"\xff\x00tail",
        b"missing quote",
        b"PROBE BEFORE",
        b"PROBE BEFORE",
    ),
    (
        "jim",
        "unclosed_brace_raw_nul",
        b"{\xff\x00tail",
        b"missing close-brace",
        b"PROBE BEFORE",
        b"PROBE BEFORE",
    ),
    (
        "jim",
        "raw_brace_extra",
        b"{\xff} \x00 1",
        b"syntax error in expression: \"{\xff} \"",
        b"PROBE BEFORE",
        b"PROBE BEFORE",
    ),
    (
        "jim",
        "raw_quote_extra",
        b"\"\xff\" 1",
        b"missing operator in expression: \"\"\xff\" 1\"",
        b"PROBE BEFORE",
        b"PROBE BEFORE",
    ),
    (
        "jim",
        "raw_command_extra",
        b"[set {\xff}] \x00 1",
        b"syntax error in expression: \"[set {\xff}] \"",
        b"PROBE BEFORE",
        b"PROBE BEFORE",
    ),
];
