#!/usr/bin/env python3
"""Generate editor catalog files from the command registry.

Reads the registry and emits:
  - editors/zed/src/generated/tcl_commands.json
  - editors/zed/src/generated/irule_events.json
  - editors/vscode/src/generated/iruleEvents.json

Usage:
    python scripts/generate_catalogs.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

# Add project root to path.
sys.path.insert(0, str(Path(__file__).parent.parent))


def _tcl_commands_catalog() -> dict:
    """Generate a JSON catalog of Tcl commands."""
    from core.commands.registry import REGISTRY

    commands = []
    for name in sorted(REGISTRY.command_names()):
        spec = REGISTRY.get_any(name)
        if spec is None:
            continue
        entry: dict = {"name": name}
        if spec.hover:
            entry["summary"] = spec.hover.summary
        if spec.subcommands:
            entry["subcommands"] = sorted(spec.subcommands.keys())
        if spec.pure:
            entry["pure"] = True
        commands.append(entry)

    return {
        "__generated": "DO NOT EDIT — generated by scripts/generate_catalogs.py",
        "commands": commands,
    }


def _irule_events_catalog() -> dict:
    """Generate a JSON catalog of iRules events."""
    from core.commands.registry import REGISTRY

    when_values = REGISTRY.argument_values("when", 0, "f5-irules")
    events = sorted(v.value for v in when_values if v.value)

    return {
        "__generated": "DO NOT EDIT — generated by scripts/generate_catalogs.py",
        "events": events,
    }


def _vscode_irule_events_catalog() -> dict:
    """Generate a JSON catalog of iRules events for VS Code.

    Includes event descriptions, flags (common/hot/deprecated), and
    ordering so the VS Code extension doesn't need hardcoded lists.
    """
    from core.commands.registry.namespace_data import EVENT_DESCRIPTIONS, EVENT_PROPS

    events = []
    for name in sorted(EVENT_PROPS):
        props = EVENT_PROPS[name]
        entry: dict = {"name": name}
        desc = EVENT_DESCRIPTIONS.get(name)
        if desc:
            entry["description"] = desc
        if props.common:
            entry["common"] = True
        if props.hot:
            entry["hot"] = True
        if props.deprecated:
            entry["deprecated"] = True
        events.append(entry)

    return {
        "__generated": "DO NOT EDIT — generated by scripts/generate_catalogs.py",
        "events": events,
    }


def main() -> None:
    import argparse

    parser = argparse.ArgumentParser(description="Generate editor catalog files")
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=None,
        help="Override output directory (default: per-editor generated dirs)",
    )
    args = parser.parse_args()

    tcl_catalog = _tcl_commands_catalog()
    irule_catalog = _irule_events_catalog()
    vscode_events = _vscode_irule_events_catalog()

    # Emit Zed catalogs.
    zed_dir = args.output_dir or Path("editors/zed/src/generated")
    zed_dir.mkdir(parents=True, exist_ok=True)

    tcl_path = zed_dir / "tcl_commands.json"
    irule_path = zed_dir / "irule_events.json"

    tcl_path.write_text(json.dumps(tcl_catalog, indent=2) + "\n")
    irule_path.write_text(json.dumps(irule_catalog, indent=2) + "\n")

    print(f"Generated {tcl_path} ({len(tcl_catalog['commands'])} commands)")
    print(f"Generated {irule_path} ({len(irule_catalog['events'])} events)")

    # Emit VS Code catalogs.
    vscode_dir = args.output_dir or Path("editors/vscode/src/generated")
    vscode_dir.mkdir(parents=True, exist_ok=True)

    vscode_events_path = vscode_dir / "iruleEvents.json"
    vscode_events_path.write_text(json.dumps(vscode_events, indent=2) + "\n")

    common_count = sum(1 for e in vscode_events["events"] if e.get("common"))
    print(
        f"Generated {vscode_events_path} ({len(vscode_events['events'])} events, {common_count} common)"
    )


if __name__ == "__main__":
    main()
