// tcl-lsp — a language server and toolchain for Tcl
// Copyright (C) 2026 James Deucker (bitwisecook) <https://github.com/bitwisecook>
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
// SPDX-License-Identifier: AGPL-3.0-or-later

// Generated by scripts/generate_catalogs.py — run `make generate` to update.
import generatedEvents from "./generated/iruleEvents.json";

export interface IruleEventTemplate {
  name: string;
  description: string;
}

interface GeneratedEvent {
  name: string;
  description?: string;
  common?: boolean;
  hot?: boolean;
  // Lifecycle releases on the BIG-IP axis. Absent means the event never
  // reached that state; `retiredVersion` is the exclusive first release
  // without the event.
  introducedVersion?: string;
  deprecatedVersion?: string;
  retiredVersion?: string;
}

// Derive the common events list from the generated catalog.
export const COMMON_IRULE_EVENTS: readonly IruleEventTemplate[] = (
  generatedEvents.events as GeneratedEvent[]
)
  .filter((e) => e.common)
  .map((e) => ({ name: e.name, description: e.description ?? "" }));

const EVENT_ORDER = new Map(COMMON_IRULE_EVENTS.map((entry, idx) => [entry.name, idx]));

function normaliseEventName(value: string): string {
  return value.trim().toUpperCase();
}

function sortEvents(events: readonly string[]): string[] {
  return [...events].sort((left, right) => {
    const leftOrder = EVENT_ORDER.get(left);
    const rightOrder = EVENT_ORDER.get(right);
    if (leftOrder !== undefined && rightOrder !== undefined) {
      return leftOrder - rightOrder;
    }
    if (leftOrder !== undefined) {
      return -1;
    }
    if (rightOrder !== undefined) {
      return 1;
    }
    return left.localeCompare(right);
  });
}

function uniqueEvents(events: readonly string[]): string[] {
  const seen = new Set<string>();
  const unique: string[] = [];
  for (const rawEvent of events) {
    const eventName = normaliseEventName(rawEvent);
    if (!eventName || seen.has(eventName)) {
      continue;
    }
    seen.add(eventName);
    unique.push(eventName);
  }
  return sortEvents(unique);
}

function shouldIncludeRuleInit(events: readonly string[]): boolean {
  return events.includes("RULE_INIT");
}

function buildRuleInitBlock(): string {
  return ["when RULE_INIT {", "    # TODO: one-time initialisation", "}"].join("\n");
}

function buildClientAcceptedBlock(): string {
  return [
    "when CLIENT_ACCEPTED {",
    "    set debug 0",
    "    # TODO: CLIENT_ACCEPTED handling",
    "}",
  ].join("\n");
}

function buildHttpRequestBlock(): string {
  return [
    "when HTTP_REQUEST {",
    "    set host [string tolower [HTTP::host]]",
    "    set path [HTTP::path]",
    "    set uri [HTTP::uri]",
    "",
    "    if {$debug} {",
    '        log local0.debug "HTTP_REQUEST host=$host path=$path"',
    "    }",
    "",
    "    # TODO: request handling",
    "}",
  ].join("\n");
}

function buildHttpResponseBlock(): string {
  return [
    "when HTTP_RESPONSE {",
    "    set status [HTTP::status]",
    "",
    "    if {$debug} {",
    '        log local0.debug "HTTP_RESPONSE status=$status"',
    "    }",
    "",
    "    # TODO: response handling",
    "}",
  ].join("\n");
}

function buildHttpRequestDataBlock(): string {
  return [
    "when HTTP_REQUEST_DATA {",
    "    set payload [HTTP::payload]",
    "    HTTP::release",
    "",
    "    if {$debug} {",
    '        log local0.debug "HTTP_REQUEST_DATA bytes=[string length $payload]"',
    "    }",
    "",
    "    # TODO: payload handling",
    "}",
  ].join("\n");
}

function buildHttpResponseDataBlock(): string {
  return [
    "when HTTP_RESPONSE_DATA {",
    "    set payload [HTTP::payload]",
    "    HTTP::release",
    "",
    "    if {$debug} {",
    '        log local0.debug "HTTP_RESPONSE_DATA bytes=[string length $payload]"',
    "    }",
    "",
    "    # TODO: payload handling",
    "}",
  ].join("\n");
}

function buildGenericBlock(eventName: string): string {
  return [`when ${eventName} {`, `    # TODO: ${eventName} handling`, "}"].join("\n");
}

function buildEventBlock(eventName: string, hasHttpEvents: boolean): string {
  switch (eventName) {
    case "RULE_INIT":
      return buildRuleInitBlock();
    case "CLIENT_ACCEPTED":
      return hasHttpEvents ? buildClientAcceptedBlock() : buildGenericBlock(eventName);
    case "HTTP_REQUEST":
      return buildHttpRequestBlock();
    case "HTTP_RESPONSE":
      return buildHttpResponseBlock();
    case "HTTP_REQUEST_DATA":
      return buildHttpRequestDataBlock();
    case "HTTP_RESPONSE_DATA":
      return buildHttpResponseDataBlock();
    default:
      return buildGenericBlock(eventName);
  }
}

const HTTP_EVENTS = new Set([
  "HTTP_REQUEST",
  "HTTP_RESPONSE",
  "HTTP_REQUEST_DATA",
  "HTTP_RESPONSE_DATA",
]);

function shouldIncludeClientAccepted(events: readonly string[]): boolean {
  if (events.includes("CLIENT_ACCEPTED")) {
    return false; // already present
  }
  return events.some((name) => HTTP_EVENTS.has(name));
}

export function buildIruleEventSkeleton(events: readonly string[]): string {
  const selected = uniqueEvents(events);
  if (selected.length === 0) {
    return "";
  }

  let ordered = shouldIncludeRuleInit(selected)
    ? ["RULE_INIT", ...selected.filter((name) => name !== "RULE_INIT")]
    : selected;

  const hasHttpEvents = selected.some((name) => HTTP_EVENTS.has(name));

  if (shouldIncludeClientAccepted(selected)) {
    // Insert CLIENT_ACCEPTED after RULE_INIT (if present) and before HTTP events
    const ruleInitIdx = ordered.indexOf("RULE_INIT");
    const insertIdx = ruleInitIdx >= 0 ? ruleInitIdx + 1 : 0;
    ordered = [...ordered.slice(0, insertIdx), "CLIENT_ACCEPTED", ...ordered.slice(insertIdx)];
  }

  const blocks = ordered.map((eventName) => buildEventBlock(eventName, hasHttpEvents));
  return `${blocks.join("\n\n")}\n`;
}
