ltm rule __tcl_lsp_probe_2286_r2286_20261006c_procedure_b {
proc same {} {return B}
when HTTP_REQUEST priority 102 {
    log local0. [list R2286 r2286_20261006c procedure_b [TMM::cmp_unit] [call same]]
}
}
