ltm node /Common/web1 {
    address 10.0.1.10
}
ltm node /Common/web2 {
    address 10.0.1.11
}
ltm node /Common/api1 {
    address 10.0.2.20
}
ltm pool /Common/web_pool {
    members {
        /Common/web1:80 {
            address 10.0.1.10
        }
        /Common/web2:80 {
            address 10.0.1.11
        }
    }
    monitor /Common/http
}
ltm pool /Common/api_pool {
    members {
        /Common/api1:8443 {
            address 10.0.2.20
        }
    }
    monitor /Common/https
}
ltm virtual /Common/web_vs {
    destination /Common/10.0.0.10:80
    description "www.example.com"
    ip-protocol tcp
    mask 255.255.255.255
    pool /Common/web_pool
}
ltm virtual /Common/web_secure_vs {
    destination /Common/10.0.0.10:443
    description "secure.example.com"
    ip-protocol tcp
    mask 255.255.255.255
    pool /Common/web_pool
}
ltm virtual /Common/api_vs {
    destination /Common/10.0.0.20:443
    description "api.example.com"
    ip-protocol tcp
    mask 255.255.255.255
    pool /Common/api_pool
}
ltm virtual /Common/unlabelled_vs {
    destination /Common/10.0.0.30:443
    ip-protocol tcp
    pool /Common/api_pool
}
