ltm rule __tcl_lsp_probe_dyn_o_when_in_httpreq_var {
when HTTP_REQUEST {
  set s "when HTTP_RESPONSE \{ log local0. \"DYNEVT resp\" \}"
  if {[catch {uplevel #0 $s} e]} {
    log local0. "DYN o_when_in_httpreq_var register=FAIL err=$e"
  } else {
    log local0. "DYN o_when_in_httpreq_var register=OK"
  }
  HTTP::respond 200 content "o done\n"
}
}
