#!/usr/bin/env python3
"""Classify Tcl 9 WASM-sweep failures into incompatible-by-design buckets.

Reads the report written by ``run_tcl9_wasm_core.py``
(``tmp/tcl9-wasm-core-report.json``) and, for every failing test ID,
extracts that test's source body from the upstream ``.test`` file and
scans it for markers that prove the test depends on something the WASM
runtime cannot — and is not meant to — reproduce:

* the interpreter's internal object representation / refcounts
  (``::tcl::unsupported::representation``, ``testobj``-family hooks),
* generated bytecode shape / disassembly
  (``::tcl::unsupported::disassemble`` / ``assemble``, ``info
  cmdcount``, bytecode-relative ``info frame`` line tables),
* C-test extension commands (``tcl::test``, ``testparser``, …).

These are the ``W9-internal`` class from the WASM bucket dictionary —
they belong in a per-stem TOML's ``just_to_match_ctcl`` bucket, never
in ``must_pass``.  Everything else is left in ``[failing]`` because a
divergence there is a *real* mismatch: error-string wording and stack
traces are expected to match C Tcl byte-for-byte, so those failures are
runtime bugs to fix, not noise to skip.

Usage::

    python scripts/dev/classify_tcl9_wasm_failures.py            # print summary
    python scripts/dev/classify_tcl9_wasm_failures.py --json     # machine-readable
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
TESTS_DIR = REPO_ROOT / "tmp" / "tcl9.0.3" / "tests"
REPORT = REPO_ROOT / "tmp" / "tcl9-wasm-core-report.json"

# Markers that mark a single test as depending on the interpreter's
# internal data structures or the generated bytecode.  Matched
# case-insensitively against the test's extracted *body*.  Kept to
# precise command forms only — bare words like ``refcount`` or
# ``representation`` appear in upstream test *titles* (e.g.
# ``encoding-2.1 {Tcl_FreeEncoding: refcount == 0}`` whose body is an
# ordinary ``encoding convertto``) and would mis-bucket a real
# behaviour mismatch as incompatible-by-design.
W9_INTERNAL_MARKERS = (
    "::tcl::unsupported::representation",
    "tcl::unsupported::representation",
    "::tcl::unsupported::disassemble",
    "tcl::unsupported::disassemble",
    "::tcl::unsupported::assemble",
    "tcl::unsupported::assemble",
    "info cmdcount",
    "testobj",
    "testbytestring",
    "testexprparser",
    "testparser",
    "testevalex",
    "testdoubleobj",
    "testintobj",
    "testlistobj",
    "testbignumobj",
    "tcl::test",
)

# ``info frame`` is its own marker: the upstream tests assert absolute
# source-file line numbers driven by the bytecode line table, which a
# whole-bundle WASM compile cannot reproduce.
INFO_FRAME_RE = re.compile(r"info\s+frame")


def _extract_test_body(text: str, test_id: str) -> str | None:
    """Return the source region for *test_id*, or None if not found.

    tcltest declarations start at column 0 with ``test <id> ``.  The
    region runs to the next column-0 ``test `` declaration (or EOF),
    which is a superset of the single test but never bleeds across more
    than one — good enough for marker detection.
    """
    pat = re.compile(rf"^test {re.escape(test_id)}[ \t{{]", re.MULTILINE)
    m = pat.search(text)
    if m is None:
        return None
    start = m.start()
    nxt = re.compile(r"^test ", re.MULTILINE).search(text, m.end())
    end = nxt.start() if nxt else len(text)
    return text[start:end]


def _is_w9_internal(body: str) -> str | None:
    """Return the matching marker if *body* is internal-by-design."""
    low = body.lower()
    for marker in W9_INTERNAL_MARKERS:
        if marker in low:
            return marker
    if INFO_FRAME_RE.search(low):
        return "info frame"
    return None


def classify() -> dict[str, dict]:
    if not REPORT.exists():
        sys.exit(f"report not found: {REPORT} — run run_tcl9_wasm_core.py first")
    rows = json.loads(REPORT.read_text())["rows"]
    out: dict[str, dict] = {}
    for row in rows:
        stem = row["stem"]
        failed_ids = row.get("failed_ids") or []
        if not failed_ids:
            continue
        test_file = TESTS_DIR / f"{stem}.test"
        if not test_file.is_file():
            continue
        try:
            text = test_file.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            text = test_file.read_text(encoding="latin-1")
        w9: dict[str, str] = {}
        real: list[str] = []
        unknown: list[str] = []
        for tid in failed_ids:
            body = _extract_test_body(text, tid)
            if body is None:
                unknown.append(tid)
                continue
            marker = _is_w9_internal(body)
            if marker:
                w9[tid] = marker
            else:
                real.append(tid)
        out[stem] = {
            "w9_internal": w9,
            "real_mismatch": real,
            "not_found": unknown,
            "total_failed": len(failed_ids),
        }
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=(__doc__ or "").splitlines()[0])
    ap.add_argument("--json", action="store_true", help="emit machine-readable JSON")
    args = ap.parse_args()
    result = classify()
    if args.json:
        print(json.dumps(result, indent=2, sort_keys=True))
        return 0
    tot_w9 = sum(len(v["w9_internal"]) for v in result.values())
    tot_real = sum(len(v["real_mismatch"]) for v in result.values())
    tot_unk = sum(len(v["not_found"]) for v in result.values())
    print(f"stems with failures: {len(result)}")
    print(f"  W9-internal (skip / just_to_match_ctcl): {tot_w9}")
    print(f"  real mismatch (error-string / stack-trace — fix): {tot_real}")
    print(f"  body not located: {tot_unk}\n")
    for stem in sorted(result, key=lambda s: -len(result[s]["w9_internal"])):
        v = result[stem]
        if not v["w9_internal"]:
            continue
        print(f"{stem}: {len(v['w9_internal'])} W9-internal of {v['total_failed']} failed")
        for tid, marker in sorted(v["w9_internal"].items()):
            print(f"    {tid:18s} ← {marker}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
