ltm pool /Common/__tcl_lsp_evtflow_egi_cross_pool {
    members {
        192.168.9.80:18703 { address 192.168.9.80 }
    }
}
ltm virtual /Common/__tcl_lsp_evtflow_egi_cross_vs {
    destination 192.168.9.24:18612
    ip-protocol tcp
    mask 255.255.255.255
    pool /Common/__tcl_lsp_evtflow_egi_cross_pool
    profiles {
        /Common/__tcl_lsp_evtflow_efe_apm_allow { }
        /Common/__tcl_lsp_evtflow_efe_clientssl_dynamic { context clientside }
        /Common/http { }
        /Common/tcp { }
        /Common/websecurity { }
    }
    rules {
        /Common/__tcl_lsp_evtflow_egi_cross_early
        /Common/__tcl_lsp_evtflow_egi_cross_security
        /Common/__tcl_lsp_evtflow_egi_cross_late
        /Common/__tcl_lsp_evtflow_efe_client_cert
        /Common/__tcl_lsp_evtflow_efe_apm_trace
    }
    source 0.0.0.0/0
    source-address-translation { type automap }
}
