"""Virtual environment creation and management.

A tclpkg virtual environment is a directory (conventionally ``.venv/``)
containing a pinned tclsh wrapper, activation scripts for multiple shells,
and a ``lib/`` directory where resolved packages are materialised.

The design mirrors Python's ``venv`` module: the user activates by
sourcing a script that prepends ``<venv>/bin`` to ``$PATH`` and sets
``$TCLLIBPATH`` to ``<venv>/lib``.  The ``tclsh`` wrapper inside
``<venv>/bin/`` always sets ``TCLLIBPATH`` so non-interactive use (CI,
Makefiles) works without activation.
"""

from __future__ import annotations

import os
import stat
import textwrap
from pathlib import Path

from core.tcl_discovery import find_tclsh

from .errors import TclPkgError


class VenvError(TclPkgError):
    """Virtual environment operation failed."""

    category = "venv"


def _resolve_tclsh(requested: str | None) -> str:
    """Find a tclsh matching *requested* (e.g. ``8.6``, ``9.0``).

    When *requested* is ``None``, picks the newest available (same logic
    as ``core.tcl_discovery.find_tclsh``).
    """
    if requested is None:
        path = find_tclsh()
        if path is None:
            raise VenvError(
                "no tclsh found on PATH",
                hint="install Tcl or specify --tcl <version>",
            )
        return path
    import shutil

    # Try the versioned name first.
    path = shutil.which(f"tclsh{requested}")
    if path:
        return path
    # Fallback to plain tclsh, but verify its version matches the request.
    path = shutil.which("tclsh")
    if path:
        actual = _tclsh_version_string(path)
        if actual and not actual.startswith(requested):
            raise VenvError(
                f"tclsh{requested} not found; plain tclsh is {actual}",
                hint=f"install Tcl {requested} or omit --tcl",
            )
        return path
    raise VenvError(
        f"tclsh{requested} not found on PATH",
        hint="install the requested Tcl version or omit --tcl",
    )


def _tclsh_version_string(tclsh_path: str) -> str:
    """Query the tclsh binary for its version string."""
    import subprocess

    try:
        result = subprocess.run(
            [tclsh_path, "-"],
            input="puts [info patchlevel]",
            capture_output=True,
            text=True,
            timeout=5,
        )
        return result.stdout.strip()
    except Exception:
        return ""


def create_venv(
    venv_path: Path,
    *,
    tcl_version: str | None = None,
    system_site_packages: bool = False,
    prompt: str | None = None,
    project_root: Path | None = None,
) -> Path:
    """Create a new tclpkg virtual environment at *venv_path*.

    Returns the absolute venv path.
    """
    venv_path = venv_path.resolve()
    if venv_path.exists():
        raise VenvError(
            f"directory already exists: {venv_path}",
            hint="use --force to overwrite or choose a different path",
        )

    tclsh = _resolve_tclsh(tcl_version)
    version_str = _tclsh_version_string(tclsh) or (tcl_version or "unknown")
    prompt_label = prompt or venv_path.name

    # Create directory structure.
    bin_dir = venv_path / "bin"
    lib_dir = venv_path / "lib"
    bin_dir.mkdir(parents=True)
    lib_dir.mkdir()

    # Write tclvenv.cfg.
    from datetime import datetime, timezone

    cfg_lines = [
        f"tcl_version = {version_str}",
        f"tcl_executable = {tclsh}",
        "venv_tool = tcl-lsp",
        f"created = {datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')}",
        f"prompt = {prompt_label}",
        f"include-system-site-packages = {'true' if system_site_packages else 'false'}",
    ]
    if project_root:
        cfg_lines.append(f"project_root = {project_root}")
    (venv_path / "tclvenv.cfg").write_text("\n".join(cfg_lines) + "\n", encoding="utf-8")

    # Write tclsh wrapper.
    _write_tclsh_wrapper(bin_dir / "tclsh", tclsh, venv_path)

    # Write activation scripts.
    _write_activate_bash(bin_dir / "activate", venv_path, prompt_label)
    _write_activate_fish(bin_dir / "activate.fish", venv_path, prompt_label)

    # Write an empty lib/pkgIndex.tcl placeholder.
    (lib_dir / "pkgIndex.tcl").write_text(
        "# Auto-generated by tclpkg — do not edit.\n"
        "# This file is regenerated by `tcl pkg install`.\n",
        encoding="utf-8",
    )

    return venv_path


def read_venv_config(venv_path: Path) -> dict[str, str]:
    """Parse ``tclvenv.cfg`` into a dict."""
    cfg_file = venv_path / "tclvenv.cfg"
    if not cfg_file.is_file():
        raise VenvError(f"not a tclpkg venv: {venv_path} (missing tclvenv.cfg)")
    result: dict[str, str] = {}
    for line in cfg_file.read_text(encoding="utf-8").splitlines():
        if "=" in line:
            key, _, value = line.partition("=")
            result[key.strip()] = value.strip()
    return result


def delete_venv(venv_path: Path) -> None:
    """Remove a virtual environment directory."""
    import shutil

    if not venv_path.is_dir():
        raise VenvError(f"venv not found: {venv_path}")
    cfg = venv_path / "tclvenv.cfg"
    if not cfg.is_file():
        raise VenvError(
            f"directory is not a tclpkg venv: {venv_path}",
            hint="missing tclvenv.cfg — refusing to delete to avoid data loss",
        )
    active = os.environ.get("TCL_VENV", "")
    if active and Path(active).resolve() == venv_path.resolve():
        raise VenvError(
            "cannot delete the currently active venv",
            hint="run 'deactivate' first or use --force",
        )
    shutil.rmtree(venv_path)


def _write_tclsh_wrapper(path: Path, tclsh: str, venv: Path) -> None:
    script = textwrap.dedent(f"""\
        #!/bin/sh
        # Auto-generated by tclpkg — do not edit.
        VENV="$(cd "$(dirname "$0")/.." && pwd)"
        : "${{TCLLIBPATH:=}}"
        export TCLLIBPATH="$VENV/lib${{TCLLIBPATH:+ $TCLLIBPATH}}"
        export TCL_VENV="$VENV"
        exec "{tclsh}" "$@"
    """)
    path.write_text(script, encoding="utf-8")
    path.chmod(path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


def _write_activate_bash(path: Path, venv: Path, prompt: str) -> None:
    script = textwrap.dedent(f"""\
        # Auto-generated by tclpkg — source this file, do not execute.
        # Usage: source {path}

        deactivate () {{
            if [ -n "${{_OLD_TCL_VENV_PATH:-}}" ]; then
                PATH="${{_OLD_TCL_VENV_PATH}}"
                export PATH
                unset _OLD_TCL_VENV_PATH
            fi
            if [ -n "${{_OLD_TCL_VENV_TCLLIBPATH:-}}" ]; then
                TCLLIBPATH="${{_OLD_TCL_VENV_TCLLIBPATH}}"
                export TCLLIBPATH
            else
                unset TCLLIBPATH
            fi
            unset _OLD_TCL_VENV_TCLLIBPATH
            if [ -n "${{_OLD_TCL_VENV_PS1:-}}" ]; then
                PS1="${{_OLD_TCL_VENV_PS1}}"
                export PS1
                unset _OLD_TCL_VENV_PS1
            fi
            unset TCL_VENV
        }}

        _OLD_TCL_VENV_PATH="$PATH"
        _OLD_TCL_VENV_TCLLIBPATH="${{TCLLIBPATH:-}}"
        _OLD_TCL_VENV_PS1="${{PS1:-}}"

        export TCL_VENV="{venv}"
        export TCLLIBPATH="{venv}/lib${{TCLLIBPATH:+ $TCLLIBPATH}}"
        export PATH="{venv}/bin:$PATH"
        PS1="({prompt}) ${{PS1:-}}"
        export PS1
    """)
    path.write_text(script, encoding="utf-8")


def _write_activate_fish(path: Path, venv: Path, prompt: str) -> None:
    script = textwrap.dedent(f"""\
        # Auto-generated by tclpkg — source this file in fish.
        # Usage: source {path}

        function deactivate
            if set -q _OLD_TCL_VENV_PATH
                set -gx PATH $_OLD_TCL_VENV_PATH
                set -e _OLD_TCL_VENV_PATH
            end
            if set -q _OLD_TCL_VENV_TCLLIBPATH
                set -gx TCLLIBPATH $_OLD_TCL_VENV_TCLLIBPATH
                set -e _OLD_TCL_VENV_TCLLIBPATH
            else
                set -e TCLLIBPATH
            end
            set -e TCL_VENV
            functions -e deactivate
        end

        set -gx _OLD_TCL_VENV_PATH $PATH
        if set -q TCLLIBPATH
            set -gx _OLD_TCL_VENV_TCLLIBPATH $TCLLIBPATH
        end

        set -gx TCL_VENV "{venv}"
        set -gx TCLLIBPATH "{venv}/lib $TCLLIBPATH"
        set -gx PATH "{venv}/bin" $PATH
    """)
    path.write_text(script, encoding="utf-8")


__all__ = ["VenvError", "create_venv", "delete_venv", "read_venv_config"]
