# tcl-lsp — a language server and toolchain for Tcl
# Copyright (C) 2026 James Deucker (bitwisecook) <https://github.com/bitwisecook>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# SPDX-License-Identifier: AGPL-3.0-or-later
# _mock_stubs.tcl -- AUTO-GENERATED from tcl-registry by `cargo xtask gen-irule-test-data`
#
# DO NOT EDIT. Regenerate with:
#   cargo xtask gen-irule-test-data
#
# The action table covers registry commands that do not have a hand-written
# mock proc in command_mocks.tcl.

namespace eval ::itest::cmd {

    # One generic fallback for registry-only commands.
    proc _stub {cat action args} {
        ::itest::log_decision $cat $action $args
        return ""
    }

    # Map: _mock_proc_name tail -> {decision category action}.
    variable _stub_actions
    array set _stub_actions {
    aaa_acct_result {aaa acct_result}
    aaa_acct_send {aaa acct_send}
    aaa_auth_result {aaa auth_result}
    aaa_auth_send {aaa auth_send}
    access2_access2_proc {access2 access2_proc}
    access_acl {access acl}
    access_disable {access disable}
    access_enable {access enable}
    access_ephemeral_auth {access ephemeral-auth}
    access_flowid {access flowid}
    access_log {access log}
    access_oauth {access oauth}
    access_perflow {access perflow}
    access_policy {access policy}
    access_respond {access respond}
    access_restrict_irule_events {access restrict_irule_events}
    access_saml {access saml}
    access_session {access session}
    access_user {access user}
    access_uuid {access uuid}
    acl_action {acl action}
    acl_eval {acl eval}
    adapt_allow {adapt allow}
    adapt_context_create {adapt context_create}
    adapt_context_current {adapt context_current}
    adapt_context_delete_all {adapt context_delete_all}
    adapt_context_name {adapt context_name}
    adapt_context_static {adapt context_static}
    adapt_enable {adapt enable}
    adapt_preview_size {adapt preview_size}
    adapt_result {adapt result}
    adapt_select {adapt select}
    adapt_service_down_action {adapt service_down_action}
    adapt_timeout {adapt timeout}
    aes_decrypt {aes decrypt}
    aes_encrypt {aes encrypt}
    aes_key {aes key}
    am_age {am age}
    am_application {am application}
    am_cache {am cache}
    am_disable {am disable}
    am_expires {am expires}
    am_media_playlist {am media_playlist}
    am_policy_node {am policy_node}
    antifraud_alert_additional_info {antifraud alert_additional_info}
    antifraud_alert_bait_signatures {antifraud alert_bait_signatures}
    antifraud_alert_component {antifraud alert_component}
    antifraud_alert_defined_value {antifraud alert_defined_value}
    antifraud_alert_details {antifraud alert_details}
    antifraud_alert_device_id {antifraud alert_device_id}
    antifraud_alert_expected_value {antifraud alert_expected_value}
    antifraud_alert_fingerprint {antifraud alert_fingerprint}
    antifraud_alert_forbidden_added_element {antifraud alert_forbidden_added_element}
    antifraud_alert_guid {antifraud alert_guid}
    antifraud_alert_html {antifraud alert_html}
    antifraud_alert_http_referrer {antifraud alert_http_referrer}
    antifraud_alert_id {antifraud alert_id}
    antifraud_alert_license_id {antifraud alert_license_id}
    antifraud_alert_min {antifraud alert_min}
    antifraud_alert_origin {antifraud alert_origin}
    antifraud_alert_resolved_value {antifraud alert_resolved_value}
    antifraud_alert_score {antifraud alert_score}
    antifraud_alert_transaction_data {antifraud alert_transaction_data}
    antifraud_alert_transaction_id {antifraud alert_transaction_id}
    antifraud_alert_type {antifraud alert_type}
    antifraud_alert_username {antifraud alert_username}
    antifraud_alert_view_id {antifraud alert_view_id}
    antifraud_client_id {antifraud client_id}
    antifraud_device_id {antifraud device_id}
    antifraud_disable {antifraud disable}
    antifraud_disable_alert {antifraud disable_alert}
    antifraud_disable_app_layer_encryption {antifraud disable_app_layer_encryption}
    antifraud_disable_auto_transactions {antifraud disable_auto_transactions}
    antifraud_disable_injection {antifraud disable_injection}
    antifraud_disable_malware {antifraud disable_malware}
    antifraud_disable_phishing {antifraud disable_phishing}
    antifraud_enable {antifraud enable}
    antifraud_enable_log {antifraud enable_log}
    antifraud_fingerprint {antifraud fingerprint}
    antifraud_geo {antifraud geo}
    antifraud_guid {antifraud guid}
    antifraud_result {antifraud result}
    antifraud_username {antifraud username}
    asm_captcha {asm captcha}
    asm_captcha_age {asm captcha_age}
    asm_captcha_status {asm captcha_status}
    asm_client_ip {asm client_ip}
    asm_conviction {asm conviction}
    asm_deception {asm deception}
    asm_disable {asm disable}
    asm_enable {asm enable}
    asm_fingerprint {asm fingerprint}
    asm_is_authenticated {asm is_authenticated}
    asm_login_status {asm login_status}
    asm_microservice {asm microservice}
    asm_payload {asm payload}
    asm_policy {asm policy}
    asm_raise {asm raise}
    asm_severity {asm severity}
    asm_signature {asm signature}
    asm_status {asm status}
    asm_support_id {asm support_id}
    asm_threat_campaign {asm threat_campaign}
    asm_unblock {asm unblock}
    asm_uncaptcha {asm uncaptcha}
    asm_username {asm username}
    asm_violation {asm violation}
    asm_violation_data {asm violation_data}
    asn1_decode {asn1 decode}
    asn1_element {asn1 element}
    asn1_encode {asn1 encode}
    auth_abort {auth abort}
    auth_authenticate {auth authenticate}
    auth_authenticate_continue {auth authenticate_continue}
    auth_cert_credential {auth cert_credential}
    auth_cert_issuer_credential {auth cert_issuer_credential}
    auth_last_event_session_id {auth last_event_session_id}
    auth_password_credential {auth password_credential}
    auth_response_data {auth response_data}
    auth_ssl_cc_ldap_status {auth ssl_cc_ldap_status}
    auth_ssl_cc_ldap_username {auth ssl_cc_ldap_username}
    auth_start {auth start}
    auth_status {auth status}
    auth_subscribe {auth subscribe}
    auth_unsubscribe {auth unsubscribe}
    auth_username_credential {auth username_credential}
    auth_wantcredential_prompt {auth wantcredential_prompt}
    auth_wantcredential_prompt_style {auth wantcredential_prompt_style}
    auth_wantcredential_type {auth wantcredential_type}
    avr_disable {avr disable}
    avr_disable_cspm_injection {avr disable_cspm_injection}
    avr_enable {avr enable}
    avr_log {avr log}
    bigproto_enable_fix_reset {bigproto enable_fix_reset}
    bigtcp_release_flow {bigtcp release_flow}
    botdefense_action {botdefense action}
    botdefense_bot_anomalies {botdefense bot_anomalies}
    botdefense_bot_categories {botdefense bot_categories}
    botdefense_bot_name {botdefense bot_name}
    botdefense_bot_signature {botdefense bot_signature}
    botdefense_bot_signature_category {botdefense bot_signature_category}
    botdefense_captcha_age {botdefense captcha_age}
    botdefense_captcha_status {botdefense captcha_status}
    botdefense_client_class {botdefense client_class}
    botdefense_client_type {botdefense client_type}
    botdefense_cookie_age {botdefense cookie_age}
    botdefense_cookie_status {botdefense cookie_status}
    botdefense_cs_allowed {botdefense cs_allowed}
    botdefense_cs_attribute {botdefense cs_attribute}
    botdefense_cs_possible {botdefense cs_possible}
    botdefense_device_id {botdefense device_id}
    botdefense_disable {botdefense disable}
    botdefense_enable {botdefense enable}
    botdefense_intent {botdefense intent}
    botdefense_micro_service {botdefense micro_service}
    botdefense_previous_action {botdefense previous_action}
    botdefense_previous_request_age {botdefense previous_request_age}
    botdefense_previous_support_id {botdefense previous_support_id}
    botdefense_reason {botdefense reason}
    botdefense_support_id {botdefense support_id}
    bwc_color {bwc color}
    bwc_debug {bwc debug}
    bwc_mark {bwc mark}
    bwc_measure {bwc measure}
    bwc_policy {bwc policy}
    bwc_pps {bwc pps}
    bwc_priority {bwc priority}
    bwc_rate {bwc rate}
    cache_accept_encoding {cache accept_encoding}
    cache_age {cache age}
    cache_disable {cache disable}
    cache_disabled {cache disabled}
    cache_enable {cache enable}
    cache_expire {cache expire}
    cache_fresh {cache fresh}
    cache_header {cache header}
    cache_headers {cache headers}
    cache_hits {cache hits}
    cache_payload {cache payload}
    cache_priority {cache priority}
    cache_statskey {cache statskey}
    cache_trace {cache trace}
    cache_uri {cache uri}
    cache_useragent {cache useragent}
    cache_userkey {cache userkey}
    category_analytics {category analytics}
    category_filetype {category filetype}
    category_lookup {category lookup}
    category_matchtype {category matchtype}
    category_result {category result}
    category_safesearch {category safesearch}
    classification_app {classification app}
    classification_category {classification category}
    classification_disable {classification disable}
    classification_enable {classification enable}
    classification_protocol {classification protocol}
    classification_result {classification result}
    classification_urlcat {classification urlcat}
    classification_username {classification username}
    classify_application {classify application}
    classify_category {classify category}
    classify_defer {classify defer}
    classify_disable {classify disable}
    classify_urlcat {classify urlcat}
    classify_username {classify username}
    cmd_accumulate {toplevel accumulate}
    cmd_active_members {toplevel active_members}
    cmd_active_nodes {toplevel active_nodes}
    cmd_append {toplevel append}
    cmd_array {toplevel array}
    cmd_b64decode {toplevel b64decode}
    cmd_b64encode {toplevel b64encode}
    cmd_binary {toplevel binary}
    cmd_break {toplevel break}
    cmd_call {toplevel call}
    cmd_catch {toplevel catch}
    cmd_check {toplevel check}
    cmd_client_addr {toplevel client_addr}
    cmd_client_port {toplevel client_port}
    cmd_clientside {toplevel clientside}
    cmd_clock {toplevel clock}
    cmd_clone {toplevel clone}
    cmd_close {toplevel close}
    cmd_concat {toplevel concat}
    cmd_connect {toplevel connect}
    cmd_continue {toplevel continue}
    cmd_cpu {toplevel cpu}
    cmd_crc32 {toplevel crc32}
    cmd_decode_uri {toplevel decode_uri}
    cmd_domain {toplevel domain}
    cmd_encoding {toplevel encoding}
    cmd_error {toplevel error}
    cmd_eval {toplevel eval}
    cmd_expr {toplevel expr}
    cmd_fasthash {toplevel fasthash}
    cmd_findclass {toplevel findclass}
    cmd_findstr {toplevel findstr}
    cmd_for {toplevel for}
    cmd_foreach {toplevel foreach}
    cmd_format {toplevel format}
    cmd_forward {toplevel forward}
    cmd_getfield {toplevel getfield}
    cmd_global {toplevel global}
    cmd_html_encode {toplevel html_encode}
    cmd_html_escape {toplevel html_escape}
    cmd_htmlencode {toplevel htmlencode}
    cmd_htonl {toplevel htonl}
    cmd_htons {toplevel htons}
    cmd_http_client_ip {toplevel http_client_ip}
    cmd_http_content_len_max {toplevel http_content_len_max}
    cmd_http_cookie {toplevel http_cookie}
    cmd_http_header {toplevel http_header}
    cmd_http_host {toplevel http_host}
    cmd_http_method {toplevel http_method}
    cmd_http_uri {toplevel http_uri}
    cmd_http_version {toplevel http_version}
    cmd_if {toplevel if}
    cmd_ifile {toplevel ifile}
    cmd_imid {toplevel imid}
    cmd_incr {toplevel incr}
    cmd_info {toplevel info}
    cmd_ip_addr {toplevel ip_addr}
    cmd_ip_protocol {toplevel ip_protocol}
    cmd_ip_tos {toplevel ip_tos}
    cmd_ip_ttl {toplevel ip_ttl}
    cmd_join {toplevel join}
    cmd_lappend {toplevel lappend}
    cmd_lasthop {toplevel lasthop}
    cmd_lindex {toplevel lindex}
    cmd_link_qos {toplevel link_qos}
    cmd_linsert {toplevel linsert}
    cmd_list {toplevel list}
    cmd_listen {toplevel listen}
    cmd_llength {toplevel llength}
    cmd_llookup {toplevel llookup}
    cmd_local_addr {toplevel local_addr}
    cmd_local_port {toplevel local_port}
    cmd_lrange {toplevel lrange}
    cmd_lreplace {toplevel lreplace}
    cmd_lsearch {toplevel lsearch}
    cmd_lset {toplevel lset}
    cmd_lsort {toplevel lsort}
    cmd_matchclass {toplevel matchclass}
    cmd_md4 {toplevel md4}
    cmd_md5 {toplevel md5}
    cmd_members {toplevel members}
    cmd_nexthop {toplevel nexthop}
    cmd_nodes {toplevel nodes}
    cmd_ntohl {toplevel ntohl}
    cmd_ntohs {toplevel ntohs}
    cmd_peer {toplevel peer}
    cmd_pem_dtos {toplevel pem_dtos}
    cmd_priority {toplevel priority}
    cmd_proc {toplevel proc}
    cmd_radius_authenticate {toplevel radius_authenticate}
    cmd_rateclass {toplevel rateclass}
    cmd_recv {toplevel recv}
    cmd_redirect {toplevel redirect}
    cmd_regexp {toplevel regexp}
    cmd_regsub {toplevel regsub}
    cmd_relate_client {toplevel relate_client}
    cmd_relate_server {toplevel relate_server}
    cmd_remote_addr {toplevel remote_addr}
    cmd_remote_port {toplevel remote_port}
    cmd_return {toplevel return}
    cmd_rmd160 {toplevel rmd160}
    cmd_scan {toplevel scan}
    cmd_send {toplevel send}
    cmd_server_addr {toplevel server_addr}
    cmd_server_port {toplevel server_port}
    cmd_serverside {toplevel serverside}
    cmd_session {toplevel session}
    cmd_set {toplevel set}
    cmd_sha1 {toplevel sha1}
    cmd_sha256 {toplevel sha256}
    cmd_sha384 {toplevel sha384}
    cmd_sha512 {toplevel sha512}
    cmd_sharedvar {toplevel sharedvar}
    cmd_split {toplevel split}
    cmd_string {toplevel string}
    cmd_subst {toplevel subst}
    cmd_substr {toplevel substr}
    cmd_switch {toplevel switch}
    cmd_tcpdump {toplevel tcpdump}
    cmd_timing {toplevel timing}
    cmd_trace {toplevel trace}
    cmd_traffic_group {toplevel traffic_group}
    cmd_translate {toplevel translate}
    cmd_uniq_ordered_ip_list {toplevel uniq_ordered_ip_list}
    cmd_uniq_sorted_ip_list {toplevel uniq_sorted_ip_list}
    cmd_unset {toplevel unset}
    cmd_uplevel {toplevel uplevel}
    cmd_upvar {toplevel upvar}
    cmd_urlcatblindquery {toplevel urlcatblindquery}
    cmd_urlcatquery {toplevel urlcatquery}
    cmd_use {toplevel use}
    cmd_variable {toplevel variable}
    cmd_vlan_id {toplevel vlan_id}
    cmd_when {toplevel when}
    cmd_whereis {toplevel whereis}
    cmd_while {toplevel while}
    cmd_xff_list {toplevel xff_list}
    cmd_xff_uniq_ordered_ip_list {toplevel xff_uniq_ordered_ip_list}
    cmd_xff_uniq_sorted_ip_list {toplevel xff_uniq_sorted_ip_list}
    compress_buffer_size {compress buffer_size}
    compress_disable {compress disable}
    compress_enable {compress enable}
    compress_gzip {compress gzip}
    compress_method {compress method}
    compress_nodelay {compress nodelay}
    connector_disable {connector disable}
    connector_enable {connector enable}
    connector_profile {connector profile}
    connector_remap {connector remap}
    crypto_decrypt {crypto decrypt}
    crypto_encrypt {crypto encrypt}
    crypto_hash {crypto hash}
    crypto_keygen {crypto keygen}
    crypto_sign {crypto sign}
    crypto_verify {crypto verify}
    datagram_dns {datagram dns}
    datagram_ip {datagram ip}
    datagram_ip6 {datagram ip6}
    datagram_l2 {datagram l2}
    datagram_tcp {datagram tcp}
    datagram_udp {datagram udp}
    decompress_disable {decompress disable}
    decompress_enable {decompress enable}
    demangle_disable {demangle disable}
    demangle_enable {demangle enable}
    dhcp_version {dhcp version}
    dhcpv4_chaddr {dhcpv4 chaddr}
    dhcpv4_ciaddr {dhcpv4 ciaddr}
    dhcpv4_drop {dhcpv4 drop}
    dhcpv4_giaddr {dhcpv4 giaddr}
    dhcpv4_hlen {dhcpv4 hlen}
    dhcpv4_hops {dhcpv4 hops}
    dhcpv4_htype {dhcpv4 htype}
    dhcpv4_len {dhcpv4 len}
    dhcpv4_opcode {dhcpv4 opcode}
    dhcpv4_option {dhcpv4 option}
    dhcpv4_reject {dhcpv4 reject}
    dhcpv4_secs {dhcpv4 secs}
    dhcpv4_siaddr {dhcpv4 siaddr}
    dhcpv4_type {dhcpv4 type}
    dhcpv4_xid {dhcpv4 xid}
    dhcpv4_yiaddr {dhcpv4 yiaddr}
    dhcpv6_drop {dhcpv6 drop}
    dhcpv6_hop_count {dhcpv6 hop_count}
    dhcpv6_len {dhcpv6 len}
    dhcpv6_link_address {dhcpv6 link_address}
    dhcpv6_msg_type {dhcpv6 msg_type}
    dhcpv6_option {dhcpv6 option}
    dhcpv6_peer_address {dhcpv6 peer_address}
    dhcpv6_reject {dhcpv6 reject}
    dhcpv6_transaction_id {dhcpv6 transaction_id}
    diag_test {diag test}
    diameter_avp {diameter avp}
    diameter_command {diameter command}
    diameter_disconnect {diameter disconnect}
    diameter_drop {diameter drop}
    diameter_dynamic_route_insertion {diameter dynamic_route_insertion}
    diameter_dynamic_route_lookup {diameter dynamic_route_lookup}
    diameter_header {diameter header}
    diameter_host {diameter host}
    diameter_is_request {diameter is_request}
    diameter_is_response {diameter is_response}
    diameter_is_retransmission {diameter is_retransmission}
    diameter_length {diameter length}
    diameter_message {diameter message}
    diameter_payload {diameter payload}
    diameter_persist {diameter persist}
    diameter_realm {diameter realm}
    diameter_respond {diameter respond}
    diameter_result {diameter result}
    diameter_retransmission {diameter retransmission}
    diameter_retransmission_default {diameter retransmission_default}
    diameter_retransmission_reason {diameter retransmission_reason}
    diameter_retransmit {diameter retransmit}
    diameter_retry {diameter retry}
    diameter_route_status {diameter route_status}
    diameter_session {diameter session}
    diameter_skip_capabilities_exchange {diameter skip_capabilities_exchange}
    diameter_state {diameter state}
    dns_additional {dns additional}
    dns_authority {dns authority}
    dns_class {dns class}
    dns_disable {dns disable}
    dns_drop {dns drop}
    dns_edns0 {dns edns0}
    dns_enable {dns enable}
    dns_is_wideip {dns is_wideip}
    dns_last_act {dns last_act}
    dns_len {dns len}
    dns_log {dns log}
    dns_name {dns name}
    dns_origin {dns origin}
    dns_ptype {dns ptype}
    dns_query {dns query}
    dns_question {dns question}
    dns_rdata {dns rdata}
    dns_rpz_policy {dns rpz_policy}
    dns_rr {dns rr}
    dns_scrape {dns scrape}
    dns_tsig {dns tsig}
    dns_ttl {dns ttl}
    dns_type {dns type}
    dnsmsg_header {dnsmsg header}
    dnsmsg_record {dnsmsg record}
    dnsmsg_section {dnsmsg section}
    dosl7_disable {dosl7 disable}
    dosl7_enable {dosl7 enable}
    dosl7_health {dosl7 health}
    dosl7_is_ip_slowdown {dosl7 is_ip_slowdown}
    dosl7_is_mitigated {dosl7 is_mitigated}
    dosl7_profile {dosl7 profile}
    dosl7_slowdown {dosl7 slowdown}
    dslite_remote_addr {dslite remote_addr}
    eca_client_machine_name {eca client_machine_name}
    eca_disable {eca disable}
    eca_domainname {eca domainname}
    eca_enable {eca enable}
    eca_select {eca select}
    eca_status {eca status}
    eca_username {eca username}
    fix_tag {fix tag}
    flow_create_related {flow create_related}
    flow_idle_duration {flow idle_duration}
    flow_idle_timeout {flow idle_timeout}
    flow_peer {flow peer}
    flow_priority {flow priority}
    flow_refresh {flow refresh}
    flow_this {flow this}
    flowtable_count {flowtable count}
    flowtable_limit {flowtable limit}
    ftp_allow_active_mode {ftp allow_active_mode}
    ftp_disable {ftp disable}
    ftp_enable {ftp enable}
    ftp_enforce_tls_session_reuse {ftp enforce_tls_session_reuse}
    ftp_ftps_mode {ftp ftps_mode}
    ftp_port {ftp port}
    genericmessage_message {genericmessage message}
    genericmessage_peer {genericmessage peer}
    genericmessage_route {genericmessage route}
    gtp_clone {gtp clone}
    gtp_discard {gtp discard}
    gtp_forward {gtp forward}
    gtp_header {gtp header}
    gtp_ie {gtp ie}
    gtp_length {gtp length}
    gtp_message {gtp message}
    gtp_new {gtp new}
    gtp_parse {gtp parse}
    gtp_payload {gtp payload}
    gtp_respond {gtp respond}
    gtp_tunnel {gtp tunnel}
    ha_status {ha status}
    hsl_open {hsl open}
    hsl_send {hsl send}
    html_comment {html comment}
    html_disable {html disable}
    html_enable {html enable}
    html_encode {html encode}
    html_tag {html tag}
    http2_active {http2 active}
    http2_concurrency {http2 concurrency}
    http2_disable {http2 disable}
    http2_disconnect {http2 disconnect}
    http2_enable {http2 enable}
    http2_push {http2 push}
    http2_requests {http2 requests}
    http2_version {http2 version}
    http_passthrough_reason {http passthrough_reason}
    http_password {http password}
    http_proxy {http proxy}
    http_reject_reason {http reject_reason}
    http_response {http response}
    http_username {http username}
    httplog_disable {httplog disable}
    httplog_enable {httplog enable}
    icap_header {icap header}
    icap_method {icap method}
    icap_status {icap status}
    icap_uri {icap uri}
    ike_auth_success {ike auth_success}
    ike_cert {ike cert}
    ike_san_dirname {ike san_dirname}
    ike_san_dns {ike san_dns}
    ike_san_ediparty {ike san_ediparty}
    ike_san_email {ike san_email}
    ike_san_ipadd {ike san_ipadd}
    ike_san_othername {ike san_othername}
    ike_san_rid {ike san_rid}
    ike_san_uri {ike san_uri}
    ike_san_x400 {ike san_x400}
    ike_subjectAltName {ike subjectAltName}
    ilx_call {ilx call}
    ilx_init {ilx init}
    ilx_notify {ilx notify}
    imap_activation_mode {imap activation_mode}
    imap_disable {imap disable}
    imap_enable {imap enable}
    ip_addr {ip addr}
    ip_hops {ip hops}
    ip_idle_timeout {ip idle_timeout}
    ip_ingress_drop_rate {ip ingress_drop_rate}
    ip_ingress_rate_limit {ip ingress_rate_limit}
    ip_intelligence {ip intelligence}
    ip_reputation {ip reputation}
    ip_stats {ip stats}
    ip_version {ip version}
    ipfix_destination {ipfix destination}
    ipfix_msg {ipfix msg}
    ipfix_template {ipfix template}
    isession_deduplication {isession deduplication}
    istats_get {istats get}
    istats_incr {istats incr}
    istats_remove {istats remove}
    istats_set {istats set}
    ivs_entry_result {ivs_entry result}
    json_array {json array}
    json_create {json create}
    json_get {json get}
    json_object {json object}
    json_parse {json parse}
    json_render {json render}
    json_root {json root}
    json_set {json set}
    json_type {json type}
    l7check_protocol {l7check protocol}
    lb_bias {lb bias}
    lb_class {lb class}
    lb_command {lb command}
    lb_connect {lb connect}
    lb_connlimit {lb connlimit}
    lb_context_id {lb context_id}
    lb_down {lb down}
    lb_dst_tag {lb dst_tag}
    lb_enable_decisionlog {lb enable_decisionlog}
    lb_mode {lb mode}
    lb_persist {lb persist}
    lb_prime {lb prime}
    lb_queue {lb queue}
    lb_snat {lb snat}
    lb_src_tag {lb src_tag}
    lb_up {lb up}
    ldap_activation_mode {ldap activation_mode}
    ldap_disable {ldap disable}
    ldap_enable {ldap enable}
    line_get {line get}
    line_set {line set}
    link_lasthop {link lasthop}
    link_nexthop {link nexthop}
    link_qos {link qos}
    link_vlan_id {link vlan_id}
    lsn_address {lsn address}
    lsn_disable {lsn disable}
    lsn_inbound {lsn inbound}
    lsn_inbound_entry {lsn inbound-entry}
    lsn_persistence {lsn persistence}
    lsn_persistence_entry {lsn persistence-entry}
    lsn_pool {lsn pool}
    lsn_port {lsn port}
    message_field {message field}
    message_proto {message proto}
    message_type {message type}
    mqtt_clean_session {mqtt clean_session}
    mqtt_client_id {mqtt client_id}
    mqtt_collect {mqtt collect}
    mqtt_disable {mqtt disable}
    mqtt_disconnect {mqtt disconnect}
    mqtt_drop {mqtt drop}
    mqtt_dup {mqtt dup}
    mqtt_enable {mqtt enable}
    mqtt_insert {mqtt insert}
    mqtt_keep_alive {mqtt keep_alive}
    mqtt_length {mqtt length}
    mqtt_message {mqtt message}
    mqtt_packet_id {mqtt packet_id}
    mqtt_password {mqtt password}
    mqtt_payload {mqtt payload}
    mqtt_protocol_name {mqtt protocol_name}
    mqtt_protocol_version {mqtt protocol_version}
    mqtt_qos {mqtt qos}
    mqtt_release {mqtt release}
    mqtt_replace {mqtt replace}
    mqtt_respond {mqtt respond}
    mqtt_retain {mqtt retain}
    mqtt_return_code {mqtt return_code}
    mqtt_return_code_list {mqtt return_code_list}
    mqtt_session_present {mqtt session_present}
    mqtt_topic {mqtt topic}
    mqtt_type {mqtt type}
    mqtt_username {mqtt username}
    mqtt_will {mqtt will}
    mr_always_match_port {mr always_match_port}
    mr_available_for_routing {mr available_for_routing}
    mr_collect {mr collect}
    mr_connect_back_port {mr connect_back_port}
    mr_connection_instance {mr connection_instance}
    mr_connection_mode {mr connection_mode}
    mr_equivalent_transport {mr equivalent_transport}
    mr_flow_id {mr flow_id}
    mr_ignore_peer_port {mr ignore_peer_port}
    mr_instance {mr instance}
    mr_max_retries {mr max_retries}
    mr_message {mr message}
    mr_payload {mr payload}
    mr_peer {mr peer}
    mr_prime {mr prime}
    mr_protocol {mr protocol}
    mr_release {mr release}
    mr_restore {mr restore}
    mr_retry {mr retry}
    mr_return {mr return}
    mr_store {mr store}
    mr_stream {mr stream}
    mr_transport {mr transport}
    name_lookup {name lookup}
    name_response {name response}
    nsh_chain {nsh chain}
    nsh_context {nsh context}
    nsh_md1 {nsh md1}
    nsh_mocksf {nsh mocksf}
    nsh_path_id {nsh path_id}
    nsh_service_index {nsh service_index}
    ntlm_disable {ntlm disable}
    ntlm_enable {ntlm enable}
    offbox_request {offbox request}
    oneconnect_detach {oneconnect detach}
    oneconnect_label {oneconnect label}
    oneconnect_reuse {oneconnect reuse}
    oneconnect_select {oneconnect select}
    pcp_reject {pcp reject}
    pcp_request {pcp request}
    pcp_response {pcp response}
    pem_disable {pem disable}
    pem_enable {pem enable}
    pem_flow {pem flow}
    pem_session {pem session}
    pem_subscriber {pem subscriber}
    pkg_create {pkg create}
    plugin_disable {plugin disable}
    plugin_enable {plugin enable}
    policy_controls {policy controls}
    policy_names {policy names}
    policy_rules {policy rules}
    policy_targets {policy targets}
    pop3_activation_mode {pop3 activation_mode}
    pop3_disable {pop3 disable}
    pop3_enable {pop3 enable}
    profile_access {profile access}
    profile_antifraud {profile antifraud}
    profile_auth {profile auth}
    profile_avr {profile avr}
    profile_clientssl {profile clientssl}
    profile_diameter {profile diameter}
    profile_exchange {profile exchange}
    profile_exists {profile exists}
    profile_fastL4 {profile fastL4}
    profile_fasthttp {profile fasthttp}
    profile_ftp {profile ftp}
    profile_http {profile http}
    profile_httpclass {profile httpclass}
    profile_httpcompression {profile httpcompression}
    profile_list {profile list}
    profile_oneconnect {profile oneconnect}
    profile_persist {profile persist}
    profile_serverssl {profile serverssl}
    profile_stream {profile stream}
    profile_tcp {profile tcp}
    profile_tftp {profile tftp}
    profile_udp {profile udp}
    profile_vdi {profile vdi}
    profile_webacceleration {profile webacceleration}
    profile_xml {profile xml}
    protocol_inspection_disable {protocol_inspection disable}
    protocol_inspection_id {protocol_inspection id}
    psc_aaa_reporting_interval {psc aaa_reporting_interval}
    psc_attr {psc attr}
    psc_calling_id {psc calling_id}
    psc_imeisv {psc imeisv}
    psc_imsi {psc imsi}
    psc_ip_address {psc ip_address}
    psc_lease_time {psc lease_time}
    psc_policy {psc policy}
    psc_subscriber_id {psc subscriber_id}
    psc_tower_id {psc tower_id}
    psc_user_name {psc user_name}
    psm_disable {psm disable}
    psm_enable {psm enable}
    qoe_disable {qoe disable}
    qoe_enable {qoe enable}
    qoe_video {qoe video}
    radius_avp {radius avp}
    radius_code {radius code}
    radius_id {radius id}
    radius_rtdom {radius rtdom}
    radius_subscriber {radius subscriber}
    resolv_lookup {resolv lookup}
    resolver_name_lookup {resolver name_lookup}
    resolver_summarize {resolver summarize}
    rest_send {rest send}
    rewrite_disable {rewrite disable}
    rewrite_enable {rewrite enable}
    rewrite_payload {rewrite payload}
    rewrite_post_process {rewrite post_process}
    route_age {route age}
    route_bandwidth {route bandwidth}
    route_clear {route clear}
    route_cwnd {route cwnd}
    route_domain {route domain}
    route_expiration {route expiration}
    route_mtu {route mtu}
    route_rtt {route rtt}
    route_rttvar {route rttvar}
    rtsp_collect {rtsp collect}
    rtsp_header {rtsp header}
    rtsp_method {rtsp method}
    rtsp_msg_source {rtsp msg_source}
    rtsp_payload {rtsp payload}
    rtsp_release {rtsp release}
    rtsp_respond {rtsp respond}
    rtsp_status {rtsp status}
    rtsp_uri {rtsp uri}
    rtsp_version {rtsp version}
    sctp_client_port {sctp client_port}
    sctp_collect {sctp collect}
    sctp_local_port {sctp local_port}
    sctp_mss {sctp mss}
    sctp_payload {sctp payload}
    sctp_ppi {sctp ppi}
    sctp_release {sctp release}
    sctp_remote_port {sctp remote_port}
    sctp_respond {sctp respond}
    sctp_rto_initial {sctp rto_initial}
    sctp_rto_max {sctp rto_max}
    sctp_rto_min {sctp rto_min}
    sctp_sack_timeout {sctp sack_timeout}
    sctp_server_port {sctp server_port}
    sdp_field {sdp field}
    sdp_media {sdp media}
    sdp_session_id {sdp session_id}
    sip_call_id {sip call_id}
    sip_discard {sip discard}
    sip_from {sip from}
    sip_header {sip header}
    sip_message {sip message}
    sip_method {sip method}
    sip_payload {sip payload}
    sip_persist {sip persist}
    sip_record_route {sip record-route}
    sip_respond {sip respond}
    sip_response {sip response}
    sip_route {sip route}
    sip_route_status {sip route_status}
    sip_to {sip to}
    sip_uri {sip uri}
    sip_via {sip via}
    sipalg_hairpin {sipalg hairpin}
    sipalg_hairpin_default {sipalg hairpin_default}
    sipalg_nonregister_subscriber_listener {sipalg nonregister_subscriber_listener}
    smtps_activation_mode {smtps activation_mode}
    smtps_disable {smtps disable}
    smtps_enable {smtps enable}
    socks_allowed {socks allowed}
    socks_destination {socks destination}
    socks_version {socks version}
    sse_field {sse field}
    ssl_allow_dynamic_record_sizing {ssl allow_dynamic_record_sizing}
    ssl_allow_nonssl {ssl allow_nonssl}
    ssl_alpn {ssl alpn}
    ssl_authenticate {ssl authenticate}
    ssl_c3d {ssl c3d}
    ssl_cert_constraint {ssl cert_constraint}
    ssl_clientrandom {ssl clientrandom}
    ssl_collect {ssl collect}
    ssl_forward_proxy {ssl forward_proxy}
    ssl_handshake {ssl handshake}
    ssl_is_renegotiation_secure {ssl is_renegotiation_secure}
    ssl_maximum_record_size {ssl maximum_record_size}
    ssl_mode {ssl mode}
    ssl_modssl_sessionid_headers {ssl modssl_sessionid_headers}
    ssl_nextproto {ssl nextproto}
    ssl_payload {ssl payload}
    ssl_profile {ssl profile}
    ssl_release {ssl release}
    ssl_renegotiate {ssl renegotiate}
    ssl_secure_renegotiation {ssl secure_renegotiation}
    ssl_session {ssl session}
    ssl_sessionsecret {ssl sessionsecret}
    ssl_sessionticket {ssl sessionticket}
    ssl_tls13_secret {ssl tls13_secret}
    ssl_unclean_shutdown {ssl unclean_shutdown}
    ssl_verify_result {ssl verify_result}
    stats_get {stats get}
    stats_incr {stats incr}
    stats_set {stats set}
    stats_setmax {stats setmax}
    stats_setmin {stats setmin}
    stream_disable {stream disable}
    stream_enable {stream enable}
    stream_encoding {stream encoding}
    stream_expression {stream expression}
    stream_match {stream match}
    stream_max_matchsize {stream max_matchsize}
    stream_replace {stream replace}
    tap_action {tap action}
    tap_config {tap config}
    tap_insight {tap insight}
    tap_insight_requested {tap insight_requested}
    tap_score {tap score}
    tcp_abc {tcp abc}
    tcp_analytics {tcp analytics}
    tcp_autowin {tcp autowin}
    tcp_congestion {tcp congestion}
    tcp_delayed_ack {tcp delayed_ack}
    tcp_dsack {tcp dsack}
    tcp_earlyrxmit {tcp earlyrxmit}
    tcp_ecn {tcp ecn}
    tcp_enhanced_loss_recovery {tcp enhanced_loss_recovery}
    tcp_idletime {tcp idletime}
    tcp_keepalive {tcp keepalive}
    tcp_limxmit {tcp limxmit}
    tcp_lossfilter {tcp lossfilter}
    tcp_lossfilterburst {tcp lossfilterburst}
    tcp_lossfilterrate {tcp lossfilterrate}
    tcp_nagle {tcp nagle}
    tcp_naglemode {tcp naglemode}
    tcp_naglestate {tcp naglestate}
    tcp_offset {tcp offset}
    tcp_pacing {tcp pacing}
    tcp_proxybuffer {tcp proxybuffer}
    tcp_proxybufferhigh {tcp proxybufferhigh}
    tcp_proxybufferlow {tcp proxybufferlow}
    tcp_push_flag {tcp push_flag}
    tcp_rcv_scale {tcp rcv_scale}
    tcp_rcv_size {tcp rcv_size}
    tcp_recvwnd {tcp recvwnd}
    tcp_rexmt_thresh {tcp rexmt_thresh}
    tcp_rt_metrics_timeout {tcp rt_metrics_timeout}
    tcp_rto {tcp rto}
    tcp_rttvar {tcp rttvar}
    tcp_sendbuf {tcp sendbuf}
    tcp_setmss {tcp setmss}
    tcp_snd_cwnd {tcp snd_cwnd}
    tcp_snd_scale {tcp snd_scale}
    tcp_snd_ssthresh {tcp snd_ssthresh}
    tcp_snd_wnd {tcp snd_wnd}
    tcp_unused_port {tcp unused_port}
    tds_msg {tds msg}
    tds_session {tds session}
    tmm_cmp_count {tmm cmp_count}
    tmm_cmp_group {tmm cmp_group}
    tmm_cmp_groups {tmm cmp_groups}
    tmm_cmp_primary_group {tmm cmp_primary_group}
    tmm_cmp_unit {tmm cmp_unit}
    udp_client_port {udp client_port}
    udp_debug_queue {udp debug_queue}
    udp_drop {udp drop}
    udp_hold {udp hold}
    udp_local_port {udp local_port}
    udp_max_buf_pkts {udp max_buf_pkts}
    udp_max_rate {udp max_rate}
    udp_mss {udp mss}
    udp_payload {udp payload}
    udp_release {udp release}
    udp_remote_port {udp remote_port}
    udp_respond {udp respond}
    udp_sendbuffer {udp sendbuffer}
    udp_server_port {udp server_port}
    udp_unused_port {udp unused_port}
    uri_basename {uri basename}
    uri_compare {uri compare}
    uri_decode {uri decode}
    uri_encode {uri encode}
    uri_encode_component {uri encode_component}
    uri_escape {uri escape}
    uri_host {uri host}
    uri_path {uri path}
    uri_port {uri port}
    uri_protocol {uri protocol}
    uri_query {uri query}
    validate_protocol {validate protocol}
    vdi_disable {vdi disable}
    vdi_enable {vdi enable}
    wam_disable {wam disable}
    wam_enable {wam enable}
    websso_disable {websso disable}
    websso_enable {websso enable}
    websso_select {websso select}
    ws_collect {ws collect}
    ws_disconnect {ws disconnect}
    ws_enabled {ws enabled}
    ws_frame {ws frame}
    ws_masking {ws masking}
    ws_message {ws message}
    ws_payload {ws payload}
    ws_payload_ivs {ws payload_ivs}
    ws_payload_processing {ws payload_processing}
    ws_release {ws release}
    ws_request {ws request}
    ws_response {ws response}
    x509_cert_fields {x509 cert_fields}
    x509_extensions {x509 extensions}
    x509_hash {x509 hash}
    x509_issuer {x509 issuer}
    x509_not_valid_after {x509 not_valid_after}
    x509_not_valid_before {x509 not_valid_before}
    x509_pem2der {x509 pem2der}
    x509_serial_number {x509 serial_number}
    x509_signature_algorithm {x509 signature_algorithm}
    x509_subject {x509 subject}
    x509_subject_public_key {x509 subject_public_key}
    x509_subject_public_key_RSA_bits {x509 subject_public_key_RSA_bits}
    x509_subject_public_key_type {x509 subject_public_key_type}
    x509_verify_cert_error_string {x509 verify_cert_error_string}
    x509_version {x509 version}
    x509_whole {x509 whole}
    xlat_listen {xlat listen}
    xlat_listen_lifetime {xlat listen_lifetime}
    xlat_src_addr {xlat src_addr}
    xlat_src_config {xlat src_config}
    xlat_src_endpoint_reservation {xlat src_endpoint_reservation}
    xlat_src_nat_valid_range {xlat src_nat_valid_range}
    xlat_src_port {xlat src_port}
    xml_address {xml address}
    xml_collect {xml collect}
    xml_disable {xml disable}
    xml_element {xml element}
    xml_enable {xml enable}
    xml_event {xml event}
    xml_eventid {xml eventid}
    xml_parse {xml parse}
    xml_payload {xml payload}
    xml_release {xml release}
    xml_soap {xml soap}
    xml_subscribe {xml subscribe}
    }
}

# Total stub actions generated: 978
