include /workspace/tcl-lsp/tmp/tcl9.1.0/unix/Makefile
BUILD_DIR := /workspace/tcl-lsp/tmp/tcl9.1.0/unix
.PHONY: observed-execute observed-object
observed-execute:
	$(CC) -c $(CC_SWITCHES) /tmp/native-dictionary-update-lifetime398/9.1.0/observed-tclExecute.c -o /tmp/native-dictionary-update-lifetime398-capture/9.1.0/tclExecute.o
observed-object:
	$(CC) -c $(CC_SWITCHES) /tmp/native-dictionary-update-lifetime398/9.1.0/observed-tclObj.c -o /tmp/native-dictionary-update-lifetime398-capture/9.1.0/tclObj.o
