ltm policy /EVTFLOW_EFB/__tcl_lsp_evtflow_EFB_policy {
    requires { http }
    strategy /Common/first-match
    rules {
        insert_header {
            ordinal 1
            conditions {
                0 {
                    http-uri
                    path
                    starts-with
                    values { /policy }
                }
            }
            actions {
                0 {
                    http-header
                    insert
                    name X-Evtflow-Policy
                    value yes
                }
            }
        }
    }
}
