ltm profile client-ssl /EVTFLOW_EFB/__tcl_lsp_evtflow_EFB_http3_clientssl {
    defaults-from /Common/clientssl
    renegotiation disabled
}
ltm pool /EVTFLOW_EFB/__tcl_lsp_evtflow_EFB_http3_pool {
    members {
        /EVTFLOW_EFB/__tcl_lsp_evtflow_EFB_node:18603 { address 192.168.9.80 }
    }
}
ltm virtual /EVTFLOW_EFB/__tcl_lsp_evtflow_EFB_http3_vs {
    destination 192.168.9.24:18515
    ip-protocol udp
    mask 255.255.255.255
    pool /EVTFLOW_EFB/__tcl_lsp_evtflow_EFB_http3_pool
    profiles {
        /EVTFLOW_EFB/__tcl_lsp_evtflow_EFB_http3_clientssl { context clientside }
        /Common/http { }
        /Common/http3 { context clientside }
        /Common/httprouter { }
        /Common/quic { context clientside }
        /Common/udp { }
    }
    rules { /Common/__tcl_lsp_evtflow_EFB_http3_trace }
    source 0.0.0.0/0
    source-address-translation { type automap }
}
