ltm rule /Common/__tcl_lsp_evtflow_EFB_http3_trace {
    when CLIENT_ACCEPTED {
        log local0. "EVTFLOW|run=EFB|probe=http3|event=CLIENT_ACCEPTED|tmm=[TMM::cmp_group]:[TMM::cmp_unit]|client=[IP::client_addr]"
    }
    when CLIENTSSL_CLIENTHELLO {
        log local0. "EVTFLOW|run=EFB|probe=http3|event=CLIENTSSL_CLIENTHELLO|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
    when CLIENTSSL_HANDSHAKE {
        log local0. "EVTFLOW|run=EFB|probe=http3|event=CLIENTSSL_HANDSHAKE|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
    when HTTP_REQUEST {
        log local0. "EVTFLOW|run=EFB|probe=http3|event=HTTP_REQUEST|tmm=[TMM::cmp_group]:[TMM::cmp_unit]|version=[HTTP::version]|uri=[HTTP::uri]"
    }
    when HTTP_RESPONSE {
        log local0. "EVTFLOW|run=EFB|probe=http3|event=HTTP_RESPONSE|tmm=[TMM::cmp_group]:[TMM::cmp_unit]|version=[HTTP::version]|status=[HTTP::status]"
    }
}
