ltm rule /Common/__tcl_lsp_evtflow_EFB_policy_trace {
    when HTTP_REQUEST priority 100 {
        log local0. "EVTFLOW|run=EFB|probe=policy|event=HTTP_REQUEST|priority=100|header=[HTTP::header value X-Evtflow-Policy]|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
    when HTTP_REQUEST priority 900 {
        log local0. "EVTFLOW|run=EFB|probe=policy|event=HTTP_REQUEST|priority=900|header=[HTTP::header value X-Evtflow-Policy]|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
}
