ltm rule /Common/__tcl_lsp_evtflow_EFB_serverssl_trace {
    when SERVERSSL_CLIENTHELLO_SEND {
        log local0. "EVTFLOW|run=EFB|probe=tls-server|event=SERVERSSL_CLIENTHELLO_SEND|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
    when SERVERSSL_SERVERHELLO {
        log local0. "EVTFLOW|run=EFB|probe=tls-server|event=SERVERSSL_SERVERHELLO|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
    when SERVERSSL_SERVERCERT {
        log local0. "EVTFLOW|run=EFB|probe=tls-server|event=SERVERSSL_SERVERCERT|tmm=[TMM::cmp_group]:[TMM::cmp_unit]"
    }
    when SERVERSSL_HANDSHAKE {
        log local0. "EVTFLOW|run=EFB|probe=tls-server|event=SERVERSSL_HANDSHAKE|tmm=[TMM::cmp_group]:[TMM::cmp_unit]|cipher=[SSL::cipher name]|version=[SSL::cipher version]"
    }
}
