ltm rule /Common/__tcl_lsp_evtflow_efd_ssl_data {
    when RULE_INIT {
        log local0. "EVTFLOW2|run=EFD|event=RULE_INIT|tmm=[TMM::cmp_group]:[TMM::cmp_unit]|probe=ssl-data"
    }
    when CLIENTSSL_HANDSHAKE {
        log local0. "EVTFLOW2|run=EFD|event=CLIENTSSL_HANDSHAKE|tmm=[TMM::cmp_group]:[TMM::cmp_unit]|probe=ssl-data|cipher=[SSL::cipher name]"
        SSL::collect 1
    }
    when CLIENTSSL_DATA {
        binary scan [SSL::payload] H* payload_hex
        log local0. "EVTFLOW2|run=EFD|event=CLIENTSSL_DATA|tmm=[TMM::cmp_group]:[TMM::cmp_unit]|probe=ssl-data|bytes=[SSL::payload length]|hex=$payload_hex"
        SSL::release
    }
    when SERVERSSL_HANDSHAKE {
        log local0. "EVTFLOW2|run=EFD|event=SERVERSSL_HANDSHAKE|tmm=[TMM::cmp_group]:[TMM::cmp_unit]|probe=ssl-data|cipher=[SSL::cipher name]"
        SSL::collect 1
    }
    when SERVERSSL_DATA {
        binary scan [SSL::payload] H* payload_hex
        log local0. "EVTFLOW2|run=EFD|event=SERVERSSL_DATA|tmm=[TMM::cmp_group]:[TMM::cmp_unit]|probe=ssl-data|bytes=[SSL::payload length]|hex=$payload_hex"
        SSL::release
    }
}
